### PR TITLE
Update SDL2 to 2.24

### PR DESCRIPTION
**Pull request by Gnimuc**
https://github.com/JuliaPackaging/Yggdrasil/pull/5568

### CODE REVIEW

**Comment by Gnimuc** [comment]
cc @mfiano I don't have time to debug the apple aarch64 build, so I disabled that platform in this PR.

**Comment by mfiano** [comment]
> I disabled that platform in this PR

That's quite alright. Thank you again!

**Comment by Gnimuc** [comment]
This upstream issue might be related: https://github.com/libsdl-org/SDL/issues/4958

**Comment by giordano** [comment]
> That's quite alright.

I doubt users of that platform, which isn't a small fraction of Julia users, would agree.

**Comment by giordano** [comment]
Sounds like this is trying to build the joystick components for iOS when targeting aarch64-apple-darwin, which looks like wrong.

**Review by giordano — CHANGES_REQUESTED** [review]
In case it wasn't clear, someone (!= me) should investigate why the aarch64-apple-darwin build is failing (building for iOS looks suspiciously wrong to me.  ***Edit***: looking at the [build log of 2.0.20](https://github.com/JuliaBinaryWrappers/SDL2_jll.jl/releases/download/SDL2-v2.0.20%2B1/SDL2-logs.v2.0.20.aarch64-apple-darwin.tar.gz) I noticed that also back then we built the joystick component for iOS, but at least it wasn't failing, so something happened), it isn't very nice to drop support for widespread platforms, which is the reason why https://github.com/JuliaPackaging/Yggdrasil/pull/5568 wasn't merged including the upgrade to v2.24

**Review by giordano — APPROVED** [review]

**Pull request merged**
