### PR TITLE
[SSGraphBLAS] Update to 6.0.0

### PR DESCRIPTION
**Pull request by Wimmerer**
Significant upgrade to most of the library.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Failing on aarch64+musl - probably easiest to exclude that combination.

**Comment by giordano** [comment]
It's failing also on `aarch64-linux-gnu`.  I'm under the impression @Wimmerer is looking into the error.

**Comment by Wimmerer** [comment]
@giordano this is ready.

**Comment by giordano** [comment]
So the trick was simply to use GCC 7?

**Pull request merged**
