### PR TITLE
[libCEED] Bump to latest version

### PR DESCRIPTION
**Pull request by pazner**

### CODE REVIEW

**Comment by giordano** [comment]
Doesn't the version number change?

**Comment by pazner** [comment]
A new release wasn't made (no new version number), but several bugfixes were made to the main branch that are important for Julia integration.

**Comment by giordano** [comment]
I had a look at [building instructions of libCEED](https://github.com/CEED/libCEED/blob/307f1d1b76f3a034e21c54dcd8eed3f2619f0ee6/README.rst#building) and noticed that it requires manually enabling optimisation for specific microarchitectures.  We have a (_very_!) experimental support for building libraries for multiple microarchitectures, maybe you'll be interested in testing it once we get this properly working?  Note that tarballs for multiple microarchitectures will require Julia v1.6.

**Comment by pazner** [comment]
Thanks for pointing that out — indeed, that could be very interesting for me. I would also be interested in compiling with CUDA support (I believe that is related to [this issue](https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/559)) if that is possible at some point.

**Comment by giordano** [comment]
We can actually already link libraries against CUDA, but there are two issues:

1. it works only for x86_64-linux-gnu because `nvcc` isn't a cross-compiler
2. it needs to be a separate package, see for example what we do for [Darknet](https://github.com/JuliaPackaging/Yggdrasil/tree/6c6f78cede7d3ca943dc58b937d1c001fb1343fa/D/Darknet).  Unfortunately we don't have (yet?) a good mechanism to handle variants of a library in a single package

**Pull request merged**
