### PR TITLE
[sundials] Update to 5.7.0

### PR DESCRIPTION
**Pull request by ViralBShah**
Some refactoring to share code between 32 and 64-bit builds.

@jd-lara I started a new PR to be able to edit it directly here. Hope you don't mind.

### CODE REVIEW

**Comment by ViralBShah** [comment]
We have ppc support also now.

The main issue is that something in Sundials seems to have changed on windows, in how it finds libraries. But it is hard to tell from the logs what the exact link issue is. 

@giordano Any thoughts? Or guesses?

**Comment by giordano** [comment]
No idea just by looking at the compilation log, I'd need to enter the build environment to see what's going on.  However these days I'm having my fair share of fun with [building GCC](https://github.com/JuliaPackaging/Yggdrasil/pull/2301)

**Comment by ViralBShah** [comment]
That's what I figured too. I guess I will bite the bullet some time and install the full environment.

**Comment by jd-lara** [comment]
FYI, it seems that the issues with SuperluMT got fixed https://github.com/LLNL/sundials/releases/tag/v5.7.0 it might be worth to jump to 5.7

**Comment by ViralBShah** [comment]
I agree. Let's just jump to 5.7. I am closing this one.

**Comment by ViralBShah** [comment]
@jd-lara Any ideas why it can't find superlu on windows?

**Pull request closed without merging**
