### PR TITLE
[OSQP] Add MKL_PARDISO

### PR DESCRIPTION
**Pull request by jd-lara**
Testing here since this https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/742

### CODE REVIEW

**Comment by mlubin** [comment]
Have you tested this in OSQP by setting the `linsys_solver` parameter? Does it used MKL by default if it was compiled in?

**Comment by jd-lara** [comment]
@mlubin The reason for this PR is precisely because it looks like the current OSQP binaries can be built with MKL from the script in the repo https://github.com/oxfordcontrol/osqp/blob/master/ci/travis/script.sh however there is a note that this doesn't work for macOS. 

I tried to use it on my computer and got this error which confirms that the capability is there but it can't find the library. 

```
optimize!(model)
ERROR in lh_load_lib: Error while loading dynamic library libmkl_rt.dylib: dlopen(libmkl_rt.dylib, 1): image not found
ERROR in osqp_setup: Linear system solver not available.
Tried to obtain it from shared library.
ERROR: Error in OSQP setup
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] setup!(::OSQP.Model; P::SparseArrays.SparseMatrixCSC{Float64,Int64}, q::Array{Float64,1}, A::SparseArrays.SparseMatrixCSC{Float64,Int64}, l::Array{Float64,1}, u::Array{Float64,1}, settings::Base.Iterators.Pairs{Symbol,Any,Tuple{Symbol,Symbol},NamedTuple{(:verbose, :linsys_solver),Tuple{Bool,String}}}) at /Users/jdlara/.julia/packages/OSQP/BU4WO/src/interface.jl:164
 [3] copy_to(::OSQP.MathOptInterfaceOSQP.Optimizer, ::MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}; copy_names::Bool) at /Users/jdlara/.julia/packages/OSQP/BU4WO/src/MOI_wrapper.jl:151
 [4] attach_optimizer(::MathOptInterface.Utilities.CachingOptimizer{OSQP.MathOptInterfaceOSQP.Optimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}) at /Users/jdlara/.julia/packages/MathOptInterface/RmalA/src/Utilities/cachingoptimizer.jl:149
 [5] optimize!(::MathOptInterface.Utilities.CachingOptimizer{OSQP.MathOptInterfaceOSQP.Optimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}) at /Users/jdlara/.julia/packages/MathOptInterface/RmalA/src/Utilities/cachingoptimizer.jl:185
 [6] optimize!(::MathOptInterface.Bridges.LazyBridgeOptimizer{MathOptInterface.Utilities.CachingOptimizer{OSQP.MathOptInterfaceOSQP.Optimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}}) at /Users/jdlara/.julia/packages/MathOptInterface/RmalA/src/Bridges/bridge_optimizer.jl:239
 [7] optimize!(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer,MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.Model{Float64}}}) at /Users/jdlara/.julia/packages/MathOptInterface/RmalA/src/Utilities/cachingoptimizer.jl:189
 [8] optimize!(::Model, ::Nothing; bridge_constraints::Bool, ignore_optimize_hook::Bool, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /Users/jdlara/.julia/packages/JuMP/MnJQc/src/optimizer_interface.jl:131
 [9] optimize! at /Users/jdlara/.julia/packages/JuMP/MnJQc/src/optimizer_interface.jl:107 [inlined] (repeats 2 times)
 [10] top-level scope at REPL[31]:1
```

**Comment by giordano** [comment]
@jd-lara What's the value of `MKL_jll.libmkl_rt_handle`?

**Comment by jd-lara** [comment]
> @jd-lara What's the value of `MKL_jll.libmkl_rt_handle`?

Ptr{Nothing} @0x00007feff3d3a3b0

**Comment by giordano** [comment]
So the has been loaded :thinking:

**Comment by jd-lara** [comment]
> So the library has been loaded 🤔

I am looking into OSQP's code and it looks like they don't allow to manually specify the location of the library. 

https://github.com/oxfordcontrol/osqp/blob/master/lin_sys/direct/pardiso/pardiso_loader.c

**Comment by giordano** [comment]
Right, what is failing is this: https://github.com/oxfordcontrol/osqp/blob/7b33ad2c0aac71bdfc107a2ca139ee67c9addde6/lin_sys/lib_handler.c#L26-L31 not our linking to the library

**Comment by giordano** [comment]
What happens if you do
```julia
withenv(MKL_jll.LIBPATH_env => MKL_jll.LIBPATH) do
    optimize!(model)
end
```
?

**Comment by jd-lara** [comment]
> ```julia
> withenv(MKL_jll.LIBPATH_env => MKL_jll.LIBPATH) do
>     optimize!(model)
> end
> ```

Same error. Here is the MWE for this 

```Julia
using JuMP
using OSQP
using MKL_jll
using Random
opt = optimizer_with_attributes(OSQP.Optimizer, "linsys_solver" =>"mkl pardiso")
m = Model(opt)

A = rand(10,10)
@variable(m, x[1:10])
@variable(m, t[1:10])
@constraint(m, A*x .== t)
@objective(m, Min, sum(t[i]^2 for i in 1:10))

withenv(MKL_jll.LIBPATH_env => MKL_jll.LIBPATH) do
           optimize!(m)
end
```

**Comment by giordano** [comment]
If osqp tries to dlopen MKL in this way maybe we don't really need to build the library, but just to` and understand how to make libosqp find the library.

**Comment by jd-lara** [comment]
> If osqp tries to dlopen MKL in this way maybe we don't really need to build the library, but just to` and understand how to make libosqp find the library at runtime.

Agreed, we can close this until they respond to the issue I opened. This will be a problem for OSQP.jl instead. 

cc. @odow

**Comment by giordano** [comment]
Your example works for me:
```
julia> withenv(MKL_jll.LIBPATH_env => MKL_jll.LIBPATH) do
                  optimize!(m)
       end
-----------------------------------------------------------------
           OSQP v0.6.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2019
-----------------------------------------------------------------
problem:  variables n = 20, constraints m = 10
          nnz(P) + nnz(A) = 120
settings: linear system solver = mkl pardiso (4 threads),
          eps_abs = 1.0e-03, eps_rel = 1.0e-03,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 4000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: off, time_limit: off

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   0.00e+00   0.00e+00   1.00e-01   2.53e-02s
  25   0.0000e+00   0.00e+00   0.00e+00   1.00e-01   2.55e-02s

status:               solved
number of iterations: 25
optimal objective:    0.0000
run time:             2.55e-02s
optimal rho estimate: 1.00e-06
```

**Comment by giordano** [comment]
Actually, also without using `wihtenv,` I just need to load `MKL_jll` before calling `optimize!`.  But I'm on GNU/Linux, that might makes a difference

**Comment by jd-lara** [comment]
> Actually, also without using `wihtenv,` I just need to load `MKL_jll` before calling `optimize!`. But I'm on GNU/Linux, that might make a difference

In mac doesn't work

**Pull request closed without merging**
