### PR TITLE
HiGHS: build for powerpc

### PR DESCRIPTION
**Pull request by matbesancon**

### CODE REVIEW

**Comment by matbesancon** [comment]
Ok this finally worked.
Is it elegant? No.
Is this a permanent solution to the problem? No.
Did I finally understand what I was doing? Still no.

**Comment by giordano** [comment]
For the record, all the extra work for powerpc won't even be necessary with https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/749 :stuck_out_tongue:

**Comment by matbesancon** [comment]
:sob:

**Comment by matbesancon** [comment]
Closing this in favour of https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/749

**Comment by matbesancon** [comment]
re-opened, this will be failing for the moment, to merge after JuliaPackaging/BinaryBuilder.jl#749

**Comment by giordano** [comment]
We hadn't updated BinaryBuilder here yet :wink:

**Comment by matbesancon** [comment]
oh ok thanks :)

**Pull request merged**
