### PR TITLE
SuiteSparse aarch64

### PR DESCRIPTION
**Pull request by matbesancon**
Following the modification on OpenBLAS, this PR allows 64 bits on aarch64 for https://github.com/JuliaLang/julia/pull/39714

### CODE REVIEW

**Comment by ViralBShah** [comment]
Is the aarch64 libopenblas64_ merged? It seems like it can't find that on aarch64.

**Comment by matbesancon** [comment]
Yes it seems to be the case:
https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases

**Comment by ViralBShah** [comment]
Wasn't that reverted? https://github.com/JuliaPackaging/Yggdrasil/pull/2588

It might break existing 1.6 releases, and perhaps we need to revisit this after the [LBT PR](https://github.com/JuliaLang/julia/pull/39455) is merged, because everything will change anyways again.

**Comment by ViralBShah** [comment]
Cc @staticfloat

**Comment by matbesancon** [comment]
Yes I also got feedback from @staticfloat to use OpenBlas v0.3.13

**Comment by ViralBShah** [comment]
I think this will all snap in together over the next few weeks.

**Comment by ViralBShah** [comment]
Since we have some catching up to do on SuiteSparse, let's get a new version of SuiteSparse in here, which links against 64-bit openblas 0.3.13 on aarch64 as well. That new SuiteSparse version can have a julia compat for 1.7+.

**Comment by ViralBShah** [comment]
The plan is to do this first, and then merge the LBT PR I link above.

**Pull request closed without merging**
