### PR TITLE
Add builder for CGAL julia wrapper

### PR DESCRIPTION
**Pull request by rgcv**
Properly this time, unlike #405.

**EDIT:** Force pushed to rename the package.

### CODE REVIEW

**Comment by giordano** [comment]
> Force pushed to rename the package.

Could you please reflect the change also on the directory name?

**Comment by rgcv** [comment]
> Could you please reflect the change also on the directory name?

Just to confirm: `C/cgal_julia` --> `L/libcgal_julia`?

**Comment by giordano** [comment]
Yes please

**Comment by rgcv** [comment]
New push bumps to newer version + installs `LICENSE`

**Comment by rgcv** [comment]
Hi!

Been slowly tracking progress on a few PRs here, specifically the Julia and cxxwrap_julia builders. I'm guessing the former is still going to take a while to stabilize and get up and running. Nevertheless, the latter has been merged and a new release published.

Now I don't mean to sound pushy or anything, but I was wondering if there is something in the way of merging this PR. Anything I can lend a hand with?

Much abliged!

**Comment by giordano** [comment]
Oops, sorry for missing this one.

**Comment by rgcv** [comment]
No problem! And thanks :)

**Pull request merged**
