### PR TITLE
[DONOTMERGE] Check if HIP still builds

### PR DESCRIPTION
**Pull request by Keno**
Fails for me locally, so I want to see if it builds on Yggdrasil.

### CODE REVIEW

**Comment by Keno** [comment]
Ok. The failure here matches what I see locally. @jpsamaroo You probably know better than me what needs to be fixed.

**Comment by giordano** [comment]
I don't know if that's the culprit here, but we upgraded cmake since #4109

**Comment by jpsamaroo** [comment]
I would guess we probably need to pull in rocm_cmake: https://github.com/JuliaPackaging/Yggdrasil/tree/master/R/rocm_cmake

**Comment by giordano** [comment]
#4690 fixed it

**Comment by giordano** [comment]
I presume this can be closed now.

**Pull request closed without merging**
