### PR TITLE
rebuild libLLVMExtra for LLVM 15

### PR DESCRIPTION
**Pull request by vchuravy**
cc: @maleadt

### CODE REVIEW

**Comment by maleadt** [comment]
Great! Have been looking forward to this :-)

**Comment by giordano** [comment]
https://buildkite.com/julialang/yggdrasil/builds/946#01865670-42c3-4792-ac80-4c44cf310708/634-930
```
[20:28:29] /workspace/srcdir/LLVM.jl/deps/LLVMExtra/lib/llvm-api.cpp: In function ‘LLVMOpaqueValue* LLVMBuildCallWithOpBundle(LLVMBuilderRef, LLVMValueRef, LLVMOpaqueValue**, unsigned int, LLVMOpaqueOperandBundleDef**, unsigned int, const char*)’:
[20:28:29] /workspace/srcdir/LLVM.jl/deps/LLVMExtra/lib/llvm-api.cpp:512:61: error: ‘class llvm::PointerType’ has no member named ‘getElementType’; did you mean ‘getArrayElementType’?
[20:28:29]          cast<FunctionType>(cast<PointerType>(V->getType())->getElementType());
[20:28:29]                                                              ^~~~~~~~~~~~~~
[20:28:29]                                                              getArrayElementType
```
and we also need to remove i686-linux-musl (at least for LLVM 15)

**Comment by vchuravy** [comment]
https://github.com/maleadt/LLVM.jl/pull/324

**Comment by vchuravy** [comment]
Argh automerge...

**Pull request merged**
