### PR TITLE
Fix incorrect mlpack `LibraryProduct` names

### PR DESCRIPTION
**Pull request by rcurtin**
Oops, when I created the `mlpack` package, I mistyped one of the `LibraryProduct` names and entirely missed another.  This PR fixes those issues.

### CODE REVIEW

**Comment by rcurtin** [comment]
(This should probably wait on #538 for merge, by the way.)

**Comment by rcurtin** [comment]
I think that maybe this has to do with the names of the LAPACK symbols that are modified in Armadillo's `build_tarballs.jl`.  I've been trying to find some time to debug but this weekend has been busy so I've only gotten a few seconds here or there...

I'll post more if I find anything, but, it's also possible you may get to the solution before I do. :)

Note this fascinating warning from Armadillo during compilation:  (I'm surprised it checks for such things!)

```
[23:36:27] /workspace/destdir/include/armadillo_bits/def_blas.hpp:21:97: note: #pragma message: WARNING: detected possible interference with definitions of BLAS functions;
```

**Comment by rcurtin** [comment]
Take a look at #547, that might do it.

**Comment by rcurtin** [comment]
Ha!  I didn't realize my description in #547 would cause this PR to close. :smile:

**Comment by giordano** [comment]
Screenshot_20200223_202312

**Comment by giordano** [comment]
What's wrong with FreeBSD? :thinking:

**Comment by rcurtin** [comment]
Let me try to reproduce locally.  Probably the LAPACK names are still wrong.

**Comment by rcurtin** [comment]
I still haven't been able to reproduce this locally.  I'm going to try to rebuild, since everything seems like it *should* work: the version of `libarmadillo.so` provided by `JuliaBinaryWrappers` for FreeBSD references the OpenBLAS LAPACK/BLAS symbols with `_64` appended (so, e.g., `sgges_64_` and `wrapper_sgges_64_`).  The `libopenblas64_.so` provided by `JuliaBinaryWrappers` for FreeBSD have the symbols with `_64` appended (so, e.g., `sgges_64_`).  So the failures provided by the build don't seem to make sense.

**Comment by giordano** [comment]
It looks like FreeBSD worked this time?

**Comment by rcurtin** [comment]
Yeah, I feel bad that I didn't just close/reopen to try it again immediately, but I feel better that I did my homework to understand what's actually going on here.  Anyway, I think we're good.

**Comment by rcurtin** [comment]
Thanks! :rocket:

**Comment by giordano** [comment]
Thanks for your collaboration and patience!

**Comment by rcurtin** [comment]
Oh this is nothing, what you have here is absolutely beautiful. :100:  On the other hand, getting mlpack's Python bindings to compile on AppVeyor so they can be distributed via PyPI is a complete and utter bloodbath that I have been working on for literally months:

https://ci.appveyor.com/project/mlpack/mlpack-wheels/history

Yggdrasil and BinaryBuilder are such a breath of fresh air by comparison.  (Even compared to the non-Windows Python wheel builds.)

**Comment by giordano** [comment]
We also have a website as of yesterday to advertise this tool to the world: https://binarybuilder.org/ :grin:

**Pull request merged**
