### PR TITLE
[Sundials 5] Rebuild sundials 5.

### PR DESCRIPTION
**Pull request by ViralBShah**

### CODE REVIEW

**Comment by ViralBShah** [comment]
@giordano For cmake systems, how to do the equivalent of `autoreconf -vi` or is there a different issue here?

**Comment by giordano** [comment]
The issue we've seen in #671 is very autotools-specific, this is probably different:
```
[ Info: Could not locate libsundials_sunlinsollapackdense inside ["/agent/_work/1/s/S/Sundials@5/build/powerpc64le-linux-gnu-libgfortran3/FHTIzTO4/destdir/lib64", "/agent/_work/1/s/S/Sundials@5/build/powerpc64le-linux-gnu-libgfortran3/FHTIzTO4/destdir/lib"]
[...]
[ Info: Could not locate libsundials_sunlinsollapackband inside ["/agent/_work/1/s/S/Sundials@5/build/powerpc64le-linux-gnu-libgfortran3/FHTIzTO4/destdir/lib64", "/agent/_work/1/s/S/Sundials@5/build/powerpc64le-linux-gnu-libgfortran3/FHTIzTO4/destdir/lib"]
```
Maybe the dependencies of these two libraries can't be found?

**Comment by giordano** [comment]
Looks like LAPACK can't be found:
```
[00:09:17] -- Checking if LAPACK works... FAILED
[00:09:17] CMake Warning at config/SundialsCMakeMacros.cmake:83 (message):
[00:09:17]   ------------------------------------------------------------------------
[00:09:17] 
[00:09:17]   WARNING: LAPACK not functional
[00:09:17] 
[00:09:17]   Blas/Lapack support will not be provided
[00:09:17] 
[00:09:17]   ------------------------------------------------------------------------
[00:09:17] Call Stack (most recent call first):
[00:09:17]   CMakeLists.txt:933 (print_warning)
[00:09:17] 
[00:09:17] 
```

**Comment by ViralBShah** [comment]
I have no idea why powerpc is failing. Disabling it.

**Pull request merged**
