### PR TITLE
[CoinUtils] update to 2.11.11

### PR DESCRIPTION
**Pull request by odow**
Replacement for https://github.com/JuliaPackaging/Yggdrasil/pull/8067

### CODE REVIEW

**Comment by odow** [comment]
Seems like we've hit this before: https://github.com/JuliaPackaging/Yggdrasil/pull/837#issuecomment-612641835

**Comment by imciner2** [comment]
When I go to the commit associated with the release on GitHub I get a large banner warning.

image

Perhaps our git library doesn't like this case and can't find the commit because of it?

**Comment by imciner2** [comment]
Also, are we replacing https://github.com/JuliaPackaging/Yggdrasil/pull/8067 with this one now? That one seems to have also done some other changes on top of just the version update.

**Comment by odow** [comment]
I just started this to see if I could fix the build under my fork without requiring @amontoison. I don't have a preference for which.

**Comment by odow** [comment]
I changed to use ArchiveSource following https://github.com/JuliaPackaging/Yggdrasil/pull/837#issuecomment-612656350. Works for me locally.

**Comment by odow** [comment]
@amontoison happy?

**Review by amontoison — APPROVED** [review]

**Comment by amontoison** [comment]
Thanks Oscar!

**Pull request merged**
