### PR TITLE
[oneAPI_Support_Headers] add recipe

### PR DESCRIPTION
**Pull request by amontoison**
@maleadt @michel2323

### CODE REVIEW

**Comment by maleadt** [comment]
Any reason you're sourcing these from the upstream repositories instead of re-using the Conda set-up we're using for the actual build? This may lead to differences between both.

**Comment by amontoison** [comment]
> Any reason you're sourcing these from the upstream repositories instead of re-using the Conda set-up we're using for the actual build? This may lead to differences between both.

I updated the build script to use the Conda archive.

**Comment by maleadt** [comment]
Oh I wasn't saying you had to change, it was just a remark. Anyway, let's merge this so that the upstream work can go ahead.

**Comment by amontoison** [comment]
I know but I was a good suggestion!

**Pull request merged**
