### PR TITLE
gh_cli: New version 2.39.2

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by eschnett** [comment]
The error is `context/context.go:7:2: package slices is not in GOROOT (/opt/x86_64-linux-musl/go/src/slices)`.

**Comment by eschnett** [comment]
I disabled Windows because the Go compiler reports an ICE there.

**Comment by giordano** [comment]
@eschnett shouldn't have removed a platform lightly: https://github.com/JuliaPackaging/ArtifactUtils.jl/issues/24

**Comment by eschnett** [comment]
Sorry. I should have checked for automerge. (I also thought things would fall back automatically.)

**Comment by eschnett** [comment]
Since it's an ICE that I don't know how to fix, can we recall this update?

**Pull request merged**
