### PR TITLE
OpenMPI: New version 4.1.6

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by eschnett** [comment]
The FreeBSD build fails with the error message
```
configure: error: could not find cross-compile data file /workspace/srcdir/x86_64-unknown-freebsd13.2
```
This file is indeed not present; only the file `x86_64-unknown-freebsd12.2` exists.

**Comment by giordano** [comment]
It should be renamed

**Comment by eschnett** [comment]
I assume that's something that should happen in the image that's used for building, not in the build script here.

**Comment by giordano** [comment]
https://github.com/JuliaPackaging/Yggdrasil/blob/07548edf030220b89b0ffc8d187a03fb91aefa8e/O/OpenMPI/bundled/x86_64-unknown-freebsd12.2

**Pull request merged**
