### PR TITLE
Updated libportaudio to v19.7.0 and added support for MacOS AArch64

### PR DESCRIPTION
**Pull request by abhayap**
- removed the patch as it looks like v19.7.0 has a number of fixes that might address what the patch was doing

### CODE REVIEW

**Comment by abhayap** [comment]
I opened an issue in PortAudio to see if I can fix the build issue: https://github.com/PortAudio/portaudio/issues/685

**Comment by jeremiahpslewis** [comment]
It looks like windows i686 is special-cased in the build scripts for portaudio; based on what they use [here](https://github.com/PortAudio/portaudio/blob/52aee492edc64605dcc65afff13776c4dad81910/.github/workflows/cmake.yml#L31
), I might try the following:

```bash
if [[ $target == i686*mingw* ]]; then
    cmake -DCMAKE_INSTALL_PREFIX=$prefix \
        -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/i686-w64-mingw32.cmake \
        -DCMAKE_DISABLE_FIND_PACKAGE_PkgConfig=ON \
        -DCMAKE_FIND_ROOT_PATH=$prefix \
        ../portaudio/
else
    cmake -DCMAKE_INSTALL_PREFIX=$prefix \
        -DCMAKE_TOOLCHAIN_FILE="${CMAKE_TARGET_TOOLCHAIN}" \
        -DCMAKE_DISABLE_FIND_PACKAGE_PkgConfig=ON \
        -DCMAKE_FIND_ROOT_PATH=$prefix \
        ../portaudio/
fi
```

**Comment by jeremiahpslewis** [comment]
@abhayap Looks like I got the path wrong, maybe it should be ``-DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/i686-w64-mingw32.cmake \`` or ``-DCMAKE_TOOLCHAIN_FILE=../portaudio/toolchains/i686-w64-mingw32.cmake \``

**Comment by giordano** [comment]
That [toolchain file](https://github.com/PortAudio/portaudio/blob/52aee492edc64605dcc65afff13776c4dad81910/cmake/toolchains/i686-w64-mingw32.cmake) doesn't do anything special.  There is simply an upstream bug.

**Comment by abhayap** [comment]
@jeremiahpslewis Thanks for the suggestion. I fixed the path but I'm still getting the same error unfortunately.

**Comment by abhayap** [comment]
Thanks @giordano. I have filed an issue with portaudio. Is there a way to update the package just for MacOS AArch64 and have the other platforms download the previous version?

**Comment by giordano** [comment]
As I said already in that bug report, your issue is a duplicate of another ticket, which had been already fixed.  The fix didn't make it yet to a released version though

**Comment by abhayap** [comment]
Thanks for the changes and merging this @giordano!

**Pull request merged**
