### PR TITLE
highs bump

### PR DESCRIPTION
**Pull request by matbesancon**
bump HiGHS version to latest for some features.
ping @odow

### CODE REVIEW

**Comment by matbesancon** [comment]
Mmh, was this there before?
https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=8845&view=logs&j=dc0b91cd-646e-5b91-71d2-5bd6c66154e3&t=06876633-9a75-57a9-a678-1ccf14cae018&l=424
The build process seems find, but BB cannot find libhighs in the bin subdir

**Comment by odow** [comment]
I guess we need to re-add https://github.com/JuliaPackaging/Yggdrasil/pull/2467/commits/13e95d1dc30ed2732e4ec7fb58c58ac9d729db30.

**Comment by odow** [comment]
We're also in no rush to release a new jll. There are some more upstream changes coming: https://github.com/ERGO-Code/HiGHS/pull/453, and I think @galabovaa was integrating the ipx code?

**Comment by matbesancon** [comment]
ok yes, this is on hold for now

**Comment by odow** [comment]
Actually, any change you could re-add the following and see if it compiles?
```
if [[ ${target} == *mingw* ]]; then
     # On Windows, we need to move our .dll files.
     mv ${prefix}/lib/*.dll ${prefix}/bin
 fi
```
The option code is less needed than the infeasibility certificates. And the printing is going to take a while.

**Comment by matbesancon** [comment]
just did

**Comment by odow** [comment]
Ah. The issue is that the commit we used last time is not on master: https://github.com/ERGO-Code/HiGHS/commit/72523038995877307d9309354a77cd39e2388033. @galabovaa is the intent to merge the changes into the main development branch?

**Comment by odow** [comment]
@matbesancon try removing the `-DFAST_BUILD=ON \` line.

**Comment by galabovaa** [comment]
@odow Merging ERGO-Code/HiGHS@7252303 into master now. 

@matbesancon Why did you remove the FAST_BUILD flag? It is necessary to make use of the updated HiGHS CMake functionality, which is necessary for building on multiple platforms.

**Comment by matbesancon** [comment]
> @matbesancon Why did you remove the FAST_BUILD flag? It is necessary to make use of the updated HiGHS CMake functionality, which is necessary for building on multiple platforms.

I put it back, it was an experiment to see if it was causing the break

**Comment by matbesancon** [comment]
Replaced by https://github.com/JuliaPackaging/Yggdrasil/pull/2552/files

**Pull request closed without merging**
