### PR TITLE
[ROCmOpenCLRuntime] Update to 4.2.0

### PR DESCRIPTION
**Pull request by jpsamaroo**

### CODE REVIEW

**Comment by jpsamaroo** [comment]
@vchuravy any ideas on what the glibc failure is about?

**Comment by giordano** [comment]
```
[17:04:21] /opt/bin/x86_64-linux-gnu-libgfortran5-cxx11/c++ -fPIC -O3 -DNDEBUG  -Wl,-Bsymbolic -Wl,--unresolved-symbols=report-all -Wl,--version-script=/workspace/srcdir/ROCm-OpenCL-Runtime-rocm-4.2.0/amdocl/amdocl.map -shared -Wl,-soname,libamdocl64.so -o ../lib/libamdocl64.so CMakeFiles/amdocl64.dir/cl_memobj.cpp.o CMakeFiles/amdocl64.dir/cl_program.cpp.o CMakeFiles/amdocl64.dir/cl_sdi_amd.cpp.o CMakeFiles/amdocl64.dir/cl_device.cpp.o CMakeFiles/amdocl64.dir/cl_debugger_amd.cpp.o CMakeFiles/amdocl64.dir/cl_svm.cpp.o CMakeFiles/amdocl64.dir/cl_sampler.cpp.o CMakeFiles/amdocl64.dir/cl_thread_trace_amd.cpp.o CMakeFiles/amdocl64.dir/cl_counter.cpp.o CMakeFiles/amdocl64.dir/cl_d3d10.cpp.o CMakeFiles/amdocl64.dir/cl_d3d9.cpp.o CMakeFiles/amdocl64.dir/cl_command.cpp.o CMakeFiles/amdocl64.dir/cl_platform_amd.cpp.o CMakeFiles/amdocl64.dir/cl_event.cpp.o CMakeFiles/amdocl64.dir/cl_lqdflash_amd.cpp.o CMakeFiles/amdocl64.dir/cl_kernel_info_amd.cpp.o CMakeFiles/amdocl64.dir/cl_execute.cpp.o CMakeFiles/amdocl64.dir/cl_gl.cpp.o CMakeFiles/amdocl64.dir/cl_icd.cpp.o CMakeFiles/amdocl64.dir/cl_pipe.cpp.o CMakeFiles/amdocl64.dir/cl_d3d11.cpp.o CMakeFiles/amdocl64.dir/cl_context.cpp.o CMakeFiles/amdocl64.dir/cl_profile_amd.cpp.o CMakeFiles/amdocl64.dir/cl_p2p_amd.cpp.o CMakeFiles/amdocl64.dir/glibc_functions.cpp.o  -Wl,-rpath,/workspace/destdir/lib64:/workspace/destdir/lib /workspace/srcdir/ROCclr-rocm-4.2.0/build/libamdrocclr_static.a -ldl -pthread /workspace/destdir/lib64/libamd_comgr.so.2.0.0 /workspace/destdir/lib/libhsa-runtime64.so.1.3.0 /workspace/destdir/lib/libnuma.so 
[17:04:21] /opt/x86_64-linux-gnu/bin/../lib/gcc/x86_64-linux-gnu/8.1.0/../../../../x86_64-linux-gnu/bin/ld: /workspace/srcdir/ROCclr-rocm-4.2.0/build/libamdrocclr_static.a(os_posix.cpp.o): undefined reference to symbol 'clock_getres@@GLIBC_2.2.5'
[17:04:21] /opt/x86_64-linux-gnu/bin/../lib/gcc/x86_64-linux-gnu/8.1.0/../../../../x86_64-linux-gnu/bin/ld: /opt/x86_64-linux-gnu/bin/../x86_64-linux-gnu/sys-root/lib64/librt.so.1: error adding symbols: DSO missing from command line
[17:04:21] collect2: error: ld returned 1 exit status
[17:04:21] make[2]: *** [amdocl/CMakeFiles/amdocl64.dir/build.make:468: lib/libamdocl64.so] Error 1
```
Missing `-lrt`?

**Comment by jpsamaroo** [comment]
> Missing `-lrt`?

Indeed, `man clock_getres` says as much!

**Comment by jpsamaroo** [comment]
@giordano I can't reproduce this new glibc failure locally; am I doing something obviously wrong?

**Comment by giordano** [comment]
Maybe you can't reproduce locally because you have all dependencies :stuck_out_tongue:  but I don't:
```
julia> using libtree_jll

shell> $(libtree()) ./libamdocl64.so
libamdocl64.so 
├── libamd_comgr.so.2 [runpath]
│   ├── libz.so.1 [runpath]
│   └── librt.so.1 [default path]
├── libhsa-runtime64.so.1 [runpath]
│   ├── libelf.so.1 [default path]
│   │   └── libz.so.1 [default path]
│   ├── librt.so.1 [default path]
│   └── libhsakmt.so.1 not found
│       ┊ Paths considered in this order:
│       ┊ 1. rpath is skipped because runpath was set
│       ┊ 2. LD_LIBRARY_PATH was not set
│       ┊ 3. runpath:
│       ┊    ./../hsa/lib
│       ┊ 4. ld config files:
│       ┊    /opt/ComputeCpp-CE-1.3.0-Ubuntu-16.04-x86_64/lib
│       ┊    /usr/lib/libfakeroot
│       ┊    /opt/intel/mkl/lib/intel64
│       ┊    /opt/intel/mkl/lib/intel64_lin
│       ┊    /usr/lib32
│       ┊    /usr/lib/openmpi
│       ┊ 5. Standard paths:
│       ┊    /lib
│       ┊    /lib64
│       ┊    /usr/lib
│       ┊    /usr/lib64
├── libnuma.so.1 [runpath]
└── librt.so.1 [default path]
Error [./libamdocl64.so]: Not all dependencies were found
```
(courtesy of @haampie)

**Comment by jpsamaroo** [comment]
So what's the fix here? Is `hsa_rocr_jll` (provider of `libhsa-runtime64.so.1`) doing something wrong? It definitely depends on `hsakmt_roct_jll`, where `libhsakmt.so.1` comes from.

**Comment by giordano** [comment]
To be honest, I'm quite confused, `libhsakmt.so.1` is there in `${libdir}`:
```console
% ls libhsakmt.so.1   
libhsakmt.so.1
```
however the runpath of `libamdocl64.so` looks wrong:
```console
% readelf -d libamdocl64.so | grep RUNPATH
 0x000000000000001d (RUNPATH)            Library runpath: [/workspace/destdir/lib64:/workspace/destdir/lib:$ORIGIN/../lib64:$ORIGIN/../hsa/lib:$ORIGIN]
```
as if [`check_dynamic_linkage`](https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/084d75b38aa9d0a0240d328d9ff3adbc9c7d9068/src/Auditor.jl#L114-L115) didn't run before [`dlopen`](https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/084d75b38aa9d0a0240d328d9ff3adbc9c7d9068/src/Auditor.jl#L145-L175), which would [normalise the runpaths](https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/084d75b38aa9d0a0240d328d9ff3adbc9c7d9068/src/auditor/dynamic_linkage.jl#L353-L448)

**Comment by giordano** [comment]
If you set `dont_dlopen=true` you work around the audit failure but don't solve the fact that the library can't be dlopened unless you happen to have the missing library already available, no?

I don't really have the time these days to investigate the issue, but if someone can look into why `check_dynamic_linkage` doesn't run in the audit that would help us move forward.  In the message above I also pointed to the relevant lines.

Note that you can run the build with
```
julia build_tarballs.jl --debug=end --verbose x86_64-linux-gnu-cxx11
```
exit from the debug shell at the end, and then manually run audit with something like
```julia
using BinaryBuilder.Auditor
audit(Prefix("path/to/prefix"))
```
You'll likely have to add some debugging prints (or run an actual debugger) to follow what's happening.

**Comment by jpsamaroo** [comment]
It appears that in `check_dynamic_linkage`, `libhsakmt` doesn't ever show up in `keys(find_libraries(oh))`.

**Comment by giordano** [comment]
I'm trying to look into this.  Some findings:

* we usually keep `/workspace/destdir` in RUNPATH, as that's usually harmless.  We may decide to remove it in the future if it proves to be an issue, but it doesn't seem to be the culprit here, so my hypothesis that `check_dynamic_linkage` isn't working correctly doesn't stand
* we seem to be facing something extremely fishy in the dynamic loader
* for the record, in my system I have glibc 2.33, on amdci7 we have 2.27, we observe the same issue on both machines
* as pointed out by the output of libtree above, `libhsakmt.so.1` is an indirect dependency, it comes from `libhsa-runtime64.so.1`
* `libhsa-runtime64.so.1` alone can find `libhsakmt.so.1` just fine (note that `libamdocl64.so`, `libhsa-runtime64.so`, and `libhsakmt.so` are in the same directory):
```console
% readelf -d libhsa-runtime64.so | head -n 15

Dynamic section at offset 0x113000 contains 36 entries:
  Tag        Type                         Name/Value
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN]
 0x0000000000000001 (NEEDED)             Shared library: [libhsakmt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libelf.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [librt.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
 0x000000000000000e (SONAME)             Library soname: [libhsa-runtime64.so.1]
% ldd libhsa-runtime64.so
        linux-vdso.so.1 (0x00007ffd3c3be000)
        libhsakmt.so.1 => /home/mose/repo/Yggdrasil/R/ROCmOpenCLRuntime/build/x86_64-linux-gnu-cxx11/LeNx4P4T/x86_64-linux-gnu-libgfortran5-cxx11/destdir/lib/./libhsakmt.so.1 (0x00007f01088ab000)
        libelf.so.1 => /home/mose/repo/Yggdrasil/R/ROCmOpenCLRuntime/build/x86_64-linux-gnu-cxx11/LeNx4P4T/x86_64-linux-gnu-libgfortran5-cxx11/destdir/lib/./libelf.so.1 (0x00007f0108685000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f0108650000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f010862f000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f0108624000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f010840c000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f01082c8000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f01082ad000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f01080e1000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f01089bf000)
        libnuma.so.1 => /home/mose/repo/Yggdrasil/R/ROCmOpenCLRuntime/build/x86_64-linux-gnu-cxx11/LeNx4P4T/x86_64-linux-gnu-libgfortran5-cxx11/destdir/lib/./libnuma.so.1 (0x00007f0107ed6000)
        libz.so.1 => /home/mose/repo/Yggdrasil/R/ROCmOpenCLRuntime/build/x86_64-linux-gnu-cxx11/LeNx4P4T/x86_64-linux-gnu-libgfortran5-cxx11/destdir/lib/./libz.so.1 (0x00007f0107cba000)
```
* it looks like that moving `$ORIGIN` before `hsa/lib` in RUNPATH, solves the issue:
```console
% patchelf --set-rpath '/workspace/destdir/lib64:/workspace/destdir/lib:$ORIGIN/../lib64:$ORIGIN:$ORIGIN/../hsa/lib' libamdocl64.so
% ldd libamdocl64.so                                                                                                               
        linux-vdso.so.1 (0x00007ffda0f0a000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f1ab5d3a000)
        libamd_comgr.so.2 => /home/mose/repo/Yggdrasil/R/ROCmOpenCLRuntime/build/x86_64-linux-gnu-cxx11/LeNx4P4T/x86_64-linux-gnu-libgfortran5-cxx11/destdir/lib/./../lib64/libamd_comgr.so.2 (0x00007f1aaf036000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f1aaf02b000)
        libhsa-runtime64.so.1 => /home/mose/repo/Yggdrasil/R/ROCmOpenCLRuntime/build/x86_64-linux-gnu-cxx11/LeNx4P4T/x86_64-linux-gnu-libgfortran5-cxx11/destdir/lib/./libhsa-runtime64.so.1 (0x00007f1aaef48000)
        libnuma.so.1 => /home/mose/repo/Yggdrasil/R/ROCmOpenCLRuntime/build/x86_64-linux-gnu-cxx11/LeNx4P4T/x86_64-linux-gnu-libgfortran5-cxx11/destdir/lib/./libnuma.so.1 (0x00007f1aaed3b000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f1aaeb25000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f1aae9e1000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f1aae9c6000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f1aae9a5000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f1aae7d9000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f1ab5f0a000)
        libz.so.1 => /home/mose/repo/Yggdrasil/R/ROCmOpenCLRuntime/build/x86_64-linux-gnu-cxx11/LeNx4P4T/x86_64-linux-gnu-libgfortran5-cxx11/destdir/lib/./../lib64/../lib/libz.so.1 (0x00007f1aae5bd000)
        libhsakmt.so.1 => /home/mose/repo/Yggdrasil/R/ROCmOpenCLRuntime/build/x86_64-linux-gnu-cxx11/LeNx4P4T/x86_64-linux-gnu-libgfortran5-cxx11/destdir/lib/./libhsakmt.so.1 (0x00007f1aae58e000)
        libelf.so.1 => /home/mose/repo/Yggdrasil/R/ROCmOpenCLRuntime/build/x86_64-linux-gnu-cxx11/LeNx4P4T/x86_64-linux-gnu-libgfortran5-cxx11/destdir/lib/./libelf.so.1 (0x00007f1aae368000)
```
* another incredibly weird think is that when searching for `libhsakmt.so.1`, LD_DEBUG=libs` shows that only `./../hsa/lib` is in the RUNPATH of `libamdocl64.so` (?????), which is consistent with what libtree shows above
```console
% LD_DEBUG=libs ldd ./libamdocl64.so
[...]
      8788:	find library=libamd_comgr.so.2 [0]; searching
      8788:	 search path=/home/mose/repo/Yggdrasil/R/ROCmOpenCLRuntime/build/x86_64-linux-gnu-cxx11/LeNx4P4T/x86_64-linux-gnu-libgfortran5-cxx11/destdir/lib/./../lib64:/home/mose/repo/Yggdrasil/R/ROCmOpenCLRuntime/build/x86_64-linux-gnu-cxx11/LeNx4P4T/x86_64-linux-gnu-libgfortran5-cxx11/destdir/lib/./../hsa/lib:/home/mose/repo/Yggdrasil/R/ROCmOpenCLRuntime/build/x86_64-linux-gnu-cxx11/LeNx4P4T/x86_64-linux-gnu-libgfortran5-cxx11/destdir/lib/.		(RUNPATH from file ./libamdocl64.so)
[...]
      8788:	find library=libhsakmt.so.1 [0]; searching
      8788:	 search path=/home/mose/repo/Yggdrasil/R/ROCmOpenCLRuntime/build/x86_64-linux-gnu-cxx11/LeNx4P4T/x86_64-linux-gnu-libgfortran5-cxx11/destdir/lib/./../hsa/lib		(RUNPATH from file ./libamdocl64.so)
      8788:	  trying file=/home/mose/repo/Yggdrasil/R/ROCmOpenCLRuntime/build/x86_64-linux-gnu-cxx11/LeNx4P4T/x86_64-linux-gnu-libgfortran5-cxx11/destdir/lib/./../hsa/lib/libhsakmt.so.1
      8788:	 search cache=/etc/ld.so.cache
      8788:	 search path=/usr/lib/glibc-hwcaps/x86-64-v3:/usr/lib/glibc-hwcaps/x86-64-v2:/usr/lib/tls/haswell/x86_64:/usr/lib/tls/haswell:/usr/lib/tls/x86_64:/usr/lib/tls:/usr/lib/haswell/x86_64:/usr/lib/haswell:/usr/lib/x86_64:/usr/lib		(system search path)
      8788:	  trying file=/usr/lib/glibc-hwcaps/x86-64-v3/libhsakmt.so.1
      8788:	  trying file=/usr/lib/glibc-hwcaps/x86-64-v2/libhsakmt.so.1
      8788:	  trying file=/usr/lib/tls/haswell/x86_64/libhsakmt.so.1
      8788:	  trying file=/usr/lib/tls/haswell/libhsakmt.so.1
      8788:	  trying file=/usr/lib/tls/x86_64/libhsakmt.so.1
      8788:	  trying file=/usr/lib/tls/libhsakmt.so.1
      8788:	  trying file=/usr/lib/haswell/x86_64/libhsakmt.so.1
      8788:	  trying file=/usr/lib/haswell/libhsakmt.so.1
      8788:	  trying file=/usr/lib/x86_64/libhsakmt.so.1
      8788:	  trying file=/usr/lib/libhsakmt.so.1
[...]
```

@haampie since you're probably to be one who delved more into runpaths recently and libtree also completely agrees with dlopen/ldd, do you have a clue about why when getting to `libhsakmt.so.1` the loader only finds `./../hsa/lib` in RUNPATH?

**Comment by giordano** [comment]
Don't ask me why, but following the findings I reported yesterday I can confirm adding
```
patchelf --set-rpath '$ORIGIN/../lib64:$ORIGIN:$ORIGIN/../hsa/lib' "${libdir}/libamdocl64.so"
```
works around the issue, so we can move this forward, but I'd still be interested in knowing what the heck is happening with the dynamic loader.

**Comment by haampie** [comment]
`$ORIGIN` is relative to the path in which the library is located, it's not the real path of the library.

This is a symlink:

```
$ file hsa/lib/libhsa-runtime64.so
hsa/lib/libhsa-runtime64.so: symbolic link to ../../lib/libhsa-runtime64.so
```

the file has runpath $ORIGIN, which makes sense for `./lib/libhsa-runtime64.so`, but not for `./hsa/lib/libhsa-runtime64.so`.

So the issue is probably that libhsa-runtime64.so should not be located in the ./hsa/lib dir

**Comment by giordano** [comment]
Thanks a lot, I completely missed there was that symlink!

Ok, so having `$ORIGIN/../hsa/lib:$ORIGIN` in RUNPATH would find `../hsa/lib/libhsa-runtime64.so` before `./libhsa-runtime64.so`, but then this has only `$ORIGIN` in its RUNPATH and so it can't find its dependencies.  However the output of `LD_DEBUG=libs ldd ./libamdocl64.so` shows (see above)
```
      8788:	find library=libhsakmt.so.1 [0]; searching
      8788:	 search path=/home/mose/repo/Yggdrasil/R/ROCmOpenCLRuntime/build/x86_64-linux-gnu-cxx11/LeNx4P4T/x86_64-linux-gnu-libgfortran5-cxx11/destdir/lib/./../hsa/lib		(RUNPATH from file ./libamdocl64.so)
```
which is at very least misleading because this is the RUNPATH of `libhsa-runtime64.so`, and not of `libamdocl64.so` (which would include more directories), or am I missing something?  And also `libtree` when searching for `libhsakmt.so.1` shows `./../hsa/lib` as RUNPATH, but shouldn't it be `.` only for `libhsa-runtime64.so`?

**Pull request merged**
