### PR TITLE
[micromamba] Update to v1.4.7

### PR DESCRIPTION
**Pull request by tylerjthomas9**
[Release notes](https://github.com/mamba-org/mamba/releases/tag/2023.07.06)

`v1.4.3` has some [issues](https://github.com/mamba-org/mamba/issues/2546) with Windows, but this version has a fix (the fix came in [`v1.4.5`](https://github.com/mamba-org/mamba/releases/tag/2023.06.27)).

### CODE REVIEW

**Comment by tylerjthomas9** [comment]
I expected this to build without issues. Closing it for now until I have time to debug.

**Comment by giordano** [comment]
Sounded like they added a new directory inside the license directory

**Comment by tylerjthomas9** [comment]
Thank you! That was a quick fix.

**Comment by giordano** [comment]
But there were also other license files with txt extension in the directory, no?

**Comment by tylerjthomas9** [comment]
> But there were also other license files with txt extension in the directory, no?

You're right. I just checked and the old builds have all the licenses. I was confused because of the error when just using `install_license info/licenses/*`. I have added in another `install_license` command to get all the other ones.

**Pull request merged**
