### PR TITLE
OpenBLAS: Enable DYNAMIC_ARCH for aarch64

### PR DESCRIPTION
**Pull request by ianshmean**
Following success here https://github.com/xianyi/OpenBLAS/issues/2696#issuecomment-653252750 in fixing BLAS on aarch64

Worth doing on `powerpc64le` ?

cc. @giordano

### CODE REVIEW

**Comment by giordano** [comment]
Note that you need to touch the build_tarballs.jl script of OpenBLAS 0.3.9

**Comment by ianshmean** [comment]
@staticfloat @KristofferC as this should just change a subset of aarch64 builds (i.e. fixes Blas on aws graviton2 machines), could it make 1.5?

**Comment by staticfloat** [comment]
Let's merge, get a PR open and see what Kristoffer says.

**Comment by KristofferC** [comment]
So much pressure :p. You have better knowledge to make a decision than me. Last release we had an "innocent" new build of LLVM that broke Julia on old processors and was put in after the RCs which was kinda unfortunate. But this is probably not the same scale of change.

**Comment by ianshmean** [comment]
Perhaps it’s acceptable only if there’s going to be another rc?

**Comment by KristofferC** [comment]
How big is the impact of having it in?

**Comment by giordano** [comment]
Three orders of magnitude on AWS Amazon Graviton 2: https://github.com/xianyi/OpenBLAS/issues/2696. However there is a workaround: by setting an environment variable you can recover most, but not all, of the performance. Maybe it's better to be conservative here and live with a workaround?

**Comment by KristofferC** [comment]
Yeah, but how many people are using it I mean.

**Comment by ianshmean** [comment]
I think that would be fine. 

Also, having it land properly in 1.6 along with https://github.com/julialang/julia/pull/36485 would make sense

**Comment by staticfloat** [comment]
I think it’s low risk, but let’s just have it sit on master. We can always backport it to 1.5.1.

**Pull request merged**
