### PR TITLE
[SuiteSparse@7] Update some CMake configuration options

### PR DESCRIPTION
**Pull request by giordano**
Ref https://github.com/JuliaLang/julia/pull/52577#issuecomment-1872963230 and https://github.com/JuliaLang/julia/pull/52577#issuecomment-1872967550.  Most of the other options were fixed by #7878, but some were missed.

### CODE REVIEW

**Comment by imciner2** [comment]
Let's wait to see if any of those other options should be removed/changed. `LAPACK_FOUND` is probably a CMake option, not SuiteSparse (so it is a bit weird it isn't being used, but that might be because of their build system changing how they check for BLAS/LAPACK), but `NPARTITION` I think is SuiteSparse, but when I looked through there code last night that flag was still in use in the C code, but I couldn't see what the CMake for it was now. `BLAS_UNDERSCORE` I am not sure if it is CMake or SuiteSparse.

**Comment by giordano** [comment]
@mmuetzel how does it look now?

**Comment by mmuetzel** [comment]
@DrTimothyAldenDavis was writing that the Fortran name mangling should be detected automatically by the build system of SuiteSparse. Afaict, that requires that the Fortran compiler that was used to build the Fortran libraries (like BLAS or LAPACK) is installed when SuiteSparse is built (or at least a Fortran compiler that uses compatible name mangling).
If that is the case, you could probably remove setting that preprocessor variable.

On the other hand: If you are sure that the Fortran name mangling is one single trailing underscore, you could also set that variable.

Other than that, it looks good to me. 👍

**Comment by mmuetzel** [comment]
Also, I don't know if your build environment already sets `CFLAGS` and/or `CXXFLAGS`. If you prefer to retain their values, you might want to append to them instead. E.g., `CFLAGS="$CFLAGS -DBLAS_UNDERSCORE"

**Comment by giordano** [comment]
No, we don't set the compiler `*FLAGS` environment variables by default, so the script starts from a clean slate.  And it looks like the builds after removing `-DBLAS_UNDERSCORE` are by-by-bit identical to when setting that variable, which suggests the build system was inferring correctly the setting.  Thanks for the quick review!

**Pull request merged**
