### PR TITLE
Add libxkbcommon-x11

### PR DESCRIPTION
**Pull request by serenity4**

### CODE REVIEW

**Comment by giordano** [comment]
So you only want to add a product in the wrappers which was actually already there?

**Comment by serenity4** [comment]
I think it is more convenient to have a symbol for the library. It would also ensure the product is built (which may not be the case with the flag `-Denable_x11=false` I believe?). Well, that's all very minor, I agree. If you prefer, we can wait until the next version bump before building new tarballs.

**Comment by giordano** [comment]
I just wanted to understand: if you only want to have the product in the wrapper, without touching the tarballs, we can avoid rebuilding them (no need for the users to download new stuff!) by adding `[skip build]` to the git commit message.  I'm going to do that.

**Comment by serenity4** [comment]
Alright, thanks! I'll know next time ;)

**Pull request merged**
