### PR TITLE
TempestRemap: support same platforms as NetCDF

### PR DESCRIPTION
**Pull request by simonbyrne**

### CODE REVIEW

**Comment by simonbyrne** [comment]
Failures

MacOS aarch64: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=21805&view=logs&j=c1c90f1d-4335-55cc-47e9-7f0b47e2ad94&t=49c9434a-5aae-5284-a721-8d9cc541f775&l=837
```
[21:36:27] Undefined symbols for architecture arm64:
[21:36:27]   "_dgemv_", referenced from:
[21:36:27]       __Z29ForceConsistencyConservation3RK11DataArray1DIdES2_R11DataArray2DIdEbb in LinearRemapSE0.o
[21:36:27]       __Z36ForceIntArrayConsistencyConservationRK11DataArray1DIdES2_R11DataArray2DIdEb in LinearRemapFV.o
[21:36:27]   "_dgeqrf_", referenced from:
[21:36:27]       __Z27InvertFitArray_LeastSquaresRK11DataArray1DIdER11DataArray2DIdERS0_S5_ in FiniteVolumeTools.o
```
this looks like some sort of BLAS issue? We have OpenBLAS32 on this platform, so not sure what the exact problem is.

Windows x86_64: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=21805&view=logs&jobId=c1c90f1d-4335-55cc-47e9-7f0b47e2ad94&j=329a03a7-d7c2-595e-462a-1f7a0e574bc7&t=3461d365-9331-5089-03d9-b8470fce10d0
There's a bunch of warnings, but not clear what the error is?

@giordano any suggestions?

**Comment by giordano** [comment]
Something looks broken in the build system for aarch64 darwin because the log says
```
[21:36:15] checking for sgemm_ in -lopenblas... yes
[21:36:16] checking for cheev_ in -lopenblas... yes
```
but then the code is built without `-lopenblas`, hence the linking error.

Errors on Windows start at
```
[21:36:21] ../src/triangle.cpp:3682:69: error: cast from ‘double***’ to ‘long unsigned int’ loses precision [-fpermissive]
[21:36:21]    printf("triangle x%lx with orientation %d:\n", (unsigned long) t->tri,
[21:36:21]                                                                      ^
```

Pro tip: search for "***error:***, colon included".

**Comment by simonbyrne** [comment]
Any suggestions on how to fix these? Should I use the system BLAS on MacOS Aarch64? and can I pass `-fpermissive` as a CFLAGS?

**Comment by giordano** [comment]
Aarch64 darwin should theoretically work since it's should be pretty similar to x86 darwin, but I can't tell what's wrong without entering the build environment, reading the logs, `configure` and `Makefile` to figure out why `-lopenblas` isn't actually passed.

For Windows, what's shown between square brackets is usually the flag which causes the error, no?  I'm confused by what that `-fpermissive` there means.

**Comment by simonbyrne** [comment]
closed in favor of #5864

**Pull request closed without merging**
