### PR TITLE
GDAL add OpenJPEG support

### PR DESCRIPTION
**Pull request by visr**
Fixes https://github.com/JuliaGeo/GDAL.jl/issues/64

### CODE REVIEW

**Comment by visr** [comment]
Seems to find it alright:
```
[20:18:38] checking for OPENJPEG... yes
[20:18:38] checking for opj_setup_decoder in -lopenjp2... yes
```

**Comment by giordano** [comment]
Oh, nice, some failures on Windows.  I was missing them :slightly_smiling_face:

**Comment by visr** [comment]
Ah I see, it cannot find PROJ 6 symbols.
```
[20:56:08] checking for PROJ >= 6 library... checking for proj_create_from_wkt in -lproj_6_3... no
[20:56:09] checking for proj_create_from_wkt in -l-lproj_6_3... no
[20:56:10] checking for internal_proj_create_from_wkt in -lproj_6_3... no
[20:56:10] checking for internal_proj_create_from_wkt in -lproj_6_3... (cached) no
[20:56:10] checking for internal_proj_create_from_wkt in -linternalproj... no
[20:56:10] checking for internal_proj_create_from_wkt in -linternalproj... (cached) no
[20:56:10] configure: error: PROJ 6 symbols not found
```

It currently uses PROJ 7 though (`PROJ_jll v7.0.1+0`). I assumed that it would accept that. Would have to look into it. If it doesn't maybe it's best to go straight for GDAL 3.1.0 instead of 3.0.4, would prefer not holding back PROJ.

**Comment by visr** [comment]
This is now working on Windows 64 bit. On 32 bit it is not adding OpenJPEG support, here is the difference:

```
[ Info: Building for x86_64-w64-mingw32-cxx11
[18:44:43] checking for OPENJPEG... yes
[18:44:43] checking for opj_setup_decoder in -lopenjp2... yes
[18:44:48]   OpenJPEG support:          yes

[ Info: Building for i686-w64-mingw32-cxx11
[18:17:42] checking for OPENJPEG... yes
[18:17:42] checking for opj_setup_decoder in -lopenjp2... no
[18:18:22]   OpenJPEG support:          no
```
https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=4215&view=logs&j=c85d1a7d-ef75-519a-357c-97d5ec742f2e&t=d7c76b8d-3c56-539d-0892-69fd7464391b&l=4629

I don't really have any leads to go on, and am also fine with merging this without 32 bit Windows support. Other 32 bit systems are working fine.

**Comment by giordano** [comment]
Interestingly enough, the symbol is there
```
sandbox:${WORKSPACE}/destdir/bin # nm libopenjp2.dll | grep opj_setup_decoder
68ae2750 T _opj_setup_decoder@8
```
but the `configure.log` says
```
configure:32867: checking for opj_setup_decoder in -lopenjp2
configure:32892: cc -o conftest.exe -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2  -L/workspace/destdir/bin conftest.c -lopenjp2  -L/workspace/destdir/lib -lopenjp2  >&5
/tmp/ccpNClgF.o: In function `main':
/workspace/srcdir/gdal-3.0.4/conftest.c:69: undefined reference to `opj_setup_decoder'
collect2: error: ld returned 1 exit status
```
For the record, this is the `conftest.c`:
```c
/* confdefs.h */
#define PACKAGE_NAME ""
#define PACKAGE_TARNAME ""
#define PACKAGE_VERSION ""
#define PACKAGE_STRING ""
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define HAVE_GCC_WARNING_ZERO_AS_NULL_POINTER_CONSTANT 1
#define HAVE_CXX11 1
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_STD_IS_NAN 1
#define STDC_HEADERS 1
#define HAVE_ASSERT_H 1
#define HAVE_FCNTL_H 1
#define HAVE_UNISTD_H 1
#define HAVE_STDINT_H 1
#define HAVE_LIMITS_H 1
#define HAVE_LOCALE_H 1
#define HAVE_FLOAT_H 1
#define HAVE_ERRNO_H 1
#define HAVE_DIRECT_H 1
#define HAVE_LONG_LONG 1
#define VSI_STAT64 _stat64
#define VSI_STAT64_T __stat64
#define SIZEOF_INT 4
#define SIZEOF_UNSIGNED_LONG 4
#define SIZEOF_VOIDP 4
#define HAVE_UINTPTR_T 1
#define HAVE_IEEEFP 1
#define HOST_FILLORDER FILLORDER_LSB2MSB
#define HAVE_VPRINTF 1
#define HAVE_SNPRINTF 1
#define HAVE_VSNPRINTF 1
#define HAVE_ATOLL 1
#define HAVE_STRTOULL 1
#define HAVE_STRTOF 1
#define HAVE_GETCWD 1
#define HAVE_DECL_STRTOF 1
#define HAVE_GCC_ATOMIC_BUILTINS 1
#define HAVE_GCC_BSWAP 1
#define HAVE_PTHREAD_MUTEX_RECURSIVE 1
#define HAVE_PTHREAD_MUTEX_ADAPTIVE_NP 1
#define HAVE_PTHREAD_SPINLOCK 1
#define CPL_MULTIPROC_PTHREAD 1
#define HAVE_PNG_H 1
#define HAVE_JPEGLIB_H 1
/* end confdefs.h.  */

/* Override any GCC internal prototype to avoid an error.
   Use char because int might match the return type of a GCC
   builtin and then its argument prototype would still apply.  */
#ifdef __cplusplus
extern "C"
#endif
char opj_setup_decoder ();
int
main ()
{
return opj_setup_decoder ();
  ;
  return 0;
}
```

To be honest, I'm not sure what's going on here.  But if you want to ignore this, let's merge

**Pull request merged**
