### PR TITLE
liblsl fix windows x86

### PR DESCRIPTION
**Pull request by samuelpowell**
Building of unit tests was disabled as this failed on 32-bit Windows, but this appears to be a genuine problem in the underlying library, as it crashes on CI. Will attempt to resolve x86 build to overcome this problem.

### CODE REVIEW

**Comment by samuelpowell** [comment]
Note: must patch CMakeList for MINGW special link additions for internal unit test to avoid most errors.

**Comment by samuelpowell** [comment]
@tstenner I wonder if you might be able to assist?

This repository contains build recipes which are executed on CI and result in a set of binary outputs. For LSL these are located [here](https://github.com/JuliaBinaryWrappers/liblsl_jll.jl/releases).

LSL is successfully cross-compiling on Linux (x86, x64, ARMv7, ARMv8, PPC), FreeBSD(x64), MacOS,  and Windows (x86, and x64). 

I have CI running on the package that uses these binaries, [LSL.jl](https://github.com/samuelpowell/LSL.jl) which tests on Linux (x86, x64, ARMv8), MacOS, Windows(x86, x64). Of all of these platforms, everything is working fine with the exception of ARMv8 and Windows x86. Fixing the former is for another day, but I wonder if you have any ideas why the Windows x86 build might not be working?

The AppVeyor log is [here](https://ci.appveyor.com/project/samuelpowell/LSL-jl/build/job/jedh2knbm0kcj1i3) where one can see the error:

```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x649cbc2a -- __fu134___ZTVSt15basic_streambufIcSt11char_traitsIcEE at C:\Users\appveyor\.julia\artifacts\ea828e58e0e461257aabf7a9d244ce073dc79189\bin\liblsl.dll (unknown line)in expression starting at C:\projects\lsl-jl\test\sample.jl:12
```

I can dig down to work out exactly what library call triggered this if it isn't obvious from the mangled name.

All of the platforms are being built with a common set of commands:

```bash
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$prefix -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TARGET_TOOLCHAIN} -DCMAKE_BUILD_TYPE=Release -DLSL_UNIXFOLDERS=1 -DLSL_NO_FANCY_LIBNAME=1 -DLSL_UNITTESTS=1 ../
make -j${nproc}
make install
```

So my question is, do you know if the Windows 32-bit build requires any specific configuration steps (note that this is not simply a matter of 32- vs. 64-bit, as Linux x86 is fine).

Any pointers warmly received!

(For the record, ARMv8 passes some tests, but [stalls](https://travis-ci.org/samuelpowell/LSL.jl/jobs/650153640) when creating a stream with the error `
Unexpected error while serializing the feed header (id: ffff8b912630): Unsupported channel format used to construct a sample.`)

**Comment by tstenner** [comment]
> Note: must patch CMakeList for MINGW special link additions for internal unit test to avoid most errors.

These should be shipped upstream, as they might affect all users. MinGW on win-x86 isn't tested regularly.

> `Exception: EXCEPTION_ACCESS_VIOLATION at 0x649cbc2a -- __fu134___ZTVSt15basic_streambufIcSt11char_traitsIcEE at C:\Users\appveyor\.julia\artifacts\ea828e58e0e461257aabf7a9d244ce073dc79189\bin\liblsl.dll (unknown line)in expression starting at C:\projects\lsl-jl\test\sample.jl:12`

This is either a result of a too short buffer or a genuine bug, in any case I'd need a full stack trace; mangled names are fine, though.

One thing that comes to mind is the [historic int32/int64 problem on windows](https://github.com/sccn/liblsl/pull/6/files) that's not been fixed in the 1.13 branch, so I'd disable the 64bit support on liblsl < 1.14

> (For the record, ARMv8 passes some tests, but stalls when creating a stream with the error Unexpected error while serializing the feed header (id: ffff8b912630): Unsupported channel format used to construct a sample.)

I suspect that boost doesn't know that the target arch has native 64 bit ints so creating a stream with this format fails.

**Comment by samuelpowell** [comment]
Thanks @tstenner, I will open an issue with the diffs for CMakeLists which enable a clean MinGW build. 

I doubt I will have access to Windows x86 for a while, but I will look at this further when I do.

With regard to AARCH64, I'm not actually trying to create a stream with a 64-bit integer format in any of the tests. The error above repeats continuously until CI timeout, as though it is occurring as transmission is retried. If this is indeed a BOOST related issue, are there any appropriate build flags I can set?

**Comment by samuelpowell** [comment]
Diffs for MinGW posted upstream https://github.com/sccn/liblsl/issues/58

**Comment by staticfloat** [comment]
Looks good to me!  Ready to merge?

**Comment by samuelpowell** [comment]
Yes please, thanks @staticfloat

**Comment by giordano** [comment]
Need to rename `FileSource`

**Comment by samuelpowell** [comment]
(Note that the win32 library is still not working, nor is AARCH64, but building the unit tests through this PR will help diagnosis so this is still an improvement)

**Comment by samuelpowell** [comment]
@giordano what should it be?

**Comment by samuelpowell** [comment]
Ahhh, I didn’t realise this was a type

**Comment by giordano** [comment]
We introduced `ArchiveSource` very recently with https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/671.

Just to create confusion, the old `FileSource` is to be replaced in most cases by `ArchiveSource`, only a very small subset of the old `FileSource` can remain as they are.  Despite these temporary (re)naming mess, I think these new types give us much more control over what we do with the sources and the dependencies.

**Comment by samuelpowell** [comment]
Sounds good, it reads well

**Pull request merged**
