### PR TITLE
Bump [ICU] version

### PR DESCRIPTION
**Pull request by bramtayl**
Libical seems to require at least this version

### CODE REVIEW

**Comment by bramtayl** [comment]
Well, I guess I shouldn't have expected this to be easy...

**Comment by bramtayl** [comment]
I'm getting uarrsort.cpp:40:34: error: ‘max_align_t’ is not a member of ‘std’ when I try to follow the existing build script. It seems like the newer version of ICU requires at least gcc 4.9

**Comment by giordano** [comment]
This one uses GCC 7...

**Comment by bramtayl** [comment]
Oh, forgot you could change that! Now I'm getting

```
x86_64-linux-musl-g++ -D_REENTRANT -DU_HAVE_ELF_H=1 -DU_HAVE_STRTOD_L=0 -DU_HAVE_XLOCALE_H=0 -I. -I../common -I../i18n -DU_ATTRIBUTE_DEPRECATED= -DU_IO_IMPLEMENTATION -O2 -W -Wall -pedantic -Wpointer-arith -Wwrite-strings -Wno-long-long -std=c++11 -c -DPIC -fPIC -o ufile.o ufile.cpp
In file included from ../common/unicode/uenum.h:25:0,
                 from ../common/unicode/uloc.h:27,
                 from ../i18n/unicode/unum.h:21,
                 from locbund.h:28,
                 from locbund.cpp:25:
../common/unicode/localpointer.h:45:10: fatal error: memory: No such file or directory
 #include <memory>
```

**Comment by giordano** [comment]
Could you please update the PR here so that we're on the same page?  I think I asked the same a few times already....

**Comment by bramtayl** [comment]
Hmm I haven't changed anything at all except the version. The line numbers on the patches might have changed; but I've been doing them manually with `vi`. I'm not sure how to share patches? I think maybe these lines

```
for x in ARFLAGS CFLAGS CPPFLAGS CXXFLAGS FFLAGS LDFLAGS; do
    sed -i -e "/^${x} =.*/s:@${x}@::" "config/Makefile.inc.in"
done
```

could be deleted though, because the alpine script referenced in the comment

https://git.alpinelinux.org/aports/tree/main/icu/APKBUILD?id=334ebffde9dec34becdd628ad56007699e98ea81

links to an ICU issue that doesn't seem to exist anymore

https://bugs.icu-project.org/trac/ticket/6102

But otherwise I haven't changed anything at all about the existing script, mostly because I don't really understand it...

**Comment by giordano** [comment]
Besides the version number, you must update the hash of the source archive (different file -> different hash):
https://github.com/JuliaPackaging/Yggdrasil/blob/801e854cf8f595e51e26797d542a401935255ffd/I/ICU/build_tarballs.jl#L11

**Comment by bramtayl** [comment]
I haven't gotten to the end of the wizard where it prints the new hash though...When I ctrl-c out of the wizard I get the message

```
Wizard stopped, use BinaryBuilder.run_wizard() to resume,
or BinaryBuilder.deploy() to deploy the incomplete script
```

but `BinaryBuilder.deploy` doesn't seem to exist?

**Comment by giordano** [comment]
> I haven't gotten to the end of the wizard

I appreciate you like the wizard, but it's considerably more complicated than editing and running this script, besides making it impossible for me and you to look at the same thing when you have issues.

>  where it prints the new hash though

https://docs.binarybuilder.org/stable/FAQ/#What-are-those-numbers-in-the-list-of-sources?-How-do-I-get-them?-1.  Also, I assume you haven't read [the log of the failed job](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=8836&view=logs&j=96c13d9d-dfd2-51e5-2f76-4a0b3ce09abc&t=09532434-8b0a-5f0e-118d-a3181cde5ec8&l=32) here:

```
┌ Error: Hash Mismatch!
│   Expected sha256:   94a80cd6f251a53bd2a997f6f1b5ac6653fe791dfab66e1eb0227740fb86d5dc
│   Calculated sha256: c79193dee3907a2199b8296a93b52c5cb74332c26f3d167269487680d479d625
└ @ BinaryBuilderBase /depot/packages/BinaryBuilderBase/caAyF/src/ArchiveUtils.jl:113
```

> but BinaryBuilder.deploy doesn't seem to exist?

Did you actually try to run the command?

**Comment by bramtayl** [comment]
Huh. Well that seemed to have passed CI, so maybe I'm good?

**Comment by giordano** [comment]
> Huh. Well that seemed to have passed CI

That was easy, wasn't it? :slightly_smiling_face: 

> so maybe I'm good?

Honestly, I'd like to wait unless there is a specific need to get the latest version of ICU.  The issue is that the library changes the soversion.  We should first make sure _all_ packages depending on `ICU_jll` specify a compat bound

**Comment by bramtayl** [comment]
Ok, well, the needs I have are

ICU -> libical -> bluez -> PulseAudio (optional)

So the needs are not pressing. But I can go through and find all packages that depend on ICU_jll

**Comment by giordano** [comment]
> But I can go through and find all packages that depend on ICU_jll

https://juliahub.com/ui/Packages/ICU_jll/hGiiW/67.1.0+3?t=2

**Comment by bramtayl** [comment]
Good to go?

**Comment by bramtayl** [comment]
Oh darn. I guess one of the other dependencies of libical indirectly depends on HarfBuzz so this isn't going to help me...

**Comment by bramtayl** [comment]
@giordano sorry to bother you again I'm just wondering what's the path forward? Should I bump the version of HarfBuzz too? Or find evidence that the existing Harfbuzz and the new ICU work together?

**Comment by giordano** [comment]
There are a few things to do

1. open a _**draft**_ PR to build a newer version of HarfBuzz (we have v2.6.1, latest is v2.7.4).  This _must_ specify the compat bound with ICU v68.2
2. investigate whether this new version of HarfBuzz is compatible with the one we have already.  In particular, we want to see whether the soname/soversion changed, or the minimum compatibility for macOS changed
3. if we find some incompatibilities, we _must_ lock all JLL packages [depending on `HarfBuzz_jll`](https://juliahub.com/ui/Packages/HarfBuzz_jll/h60co/2.6.1+10?t=2) to v2.6.1, just like what we did for ICU (https://github.com/JuliaRegistries/General/pull/29748, https://github.com/JuliaPackaging/Yggdrasil/pull/2515)
4. after we solve points 2 and 3, we may merge the PR at point 1

**Comment by bramtayl** [comment]
Well, 1 is done I think. I'm not really how to do the next step though...I see `Linked library libharfbuzz.so.0 has been auto-mapped to libharfbuzz.so.0` in the build script...the 0 seems promising?

**Pull request merged**
