### PR TITLE
[LCIO_Julia_Wrapper] source version bump and using builddependency

### PR DESCRIPTION
**Pull request by jstrube**

### CODE REVIEW

**Comment by jstrube** [comment]
I don't understand why different CMake options are needed on linux and MacOS to find the libcxxwrap dependency now. This was working on both architectures before. I only changed the julia dependency. Also, this is working for me when I cross-compile for MacOS, so I'm not sure how to debug this.
Suggestions welcome. Maybe @barche has an idea?

**Comment by jstrube** [comment]
Locally this works with the BB release, but on master it gives me a CMake error, but it's different from the one I see on Azure... I'm not sure what the CMake env is on the builders...

**Comment by barche** [comment]
Not sure what's happening, did you try `-DJlCxx_DIR=${prefix}/lib/cmake/JlCxx -DCMAKE_INSTALL_PREFIX=${prefix} -DCMAKE_FIND_ROOT_PATH=${prefix}`?

**Comment by jstrube** [comment]
I did, yeah. Somehow, this works now (I was confused about that at first, but 0.8 has landed in the meantime, and it seems to work there). But now, cxx03 is broken...

**Pull request merged**
