### PR TITLE
[XGBoost] Remove unused operator which caused us to require macOS 10.15

### PR DESCRIPTION
**Pull request by giordano**
Ref: https://github.com/dmlc/XGBoost.jl/issues/110#issuecomment-1236411155.  CC: @hcho3.

### CODE REVIEW

**Comment by giordano** [comment]
Still getting same error:
```
[20:50:20] /opt/bin/x86_64-apple-darwin14-libgfortran5-cxx11/x86_64-apple-darwin14-clang++ --sysroot=/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root -O3 -DNDEBUG -mmacosx-version-min=10.10 -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/runxgboost.dir/src/cli_main.cc.o src/CMakeFiles/objxgboost.dir/c_api/c_api.cc.o src/CMakeFiles/objxgboost.dir/c_api/c_api_error.cc.o src/CMakeFiles/objxgboost.dir/common/charconv.cc.o src/CMakeFiles/objxgboost.dir/common/common.cc.o src/CMakeFiles/objxgboost.dir/common/hist_util.cc.o src/CMakeFiles/objxgboost.dir/common/host_device_vector.cc.o src/CMakeFiles/objxgboost.dir/common/io.cc.o src/CMakeFiles/objxgboost.dir/common/json.cc.o src/CMakeFiles/objxgboost.dir/common/pseudo_huber.cc.o src/CMakeFiles/objxgboost.dir/common/quantile.cc.o src/CMakeFiles/objxgboost.dir/common/random.cc.o src/CMakeFiles/objxgboost.dir/common/survival_util.cc.o src/CMakeFiles/objxgboost.dir/common/threading_utils.cc.o src/CMakeFiles/objxgboost.dir/common/timer.cc.o src/CMakeFiles/objxgboost.dir/common/version.cc.o src/CMakeFiles/objxgboost.dir/data/data.cc.o src/CMakeFiles/objxgboost.dir/data/ellpack_page.cc.o src/CMakeFiles/objxgboost.dir/data/gradient_index.cc.o src/CMakeFiles/objxgboost.dir/data/gradient_index_format.cc.o src/CMakeFiles/objxgboost.dir/data/gradient_index_page_source.cc.o src/CMakeFiles/objxgboost.dir/data/proxy_dmatrix.cc.o src/CMakeFiles/objxgboost.dir/data/simple_dmatrix.cc.o src/CMakeFiles/objxgboost.dir/data/sparse_page_dmatrix.cc.o src/CMakeFiles/objxgboost.dir/data/sparse_page_raw_format.cc.o src/CMakeFiles/objxgboost.dir/gbm/gblinear.cc.o src/CMakeFiles/objxgboost.dir/gbm/gblinear_model.cc.o src/CMakeFiles/objxgboost.dir/gbm/gbm.cc.o src/CMakeFiles/objxgboost.dir/gbm/gbtree.cc.o src/CMakeFiles/objxgboost.dir/gbm/gbtree_model.cc.o src/CMakeFiles/objxgboost.dir/global_config.cc.o src/CMakeFiles/objxgboost.dir/learner.cc.o src/CMakeFiles/objxgboost.dir/linear/linear_updater.cc.o src/CMakeFiles/objxgboost.dir/linear/updater_coordinate.cc.o src/CMakeFiles/objxgboost.dir/linear/updater_shotgun.cc.o src/CMakeFiles/objxgboost.dir/logging.cc.o src/CMakeFiles/objxgboost.dir/metric/auc.cc.o src/CMakeFiles/objxgboost.dir/metric/elementwise_metric.cc.o src/CMakeFiles/objxgboost.dir/metric/metric.cc.o src/CMakeFiles/objxgboost.dir/metric/multiclass_metric.cc.o src/CMakeFiles/objxgboost.dir/metric/rank_metric.cc.o src/CMakeFiles/objxgboost.dir/metric/survival_metric.cc.o src/CMakeFiles/objxgboost.dir/objective/aft_obj.cc.o src/CMakeFiles/objxgboost.dir/objective/hinge.cc.o src/CMakeFiles/objxgboost.dir/objective/multiclass_obj.cc.o src/CMakeFiles/objxgboost.dir/objective/objective.cc.o src/CMakeFiles/objxgboost.dir/objective/rank_obj.cc.o src/CMakeFiles/objxgboost.dir/objective/regression_obj.cc.o src/CMakeFiles/objxgboost.dir/predictor/cpu_predictor.cc.o src/CMakeFiles/objxgboost.dir/predictor/predictor.cc.o src/CMakeFiles/objxgboost.dir/tree/constraints.cc.o src/CMakeFiles/objxgboost.dir/tree/hist/param.cc.o src/CMakeFiles/objxgboost.dir/tree/param.cc.o src/CMakeFiles/objxgboost.dir/tree/tree_model.cc.o src/CMakeFiles/objxgboost.dir/tree/tree_updater.cc.o src/CMakeFiles/objxgboost.dir/tree/updater_approx.cc.o src/CMakeFiles/objxgboost.dir/tree/updater_colmaker.cc.o src/CMakeFiles/objxgboost.dir/tree/updater_histmaker.cc.o src/CMakeFiles/objxgboost.dir/tree/updater_prune.cc.o src/CMakeFiles/objxgboost.dir/tree/updater_quantile_hist.cc.o src/CMakeFiles/objxgboost.dir/tree/updater_refresh.cc.o src/CMakeFiles/objxgboost.dir/tree/updater_sync.cc.o src/CMakeFiles/objxgboost.dir/__/rabit/src/allreduce_base.cc.o src/CMakeFiles/objxgboost.dir/__/rabit/src/rabit_c_api.cc.o src/CMakeFiles/objxgboost.dir/__/rabit/src/engine.cc.o -o ../xgboost  dmlc-core/libdmlc.a /opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root/usr/local/lib/libomp.dylib 
[20:50:21] Undefined symbols for architecture x86_64:
[20:50:21]   "___cxa_deleted_virtual", referenced from:
[20:50:21]       __ZTVN7xgboost5ValueE in json.cc.o
[20:50:21]       __ZTVN7xgboost10JsonStringE in json.cc.o
[20:50:21]       __ZTVN7xgboost9JsonArrayE in json.cc.o
[20:50:21]       __ZTVN7xgboost10JsonObjectE in json.cc.o
[20:50:21]       __ZTVN7xgboost10JsonNumberE in json.cc.o
[20:50:21]       __ZTVN7xgboost11JsonIntegerE in json.cc.o
[20:50:21]       __ZTVN7xgboost8JsonNullE in json.cc.o
[20:50:21]       ...
[20:50:21] ld: symbol(s) not found for architecture x86_64
[20:50:21] clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```
:confused:

**Comment by hcho3** [comment]
Where is the patch `X/XGBoost/bundled/patches/remove-unused-operator.patch` applied? I don't see it in the build log.

**Comment by giordano** [comment]
You're right because I forgot to do that :facepalm:

**Comment by giordano** [comment]
While I was there I submitted https://github.com/dmlc/dmlc-core/pull/673 to upstream the other patch we have for building the Windows library.  We're usually more active upstreaming the patches, this one slipped though.

**Comment by giordano** [comment]
Ok, that did the trick, thanks a lot for the help!

**Comment by hcho3** [comment]
No problem! I will go ahead and submit a pull request to the upstream XGBoost.

**Pull request merged**
