### PR TITLE
Revert to the older version of VMEC due to bug

### PR DESCRIPTION
**Pull request by benjaminfaber**
Need to revert to an older version of the underlying VMEC due to a bug introduced in the latest version that requires a much larger fix.

### CODE REVIEW

**Comment by giordano** [comment]
Isn't it easier to yank the broken version in the registry?

**Comment by benjaminfaber** [comment]
I wasn't aware I could do that, how do I go about doing that?  Do I submit a PR to the `General` registry with that version removed?

**Comment by giordano** [comment]
https://github.com/JuliaRegistries/General/blob/d36bad416efc43e6fcd66dfaf7fa597622e8a39e/README.md#when-is-yanking-a-release-appropriate

**Comment by benjaminfaber** [comment]
I reverted the VMEC.jl packaged to exclude VMEC_jll v1.3.  I'll close this and update VMEC_jll once we have the bug fixed.

**Pull request closed without merging**
