### PR TITLE
[Qt] Fix dependencies and product list

### PR DESCRIPTION
**Pull request by barche**
This fixes the issues mentioned in #1274 

The product list is long now, but Qt itself dynamically loads so-called plugins from the qml directory that may link to some of these, so to be safe I added all libraries that are generated.

### CODE REVIEW

**Comment by giordano** [comment]
Note that you'll need to manually fix the list of dependencies in the registry

**Comment by barche** [comment]
> Note that you'll need to manually fix the list of dependencies in the registry

OK, do I need to do that after this is merged, or will it error out somewhere?

**Comment by giordano** [comment]
Also before merging should be fine

**Comment by barche** [comment]
Checks passed, so I think this is OK!

**Comment by barche** [comment]
> Note that you'll need to manually fix the list of dependencies in the registry

It seems to be done automatically, or do I need to change something else?

https://github.com/JuliaRegistries/General/pull/17300/files

**Comment by giordano** [comment]
Uhm, ok, good!  Maybe only _removing_ dependencies requires manual intervention

**Pull request merged**
