### PR TITLE
[Ipopt] Upgrade to version 3.14.3

### PR DESCRIPTION
**Pull request by amontoison**
I also removed the static library `libipopt.a` to reduce the size of the tarballs.

### CODE REVIEW

**Comment by odow** [comment]
I don't understand

**Comment by amontoison** [comment]
What do you not understand Oscar?
The errors on Mac are related to the new linker `lld`. (@gbaraldi)

**Comment by odow** [comment]
The cause of https://github.com/jump-dev/AmplNLWriter.jl/pull/163#issuecomment-1807223107

**Comment by amontoison** [comment]
Me neither but it could help us to solve the issue in `AMPLNLWriter.jl`.

**Pull request merged**
