### PR TITLE
libclangex: Fix RPATH

### PR DESCRIPTION
**Pull request by Gnimuc**
@vchuravy, using `LLVM_full_jll` instead of `Clang_jll` seems to work fine. I'd like to do some tests on Windows, and it's OK to use `LLVM_full_jll` at the moment.

### CODE REVIEW

**Comment by vchuravy** [comment]
That is not ideal. LLVM_full_jll declares libclang as https://github.com/JuliaPackaging/Yggdrasil/blob/3337b1abac88846ddbecf4288d2293315059982c/L/LLVM/common.jl#L348

**Comment by vchuravy** [comment]
I think my prefered workaround would be for now, to use `BuidlDependency(LLVM_full_jll)` and then in the consumer to libclangex do a `using Clang_jll` before `using libclangex_jll`

**Comment by Gnimuc** [comment]
Do I need to dlopen `libclang-cpp`?

**Comment by Gnimuc** [comment]
With https://github.com/Gnimuc/ClangComplier.jl/blob/master/src/ClangCompiler.jl#L9, I still get:
```
ERROR: LoadError: InitError: could not load library "/Users/gnimuc/.julia/artifacts/8830363b18984d28665adc3d47d839eff75083bb/lib/libclangex.dylib"
dlopen(/Users/gnimuc/.julia/artifacts/8830363b18984d28665adc3d47d839eff75083bb/lib/libclangex.dylib, 1): Library not loaded: @rpath/libclang-cpp.dylib
  Referenced from: /Users/gnimuc/.julia/artifacts/8830363b18984d28665adc3d47d839eff75083bb/lib/libclangex.dylib
  Reason: image not found
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
```

**Comment by Gnimuc** [comment]
But wait, that's probably I did not config CMake script right.

**Comment by Gnimuc** [comment]
@vchuravy, after merging this, [the package registration PR](https://github.com/JuliaRegistries/General/pull/40688) will be rewritten and then trigger auto-merge bot, right?

**Comment by giordano** [comment]
> after merging this, the package registration PR will be rewritten and then trigger auto-merge bot, right?

No, because the version number is different: the branch contains name+version number+uuid.

**Comment by Gnimuc** [comment]
@giordano thanks for the explanation! Now, this is ready to be merged.

**Pull request merged**
