### PR TITLE
[libgeotiff] build against latest PROJ

### PR DESCRIPTION
**Pull request by visr**

### CODE REVIEW

**Comment by eschnett** [comment]
libgeotiff looks for a jpeg library, and builds against it if it finds it. It might be good to be explicit about this, i.e. to either disable jpeg support, or to enable it and add `JpegTurbo_jll` as dependency.

Also, this recipe builds against Libtiff_jll version 4.5.1. That version is built against LERC_jll version 3. If you want to use LERC_jll version 4 then you need to use at least Libtiff_jll version 4.7.0. There's nothing wrong with the current setup; just be aware that you're implicitly using LERC_jll 3.

**Comment by eschnett** [comment]
To be able to build `aarch64-*-freebsd` (that's a new architecture) you will need to use at least Libtiff_jll 4.7. Earlier versions of Libtiff_jll haven't been built for `aarch64-*-freebsd`. It's likely that a few other package also don't exist yet for `aarch64-*-freebsd`, so it might be best to disable that architecture with a respective comment.

**Comment by visr** [comment]
> libgeotiff looks for a jpeg library

Thanks, I made it an explicit dependency. Similarly for zlib.

> To be able to build `aarch64-*-freebsd`

I already set libtiff compat to 4.7, the problem is probably libcurl. So like recommended in https://github.com/JuliaPackaging/Yggdrasil/pull/9588#issuecomment-2404289725 I disabled `aarch64-*-freebsd` support for now.

**Comment by ViralBShah** [comment]
Is this good to merge?

**Comment by visr** [comment]
Yes.

**Pull request merged**
