### PR TITLE
[PTSCOTCH] Version 7.0.4

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by amontoison** [comment]
@eschnett You compiled the last release of PTSCOTCH with MPITrampoline, do you have an idea what we should do to help Cmake to detect MPI?

**Comment by eschnett** [comment]
@amontoison I looked at your package description and I can't see anything that's obviously wrong. I'm looking at the build result `x86_64-linux-gnu-mpi+mpich` since this is the most straightforward one. This build shows the errors
```
[03:44:33] cd /workspace/srcdir/scotch/build/src/libscotch && /usr/bin/cmake -E copy /workspace/srcdir/scotch/src/libscotch/parser_yy.y /workspace/srcdir/scotch/build/src/libscotch
[03:44:33] Error relocating /workspace/destdir/lib/libmpi.so.12: __isnan: symbol not found
[03:44:33] Error relocating /workspace/destdir/lib/libmpi.so.12: backtrace_symbols: symbol not found
[03:44:33] Error relocating /workspace/destdir/lib/libmpi.so.12: backtrace: symbol not found
[03:44:33] Error relocating /workspace/destdir/lib/libmpi.so.12: __isinf: symbol not found
[03:44:33] Error relocating /workspace/destdir/lib/libmpi.so.12: __strdup: symbol not found
[03:44:33] Error relocating /workspace/destdir/lib/libmpi.so.12: random_r: symbol not found
[03:44:33] Error relocating /workspace/destdir/lib/libmpi.so.12: __sched_cpufree: symbol not found
[03:44:33] Error relocating /workspace/destdir/lib/libmpi.so.12: __sched_cpualloc: symbol not found
[03:44:33] Error relocating /workspace/destdir/lib/libmpi.so.12: initstate_r: symbol not found
[03:44:33] Error relocating /lib64/ld-linux-x86-64.so.2: unsupported relocation type 37
[03:44:33] make[2]: *** [src/libscotch/CMakeFiles/ptscotchf_h.dir/build.make:75: src/include/ptscotchf.h] Error 127
[03:44:33] make[1]: *** [CMakeFiles/Makefile2:585: src/libscotch/CMakeFiles/ptscotchf_h.dir/all] Error 2
[03:44:33] make[1]: *** Waiting for unfinished jobs....
```
which I don't understand. I don't know what "relocating" means in this context, or why cmake is trying to do that, or why the tool that relocates can't find the dependencies.

Can you change the build recipe to build serially (i.e. omit the `j${nproc}`), and maybe enable verbose output as well? This might tell us more about what is happening the the "relocating" is attempted.

**Comment by amontoison** [comment]
> Error relocating /workspace/destdir/lib/libmpi.so.12



> @amontoison I looked at your package description and I can't see anything that's obviously wrong. I'm looking at the build result `x86_64-linux-gnu-mpi+mpich` since this is the most straightforward one. This build shows the errors
> 
> ```
> [03:44:33] cd /workspace/srcdir/scotch/build/src/libscotch && /usr/bin/cmake -E copy /workspace/srcdir/scotch/src/libscotch/parser_yy.y /workspace/srcdir/scotch/build/src/libscotch
> [03:44:33] Error relocating /workspace/destdir/lib/libmpi.so.12: __isnan: symbol not found
> [03:44:33] Error relocating /workspace/destdir/lib/libmpi.so.12: backtrace_symbols: symbol not found
> [03:44:33] Error relocating /workspace/destdir/lib/libmpi.so.12: backtrace: symbol not found
> [03:44:33] Error relocating /workspace/destdir/lib/libmpi.so.12: __isinf: symbol not found
> [03:44:33] Error relocating /workspace/destdir/lib/libmpi.so.12: __strdup: symbol not found
> [03:44:33] Error relocating /workspace/destdir/lib/libmpi.so.12: random_r: symbol not found
> [03:44:33] Error relocating /workspace/destdir/lib/libmpi.so.12: __sched_cpufree: symbol not found
> [03:44:33] Error relocating /workspace/destdir/lib/libmpi.so.12: __sched_cpualloc: symbol not found
> [03:44:33] Error relocating /workspace/destdir/lib/libmpi.so.12: initstate_r: symbol not found
> [03:44:33] Error relocating /lib64/ld-linux-x86-64.so.2: unsupported relocation type 37
> [03:44:33] make[2]: *** [src/libscotch/CMakeFiles/ptscotchf_h.dir/build.make:75: src/include/ptscotchf.h] Error 127
> [03:44:33] make[1]: *** [CMakeFiles/Makefile2:585: src/libscotch/CMakeFiles/ptscotchf_h.dir/all] Error 2
> [03:44:33] make[1]: *** Waiting for unfinished jobs....
> ```
> 
> which I don't understand. I don't know what "relocating" means in this context, or why cmake is trying to do that, or why the tool that relocates can't find the dependencies.
> 
> Can you change the build recipe to build serially (i.e. omit the `j${nproc}`), and maybe enable verbose output as well? This might tell us more about what is happening the the "relocating" is attempted.

@eschnett Yes, I did the modifications.

**Comment by amontoison** [comment]
@eschnett I finally found the culprit! A binary compiled for the host with the host compiler was linked with the MPI library for the build platform.

**Pull request merged**
