### PR TITLE
Build gdb 14 and use a newer python, 2nd try

### PR DESCRIPTION
**Pull request by fxcoudert**
Trying my fix for https://github.com/JuliaPackaging/Yggdrasil/pull/8413

### CODE REVIEW

**Comment by fxcoudert** [comment]
I've tried to reproduce this locally, cross-building GCC for the same target, but it works for me:

```
checking build system type... aarch64-apple-darwin23.4.0
checking host system type... i686-w64-mingw32
```

It detects that `vsnprintf` should not be compiled, and I don't see the error. I would need to get access to `libiberty/config.log` from the build machine to understand what is happening.

**Comment by fxcoudert** [comment]
There error is:

```
[11:35:18] configure:6859: checking for vsnprintf
[11:35:18] configure:6859: cc -o conftest.exe -g -O2       -Wl,--stack,12582912 conftest.c  >&5
[11:35:18] conftest.c:107:6: warning: conflicting types for built-in function 'vsnprintf'; expected 'int(char *, unsigned int,  const char *, char *)' [-Wbuiltin-declaration-mismatch]
[11:35:18]   107 | char vsnprintf ();
[11:35:18]       |      ^~~~~~~~~
[11:35:18] conftest.c:95:1: note: 'vsnprintf' is declared in header '<stdio.h>'
[11:35:18]    94 | # include <limits.h>
[11:35:18]    95 | #else
[11:35:18] /opt/i686-w64-mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld: /opt/i686-w64-mingw32/bin/../i686-w64-mingw32/sys-root/lib/../lib/libmsvcrt.a(lib32_libmsvcrt_extra_a-_vscprintf.o): in function `_mingw_get_msvcrt_handle':
[11:35:18] /workspace/srcdir/mingw-w64-v11.0.1/mingw-w64-crt/include/msvcrt.h:9: undefined reference to `_imp__GetModuleHandleW@4'
[11:35:18] /opt/i686-w64-mingw32/bin/../lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld: /opt/i686-w64-mingw32/bin/../i686-w64-mingw32/sys-root/lib/../lib/libmsvcrt.a(lib32_libmsvcrt_extra_a-_vscprintf.o): in function `init_vscprintf':
[11:35:18] /workspace/srcdir/mingw-w64-v11.0.1/mingw-w64-crt/stdio/_vscprintf.c:73: undefined reference to `_imp__GetProcAddress@8'
[11:35:18] collect2: error: ld returned 1 exit status
[11:35:18] configure:6859: $? = 1
[11:35:18] configure: failed program was:
[11:35:18] | /* confdefs.h */
[11:35:18] | #define PACKAGE_NAME ""
[11:35:18] | #define PACKAGE_TARNAME ""
[11:35:18] | #define PACKAGE_VERSION ""
[11:35:18] | #define PACKAGE_STRING ""
[11:35:18] | #define PACKAGE_BUGREPORT ""
[11:35:18] | #define PACKAGE_URL ""
[11:35:18] | #define STDC_HEADERS 1
[11:35:18] | #define HAVE_SYS_TYPES_H 1
[11:35:18] | #define HAVE_SYS_STAT_H 1
[11:35:18] | #define HAVE_STDLIB_H 1
[11:35:18] | #define HAVE_STRING_H 1
[11:35:18] | #define HAVE_MEMORY_H 1
[11:35:18] | #define HAVE_STRINGS_H 1
[11:35:18] | #define HAVE_INTTYPES_H 1
[11:35:18] | #define HAVE_STDINT_H 1
[11:35:18] | #define HAVE_UNISTD_H 1
[11:35:18] | #define __EXTENSIONS__ 1
[11:35:18] | #define _ALL_SOURCE 1
[11:35:18] | #define _GNU_SOURCE 1
[11:35:18] | #define _POSIX_PTHREAD_SEMANTICS 1
[11:35:18] | #define _TANDEM_SOURCE 1
[11:35:18] | #define _FILE_OFFSET_BITS 64
[11:35:18] | #define HAVE_SYS_FILE_H 1
[11:35:18] | #define HAVE_SYS_PARAM_H 1
[11:35:18] | #define HAVE_LIMITS_H 1
[11:35:18] | #define HAVE_STDLIB_H 1
[11:35:18] | #define HAVE_MALLOC_H 1
[11:35:18] | #define HAVE_STRING_H 1
[11:35:18] | #define HAVE_UNISTD_H 1
[11:35:18] | #define HAVE_STRINGS_H 1
[11:35:18] | #define HAVE_SYS_TIME_H 1
[11:35:18] | #define HAVE_TIME_H 1
[11:35:18] | #define HAVE_SYS_STAT_H 1
[11:35:18] | #define HAVE_FCNTL_H 1
[11:35:18] | #define HAVE_STDINT_H 1
[11:35:18] | #define HAVE_PROCESS_H 1
[11:35:18] | #define TIME_WITH_SYS_TIME 1
[11:35:18] | #define SIZEOF_INT 4
[11:35:18] | #define SIZEOF_LONG 4
[11:35:18] | #define SIZEOF_SIZE_T 4
[11:35:18] | #define HAVE_LONG_LONG 1
[11:35:18] | #define SIZEOF_LONG_LONG 8
[11:35:18] | #define UNSIGNED_64BIT_TYPE uint64_t
[11:35:18] | #define HAVE_INTPTR_T 1
[11:35:18] | #define HAVE_UINTPTR_T 1
[11:35:18] | #define HAVE_UINTPTR_T 1
[11:35:18] | #define HAVE_SYS_ERRLIST 1
[11:35:18] | #define HAVE_SYS_NERR 1
[11:35:18] | #define HAVE_ASPRINTF 1
[11:35:18] | #define HAVE_ATEXIT 1
[11:35:18] | #define HAVE_BASENAME 1
[11:35:18] | #define HAVE_BSEARCH 1
[11:35:18] | #define HAVE_CALLOC 1
[11:35:18] | #define HAVE_CLOCK 1
[11:35:18] | #define HAVE_GETCWD 1
[11:35:18] | #define HAVE_GETPAGESIZE 1
[11:35:18] | #define HAVE_GETTIMEOFDAY 1
[11:35:18] | #define HAVE_MEMCHR 1
[11:35:18] | #define HAVE_MEMCMP 1
[11:35:18] | #define HAVE_MEMCPY 1
[11:35:18] | #define HAVE_MEMMOVE 1
[11:35:18] | #define HAVE_MEMPCPY 1
[11:35:18] | #define HAVE_MEMSET 1
[11:35:18] | #define HAVE_PUTENV 1
[11:35:18] | #define HAVE_RENAME 1
[11:35:18] | #define HAVE_STRCASECMP 1
[11:35:18] | #define HAVE_STRCHR 1
[11:35:18] | #define HAVE_STRDUP 1
[11:35:18] | #define HAVE_STRNCASECMP 1
[11:35:18] | #define HAVE_STRNLEN 1
[11:35:18] | #define HAVE_STRRCHR 1
[11:35:18] | #define HAVE_STRSTR 1
[11:35:18] | #define HAVE_STRTOD 1
[11:35:18] | #define HAVE_STRTOL 1
[11:35:18] | #define HAVE_STRTOUL 1
[11:35:18] | #define HAVE_STRTOLL 1
[11:35:18] | #define HAVE_STRTOULL 1
[11:35:18] | #define HAVE_TMPNAM 1
[11:35:18] | #define HAVE_VASPRINTF 1
[11:35:18] | #define HAVE_VFPRINTF 1
[11:35:18] | #define HAVE_VPRINTF 1
[11:35:18] | /* end confdefs.h.  */
[11:35:18] | /* Define vsnprintf to an innocuous variant, in case <limits.h> declares vsnprintf.
[11:35:18] |    For example, HP-UX 11i <limits.h> declares gettimeofday.  */
[11:35:18] | #define vsnprintf innocuous_vsnprintf
[11:35:18] |
[11:35:18] | /* System header to define __stub macros and hopefully few prototypes,
[11:35:18] |     which can conflict with char vsnprintf (); below.
[11:35:18] |     Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
[11:35:18] |     <limits.h> exists even on freestanding compilers.  */
[11:35:18] |
[11:35:18] | #ifdef __STDC__
[11:35:18] | # include <limits.h>
[11:35:18] | #else
[11:35:18] | # include <assert.h>
[11:35:18] | #endif
[11:35:18] |
[11:35:18] | #undef vsnprintf
[11:35:18] |
[11:35:18] | /* Override any GCC internal prototype to avoid an error.
[11:35:18] |    Use char because int might match the return type of a GCC
[11:35:18] |    builtin and then its argument prototype would still apply.  */
[11:35:18] | #ifdef __cplusplus
[11:35:18] | extern "C"
[11:35:18] | #endif
[11:35:18] | char vsnprintf ();
[11:35:18] | /* The GNU C library defines this for functions which it implements
[11:35:18] |     to always fail with ENOSYS.  Some functions are actually named
[11:35:18] |     something starting with __ and the normal name is an alias.  */
[11:35:18] | #if defined __stub_vsnprintf || defined __stub___vsnprintf
[11:35:18] | choke me
[11:35:18] | #endif
[11:35:18] |
[11:35:18] | int
[11:35:18] | main ()
[11:35:18] | {
[11:35:18] | return vsnprintf ();
[11:35:18] |   ;
[11:35:18] |   return 0;
[11:35:18] | }
[11:35:18] configure:6859: result: no
```

It is discussed here: https://sourceforge.net/p/mingw-w64/mailman/message/37840691/
where it is said that it is fixed in GCC 11.1.0 and later.

**Comment by giordano** [comment]
For the sake of getting a build of gdb with python 3.10 to be used in BugReporting, I think it'd be better to stick to v12.1 as done at the end in #8413, since BugReporting at the moment requires major version 12: https://github.com/JuliaLang/BugReporting.jl/blob/fec2ece8be317462fe8b93ffca56e5b228d0b341/Project.toml#L22.  We can do the upgrade to v14 in a follow up PR

**Comment by giordano** [comment]
But thanks a lot for the investigation!

**Comment by fxcoudert** [comment]
Probably 12.1 will build with GCC 11.1.0 as well

**Pull request closed without merging**
