### PR TITLE
[GMT] downgrade GDAL version dependency due to Windows break

### PR DESCRIPTION
**Pull request by joa-quim**

### CODE REVIEW

**Comment by visr** [comment]
I think this can be closed. It wouldn't have helped, see https://github.com/JuliaGeo/GDAL.jl/issues/173#issuecomment-2131414853, but there is also https://github.com/JuliaRegistries/General/pull/107721 now.

**Comment by joa-quim** [comment]
Closing as this is being addressed elsewhere.

**Comment by joa-quim** [comment]
Reopen. I'm confused now. This PR requests downgrading to  GDAL_jll "301.800.500". At this time what I need is to restore the GMT_jll buiding. It is unfortunate that this has happen at this time where students got their GMT.jl version broken and I need to restore it to a function state ASAP.

**Comment by joa-quim** [comment]
Closing again as, with latest fixes GMT_jll builds again.

**Pull request closed without merging**
