### PR TITLE
Wizard recipe: Bison-v3.5.2

### PR DESCRIPTION
**Pull request by visr**
This pull request contains a new build recipe I built using the BinaryBuilder.jl wizard:

* Package name: Bison
* Version: v3.5.2

@staticfloat please review and merge.

### CODE REVIEW

**Comment by visr** [comment]
Windows is disabled here such that I could get to the end of the Wizard and send this PR. But I'd like Windows support as well, this is the failure it got:

```
[16:11:15] make[2]: Entering directory '/workspace/srcdir/bison-3.5.2'
[16:11:15] cc -std=gnu11 -DEXEEXT=\".exe\"   -I. -I./lib -I. -I./lib -DINSTALLDIR=\"/workspace/destdir/bin\"    -g -O2 -MT src/bison-files.o -MD -MP -MF src/.deps/bison-files.Tpo -c -o src/bison-files.o `test -f 'src/files.c' || echo './'`src/files.c
[16:11:16] In file included from src/gram.h:106:0,
[16:11:16]                  from src/files.c:37:
[16:11:16] src/symtab.h:250:16: error: 'accept' redeclared as different kind of symbol
[16:11:16]  extern symbol *accept;
[16:11:16]                 ^
[16:11:16] In file included from ./lib/configmake.h:3:0,
[16:11:16]                  from src/files.c:24:
[16:11:16] /opt/x86_64-w64-mingw32/x86_64-w64-mingw32/sys-root/include/winsock2.h:973:37: note: previous declaration of 'accept' was here
[16:11:16]    WINSOCK_API_LINKAGE SOCKET WSAAPI accept(SOCKET s,struct sockaddr *addr,int *addrlen);
[16:11:16]                                      ^
[16:11:16] make[2]: *** [Makefile:7078: src/bison-files.o] Error 1
[16:11:16] make[2]: Leaving directory '/workspace/srcdir/bison-3.5.2'
[16:11:16] make[1]: *** [Makefile:8323: install-recursive] Error 1
[16:11:16] make[1]: Leaving directory '/workspace/srcdir/bison-3.5.2'
[16:11:16] make: *** [Makefile:8779: install] Error 2
```
Not sure how to resolve it...

Also cc @tanmaykm who previously made https://github.com/tanmaykm/BisonBuilder/blob/master/build_tarballs.jl.

Ref https://github.com/tanmaykm/Thrift.jl/issues/29#issuecomment-586718014

**Comment by giordano** [comment]
I think this has never been compiled with MinGW, there are a lot of issues.  Some of them looks quite serious and would require serious work to fix them, like
```
src/location.c:28:23: fatal error: sys/ioctl.h: No such file or directory
 #include <sys/ioctl.h>
                       ^
compilation terminated.
```

**Comment by visr** [comment]
Hmm I see. Hoped it was something simple :)

Looking around I found some 5 year old patches here: https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-bison.

More up to date but a MSVC port can be found here: https://github.com/lexxmark/winflexbison/releases.

**Comment by giordano** [comment]
> Looking around I found some 5 year old patches here: msys2/MINGW-packages:mingw-w64-bison@master .

That was the first think I looked at, but it's super old and doesn't seem to be relevant anymore

**Comment by giordano** [comment]
> More up to date but a MSVC port can be found here: lexxmark/winflexbison/releases.

We don't use Visual Studio Code :confused:

**Comment by staticfloat** [comment]
Man, why do you need `bison`?!

**Comment by visr** [comment]
Ha, it's needed to build the Thrift to Julia compiler: https://github.com/tanmaykm/Thrift.jl/issues/29#issuecomment-586718014

Currently it is built by the old BinaryBuilder, and not available on Windows. Note that Thrift.jl can still be used on Windows, only compiling .thrift to .jl then needs to be done in advance on Linux.

We can leave out Windows for now, and keep suggesting the workaround. Then at least we've ported the existing builder over. Alternatively, since the patches at https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-bison seems to be last updated for bison 3.0.3, we build an old version for which there are mingw patches available. In the [Thrift docs](https://thrift.apache.org/docs/install/) it doesn't mention a minimum required version, so probably that is fine too.

But yeah, I care about NetCDF (#513) being available on Windows than this ;)

**Comment by staticfloat** [comment]
Yeah, I say let's skip windows for now.  :)

**Pull request merged**
