### PR TITLE
MAGEMin 1.2.8

### PR DESCRIPTION
**Pull request by NicolasRiel**
- Added new options to PlotPseudosection.app (Matlab GUI). Now the legacy (back-up solver) can be selected, and bulk-rock compositions can be loaded from file. If Fe2O3 is provided the bulk-rock composition will be automatically converted to the right format.
- Fixed error in the BrentQ root finding function that was causing crash during Parallel calculation
- Fixed memory leak when using the Julia wrapper (MAGEMin_C)
- Fixed bug in MAGEMin_EquilibriumPath.mlx (Matlab notebook)
- Added pure phase: wollastonite, pseudowollastonite and nepheline
- Added EOS for CO2
- Documentation update

### CODE REVIEW

**Comment by giordano** [comment]
@NicolasRiel as a general remark, it's good practice to open a PR from a branch with a _different_ name than the target branch, otherwise you end up with pushing multiple unrelated commits like it has happened in this PR.

**Comment by NicolasRiel** [comment]
Oh sorry! 
I am not quite sure I fully understand the branch name problem, could you explain to me with a bit more details?

Does that mean that I have to fork Yggdrasil each time I want to make a pull request?

**Comment by NicolasRiel** [comment]
Oh I see, I should create a new branch on my fork right?

**Comment by giordano** [comment]
This isn't specific to Yggdrasil at all, but a general git practice: it's an anti-pattern to create a PR from the same branch you want to target.  Please read https://blog.jasonmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/  for more information.

**Comment by NicolasRiel** [comment]
Thank you!

**Comment by NicolasRiel** [comment]
Hi Mosé,
The new version have been merged with the General/Registry.toml However when I try to update the package to get the new version 1.2.8, it is not found and I am left with the previous one. Do you have any idea why this would happen?

Thanks!

**Comment by giordano** [comment]
What version of Julia?  If 1.7+, does setting the environment variable
```sh
JULIA_PKG_SERVER_REGISTRY_PREFERENCE="eager"
```
help?

**Comment by NicolasRiel** [comment]
I have the Julia version 1.8.5

Using the command you provided does not seem to help :\

`julia> JULIA_PKG_SERVER_REGISTRY_PREFERENCE="eager"
"eager"

(@v1.8) pkg> update MAGEMin_jll
    Updating registry at `C:\Users\Seph\.julia\registries\General.toml`
  No Changes to `C:\Users\Seph\.julia\environments\v1.8\Project.toml`
  No Changes to `C:\Users\Seph\.julia\environments\v1.8\Manifest.toml`

(@v1.8) pkg> add MAGEMin_jll@1.2.8
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package MAGEMin_jll [763ebaa8]:
 MAGEMin_jll [763ebaa8] log:
 ├─possible versions are: 1.0.1-1.2.7 or uninstalled
 └─restricted to versions 1.2.8 by an explicit requirement — no versions left
`

**Comment by giordano** [comment]
I said [environment variable](https://en.wikipedia.org/wiki/Environment_variable) :slightly_smiling_face: Either do this in your shell
```
export JULIA_PKG_SERVER_REGISTRY_PREFERENCE="eager"
julia
```
or
```
JULIA_PKG_SERVER_REGISTRY_PREFERENCE="eager" julia
```
or, inside julia,
```
ENV["JULIA_PKG_SERVER_REGISTRY_PREFERENCE"] ="eager"
```

If this works, you may want to add
```
export JULIA_PKG_SERVER_REGISTRY_PREFERENCE="eager"
```
to your shell init script (`.bashrc`, `.zshrc` or whatever)

**Comment by NicolasRiel** [comment]
Oh my bad! 

I just tried on Linux, and it works! MAGEMin_jll has been updated to 1.2.8

Does everyone that want to use the package have to do that? It seems a bit odd no?

Thank you so much for your help,

Nicolas

**Comment by giordano** [comment]
Not forever, it only happens occasionally that the PkgServer trails a bit back, so latest packages may not be readily available.  In a few hours your package should make to the PkgServer, also without exporting the environment variable.

**Comment by NicolasRiel** [comment]
Ok perfect, thanks again!

**Pull request merged**
