### PR TITLE
PDAL: New version 2.8.2

### PR DESCRIPTION
**Pull request by eschnett**
Closes https://github.com/JuliaPackaging/Yggdrasil/issues/9985

### CODE REVIEW

**Comment by evetion** [comment]
It's certainly useful, thanks for the very quick action! ❤️ 

I'm only doubting the GDAL bounds, you choose the latest, which might be too new? I'm checking the sonames (this build has libgdal.36.dylib), so 36 = v3.10, and 35 = v3.9 (jll v301.902). This version is not used yet by GDAL.jl, which might lead to package conflicts on common downstream packages (GeoDataFrames, Rasters), so it might be safer to use v301.902 here. @visr what do you think?

**Comment by eschnett** [comment]
I though we had fixed this... All the `GDAL_jll @301` are supposed to be compatible. Are you saying that there are `GDAL_jll` versions that differ only in their minor version number and which are actually incompatible? These should then be `GDAL_jll @302`!

**Comment by evetion** [comment]
I'm not entirely sure here (I've always felt a bit out of my depth on these matters), hence me calling on visr.

That said, GDAL moves their GDAL_SOVERSION forward by one each minor version. Whether their ABI is actually compatible matters little if we [link](https://buildkite.com/julialang/yggdrasil/builds/15471#0193b1dc-c30e-47e5-a04e-1c1140bf4ba7/6-16207) to a specific version in these builds I guess:

```
[ Info: Linked library libgdal.36.dylib has been auto-mapped to @rpath/libgdal.36.dylib
```

**Comment by eschnett** [comment]
If this is so, then `GDAL_jll` should move their major version number forward by one for each minor version number change of GDAL. This is why the build recipe for `GDAL_jll` has a variable `version_offset`. It seems we forgot to bump it for the latest `GDAL_jll` update.

I'm tempted to disable the current (probably unused?) `GDAL_jll` for GDAL 3.10 to avoid breaking packages that would otherwise try to use it. We can then quickly re-release a new `GDAL_jll` with a bumped major version number.

We should also add a comment to the beginning of GDAL_jll's build recipe. I like reading comments from my past self.

**Comment by evetion** [comment]
FWIW not that many packages use GDAL_jll directly, so I would consider 3.10 unused of now. Of the [jll packages ](https://github.com/search?q=repo%3AJuliaPackaging%2FYggdrasil+GDAL_jll&type=code), only two set compat, so others can be assumed broken. Of direct deps GDAL.jl pins GDAL_jll, and ADRIA and GMT have compats via other packages (GeoDataFrames>ArchGDAL>GDAL, and via PROJ_jll respectively). Pinging @joa-quim to be sure.

**Comment by joa-quim** [comment]
GMT_jll directly sets a GDAL version
https://github.com/JuliaPackaging/Yggdrasil/blob/958380436934994ad20891ea87212a3e2a44fa96/G/GMT/build_tarballs.jl#L79

I confess that I'm nothing at easy with this version/compat things. And I would like to move to GDAL3.10 soon (was not possible when I looked not long ago).

**Comment by eschnett** [comment]
@giordano Would it be feasible to yank the current `GDAL_jll `301.1000`? It's incompatible with earlier `GDAL_jll @301`. Is that a proper usage of the yanking mechanism?

**Comment by joa-quim** [comment]
> Would it be feasible to yank the current  `GDAL_jll 301.1000`? It's incompatible with earlier `GDAL_jll @301`

Why incompatible? They are two different version builds. And as I mentioned above, I will want to make GMT.jl release that links to GDAL 3.10. GMT links directly to `GDAL_jll` so it should works (though some versions have broke in the past).

**Comment by eschnett** [comment]
They are incompatible because their shared library sonames don't match. If you build PDAL_jll against GDAL_jll 3.9 then you cannot use PDAL_jll with GDAL_jll 3.10. This is "cannot use" in the sense "Julia will not detect it, things will abort with a low-level error message at run time".

This isn't supposed to happen. Most packages behave differently. If you e.g. build against OpenSSL 3.0.9, then you can run with OpenSSL 3.0.15 just fine.

To tell Julia about this (the fact that the sonames differ) we will need to bump the major version number of GDAL_jll when we re-release it for GDAL 3.10.

**Comment by joa-quim** [comment]
OK, I'm fine with the replacement (re-release). I'm in no hurry to use 3.10

**Comment by evetion** [comment]
I'm fine with merging this PR as is 👍🏻

**Comment by eschnett** [comment]
Let's wait a day or two. I'm working on Arrow_jll and GDAL_jll at the moment.

**Pull request merged**
