### PR TITLE
Added OpenBLASConsistentFPCSR

### PR DESCRIPTION
**Pull request by orkolorko**
We add a package OpenBLASConsistentFPCSR, which is nothing else than OpenBLAS
compiled with the `CONSISTENT_FPCSR=1` flag enabled, following issues 

https://github.com/JuliaPackaging/Yggdrasil/issues/6214
and
https://github.com/JuliaIntervals/IntervalLinearAlgebra.jl/issues/131

This flag controls the fact that, as the thread pool is started, all the threads have the same rounding mode; this flag is not implemented by default since in principle this may affect performance and there are no benchmarks proving the opposite.

The packages is essentially the same as OpenBLAS with two differences:

- we removed the build recipes for 32 bit BLAS (maybe it is not a good idea, but it should be not so much work to add them again)
- we added the flag `CONSISTENT_FPCSR=1` at
https://github.com/orkolorko/Yggdrasil/blob/697e6e7314378e42617c223bbc284780f00270ee/O/OpenBLASConsistentFPCSR/common.jl#L86
- we changed the names of the built packages from "OpenBLAS*" to "OpenBLASConsistentFPCSR*"

### CODE REVIEW

**Comment by giordano** [comment]
I'd only use the latest version, there's little point in building all previous ones.

**Comment by orkolorko** [comment]
Ok, even if it seems that this flag is supported on aarch64
https://github.com/xianyi/OpenBLAS/commit/84453b924fe7695029cad974dfe0cf7bf6ffe0f6
the build is failing.

I will work to exclude unsupported platforms.

**Comment by orkolorko** [comment]
@giordano the compilation went through without  any problems, but I needed to restrict to x86_64

**Comment by giordano** [comment]
Thanks for your contribution!

**Comment by orkolorko** [comment]
Thank you @giordano!

**Pull request merged**
