### PR TITLE
Try -O3 for ffmpeg & x264

### PR DESCRIPTION
**Pull request by ianshmean**
Just an idea to try and eek more performance out on aarch64

### CODE REVIEW

**Comment by ViralBShah** [comment]
Have you looked at past build logs for these packages to see what flags they are using? Usually packages such as these have other arch-specific flags you can pass. 

The bigger issue is that we do not have a good mechanism to build CPU-family specific binaries.

**Comment by ViralBShah** [comment]
@ianshmean Were you able to try out the binaries from this? I am curious if they are faster even on x86.

**Comment by ianshmean** [comment]
I just tried by benchmarking, then switching out the artifacts manually (which was a pain of approval on MacOS!) and then re-benchmarking.

4.6% faster, but within the noise.. 🤷‍♂️

```
│ Row │ cat         │ testname                  │ units   │ ref_res                                  │ test_res                                 │ factor    │
│     │ String      │ String                    │ String? │ Any                                      │ Any                                      │ Any       │
├─────┼─────────────┼───────────────────────────┼─────────┼──────────────────────────────────────────┼──────────────────────────────────────────┼───────────┤
│ 1   │ info        │ SysBenchVer               │ missing │ 0.3.2                                    │ 0.3.2                                    │ Equal     │
│ 2   │ info        │ JuliaVer                  │ missing │ 1.4.1                                    │ 1.4.1                                    │ Equal     │
│ 3   │ info        │ OS                        │ missing │ macOS (x86_64-apple-darwin18.7.0)        │ macOS (x86_64-apple-darwin18.7.0)        │ Equal     │
│ 4   │ info        │ CPU                       │ missing │ Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz │ Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz │ Equal     │
│ 5   │ info        │ WORD_SIZE                 │ missing │ 64                                       │ 64                                       │ Equal     │
│ 6   │ info        │ LIBM                      │ missing │ libopenlibm                              │ libopenlibm                              │ Equal     │
│ 7   │ info        │ LLVM                      │ missing │ libLLVM-8.0.1 (ORCJIT, skylake)          │ libLLVM-8.0.1 (ORCJIT, skylake)          │ Equal     │
│ 8   │ info        │ GPU                       │ missing │ missing                                  │ missing                                  │ Not Equal │
│ 9   │ cpu         │ FloatMul                  │ ms      │ 1.711e-6                                 │ 1.714e-6                                 │ 1.00175   │
│ 10  │ cpu         │ FusedMulAdd               │ ms      │ 1.7119999999999999e-6                    │ 1.705e-6                                 │ 0.995911  │
│ 11  │ cpu         │ FloatSin                  │ ms      │ 5.048e-6                                 │ 4.934999999999999e-6                     │ 0.977615  │
│ 12  │ cpu         │ VecMulBroad               │ ms      │ 4.723529411764706e-5                     │ 4.699191102123357e-5                     │ 0.994847  │
│ 13  │ cpu         │ CPUMatMul                 │ ms      │ 0.038171                                 │ 0.037243                                 │ 0.975688  │
│ 14  │ cpu         │ MatMulBroad               │ ms      │ 0.02144575                               │ 0.020010857142857143                     │ 0.933092  │
│ 15  │ cpu         │ 3DMulBroad                │ ms      │ 0.0014883                                │ 0.0017037999999999999                    │ 1.1448    │
│ 16  │ cpu         │ peakflops                 │ flops   │ 2.445323596014019e11                     │ 2.514171599628481e11                     │ 1.02815   │
│ 17  │ cpu         │ FFMPEGH264Write           │ ms      │ 154.930265                               │ 147.813616                               │ 0.954065  │ <<
│ 18  │ mem         │ DeepCopy                  │ ms      │ 0.0002134237288135593                    │ 0.00020293437499999998                   │ 0.950852  │
│ 19  │ mem         │ Bandwidth10kB             │ MiB/s   │ 96724.22923250163                        │ 96742.89886014824                        │ 1.00019   │
│ 20  │ mem         │ Bandwidth100kB            │ MiB/s   │ 49636.928975498355                       │ 51001.353890916624                       │ 1.02749   │
│ 21  │ mem         │ Bandwidth1MB              │ MiB/s   │ 30391.150937101655                       │ 30148.083217091327                       │ 0.992002  │
│ 22  │ mem         │ Bandwidth10MB             │ MiB/s   │ 11934.205758984996                       │ 12249.962960188797                       │ 1.02646   │
│ 23  │ mem         │ Bandwidth100MB            │ MiB/s   │ 9365.244925929888                        │ 9104.533652943339                        │ 0.972162  │
│ 24  │ diskio      │ DiskWrite1KB              │ ms      │ 0.1298155                                │ 0.132302                                 │ 1.01915   │
│ 25  │ diskio      │ DiskWrite1MB              │ ms      │ 0.449156                                 │ 0.40548                                  │ 0.90276   │
│ 26  │ diskio      │ DiskRead1KB               │ ms      │ 0.0696805                                │ 0.0727355                                │ 1.04384   │
│ 27  │ diskio      │ DiskRead1MB               │ ms      │ 0.879918                                 │ 0.889036                                 │ 1.01036   │
│ 28  │ loading     │ JuliaLoad                 │ ms      │ 246.085102                               │ 238.220408                               │ 0.968041  │
│ 29  │ compilation │ compilecache              │ ms      │ 368.1391635                              │ 361.8034345                              │ 0.98279   │
│ 30  │ compilation │ success_create_expr_cache │ ms      │ 356.786525                               │ 353.3215305                              │ 0.990288  │
│ 31  │ compilation │ create_expr_cache         │ ms      │ 11.53056                                 │ 10.591928                                │ 0.918596  │
│ 32  │ compilation │ output-ji-substart        │ ms      │ 37.787221500000015                       │ 65.25288800000001                        │ 1.72685   │
```

**Comment by ViralBShah** [comment]
I bet ffmpeg has all sorts of simd optimizations that we are unable to enable. But I'm sure we'll take the extra 4-5%, even if within noise.

**Comment by ianshmean** [comment]
I’m not convinced the 5% is real. The measurement noise does seem on that range.. but at least it doesn’t seem to hurt! And I have seen mentions of people compiling with -O3 elsewhere.

**Comment by staticfloat** [comment]
@ianshmean do you want this to eventually be merged?  If so, mark this as non-draft. :)

**Comment by ianshmean** [comment]
I don't think we saw reliable evidence of a performance improvement, but it didn't seem to break anything.. What do you think? I'll un-draft.. Feel free to close or merge

**Comment by ViralBShah** [comment]
Closing this for now, but can always reopen if necessary.

**Pull request closed without merging**
