### PR TITLE
[libsharp2] Enable multiarch and build for experimental platforms

### PR DESCRIPTION
**Pull request by giordano**
CC: @ziotom78

### CODE REVIEW

**Comment by giordano** [comment]
macOS x86_64 is failing with
```
[19:21:47] libtool: link: cc -dynamiclib  -o .libs/libsharp2.0.dylib  libsharp2/.libs/pocketfft.o libsharp2/.libs/sharp_utils.o libsharp2/.libs/sharp.o libsharp2/.libs/sharp_almhelpers.o libsharp2/.libs/sharp_core.o libsharp2/.libs/sharp_geomhelpers.o libsharp2/.libs/sharp_legendre_roots.o libsharp2/.libs/sharp_ylmgen_c.o   -Wl,-force_load,./.libs/libavx.a -Wl,-force_load,./.libs/libavx2.a -Wl,-force_load,./.libs/libfma.a -Wl,-force_load,./.libs/libfma4.a -Wl,-force_load,./.libs/libavx512f.a  -lm    -install_name  /workspace/destdir/lib/libsharp2.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module
[19:21:47] Undefined symbols for architecture x86_64:
[19:21:47]   "___cpu_indicator_init", referenced from:
[19:21:47]       _have_fma4 in sharp_core.o
[19:21:47]       _have_fma in sharp_core.o
[19:21:47]       _have_avx2 in sharp_core.o
[19:21:47]       _have_avx in sharp_core.o
[19:21:47]   "___cpu_model", referenced from:
[19:21:47]       _have_fma4 in sharp_core.o
[19:21:47]       _have_fma in sharp_core.o
[19:21:47]       _have_avx2 in sharp_core.o
[19:21:47]       _have_avx in sharp_core.o
[19:21:47] ld: symbol(s) not found for architecture x86_64
[19:21:47] clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
```
This is similar to https://github.com/tensorflow/tensorflow/issues/7223 and https://github.com/numpy/numpy/issues/8130, but I don't really understand what the solutions were, I'm not even sure they're relevant here since the bug was supposedly fixed upstream in LLVM.  I think I'm going to skip multiarch for macOS

Instead Windows x86_64 is failing with:
```
[19:21:45] /bin/sh ./libtool  --tag=CC   --mode=link cc -fopenmp -DMULTIARCH -version-info 0:0:0 -no-undefined  -o libsharp2.la -rpath /workspace/destdir/lib libsharp2/pocketfft.lo libsharp2/sharp_utils.lo libsharp2/sharp.lo libsharp2/sharp_almhelpers.lo libsharp2/sharp_core.lo libsharp2/sharp_geomhelpers.lo libsharp2/sharp_legendre_roots.lo libsharp2/sharp_ylmgen_c.lo libavx.la libavx2.la libfma.la libfma4.la libavx512f.la -lm
[19:21:45] libtool: link: cc -shared  libsharp2/.libs/pocketfft.o libsharp2/.libs/sharp_utils.o libsharp2/.libs/sharp.o libsharp2/.libs/sharp_almhelpers.o libsharp2/.libs/sharp_core.o libsharp2/.libs/sharp_geomhelpers.o libsharp2/.libs/sharp_legendre_roots.o libsharp2/.libs/sharp_ylmgen_c.o  -Wl,--whole-archive ./.libs/libavx.a ./.libs/libavx2.a ./.libs/libfma.a ./.libs/libfma4.a ./.libs/libavx512f.a -Wl,--no-whole-archive   -fopenmp   -fopenmp -o .libs/libsharp2-0.dll -Wl,--enable-auto-image-base -Xlinker --out-implib -Xlinker .libs/libsharp2.dll.a
[19:21:45] ./.libs/libavx512f.a(libavx512f_la-sharp_core_inc.o):sharp_core_inc.c:(.text+0x81): undefined reference to `_mm512_reduce_add_pd'
[19:21:45] ./.libs/libavx512f.a(libavx512f_la-sharp_core_inc.o):sharp_core_inc.c:(.text+0xa9): undefined reference to `_mm512_reduce_add_pd'
[19:21:45] ./.libs/libavx512f.a(libavx512f_la-sharp_core_inc.o):sharp_core_inc.c:(.text+0x11d): undefined reference to `_mm512_reduce_add_pd'
[19:21:45] ./.libs/libavx512f.a(libavx512f_la-sharp_core_inc.o):sharp_core_inc.c:(.text+0x145): undefined reference to `_mm512_reduce_add_pd'
[19:21:45] collect2: error: ld returned 1 exit status
[19:21:45] make: *** [Makefile:804: libsharp2.la] Error 1
```
This looks the same as the error reported in [this thread in HEALPix mailing list](https://sourceforge.net/p/healpix/mailman/healpix-support/thread/308A446D-A33B-4302-A287-45FFC3240F6D%40getmailspring.com/#msg36890712).  Solved by using GCC 7 as suggested there.

**Comment by ziotom78** [comment]
Thanks @giordano, if I understand correctly this improvement will silently propagate to users that install [Libsharp.jl](https://github.com/ziotom78/Libsharp.jl) (which uses `libsharp2`): the Libsharp.jl repository does not contain `Manifest.toml`, and therefore it should pick the latest available version, right?

**Comment by giordano** [comment]
The `Manifest.toml` doesn't really matter for installing dependencies, only `compat` bounds in `Project.toml` would be relevant.  `Manifest.toml` is only picked up in continuous integration jobs.

To more directly answer your question, yes, the new `libsharp2_jll` is already available to all users (well, in Julia v1.6+) and I can confirm tests of `Healpix.jl` pass on a MacBook with M1 CPU (Apple Silicon)

**Comment by ziotom78** [comment]
Great news! Thanks!

**Pull request merged**
