### PR TITLE
update libuv to 2+1.29.1-julia proposed

### PR DESCRIPTION
**Pull request by vtjnash**
For https://github.com/JuliaLang/julia/pull/32280

### CODE REVIEW

**Comment by staticfloat** [comment]
Should this wait until the Julia PR is merged?

**Comment by staticfloat** [comment]
And is there any reason we might want to maintain this side-by-side with the other `libuv`, or do we only need this one from now on?

**Comment by vtjnash** [comment]
We should probably update Julia to use the 2+1.24.0-julia binary first (and make sure those work), then merge this, then merge that PR.

What’s the other `libuv`?

**Comment by staticfloat** [comment]
> What’s the other `libuv`?

Nevermind, nothing but the gitsha and version is changing here, so it doesn't matter.

**Comment by vtjnash** [comment]
OK, can you merge this now, get binaries, then update https://github.com/JuliaLang/julia/pull/32280 for me?

**Pull request merged**
