### PR TITLE
add Microsoft MPI

### PR DESCRIPTION
**Pull request by simonbyrne**
It wasn't clear how to get this to build directly, since it requires Visual Studio, so instead we download and extract the Micrsoft-provided binaries.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Is this basically just MPICH? In which case, should we hack the MPICH script to provide these binaries on Windows? Or should BB have support for packages to provide certain interfaces, much in the way that Debian has `Provides`?

**Comment by giordano** [comment]
> Or should BB have support for packages to provide certain interfaces, much in the way that Debian has the Provides mechanism where multiple packages can provide say, blas, or mpi, and there's a way to pick a default?


This is more on the Pkg's side rather than BinaryBuilder's one. I've also been wishing for a long time that we had a mechanism to provide alternatives to packages, exactly like what you mentioned in Debian

**Comment by simonbyrne** [comment]
> Is this basically just MPICH?

Not really: it's an MPICH derivative, but has a different ABI for example (so that if we did manage to compile MPICH on Windows, we wouldn't be able to swap them cleanly).

I do agree that some sort of mechanism to provide alternatives is required: we already do this for gfortran and libcxx (and implicitly for OS, arch and libc), so it would make sense to provide a generic way to do it for other cases where alternative libraries are available (BLAS, MPI, etc).

**Comment by giordano** [comment]
> Not really: it's an MPICH derivative, but has a different ABI for example (so that if we did manage to compile MPICH on Windows, we wouldn't be able to swap them cleanly).

Ok, so I assume we can merge this?

> I do agree that some sort of mechanism to provide alternatives is required: we already do this for gfortran and libcxx (and implicitly for OS, arch and libc), so it would make sense to provide a generic way to do it for other cases where alternative libraries are available (BLAS, MPI, etc).

It's true that we already have a mechanism to select the specific flavour of the artifact based on some conditions, but in this case we have fundamentally different artifacts that you can choose from, not just different flavours of a single one.  Like Viral, I'm a fan of Debian's approach on this: if two or more packages are interchangeable (i.e., provide the same API), we keep them as distinct artifacts/JLLs but we can choose one of them at install time.  The `Project.toml` file would indicate the "provided" package, the `Manifest.toml` package would record the package that was actually installed, for reproducibility.

**Comment by simonbyrne** [comment]
I was thinking in terms of dependent binaries, for example PETSc which requires an MPI implementation. 

You would specify something like `DependencyInterface("MPI")` in the dependency list, and that would expand the build matrix to build against e.g. both MPICH and OpenMPI on Linux & Mac, and against Microsoft MPI on Windows.

**Comment by giordano** [comment]
For this specific case were MPICH provides binaries for all platforms but Windows, and MicrosoftMPI only for Windows, you can depend on both packages, you only need to do something like
```julia
@static if Sys.iswindows()
    using MicrosoftMPI
else
    using MPICH
end
```
Not as nice as what you suggest, but it already works.

**Comment by simonbyrne** [comment]
Does that work for binaries as well?

**Comment by ViralBShah** [comment]
So, can we merge this package then? Nothing like using the solution that already works, and of course implementing better things as we go along.

**Comment by ViralBShah** [comment]
> Does that work for binaries as well?

Aren't these JLL things just regular Julia packages?

**Comment by giordano** [comment]
> Does that work for binaries as well?

I didn't try, but my feeling is that it should work, yes

**Comment by simonbyrne** [comment]
I meant for BinaryBuilder: e.g. can I do
```
dependencies = [Dependency("MPICH"), Dependency("MicrosoftMPI")]
```
and have them build on the union of available platforms?

**Comment by giordano** [comment]
Ah, yes, that works.  We use it already in many place, for platform-specific dependencies.  When an artifact is not available for the specific platform you only get a warning.

**Pull request merged**
