### PR TITLE
[PTSCOTCH] Add Builder

### PR DESCRIPTION
**Pull request by Wimmerer**
I'm not sure this is the best way to do this, if we had multi-jll builders that would be best. Right now I just build scotch and ptscotch but only copy ptscotch to the prefix.  The build script is otherwise exactly the same as SCOTCH_jll.

### CODE REVIEW

**Comment by Wimmerer** [comment]
No idea why I'm missing this symbol. Missing include somewhere maybe?

**Comment by Wimmerer** [comment]
@giordano any thoughts on why x86_64-linux-gnu is missing this symbol "_SCOTCHorderSaveMap" or where to look? The symbol is in both the SCOTCH_jll and this compilation's `libscotch.so` in the same directory as `libptscotch.so`. And only failing on this platform is weird. Unless dlopen isn't run for the other platforms?

**Comment by giordano** [comment]
> Unless dlopen isn't run for the other platforms?

You can dlopen libraries only for Julia's `HostPlatform()` :wink:

**Comment by giordano** [comment]
> any thoughts on why x86_64-linux-gnu is missing this symbol "_SCOTCHorderSaveMap" or where to look?

```console
% readelf -d libptscotch.so | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libmpi.so.12]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```
`libptscotch.so` doesn't link to `libscotch.so`, which defines the symbol:
```console
% nm libscotch.so | grep _SCOTCHorderSaveMap 
0000000000061f20 T _SCOTCHorderSaveMap
```
so the loader doesn't know where to find the symbol

**Comment by Wimmerer** [comment]
Interestingly the Debian package ptscotch also does not link to scotch.

**Comment by giordano** [comment]
I suspect we have to dlopen libscotch with `RTLD_GLOBAL` and not dlopen libptscotch automatically.  Not great, but if that's what they want...

**Comment by Wimmerer** [comment]
Can you elaborate? I know you're not supposed to link against *both* (`libptscotch` if you have MPI, otherwise `libscotch`, but it's unclear how that will work if `libptscotch` is missing symbols. I won't use this directly, it's just a prereq for OpenFOAM.

**Comment by giordano** [comment]
Don't dlopen the library: https://docs.binarybuilder.org/stable/reference/#BinaryBuilderBase.LibraryProduct

**Comment by Wimmerer** [comment]
Do you want this under `P/PTSCOTCH` or `S/SCOTCH`

**Review by giordano — APPROVED** [review]
> Do you want this under P/PTSCOTCH or S/SCOTCH

If they share lots of code together we could have `S/SCOTCH/{PT,}SCOTCH/build_tarballs.jl` which call `S/SCOTCH/common.jl`, we have a few example here already.  But we can also do this change later.  I'm going to merge this.

**Pull request merged**
