### PR TITLE
New Recipe: QCDNUM v17.1.83

### PR DESCRIPTION
**Pull request by cescalara**

### CODE REVIEW

**Comment by giordano** [comment]
Thank you so much for your contribution!  I pushed a couple of changes to build for all platforms we support

**Comment by cescalara** [comment]
Ah great that's very helpful - thanks!

**Comment by oschulz** [comment]
Nicely done, @cescala, and thanks for the assist @giordano !

**Comment by oschulz** [comment]
@cescalara , I think it's time we get https://github.com/cescalara/QCDNUM.jl registered (we should start as v0.1 though) :-)

**Pull request merged**
