### PR TITLE
SCALAPACK: Support MPItrampoline

### PR DESCRIPTION
**Pull request by eschnett**
This PR adds support for MPItrampoline. It also
- updates to version 2.2.0
- follows the official instructions for ILP64 mode https://github.com/Reference-ScaLAPACK/scalapack/pull/19

### CODE REVIEW

**Comment by eschnett** [comment]
`-lblastrampoline` might actually simplify things.

**Comment by giordano** [comment]
libblastrampoline doesn't solve the fact you'll need to make sure to have a backing BLAS with the right interface

**Comment by ViralBShah** [comment]
Not sure I understand the comment. Isn't linking to LBT sufficient since Julia then provides the right BLAS and LAPACK?

**Comment by giordano** [comment]
Not really. Julia provides an ILP64 BLAS on 64-bit, but what's the expected interface of the package here? If you remove the dance the rename all symbols here, you'll be basically expecting an LP64 BLAS, which Julia does _not_ provide

**Comment by eschnett** [comment]
I assume that all artefacts are rebuilt when this PR are merged. If so, this PR will automatically require MPItrampoline 5.

**Pull request merged**
