### PR TITLE
[GR] Build on Apple M1

### PR DESCRIPTION
**Pull request by ViralBShah**

### CODE REVIEW

**Comment by giordano** [comment]
1. This _must_ change the version number
2. This _must_ require Julia v1.6
3. We need to build all dependencies first, which also have the same constraints above

**Comment by ViralBShah** [comment]
Oh yeah, I keep forgetting those points.

**Comment by giordano** [comment]
I opened an issue about building JLLs in general for the new platforms: #2763.  BTW: this pull request at the moment doesn't build GR for any new platform, you should explicitly add `Platform("aarch64", "macos")` to the list of platform to do so.

**Comment by ViralBShah** [comment]
Hopefully now it will just fail. When can we make macos aarch64 a regular architecture?

**Comment by ViralBShah** [comment]
@jheinen Just FYI.

**Comment by giordano** [comment]
> When can we make macos aarch64 a regular architecture?

I guess when people will be happy to cut out Julia v1.5-

**Comment by ViralBShah** [comment]
Ok - I suppose that could happen with 1.6 or 1.7 being the new LTS.

**Comment by giordano** [comment]
Exactly, which however is in the timescale of months

**Comment by jheinen** [comment]
> Exactly, which however is in the timescale of months

Until then macOS M1 users can use the (self-contained) aarch64 distribution found [here](https://github.com/sciapp/gr/releases). At our site, I often use a universal distribution for both macOS architectures (`gr-latest-Darwin-universal.tar.gz`), see [here](https://gr-framework.org/downloads/).

**Comment by ViralBShah** [comment]
I think we should be able to update many of the dependencies to newer versions and start enabling experimental. Since @jheinen is able to build these, I imagine that it is not difficult for us to do the same.

@giordano Is it ok, if only the patch level in the version number changes, or does it need to be a minor/major change?

**Comment by staticfloat** [comment]
> Is it ok, if only the patch level in the version number changes

Changing just the patch level is fine.

**Comment by ViralBShah** [comment]
Is there a way to easily figure out which dependencies have yet to be built on M1? Perhaps more importantly, is there a way to build a list of the most commonly used JLLs, and which of those are available on M1?

**Comment by giordano** [comment]
All Julia binary dependencies are already available for the new platforms.  Other packages already built for M1 are listed in #2763.

**Comment by giordano** [comment]
@jheinen does GR use Qt on macos?

**Comment by jheinen** [comment]
The macOS artifacts built by our own deployment system (gr-framework.org or GH) have backend support for both CoreGraphics (GKSTerm.app) and Qt5 (gksqt.app), whereas the BB binaries only contain the Qt version.

**Comment by giordano** [comment]
Once https://github.com/JuliaRegistries/General/pull/37880 is merged and hits the PkgServer, this pull request should work.  Will still need to increase to version number.  Note also that this will require Julia v1.6

**Comment by ViralBShah** [comment]
Rebasing to master and rebuilding.

**Comment by ViralBShah** [comment]
@giordano Should we merge?

**Comment by giordano** [comment]
Not yet. Next time there will be a GR release, we'll do it from here. CC: @jheinen

**Comment by ViralBShah** [comment]
Do we want a GR 0.59 or higher to have a clean break for Julia 1.6 compatible only binaries? I suppose Julia 1.6 as the new LTS is also not too far away.

**Comment by ViralBShah** [comment]
Does someone remember why we need to build the QHull within GR (and not use the BB built one)? Does GR need an older version or does it patch it? Perhaps @jheinen knows.

**Comment by jheinen** [comment]
> Does someone remember why we need to build the QHull within GR (and not use the BB built one)? Does GR need an older version or does it patch it? Perhaps @jheinen knows.

No, QHull 8.0.2 should work, too.

**Comment by jheinen** [comment]
> Ok triggering a build with `QHull_jll`. I think ZeroMQ had been a bit difficult in the past - @jheinen can we use a stock zeromq version as well?

We are on ZeroMQ 4.3.4 - so it should be no problem ...

**Comment by ViralBShah** [comment]
I think we should get this to merge with what is known to work - and do a separate PR later on for using our own Qhull and ZeroMQ which would b nice.

**Comment by ViralBShah** [comment]
Is this not doing a new build of everything after I reverted the last commit, because it knows it built the earlier commit before? If so, is this ok to merge?

**Comment by staticfloat** [comment]
[Yes, that's right](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=13388&view=logs&j=96c13d9d-dfd2-51e5-2f76-4a0b3ce09abc&t=09532434-8b0a-5f0e-118d-a3181cde5ec8&l=34).

**Pull request merged**
