### PR TITLE
add OpenFAST

### PR DESCRIPTION
**Pull request by Crghilardi**
This PR adds a build_tarballs.jl for the [OpenFAST](https://github.com/OpenFAST/openfast) libraries. Possibly long shot?

**Warning** This is currently using `Debug` mode, running on `Release` or anything that uses higher `-O` levels would completely overwhelm my laptop. `Debug` mode ran locally for me and allowed me to get through the wizard and do testing.

Tested successfully on `x86_64-linux-gnu` and `x86_64-linux-musl`
Tested unsuccessfully on `x86_64-w64-mingw64` due to `missing _gemm` type errors, still figuring it out

### CODE REVIEW

**Comment by giordano** [comment]
>  Tested unsuccessfully on x86_64-w64-mingw64 due to missing _gemm type errors, still figuring it out

I guess because it's using the wrong OpenBLAS (alternatively, you need to rename all symbols)

**Comment by Crghilardi** [comment]
A few platforms (`x86-linux-gnu-*`, `x86-linux-musl-*` at least) seem to be building and then failing on the last step of the audit procedure with something about `curl`?

```
[ Info: Tree hash of contents of OpenFAST.v3.0.0.x86_64-linux-gnu-libgfortran3.tar.gz: bde18894dbf8d5dd403882aa6a21aeb2598d0eae
[ Info: SHA256 of OpenFAST.v3.0.0.x86_64-linux-gnu-libgfortran3.tar.gz: d2be2937d4ce16e1a44677b887b5d9bd7ff43b976856c0a5d0167b12c43d8b29
Uploading artifact to https://julia-bb-buildcache.s3.amazonaws.com/5583a04062009be6e31f85da09c5de29ac81f7a25fb478148821cd6f8c7bfcb7/4114ad103d677ee096e27c1ab3ab2ca6e5c4aa0908dbfd08ad50c69c9116aca4/x86_64-linux-gnu-libgfortran3.tar.gz
curl: Can't open './products/OpenFast*x86_64-linux-gnu-libgfortran3*.tar.gz'!
curl: try 'curl --help' or 'curl --manual' for more information
##[error]Bash exited with code '26'.
Finishing: run build_tarballs.jl

```

posting a snippet from the `x86_64-w64-mingw`error logs as well so I have it non-ephemerally
```
[03:52:43] cd /workspace/srcdir/openfast-3.0.0/build/modules/nwtc-library && /usr/bin/cmake -E cmake_link_script CMakeFiles/nwtclibs.dir/link.txt --verbose=true
[03:52:43] /usr/bin/cmake -E rm -f CMakeFiles/nwtclibs.dir/objects.a
[03:52:43] /opt/bin/x86_64-w64-mingw32-libgfortran5-cxx11/x86_64-w64-mingw32-ar cr CMakeFiles/nwtclibs.dir/objects.a @CMakeFiles/nwtclibs.dir/objects1.rsp
[03:52:43] /opt/bin/x86_64-w64-mingw32-libgfortran5-cxx11/x86_64-w64-mingw32-gfortran --sysroot=/opt/x86_64-w64-mingw32/x86_64-w64-mingw32/sys-root/   -ffree-line-length-none -cpp -fstack-reuse=none -fdefault-real-8 -fopenmp -g -fcheck=all,no-array-temps -pedantic -fbacktrace -finit-real=inf -finit-integer=9999. -fopenmp  -shared -o libnwtclibs.dll -Wl,--out-implib,libnwtclibs.dll.a -Wl,--major-image-version,0,--minor-image-version,0 -Wl,--whole-archive CMakeFiles/nwtclibs.dir/objects.a -Wl,--no-whole-archive @CMakeFiles/nwtclibs.dir/linklibs.rsp
[03:52:43] /opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/nwtclibs.dir/objects.a(NWTC_LAPACK.f90.o): in function `__nwtc_lapack_MOD_lapack_sgemm':
[03:52:43] /workspace/srcdir/openfast-3.0.0/modules/nwtc-library/src/NetLib/lapack/NWTC_LAPACK.f90:441: undefined reference to `sgemm_'
[03:52:43] /opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/nwtclibs.dir/objects.a(NWTC_LAPACK.f90.o): in function `__nwtc_lapack_MOD_lapack_dgemm':
[03:52:43] /workspace/srcdir/openfast-3.0.0/modules/nwtc-library/src/NetLib/lapack/NWTC_LAPACK.f90:351: undefined reference to `dgemm_'
[03:52:43] collect2: error: ld returned 1 exit status
[03:52:43] make[2]: *** [modules/nwtc-library/CMakeFiles/nwtclibs.dir/build.make:606: modules/nwtc-library/libnwtclibs.dll] Error 1
[03:52:43] make[2]: Leaving directory '/workspace/srcdir/openfast-3.0.0/build'
[03:52:43] make[1]: *** [CMakeFiles/Makefile2:659: modules/nwtc-library/CMakeFiles/nwtclibs.dir/all] Error 2
[03:52:43] make[1]: Leaving directory '/workspace/srcdir/openfast-3.0.0/build'
[03:52:43] make: *** [Makefile:150: all] Error 2
```

**Comment by Crghilardi** [comment]
OK, switching to `OpenBLAS32` cleared up the `mingw` issues. The weird thing now is `aarch64-linux-musl` fails with

```
  9%] Building Fortran object modules/nwtc-library/CMakeFiles/nwtclibs.dir/src/NWTC_IO.f90.o
[16:12:58] cd /workspace/srcdir/openfast-3.0.0/build/modules/nwtc-library && /opt/bin/aarch64-linux-musl-libgfortran3-cxx11/aarch64-linux-musl-gfortran --sysroot=/opt/aarch64-linux-musl/aarch64-linux-musl/sys-root/ -DHAS_FORTRAN2008_FEATURES -DOPENFAST_DOUBLE_PRECISION -DUSE_DLL_INTERFACE -Dnwtclibs_EXPORTS -I/workspace/srcdir/openfast-3.0.0/build/ftnmods  -fpic  -ffree-line-length-none -cpp -fstack-reuse=none -fdefault-real-8 -fopenmp -g -fcheck=all,no-array-temps -pedantic -fbacktrace -finit-real=inf -finit-integer=9999. -fopenmp -J../../ftnmods -fPIC   -c /workspace/srcdir/openfast-3.0.0/modules/nwtc-library/src/NWTC_IO.f90 -o CMakeFiles/nwtclibs.dir/src/NWTC_IO.f90.o
[16:12:58] /workspace/srcdir/openfast-3.0.0/modules/nwtc-library/src/NWTC_IO.f90:25:7:
[16:12:58] 
[16:12:58]     USE IEEE_ARITHMETIC
[16:12:58]        1
[16:12:58] Fatal Error: Can't open module file ‘ieee_arithmetic.mod’ for reading at (1): No such file or directory
[16:12:58] compilation terminated.
[16:12:58] make[2]: *** [modules/nwtc-library/CMakeFiles/nwtclibs.dir/build.make:135: modules/nwtc-library/CMakeFiles/nwtclibs.dir/src/NWTC_IO.f90.o] Error 1
[16:12:58] make[2]: *** Waiting for unfinished jobs....
[16:12:58] make[2]: Leaving directory '/workspace/srcdir/openfast-3.0.0/build'
[16:12:58] make[1]: *** [CMakeFiles/Makefile2:659: modules/nwtc-library/CMakeFiles/nwtclibs.dir/all] Error 2
[16:12:58] make[1]: Leaving directory '/workspace/srcdir/openfast-3.0.0/build'
[16:12:58] make: *** [Makefile:150: all] Error 2

```

aarch64-linux-gnu works fine.

Looking at the [gfortran docs](https://gcc.gnu.org/onlinedocs/gcc-8.1.0/gfortran.pdf), I saw this snippet

```
10.3 IEEE modules: IEEE_EXCEPTIONS, IEEE_ARITHMETIC, and
IEEE_FEATURES
Standard : Fortran 2003 and later
The IEEE_EXCEPTIONS, IEEE_ARITHMETIC, and IEEE_FEATURES intrinsic modules pro-
vide support for exceptions and IEEE arithmetic, as defined in Fortran 2003 and later
standards, and the IEC 60559:1989 standard (Binary floating-point arithmetic for micro-
processor systems ). These modules are only provided on the following supported platforms:
• i386 and x86 64 processors
• platforms which use the GNU C Library (glibc)
• platforms with support for SysV/386 routines for floating point interface (including
Solaris and BSDs)
• platforms with the AIX OS

```
which made me think it was a `musl` issue but other musl platforms (x86-64-linux-musl, i686-linux-musl) are working fine. 

The only clue I have at this point is aarch64-linux-musl is using `gcc8.1.0` and everything else that is working seems to use a lower version (either 6 or 7)

**Comment by Crghilardi** [comment]
For the "Can't find IEEE module" issue on `aarch64-linux-musl` I believe that is running into the same issue as outlined [this GCC issue](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100662). I was looking at `configure.host` file mentioned in that thread and noticed there has been a [recent commit](https://github.com/gcc-mirror/gcc/commit/220b9bdfe8faebdd2aea0ab7cea81c162d42d8e0) allowing IEEE support for `aarch64` non-glibc platforms. 
I don't know which gcc version that will end up in and I don't want to have to use a super high GCC version, so I am just filtering those out here. I am also filtering out `arm-*`, I think they are a long shot.

**Pull request merged**
