### PR TITLE
[LCIO_Julia_Wrapper] removing (hopefully) redundant workaround

### PR DESCRIPTION
**Pull request by jstrube**

### CODE REVIEW

**Comment by giordano** [comment]
This isn't changing anything in the tarballs or the jll package, right?

**Comment by jstrube** [comment]
Correct.

**Comment by giordano** [comment]
Then do you mind if I add the `[skip ci]` cookie so that we don't generate again a new version of the JLL package?

**Comment by jstrube** [comment]
Where do you add that? In the title of the PR?

**Comment by giordano** [comment]
In any part of the commit message

**Pull request merged**
