### PR TITLE
add builder for PROPACK

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by giordano** [comment]
You don't need the patch for building a library against OpenBLAS, you can adapt what I did in https://github.com/JuliaPackaging/Yggdrasil/pull/388#issuecomment-574935823.  If you're not comfortable doing this, I can have a look to this in the next days.

**Comment by dpo** [comment]
Thanks. I thought there should be a better way than the patch but will your trick work with Fortran 77 source code?

**Comment by giordano** [comment]
Yes, gfortran uses the same C preprocessor as GCC (even if there isn't a standard Fortran preprocessor, as far as I know).  However you need to set `FFLAGS`, instead of `CXXFLAGS`.  Also [`ARPACK`](https://github.com/JuliaPackaging/Yggdrasil/blob/dcb1e7c2ff69d456117074b57a27168745296015/A/Arpack/build_tarballs.jl) does this and is in Fortran

**Comment by dpo** [comment]
Much better, thank you.

**Comment by giordano** [comment]
Is [this](https://github.com/JuliaPackaging/Yggdrasil/compare/7bc520da11b3e44fd0e67815dfe8c2df953914b9..6e66e15498d671fdb4680fb3c92daabad7c029cd) because you wanted to build locally only for one platform?

**Comment by dpo** [comment]
I erroneously pushed the script I was using for testing locally. I really want to build for all platforms.

**Comment by giordano** [comment]
> I really want to build for all platforms.

Sure, no doubt, I just wanted to point out that if you want to build for just a specific platform you don't need to modify the script, just pass the triplet of that platform as argument to the script, as explained in the [FAQ](https://juliapackaging.github.io/BinaryBuilder.jl/dev/FAQ/#I-love-the-wizard,-but-now-I-want-to-break-free:-can-I-build-the-tarballs-without-it?-1)

**Comment by dpo** [comment]
>  if you want to build for just a specific platform you don't need to modify the script, just pass the triplet of that platform as argument to the script, as explained in the FAQ

Just to follow up on this, it would be great if the triplets were listed somewhere. It wasn't obvious to me that `MacOS(:x86_64)` is in fact `x86_64-apple-darwin14`.

**Comment by giordano** [comment]
```julia
julia> using BinaryBuilder

julia> for p in supported_platforms()
           println("$(p): $(triplet(p))")
       end
Linux(:i686, libc=:glibc): i686-linux-gnu
Linux(:x86_64, libc=:glibc): x86_64-linux-gnu
Linux(:aarch64, libc=:glibc): aarch64-linux-gnu
Linux(:armv7l, libc=:glibc, call_abi=:eabihf): arm-linux-gnueabihf
Linux(:powerpc64le, libc=:glibc): powerpc64le-linux-gnu
Linux(:i686, libc=:musl): i686-linux-musl
Linux(:x86_64, libc=:musl): x86_64-linux-musl
Linux(:aarch64, libc=:musl): aarch64-linux-musl
Linux(:armv7l, libc=:musl, call_abi=:eabihf): arm-linux-musleabihf
MacOS(:x86_64): x86_64-apple-darwin14
FreeBSD(:x86_64): x86_64-unknown-freebsd11.1
Windows(:i686): i686-w64-mingw32
Windows(:x86_64): x86_64-w64-mingw32
```
:wink:

**Comment by dpo** [comment]
Thanks. That would fit just right in the docs somewhere ;-).

**Pull request merged**
