### PR TITLE
Update XGBoost

### PR DESCRIPTION
**Pull request by ViralBShah**

### CODE REVIEW

**Comment by ViralBShah** [comment]
https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=2190&view=logs&j=50fc9a23-07ae-5144-22c5-e100aa71d015&t=e7217edf-d9b1-59da-dc6f-7bd1fbefc843&l=493

Can’t find Shlwapi.h. Seems like it is a mingw file.

**Comment by ViralBShah** [comment]
it's odd that on mac it wants such a new cmake - 3.16.

https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=2190&view=logs&j=0e6f23d3-bbc5-5a5c-1679-8a7f37dad18d&t=62f65e56-6499-50ca-7cf6-50d14fe18c3b&l=151

**Comment by aviks** [comment]
For the record, I've made a lot of progress with this, linux and windows now work fine on xgboost master.  For Mac,  it's currently blocked on https://github.com/dmlc/xgboost/issues/5518, or our ability to provide `libomp` in `CompilerSupportLibraries`

**Comment by clouds56** [comment]
Hi @aviks , I'm on mac and hope use xgboost with libomp.
What's blocking libomp goes into `CompilerSupportLibraries` now?
Thanks.

**Pull request closed without merging**
