### PR TITLE
[SuiteSparse] Enable build of libgraphblas

### PR DESCRIPTION
**Pull request by ViralBShah**
It looks like libgraphblas is 36M and it compresses down to 11M.

I wonder if it should be made into a separate package. It has no dependencies on the rest of suitesparse, and if bundled in there, will significantly increase the size of the Julia download.

cc @fredrikekre @abhinavmehndiratta

### CODE REVIEW

**Comment by giordano** [comment]
> I wonder if it should be made into a separate package. It has no dependencies on the rest of suitesparse, and if bundled in there, will significantly increase the size of the Julia download.

Given these points and the fact that this additional library requires GCC 4.9, doing this in a separate library makes very much sense.

**Comment by ViralBShah** [comment]
What's the deal with gcc 4.9? Don't we use a fairly new gcc anyways?

**Comment by giordano** [comment]
No, that's quite the opposite: for best compatibility it's better to use an as old version as possible. If the library is in C, compatibility with the compiler isn't a big deal, but the binutils version bound to our compiler can be a problem, especially for compiling julia since this is a dependency.  See https://github.com/JuliaPackaging/Yggdrasil/blob/master/RootFS.md#compiler-shards

**Comment by ViralBShah** [comment]
New PR in #336 to publish as a separate package.

**Pull request closed without merging**
