### PR TITLE
MPICH 3.4a3

### PR DESCRIPTION
**Pull request by simonbyrne**
MPICH 3.3.2 has problems with the new MacOS image on GitHub Actions. This attempts to build the alpha release of 3.4, in the hopes that it might fix it.

https://github.com/JuliaParallel/MPI.jl/issues/407

cc: @jakebolewski @giordano

### CODE REVIEW

**Comment by simonbyrne** [comment]
Main question is whether we want to tag an alpha version?

**Comment by giordano** [comment]
I can make a custom build of this package for you that you can at least use to check whether it fixes the issue

**Comment by giordano** [comment]
As an alternative, you could add the patch for https://github.com/pmodels/mpich/pull/3363 to the current version (but the change looks quite large and who knows whether it applies cleanly, I guess you already considered this option)

**Comment by eschnett** [comment]
Yggdrasil's MPICH is now at version 3.4.2. Can this be closed?

**Comment by simonbyrne** [comment]
Good point, thanks!

**Pull request closed without merging**
