### PR TITLE
Arpack: Update to version 3.8.0

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by giordano** [comment]
I think we tried Arpack 3.8 in the past but it had some bugs. CC @ViralBShah

**Comment by ViralBShah** [comment]
This is the issue: https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/138

**Comment by ViralBShah** [comment]
Also note we already have `Arpack_jll` v3.8 in Yggdrasil.

**Comment by ViralBShah** [comment]
Need to rebuild this anyways.

**Comment by giordano** [comment]
Wait for v3.7 to be merged in the registry before merging this PR

**Pull request merged**
