### PR TITLE
[OpenBLAS] Update to v0.3.28

### PR DESCRIPTION
**Pull request by giordano**

### CODE REVIEW

**Comment by giordano** [comment]
I'm very much confused by the failures when compiling with Clang 16 for x86_64 targets, e.g. https://buildkite.com/julialang/yggdrasil/builds/12408#01913b82-30cb-4c03-875d-10cbd38bf496 :
```
[09:56:16] make[1]: *** [Makefile.L2:513: sbgemv_n_COOPERLAKE.o] Error 255
[09:56:16] make[1]: *** Waiting for unfinished jobs....
[09:56:16] make[1]: *** [Makefile.L3:821: sbgemm_kernel_COOPERLAKE.o] Error 255
```
but I can't see any real error message.  Is the compiler just silently dying?  Not even with an ICE?  @martin-frbg sorry for the ping, would you have a clue of what's going on?  The full log is linked above.

**Comment by martin-frbg** [comment]
in the build log it has some unpleasant things to say about the sbgemv_t microkernel, maybe the error 255 for sbgemv_n is simply that the compiler quit at that point, refusing to process the next file ? 
Both these microkernels for CooperLake should be unchanged from about a year ago, I think. Did you guys add any option to turn compiler warnings into errors, or upgrade clang to a version that maybe does it by default lately ?
I have not checked yet if the static array overflow it complains about is real and I'm in a hurry right now, maybe see if you can placate the compiler by making whatever array that is a bit bigger...

**Comment by martin-frbg** [comment]
try https://github.com/OpenMathLib/OpenBLAS/pull/4859 (but I'm off now, kept someone waiting at the train station...)

**Comment by giordano** [comment]
> Did you guys add any option to turn compiler warnings into errors, or upgrade clang to a version that maybe does it by default lately ?

No, we don't generally force `-Werror` and I don't think Clang enabled `-Werror` by default at any point, but also, the compiler should clearly print an error message showing what warning would cause the failure, here I just don't see anything.

However, in this PR I did switch from Clang 13 to Clang 16, and I accidentally did it only for the ILP64 build, but not the LP64 one, with the result that only the ILP64 build failed.  So I do think the failure comes from moving to Clang 16, but I can't understand _what_ is the issue.  Now I'm trying to revert to Clang 13 everywhere and see what happens.

**Comment by giordano** [comment]
I did a little bit of debugging locally, it looks to me Clang 16 just silently dies.  With https://github.com/OpenMathLib/OpenBLAS/pull/4859, the warning is gone, but Clang just dies:
```console
sandbox:${WORKSPACE}/srcdir/OpenBLAS-0.3.28/kernel # cc -c -O2 -DSMALL_MATRIX_OPT -DMAX_STACK_ALLOC=2048 -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=512 -DMAX_PARALLEL_NUMBER=1 -DBUILD_BFLOAT16 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.28\" -msse3 -mssse3 -msse4.1 -mavx -mavx2 -march=cooperlake -mavx2 -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=_sbgemv_t_COOPERLAKE -DASMFNAME=_sbgemv_t_COOPERLAKE_ -DNAME=sbgemv_t_COOPERLAKE_ -DCNAME=sbgemv_t_COOPERLAKE -DCHAR_NAME=\"sbgemv_t_COOPERLAKE_\" -DCHAR_CNAME=\"sbgemv_t_COOPERLAKE\" -DNO_AFFINITY -DTS=_COOPERLAKE -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_COOPERLAKE -march=cooperlake -DBFLOAT16 -UDOUBLE  -UCOMPLEX -UCOMPLEX ../kernel/x86_64/sbgemv_t.c -o sbgemv_t_COOPERLAKE.o; echo $?
255
```
So I'm more and more convinced this is an upstream bug in newer versions of Clang and we have to stick to version 13 for the time being, sigh.

**Comment by giordano** [comment]
It turns out it's a segfault inside Clang: https://github.com/llvm/llvm-project/issues/102754#issuecomment-2282069974.  Let's move on with Clang 13, and hope this is fixed upstream.

**Comment by giordano** [comment]
For future reference, it was `ccache` which swallowed the "Segmentation fault" error message and returned 255 instead of 139, compare
```console
sandbox:${WORKSPACE}/srcdir/OpenBLAS-0.3.28/kernel # /opt/x86_64-linux-musl/bin/clang -target x86_64-linux-gnu --sysroot=/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root -D_GLIBCXX_USE_CXX11_ABI=1 --gcc-install-dir=/opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/11.1.0 -isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/include/c++/11.1.0 -isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/include/c++/11.1.0/x86_64-linux-gnu -isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/include/c++/11.1.0/backward -isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/include -isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/include -O2 -Wall -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -march=cooperlake -mavx2 -march=cooperlake -DSMALL_MATRIX_OPT -DMAX_STACK_ALLOC=2048 -DF_INTERFACE_GFORT -DDYNAMIC_ARCH -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=512 -DMAX_PARALLEL_NUMBER=1 -DBUILD_BFLOAT16 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION="0.3.28" -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=sbgemv_n_COOPERLAKE -DASMFNAME=sbgemv_n_COOPERLAKE_ -DNAME=sbgemv_n_COOPERLAKE_ -DCNAME=sbgemv_n_COOPERLAKE -DCHAR_NAME="sbgemv_n_COOPERLAKE_" -DCHAR_CNAME="sbgemv_n_COOPERLAKE" -DNO_AFFINITY -DTS=_COOPERLAKE -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_COOPERLAKE -DBFLOAT16 -UDOUBLE -UCOMPLEX -UCOMPLEX -c -fcolor-diagnostics -o sbgemv_n_COOPERLAKE.o ../kernel/x86_64/sbgemv_n.c; echo $?
Segmentation fault
139
sandbox:${WORKSPACE}/srcdir/OpenBLAS-0.3.28/kernel # ccache /opt/x86_64-linux-musl/bin/clang -target x86_64-linux-gnu --sysroot=/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root -D_GLIBCXX_USE_CXX11_ABI=1 --gcc-install-dir=/opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/11.1.0 -isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/include/c++/11.1.0 -isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/include/c++/11.1.0/x86_64-linux-gnu -isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/include/c++/11.1.0/backward -isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/include -isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/include -O2 -Wall -m64 -fPIC -msse3 -mssse3 -msse4.1 -mavx -mavx2 -march=cooperlake -mavx2 -march=cooperlake -DSMALL_MATRIX_OPT -DMAX_STACK_ALLOC=2048 -DF_INTERFACE_GFORT -DDYNAMIC_ARCH -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=512 -DMAX_PARALLEL_NUMBER=1 -DBUILD_BFLOAT16 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION="0.3.28" -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=sbgemv_n_COOPERLAKE -DASMFNAME=sbgemv_n_COOPERLAKE_ -DNAME=sbgemv_n_COOPERLAKE_ -DCNAME=sbgemv_n_COOPERLAKE -DCHAR_NAME="sbgemv_n_COOPERLAKE_" -DCHAR_CNAME="sbgemv_n_COOPERLAKE" -DNO_AFFINITY -DTS=_COOPERLAKE -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_COOPERLAKE -DBFLOAT16 -UDOUBLE -UCOMPLEX -UCOMPLEX -c -fcolor-diagnostics -o sbgemv_n_COOPERLAKE.o ../kernel/x86_64/sbgemv_n.c; echo $?
255
```

**Pull request merged**
