### PR TITLE
[WI4MPI] Add builder

### PR DESCRIPTION
**Pull request by giordano**
Not really working at the moment

### CODE REVIEW

**Comment by giordano** [comment]
My understanding is that #3230 wasn't enough.  OpenMPI has these four different levels of Fortran bindings:
```sh
# These are the 4 monotonically-rising values indicating levels of
# Fortran bindings support.
OMPI_FORTRAN_NO_BINDINGS=0
OMPI_FORTRAN_MPIFH_BINDINGS=1
OMPI_FORTRAN_USEMPI_BINDINGS=2
OMPI_FORTRAN_USEMPIF08_BINDINGS=3
```
wi4mpi needs the OpenMPI f08 Fortran module (`OMPI_FORTRAN_USEMPIF08_BINDINGS`), which is built with `--enable-mpi-fortran=all` or `--enable-mpi-fortran=usempif08`, but our build got to `OMPI_FORTRAN_USEMPI_BINDINGS`.  I'm trying to figure out if/how to convince OpenMPI to build this f08 module.

**Comment by giordano** [comment]
The build "works" only for x86_64-linux-gnu, and dlopening the library fails with the error
```
Please provide either WI4MPI_WRAPPER_LIB environment or compile with -wi4mpi_default_run_paths
```
Of course there is no reference _anywhere_ to what `-wi4mpi_default_run_paths` is, at least the environment variable is mentioned in the [`README.md`](https://github.com/cea-hpc/wi4mpi/blob/cc1aae965073409764a2632105e822d01699caf7/README.md).  I didn't look into the other platforms, but it doesn't look very encouraging :grimacing:   CC: @vchuravy @simonbyrne @lcw

**Comment by vchuravy** [comment]
cc: @tgamblin

**Comment by vchuravy** [comment]
@giordano we will need to think about how we present this to other packages who want to use mpicc and co.

**Comment by giordano** [comment]
> we will need to think about how we present this to other packages who want to use mpicc and co.

In general, I think dealing with wi4mpi could be somewhat similar to how we'll deal with libblastrampoline.  To answer your question specifically, it looks like this package already provides a shell script version of `mpicc`, so hopefully cross-compilation shouldn't be a problem: https://github.com/cea-hpc/wi4mpi/blob/cc1aae965073409764a2632105e822d01699caf7/src/interface/interface_utils/bin/mpicc

**Comment by giordano** [comment]
Ok, this is unlikely to happen, and now we have [`MPItrampoline`](https://github.com/JuliaPackaging/Yggdrasil/blob/4ebbdc2d5b4a55ec28124c25d763eece01c8ffb3/M/MPItrampoline/build_tarballs.jl)

**Pull request closed without merging**
