### PR TITLE
Update Chemfiles to 0.9.3

### PR DESCRIPTION
**Pull request by Luthaf**

### CODE REVIEW

**Comment by Luthaf** [comment]
Is there an issue with CI? It seems stuck for multiple PR.

**Comment by giordano** [comment]
> Is there an issue with CI?

Not really an issue, but there is work ongoing to reorganise the pipeline, see #424.  In the meantime, the old pipeline is not working, but hopefully this situation will be fixed soon™

**Comment by Luthaf** [comment]
Ok, thanks !

**Comment by Luthaf** [comment]
Looks like armv7 cmake toolchain files are missing:

```
[11:06:40] CMake Error at /usr/share/cmake/Modules/CMakeDetermineSystem.cmake:100 (message):
[11:06:40]   Could not find toolchain file:
[11:06:40]   /opt/arm-linux-gnueabihf/arm-linux-gnueabihf.cmake

---

[11:04:25] CMake Error at /usr/share/cmake/Modules/CMakeDetermineSystem.cmake:100 (message):
[11:04:25]   Could not find toolchain file:
[11:04:25]   /opt/arm-linux-musleabihf/arm-linux-musleabihf.cmake
```

**Comment by Luthaf** [comment]
Yay, it works!

**Comment by Luthaf** [comment]
thanks!

**Pull request merged**
