### PR TITLE
Bump Xyce to 7.4

### PR DESCRIPTION
**Pull request by ven-k**
- Also, don't add no-undefined.patch as it is expected to be fixed

### CODE REVIEW

**Comment by giordano** [comment]
This now links to libgfortran, sigh:
```
┌ Warning: /agent/_work/1/s/X/Xyce/build/i686-linux-gnu-cxx03/g3vW8jZ2/i686-linux-gnu-libgfortran4-cxx03/destdir/bin/Xyce links to libgfortran!  This causes incompatibilities across major versions of GCC.  To remedy this, you must build a tarball for each major version of GCC.  To do this, immediately after your `platforms` definition in your `build_tarballs.jl` file, add the line:
│ 
│     platforms = expand_gfortran_versions(platforms)
└ @ BinaryBuilder.Auditor /depot/packages/BinaryBuilder/CuDaR/src/auditor/compiler_abi.jl:60
```

**Comment by giordano** [comment]
I feel like there may be something wrong in the build system, this doesn't look right

**Comment by ven-k** [comment]
> This now links to libgfortran, sigh:
> 
> ```
> ┌ Warning: /agent/_work/1/s/X/Xyce/build/i686-linux-gnu-cxx03/g3vW8jZ2/i686-linux-gnu-libgfortran4-cxx03/destdir/bin/Xyce links to libgfortran!  This causes incompatibilities across major versions of GCC.  To remedy this, you must build a tarball for each major version of GCC.  To do this, immediately after your `platforms` definition in your `build_tarballs.jl` file, add the line:
> │ 
> │     platforms = expand_gfortran_versions(platforms)
> └ @ BinaryBuilder.Auditor /depot/packages/BinaryBuilder/CuDaR/src/auditor/compiler_abi.jl:60
> ```

With the new patch these warnings are gone. From 96 down to 56 😅 Let me know if any of these are fatal

**Comment by giordano** [comment]
Warnings like
```
┌ Warning: Skipping abspath scanning of /agent/_work/1/s/X/Xyce/build/i686-linux-gnu-cxx03/dr6r8g6b/i686-linux-gnu-libgfortran4-cxx03/destdir/lib/cmake/tribits/doc/developers_guide/TribitsBuildReference.html, as we can't open it
└ @ BinaryBuilder.Auditor /depot/packages/BinaryBuilder/CuDaR/src/auditor/filesystems.jl:39
```
look like a bug in the auditor, I don't think we should try to audit that file at all.  Other warnings look harmless, thanks!

**Pull request merged**
