### PR TITLE
[MUMPS_seq] Version 5.5.1

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by amontoison** [comment]
@ViralBShah Is it possible to compile with `libblastrampoline_jll` for Julia < 1.8 ?
It seems to be not supported by Julia 1.6 but I don't know the issue with Julia 1.7.

**Comment by ViralBShah** [comment]
Yes, in theory it should work for 1.7.

**Comment by amontoison** [comment]
Thank @ViralBShah!
I changed the `julia_compat` for Julia 1.7 but I don't know if if we need something similar to https://github.com/JuliaPackaging/Yggdrasil/pull/4770.

**Comment by ViralBShah** [comment]
Ah, I was wondering about that - and yes, it's best to follow the recipe there.

**Comment by amontoison** [comment]
The release of Julia 1.8 is quite soon, let's just set the Julia compat to `v"1.8"`.

**Comment by ViralBShah** [comment]
@giordano Is it ok to merge this now - or should we wait for 1.8 to release first?

**Comment by amontoison** [comment]
Julia 1.8 is released, we can merge this PR and https://github.com/JuliaPackaging/Yggdrasil/pull/5309.

**Pull request merged**
