### PR TITLE
[Qt] Retrigger build

### PR DESCRIPTION
**Pull request by miguelraz**

### CODE REVIEW

**Comment by giordano** [comment]
The license is missing...

**Comment by miguelraz** [comment]
From their [website]():
> Qt for Application Development is also available under GPL and LGPLv3 open source licenses. Qt tools and some libraries are only available under GPL. See the comparison chart for details. The Qt open source licensing is ideal for use cases such as open source projects with open source distribution, student/academic purposes, hobby projects, internal research projects without external distribution, or other projects where all (L)GPL obligations can be met.

Which one should be preferred between GPL and LGPLv3? How should I add it to the PR?

**Comment by giordano** [comment]
@barche

**Comment by barche** [comment]
The license should be LGPL, I'll look into how to add it.

I'm also working on updating to Qt 5.15 (that's an LTS) and the Xorg dependencies should actually be build dependencies, using the bundled X stuff on Linux causes errors.

**Comment by giordano** [comment]
> The license should be LGPL, I'll look into how to add it.

You can use the [`install_license`](https://juliapackaging.github.io/BinaryBuilder.jl/dev/build_tips/#Installing-the-license-file-1) command.  It is better to install the original license files from the upstream source, otherwise we have a bunch of licenses in `/usr/share/licenses`:
```
install_license /usr/share/licenses/LGPL3
```

**Comment by barche** [comment]
Closing this in favor of PR #1182

**Pull request closed without merging**
