### PR TITLE
[CUDA] Upgrade to v11.2.1.

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
Did something change in BinaryBuilder? I'm seeing all expected libraries and binaries in the prefix:

```
sandbox:${WORKSPACE}/x86_64-linux-gnu-libgfortran3-cxx11/artifacts/59172198ec76ea7ee8fa48623c552818ceb1affa/cuda # ls $prefix/bin
cuda-memcheck  nvdisasm
```

Yet the package can't find them:

```
┌ Warning: Skipping abspath scanning of /home/tbesard/Julia/tools/Yggdrasil/C/CUDA/CUDA@11.2/build/x86_64-linux-gnu-cxx11/MoBMwheO/x86_64-linux-gnu-libgfortran3-cxx11/destdir/cuda/bin/nvdisasm, as we can't open it
└ @ BinaryBuilder.Auditor ~/Julia/depot/packages/BinaryBuilder/32BRI/src/auditor/filesystems.jl:39

[ Info: ["nvdisasm"] does not exist, reporting unsatisfied
┌ Error: Built CUDA but nvdisasm still unsatisfied:
└ @ BinaryBuilder ~/Julia/depot/packages/BinaryBuilder/32BRI/src/AutoBuild.jl:776
```

**Comment by giordano** [comment]
There have been some changes lately, but nothing that should affect how products are found. Not directly at least 🤔

**Comment by giordano** [comment]
Do the file have execution permissions?

**Comment by maleadt** [comment]
They do; I even patch them up myself (landed that fix before your change in BB itself).

**Comment by maleadt** [comment]
Hm, those absolute paths are symlinks that do not resolve:

```
$ ls /home/tbesard/Julia/tools/Yggdrasil/C/CUDA/CUDA@11.2/build/x86_64-linux-gnu-cxx11/MoBMwheO/x86_64-linux-gnu-libgfortran3-cxx11/destdir/cuda/bin/nvdisasm -la                                                     
lrwxrwxrwx 1 tbesard tbesard 77 Feb 17 11:23 /home/tbesard/Julia/tools/Yggdrasil/C/CUDA/CUDA@11.2/build/x86_64-linux-gnu-cxx11/MoBMwheO/x86_64-linux-gnu-libgfortran3-cxx11/destdir/cuda/bin/nvdisasm -> ../../../artifacts/59172198ec76ea7ee8fa48623c552818ceb1affa/cuda/bin/nvdisasm

$ realpath /home/tbesard/Julia/tools/Yggdrasil/C/CUDA/CUDA@11.2/build/x86_64-linux-gnu-cxx11/MoBMwheO/x86_64-linux-gnu-libgfortran3-cxx11/destdir/cuda/bin/nvdisasm                                                   
/home/tbesard/Julia/tools/Yggdrasil/C/CUDA/CUDA@11.2/build/x86_64-linux-gnu-cxx11/MoBMwheO/x86_64-linux-gnu-libgfortran3-cxx11/artifacts/59172198ec76ea7ee8fa48623c552818ceb1affa/cuda/bin/nvdisasm

$ ls -la /home/tbesard/Julia/tools/Yggdrasil/C/CUDA/CUDA@11.2/build/x86_64-linux-gnu-cxx11/MoBMwheO/x86_64-linux-gnu-libgfortran3-cxx11/artifacts/59172198ec76ea7ee8fa48623c552818ceb1affa/cuda/bin/nvdisasm          
ls: cannot access '/home/tbesard/Julia/tools/Yggdrasil/C/CUDA/CUDA@11.2/build/x86_64-linux-gnu-cxx11/MoBMwheO/x86_64-linux-gnu-libgfortran3-cxx11/artifacts/59172198ec76ea7ee8fa48623c552818ceb1affa/cuda/bin/nvdisasm': No such file or directory
```

I move stuff out of the CUDA_full artifact, because I expect to duplicate them (as we don't want users to have to install CUDA_full_jll).

**Pull request merged**
