### PR TITLE
[oxigraph_server] Add rocks db?

### PR DESCRIPTION
**Pull request by jeremiahpslewis**

### CODE REVIEW

**Comment by jeremiahpslewis** [comment]
I've tried a few different env vars to try and point it to clang, but cannot resolve the error:

```bash
[03:27:54]   thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /opt/x86_64-linux-musl/lib/libclang.so.12 could not be opened: Dynamic loading not supported"', /opt/x86_64-linux-musl/registry/src/github.com-1ecc6299db9ec823/bindgen-0.57.0/src/lib.rs:1975:31
```

**Comment by jeremiahpslewis** [comment]
@giordano Hope it is ok to ping you, I've tried every incantation I can come up with, but it doesn't want to use the libclang Yggdrasil provides and would be grateful for your feedback / a nudge in the right direction. :)

**Comment by giordano** [comment]
Do you really want to depend on `Clang_jll`?  It's a massive complication, you'd need to do different builds for each Julia version.

**Comment by jeremiahpslewis** [comment]
If I can find a way to not need `Clang_jll`, then I'm all for it. It seems like the root cause of the issue is `rust-lang/rust-bindgen` requiring clang at compile time. It seems like BinaryBuilder support this, but maybe I'm missing something.

https://github.com/rust-lang/rust-bindgen/issues/1797 


- https://github.com/tikv/grpc-rs/issues/477

**Comment by jeremiahpslewis** [comment]
Thanks

**Pull request closed without merging**
