### PR TITLE
[CompilerSupportLibraries] Upgrade to GCC 13 and move Win `*.a` files to subdir

### PR DESCRIPTION
**Pull request by giordano**
CC: @vtjnash

### CODE REVIEW

**Review by vtjnash — COMMENTED** [review]
A folder name of julia seems odd for being gcc. I think `lib/gcc/<triple>/<major>` would be better (where they normally are located when using a vanilla build of gcc).

**Comment by giordano** [comment]
Ok, I moved it to `lib/gcc/<triple>`.  I excluded `<major>` just because we'd have to update the number in julia's `Makefile` every time we update CSL there, unless that's seen as a feature?

**Comment by vtjnash** [comment]
That is where other tools, such as gcc itself, will expect to find it

**Comment by giordano** [comment]
Alright, moved to the suggested directory, including the major version number.

**Pull request merged**
