### PR TITLE
[Foldseek] New build script for Foldseek v4

### PR DESCRIPTION
**Pull request by marcom**
Foldseek is a program for fast protein structure search

https://github.com/steineggerlab/foldseek

### CODE REVIEW

**Comment by giordano** [comment]
On [FreeBSD](https://buildkite.com/julialang/yggdrasil/builds/595#018617d5-544c-4757-8a6f-8b4391ebf149/650-1627):
```
[15:16:58] /opt/x86_64-unknown-freebsd12.2/x86_64-unknown-freebsd12.2/sys-root//usr/include/sys/time.h:190:2: error: no matching function for call to 'printf'
[15:16:58]         KASSERT(_sbt >= 0, ("Negative values illegal for sbttons: %jx", _sbt));
[15:16:58]         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[15:16:58] /workspace/srcdir/foldseek/lib/kerasify/keras_model.h:20:9: note: expanded from macro 'KASSERT'
[15:16:58]         printf(__VA_ARGS__);                                                   \
[15:16:58]         ^~~~~~
```
Sounds like someone is trying to use `printf` without including `stdio.h` or `cstdio`: https://github.com/steineggerlab/foldseek/blob/53465f07cdeed1f7fda08ee7f188327cb57c37ba/lib/kerasify/keras_model.h#L10-L15 :shrug:

**Comment by giordano** [comment]
> disable freebsd build

Isn't it easier to patch it (and upstream the patch) than skipping the platform altogether?

**Comment by marcom** [comment]
Looks like a clash for the `KASSERT` macro that freebsd and this package use.

**Comment by giordano** [comment]
Yeah, it's more complicated than I thought (but I'm still positive they're missing to explicitly include the header file)

**Comment by marcom** [comment]
Will disable freebsd for now then.

Even after including cstdio, compilation is failing on freebsd. To me it looks like the error is coming from inside the freebsd header files. Either they shouldn't mix kernel and userland headers or use something with a leading underscore.

On line 190 of `/opt/x86_64-unknown-freebsd12.2/x86_64-unknown-freebsd12.2/sys-root//usr/include/sys/time.h` is where `KASSERT` is being called under the false assumption that it will be the freebsd kernel `KASSERT`.

On line 180 there is part of a comment:

```
 * Note: This file is used for both kernel and userland includes, so we can't
 * rely on KASSERT being defined, nor can we pollute the namespace by including
 * assert.h.
```

The relevant part of the log:

```
[16:57:13] In file included from /workspace/srcdir/foldseek/src/strucclustutils/GemmiWrapper.cpp:5:
[16:57:13] In file included from /workspace/srcdir/foldseek/lib/gemmi/mmread.hpp:9:
[16:57:13] In file included from /workspace/srcdir/foldseek/lib/gemmi/cif.hpp:13:
[16:57:13] In file included from /workspace/srcdir/foldseek/lib/gemmi/third_party/tao/pegtl.hpp:20:
[16:57:13] In file included from /workspace/srcdir/foldseek/lib/gemmi/third_party/tao/pegtl/file_input.hpp:16:
[16:57:13] In file included from /workspace/srcdir/foldseek/lib/gemmi/third_party/tao/pegtl/mmap_input.hpp:15:
[16:57:13] In file included from /workspace/srcdir/foldseek/lib/gemmi/third_party/tao/pegtl/internal/file_mapper.hpp:12:
[16:57:13] In file included from /workspace/srcdir/foldseek/lib/gemmi/third_party/tao/pegtl/internal/file_opener.hpp:8:
[16:57:13] In file included from /opt/x86_64-unknown-freebsd12.2/x86_64-unknown-freebsd12.2/sys-root//usr/include/sys/stat.h:101:
[16:57:13] /opt/x86_64-unknown-freebsd12.2/x86_64-unknown-freebsd12.2/sys-root//usr/include/sys/time.h:190:2: error: no matching function for call to 'printf'
[16:57:13]         KASSERT(_sbt >= 0, ("Negative values illegal for sbttons: %jx", _sbt));
[16:57:13]         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[16:57:13] /workspace/srcdir/foldseek/lib/kerasify/keras_model.h:21:9: note: expanded from macro 'KASSERT'
[16:57:13]         printf(__VA_ARGS__);                                                   \
[16:57:13]         ^~~~~~
[16:57:13] /opt/x86_64-unknown-freebsd12.2/x86_64-unknown-freebsd12.2/sys-root//usr/include/stdio.h:277:6: note: candidate function not viable: no known conversion from 'sbintime_t' (aka 'long') to 'const char *' for 1st argument
[16:57:13] int      printf(const char * __restrict, ...);
[16:57:13]          ^
```

**Comment by giordano** [comment]
CC @ararslan in case you want to have a look at this.

**Pull request merged**
