### PR TITLE
WaveFD 0.2.0

### PR DESCRIPTION
**Pull request by samtkaplan**
New version of WaveFD (with breaking changes).

### CODE REVIEW

**Comment by samtkaplan** [comment]
Thanks for merging this.  It looks like the CI failed on to create the General.jl PR.  The logs seem to indicate that one of the artifacts failed to upload.  I'm not sure what to do next.  Any advice?

**Comment by giordano** [comment]
I have no clue what's happening, I restarted the job three times, to no avail.  There might be some issues with GitHub at the moment.  Is it urgent or you can wait tomorrow?  I don't really have much time to investigate further now.

**Comment by samtkaplan** [comment]
thanks for looking.  can definitely wait.

**Comment by giordano** [comment]
I think that was a GitHub glitch, I tried again now and it just worked.  Thanks for spotting the issue!

**Pull request merged**
