### PR TITLE
Use explicit nproc with ninja.

### PR DESCRIPTION
**Pull request by maleadt**
Ref https://github.com/JuliaPackaging/Yggdrasil/pull/882#discussion_r410662622

### CODE REVIEW

**Comment by giordano** [comment]
Looks good!  However I just noticed there are broken links in NEO: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=3205&view=results

**Comment by maleadt** [comment]
Didn't notice that warning before. `libze` comes from oneAPI_Level_Zero_jll, which is a dependency of Neo. This vaguely sounds like https://github.com/JuliaPackaging/Yggdrasil/pull/770#issuecomment-615269981?

**Comment by giordano** [comment]
Ok, I'll have a look at what's happening here :confused:

**Comment by giordano** [comment]
> Didn't notice that warning before.

Probably because the symlinks aren't in the tarballs in [`v20.12.16259+0`](https://github.com/JuliaBinaryWrappers/NEO_jll.jl/releases/tag/NEO-v20.12.16259%2B0) :confused:

**Comment by giordano** [comment]
Am I missing something or here there is a circular dependency?

https://github.com/JuliaPackaging/Yggdrasil/blob/9ea44253feab7dcc642fd1834eca82e9d151af77/O/oneAPI_Level_Zero/build_tarballs.jl#L44

https://github.com/JuliaPackaging/Yggdrasil/blob/3308a30504ea3de6969954943bb23ad2ab87582a/N/NEO/build_tarballs.jl#L70

**Comment by giordano** [comment]
The circular dependency was a side note, not really relevant for the symlink problem.

In the [tarballs](https://github.com/JuliaBinaryWrappers/oneAPI_Level_Zero_jll.jl/releases/tag/oneAPI_Level_Zero-v0.91.10%2B1) of `oneAPI_Level_Zero_jll` the symlinks aren't there, that's why they aren't removed by `cleanup_dependencies`.  I'm not sure where these links are coming from, they are already there at the beginning of the build script.

**Comment by maleadt** [comment]
> Am I missing something or here there is a circular dependency?

There is, but it's needed. NEO needs the oneAPI Level Zero headers, but that package also provides a 'loader' to work with (instead of directly depending on an implementation like NEO). However, lacking optional dependencies, that loader also needs to depend on NEO... https://github.com/JuliaPackaging/Yggdrasil/pull/866

> In the [tarballs](https://github.com/JuliaBinaryWrappers/oneAPI_Level_Zero_jll.jl/releases/tag/oneAPI_Level_Zero-v0.91.10%2B1) of `oneAPI_Level_Zero_jll` the symlinks aren't there, that's why they aren't removed by `cleanup_dependencies`. I'm not sure where these links are coming from.

Strange how they weren't included in the first build. Thanks for looking into this!

**Comment by giordano** [comment]
Ok, good, now the broken symlinks are gone!  I'm going to merge without triggering a new release, as the changes here aren't really relevant.

**Pull request merged**
