### PR TITLE
Wizard recipe: libftd2xx-v1.0.0

### PR DESCRIPTION
**Pull request by samuelpowell**
This pull request contains a new build recipe I built using the BinaryBuilder.jl wizard:

* Package name: libftd2xx
* Version: v1.0.0

@staticfloat please review and merge.

### CODE REVIEW

**Comment by samuelpowell** [comment]
BB is failing to unzip a file (oddly this works fine locally). I wonder if this is because of the spaces in the URL?

There's not much I can do about that, since it automatically gets unzipped as a source (I'd be happy if it didn't, I can always do that in the script).

Any suggestions?

**Comment by samuelpowell** [comment]
Ahhh, okay.

More generally - is this a reasonable way to repackage binaries? It feels a bit clunky?

And for whatever reason, the original Windows library has a different name. Can I do what I did with BB/BP and provide an array of names (without extension) as follows?:

```
libnames = ["libftd2xx", "ftdxx", "ftdxx64"]
products = Product[LibraryProduct(joinpath(prefix, "lib"), libnames, :libftd2xx)]```

**Comment by giordano** [comment]
> More generally - is this a reasonable way to repackage binaries? It feels a bit clunky?

Well, in general repackaging is a bit clunky.  However, it looks like this is more clunky than usual because these are tar archives within gzipped files, which is........

>  Can I do what I did with BB/BP and provide an array of names (without extension) as follows?:

Yes, this works here as well.

**Comment by samuelpowell** [comment]
Yes it's remarkable isn't it? The internal structure is no better, looks like an in-source build with the source removed. 

Would you ping me when you think I can retry on the odd filename?

**Comment by giordano** [comment]
Generally speaking, use `${libdir}` when you want to refer to the directory where the libraries should be installed and to `${dlext}` as the extension of the shared libraries, as these variables are platform-dependent.  See https://juliapackaging.github.io/BinaryBuilder.jl/dev/build_tips/#Automatic-environment-variables-1

**Comment by samuelpowell** [comment]
Ready for review

**Comment by samuelpowell** [comment]
I had to bundle the license as a text file taken from the FTDI web site, as it is not included in the downloaded files.

I don't have any need for linking against the library - there is a full featured Julia package which will migrate to using this for its binary dependencies when ready.

**Pull request merged**
