### PR TITLE
Rebuild LLVM 6.0.1

### PR DESCRIPTION
**Pull request by fingolfin**
... to resolve issues on PowerPC due to a "too new glibc".

### CODE REVIEW

**Comment by giordano** [comment]
@vchuravy any clue about the failure for macOS:
```
[15:55:28] ninja: job failed: /opt/bin/clang --target=x86_64-apple-darwin14 --sysroot=/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root -DKERNEL_USE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Iprojects/compiler-rt/lib/builtins -I/workspace/srcdir/llvm-project/compiler-rt/lib/builtins -Iinclude -I/workspace/srcdir/llvm-project/llvm/include -O3 -DNDEBUG -arch x86_64    -isysroot /opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root -mmacosx-version-min=10.5 -fPIC -O3 -fvisibility=hidden -DVISIBILITY_HIDDEN -Wall -fomit-frame-pointer -arch x86_64 -mkernel -MD -MT projects/compiler-rt/lib/builtins/CMakeFiles/clang_rt.cc_kext_x86_64_osx.dir/atomic.c.o -MF projects/compiler-rt/lib/builtins/CMakeFiles/clang_rt.cc_kext_x86_64_osx.dir/atomic.c.o.d -o projects/compiler-rt/lib/builtins/CMakeFiles/clang_rt.cc_kext_x86_64_osx.dir/atomic.c.o   -c /workspace/srcdir/llvm-project/compiler-rt/lib/builtins/atomic.c
[15:55:28] /workspace/srcdir/llvm-project/compiler-rt/lib/builtins/atomic.c:257:1: error: atomic load requires runtime support that is not available for this target
[15:55:28] OPTIMISED_CASES
[15:55:28] ^
[15:55:28] /workspace/srcdir/llvm-project/compiler-rt/lib/builtins/atomic.c:238:3: note: expanded from macro 'OPTIMISED_CASES'
[15:55:28]   OPTIMISED_CASE(16, IS_LOCK_FREE_16, __uint128_t)
[15:55:28]   ^
[15:55:28] /workspace/srcdir/llvm-project/compiler-rt/lib/builtins/atomic.c:250:12: note: expanded from macro 'OPTIMISED_CASE'
[15:55:28]     return __c11_atomic_load((_Atomic(type)*)src, model);\
[15:55:28]            ^
[15:55:28] /workspace/srcdir/llvm-project/compiler-rt/lib/builtins/atomic.c:272:1: error: atomic store requires runtime support that is not available for this target
[15:55:28] OPTIMISED_CASES
[15:55:28] ^
[15:55:28] /workspace/srcdir/llvm-project/compiler-rt/lib/builtins/atomic.c:238:3: note: expanded from macro 'OPTIMISED_CASES'
[15:55:28]   OPTIMISED_CASE(16, IS_LOCK_FREE_16, __uint128_t)
[15:55:28]   ^
[15:55:28] /workspace/srcdir/llvm-project/compiler-rt/lib/builtins/atomic.c:263:5: note: expanded from macro 'OPTIMISED_CASE'
[15:55:28]     __c11_atomic_store((_Atomic(type)*)dest, val, model);\
[15:55:28]     ^
[15:55:28] 2 errors generated.
[15:55:28] ninja: subcommands failed
[15:55:28]  ---> ninja -j${nproc} -vv
[15:55:28] Previous command exited with 1
[15:55:28] Child Process exited, exit code 1
```
?

**Comment by vchuravy** [comment]
Likely because we raised the minimum sdk version?

**Comment by vchuravy** [comment]
The error is tres bizzare. The codepath exists in later LLVM versions and the builds are all using the same target, and the same compiler...

You could try setting `-DCOMPILER_RT_EXCLUDE_ATOMIC_BUILTIN:Bool=On`, but I am very confused.

**Comment by vchuravy** [comment]
I suspect that those binaries were build from https://github.com/staticfloat/LLVMBuilder/blob/2c3b8c674f2d5bfecf38448ba96fa0c0ce656def/build_tarballs.jl and/or later so they are pre-historic. 

@staticfloat do you recall when we added Clang as a compiler for BB? I suspect that we used to build these with GCC.

**Comment by fingolfin** [comment]
Now tried to make it compile using GCC. That gives a different error: it tries to pass `-allow-shlib-undefined` to `ld`, but that rejects it as an "unknown option".

**Comment by fingolfin** [comment]
I experimented some more, switching this to use GCC as compiler. After some patching around, the latest errors on the Apple target is `ld: unknown option: -rpath-link`. Grepping through the LLVM build system, it is clear that inside the CMake files, the variable `APPLE` is *not* set to `true`; so all these errors I am battling with are consequence of that. I am also seeing this:
```
[19:58:57] CMake Warning:
[19:58:57]   Manually-specified variables were not used by the project:
[19:58:57] 
[19:58:57]     DARWIN_macosx_OVERRIDE_SDK_VERSION
```

**Pull request closed without merging**
