### PR TITLE
[Uno] update to v1.2.0

### PR DESCRIPTION
**Pull request by cvanaret**
cc @odow

### CODE REVIEW

**Comment by imciner2** [comment]
In general, you should do a version change if you change the gitsha - especially in this case since it is changing some actual code inside the solver.

(while we do technically support different builds of the same version, it isn't really supported by the Pkg system, so it is generally not suggested to use them)

**Comment by cvanaret** [comment]
Got it! So v"1.1.2" would be ok?

**Review by odow — CHANGES_REQUESTED** [review]
I was only bumping the gitsha without the version change because previous versions of Uno did not work, and I want to avoid the Yggdrasil version and the upstream version getting out of sync.

@cvanaret perhaps it's time for a new v1.2.0 upstream release?

**Comment by cvanaret** [comment]
I learn along the way :)
[Uno 1.2.0](https://github.com/cvanaret/Uno/releases/tag/v1.2.0) was released and the build_tarballs.jl was updated accordingly.

**Review by odow — APPROVED** [review]

**Pull request merged**
