### PR TITLE
SCALAPACK: new builder

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
Another one that's tons of fun to debug...

**Comment by dpo** [comment]
[This page](https://trac.macports.org/ticket/52316) says that the Fortran mangling issue could be due to a wrong linker being picked up (at least on macOS).

**Comment by dpo** [comment]
On i686-linux-musl, the error is a bit different:
```
Error loading shared library libgfortran.so.3: Exec format error
Error loading shared library libgcc_s.so.1: Exec format error
Error loading shared library libquadmath.so.0: Exec format error
```

**Comment by giordano** [comment]
> On i686-linux-musl, the error is a bit different:

This is very likely trying to run some code because it thinks we're doing a native build.  I already have used a work around for this other times

**Comment by giordano** [comment]
See for example https://github.com/JuliaPackaging/Yggdrasil/blob/b1ed82d21783442aede17e5c0112e10c0ba83647/G/Gnuastro/build_tarballs.jl#L19-L26

**Comment by giordano** [comment]
Oh, wait, this is using CMake, not autotools!  And looking to the succeeding platforms I guess it's trying to run everywhere a program...  This is just bad for cross-compilation :sob:

**Comment by dpo** [comment]
Is it only i686-linux-musl that can't run executables?

**Comment by giordano** [comment]
No, only x86_64-linux-* and i686-linux-gnu can. When I see that only these three platforms are successful I'm pretty sure that the failure is related to an attempt to run foreign executables

We should theoretically be able to run programs compiled for i686-linux-musl, but actually can't because of a bug.

**Comment by dpo** [comment]
Remaining errors:
* aarch64-linux-gnu and musl: `cannot find -lquadmath`
* armv7l-linux-gnueabihf and musl: `cannot find -lquadmath`
* powerpc64le-linux-gnu: `MPI Library NOT FOUND -- please set MPI_BASE_DIR accordingly`

**Comment by dpo** [comment]
Cool! I thought I tried that but must have messed up. Any idea what's going on on PowerPC?

**Comment by giordano** [comment]
> Any idea what's going on on PowerPC?

Yesterday I tried a little bit to debug it, but as usual CMake isn't very collaborative.  Interesting that with libgfortran5 it works :thinking:

**Comment by dpo** [comment]
Not sure if this is the root cause, but in `build/CMakeFiles/FindMPI`, there is `test_mpi.f90`. Trying to build it gives
```
sandbox:${WORKSPACE}/srcdir/scalapack-2.1.0/build/CMakeFiles/FindMPI # mpif90 -o test_mpi_f90.bin test_mpi.f90
/opt/powerpc64le-linux-gnu/bin/../lib/gcc/powerpc64le-linux-gnu/4.8.5/../../../../powerpc64le-linux-gnu/bin/ld: warning: libpthread.so.0, needed by /workspace/destdir/lib/libmpifort.so, not found (try using -rpath or -rpath-link)
/opt/powerpc64le-linux-gnu/bin/../lib/gcc/powerpc64le-linux-gnu/4.8.5/../../../../powerpc64le-linux-gnu/bin/ld: warning: librt.so.1, needed by /workspace/destdir/lib/libmpifort.so, not found (try using -rpath or -rpath-link)
/workspace/destdir/lib/libmpi.so: undefined reference to `pthread_create@GLIBC_2.17'
/workspace/destdir/lib/libmpi.so: undefined reference to `pthread_mutexattr_setpshared@GLIBC_2.17'
/workspace/destdir/lib/libmpi.so: undefined reference to `pthread_mutexattr_init@GLIBC_2.17'
/workspace/destdir/lib/libmpi.so: undefined reference to `pthread_mutexattr_destroy@GLIBC_2.17'
collect2: error: ld returned 1 exit status
```
I can build but not run with
```
sandbox:${WORKSPACE}/srcdir/scalapack-2.1.0/build/CMakeFiles/FindMPI # mpif90 -o test_mpi_f90.bin -L/lib64 -lpthread -lrt test_mpi.f90
sandbox:${WORKSPACE}/srcdir/scalapack-2.1.0/build/CMakeFiles/FindMPI # ./test_mpi_f90.bin
/lib64/ld64.so.2: No such file or directory
sandbox:${WORKSPACE}/srcdir/scalapack-2.1.0/build/CMakeFiles/FindMPI # mpif90 -o test_mpi_f90.bin -L/lib -lpthread -lrt test_mpi.f90
sandbox:${WORKSPACE}/srcdir/scalapack-2.1.0/build/CMakeFiles/FindMPI # ./test_mpi_f90.bin
/lib64/ld64.so.2: No such file or directory
```
I tried linking `/lib64/ld64.so.2` to `/lib64/ld-linux-x86-64.so.2`, but that results in
```
/lib64/ld64.so.2: Invalid ELF image for this architecture
```
Don't know if this is a clue that helps?!

**Comment by giordano** [comment]
`/lib64` contains libraries for the native system, you should _never_ use them.  Libraries for the target are in `/opt/${target}/${target}/lib` or `/opt/${target}/${target}/lib64`

**Comment by dpo** [comment]
libpthread isn't in there, so I'm not sure what the problem is.

**Comment by giordano** [comment]
Sorry, it's `/opt/${target}/${target}/sys-root/usr/lib64`

**Comment by dpo** [comment]
That doesn't solve it. Do you want to close this or exclude the problematic platform for now and move on?

**Comment by dpo** [comment]
Fix might be coming. Hold on.

**Comment by giordano** [comment]
I'm disabling PowerPC for the time being.  CMake is just useless, I can't find how it's failing, so I don't what to fix.   If you have an idea about what's the exact error making the MPI test failing and how to find it, please tell me.

**Comment by giordano** [comment]
> Fix might be coming. Hold on.

Uh, I've seen this too late.  Please, do push a fix if you have it!

**Comment by dpo** [comment]
MPI_Fortran should now be discovered. Around 66% of the build, we get this next error:
```
[15:43:09] /workspace/destdir/lib/libopenblas64_.so: undefined reference to `GOMP_parallel@GOMP_4.0'
[15:43:09] collect2: error: ld returned 1 exit status
```
I added `-lgomp` to `$OPENBLAS`, but that doesn't cut it.

**Comment by giordano** [comment]
I think you need to build with GCC v5 for that

**Comment by dpo** [comment]
There is a version of OpenBLAS for PowerPC with libgfortran3 though. So how does that work?

**Comment by dpo** [comment]
Is it the `preferred_gcc_version` thing?

**Comment by giordano** [comment]
> Is it the preferred_gcc_version thing?

Yes, OpenBLAS was built with GCC v6, here v5 should be hopefully sufficient.

> There is a version of OpenBLAS for PowerPC with libgfortran3 though. So how does that work?

libgfortran3 is up to GCC v6, see [`RootFS.md`](https://github.com/JuliaPackaging/Yggdrasil/blob/c9d46c4474502496a9933bf577bb5a69b8caf94e/RootFS.md#compiler-shards)

**Comment by dpo** [comment]
Testing now.

**Comment by dpo** [comment]
Fails with v5 with the same error. Testing v6.

**Comment by giordano** [comment]
> Fails with v5 with the same error

What error do you get?  I don't expect to be the same as before.

**Comment by dpo** [comment]
I get the exact same error with both v5 and v6. Is there anything else to do besides
```
build_tarballs(ARGS, name, version, sources, script, platforms, products, dependencies; preferred_gcc_version=v"5")
```

**Comment by dpo** [comment]
If I remove `-lgomp` and instead add `-fopenmp` to `FFLAGS`, I get the new error
```
[19:37:53]     /opt/powerpc64le-linux-gnu/bin/../lib/gcc/powerpc64le-linux-gnu/5.2.0/../../../../powerpc64le-linux-gnu/bin/ld: warning: libdl.so.2, needed by /opt/powerpc64le-linux-gnu/bin/../lib/gcc/powerpc64le-linux-gnu/5.2.0/../../../../powerpc64le-linux-gnu/lib/../lib64/libgomp.so, not found (try using -rpath or -rpath-link)
```
I added `-ldl` to the linker, but the error remains the same. The library is there:
```
sandbox:${WORKSPACE}/srcdir/scalapack-2.1.0/build # ll /opt/${target}/${target}/sys-root/lib64/libdl*.so*
-r-xr-xr-x    1 root     root        160160 Oct 12 04:01 /opt/powerpc64le-linux-gnu/powerpc64le-linux-gnu/sys-root/lib64/libdl-2.25.so*
lrwxr-xr-x    1 root     root            13 Oct 12 04:01 /opt/powerpc64le-linux-gnu/powerpc64le-linux-gnu/sys-root/lib64/libdl.so.2 -> libdl-2.25.so*
```
I tried the `-rpath` suggestion, but no luck.

Any other ideas? I've had it with that stupid platform.

**Comment by giordano** [comment]
Merging for the time being, maybe we'll have a look later :disappointed:

**Pull request merged**
