### PR TITLE
[Qt6Base] Targets build for v6.3.5

### PR DESCRIPTION
**Pull request by barche**
CC @simonbyrne

### CODE REVIEW

**Comment by barche** [comment]
I just realized that the host-then-target build sequence temporarily breaks GR in minor point upgrades like this, since QtBase 6.5.3 is already in the registry but only for x64 MUSL.

**Comment by barche** [comment]
Windows is failing because CMake can't find OpenSSL, I have no immediate idea on how to fix this, maybe someone else encountered this before using OpenSSL 3? CC @giordano

**Comment by barche** [comment]
Removing `-openssl-linked` on mingw is the only thing I can think of right now. For context, see: https://doc.qt.io/qt-6/ssl.html#enabling-and-disabling-ssl-support-when-building-qt-from-source

I *think* this should still pick up our openssl at runtime, and if not and someone complains (I don't think anyone is actually using the SSL-dependent Qt classes from within Julia) we can try to find a better fix.

**Comment by barche** [comment]
Feel free to merge if this builds and if you approve @giordano

**Comment by giordano** [comment]
Import libraries of openssl on x86_64 win are in `${prefix}/lib64` instead of `${prefix}/lib`, but setting LDFLAGS like in https://github.com/JuliaPackaging/Yggdrasil/blob/b524ac3c03e12e162435e5886e0b619fa32c8737/C/CyrusSASL/build_tarballs.jl#L46-L49 doesn't seem to help here.  I don't think I'll have much time to debug this, also because Qt build system is incredibly messed up and I'm not familiar with it, but in general we should have a better way to deal with this upgrades.  Why not doing the native build in all builds?  It's wasteful, but at least we don't have the problem of having broken packages between updates.

**Comment by giordano** [comment]
Also, why don't we hit ccache here?  Rebuilds with what should be warm cache take way too long.

**Comment by giordano** [comment]
https://github.com/JuliaPackaging/Yggdrasil/blob/bca4972591bcae84eecf051c8039a2f491a38601/Q/Qt6Base/build_tarballs.jl#L181 what is LLVM needed for?

**Comment by giordano** [comment]
I found https://github.com/JuliaPackaging/Yggdrasil/pull/2856#discussion_r615281072 but I don't think we should use LLVM_full_jll, but rather the compiler-rt stuff.

**Comment by barche** [comment]
Continuing discussion in PR #7629

**Pull request merged**
