### PR TITLE
[VegaFusion] Bump to 0.10.0

### PR DESCRIPTION
**Pull request by jeremiahpslewis**

### CODE REVIEW

**Comment by giordano** [comment]
```
[17:12:18]       /opt/bin/aarch64-linux-gnu-libgfortran3-cxx03/cc   -ffunction-sections -fdata-sections -fPIC -m64  -o CMakeFiles/cmTC_b02f2.dir/testCCompiler.c.o -c /workspace/srcdir/vegafusion/target/release/build/prost-build-c4a9fe4119e8474e/out/build/CMakeFiles/CMakeTmp/testCCompiler.c
[17:12:18]       aarch64-linux-gnu-gcc: error: unrecognized command line option ‘-m64’
```
Uh uh... looks like someone thought that it was a good idea to force `-m64` breaking cross-compilation.

**Comment by jeremiahpslewis** [comment]
Blocked by https://github.com/JuliaPackaging/Yggdrasil/pull/5527

**Comment by giordano** [comment]
This is trying to build for x86_64-linux-musl everywhere.  Don't ask me why.

**Comment by giordano** [comment]
I think #5527 broke the Rust toolchain, because now I can't build anything else.

**Comment by giordano** [comment]
This is finally working! Good to go?

**Comment by jeremiahpslewis** [comment]
Yep!

**Pull request merged**
