### PR TITLE
[GnuTLS] Upgrade to 3.7.8

### PR DESCRIPTION
**Pull request by lucifer1004**
This enables the build of the latest `glib-networking`, which is related to #5656

### CODE REVIEW

**Comment by lucifer1004** [comment]
Current issue with OSX:

```
[05:13:19] Undefined symbols for architecture x86_64:
[05:13:19]   "_rpl_malloc", referenced from:
[05:13:19]       _gnutls_secure_malloc in mem.o
[05:13:19]       _gnutls_malloc in mem.o
[05:13:19]       _gnutls_system_mutex_init in threads.o
[05:13:19]       _gnutls_load_file in file.o
[05:13:19]       _mdir_name in libgnu.a(dirname-lgpl.o)
[05:13:19]       _hash_initialize in libgnu.a(hash.o)
[05:13:19]       _allocate_entry in libgnu.a(hash.o)
[05:13:19]       ...
[05:13:19]   "_rpl_realloc", referenced from:
[05:13:19]       _gnutls_realloc in mem.o
[05:13:19]       __gnutls_fread_file in libgnu.a(read-file.o)
[05:13:19]       _rpl_getdelim in libgnu.a(getdelim.o)
[05:13:19]       _printf_parse in libgnu.a(printf-parse.o)
[05:13:19]       _vasnprintf in libgnu.a(vasnprintf.o)
[05:13:19]       __asn1_realloc in libminitasn1.a(decoding.o)
[05:13:19]       __asn1_realloc in libminitasn1.a(parser_aux.o)
[05:13:19]       ...
```

**Comment by lucifer1004** [comment]
Give up for now.

**Comment by jeremiahpslewis** [comment]
Hey! Here are the tweaks that seem to make the PR work: https://github.com/JuliaPackaging/Yggdrasil/pull/5672

**Comment by lucifer1004** [comment]
> Hey! Here are the tweaks that seem to make the PR work: #5672

Nice, then I will close my PR in favor of yours.

**Pull request closed without merging**
