### PR TITLE
[CUDA] Regenerate CUDA_SDK

### PR DESCRIPTION
**Pull request by amontoison**
Tim, I propose to add `yanked = true` for the previous release [here](https://github.com/JuliaRegistries/General/blob/7d59d07cee1ba8ec829523c7d8711267d1aac927/jll/C/CUDA_SDK_jll/Versions.toml#L100-L101).

### CODE REVIEW

**Comment by maleadt** [comment]
Nicely spotted, thanks.

**Comment by maleadt** [comment]
There's nothing to yank, though: https://github.com/JuliaRegistries/General/blob/2521f65219e3eb37bfa3a25b5cacdb86f66322b2/jll/C/CUDA_SDK_jll/Versions.toml

I'm not sure why a register wasn't triggered... https://buildkite.com/julialang/yggdrasil/builds/10660
@giordano Did I do something wrong in https://github.com/JuliaPackaging/Yggdrasil/commit/a8b3618b5691eedc9536512759d9c67c0c8616b2#diff-6a616eb06d0c52ba0c44a4656213ad37212220e1c05a47d4de72b8bfbefeed22?

**Comment by giordano** [comment]
I think it was registered as 12.4.1+2:

* https://github.com/JuliaRegistries/General/pull/107393
* https://buildkite.com/julialang/yggdrasil/builds/10660#018f9ffe-d3ed-435c-a825-94238636f856/556-576

**Comment by maleadt** [comment]
Oh, of course, the `version` was used as the JLL version too. Thanks!

**Pull request merged**
