### PR TITLE
[SLATEC] Initial builder for public domain Fortran math library SLATEC.

### PR DESCRIPTION
**Pull request by JuhaHeiskala**
Builder for SLATEC from www.netlib.org/slatec/

### CODE REVIEW

**Comment by giordano** [comment]
The package doesn't have a license

**Comment by JuhaHeiskala** [comment]
No license, SLATEC is in the public domain. (Tax payer funded work in the time it was written as far as I understand)

From the guide (http://www.netlib.org/slatec/guide)
```
SECTION 4.  OBTAINING THE LIBRARY
 
The Library is in the public domain and distributed by the Energy Science
and Technology Software Center.

               Energy Science and Technology Software Center
               P.O. Box 1020
               Oak Ridge, TN  37831
 
               Telephone  615-576-2606
               E-mail  estsc%a1.adonis.mrouter@zeus.osti.gov
```

**Comment by giordano** [comment]
> No license, SLATEC is in the public domain.

It doesn't matter, we still need a license file.  The AUR package bundles this file: https://aur.archlinux.org/cgit/aur.git/tree/LICENSE?h=slatec

**Comment by JuhaHeiskala** [comment]
That seems fine. How should it be incorporated, as the slatec repository doesn't have it?

**Comment by giordano** [comment]
> How should it be incorporated, as the slatec repository doesn't have it?

`sources` is a vector because we can have multiple source, and [`DirectorySource`](https://docs.binarybuilder.org/stable/reference/#BinaryBuilderBase.DirectorySource) allows us to bundle whatever files we want.  I'm using the same license file used by AUR

**Pull request merged**
