### PR TITLE
Tag a new build for libserialport to add experimental platforms

### PR DESCRIPTION
**Pull request by gbaraldi**
It should just work 🙏

### CODE REVIEW

**Review by giordano — CHANGES_REQUESTED** [review]
You must change version number: #2763

**Comment by gbaraldi** [comment]
The version numbers are weird, the last tagged version in upstream is 0.1.1. I guess I will put 0.1.3 and that's it. Also [LibSerialPort ](https://github.com/JuliaIO/LibSerialPort.jl) will have to become 1.6 right?

**Comment by giordano** [comment]
It doesn't _have_ to, but the new versions of the jll package will be available only in v1.6. At some point they'll likely want to do that anyway, especially since now v1.6 is the LTS

**Comment by gbaraldi** [comment]
Well the lib doesn't look like it sees many changes so I guess it's fine.

**Pull request merged**
