### PR TITLE
[qr_mumps] Version 3.0.2

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by amontoison** [comment]
+ AMD / COLAMD is not detected on Windows by default on Windows.
+ I'm not sure but it seems that we need `Bootstrapping` (https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/10) for checking  that SCOTCH and METIS are compiled with `Int32` or `Int64` : https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=9544&view=logs&j=8535053a-a49b-506b-fb1e-6612d403aa63&t=19ed140a-5fa2-50ba-bfb4-4a75a35013ae&l=478

**Comment by giordano** [comment]
I'm confused: the build worked, but the result isn't what you expect?

**Comment by amontoison** [comment]
Yes, on Windows `qr_mumps` was compiled without `AMD / COLAMD` because the libraries were not found.
I will investigate.

For the second issue, I need to ask @abuttari if it's a problem that `qr_mumps` compiled without knowing if SCOTCH and METIS were compiled with `Int32` / `Int64`.

**Comment by amontoison** [comment]
@giordano 
Let's merge this, we will see if it works or not in `qr_mumps.jl`.
I will solve the issue with `AMD / COLAMD` later on Windows.

**Pull request merged**
