### PR TITLE
add OpenSpiel

### PR DESCRIPTION
**Pull request by findmyway**
TODO:

- [ ] Use Julia_jll
- [ ] Support Mac os (Depends on the above one. Will make a minor release later)
- [x] Enable all games by default (We have some problems for the ACPC)

### CODE REVIEW

**Comment by findmyway** [comment]
The error is due to

> final link failed: No space left on device

https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=1478&view=logs&j=9f338677-a1f4-503e-790c-a58f3dc3b685&t=2483d461-f979-587b-ef3a-641fb5f6eb6a&l=5131

**Comment by giordano** [comment]
Is it possible to use tarballs instead of git repositories as sources? They might be considerably smaller

**Comment by findmyway** [comment]
Yeah, thanks. I will try it.

**Comment by giordano** [comment]
Well, at least if failed at a a later stage.  We need to fix this problem, though, we're having it also in other PRs (for example #475)

**Comment by findmyway** [comment]
So can this be merged now?

I'll make a patch release to support Mac OS later.

**Comment by giordano** [comment]
Ok, the choice of the supported platforms is up to you, but this warning needs to be addresse:
```
┌ Warning: /agent/_work/1/s/O/OpenSpiel/build/x86_64-linux-gnu-cxx03/xhbMBjFc/destdir/lib/libspieljl.so contains cxx11 ABI std::string values within its public interface, but we are supposedly building for cxx03 ABI. This usually indicates that the build system is somehow ignoring our choice of compiler, as we manually insert the correct compiler flags for this ABI choice!
└ @ BinaryBuilder /depot/packages/BinaryBuilder/SlQ9E/src/auditor/compiler_abi.jl:200
```

**Comment by findmyway** [comment]
Thanks for catching it!

Now I just removed `expand_cxxstring_abis`

**Comment by giordano** [comment]
Well, that's not the solution, in fact now you're getting
```
┌ Warning: /agent/_work/1/s/O/OpenSpiel/build/x86_64-linux-gnu/XEZIkET9/destdir/lib/libspieljl.so contains std::string values!  This causes incompatibilities across the GCC 4/5 version boundary.  To remedy this, you must build a tarball for both GCC 4 and GCC 5.  To do this, immediately after your `platforms` definition in your `build_tarballs.jl` file, add the line:
│ 
│     platforms = expand_cxxstring_abis(platforms)
└ @ BinaryBuilder /depot/packages/BinaryBuilder/SlQ9E/src/auditor/compiler_abi.jl:189
```

**Comment by findmyway** [comment]
Now I explicitly set the `compiler_abi` in the platform instead to avoid the warning. In fact, this package can not build with gcc below gcc 8 😢

**Comment by giordano** [comment]
> In fact, this package can not build with gcc below gcc 8 cry

That's not related: all versions of GCC from v5 (or was it v4.9?) onwards are able to build with both C++03- and C++11-style string ABI, it doesn't have to do with the C++ standard actually used.

@staticfloat any clue about what could cause the warning
```
┌ Warning: /agent/_work/1/s/O/OpenSpiel/build/x86_64-linux-gnu-cxx03/xhbMBjFc/destdir/lib/libspieljl.so contains cxx11 ABI std::string values within its public interface, but we are supposedly building for cxx03 ABI. This usually indicates that the build system is somehow ignoring our choice of compiler, as we manually insert the correct compiler flags for this ABI choice!
```
?  I don't see a conflicting setting of `_GLIBCXX_USE_CXX11_ABI` in the compiler invocation.

**Comment by giordano** [comment]
[This](https://gcc.gnu.org/ml/gcc-bugs/2019-08/msg00651.html) might be relevant:

> Unfortunately _GLIBCXX_USE_CXX11_ABI does not help in case of using
-std=gnu++11, because conditional compilation in some header files ignores
_GLIBCXX_USE_CXX11_ABI  and rely only on __cplusplus >= 201103. I have
cross-compiled two programs with patched "stdexcept" and they now run on the
old system too, so I believe that there is a way how to make all binaries
portable.

Here we're using `-std=gnu++17`

**Comment by findmyway** [comment]
I just enter the sandbox and check what's generated:

```bash
sandbox:${WORKSPACE} # cat /opt/bin/x86_64-linux-gnu-g++
#!/bin/bash
# This compiler wrapper script brought into existence by `generate_compiler_wrappers()`

if [ "x${SUPER_VERBOSE}" = "x" ]; then
    vrun() { "$@"; }
else
    vrun() { echo -e "\e[96m$@\e[0m" >&2; "$@"; }
fi

PRE_FLAGS=()
POST_FLAGS=()
ARGS_HASH="$(echo -n "$*" | sha1sum | cut -c1-8)"


if [ ${USE_CCACHE} == "true" ]; then
    vrun ccache /opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-g++  -frandom-seed=0x${ARGS_HASH} "${PRE_FLAGS[@]}" "$@" "${POST_FLAGS[@]}"
else
    vrun /opt/x86_64-linux-gnu/bin/x86_64-linux-gnu-g++  -frandom-seed=0x${ARGS_HASH} "${PRE_FLAGS[@]}" "$@" "${POST_FLAGS[@]}"
fi
```

But it seems that `_GLIBCXX_USE_CXX11_ABI` is missing here.

From the definition of [`gcc_base_flags`](https://github.com/JuliaPackaging/BinaryBuilder.jl/blame/8c89c90bbcc641227c88be6c941f6d1b3d700f29/src/Runner.jl#L176-L187). It should be inserted here?

Any idea?

**Comment by giordano** [comment]
> I just enter the sandbox and check what's generated:

How did you enter?

**Comment by findmyway** [comment]
Never mind. I just update BinaryBuilder.jl to v0.2.3 and it seems the `_GLIBCXX_USE_CXX11_ABI` is inserted correctly.

**Comment by staticfloat** [comment]
> Unfortunately _GLIBCXX_USE_CXX11_ABI does not help in case of using -std=gnu++11, because conditional compilation in some header files ignores _GLIBCXX_USE_CXX11_ABI  and rely only on __cplusplus >= 201103. 

Hmmm, that [contradicts the docs](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html):

> Although the changes were made for C++11 conformance, the choice of ABI to use is independent of the -std option used to compile your code, i.e. for a given GCC build the default value of the _GLIBCXX_USE_CXX11_ABI macro is the same for all dialects. This ensures that the -std does not change the ABI, so that it is straightforward to link C++03 and C++11 code together.

It looks like those docs are outdated.  The issue is, in `/workspace/srcdir/open_spiel/open_spiel/spiel.cc`, the usage of std::map<>::erase`; apparently that method, when `__cplusplus` is c++14 or greater, uses a `cxx11` ABI tag.  That might be a bug, it might not, in either case, it makes this package stricly `cxx11`-only.  :(

**Comment by giordano** [comment]
> That might be a bug, it might not, in either case, it makes this package stricly cxx11-only. :( 

Ok, so it looks like the builder is fine in its current form, I'm going to merge the pull request

**Pull request merged**
