### PR TITLE
Bump rr

### PR DESCRIPTION
**Pull request by Keno**
This should pick up experimental support for AMD Zen, as well as restoring trace compatibility with upstream rr.

### CODE REVIEW

**Comment by giordano** [comment]
```
[13:08:20] In file included from /workspace/srcdir/rr/src/Registers.cc:3:
[13:08:20] /workspace/srcdir/rr/src/Registers.h: In lambda function:
[13:08:20] /workspace/srcdir/rr/src/core.h:45:12: warning: control reaches end of non-void function [-Wreturn-type]
[13:08:20]      size_t s __attribute__((unused)) = sizeof(cond);                           \
[13:08:20]             ^
[13:08:20] /workspace/srcdir/rr/src/Registers.h:147:7: note: in definition of macro ‘ARCH_SWITCH_CASE’
[13:08:20]        arm64case;                                                               \
[13:08:20]        ^~~~~~~~~
[13:08:20] /workspace/srcdir/rr/src/Registers.h:184:5: note: in expansion of macro ‘DEBUG_ASSERT’
[13:08:20]      DEBUG_ASSERT(0 && "Hit an x86-only case, but this is not x86"))
[13:08:20]      ^~~~~~~~~~~~
[13:08:20] /workspace/srcdir/rr/src/Registers.h:364:44: note: in expansion of macro ‘RR_SET_REG_X86’
[13:08:20]    bool set_flags(uintptr_t value) { return RR_SET_REG_X86(eflags, eflags, value); }
[13:08:20]                                             ^~~~~~~~~~~~~~
```

**Comment by Keno** [comment]
That's just a warning. The error is about not having the `NT_` definitions for aarch64, which makes sense since our libc is ancient. I'll patch rr to look for those in the kernel headers instead.

**Comment by giordano** [comment]
Right, I missed to copy the errors from the lines below:
```
[13:08:22] /workspace/srcdir/rr/src/record_syscall.cc: In function ‘rr::Switchable rr::prepare_ptrace(rr::RecordTask*, rr::TaskSyscallState&)’:
[13:08:22] /workspace/srcdir/rr/src/record_syscall.cc:2627:14: error: ‘NT_ARM_HW_BREAK’ was not declared in this scope
[13:08:22]          case NT_ARM_HW_BREAK:
[13:08:22]               ^~~~~~~~~~~~~~~
[13:08:22] /workspace/srcdir/rr/src/record_syscall.cc:2628:14: error: ‘NT_ARM_HW_WATCH’ was not declared in this scope
[13:08:22]          case NT_ARM_HW_WATCH: {
[13:08:22]               ^~~~~~~~~~~~~~~
```

**Comment by Keno** [comment]
Alright, that fixed it, but I want to make one more change.

**Pull request merged**
