### PR TITLE
Add alsa_plugins to PortAudio

### PR DESCRIPTION
**Pull request by bramtayl**

### CODE REVIEW

**Comment by bramtayl** [comment]
Ok, well, I don't see any evidence that configure is even looking for the alsa plugins...so...what next? I feel like I'm really close.

**Comment by giordano** [comment]
> Ok, well, I don't see any evidence that configure is even looking for the alsa plugins

I'm not sure what you mean by this: this PR isn't needed?

**Comment by bramtayl** [comment]
Yeah, I'm not sure this will do anything. I've been working off of this comment: https://github.com/JuliaAudio/PortAudio.jl/issues/42#issue-566450599

**Comment by bramtayl** [comment]
I think #2740 or something like it would be necessary first

**Comment by bramtayl** [comment]
I'm seeing 

```
control.c: In function ‘snd_ctl_open_conf’:
[22:10:21] control.c:1336:39: warning: unknown escape sequence: '\$' [enabled by default]
[22:10:21]     buf1 = malloc(strlen(str) + sizeof(ALSA_PLUGIN_DIR) + 32);
[22:10:21]                                        ^
[22:10:21] control.c:1342:51: warning: unknown escape sequence: '\$' [enabled by default]
[22:10:21]     sprintf(buf1, "%s/libasound_module_ctl_%s.so", ALSA_PLUGIN_DIR, str);
```

**Pull request closed without merging**
