### PR TITLE
[BLAS32] Add a recipe

### PR DESCRIPTION
**Pull request by amontoison**
I will add a `BLAS_jll.jl` with the release `3.12.0`.
The new release will add an option to add the  suffix `_64` automatically.

With `BLAS32_jll.jl`, we will be able to compare the performances of the reference BLAS with OpenBLAS, Intel MKL, BLIS or AppleAccelerate for packages compiled with LBT.

### CODE REVIEW

**Review by ViralBShah — APPROVED** [review]

**Comment by ViralBShah** [comment]
How about just calling this package `ReferenceBLAS` and having both the 32-bit and 64-bit versions in there??

**Comment by amontoison** [comment]
I prefer `BLAS` than `ReferenceBLAS` but having the two libraries is a good idea.
The issue is that we already have `LAPACK32_jll.jl` / `LAPACK_jll.jl`, `OpenBLAS32_jll` / `OpenBLAS_jll` and `blis32_jll` / `blis_jll`.

**Comment by ViralBShah** [comment]
Well, this all sounded a bit familiar. So we already have it: https://github.com/JuliaPackaging/Yggdrasil/pull/7167

**Comment by amontoison** [comment]
Why did you use `ReferenceBLAS` and not `ReferenceLPACK`?
I was not aware that you already precompiled `BLAS`!

**Comment by ViralBShah** [comment]
I don't have a good explanation 😕 I just feel like BLAS is a little bit more general with multiple implementations whereas there is usually only one LAPACK.

**Comment by amontoison** [comment]
I think that the best thing to do is to update `ReferenceBLAS` and modernize its `build_tarballs.jl` with the future release 0.3.12.

**Pull request closed without merging**
