### PR TITLE
RFC: update the logo

### PR DESCRIPTION
**Pull request by KristofferC**
To:
tree_430

A bit more Julian?

### CODE REVIEW

**Comment by vchuravy** [comment]
I love it! I would propose a red sky and blue ground, with a purple tree, but ya know that's just me being fanciful.

**Review by giordano — APPROVED** [review]
:tada:

**Comment by Wimmerer** [comment]
Fantastique!

**Comment by KristofferC** [comment]
> I love it! I would propose a red sky and blue ground, with a purple tree, but ya know that's just me being fanciful.

Anyone should feel free to take it from here. I am already at the limit of my artistic ability :rofl:

**Pull request merged**
