### PR TITLE
Add builder for Julia Thrift IDL Compiler

### PR DESCRIPTION
**Pull request by tanmaykm**
This adds a builder for the Thrift IDL compiler for Julia. Includes additional patches to Thrift maintained [here](https://github.com/tanmaykm/thrift).

### CODE REVIEW

**Comment by visr** [comment]
Nice!

I wonder how this is passing on Windows though. In #514 we disabled Windows support for Bison. But here the build says:

```
Warning: Dependency Bison_jll does not have a mapping for Bison!
⋮
[02:29:16] checking for bison... yes
[02:29:16] checking for bison version >= 2.5... yes
[02:29:17] checking for bison... bison -y
```

**Comment by tanmaykm** [comment]
Looks like it may be detecting bison from elsewhere? I see:
```
sandbox:${WORKSPACE}/srcdir # which bison
/usr/bin/bison
```

We may not need Bison_jll here for building if that's the case for all platforms. I shall check and update the PR. Thanks!

**Comment by tanmaykm** [comment]
The PR mentions it is needed for arrow builder. I am not aware what exactly that needs, but looks like #931 that is for the thrift library - the libthrift.

**Comment by tanmaykm** [comment]
So yeah, though they both build from Apache Thrift, they build different things and are on different versions. This builds the idl compiler executable with additions to support Julia, to be used along with Thrift.jl. While from what I understand #931 is probably building the library that's needed for runtime use with arrow.

**Comment by tanmaykm** [comment]
Hmm... I do see `thrift` executable being built in #931. But since it will not have the changes needed for Julia, it won't be usable in Thrift.jl. It is some effort to move the changes to that version of thrift. And there are unresolved build issues. While it may be possible to merge the two later, it may be better to go with this now?

**Comment by giordano** [comment]
> While it may be possible to merge the two later, it may be better to go with this now?

Agreed

**Comment by aviks** [comment]
I think bison is generally used as a build time dependency, so the fact that it's picking it up from the build environment seems OK.

**Pull request merged**
