### PR TITLE
CeresSolver: new recipe

### PR DESCRIPTION
**Pull request by dpo**
No success using OpenMP on macOS so far. Setting the compiler to `gcc` results in `"/opt/bin/gcc" is not able to compile a simple test program`.

### CODE REVIEW

**Comment by dpo** [comment]
Getting a bunch of
```
┌ Warning: lib/libmudflapth.so.0.0.0 cannot be dlopen()'ed
└ @ BinaryBuilder /depot/packages/BinaryBuilder/dQyt9/src/Auditor.jl:146
##[warning]lib/libmudflapth.so.0.0.0 cannot be dlopen()'ed
```
and
```
curl: Can't open './products/CeresSolver*x86_64-linux-gnu-cxx11*.tar.gz'!
```

**Comment by giordano** [comment]
>     curl: Can't open './products/CeresSolver*x86_64-linux-gnu-cxx11*.tar.gz'!

Quoting from https://github.com/JuliaPackaging/Yggdrasil/pull/896#discussion_r410745251

> The directory name must exactly match, capitalisation included, this name.

**Comment by dpo** [comment]
Does that refer to the name of the formula?

**Comment by dpo** [comment]
Here are also some of those interesting errors: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=3715&view=logs&j=5dee3092-a96a-5085-aeff-50fab0013885&t=1e62515a-823e-527c-6447-2e6948e8e4b9

**Comment by giordano** [comment]
Yes.  The name of the tarballs comes from the `name` argument to the `build_tarballs()` function, but the upload uses the name of the directory.  You can understand what happens if the two names don't match.

**Comment by dpo** [comment]
Not sure how to debug the macOS build. Locally, I'm getting
```
clang-9: error: unable to execute command: Killed
```

**Comment by dpo** [comment]
I think all the warnings are due to the fact that this recipe depends on OpenBLAS32_jll, but it also depends on SuiteSparse_jll, which in turn depends on OpenBLAS_jll.

**Comment by giordano** [comment]
> I think all the warnings are due to the fact that this recipe depends on OpenBLAS32_jll, but it also depends on SuiteSparse_jll, which in turn depends on OpenBLAS_jll.

I wonder whether this needs a 32-bit suite sparse, which is coming in #1005

**Comment by dpo** [comment]
> I wonder whether this needs a 32-bit suite sparse, which is coming in #1005

It's a possibility, but wouldn't that prevent users from installing this formula alongside a standard 64bit SuiteSparse?

**Comment by giordano** [comment]
What is being done in #1005 is to have two separate packages, with different library names, for the two implementations, so that they can coexist

**Comment by dpo** [comment]
Sweet!

**Comment by dpo** [comment]
Building with gcc/g++ on FreeBSD and macOS, but that still doesn't enable OpenMP. The [build instructions](http://ceres-solver.org/installation.html#building-with-openmp-on-os-x) say that we should use  a more recent LLVM (on macOS). But is that available here?

**Comment by giordano** [comment]
> Building with gcc/g++ on FreeBSD and macOS, but that still doesn't enable OpenMP

Are you sure you're using GCC?  With CMake you can't just set `CC` and `CXX`: https://juliapackaging.github.io/BinaryBuilder.jl/dev/build_tips/#Using-GCC-on-macOS-and-FreeBSD-1

> The build instructions say that we should use a more recent LLVM (on macOS). But is that available here?

[This](https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/c3fbfc0005d7f9ea01f3c7764a56f1e181b1a04f/src/Rootfs.jl#L356-L361) is the list of available LLVM builds, by default the latest LLVM version is used.  Do they require something newer than 9.0.1?

**Comment by dpo** [comment]
You're right; here it is with the gcc toolchain but locally I get a segfault.

**Comment by dpo** [comment]
Not sure about LLVM. Homebrew ships version 10.0, but it was probably not version 10.0 at the time the CeresSolver build directions were written. However, OpenMP isn't picked up with clang/clang++.

**Comment by dpo** [comment]
Found this about the warnings on macOS: https://stackoverflow.com/questions/38193043/disable-assembler-warning-section-text-textcoal-nt-coalesced-pure-instruct. Not sure what to do about them.

Regarding the error message
```
 Undefined symbols for architecture x86_64:
   "google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()",
```
[this post](https://github.com/ceres-solver/ceres-solver/issues/291#issuecomment-307469888) suggests that dependency `glog_jll` wasn't built with C++11 enabled. However, it seems that the C++11 variant is indeed pulled in in the macOS build?!

**Comment by giordano** [comment]
The error is super annoying.   The problem is that glog has been compiled for macOS with Clang, which doesn't have the [dual C++ ABI](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html) that GCC has.  In practice, the cxx11 and cxx03 libraries we build with Clang (typically for macOS and FreeBSD) are identical.  I think the linker here is looking for the glog symbol with the GCC ABI, but can't find it.  I don't have a good solution at the moment, apart from recompiling glog with GCC (which doesn't sound like a great solution).

You may be asking why we don't have the same issue for FreeBSD as it's in a similar situation -- glog compiled with Clang, this library with GCC: we have it, but the linker didn't complain:
```
% nm  x86_64-unknown-freebsd11.1-cxx11/lib/libceres.so | c++filt | grep google::base::CheckOpMessageBuilder::NewString
                 U google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()
```
it just left the symbol undefined.

**Comment by dpo** [comment]
You're the overlord of build errors :-). The macOS build succeeds if I disable GLOG support (CeresSolver ships with a mock GLOG that can be used in place of the real thing). Shall I do the same for FreeBSD?

**Comment by giordano** [comment]
> You're the overlord of build errors :-).

I've learnt some things the hard way :slightly_smiling_face: 

> The macOS build succeeds if I disable GLOG support (CeresSolver ships with a mock GLOG that can be used in place of the real thing).

Ok, if this doesn't break functionalities of the package this is a great solution!

> Shall I do the same for FreeBSD?

Yes, please

**Comment by dpo** [comment]
Done. There remains the question of SuiteSparse32.

**Comment by giordano** [comment]
Not sure SuiteSparse32 is going to happen, so maybe we can merge this and see how it goes

**Pull request merged**
