### PR TITLE
Upgrade to msys2 binaries

### PR DESCRIPTION
**Pull request by musm**
- Use binaries provided from msys2 (they finally updated hdf5 after pushing the patches I sent).
- Reverted the changes made before upgrading to use my binaries.

### CODE REVIEW

**Comment by musm** [comment]
cc @ararslan , @staticfloat

**Comment by musm** [comment]
@ararslan  can we go ahead and merge? This is non-destructive and we can always revert. I want to test if it works on the master HDF5 repo. If it doesn't we can always revert back. 
Thanks

**Comment by staticfloat** [comment]
Sorry Musm, I've been quite busy building other binaries.  :)

**Comment by musm** [comment]
thanks!!! no worries!

**Comment by staticfloat** [comment]
https://github.com/JuliaPackaging/Yggdrasil/releases/tag/HDF5-v1.10.5%2B3

**Pull request merged**
