### PR TITLE
[pprof] Build for Apple Silicon

### PR DESCRIPTION
**Pull request by Keno**

### CODE REVIEW

**Comment by Keno** [comment]
arg, I guess this requires a version bump to work. What's the default answer here now these days @staticfloat @giordano @vchuravy ?

**Comment by vchuravy** [comment]
Just bump it to `0.1.1` it's meaningless anyway since pprof doesn't have proper version

**Comment by vchuravy** [comment]
cc: @NHDaly

**Comment by giordano** [comment]
Do you also want to build a more recent version?

**Comment by Keno** [comment]
I'm ok with whatever version is available, but if somebody else wants something newer, might as well.

**Comment by giordano** [comment]
Allright, we can update the upstream version in a later pull request

**Comment by NHDaly** [comment]
@giordano TBH I think there's something weird going on with the pprof build version we have currently. I'm actually not seeing the upstream bug fix that we put into pprof in our build, which makes me wonder if we're somehow not actually using the commit we think we are? 🤔 i've worked around it in the julia code in PProf.jl, so it's fine, but maybe doing another upstream version bump could help? I'd be supportive of that anyway, yeah... 🤷

**Comment by giordano** [comment]
That looks...unlikely.  We never had similar reports for other packages.  I think it's a bit hard to verify what version pprof was built against (they don't seem to show anything like that anywhere?), but if I try to run the recipe locally and drop into the shell I can see
```console
sandbox:${WORKSPACE}/srcdir/pprof # git rev-parse --short HEAD
20978b5
```
which seems to be indeed the right hash.

**Comment by NHDaly** [comment]
huh, weird. thanks! Well maybe i didn't actually fix the bug upstream after all! 😋

**Pull request merged**
