### PR TITLE
[LAPACK] Upgrade to v3.10.1 and require newer libblastrampoline

### PR DESCRIPTION
**Pull request by giordano**
Libblastrampoline v5.4.0 is compatible only with Julia v1.9+, but it has a stable ABI on all platforms, including Windows.

CC: @fredrikekre.

### CODE REVIEW

**Comment by ViralBShah** [comment]
How about the lapack 3.11.0 PR that is open?

**Comment by giordano** [comment]
I wanted to make a smaller jump first.

**Review by ViralBShah — APPROVED** [review]

**Comment by giordano** [comment]
Compilation for aarch64-linux-*-libgfortran4 is crashing (looks like an ICE on both glibc and musl), but we don't have many other compilers for those versions of libgfortran (to be clear, libgfortran4 corresponds _only_ to GCC 7), so this is quite problematic.  Sigh.

**Comment by amontoison** [comment]
Don't we need LBT v"5.7.0" for LAPACK_jll?
https://github.com/JuliaLinearAlgebra/libblastrampoline/pull/114

**Comment by ViralBShah** [comment]
I believe 5.4 is used in Julia 1.9, although there is a PR to backport 5.7.

**Comment by amontoison** [comment]
I don't think that 5.7 can be backported because it was compiled with a Julia compat `1.10`.

**Pull request merged**
