### PR TITLE
[Sundials] Build 6.5.1

### PR DESCRIPTION
**Pull request by ViralBShah**

### CODE REVIEW

**Comment by giordano** [comment]
clock_gettime requires linking to librt with old glibc versions, such as those we use for i686 and x86_64 Linux

**Comment by Wimmerer** [comment]
https://salsa.debian.org/science-team/sundials/-/tree/debian/sid/debian/patches

Debian disabled all tests with KLU (and maybe LAPACK etc)? LAPACK gives me errors locally even if I tell it that KLU works.

**Comment by Wimmerer** [comment]
@ViralBShah with `DLAPACK_WORKS=ON` and `DKLU_WORKS=ON` I get successful *build* locally. I haven't run audit though.

**Comment by ViralBShah** [comment]
https://github.com/JuliaRegistries/General/pull/87307 needs to be addressed and merged before merging this one.

**Pull request merged**
