### PR TITLE
[libcellml] Update to version 0.4.0

### PR DESCRIPTION
**Pull request by hsorby**

### CODE REVIEW

**Comment by giordano** [comment]
https://buildkite.com/julialang/yggdrasil/builds/456#0185ef94-c0d2-427c-bf0a-735d89299a8d/650-965
```
[21:23:59] /workspace/srcdir/libcellml/src/xmldoc.cpp: In function ‘std::__cxx11::string libcellml::decompressMathMLDTD()’:
[21:23:59] /workspace/srcdir/libcellml/src/xmldoc.cpp:105:93: error: cannot convert ‘UNCOMPRESS_SIZE_TYPE* {aka long long unsigned int*}’ to ‘uLongf* {aka long unsigned int*}’ for argument ‘2’ to ‘int uncompress(Bytef*, uLongf*, const Bytef*, uLong)’
[21:23:59]      uncompress(&mathmlDTD[0], &sizeMathmlDTDUncompressedResize, a, COMPRESSED_MATHML_DTD_LEN);
[21:23:59]                                                                                              ^
[21:23:59] /workspace/srcdir/libcellml/src/xmldoc.cpp: In member function ‘void libcellml::XmlDoc::parseMathML(const string&)’:
[21:23:59] /workspace/srcdir/libcellml/src/xmldoc.cpp:134:23: warning: ‘void xmlCleanupGlobals()’ is deprecated [-Wdeprecated-declarations]
[21:23:59]      xmlCleanupGlobals();
[21:23:59]                        ^
```
sounds like an upstream bug?

**Comment by hsorby** [comment]
No, that is me.  I need to do a better test for the API that I am using.  I will need to make changes to libCellML itself to fix this,  I will start the process for making the required changes there.

**Comment by giordano** [comment]
Alright, I'll have a look at the macOS problem (we have to use the 10.14 SDK), thanks for all the work so far!

**Comment by hsorby** [comment]
Great, thanks. I have been trying to figure out what is happening there and how I might fix it.

**Comment by giordano** [comment]
We're all good now :slightly_smiling_face:  Thanks again for your contribution, much appreciated!

**Comment by hsorby** [comment]
Thank you for your help.  I will progress the required changes into the correct location and the update the PR and make it ready for review when that is done.  Once again thanks, would have taken me hours to figure that change out.

**Comment by giordano** [comment]
Sadly we have to do it in a few places.  I hope that in a not-so-distant future we can more easily select the SDK to use, instead to use this hack.

**Comment by giordano** [comment]
Awesome, thanks again for your contribution!

**Pull request merged**
