### PR TITLE
[CGAL] Trigger re-build to register up to date jll

### PR DESCRIPTION
**Pull request by rgcv**

### CODE REVIEW

**Comment by giordano** [comment]
Yeah, sorry, we've had some problems yesterday with registration. Now everything should be in place, I've also added a test in https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/656 featuring CGAL, but I forgot to retrigger the build after fixing. Thanks for doing this!

**Comment by rgcv** [comment]
No problem! I noticed things were a bit finicky lately, but that's perfectly fine. You guys already do more than enough and have plenty to deal with at once, something is bound to slip through the cracks every now and again :wink: So thank you for working on streamlining this process, I love it!

**Comment by rgcv** [comment]
Unfortunately, it looks like it tanked again when running for `armv7l-linux-gnueabihf-cxx11`. [It's a `git` specific error](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=1454&view=logs&j=cfee86f2-e63f-56d8-3240-58213141d5db&t=22ccb885-1f00-557d-15e9-ea3af3d12a0f&l=23), when attempting to access the index when it has been locked.

The 5.0.1 artifacts already exist on the [jll repo](https://github.com/JuliaBinaryWrappers/CGAL_jll) from a previous attempt, but registry still failed nonetheless. Can't catch a break!

**Comment by giordano** [comment]
Fixed: https://github.com/JuliaRegistries/General/pull/9158 :wink:

**Pull request merged**
