### PR TITLE
PROJ: New version 9.4.0

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by ararslan** [comment]
Looks like you might need to update the `preferred_gcc_version`?

**Comment by visr** [comment]
Hmm since this changes the DLL name from `libproj_9_3.dll` to `libproj_9_4.dll` it is breaking on Windows. It needed the `version_offset` major version to be bumped like in https://github.com/JuliaPackaging/Yggdrasil/pull/7366. We should probably write this in a comment next to the version numbers.

Now that it is out, I guess General needs to be updated to block PROJ_jll 901.400? Or better to just yank it?

**Comment by eschnett** [comment]
Is it actually incompatible? Would changing the library name on Windows to `libproj_9_3.dll` be another option?

**Comment by visr** [comment]
I think it is only the library name on Windows that is the issue I think. The [PROJ_SOVERSION](https://github.com/OSGeo/PROJ/blob/9.4.0/CMakeLists.txt#L145) is the same so the ABI should otherwise be the same.

**Comment by eschnett** [comment]
That's also how the release notes read. Should we then rename the Windows libraries (and add respective comments) instead of blocking or yanking the package?

**Comment by visr** [comment]
I'd be fine with that if others agree. It seems like the smoothest upgrade path. I tried locally renaming the DLL in the artifact, and `dev PROJ_jll` with the same renames. That didn't work yet however, it is not clear why:

```
julia> using GDAL_jll
ERROR: InitError: could not load library "C:\Users\visser_mn\.julia\artifacts\415bbbe8ca2ee27f90b17984069673e280f25d0d\bin\libgdal-35.dll"
The specified module could not be found.
```

Note that GDAL_jll has a PROJ_jll dependency, but also via libgeotiff_jll. It is libgeotiff_jll that gives the errors: https://github.com/yeesian/ArchGDAL.jl/issues/427

Of course it could be confusing that PROJ 9.4 has a `libproj_9_3.dll`. Going forward I'd rather not have the minor version in the name. As far as I can see this is not configurable, but we could ask upstream or patch ourselves:

https://github.com/OSGeo/PROJ/blob/9.4.0/cmake/ProjVersion.cmake#L40-L46
https://github.com/OSGeo/PROJ/blob/9.4.0/cmake/ProjUtilities.cmake#L37-L63
https://github.com/OSGeo/PROJ/pull/3066

**Comment by visr** [comment]
Actually the `libgdal-35.dll` seems to be a separate issue affecting the new GDAL_jll versions, because forcing `PROJ_jll@901.300` does not resolve that. Users need to downgrade both; `add PROJ_jll@901.300 GDAL_jll@301.800.500`.

**Comment by visr** [comment]
I propose we yank these two broken/breaking releases; https://github.com/JuliaRegistries/General/pull/107721

Regarding the libproj DLL name, I also created an upstream issue: https://github.com/OSGeo/PROJ/issues/4151

**Comment by joa-quim** [comment]
> Is it actually incompatible? Would changing the library name on Windows to libproj_9_3.dll be another option?

Unfortunately that does not work on Windows because the dll name in embedded in the dll itself.

**Pull request merged**
