### PR TITLE
[Leptonica] Upgrade to v1.79.0

### PR DESCRIPTION
**Pull request by pixel27**
This pull request contains a new build recipe I built using the BinaryBuilder.jl wizard:

* Package name: Leptonica
* Version: v1.79.0

@staticfloat please review and merge.

### CODE REVIEW

**Comment by giordano** [comment]
There was already a recipe for this package.  You used a newer version, but built for fewer platforms, I'll try to merge the changes.

**Comment by pixel27** [comment]
Unfortunately I couldn't get it building for Windows.  The build instructions mention downloading sw client from https://software-network.org/client/ which I could do, but I couldn't run the program in the environment, it needed libstdc++.6.so if I remember correctly but couldn't find it.

**Comment by pixel27** [comment]
I wasn't sure what the process was for moving versions.  I read through the BinaryBuilder documentation but I didn't see anything out updating packages.  So I just assumed it was the run_wizard() path which was documented.

One thing I'm wondering about is 1.78.0 (the previous) version was not compiled with GIF support.  I believe this build has it, at least cmake mentioned that it found the libgif.  

If there is a different process to go through for updating version numbers I'd love to know what it is, since I kind of want to update tesseract next.

**Comment by giordano** [comment]
> I wasn't sure what the process was for moving versions. I read through the BinaryBuilder documentation but I didn't see anything out updating packages. So I just assumed it was the run_wizard() path which was documented.

What you did is fine, but the easiest thing to do to update the version of a package is to just open a pull request here and update the source as appropriate.  In this way you don't have to spend time to build locally.  This is in the end what we're doing here.

> One thing I'm wondering about is 1.78.0 (the previous) version was not compiled with GIF support. I believe this build has it, at least cmake mentioned that it found the libgif.

For this build I get:
```
% % ldd Leptonica.v1.79.0.x86_64-linux-gnu/lib/liblept.so.5
        linux-vdso.so.1 (0x00007fff531ba000)
        libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007ff728dec000)
        libjpeg.so.62 => not found
        libgif.so.7 => /usr/lib/libgif.so.7 (0x00007ff728de1000)
        libtiff.so.5 => /usr/lib/libtiff.so.5 (0x00007ff728d52000)
        libwebpmux.so.3 => /usr/lib/libwebpmux.so.3 (0x00007ff728d46000)
        libwebp.so.7 => /usr/lib/libwebp.so.7 (0x00007ff728cd6000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007ff728b8e000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007ff728b74000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007ff728b52000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007ff72898c000)
        libzstd.so.1 => /usr/lib/libzstd.so.1 (0x00007ff7288e2000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007ff7288ba000)
        libjpeg.so.8 => /usr/lib/libjpeg.so.8 (0x00007ff728821000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007ff729360000)
```
Looks like libgif is there

**Pull request merged**
