### PR TITLE
Add Doxygen-1.9.2

### PR DESCRIPTION
**Pull request by marcom**
- Libiconv_jll added for aarch64-apple-darwin, auditor was complaining
- not sure if it should be Doxygen or doxygen

### CODE REVIEW

**Comment by marcom** [comment]
Hmm, without the `Libiconv_jll` dependency, it compiles everywhere except `aarch64-apple-darwin`. With the `Libiconv_jll` dependency, it fails on linux and freebsd.

**Comment by giordano** [comment]
> With the Libiconv_jll dependency, it fails on linux and freebsd.

Why does it fail?

**Comment by giordano** [comment]
I'm curious to know what you need Doxygen for though :swe

**Comment by marcom** [comment]
Many thanks @giordano, hadn't thought of simply patching out the check! I wanted to build OpenMM and i was unable to get it to build without doxygen, maybe there would have been an easier solution there as well... Anyways, thanks a lot for the help! :)

**Comment by giordano** [comment]
But isn't doxygen a build-only tool for the host?  https://docs.binarybuilder.org/stable/build_tips/#Dependencies-for-the-target-system-vs-host-system

**Comment by marcom** [comment]
> But isn't doxygen a build-only tool for the host? https://docs.binarybuilder.org/stable/build_tips/#Dependencies-for-the-target-system-vs-host-system

Yes, and reading the link i think i should have used apk to install doxygen in the OpenMM build script.

**Comment by giordano** [comment]
Well, now you can use a [`HostBuildDependency`](https://docs.binarybuilder.org/stable/reference/#BinaryBuilderBase.HostBuildDependency) :slightly_smiling_face:  This has the nice property of being cached, contrary to packages installed via `apk` :wink:

**Comment by marcom** [comment]
Ok i'll do it that way, thanks for the tip! :)

**Pull request merged**
