### PR TITLE
[NetCDF] fix MbedTLS version

### PR DESCRIPTION
**Pull request by visr**
Since this library gave it a failure on loading the JLL package.
As suggested by @giordano in https://github.com/JuliaPackaging/Yggdrasil/pull/2125#issuecomment-729904159.

### CODE REVIEW

**Comment by giordano** [comment]
The log of #2125 contains
```
checking for curl_easy_setopt in -lcurl... yes
checking for library containing curl_easy_setopt... -lcurl
```
for x86_64-linux-gnu, no idea why now we're getting
```
[19:51:52] checking for curl_easy_setopt in -lcurl... no
[19:51:53] checking for library containing curl_easy_setopt... no
[19:51:53] configure: error: curl required for remote access. Install curl or build with --disable-dap.
```

**Comment by visr** [comment]
Could it be since we are holding back the MbedTLS but building on julia 1.6 this creates issues?

**Comment by giordano** [comment]
No, since the build environment doesn't have anything to do with the Julia version.  And it worked for AzStorage (#2050)

**Comment by giordano** [comment]
I just realised this script creates a couple of symlinks for libhdf5, this is very wrong

**Comment by giordano** [comment]
I've removed the symlinks.  This is going to fail, the symlinks should be created in hdf5, not here.  I don't have the time to do that though

**Comment by visr** [comment]
Ok thanks! Good to see we had a green checkmark before the last commit though :)

**Comment by giordano** [comment]
And also the link `libz.dll` -> `libzlib1.dll` in the Windows package for HDF5... :facepalm:

**Comment by giordano** [comment]
Finally working properly!

```
% tree x86_64-w64-mingw32 
x86_64-w64-mingw32
├── bin
│   ├── libnetcdf-18.dll
│   └── nc-config
├── include
│   ├── netcdf_aux.h
│   ├── netcdf_dispatch.h
│   ├── netcdf_filter.h
│   ├── netcdf.h
│   ├── netcdf_mem.h
│   └── netcdf_meta.h
├── lib
│   ├── libh5bzip2.dll
│   ├── libh5bzip2.dll.a
│   ├── libh5bzip2.la
│   ├── libnetcdf.dll.a
│   ├── libnetcdf.la
│   ├── libnetcdf.settings
│   └── pkgconfig
│       └── netcdf.pc
├── logs
│   └── NetCDF.log.gz
└── share
    ├── licenses
    │   └── NetCDF
    │       └── COPYRIGHT
    └── man
        └── man3
            └── netcdf.3
```
Do you need `libh5bzip2.dll`?

**Comment by visr** [comment]
That's great!

> Do you need libh5bzip2.dll?

Not as far as I know. It seems to be a bzip2 plugin. We could leave it out for know and include it if it turns out we need it after all. I found this reference: https://github.com/Unidata/netcdf-c/pull/1348

**Comment by Alexander-Barth** [comment]
Strangely, I still get an error on julia 1.6.0-DEV.1699 and 1.7.0-DEV.136:

On julia 1.6.0-DEV.1699 with NetCDF_jll v4.7.4+1, I have this error message:

```
julia> using NetCDF_jll
ERROR: InitError: could not load library "/home/ulg/gher/abarth/.julia/artifacts/877149aedda703fde4a848bffd955df8934ca876/lib/libnetcdf.so"
libmbedtls.so.12: cannot open shared object file: No such file or directory
Stacktrace:
[1] dlopen(s::String, flags::UInt32; throw_error::Bool)
   @ Base.Libc.Libdl ./libdl.jl:114
 [2] dlopen(s::String, flags::UInt32)
   @ Base.Libc.Libdl ./libdl.jl:114
 [3] macro expansion
   @ ~/.julia/packages/JLLWrappers/KuIwt/src/products/library_generators.jl:61 [inlined]
 [4] __init__()
   @ NetCDF_jll ~/.julia/packages/NetCDF_jll/y27Nj/src/wrappers/x86_64-linux-gnu.jl:14
 [5] _include_from_serialized(path::String, depmods::Vector{Any})
   @ Base ./loading.jl:669
 [6] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
   @ Base ./loading.jl:755
 [7] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:993
 [8] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:909
 [9] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:896
during initialization of module NetCDF_jll
```
In `~/.julia/packages/NetCDF_jll/y27Nj/Project.toml`, I see the dependency on  MbedTLS_jll but without explicit version number:

```name = "NetCDF_jll"
uuid = "7243133f-43d8-5620-bbf4-c2c921802cf3"
version = "4.7.4+1"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
LibSSH2_jll = "29816b5a-b9ab-546f-933c-edad1886dfa8"
LibCURL_jll = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0"
MbedTLS_jll = "c8ffd9c3-330d-5841-b78e-0817d7145fa1"
nghttp2_jll = "8e850ede-7688-5339-a07c-302acd2aaf8d"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
HDF5_jll = "0234f1f7-429e-5d53-9886-15a909be8d59"

[compat]
JLLWrappers = "1.1.0"
julia = "1.0"
HDF5_jll = "=1.12.0"
```

Maybe this fix not yet released?

**Comment by Alexander-Barth** [comment]
The workaround is to load explicitly `MbedTLS_jll`

```
julia> using NetCDF_jll
ERROR: InitError: could not load library "/home/ulg/gher/abarth/.julia/artifacts/877149aedda703fde4a848bffd955df8934ca876/lib/libnetcdf.so"
libmbedtls.so.12: cannot open shared object file: No such file or directory
Stacktrace:
[...]
julia> using MbedTLS_jll
julia> using NetCDF_jll  # no errors
```

**Comment by visr** [comment]
The NetCDF_jll is built with a fixed version, but does not have a fixed version as a compat, so that is expected. I'm not sure why it cannot find MbedTLS on recent julia though. Could be that it just needs a rebuild since there recently have been changes in julia to how shipped libraries like MbedTLS are now handled like Artifacts.

**Comment by visr** [comment]
@Alexander-Barth that issue is https://github.com/JuliaLang/julia/issues/39015

**Pull request merged**
