### PR TITLE
Update MKL to 2021.1.1

### PR DESCRIPTION
**Pull request by ViralBShah**

### CODE REVIEW

**Review by giordano — APPROVED** [review]
Changes look good, but it seems they once again changed the files structure in the Window package...

**Comment by ViralBShah** [comment]
Basically, the txt files seem to be missing on windows.

**Comment by ViralBShah** [comment]
Looks like the windows now has the same paths for the licenses.

**Comment by ViralBShah** [comment]
What's the reason to make MKL a lazy artifact? Shouldn't we always install it when required?

**Comment by giordano** [comment]
Oh yeah, like it was last year: https://github.com/JuliaPackaging/Yggdrasil/commit/6c03359ca37f82ab2254d5267b9d2fd5a6003540.  They seem to like moving files back and forth

**Comment by giordano** [comment]
> What's the reason to make MKL a lazy artifact? Shouldn't we always install it when required?

MKL is proprietary, it's large, it's a dependency of `FFTW.jl` and it isn't even used by default: https://github.com/JuliaMath/FFTW.jl/issues/133

**Comment by ViralBShah** [comment]
Ah it is an optional dependency there. Makes sense.

**Comment by ViralBShah** [comment]
I wonder why it can't find `mkl_core`. There is a file in the distribution called `mkl-core.1.dll`. Is it the `.1` that is a problem?

```
[ Info: Found a valid dl path mkl_vml_mc3.1.dll while looking for libmkl_core, mkl_core
[ Info: Could not locate libmkl_core, mkl_core inside ["/agent/_work/1/s/M/MKL/build/x86_64-w64-mingw32/jIJ1g1rr/destdir/bin"]
┌ Error: Built MKL but libmkl_core still unsatisfied:
└ @ BinaryBuilder /depot/packages/BinaryBuilder/57NRU/src/AutoBuild.jl:761
##[error]Built MKL but libmkl_core still unsatisfied:
```

**Comment by giordano** [comment]
Yes, it should be called `mkl-core.1`:
```
julia> using Base.BinaryPlatforms

julia> parse_dl_name_version("mkl-core.1.dll", "windows")[1] 
"mkl-core.1"
```

**Pull request merged**
