### PR TITLE
Run init_jll serially.

### PR DESCRIPTION
**Pull request by maleadt**
@giordano like this?
If so, I'll attach a bump to the recently-failed JLL build here.

### CODE REVIEW

**Comment by giordano** [comment]
Yes, let's try this

**Comment by giordano** [comment]
:crossed_fingers:

**Comment by giordano** [comment]
Nope :confused:

**Comment by maleadt** [comment]
I'll bump them separately, I guess...

**Comment by giordano** [comment]
I'm having a hard time understanding what's wrong in https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/40098a71ab3213c11cfbf1e5033fb99ccd616ba5/src/AutoBuild.jl#L902-L903  The first two runs work, the last two fail

**Comment by giordano** [comment]
Ok, maybe the failing job is two lines below (there has been a recent change in BB which we didn't pull yet which makes the file line in the stacktrace inaccurate): https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/40098a71ab3213c11cfbf1e5033fb99ccd616ba5/src/AutoBuild.jl#L904-L906

**Pull request merged**
