### PR TITLE
[NetCDF] Simplify NetCDF build script

### PR DESCRIPTION
**Pull request by Alexander-Barth**
* require LibCURL_jll 7.73.0
* drop support for julia 1.3
* single build script
* ~~enable Zstandard~~

See also issue https://github.com/JuliaPackaging/Yggdrasil/issues/4511

### CODE REVIEW

**Comment by mkitti** [comment]
I'm just curious how the Zstandard integration works here. I would like to test how that interacts with https://github.com/JuliaIO/HDF5.jl/tree/master/filters/H5Zzstd

**Comment by visr** [comment]
@mkitti it hasn't quite been hooked up yet in the netcdf wrapper packages, though see https://github.com/JuliaGeo/NetCDF.jl/issues/160#issuecomment-1210890474.

Both approaches would use the same Zstd_jll. What kind of interaction are you thinking about? I'd be very strange for someone to use both on the same file, since they'd probably do similar things, one just going through the `libnetcdf` interface.

**Comment by Alexander-Barth** [comment]
After looking into a how the these filters work, there is certainly more work needed before zstandard (and NetCDF plugins for HDF5 in general) become usable with NetCDF_jll.
So far, in they do not compile on Windows (https://github.com/Unidata/netcdf-c/issues/2468) and on Mac it seems that some plugins have the `.so` extension while they should have the `.dylib`. Currently it is a mix of both on aarch64-apple-darwin:

```
$ ls .libs/lib__nc*dylib
.libs/lib__nch5bzip2.0.dylib    .libs/lib__nch5fletcher32.0.dylib  .libs/lib__nch5noop.0.dylib   .libs/lib__nch5shuffle.0.dylib  .libs/lib__nch5zstd.0.dylib
.libs/lib__nch5bzip2.dylib      .libs/lib__nch5fletcher32.dylib    .libs/lib__nch5noop1.0.dylib  .libs/lib__nch5shuffle.dylib    .libs/lib__nch5zstd.dylib
.libs/lib__nch5deflate.0.dylib  .libs/lib__nch5misc.0.dylib        .libs/lib__nch5noop1.dylib    .libs/lib__nch5unknown.0.dylib  .libs/lib__nczmisc.0.dylib
.libs/lib__nch5deflate.dylib    .libs/lib__nch5misc.dylib          .libs/lib__nch5noop.dylib     .libs/lib__nch5unknown.dylib    .libs/lib__nczmisc.dylib
$ ls .libs/lib__nc*so
.libs/lib__nczhdf5filters.so  .libs/lib__nczstdfilters.so
```

which leads to this error if `lib__nczhdf5filters` is declared as a `LibraryProduct`

```
[ Info: Could not locate lib__nczhdf5filters inside ["/mnt/data1/abarth/src/Yggdrasil/N/NetCDF/build/aarch64-apple-darwin/McixRJ5o/aarch64-apple-darwin20-libgfortran5-cxx11/destdir/lib64", "/mnt/data1/abarth/src/Yggdrasil/N/NetCDF/build/aarch64-apple-darwin/McixRJ5o/aarch64-apple-darwin20-libgfortran5-cxx11/destdir/lib"]
┌ Error: Built NetCDF but lib__nczhdf5filters still unsatisfied:
└ @ BinaryBuilder ~/.julia/packages/BinaryBuilder/wohhx/src/AutoBuild.jl:906
```

Once this is resolved, there is the question where to install the plugins so that HDF5 can find them. Here is a relevant discussion https://github.com/Unidata/netcdf-c/issues/2294 and there will probably some changed in the upcoming version 4.9.1.
The approach of using the environment variable `HDF5_PLUGIN_PATH` (or dropping file in the HDF5 installation directory) does not seem to be well suited to the way we install libraries in julia.

I think it would be good to track the integration of HDF5 plugins in a separate issue.

**Comment by mkitti** [comment]
Just to elaborate on the follwoing Unidata/netcdf comment from Unidata from the Julia perspective:

> It turns out that we are not building and installing the zstandard filter code itself. This is a small C program that we must compile and install on the users system, or else zstandard cannot work for them.

The HDF5 plugin they refer to is located here:
https://github.com/aparamon/HDF5Plugin-Zstandard
This is small piece of [`C code`](https://github.com/aparamon/HDF5Plugin-Zstandard/blob/master/zstd_h5plugin.c) that glues HDF5 and ZStandard together.

For Julia, rather than compiling this small piece of C code, we just translated it to Julia here:
https://github.com/JuliaIO/HDF5.jl/blob/master/filters/H5Zzstd/src/H5Zzstd.jl

Other translated filter plugins can be found here:
https://github.com/JuliaIO/HDF5.jl/blob/master/filters

Technically, we could package up the C plugin in BinaryBulider, but so far I have not seen a strong incentive to do so.

**Comment by Alexander-Barth** [comment]
Do you register these julia plugins with `H5Pset_filter` when `HDF5.jl` is loaded?

**Comment by Alexander-Barth** [comment]
I removed the Zstd_jll dependency because the support for Zstandard and plugins is not jet functional.

**Comment by visr** [comment]
Sounds good! So this is good to go, right? I see julia 1.8 got tagged, would be great to have a fully functional netcdf binary by the time it is announced :)

**Comment by mkitti** [comment]
> Do you register these julia plugins with `H5Pset_filter` when `HDF5.jl` is loaded?

The filters are registered via [`H5Zregister`](https://docs.hdfgroup.org/hdf5/develop/group___h5_z.html#title6):
https://github.com/JuliaIO/HDF5.jl/blob/e3252afec2dadecc5a6ba644924dae2922c4e5b0/src/filters/filters.jl#L233

via their `__init__`:
https://github.com/JuliaIO/HDF5.jl/blob/master/filters/H5Zzstd/src/H5Zzstd.jl#L122

If you want to use Zstd compression with HDF5.jl, then you just have to do:
```julia
using HDF5
using H5Zzstd
```

This is documented here:
https://juliaio.github.io/HDF5.jl/stable/filters/

[`H5Pset_filter`](https://portal.hdfgroup.org/display/HDF5/H5P_SET_FILTER) is used to add a filter to a dataset's filter pipeline. Via HDF5.jl this is usually done by passing a vector of `Filter`s to the `filters` keyword of [`create_dataset`](https://juliaio.github.io/HDF5.jl/stable/dataset/#HDF5.create_dataset).

If we're talking about filter ID 32015, then `using H5Zzstd` should work for you.

**Comment by mkitti** [comment]
One can confirm the availability of the filter via [`H5Zfilter_avail`](https://portal.hdfgroup.org/display/HDF5/H5Z_FILTER_AVAIL)
```
julia> using HDF5

julia> HDF5.API.h5z_filter_avail(32015)
false

julia> using H5Zzstd

julia> H5Z_FILTER_ZSTD
32015

julia> HDF5.API.h5z_filter_avail(32015)
true

julia> HDF5.API.h5z_filter_avail(H5Z_FILTER_ZSTD)
true

julia> HDF5.Filters.isavailable(ZstdFilter)
true

julia> HDF5.Filters.isavailable(H5Z_FILTER_ZSTD)
true
```

**Comment by Alexander-Barth** [comment]
Thank you for this detailed information! So there are good chances that this mechanism already works for NetCDF too. 
As @visr said, it would be good to have this release so that we have again a working NetCDF_jll for all major OSes.

**Comment by staticfloat** [comment]
So to be clear, the expectation here is that this will build a single version of NetCDF that can be loaded in Julia 1.6, 1.7 and 1.8.  I see the dependency on LibCURL is specifically set to the version in 1.6, I think there's a good chance this will work, so let's roll with it!

**Comment by maleadt** [comment]
Since yesterday, quite some packages have started to fail on Julia 1.9 segfaulting in libnetcdf during initialization, so I guess that may be related to this PR. See https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7144f7/report.html, e.g., https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7144f7/ArgoData.primary.log (for one of the shorter failed tests). This happens during precompilation, when NCDatasets.init_certificate_authority executes. It's possible this is related to the PkgEval sandbox, but regardless it shouldn't segfault like that.

**Comment by mkitti** [comment]
Julia 1.8 uses libcurl 7.84.0, which is the same version as Julia master (1.9) after https://github.com/JuliaLang/julia/pull/45967. ArgoData seems to pass the tests fine on my Julia 1.8 running on Windows.

```
Test Summary: | Pass  Total     Time
ArgoData.jl   |    6      6  2m23.7s
```

**Comment by mkitti** [comment]
The segmentation faults seem to be occurring on the call to `strdup`:
https://github.com/Unidata/netcdf-c/blob/717e022e80cc696ed2855b6e38d58b26ebedb8ba/libdispatch/drc.c#L168-L182

**Comment by mkitti** [comment]
ClimateModels fails after `nc_open`
https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/f7144f7/ClimateModels.primary.log

**Comment by Alexander-Barth** [comment]
I think all this is related to https://github.com/Unidata/netcdf-c/issues/2337. We are currently calling a private API to define the path of the certificate authority for HTTPS because the (new) public API produces a segfault. Now it seems that the private API segfaults too. I guess I will need to disable HTTPS until this upstream issue is resolved (at least under Julia 1.9).

**Comment by maleadt** [comment]
> I guess I will need to disable HTTPS in NCDatasets until this upstream issue is resolved (at least under Julia 1.9).

That would be great. Alternatively, if this is related to PkgEval's sandbox environment I could tweak that, as long as we get rid of the 30+ segfaulting packages on PkgEval :-)

**Comment by Alexander-Barth** [comment]
OK, I have released NCDatasets 0.12.7 which does not call `NCDatasets.init_certificate_authority` on julia 1.9. Surprisingly NCDatasets 0.12.6 works on Julia  1.9.0-DEV.1160 (nightly) in CI:

https://github.com/Alexander-Barth/NCDatasets.jl/runs/7931319355?check_suite_focus=true

and 1.9.0-DEV.1162 on my machine. I am wondering how I can reproduce this error locally. Does PkgEval also use nightly builds?

**Comment by maleadt** [comment]
> Does PkgEval also use nightly builds?

The way to test this is explained in the PkgEval README: https://github.com/JuliaCI/PkgEval.jl#why-does-my-package-fail

Interestingly however, it does not fail when using `julia=nightly` (which uses pre-built binaries from Julia CI), whereas it does when forcing PkgEval.jl to build Julia from scratch:

```julia
julia> using PkgEval

julia> config = Configuration(julia="master", buildflags=["JULIA_CPU_TARGET=native", "JULIA_PRECOMPILE=0"])

julia> PkgEval.sandboxed_julia(config)

# in the sandbox here

pkg> add NCDatasets@0.12.6

julia> using NCDatasets

# segfault
```

That's not great, because PkgEval source builds are supposed to be identical to the ones performed by CI... @staticfloat, any thoughts? The build script is here: https://github.com/JuliaCI/PkgEval.jl/blob/893b93e5723782653dc87aaec2e00b1b08b6cce5/src/julia.jl#L107-L186

**Comment by Alexander-Barth** [comment]
This issue https://github.com/Unidata/netcdf-c/issues/2486 might be relevant where a memory problem during initialization is observed (independently of julia).

**Comment by Alexander-Barth** [comment]
For the record: the C option `-std=c99` (used before) results that the function `strdup` is undefined (as it is not part of C99) and any operation on strings in NetCDF like using the home path leads in a crash.

**Comment by giordano** [comment]
`strdup` is defined conditionally:
```console
sandbox:${WORKSPACE} # grep -B3 -r '\*strdup' /opt/${target}/${target}/sys-root/usr/include/
/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/include/string.h-#if defined __USE_SVID || defined __USE_BSD || defined __USE_XOPEN_EXTENDED \
/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/include/string.h-    || defined __USE_XOPEN2K8
/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/include/string.h-/* Duplicate S, returning an identical malloc'd string.  */
/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/include/string.h:extern char *strdup (__const char *__s)
```
The `gnu99` standard defines some of those macros, thus enabling `strdup` to be defined, we had to deal with this yesterday in
https://github.com/JuliaPackaging/Yggdrasil/blob/95c449533c5c006e481de4dd3e0d803eaf95bc47/Z/ZipFlow/build_tarballs.jl#L11

**Pull request merged**
