### PR TITLE
[libcellml] Update to version 0.6.0

### PR DESCRIPTION
**Pull request by hsorby**

### CODE REVIEW

**Comment by fingolfin** [comment]
Build fails because new libxml2 unfortunately has a breaking change in the callback API. To fix it you need to apply a patch to `src/xmldoc.cpp`  in libcellml, changing `void structuredErrorCallback(void *userData, xmlErrorPtr error)` to `void structuredErrorCallback(void *userData, const xmlError *error)`

**Comment by hsorby** [comment]
Oh, great thanks.  I'll look into how this works with our other testing.

**Comment by hsorby** [comment]
Can I get some help in understanding why CMake cannot find `LibXml2` on `aarch64-unknown-freebsd` please.
Thank you.

**Comment by giordano** [comment]
> Can I get some help in understanding why CMake cannot find LibXml2 on aarch64-unknown-freebsd please.
> Thank you.

That's fixed now.  Is this good to go now?

**Comment by hsorby** [comment]
Sure.

I am still confused as to how setting the LibXml2 compat option fixed finding the LibXml2 library on that one platform.  Every other platform was able to find the LibXml2 libraries.  The compilation problem stemming from the change to the function arguments appears much later than finding LibXml2 so that issue wasn't in play.

**Comment by giordano** [comment]
> I am still confused as to how setting the LibXml2 compat option fixed finding the LibXml2 library on that one platform. Every other platform was able to find the LibXml2 libraries. The compilation problem stemming from the change to the function arguments appears much later than finding LibXml2 so that issue wasn't in play.

There were two separate issues:

* apparently there was a breaking change in xml2, I added a compat specification to make sure we only use a (hopefully) compatible version of xml2 together with libcellml
* aarch64-freebsd is a platform we introduced only recently, and many packages haven't been built for it yet, including xml2 until this morning I opened #9685 (and #9684 for a dependency of xml2 itself).  By upgrading to xml2 v2.3.14 we also got a build of the package for the new platform

**Comment by hsorby** [comment]
Great. Thanks for the explanation.

**Pull request merged**
