### PR TITLE
[LCIO_Julia_Wrapper] pinning dependency versions

### PR DESCRIPTION
**Pull request by jstrube**

### CODE REVIEW

**Comment by giordano** [comment]
I'm going to merge this, but check that the change is propagated to the registry in the PR that'll be opened by @jlbuild.  If not, you'll have to manually open a PR to fix it

**Comment by jstrube** [comment]
Thanks. Looks like it worked. The Project.toml of the new version has a strict version requirement.

**Comment by giordano** [comment]
I was talking about the registry: it doesn't matter what's written in the `Project.toml` of the package, it's the registry that rules.  Anyway, the compatibility bound has been added: https://github.com/JuliaRegistries/General/pull/17499/files

**Comment by jstrube** [comment]
Thanks for checking.

**Pull request merged**
