### PR TITLE
[QT] Add Qt5Tools

### PR DESCRIPTION
**Pull request by barche**
Tools like `qdoc` and `lrelease`. The latter is needed for Gnuplot.

### CODE REVIEW

**Comment by giordano** [comment]
Are these build tools that need to be run natively during the build?  If so, building for x86_64-linux-musl would help, if possible

**Comment by barche** [comment]
> Are these build tools that need to be run natively during the build? If so, building for x86_64-linux-musl would help, if possible

It's a mix, the tools marked as `ExecutableProduct` are built for the target, the other tools (`qdoc`, `lrelease` and a few others) are automatically compiled for musl regardless of the target. Building specifically for musl would require also building `Qt5Base_jll` for musl, I haven't tried that yet. So I would prefer to go ahead as-is, we can add musl when and if someone needs Qt for it.

**Comment by giordano** [comment]
> (qdoc, lrelease and a few others) are automatically compiled for musl regardless of the target.

Ok, that's probably enough then.

**Review by giordano — APPROVED** [review]

**Comment by barche** [comment]
OK, once this is merged I'll take a look at reviving PR #2252

**Pull request merged**
