### PR TITLE
CoolProp: new JLL wrapper, tweak platform lists

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by giordano** [comment]
Let me guess without looking at the URL: is this from SourceForge?

**Comment by fingolfin** [comment]
Yes, I am already working on putting an alternate download URL *sigh*

**Comment by fingolfin** [comment]
(downloading it from that SourceForge URL does work for me locally, though, using wget, which follows the various redirects just fine)

**Comment by giordano** [comment]
https://github.com/JuliaLang/Downloads.jl/issues/37

**Comment by fingolfin** [comment]
Ah OK. So this would be resolved by a new release of Downloads.jl?

**Comment by fingolfin** [comment]
Not sure how to proceed with this: SF.net download still were broken when I last tried this. I am not aware of mirrors of the sources. Ask the upstream to provide a mirror? (But what'd be their incentive?) Host a mirror ourselves somewhere? (But where? Just wait until the issue resolves itself one way or the other? Hmm...

Perhaps @barche (who submitted this JLL originally) has some insights on this?

**Comment by giordano** [comment]
> SF.net download still were broken when I last tried this.

We temporarily use `curl` now to download the sources

**Comment by fingolfin** [comment]
Yes it is on GitHub, but only the source code repository; they don't use it to distribute their release archives, unfortunately. Perhaps one could convince them to change that, though?

**Pull request merged**
