### PR TITLE
[ASL] build on experimental platforms

### PR DESCRIPTION
**Pull request by odow**
I assume I need to add a new `asl-extra` patch, but I'm not overly sure what it should be. 

The readme says:  https://github.com/ampl/asl/tree/master/src/solvers#readme

> For other systems, let the makefile compile and execute arithchk.c to create a suitable arith.h.

But I don't have an M1 to actually run the resulting binary.

@dpo how did you create the original files? (https://github.com/JuliaPackaging/Yggdrasil/pull/215)

### CODE REVIEW

**Comment by giordano** [comment]
> But I don't have an M1 to actually run the resulting binary.

I can help with that, if you tell me what to do

**Comment by odow** [comment]
I think it's sufficient to just run the build script. 

If you look here:
https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=14887&view=logs&j=9d0d0c39-4d29-59df-c871-a7772bacbdf9&t=f162a461-b137-5d51-9c67-0cb26e6022e4&l=319
it compiled `arithchk.c` then tried to run `./a.out > arith.h`.

So I assume you can just grab that `a.out` binary and run it locally?

**Comment by giordano** [comment]
Your guess was correct, the name was not 😉

**Comment by odow** [comment]
Haha I was like where did I go wrong???

**Pull request merged**
