### PR TITLE
ZeroMQ 4.0 for GR

### PR DESCRIPTION
**Pull request by ViralBShah**
We only build it as a static library to be linked in directly into GR.

### CODE REVIEW

**Comment by barche** [comment]
ZeroMQ is needed only to build GKSTerm I think, and that one is only used on mac. @jheinen can you confirm?

What isn't clear to me is if it's acceptable to use gksqt on Mac, that one works without ZeroMQ but it has less functionality (no menus for saving). See also my comment here:

https://github.com/jheinen/GR.jl/issues/314#issuecomment-727624313

**Comment by ViralBShah** [comment]
Except for Windows, we can get ZeroMQ 4.0 built on all platforms.

**Comment by giordano** [comment]
> Building a dynamic version of this will be bad, because it will prevent all other usage of a more recent ZeroMQ (used by Jupyter and such).

That's a good point, I'm very concerned about that.  But how does GR work now?  Does it link dynamically to ZeroMQ 4.0?

**Comment by ViralBShah** [comment]
The GR source builds zeromq statically - but it is known not to build statically with mingw32 (as also demonstrated here).

https://github.com/sciapp/gr/blob/b490cbfacc6f4dc08c2a2de52c6f6594e8c7c5f9/3rdparty/zeromq/Makefile#L37

**Comment by ViralBShah** [comment]
This version is several years old, and it just was never supported to build as as a static library on mingw32. This is why the configure script prevents you from trying. Bypassing that check leads to:

```
[22:38:07] In file included from fd.hpp:26,
[22:38:07]                  from signaler.hpp:27,
[22:38:07]                  from mailbox.hpp:26,
[22:38:07]                  from mailbox.cpp:20:
[22:38:07] windows.hpp:168:10: fatal error: Mstcpip.h: No such file or directory
```

**Comment by jheinen** [comment]
> ZeroMQ is needed only to build GKSTerm I think, and that one is only used on mac. @jheinen can you confirm?
> 
> What isn't clear to me is if it's acceptable to use gksqt on Mac, that one works without ZeroMQ but it has less functionality (no menus for saving). See also my comment here:
> 
> [jheinen/GR.jl#314 (comment)](https://github.com/jheinen/GR.jl/issues/314#issuecomment-727624313)

Yes. ZeroMQ is only used for the GKSTerm on macOS. We will eliminate ZMQ in a one of the next versions of GR.

**Comment by ViralBShah** [comment]
Great! I'll close this then, and only enable it in the GR build on apple.

**Comment by barche** [comment]
> Great! I'll close this then, and only enable it in the GR build on apple.

If I understand correctly we can actually already eliminate ZeroMQ for the GR build and use gksqt instead.

**Pull request closed without merging**
