### PR TITLE
Build SuiteSparse with Msan

### PR DESCRIPTION
**Pull request by gbaraldi**
Part of https://github.com/JuliaLang/julia/issues/46349 in order to enable Msan on CI

### CODE REVIEW

**Comment by giordano** [comment]
This is failing on the msan build

**Comment by gbaraldi** [comment]
Indeed it is. Not sure why. It seems like the failures when one doesn't link CompilerRT

**Comment by giordano** [comment]
There is something wrong here which I don't understand.  With this patch
```diff
diff --git a/SPQR/Lib/Makefile b/SPQR/Lib/Makefile
index 06c142ae..5c5f619c 100644
--- a/SPQR/Lib/Makefile
+++ b/SPQR/Lib/Makefile
@@ -93,7 +93,7 @@ ifneq ($(GPU_CONFIG),)
          -I../../GPUQREngine/Include $(CUDA_INC)
 endif
 
-C = $(CXX) $(CF) $(SPQR_CONFIG) $(CHOLMOD_CONFIG) $(CONFIG_PARTITION) $(I)
+C = $(CXX) $(CF) -v $(SPQR_CONFIG) $(CHOLMOD_CONFIG) $(CONFIG_PARTITION) $(I)
 
 ifneq ($(GPU_CONFIG),)
     LDLIBS += $(CUDART_LIB) $(CUBLAS_LIB) \
```
I see
```console
sandbox:${WORKSPACE}/srcdir/SuiteSparse # SUPER_VERBOSE=1 make -C SPQR "${FLAGS[@]}" library CFOPENMP="$CFOPENMP"
make: Entering directory '/workspace/srcdir/SuiteSparse/SPQR'
( cd Lib ; make --jobs=8 )
make[1]: Entering directory '/workspace/srcdir/SuiteSparse/SPQR/Lib'
make install INSTALL=/workspace/srcdir/SuiteSparse
make[2]: Entering directory '/workspace/srcdir/SuiteSparse/SPQR/Lib'
c++    -O3 -fexceptions -fPIC  -v -DSUN64 -DLONGBLAS='long long' -DSUN64 -DLONGBLAS='long long' -DNPARTITION -DNPARTITION -I../../CHOLMOD/Include -I../../SuiteSparse_config -I../Include -c ../Source/spqr_rmap.cpp
c++    -O3 -fexceptions -fPIC  -v -DSUN64 -DLONGBLAS='long long' -DSUN64 -DLONGBLAS='long long' -DNPARTITION -DNPARTITION -I../../CHOLMOD/Include -I../../SuiteSparse_config -I../Include -c ../Source/SuiteSparseQR_C.cpp
c++    -O3 -fexceptions -fPIC  -v -DSUN64 -DLONGBLAS='long long' -DSUN64 -DLONGBLAS='long long' -DNPARTITION -DNPARTITION -I../../CHOLMOD/Include -I../../SuiteSparse_config -I../Include -c ../Source/SuiteSparseQR_expert.cpp
c++    -O3 -fexceptions -fPIC  -v -DSUN64 -DLONGBLAS='long long' -DSUN64 -DLONGBLAS='long long' -DNPARTITION -DNPARTITION -I../../CHOLMOD/Include -I../../SuiteSparse_config -I../Include -c ../Source/spqr_kernel.cpp
c++    -O3 -fexceptions -fPIC  -v -DSUN64 -DLONGBLAS='long long' -DSUN64 -DLONGBLAS='long long' -DNPARTITION -DNPARTITION -I../../CHOLMOD/Include -I../../SuiteSparse_config -I../Include -c ../Source/spqr_analyze.cpp
c++    -O3 -fexceptions -fPIC  -v -DSUN64 -DLONGBLAS='long long' -DSUN64 -DLONGBLAS='long long' -DNPARTITION -DNPARTITION -I../../CHOLMOD/Include -I../../SuiteSparse_config -I../Include -c ../Source/spqr_assemble.cpp
c++    -O3 -fexceptions -fPIC  -v -DSUN64 -DLONGBLAS='long long' -DSUN64 -DLONGBLAS='long long' -DNPARTITION -DNPARTITION -I../../CHOLMOD/Include -I../../SuiteSparse_config -I../Include -c ../Source/spqr_cpack.cpp
c++    -O3 -fexceptions -fPIC  -v -DSUN64 -DLONGBLAS='long long' -DSUN64 -DLONGBLAS='long long' -DNPARTITION -DNPARTITION -I../../CHOLMOD/Include -I../../SuiteSparse_config -I../Include -c ../Source/spqr_csize.cpp
ccache /opt/x86_64-linux-musl/bin/clang++ -target x86_64-linux-gnu --sysroot=/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root --gcc-toolchain=/opt/x86_64-linux-gnu -march=x86-64 -mtune=generic -fsanitize=memory -O3 -fexceptions -fPIC -v -DSUN64 -DLONGBLAS=long long -DSUN64 -DLONGBLAS=long long -DNPARTITION -DNPARTITION -I../../CHOLMOD/Include -I../../SuiteSparse_config -I../Include -c ../Source/SuiteSparseQR_C.cpp
ccache /opt/x86_64-linux-musl/bin/clang++ -target x86_64-linux-gnu --sysroot=/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root --gcc-toolchain=/opt/x86_64-linux-gnu -march=x86-64 -mtune=generic -fsanitize=memory -O3 -fexceptions -fPIC -v -DSUN64 -DLONGBLAS=long long -DSUN64 -DLONGBLAS=long long -DNPARTITION -DNPARTITION -I../../CHOLMOD/Include -I../../SuiteSparse_config -I../Include -c ../Source/spqr_rmap.cpp
ccache /opt/x86_64-linux-musl/bin/clang++ -target x86_64-linux-gnu --sysroot=/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root --gcc-toolchain=/opt/x86_64-linux-gnu -march=x86-64 -mtune=generic -fsanitize=memory -O3 -fexceptions -fPIC -v -DSUN64 -DLONGBLAS=long long -DSUN64 -DLONGBLAS=long long -DNPARTITION -DNPARTITION -I../../CHOLMOD/Include -I../../SuiteSparse_config -I../Include -c ../Source/SuiteSparseQR_expert.cpp
ccache /opt/x86_64-linux-musl/bin/clang++ -target x86_64-linux-gnu --sysroot=/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root --gcc-toolchain=/opt/x86_64-linux-gnu -march=x86-64 -mtune=generic -fsanitize=memory -O3 -fexceptions -fPIC -v -DSUN64 -DLONGBLAS=long long -DSUN64 -DLONGBLAS=long long -DNPARTITION -DNPARTITION -I../../CHOLMOD/Include -I../../SuiteSparse_config -I../Include -c ../Source/spqr_kernel.cpp
ccache /opt/x86_64-linux-musl/bin/clang++ -target x86_64-linux-gnu --sysroot=/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root --gcc-toolchain=/opt/x86_64-linux-gnu -march=x86-64 -mtune=generic -fsanitize=memory -O3 -fexceptions -fPIC -v -DSUN64 -DLONGBLAS=long long -DSUN64 -DLONGBLAS=long long -DNPARTITION -DNPARTITION -I../../CHOLMOD/Include -I../../SuiteSparse_config -I../Include -c ../Source/spqr_analyze.cpp
ccache /opt/x86_64-linux-musl/bin/clang++ -target x86_64-linux-gnu --sysroot=/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root --gcc-toolchain=/opt/x86_64-linux-gnu -march=x86-64 -mtune=generic -fsanitize=memory -O3 -fexceptions -fPIC -v -DSUN64 -DLONGBLAS=long long -DSUN64 -DLONGBLAS=long long -DNPARTITION -DNPARTITION -I../../CHOLMOD/Include -I../../SuiteSparse_config -I../Include -c ../Source/spqr_assemble.cpp
ccache /opt/x86_64-linux-musl/bin/clang++ -target x86_64-linux-gnu --sysroot=/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root --gcc-toolchain=/opt/x86_64-linux-gnu -march=x86-64 -mtune=generic -fsanitize=memory -O3 -fexceptions -fPIC -v -DSUN64 -DLONGBLAS=long long -DSUN64 -DLONGBLAS=long long -DNPARTITION -DNPARTITION -I../../CHOLMOD/Include -I../../SuiteSparse_config -I../Include -c ../Source/spqr_cpack.cpp
ccache /opt/x86_64-linux-musl/bin/clang++ -target x86_64-linux-gnu --sysroot=/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root --gcc-toolchain=/opt/x86_64-linux-gnu -march=x86-64 -mtune=generic -fsanitize=memory -O3 -fexceptions -fPIC -v -DSUN64 -DLONGBLAS=long long -DSUN64 -DLONGBLAS=long long -DNPARTITION -DNPARTITION -I../../CHOLMOD/Include -I../../SuiteSparse_config -I../Include -c ../Source/spqr_csize.cpp
clang version 13.0.1 (/home/mose/.julia/dev/BinaryBuilderBase/deps/downloads/clones/llvm-project.git-1df819a03ecf6890e3787b27bfd4f160aeeeeacd50a98d003be8b0893f11a9be 75e33f71c2dae584b13a7d1186ae0a038ba98838)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/x86_64-linux-musl/bin
Found candidate GCC installation: /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0
Selected GCC installation: /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 (in-process)
 "/opt/x86_64-linux-musl/bin/clang-13" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj --mrelax-relocations -disable-free -disable-llvm-verifier -discard-value-names -main-file-name spqr_csize.cpp -mrelocation-model pic -pic-level 2 -fhalf-no-semantic-interposition -mframe-pointer=none -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -v -fcoverage-compilation-dir=/workspace/srcdir/SuiteSparse/SPQR/Lib -resource-dir /opt/x86_64-linux-musl/lib/clang/13.0.1 -D SUN64 -D "LONGBLAS=long long" -D SUN64 -D "LONGBLAS=long long" -D NPARTITION -D NPARTITION -I ../../CHOLMOD/Include -I ../../SuiteSparse_config -I ../Include -isysroot /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root -internal-isystem /opt/x86_64-linux-musl/bin/../include/c++/v1 -internal-isystem /opt/x86_64-linux-musl/lib/clang/13.0.1/include -internal-isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include -internal-isystem /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/include -internal-externc-isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/include -internal-externc-isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/include -O3 -fdeprecated-macro -fdebug-compilation-dir=/workspace/srcdir/SuiteSparse/SPQR/Lib -ferror-limit 19 -fsanitize=memory -fsanitize-memory-use-after-dtor -fno-assume-sane-operator-new -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -vectorize-loops -vectorize-slp -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o spqr_csize.o -x c++ ../Source/spqr_csize.cpp
clang -cc1 version 13.0.1 based upon LLVM 13.0.1 default target x86_64-linux-musl
ignoring nonexistent directory "/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/include"
#include "..." search starts here:
#include <...> search starts here:
 ../../CHOLMOD/Include
 ../../SuiteSparse_config
 ../Include
 /opt/x86_64-linux-musl/bin/../include/c++/v1
 /opt/x86_64-linux-musl/lib/clang/13.0.1/include
 /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include
 /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/include
 /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/include
End of search list.
In file included from ../Source/spqr_csize.cpp:5:
In file included from ../Include/spqr.hpp:22:
In file included from /opt/x86_64-linux-musl/bin/../include/c++/v1/complex:242:
In file included from /opt/x86_64-linux-musl/bin/../include/c++/v1/sstream:184:
In file included from /opt/x86_64-linux-musl/bin/../include/c++/v1/istream:163:
In file included from /opt/x86_64-linux-musl/bin/../include/c++/v1/ostream:138:
In file included from /opt/x86_64-linux-musl/bin/../include/c++/v1/ios:214:
In file included from /opt/x86_64-linux-musl/bin/../include/c++/v1/__locale:47:
/opt/x86_64-linux-musl/bin/../include/c++/v1/__support/musl/xlocale.h:27:25: error: static declaration of 'strtoll_l' follows non-static declaration
static inline long long strtoll_l(const char *nptr, char **endptr, int base,
                        ^
/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/include/stdlib.h:250:22: note: previous declaration is here
extern long long int strtoll_l (__const char *__restrict __nptr,
                     ^
[...]
```
The compiler invocation looks right, and also the output of `SUPER_VERBOSE` looks right, but then in the headers search path there is first `/opt/x86_64-linux-musl/bin/../include/c++/v1` and then the rest, but in the same session I also get
```console
sandbox:${WORKSPACE}/srcdir/SuiteSparse # echo 'int main(void){return 0;}' | clang -x c++ - -v
clang version 13.0.1 (/home/mose/.julia/dev/BinaryBuilderBase/deps/downloads/clones/llvm-project.git-1df819a03ecf6890e3787b27bfd4f160aeeeeacd50a98d003be8b0893f11a9be 75e33f71c2dae584b13a7d1186ae0a038ba98838)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/x86_64-linux-musl/bin
Found candidate GCC installation: /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0
Selected GCC installation: /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/opt/x86_64-linux-musl/bin/clang-13" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -v -fcoverage-compilation-dir=/workspace/srcdir/SuiteSparse -resource-dir /opt/x86_64-linux-musl/lib/clang/13.0.1 -isysroot /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root -internal-isystem /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/include/c++/6.1.0 -internal-isystem /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/include/c++/6.1.0/x86_64-linux-gnu -internal-isystem /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/include/c++/6.1.0/backward -internal-isystem /opt/x86_64-linux-musl/lib/clang/13.0.1/include -internal-isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include -internal-isystem /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/include -internal-externc-isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/include -internal-externc-isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/include -fdeprecated-macro -fdebug-compilation-dir=/workspace/srcdir/SuiteSparse -ferror-limit 19 -fsanitize=memory -fsanitize-memory-use-after-dtor -fno-assume-sane-operator-new -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/--2f6084.o -x c++ -
clang -cc1 version 13.0.1 based upon LLVM 13.0.1 default target x86_64-linux-musl
ignoring nonexistent directory "/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/include/c++/6.1.0
 /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/include/c++/6.1.0/x86_64-linux-gnu
 /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/include/c++/6.1.0/backward
 /opt/x86_64-linux-musl/lib/clang/13.0.1/include
 /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include
 /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/include
 /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/include
End of search list.
 "/opt/bin/x86_64-linux-gnu-libgfortran3-cxx11-sanitize+memory/ld.x86_64-linux-gnu" --sysroot=/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root -z now -z relro --hash-style=gnu --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o a.out /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/lib/../lib64/crt1.o /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/lib/../lib64/crti.o /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/crtbegin.o -L/opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0 -L/opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/lib/../lib64 -L/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/lib/../lib64 -L/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/lib/../lib64 -L/opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/lib -L/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/lib -L/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/lib --whole-archive /opt/x86_64-linux-musl/lib/clang/13.0.1/lib/linux/libclang_rt.msan-x86_64.a --no-whole-archive --dynamic-list=/opt/x86_64-linux-musl/lib/clang/13.0.1/lib/linux/libclang_rt.msan-x86_64.a.syms /tmp/--2f6084.o --no-as-needed -lpthread -lrt -lm -ldl -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/crtend.o /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/lib/../lib64/crtn.o
```
Which has completely different search paths for the header files, this time with the correct ones.  I don't know what can caus `clang` to be so confused about search paths.

**Comment by giordano** [comment]
Uhm, it's the `-c`:
```console
sandbox:${WORKSPACE}/srcdir/SuiteSparse # echo 'int foo(void){return 0;}' | clang -x c++ -c -v -
clang version 13.0.1 (/home/mose/.julia/dev/BinaryBuilderBase/deps/downloads/clones/llvm-project.git-1df819a03ecf6890e3787b27bfd4f160aeeeeacd50a98d003be8b0893f11a9be 75e33f71c2dae584b13a7d1186ae0a038ba98838)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/x86_64-linux-musl/bin
Found candidate GCC installation: /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0
Selected GCC installation: /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 (in-process)
 "/opt/x86_64-linux-musl/bin/clang-13" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -v -fcoverage-compilation-dir=/workspace/srcdir/SuiteSparse -resource-dir /opt/x86_64-linux-musl/lib/clang/13.0.1 -isysroot /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root -internal-isystem /opt/x86_64-linux-musl/bin/../include/c++/v1 -internal-isystem /opt/x86_64-linux-musl/lib/clang/13.0.1/include -internal-isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include -internal-isystem /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/include -internal-externc-isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/include -internal-externc-isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/include -fdeprecated-macro -fdebug-compilation-dir=/workspace/srcdir/SuiteSparse -ferror-limit 19 -fsanitize=memory -fsanitize-memory-use-after-dtor -fno-assume-sane-operator-new -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o -.o -x c++ -
clang -cc1 version 13.0.1 based upon LLVM 13.0.1 default target x86_64-linux-musl
ignoring nonexistent directory "/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/x86_64-linux-musl/bin/../include/c++/v1
 /opt/x86_64-linux-musl/lib/clang/13.0.1/include
 /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include
 /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/include
 /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/include
End of search list.
```
Sigh.

I'm wondering if https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/261 broke something?

**Comment by giordano** [comment]
Yes, I think `-stdlib=libstdc++` should have been kept, but only for `clang++`:
```console
sandbox:${WORKSPACE}/srcdir/SuiteSparse # echo 'int foo(void){return 0;}' | SUPER_VERBOSE=1 clang -x c++ -c -v - -stdlib=libstdc++
ccache /opt/x86_64-linux-musl/bin/clang -target x86_64-linux-gnu --sysroot=/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root --gcc-toolchain=/opt/x86_64-linux-gnu -march=x86-64 -mtune=generic -fsanitize=memory -x c++ -c -v - -stdlib=libstdc++
clang version 13.0.1 (/home/mose/.julia/dev/BinaryBuilderBase/deps/downloads/clones/llvm-project.git-1df819a03ecf6890e3787b27bfd4f160aeeeeacd50a98d003be8b0893f11a9be 75e33f71c2dae584b13a7d1186ae0a038ba98838)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/x86_64-linux-musl/bin
Found candidate GCC installation: /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0
Selected GCC installation: /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
 (in-process)
 "/opt/x86_64-linux-musl/bin/clang-13" -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model static -mframe-pointer=all -fmath-errno -fno-rounding-math -mconstructor-aliases -munwind-tables -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -v -fcoverage-compilation-dir=/workspace/srcdir/SuiteSparse -resource-dir /opt/x86_64-linux-musl/lib/clang/13.0.1 -isysroot /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root -internal-isystem /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/include/c++/6.1.0 -internal-isystem /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/include/c++/6.1.0/x86_64-linux-gnu -internal-isystem /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/include/c++/6.1.0/backward -internal-isystem /opt/x86_64-linux-musl/lib/clang/13.0.1/include -internal-isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include -internal-isystem /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/include -internal-externc-isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/include -internal-externc-isystem /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/include -fdeprecated-macro -fdebug-compilation-dir=/workspace/srcdir/SuiteSparse -ferror-limit 19 -fsanitize=memory -fsanitize-memory-use-after-dtor -fno-assume-sane-operator-new -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o -.o -x c++ -
clang -cc1 version 13.0.1 based upon LLVM 13.0.1 default target x86_64-linux-musl
ignoring nonexistent directory "/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/include/c++/6.1.0
 /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/include/c++/6.1.0/x86_64-linux-gnu
 /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/include/c++/6.1.0/backward
 /opt/x86_64-linux-musl/lib/clang/13.0.1/include
 /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/include
 /opt/x86_64-linux-gnu/lib/gcc/x86_64-linux-gnu/6.1.0/../../../../x86_64-linux-gnu/include
 /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/include
End of search list.
```

**Pull request merged**
