### PR TITLE
Add LERC compression to libtiff

### PR DESCRIPTION
**Pull request by evetion**
@Crghilardi added LERC to Yggdrasil 👍🏻. Ping to @visr because of #4537 which can be closed if this works.

### CODE REVIEW

**Comment by giordano** [comment]
Yeah, you may want to rebuild LERC_jll before this one

**Comment by evetion** [comment]
@giordano Could you restart the CI here? I'd expect it will pick up LERC v3.0.0+1 automatically now, we don't want to pin that here.

**Comment by giordano** [comment]
Not before https://github.com/JuliaRegistries/General/pull/55890 is merged.  Also, we can't just restart CI, you have to make a dummy edit to the file to actually retrigger the build, if nothing changes we reuse the cache from the previous build.

**Comment by evetion** [comment]
Ok, will do so.

**Pull request merged**
