### PR TITLE
Updated HOHQMesh to v1.2.1

### PR DESCRIPTION
**Pull request by andrewwinters5000**
cc @sloede

### CODE REVIEW

**Comment by giordano** [comment]
Only successful platforms are:

* `x86_64-linux-gnu-libgfortran4`
* `aarch64-linux-gnu-libgfortran4`
* `powerpc64le-linux-gnu-libgfortran4`
* `armv6l-linux-gnu-libgfortran3`

This is one of the most meaningless sets of successful platforms I've ever seen, I can't see any sensible pattern here (apart from they all glibc).

**Comment by giordano** [comment]
If I restart failed jobs, I get some more successful platforms.  I suspect the build system doesn't handle parallelisation correctly, by which I mean some dependencies may have not been specified correctly in the make rules.

**Comment by andrewwinters5000** [comment]
Okay, I will work on building it locally are suss out what is wrong

**Comment by andrewwinters5000** [comment]
I have a fix but it requires an upstream patch to HOHQMesh first.

**Comment by giordano** [comment]
You can also patch the source code here.  If you look for `atomic_patch` in this repository you'll find plenty of examples, alternatively if you can post the patch here I can update it later today.

**Comment by giordano** [comment]
Much better now :slightly_smiling_face:  Thanks!

**Pull request merged**
