### PR TITLE
[Elemental] Update to 1.5.1

### PR DESCRIPTION
**Pull request by ViralBShah**

### CODE REVIEW

**Comment by giordano** [comment]
Do you want to require julia v1.6?

**Comment by ViralBShah** [comment]
cc @andreasnoack

**Comment by ViralBShah** [comment]
@JBlaschke This is our Elemental build recipe. Perhaps you may know how to fix the build.

https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=11741&view=logs&j=bdc19914-4824-529b-e606-c39779d9c0ef&t=ca989bc1-9e4f-55b3-32df-8eaed39b717f

**Comment by ViralBShah** [comment]
@giordano Do you know what might be happening here, and do you have any experience with Elemental? 

Here's the spack package. 
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/hydrogen/package.py

@andreasnoack I wonder if we should leave the old Elemental build as is and create this as Hydrogen_jll.

**Comment by giordano** [comment]
Judging by the error message I think we need to rename all needed blas/lapack symbols for ILP64, see for example [`30f7d98` (#3162)](https://github.com/JuliaPackaging/Yggdrasil/pull/3162/commits/30f7d9868c964e3d058b12340a9b0d9e3991b12f).

This is particularly annoying because with OpenBLAS 0.3.10 (julia v1.6) aarch64 doesn't do ILP64, but with OpenBLAS 0.3.13 (julia v1.7) it does.  This means we can't have a binary which targets Julia v1.6- _and_ v1.7+ at the same time.

**Comment by ViralBShah** [comment]
I am fine with just targeting 1.7 and upwards. We can also just depend on a 32-bit BLAS rather than doing the ILP64 dance for now.

**Comment by giordano** [comment]
> We can also just depend on a 32-bit BLAS rather than doing the ILP64 dance for now.

That would solve lots of issues :smile:

**Comment by ViralBShah** [comment]
Also depending on 1.7+ would mean that we can unconditionally just depend on LBT, which can deal with all of this much better. In fact post 1.7, we should upgrade anything that depends on OpenBLAS or OpenBLAS32 to depend on LBT instead.

**Comment by giordano** [comment]
One problem I found with linking to libblastrampoline is that LBT has all the 32- and 64-bit symbols, so linking will always work, but maybe some symbols need to be renamed for ILP64 and you'll find that out only at runtime, which isn't great.

**Comment by ViralBShah** [comment]
I thought that was a good thing. So we tell Elemental that we have a 32-bit BLAS and it will find the symbols in LBT, and it will just work out, right? We just have to make sure that ILP64 always has the 64_ suffixes. Isn't it just a problem for BB builders (like in this PR), and not a user problem? The users will always get a correctly built setup, unless I am missing something.

**Pull request closed without merging**
