### PR TITLE
[DebianGlibc] Bump to v2.38-6

### PR DESCRIPTION
**Pull request by staticfloat**
X-ref: https://github.com/rr-debugger/rr/pull/3693#issuecomment-1951457222

### CODE REVIEW

**Comment by Keno** [comment]
Folder needs renaming or duplication.

**Comment by DilumAluthge** [comment]
Any idea why CI is failing?

**Comment by DilumAluthge** [comment]
Thank you @staticfloat and @Keno!!!

**Comment by DilumAluthge** [comment]
Cross-ref: https://github.com/JuliaRegistries/General/pull/101198

**Pull request merged**
