### PR TITLE
upgrade to GLFW 3.3.3

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by giordano** [comment]
Need to update the hash :slightly_smiling_face:

**Comment by SimonDanisch** [comment]
Ugh... of the zip right? Maybe we should switch this to a github resource...

**Comment by giordano** [comment]
> Maybe we should switch this to a github resource...

You still need to update the hash, just a different one :stuck_out_tongue:

**Comment by SimonDanisch** [comment]
>You still need to update the hash, just a different one 😛

Yeah but that one is easier to find - for me at least :D

**Pull request merged**
