### PR TITLE
Add CImGui Builder

### PR DESCRIPTION
**Pull request by Gnimuc**
Is this the correct way to add an old non-wizard builder?

### CODE REVIEW

**Comment by giordano** [comment]
Yes, this is the way. However, I'd prefer moving the content of CImGuiBuilder here and depending on the local directory, instead of relying on yet another external repository

**Comment by Gnimuc** [comment]
Those two files in the wrapper folder are not patches and may be removed in the future, so I guess it's fine to use an external repo for now.

**Comment by giordano** [comment]
> Those two files in the wrapper folder are not patches and may be removed in the future

So what? Also [SuiteSparse](https://github.com/JuliaPackaging/Yggdrasil/tree/50ed5cb4446d2cf688665bb9320c640c23a7d6cd/S/SuiteSparse%405) for example has the code for the wrapper here

**Comment by Gnimuc** [comment]
Thanks for the link. I thought only patches are allowed in the bundle folder.

**Comment by giordano** [comment]
I slightly simplified the build script, set `CMAKE_BUILD_TYPE=Release`, and installed the license files.

**Comment by Gnimuc** [comment]
Thanks for helping on this!

**Pull request merged**
