### PR TITLE
[bowtie] add build recipe for the original Bowtie program

### PR DESCRIPTION
**Pull request by M-PERSIC**
[Bowtie](https://github.com/BenLangmead/bowtie.git) v1.3.1

### CODE REVIEW

**Comment by M-PERSIC** [comment]
Fiddle-sticks, do not merge yet!

**Comment by M-PERSIC** [comment]
All good!

**Comment by M-PERSIC** [comment]
The directory is capitalized whilst I named the package all lowercase. Change the directory name in this commit or make a separate one?

**Comment by giordano** [comment]
Let's do it here?

**Comment by giordano** [comment]
There's a conflict now.

**Comment by M-PERSIC** [comment]
I will make a new pull request, apologies, it will be easier.

**Pull request closed without merging**
