### PR TITLE
[XGBoost] update to v1.4.2

### PR DESCRIPTION
**Pull request by clouds56**

### CODE REVIEW

**Comment by giordano** [comment]
Can we require Julia v1.6?

**Comment by clouds56** [comment]
What do you mean by require v1.6?
New here and I just bump version and doesn't see anything in `build_tarballs.jl` related to julia version

**Comment by giordano** [comment]
> What do you mean by require v1.6?

When merging the pull request we'll generate a so called [JLL package](https://docs.binarybuilder.org/stable/jll/).  By default they're compatible with Julia v1.3+, but if you're ok with making it compatible only for Julia v1.6+ we can build the library for more platforms

**Comment by clouds56** [comment]
I see where you are coming from. But I just don't know how to implement it.

**Comment by clouds56** [comment]
Of course I am :)

**Pull request merged**
