### PR TITLE
[Tesseract] Add builder

### LINKED ISSUE #118: Looking for Leptonica and Tesseract binaries under JuliaBinaryWrappers
Binary builder needed for Tesseract OCR and Leptonica Image Processing Library

https://github.com/tesseract-ocr/tesseract
http://www.leptonica.org/source/leptonica-1.78.0.tar.gz

Tesseract utilizes Leptonica internally. It's best both are built together.

### PR DESCRIPTION
**Pull request by giordano**
Close #118

### CODE REVIEW

**Comment by giordano** [comment]
`x86_64-linux-gnu` is failing on Azure pipelines with
```
[ Info: /workspace/T/Tesseract/build/x86_64-linux-gnu/zfh0sFWe/destdir/lib/libtesseract.so matches our search criteria of libtesseract
[ Info: /workspace/T/Tesseract/build/x86_64-linux-gnu/zfh0sFWe/destdir/lib/libtesseract.so cannot be dlopen'ed
[...]
[ Info: Could not locate libtesseract inside ["/workspace/T/Tesseract/build/x86_64-linux-gnu/zfh0sFWe/destdir/lib64", "/workspace/T/Tesseract/build/x86_64-linux-gnu/zfh0sFWe/destdir/lib"]
┌ Error: Built Tesseract but libtesseract still unsatisfied:
└ @ BinaryBuilder ~/.julia/dev/BinaryBuilder/src/AutoBuild.jl:710
```
but it's passing locally :confused:

**Comment by giordano** [comment]
In the debug build I got:
```
[23:07:18]  ---> ldd ${libdir}/libtesseract.so
[23:07:18] 	linux-vdso.so.1 (0x00007ffc1ddcc000)
[23:07:18] 	liblept.so.5 => /workspace/destdir/lib/liblept.so.5 (0x00007f789f149000)
[23:07:18] 	libpng16.so.16 => /workspace/destdir/lib/libpng16.so.16 (0x00007f789ef02000)
[23:07:18] 	libjpeg.so.62 => /workspace/destdir/lib/libjpeg.so.62 (0x00007f789ec71000)
[23:07:18] 	libtiff.so.5 => /workspace/destdir/lib/libtiff.so.5 (0x00007f789ea0d000)
[23:07:18] 	libwebp.so.7 => /workspace/destdir/lib/libwebp.so.7 (0x00007f789e74d000)
[23:07:18] 	libz.so.1 => /workspace/destdir/lib/libz.so.1 (0x00007f789e530000)
[23:07:18] 	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f789e312000)
[23:07:18] 	libstdc++.so.6 => /opt/x86_64-linux-gnu/bin/../lib/gcc/x86_64-linux-gnu/4.8.5/../../../../x86_64-linux-gnu/lib/../lib64/libstdc++.so.6 (0x00007f789e010000)
[23:07:18] 	libm.so.6 => /lib64/libm.so.6 (0x00007f789dd00000)
[23:07:18] 	libc.so.6 => /lib64/libc.so.6 (0x00007f789d966000)
[23:07:18] 	libgcc_s.so.1 => /opt/x86_64-linux-gnu/bin/../lib/gcc/x86_64-linux-gnu/4.8.5/../../../../x86_64-linux-gnu/lib/../lib64/libgcc_s.so.1 (0x00007f789d750000)
[23:07:18] 	libgomp.so.1 => /opt/x86_64-linux-gnu/bin/../lib/gcc/x86_64-linux-gnu/4.8.5/../../../../x86_64-linux-gnu/lib/../lib64/libgomp.so.1 (0x00007f789d542000)
[23:07:18] 	ldd (0x00007f789fb64000)
[23:07:18] 	librt.so.1 => /lib64/librt.so.1 (0x00007f789d33a000)
```
I'm quite clueless about why it can't be `dlopen`ed

**Comment by staticfloat** [comment]
Are you using a `cxx11` or `cxx03` build of Julia?  I think it's only trying to `dlopen()` if the cxxstring abi matches.

**Comment by giordano** [comment]
I have C++11 string ABI.

Note here I used expand_cxxstring_abis because the library is in C++, but audit didn't complain without it

**Comment by staticfloat** [comment]
Do you have problems if you build the `cxx03` version locally?

**Comment by giordano** [comment]
No:
image

**Pull request merged**
