### PR TITLE
[ERFA] Update to v2.0.0

### PR DESCRIPTION
**Pull request by helgee**

### CODE REVIEW

**Comment by giordano** [comment]
Are you OK to require Julia v1.6 and build for extra platforms like aarch64-apple-darwin (also known as Apple Silicon)?

**Comment by helgee** [comment]
Sure! To the future...

**Comment by giordano** [comment]
Also, we can probably disable building the static archive and further reduce the size of the tarball.  Does it sound good?

**Comment by helgee** [comment]
Make it so

**Pull request merged**
