### PR TITLE
[SCIP] SCIP 9.2.0

### PR DESCRIPTION
**Pull request by matbesancon**

### CODE REVIEW

**Review by giordano — COMMENTED** [review]
Unrelated to the failure, this should simplify the code a little bit :slightly_smiling_face:

**Comment by ViralBShah** [comment]
I suppose we need to build IPOpt for FreeBSD aarch64

**Comment by matbesancon** [comment]
yes but it's surprising it was not failing before?

**Comment by eschnett** [comment]
FreeBSD aarch64 didn't exist until a short while ago.

**Comment by amontoison** [comment]
I can recompile Ipopt quite soon; I have already recompiled some dependencies like METIS, but this build still requires an old version of Ipopt compiled with OpenBLAS instead of LBT.  
@matbesancon probably doesn't want to upgrade it, so the easiest solution is to avoid compiling SCIP on FreeBSD aarch64.

**Comment by matbesancon** [comment]
thanks all! I'm finally getting back to this

**Comment by matbesancon** [comment]
good to go on my side!

**Pull request merged**
