### PR TITLE
add libspatialite

### PR DESCRIPTION
**Pull request by Crghilardi**
add a `build_tarballs.jl` for [spatialite](https://www.gaia-gis.it/fossil/libspatialite/index).

### CODE REVIEW

**Comment by giordano** [comment]
[PowerPC and FreeBSD failing because the shared libraries weren't built, uh?](https://docs.binarybuilder.org/stable/troubleshooting/#PowerPC-Linux)

Their `configure` script:
```sh
#! /bin/sh
# Guess values for system-dependent variables and create Makefiles.
# Generated by GNU Autoconf 2.69 for libspatialite 5.0.1.
#
# Report bugs to <a.furieri@lqt.it>.
#
#
# Copyright (C) 1992-1996, 1998-2012 Free Software Foundation, Inc.
```
Note the year range, sigh.

**Comment by Crghilardi** [comment]
I probably went into this one a little too confident, it was working on x86_64-linux-musl locally and that is usually my smell test if everything will blow up... :laughing: 

windows is doing the same thing where it only build `.a`/ static files with the patch applied.

This is the first project I have seen using [Fossil](https://www.gaia-gis.it/fossil/libspatialite/dir?ci=tip) as source control. Kinda fun?

**Comment by giordano** [comment]
And macOS is failing because they managed to get autoconf to use the wrong extension (`.so` instead `.dylib`).  This is probably one of the first times I see something like this, I don't know how to do that

**Comment by giordano** [comment]
Windows is building only the static library because there are undefined symbols....
https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=13116&view=logs&j=5dd1de24-2b75-5d82-626d-8989f61d0cf7&t=09bbb86c-0238-5b03-c042-813fe0c7f88f&l=10169
```
[00:39:21] libtool: link: warning: undefined symbols not allowed in x86_64-w64-mingw32 shared libraries
```

**Comment by Crghilardi** [comment]
Are you supposed to `autoreconf -vi` before or after `update_configure_scripts`?

**Comment by giordano** [comment]
It shouldn't matter, the helper scripts are usually called only by configure

**Comment by Crghilardi** [comment]
Adding an `autoreconf` fixed a handful of platforms up. 

`mingw` is still strange. I checked the `Makefile.am` and the `-no-undefined` flag [seems to be there already?](https://www.gaia-gis.it/fossil/libspatialite/file?ci=tip&name=src%2FMakefile.am&ln=51) but grepping for -no-undefined shows a few different files I am still working through. 
I did try the `LDFLAGS` trick mentioned in the [Troubleshooting](https://docs.binarybuilder.org/stable/troubleshooting/#Libtool-refuses-to-build-shared-library-because-of-undefined-symbols) section with no success

**Comment by giordano** [comment]
> I did try the LDFLAGS trick mentioned in the Troubleshooting section with no success

No, that doesn't help here: it looks like the linker is already finding undefined symbols.  I don't know what symbols are missing, but my bet is that they're not linking all necessary libraries

**Comment by Crghilardi** [comment]
`mingw` finishes compiling now, but it still gives me a `.a` file in `${bindir}` for some reason. I'm not sure what else to try at this point to make `autotools` happy?

**Comment by giordano** [comment]
My understanding is that these tests in `configure.ac`
```m4
# Checking for MinGW
AM_CONDITIONAL([MINGW], [test "$target_alias" = "mingw32"])
# Checking for Mac OsX
AM_CONDITIONAL([MACOSX], [test "$target_alias" = "macosx"])
# Checking for Android
AM_CONDITIONAL([ANDROID], [test "$target_alias" = "android"])
```
are all wrong.  I'm looking into this.

**Pull request merged**
