### PR TITLE
[libsingular_julia] New version for julia 1.6

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by thofma** [comment]
I don't understand this. The builds for <= 1.5 were passing but now it complaints about versions. I guess `libpolymake_julia` will run into the same problem @benlorenz.

**Comment by thofma** [comment]
I cannot reproduce this locally. Doing
```
julia --project=.ci/ L/libsingular_julia/libsingular_julia@1.6/build_tarballs.jl --debug --verbose --deploy=local x86_64-linux-gnu
```
with julia 1.6.0 works normally.

**Comment by benlorenz** [comment]
`libpolymake_julia` does not run into this, I think because this has an explicit platform list instead of using `libjulia_platforms`. After the latest refactoring libjulia adds a [Julia version tag to the platform](https://github.com/JuliaPackaging/Yggdrasil/blob/13a719ea9ac96ead91d806b1ca43c81616d9b661/L/libjulia/common.jl#L21) which conflicts with the explicit mpfr version. We might be able to drop that explicit mpfr version restriction when the version is fixed anyway via the platform and we do not need to load binaries built for old libjulia versions in newer julia anymore. (But this might require some further experiments before deploying this....)

**Comment by thofma** [comment]
I see. I will try dropping the version restriction and see what happens.

**Comment by fingolfin** [comment]
Won't dropping the version restriction on MPFR lead to issues as we had before: namely a binary built against a version of MPFR newer than the version used in libjulia, and then resulting binary unusable (at least on macOS) ?

**Comment by benlorenz** [comment]
The error indicates that the platform tag does restrict the MPFR version as well.
Also we do have one version per Julia, so the runtime version should match the build version.

**Comment by thofma** [comment]
@benlorenz We are discussing this on slack. You are happy to join the discussion.

**Comment by benlorenz** [comment]
Not really, currently on holiday and on the playground right now.

**Comment by thofma** [comment]
Enjoy your holiday.

**Comment by thofma** [comment]
This is good to go.

**Pull request merged**
