### PR TITLE
yaml_cpp: Updated to v0.8.0

### PR DESCRIPTION
**Pull request by stemann**
Follow-up for #7591 and #7599.

### CODE REVIEW

**Comment by stemann** [comment]
Tests verified manually.

**Comment by giordano** [comment]
I can't merge this PR because github thinks this is still a draft
image

**Comment by giordano** [comment]
No, still a draft according to GitHub UI.  Can you please try to push again, or something?

**Comment by stemann** [comment]
Right, I had forgotten to rebase it onto a commit after #7599 on master - done now.

**Pull request merged**
