### PR TITLE
Add plugin dir

### PR DESCRIPTION
**Pull request by bramtayl**
No idea at all if this will work or not

### CODE REVIEW

**Comment by bramtayl** [comment]
I'm seeing

```
control.c: In function ‘snd_ctl_open_conf’:
[22:10:21] control.c:1336:39: warning: unknown escape sequence: '\$' [enabled by default]
[22:10:21]     buf1 = malloc(strlen(str) + sizeof(ALSA_PLUGIN_DIR) + 32);
[22:10:21]                                        ^
[22:10:21] control.c:1342:51: warning: unknown escape sequence: '\$' [enabled by default]
[22:10:21]     sprintf(buf1, "%s/libasound_module_ctl_%s.so", ALSA_PLUGIN_DIR, str);
```

**Comment by bramtayl** [comment]
@giordano sorry to bother you, is it possible to get an assist here? I'm pretty sure this won't work (I think ORIGIN is a cmake thing, not 100% sure) but this issue looks relevant https://github.com/alsa-project/alsa-lib/issues/82 and there's a comment that

> The latest alsa-lib looks to the relative directory where the libasound.so is located: <libasound.so.dir>/alsa-lib/<plugin.so>

which makes me think that the default will work fine?

**Comment by giordano** [comment]
Care to explain what you want to achieve exactly?

**Comment by bramtayl** [comment]
To get alsa to load the PulseAudio plugin if both alsa_plugins_jll and alsa_jll are installed. Does that help, or is there more info needed?

**Comment by giordano** [comment]
Ok, let me reword the question: what is `$ORIGIN` in `-with-plugindir='\$ORIGIN/alsa-lib'` supposed to achieve?  Where it should point to?  Why not using the real path instead?

**Comment by bramtayl** [comment]
I think the issue is that the plugindir will be looked up at run-time. So something like `$prefix/lib/alsa-lib` would stop working as soon as the library is moved to a different folder.

**Comment by giordano** [comment]
Ok, so we can't do that.  From the issue you linked above it looks like there is an environment variable to be used, so just set the environment variable at call site?

**Comment by bramtayl** [comment]
Sure...but where is the call site? A julia user would be calling code in the PortAudio.jl package, which is loading `libportaudio_jll`, which is loading `alsa_jll` and `alsa_plugins_jll`...

**Comment by giordano** [comment]
Whatever actually calls into the library, so not any JLL package but `PortAudio.jl`

**Comment by bramtayl** [comment]
Ok, sorry I'm still being dense. So I would a line to the PortAudio.jl package like

`ENV["ALSA_PLUGIN_DIR"] = {prefix/lib/alsa-lib folder for alsa_plugins_jll}

**Comment by giordano** [comment]
My recommendation would be to have something like
```julia
withenv("ALSA_PLUGIN_DIR" => joinpath(alsa_plugins_jll.artifact_dir, "lib", "alsa-lib") do
    ccall(...)
end
```
whenever you call into the library.  It isn't great to set an environment variable globally though (which is something that you could do also with the [`init_block`](https://docs.binarybuilder.org/stable/reference/#BinaryBuilder.build_tarballs) keyword argument)

**Pull request closed without merging**
