### PR TITLE
[BiCePS] add initial builder

### PR DESCRIPTION
**Pull request by odow**
Extracted from https://github.com/JuliaPackaging/Yggdrasil/pull/3139

### CODE REVIEW

**Comment by odow** [comment]
@giordano I guess there is some delay on the build servers updating the registry? I get this
image
but it works locally.

**Comment by giordano** [comment]
I thought it was a delay in PkgServer for which we can't do much apart from waiting, but this is taking a bit too long, and also locally I can install `ALPS_jll` with PkgServer, so I'm not entirely sure what's going on.

**Comment by odow** [comment]
Yeah I have no idea. 

The status page is green
https://status.julialang.org
but if you dig in, there's a lot of red:
image

**Comment by staticfloat** [comment]
It looks like this is not a packageserver issue, but might instead be an Yggdrasil issue.

**Comment by odow** [comment]
I don't know what it was. But it seemed to resolve itself. Thanks all.

**Pull request merged**
