### PR TITLE
Add libLLVM 6.0.1 for use in libjulia 1.3.1

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
OK, I got
> ERROR: LoadError: You must lock an extracted LLVM build to a particular LLVM_full build number!
and it is clear how to proceed. However, part of the issue was that the existing LLVM_jll 6.0.1 wasn't usable on PowerPC (see https://github.com/JuliaPackaging/Yggdrasil/pull/1795#issuecomment-710742359) so I assume I'd first have to rebuild the full LLVM_jll for 6.0.1.

**Comment by giordano** [comment]
@vchuravy any clue about the failure for macOS:
```
[15:55:28] ninja: job failed: /opt/bin/clang --target=x86_64-apple-darwin14 --sysroot=/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root -DKERNEL_USE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Iprojects/compiler-rt/lib/builtins -I/workspace/srcdir/llvm-project/compiler-rt/lib/builtins -Iinclude -I/workspace/srcdir/llvm-project/llvm/include -O3 -DNDEBUG -arch x86_64    -isysroot /opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root -mmacosx-version-min=10.5 -fPIC -O3 -fvisibility=hidden -DVISIBILITY_HIDDEN -Wall -fomit-frame-pointer -arch x86_64 -mkernel -MD -MT projects/compiler-rt/lib/builtins/CMakeFiles/clang_rt.cc_kext_x86_64_osx.dir/atomic.c.o -MF projects/compiler-rt/lib/builtins/CMakeFiles/clang_rt.cc_kext_x86_64_osx.dir/atomic.c.o.d -o projects/compiler-rt/lib/builtins/CMakeFiles/clang_rt.cc_kext_x86_64_osx.dir/atomic.c.o   -c /workspace/srcdir/llvm-project/compiler-rt/lib/builtins/atomic.c
[15:55:28] /workspace/srcdir/llvm-project/compiler-rt/lib/builtins/atomic.c:257:1: error: atomic load requires runtime support that is not available for this target
[15:55:28] OPTIMISED_CASES
[15:55:28] ^
[15:55:28] /workspace/srcdir/llvm-project/compiler-rt/lib/builtins/atomic.c:238:3: note: expanded from macro 'OPTIMISED_CASES'
[15:55:28]   OPTIMISED_CASE(16, IS_LOCK_FREE_16, __uint128_t)
[15:55:28]   ^
[15:55:28] /workspace/srcdir/llvm-project/compiler-rt/lib/builtins/atomic.c:250:12: note: expanded from macro 'OPTIMISED_CASE'
[15:55:28]     return __c11_atomic_load((_Atomic(type)*)src, model);\
[15:55:28]            ^
[15:55:28] /workspace/srcdir/llvm-project/compiler-rt/lib/builtins/atomic.c:272:1: error: atomic store requires runtime support that is not available for this target
[15:55:28] OPTIMISED_CASES
[15:55:28] ^
[15:55:28] /workspace/srcdir/llvm-project/compiler-rt/lib/builtins/atomic.c:238:3: note: expanded from macro 'OPTIMISED_CASES'
[15:55:28]   OPTIMISED_CASE(16, IS_LOCK_FREE_16, __uint128_t)
[15:55:28]   ^
[15:55:28] /workspace/srcdir/llvm-project/compiler-rt/lib/builtins/atomic.c:263:5: note: expanded from macro 'OPTIMISED_CASE'
[15:55:28]     __c11_atomic_store((_Atomic(type)*)dest, val, model);\
[15:55:28]     ^
[15:55:28] 2 errors generated.
[15:55:28] ninja: subcommands failed
[15:55:28]  ---> ninja -j${nproc} -vv
[15:55:28] Previous command exited with 1
[15:55:28] Child Process exited, exit code 1
```
?

**Comment by vchuravy** [comment]
We tend to use `LLVM_full` for the builds, no? `libLLVM` is a future addition.

**Comment by fingolfin** [comment]
Yes, I realized that after I made this PR and read the errors, which is why I then opened PR #1915 to deal with LLVM_full :-). Once (if?) that is merged, this PR here could be updated. Of course if you prefer, we can also close it and I'll resubmit once (if) PR #1915 is done.

**Pull request closed without merging**
