### PR TITLE
[SSGrB] Bump version

### PR DESCRIPTION
**Pull request by Wimmerer**
perf improvements

### CODE REVIEW

**Comment by Wimmerer** [comment]
Addition of `cpu_features` to GraphBLAS is killing cross-compilation.

**Comment by giordano** [comment]
The audit finds cpuid instructions in the library, what's the point of doing compile-time features-detection if you're going to use cpuid anyway?

**Comment by Wimmerer** [comment]
A double guard I think to be extra special careful, not completely sure.

I'll guinea pig multi-microarch in return for pointers :P

**Comment by giordano** [comment]
For the record, the features-detection program should be built for the host platform, not the target one. Now, all sensible build systems allow specifying both the host _and_ the target toolchain (autoconf, meson, etc...), but of course cmake is a total pile of 💩 and as far as I know it doesn't let you do that. You could work around that by configuring first with the host toolchain, build the program, then reconfigure with the target toolchain and do the rest. Of course when cross-compiling it doesn't make any sense to do features-detection on the build machine, since that won't be the machine where the code will eventually run, we even target different architectures

**Comment by Wimmerer** [comment]
Ok so probably the correct solution is to make upstream drop cmake :D, or put the compile time feature detection behind a flag?

**Comment by giordano** [comment]
> Ok so probably the correct solution is to make upstream drop cmake :D

As much as I don't like cmake, that wouldn't solve the actual issue: compile-time features-detection doesn't make sense when you build a library to be run on a different machine with different microarchitecture or even architecture. The solution is to not do that at all

**Comment by Wimmerer** [comment]
@DrTimothyAldenDavis cc. Probably better to interface here directly.

**Comment by DrTimothyAldenDavis** [comment]
I must know the architecture of the target machine.  If the target is x86_64, I can AVX2 or AVX512 vectorization to generate code that is 2x to 4x faster.  So the solution "don't do that at all" will slow me down by 4x.  That's not a solution.

The solution is for the cross-compilation to set __x64_64__ properly, according to the target architecture and not the host architecture.  Then I can use that accordingly.

I don't actually have hard-coded AVX instructions in my code.  Instead, I use the vector extensions of C: https://gcc.gnu.org/onlinedocs/gcc/Vector-Extensions.html which are also supported by clang and all Intel compilers.  I detect at compile time if I have a compiler that supports those extensions, and use them if they do (and don't use them if they don't).

**Comment by giordano** [comment]
> I must know the architecture of the target machine. If the target is x86_64, I can AVX2 or AVX512 vectorization to generate code that is 2x to 4x faster. So the solution "don't do that at all" will slow me down by 4x. That's not a solution.

As I said multiple times, it doesn't make any sense to query the capabilities of the build machine if that's different from the machines where the code will run, as it happens here, or in almost all Linux distributions.

We actually have the ability to target multiple microarchitectures, for x86_64 these include the generic microarchitecture, AVX, AVX2 and AVX512. But again, the build system shouldn't query the capabilites of the build machine, I'm not even sure this has AVX512, still we can build for it.

**Comment by DrTimothyAldenDavis** [comment]
Yes, I understand what you're saying.  What I'm saying is the same thing:  I must query the architecture of the target machine where the library will finally run.  I do not want to or need to query the architecture of the host machine that is building the code via cross compilation for another (target) machine.

**Comment by Wimmerer** [comment]
I'm going to look at providing the target flags directly to SS:GrB, although I will probably need to make a PR upstream in the process to make them optional build flags, @giordano is the microarch stuff documented yet? If not this could be a guinea pig.

**Comment by giordano** [comment]
There isn't much documentation besides the [`expand_microarchitectures`](https://docs.binarybuilder.org/stable/reference/#BinaryBuilderBase.expand_microarchitectures-Tuple{AbstractPlatform}) methods.  For each microarchitecture we set the appropriate `-march`/`-mtune` flags, then you have to convince the build system to trust the compiler capability: we can't possibly document this step, it totally depends on the build system, and this stuff is usually totally custom.

**Comment by Wimmerer** [comment]
Ok I think this should be good now? I'm not 100% sure the flags being used are set correctly, but I don't have a machine to test those on.

**Comment by Wimmerer** [comment]
Also @mose what is lost by targeting a later GCC, like GCC 9? The new vectorization stuff in this lib is restricted to GCC 9.

**Comment by Wimmerer** [comment]
@giordano bump (mis-ping on the previous comment)

**Comment by giordano** [comment]
> Also @giordano what is lost by targeting a later GCC, like GCC 9? The new vectorization stuff in this lib is restricted to GCC 9.

For pure C code there isn't usually much difference in terms of compatibility, since we have a fixed C library for each given architecture.  The problem is more for C++ code, since the compatible C++ runtime depends on the compiler version we use.

For C code there is still a minor issue related to the fact that we bundle different binutils versions with different GCC versions: this means that compiling libA with version X of GCC/binutils may force libB, which depends on libA, to be compiled/linked with GCC/binutils version Y, with Y >= X, if the linker does use some features incompatible with previous versions (which may or may not happen, it's unpredictable)

**Comment by Wimmerer** [comment]
Ok, I don't think any of that should be an issue for me, there's no downstream C libraries at the moment. Can we merge this?

**Comment by giordano** [comment]
The license is missing

**Pull request merged**
