### PR TITLE
Add Luna, software for sleep signal analysis

### PR DESCRIPTION
**Pull request by ararslan**
I have a feeling this is going to be painful.

### CODE REVIEW

**Comment by ararslan** [comment]
Trying to decide whether I care about getting Windows to work...

**Comment by ararslan** [comment]
So the issue on Windows seems to be that the archives can't find some FFTW symbols:
```
[18:20:55] c++ -L/workspace/destdir/lib -L/workspace/destdir/bin -fPIC -o luna main.o globals.o eval.o cmddefs.o -L. -lspindles -llwprep -lannot -ldefs -lartifacts -ledf -ledfz -lhelper -ltimeline -lstaging -ldsp -lfftwrap -lmtm -lmiscmath -lintervals -ltinyxml -lcwt -lclocs -lpdc -lstats -lgraphics -ldb -lsstore -lica -lsrate -lfftw3 -lz
[18:20:55] building libluna.so...
[18:20:56] libartifacts.a(artifacts.o):artifacts.cpp:(.text+0x1e02): undefined reference to `fftw_destroy_plan'
[18:20:56] libartifacts.a(artifacts.o):artifacts.cpp:(.text+0x1e10): undefined reference to `fftw_free'
[18:20:56] libartifacts.a(artifacts.o):artifacts.cpp:(.text+0x1e1e): undefined reference to `fftw_free'
```

**Comment by giordano** [comment]
The command that is actually executed is 
```
ccache /opt/x86_64-w64-mingw32/bin/x86_64-w64-mingw32-g++ -D_GLIBCXX_USE_CXX11_ABI=1 -frandom-seed=0x344e3a13 -shared -L/workspace/destdir/lib -L/workspace/destdir/bin -fPIC -o libluna.so eval.o cmddefs.o globals.o -Wl,--whole-archive libannot.a libartifacts.a libclocs.a libcwt.a libdb.a libdefs.a libdsp.a libedf.a libedfz.a libfftwrap.a libgraphics.a libhelper.a libica.a libintervals.a liblwprep.a libmiscmath.a libmtm.a libpdc.a libspindles.a libsrate.a libsstore.a libstaging.a libstats.a libtimeline.a libtinyxml.a -Wl,--no-whole-archive
```
No surprise that it can't find any symbol...

**Comment by ararslan** [comment]
🎉

**Pull request merged**
