### PR TITLE
[HiGHS] update to v1.7.1

### PR DESCRIPTION
**Pull request by odow**

### CODE REVIEW

**Comment by imciner2** [comment]
You'll need to update the dependencies in the shared library script. https://github.com/JuliaPackaging/Yggdrasil/pull/8409 only added CMake to the static library dependencies but also removed it from the common build script, so it needs adding explicitly to the shared library now.

**Comment by odow** [comment]
For now I've just dropped the `apk del cmake` line if we're building the shared libs. Is that okay?

**Comment by imciner2** [comment]
I would have thought adding the dependency was going to be easier - and it also gets you a more recent CMake version ;)

**Comment by odow** [comment]
Okay, updated to use CMake_jll

**Pull request merged**
