### PR TITLE
[Clingo] Update to v5.7.1

### PR DESCRIPTION
**Pull request by ReubenJ**
Some targets in CI were failing in #8758. I am trying again and troubleshooting here.

### CODE REVIEW

**Comment by ReubenJ** [comment]
All errors are in the form

https://buildkite.com/julialang/yggdrasil/builds/12077#0190e920-a916-439e-a855-a5667a0b9def/670-1049

```shell
[09:03:39] In file included from /workspace/srcdir/clingo/libgringo/gringo/output/literals.hh:36:0,
[09:03:39]                  from /workspace/srcdir/clingo/libgringo/gringo/output/statements.hh:29,
[09:03:39]                  from /workspace/srcdir/clingo/libgringo/gringo/output/output.hh:31,
[09:03:39]                  from /workspace/srcdir/clingo/libgringo/gringo/ground/instantiation.hh:28,
[09:03:39]                  from /workspace/srcdir/clingo/libgringo/src/ground/instantiation.cc:25:
[09:03:39] /workspace/srcdir/clingo/libgringo/gringo/output/theory.hh: In member function ‘size_t Gringo::Output::TheoryData::AtomHash::operator()(const Id_t&) const’:
[09:03:39] /workspace/srcdir/clingo/libgringo/gringo/output/theory.hh:230:88: error: converting to ‘const std::tuple<unsigned int, Potassco::Span<unsigned int>, unsigned int, unsigned int>’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {unsigned int, Potassco::Span<unsigned int>, const unsigned int&, const unsigned int&}; <template-parameter-2-2> = void; _Elements = {unsigned int, Potassco::Span<unsigned int>, unsigned int, unsigned int}]’
[09:03:39]                  ? operator()({atom.term(), atom.elements(), *atom.guard(), *atom.rhs()})
[09:03:39]                                                                                         ^
[09:03:39] /workspace/srcdir/clingo/libgringo/gringo/output/theory.hh:231:60: error: converting to ‘const std::tuple<unsigned int, Potassco::Span<unsigned int> >’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = unsigned int; _U2 = Potassco::Span<unsigned int>; <template-parameter-2-3> = void; _T1 = unsigned int; _T2 = Potassco::Span<unsigned int>]’
[09:03:39]                  : operator()({atom.term(), atom.elements()});
[09:03:39]                                                             ^
[09:03:39] make[2]: *** [libgringo/CMakeFiles/libgringo.dir/build.make:132: libgringo/CMakeFiles/libgringo.dir/src/ground/instantiation.cc.o] Error 1
```

**Comment by giordano** [comment]
You probably need a newer version of GCC, find the first one which supports the needed feature.  They claim to require C++11, and GCC 5 should in principle be sufficient for that, but who knows, maybe they're wrong.

**Comment by ReubenJ** [comment]
Thanks for the suggestion! That is the case.

Out of curiosity, I tried building some versions locally using `x86_64-linux-gnu-cxx11-julia_version+1.10.4` locally, and [v5.5.2 of clingo](https://github.com/potassco/clingo/releases/tag/v5.5.2) builds successfully but [v5.6.0](https://github.com/potassco/clingo/releases/tag/v5.6.0) fails with the same error messages as v5.7.1 is giving.

Building with `preferred_gcc_version="6.1.0"` worked locally with `x86_64-linux-gnu-cxx11-julia_version+1.10.4`. I've updated my changes, I'm assuming some other builds might still fail.

**Comment by ReubenJ** [comment]
Not sure why this last build is hanging, but everything passed [before I marked the PR as ready for review](https://buildkite.com/julialang/yggdrasil/builds/12215). @giordano I think this should be ready

**Pull request merged**
