### PR TITLE
Recompile MUMPS with SCALAPACK32 and OpenBLAS32

### PR DESCRIPTION
**Pull request by amontoison**
@dpo

### CODE REVIEW

**Comment by dpo** [comment]
were you able to test this locally?

**Comment by amontoison** [comment]
> were you able to test this locally?

Yes and the tests passed !!!

**Comment by dpo** [comment]
Maybe the formula should be renamed MUMPS32_jll...

**Comment by amontoison** [comment]
`MUMPS_seq_jll` is build with `OpenBLAS32` too.

**Pull request merged**
