### PR TITLE
Add builder for Zstd

### PR DESCRIPTION
**Pull request by ararslan**
Based on https://github.com/bicycle1885/ZstdBuilder, cc @bicycle1885. Updated to the newest version of zstd.

### CODE REVIEW

**Comment by staticfloat** [comment]
https://github.com/JuliaPackaging/Yggdrasil/releases/tag/Zstd-v1.4.2%2B0

**Comment by bicycle1885** [comment]
Cool. Is it recommended to use this repository and its binaries instead of maintaining my own?

**Comment by ararslan** [comment]
Yes, I believe so. The general goal of Yggdrasil as I understand it is to be a central source of binaries. The benefit of having it in a monorepo is that all builders can be updated at once to reflect the newest advances in BinaryBuilder.

**Comment by staticfloat** [comment]
I would like to encourage everyone to contribute to one giant repo of build recipes for the following reasons:

* Initial setup for new users will be much simpler; just open a PR to a repository that already has CI and deployment and all that setup
* It will run on JuliaComputing machines, which means that builds will go _much_ faster than they would on Travis (hot ccache's, BB already installed, etc...)
* It solves the discoverability problem (Is there already a builder for LibFoo?  How do I find that?)
* Updating dependent builders is much easier (There's a new major version of libz, let's check to make sure that all the packages that depend on libz still build)

**Comment by bicycle1885** [comment]
Thank you for clarification. That sounds a good idea, so I'm trying to move my XML2 builder here. #22 is the pull request. Perhaps I should move ZlibBuilder, too?

**Comment by staticfloat** [comment]
Yes, I think moving `ZlibBuilder` would be fine.

**Comment by bicycle1885** [comment]
OK, I will do.

By the way, I have a question about binary files that depend on other binaries. I received [this issue report](https://github.com/bicycle1885/EzXML.jl/issues/102) a while ago, and I think this is caused by lacking zlib libraries in our libxml2's distributions. I supposed the dynamic libraries of libxml2 were shipped or statically linked with zlib because zlib is included in the builder script as a dependency (https://github.com/JuliaPackaging/Yggdrasil/blob/d95ce5d890154edac451c622e4b8831b522a68f8/XML2/build_tarballs.jl). What would be the best way to make sure that libxml2 has access to our zlib?

**Comment by staticfloat** [comment]
This will be fixed soon (I am demoing the next generation of Pkg+BinaryProvider in the Pkg call today, if you're interested to see it) but for the moment, you need to run the `build.jl` for `libz` first, and then run the `build.jl` for `libxml2` next.  So that will download the `libz` libraries first, then download the `libxml2` binaries just afterward, installing them both into your `EzXML` prefix.

**Comment by bicycle1885** [comment]
That's good to know. I'll wait for it since the issue is not so urgent to me.

**Pull request merged**
