### PR TITLE
[Clp] Build with mumps_seq 4 and metis 4

### PR DESCRIPTION
**Pull request by ViralBShah**

### CODE REVIEW

**Comment by ViralBShah** [comment]
Once the new METIS_jll package is registered when https://github.com/JuliaRegistries/General/pull/13067 is merged, we should be able to retry this one.

**Comment by ViralBShah** [comment]
The libraries for metis 4 and mumps_seq 4 are static - all `.a` files in `${prefix}/lib`. I wonder why Windows is unable to link against mumps. Here's the log:

https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=3093&view=logs&j=7069e3ca-39c8-542b-a995-adadec480557&t=8d5d8655-71d0-5d9a-2846-55b233763aa6

**Comment by ViralBShah** [comment]
@odow Can you try this Clp build once it is in General? (Perhaps in a couple of hours). It will be interesting to see if this is faster on sparse problems, and as good as earlier builds. We should now be on full feature parity.

**Comment by odow** [comment]
Will do.

**Comment by ViralBShah** [comment]
It's merged in General now.

**Comment by odow** [comment]
You work fast around here! Thanks for all your help. I'll try now.

**Comment by ViralBShah** [comment]
Haha - the queue is not too busy now. I was surprised the jobs got through that quickly.

**Comment by ViralBShah** [comment]
@giordano I tried to bump Cbc, which built fine, but failed the CI in General. 

https://github.com/JuliaRegistries/General/pull/13140/checks?check_run_id=594070246#step:5:268

Cbc depends on Clp (which we expanded fortran versions on). Does that mean that anything else that depends on Clp should also expand fortran versions? I didn't get any warnings in the Cbc build itself:

https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=3115&view=results

**Comment by giordano** [comment]
> Cbc depends on Clp (which we expanded fortran versions on). Does that mean that anything else that depends on Clp should also expand fortran versions?

Not necessarily, only if Cbc itself links to libgfortran.  But if Cbc depends on Clp, it's better to rebuild it after Clp, if the latter received substantial changes, like what we did here

**Comment by ViralBShah** [comment]
I did rebuild it after merging Clp into General (directly on master) and verified it was picking it up.

**Comment by ViralBShah** [comment]
Cbc probably does link to lapack itself, so perhaps it does need its own libgfortran expansion even though the audit doesn't complain.

**Comment by ViralBShah** [comment]
Cbc itself does not need to link to mumps - since it gets the benefits through Clp. I removed any Cbc modifications in this PR as a result.

**Comment by giordano** [comment]
But the error is about a C++ function:
```
% c++filt _ZTv0_n720_NK21OsiClpSolverInterface10getRowNameEij
virtual thunk to OsiClpSolverInterface::getRowName(int, unsigned int) const
```

**Comment by ViralBShah** [comment]
Shouldn't this be a compile time error?

**Comment by giordano** [comment]
So, the `libOsiClp.so` in the new version of `Clp_jll` has this symbol instead:
```
% c++filt _ZTv0_n720_NK21OsiClpSolverInterface10getRowNameB5cxx11Eij
virtual thunk to OsiClpSolverInterface::getRowName[abi:cxx11](int, unsigned int) const
```
Why rebuilding Cbc didn't catch up the new symbol isn't immediately clear to me

**Pull request merged**
