### PR TITLE
[NetCDF] Expand platforms for NetCDF.

### PR DESCRIPTION
**Pull request by evetion**
So #5383 can use NetCDF on Windows. Might be a long shot, or a misunderstanding of mine.

### CODE REVIEW

**Comment by evetion** [comment]
That was easier than I thought 😅

**Comment by giordano** [comment]
I'm missing the point of this PR. Also, please do not add commits (like merges) which don't change the content of the directory: they're useless and only make it harder for me to find the log

**Comment by evetion** [comment]
Over at #5383, many of the builds https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=21939&view=results warn about ```
##[warning]Dependency NetCDF_jll does not have a mapping for artifact NetCDF for platform x86_64-w64-mingw32-libgfortran4-cxx11
```

I assume this PR could fix that.

**Comment by giordano** [comment]
I don't think so

**Comment by giordano** [comment]
The log shows that [`v400.802.102+0`](https://github.com/JuliaBinaryWrappers/NetCDF_jll.jl/releases/tag/NetCDF-v400.802.102+0) was used, which simply does _not_ have Windows build.  C++ string ABI has nothing to do with this.

**Pull request closed without merging**
