### PR TITLE
[NCCL] v2.18.5

### PR DESCRIPTION
**Pull request by tylerjthomas9**
[Release notes](https://developer.nvidia.com/nccl/nccl-download)

From my understanding, @maleadt or someone else must upload the private NCCL binaries to the Yggdrasil servers. The page to get to the NCCL download links is available [here](https://developer.nvidia.com/nccl).

The goal of bumping NCCL is to add multi gpu training to XGBoost.jl. I have a working NCCL+XGBoost_jll build with CUDA v11 [here](https://github.com/tylerjthomas9/Yggdrasil/blob/xgboost%2Bnccl/X/XGBoost/build_tarballs.jl).

### CODE REVIEW

**Comment by maleadt** [comment]
IIUC, looking at Nix, we could build NCCL from https://github.com/NVIDIA/nccl
The reason to try this, is that I'm moving away from uploading private binaries. With all other CUDA binaries, we can use the `redist` sources, but the NCCL binaries aren't part of that.

**Comment by findmyway** [comment]
I'm wondering what else is required to get this newer version released?

> With all other CUDA binaries, we can use the redist sources, but the NCCL binaries aren't part of that.

Given that, is it fine to manually upload it for the time?

**Comment by maleadt** [comment]
> Given that, is it fine to manually upload it for the time?

I'll do it one last time. I've uploaded the following sources:

```
nccl_2.18.5-1+cuda11.0_aarch64.txz: 2b7ba3a646fdcac66544e99b39cb1720c7b6eaa74a89f753413dcbb450bd4c36
nccl_2.18.5-1+cuda11.0_ppc64le.txz: 70d5156fa8908182d88be9dd0007b4f8fb6bc92509846b7c2579179f6fbe3595
nccl_2.18.5-1+cuda11.0_x86_64.txz: 9e8db61e16db0ed937bd116471ad4963f83d3dab588f9b8fb499a869a3fbe374
nccl_2.18.5-1+cuda12.0_aarch64.txz: aa7b11bbbadb011b155b447dabcc8ee1b521f1ff34a39ef27e766ebe36f28c05
nccl_2.18.5-1+cuda12.0_ppc64le.txz: 32fc6734ed3306b5ad956f503704d186cfcdd8ca21cb0466f9fe5c512f9c799c
nccl_2.18.5-1+cuda12.0_x86_64.txz: d3add341537dbf737352c603fdb2098beccde2c127d77cd8d2d99af8852cef47
nccl_2.18.5-1+cuda12.2_aarch64.txz: 452d6a9511c4b4fe5ceb537f31d53b4f5c95608c743116d493119dfe83307ed2
nccl_2.18.5-1+cuda12.2_ppc64le.txz: c5584c80f0744897e602237947fb31fada2741ec34c872b61ad36f96606b47db
nccl_2.18.5-1+cuda12.2_x86_64.txz: e8f181ad8acc9a46290cf76d9fc4a635a97c5b7c025cd0d1b49cedb71a3fc968
```

**Comment by tylerjthomas9** [comment]
> I'll do it one last time. I've uploaded the following sources:

Thank you for doing this. I have been playing with building nccl, but I am hitting some errors with the builds. I will keep pushing on that front for future builds.

**Comment by maleadt** [comment]
Looks like it's just the hashes that are wrong; you can use what I posted above.

**Comment by tylerjthomas9** [comment]
I have the hashes you posted (and they match the ones I calculated). I [tried](https://github.com/JuliaPackaging/Yggdrasil/pull/7491/commits/9014ea22f0068a1f1bf3eb2620256d7892cabfa2) to switch to the hashes that Buildkite was seeing, but they changed again when the next build happened, so it was likely using the error that you get when you try to download the sources without a valid session.

**Comment by maleadt** [comment]
You're using the wrong filenames, `nccl_2.18.5-1+12.2_x86_64.txz` instead of `nccl_2.18.5-1+cuda12.2_x86_64.txz`.

**Pull request merged**
