### PR TITLE
CUDNN: Rebuild v8.2.4 - to use CUDA_Runtime

### PR DESCRIPTION
**Pull request by stemann**
This should cause a rebuild of CUDNN v8.2.4 - to be based on CUDA_Runtime rather than CUDA_loader

### CODE REVIEW

**Comment by stemann** [comment]
All the file checksums fail for CUDNN from from https://developer.nvidia.com/compute/machine-learning/cudnn/secure, e.g., https://developer.nvidia.com/compute/machine-learning/cudnn/secure/8.2.4/11.4_20210831/cudnn-11.4-linux-x64-v8.2.4.15.tgz

@maleadt Any idea why?

**Comment by maleadt** [comment]
That's because these "secure.nvidia.com" downloads require a log-in, so they can't be automated. I've manually downloaded the following tarballs and put them in place (for the download mechanism to pick them up without actually accessing "secure.nvidia.com"):

```
cudnn-10.2-linux-x64-v8.2.4.15.tgz: d23c94a3115a1c77116a6c127d9175fbf59f723364374f26a34699075f3222f1
cudnn-10.2-windows10-x64-v8.2.4.15.zip: a13eb10cfd7e6b7b8f39d8593038855b911012c29f03990878622bdae873c4a8
cudnn-11.4-linux-aarch64sbsa-v8.2.4.15.tgz: 48b11f19e9cd3414ec3c6c357ad228aebbd43282aae372d42cab2af67c32a08b
cudnn-11.4-linux-ppc64le-v8.2.4.15.tgz: af8749ca83fd6bba117c8bee31b787b7f204946e864294030ee0091eb7d3577e
cudnn-11.4-linux-x64-v8.2.4.15.tgz: 0e5d2df890b9967efa6619da421310d97323565a79f05a1a8cb9b7165baad0d7
cudnn-11.4-windows-x64-v8.2.4.15.zip: f01594639de35c380b4e360673ccaf04cdb238578e4b284935ee3d5a45f51f3c
libcudnn8-dev_8.2.4.15-1+cuda10.2_arm64.deb: 4816575e8a14baf3fc1619cb01c6dc2afd4f1b39210079d271208088ecc48702
libcudnn8_8.2.4.15-1+cuda10.2_arm64.deb: 3f08dbe14c3becb9fa1ed85cd4a080efb30edb0c4beb2fc1a2e14da3f2eefb79
```

Note that I don't want to be doing this anymore, hence the switch to the redist server which we can download from without authentication.

**Comment by stemann** [comment]
Ah - right.

I know - I will keep these old-version rebuilds to a minimum.

**Comment by stemann** [comment]
LGTM :-)

**Pull request merged**
