### PR TITLE
[RootFS]: Allow setting `--deploy=local` to skip GitHub upload

### PR DESCRIPTION
**Pull request by Keno**
But still add the new Artifact to the local Artifacts.toml.

### CODE REVIEW

**Comment by staticfloat** [comment]
Could we instead have these scripts deal with `--deploy` more like the rest of BB?  E.g. have it recognize `--deploy=local` vs. `--deploy`.  It could just not look for `GITHUB_TOKEN` at all in that case, and in the event that no `GITHUB_TOKEN` is set, it can use `BinaryBuilder.Wizard.github_auth(;allow_anonymous=false)` to get one.

**Comment by Keno** [comment]
`--deploy=local` sounds good to me. Is there some more general BB arg parsing code you'd want to re-use or just hardcode that into these scripts?

**Comment by staticfloat** [comment]
Nah, let's just hardcode it.  We don't need the ability to upload things to arbitrary github orgs.

**Comment by Keno** [comment]
See if you like this better.

**Comment by staticfloat** [comment]
Confirmed working, so merging!

**Pull request merged**
