### PR TITLE
bump hsa roct

### PR DESCRIPTION
**Pull request by Moelf**

### CODE REVIEW

**Comment by jpsamaroo** [comment]
@Moelf do you plan to update this PR, or do you want me to take over?

**Comment by Moelf** [comment]
feel free to take over

**Comment by giordano** [comment]
In the meantime I'm catching up with the hints Julian left before :sweat_smile:   If they aren't enough, please take it over if you can :pray:

**Comment by giordano** [comment]
Well, it look like `-DBUILD_SHARED_LIBS=ON` and `libdrm_jll` did the trick!  Sorry for not getting back to this before :disappointed:

**Pull request merged**
