### PR TITLE
MPFI: rebuild for new platforms

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
It seems the upstream file server is gone. I still have copies of various MPFI tarballs, which I could upload somewhere, but this is dissatisfying. I will email the upstream authors.

**Comment by fingolfin** [comment]
Unfortunately I received no reply by the upstream author. Hrm.

I guess I could use the Debian mirror of the source: <https://deb.debian.org/debian/pool/main/m/mpfi/mpfi_1.5.3+ds.orig.tar.xz>. Alas, they only have 1.5.3 not 1.5.4. Indeed, the MPFI website never announced 1.5.4 (or 1.5.3 for that matter). And I also only have tarballs up to 1.5.3, but not for 1.5.4. (There is https://gitlab.inria.fr/mpfi/mpfi which has a tag for 1.5.4, but no ready for release tarball).

If anyone has a copy of this tarball somewhere...

**Comment by benlorenz** [comment]
It does exist on the gentoo distfiles mirrors, e.g. http://mirror.eu.oneandone.net/linux/distributions/gentoo/gentoo/distfiles/3a/mpfi-1.5.4.tgz

There is also this git-repo https://github.com/arpra-project/mpfi/releases/tag/1.5.4 with some version of 1.5.4 but not the original tarball.

**Comment by fingolfin** [comment]
> It does exist on the gentoo distfiles mirrors, e.g. http://mirror.eu.oneandone.net/linux/distributions/gentoo/gentoo/distfiles/3a/mpfi-1.5.4.tgz

Perfect, I'll use that
 
> There is also this git-repo https://github.com/arpra-project/mpfi/releases/tag/1.5.4 with some version of 1.5.4 but not the original tarball.

Yes, I am aware, but as you said, it doesn't actually contain the tarballs :-(.

**Comment by giordano** [comment]
Uhm, in order to change julia compat you must change the version number: #2763

**Comment by fingolfin** [comment]
Indeed, done now (and with a comment). Since MPFI development appears to be dead, it's probably "safe" anyway (as in: a real 1.5.5 is unlikely. But of course even if it happens, we'll deal)

**Pull request merged**
