### PR TITLE
[Geant4_julia] New wrappers (avoiding closures)

### PR DESCRIPTION
**Pull request by peremato**

### CODE REVIEW

**Comment by peremato** [comment]
> Note that I just merged `libcxxwrap-julia` version 0.10. If this gets rebuilt, make sure to use v0.9.7 if your project uses CxxWrap 0.13, or if you build against libcxxwrap 0.10 switch your project to the soon-to-be-released CxxWrap 0.14. In all cases, it is best to add a compat entry to the libcxxwrap dependency

Thanks. I'll leave it as it is, since this will force me to update the dependency of my `Geant4.jl` package to CxxWrap 0.14.
In any case, I cannot do final tests and release `Geant4.jl` until this gets merged, and three is little activity so far.

**Comment by peremato** [comment]
@barche Thanks for merging. But before the binary wrappers were deployed automatically at https://github.com/JuliaBinaryWrappers and registered to the general registry. This does to seem to be the case now. Is there anything to be done?

**Comment by barche** [comment]
Ah, I see what happened now, I should not have merged this, there were a lot of build failures when looking at the buildkite. Can you try reopening a PR to trigger a rebuild?

**Comment by peremato** [comment]
Thanks. I'll do. I have  a question concernant the compatibility with libcxxwrap-julia, when the new version of CxxWrap will be released?

**Comment by giordano** [comment]
Failures in https://buildkite.com/julialang/yggdrasil/builds/4801 were do to network glitches, I restarted the failing jobs and now [the version has been registered correctly](https://github.com/JuliaRegistries/General/pull/90506)

**Comment by barche** [comment]
Oh-oh, I just noted that this built against libcxxwrap-julia 1.10, so a new PR with a compat entry will still be needed. Also note that in debugging a test failure on CxxWrap I discovered that libcxxwrap-julia 0.10 is fatally flawed, so it will be replaced by 0.11.

**Comment by giordano** [comment]
> I discovered that libcxxwrap-julia 0.10 is fatally flawed

Yank it then to prevent anyone from using it

**Comment by barche** [comment]
Done in PR https://github.com/JuliaRegistries/General/pull/90705

**Pull request merged**
