### PR TITLE
[libcxxwrap-julia] Update for Julia 1.7

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
CC @barche @thofma @benlorenz

**Comment by fingolfin** [comment]
Argh, of course this fails because Julia 1.7.0-beta2 has buggy C headers, to be fixed via https://github.com/JuliaLang/julia/pull/41382 in beta3 (by backporting https://github.com/JuliaLang/julia/pull/41308)

So to continue, we first need to add a patch for libjulia with at least that fix backported, then rebuild that again. *sigh*

**Comment by barche** [comment]
Could it be enough to apply the patch here, or does it affect the libjulia binary as well?

**Comment by fingolfin** [comment]
It would be enough but tgen every single Jll package using libjulia would need it. That makes no sense to me. Let's just merge #3264 (after I fixed it)

**Comment by fingolfin** [comment]
OK, seems we should have at least one more tweak in `libjulia_jll` (namely turn `libuv` back into a dependency, instead of just a builddep).

Anyway, I worked around that by adding libuv as a builddep here; next I run into compiler errors in the cxxwrap C++ codebase:
- `jl_get_ptls_states` still exist but is not declared in `julia.h` anymore. Instead, use `jl_current_task->ptls`
- `jl_new_datatype` gained a new argument, `fattrs` (one can simply pass `jl_emptysvec` for that)

I've added a patch to resolve both, also submitted as https://github.com/JuliaInterop/libcxxwrap-julia/pull/86

Now it dies in the linker: 
> undefined reference to `jl_get_pgcstack'

**Comment by benlorenz** [comment]
> Now it dies in the linker:
> 
> > undefined reference to `jl_get_pgcstack'

So we probably need a patch for libjulia_jll (+ backport) of https://github.com/JuliaLang/julia/pull/41320
At least with a local build of 1.7 this seems to help.

**Comment by fingolfin** [comment]
@benlorenz thanks for pointing that one out. It doesn't seem to be in https://github.com/JuliaLang/julia/pull/41382 though -- I guess that'd we should ask for that, then. Will do

**Comment by fingolfin** [comment]
Note that even if we apply https://github.com/JuliaLang/julia/pull/41320 the resulting binaries won't work there.

**Comment by barche** [comment]
Same error when building libcxxwrap locally against the julia1.7 beta2 binariy.

**Comment by fingolfin** [comment]
Yeah, beta2 is just broken in several ways for anybody trying to link against its C ABI. We gotta hope beta3 will be better

**Comment by giordano** [comment]
```console
% nm libjulia.v1.7.0.x86_64-linux-gnu-cxx11-julia_version+1.7.0/lib/libjulia.so | grep jl_get_pgcstack
% nm libjulia.v1.7.0.x86_64-linux-gnu-cxx11-julia_version+1.7.0/lib/libjulia-internal.so | grep jl_get_pgcstack
0000000000107fb0 T jl_get_pgcstack
0000000000498a48 d jl_get_pgcstack_cb
0000000000107e20 t jl_get_pgcstack_fallback
0000000000107e60 t jl_get_pgcstack_init
```

**Comment by fingolfin** [comment]
Yeah the symbol exists, it just is not exported; on master this was fixed in https://github.com/JuliaLang/julia/pull/41320 but that one is not even scheduled for backporting yet :-(

**Comment by giordano** [comment]
> but that one is not even scheduled for backporting yet :-(

image

**Comment by fingolfin** [comment]
Ah, great! Thanks @vchuravy

**Comment by giordano** [comment]
Issue https://github.com/JuliaLang/julia/issues/41464 is probably going to track something relevant for you as well

**Comment by fingolfin** [comment]
With the new patched libjulia_jll this now builds. I also dropped the patches and instead switched to a newer commit of the libcxxwrap-julia git repository which already has those patches applied.

Seems to build now! yay

**Comment by fingolfin** [comment]
@giordano OK to merge?

**Pull request merged**
