### PR TITLE
[FFMPEG] Update builder

### PR DESCRIPTION
**Pull request by giordano**
* Update configure options to match those in [JuliaIO/FFMPEGBuilder](https://github.com/JuliaIO/FFMPEGBuilder/blob/99bb3a1c82dd4b8ca15487b9f1be749153662ad8/build_tarballs.jl)
* Remove products coming from other libraries
* Fix capitalisation of dependencies, add `OpenSSL_jll`

Depends on #183.

### CODE REVIEW

**Comment by giordano** [comment]
I was expecting a failure because dependencies in #183 don't have a registered JLL package yet, but the error message
```
[2K[?25h Resolving package versions...
ERROR: LoadError: MethodError: Cannot `convert` an object of type Nothing to an object of type Base.UUID
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T at essentials.jl:168
  Base.UUID(::Any) at uuid.jl:9
Stacktrace:
 [1] setindex!(::Dict{Base.UUID,String}, ::String, ::Nothing) at ./dict.jl:372
 [2] resolve_versions!(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Pkg/src/Operations.jl:316
 [3] (::BinaryBuilder.var"#34#36"{Prefix,Linux,Array{String,1}})() at /root/.julia/packages/BinaryBuilder/zhhKL/src/Prefix.jl:339
 [4] activate(::BinaryBuilder.var"#34#36"{Prefix,Linux,Array{String,1}}, ::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Pkg/src/API.jl:851
 [5] setup_dependencies(::Prefix, ::Array{Pkg.Types.PackageSpec,1}, ::Linux) at /root/.julia/packages/BinaryBuilder/zhhKL/src/Prefix.jl:336
 [6] (::BinaryBuilder.var"#296#303"{Bool,Bool,Bool,Bool,Bool,Bool,Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},String,String,VersionNumber,String,Array{Platform,1},Array{Product,1},Dict{Any,Any}})(::String) at /root/.julia/packages/BinaryBuilder/zhhKL/src/AutoBuild.jl:442
 [7] #mktempdir#18(::String, ::typeof(mktempdir), ::BinaryBuilder.var"#296#303"{Bool,Bool,Bool,Bool,Bool,Bool,Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},String,String,VersionNumber,String,Array{Platform,1},Array{Product,1},Dict{Any,Any}}, ::String) at ./file.jl:634
 [8] mktempdir at ./file.jl:632 [inlined] (repeats 2 times)
 [9] #autobuild#294(::Bool, ::Bool, ::Bool, ::Bool, ::Bool, ::Nothing, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(autobuild), ::String, ::String, ::VersionNumber, ::Array{Pair{String,String},1}, ::String, ::Array{Platform,1}, ::Array{Product,1}, ::Array{String,1}) at /root/.julia/packages/BinaryBuilder/zhhKL/src/AutoBuild.jl:346
 [10] (::BinaryBuilder.var"#kw##autobuild")(::NamedTuple{(:verbose, :debug),Tuple{Bool,Bool}}, ::typeof(autobuild), ::String, ::String, ::VersionNumber, ::Array{Pair{String,String},1}, ::String, ::Array{Platform,1}, ::Array{Product,1}, ::Array{String,1}) at ./none:0
 [11] #build_tarballs#282(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(build_tarballs), ::Array{String,1}, ::String, ::VersionNumber, ::Array{Pair{String,String},1}, ::String, ::Array{Platform,1}, ::Array{Product,1}, ::Array{String,1}) at /root/.julia/packages/BinaryBuilder/zhhKL/src/AutoBuild.jl:156
 [12] build_tarballs(::Array{String,1}, ::String, ::VersionNumber, ::Array{Pair{String,String},1}, ::String, ::Array{Platform,1}, ::Array{Product,1}, ::Array{String,1}) at /root/.julia/packages/BinaryBuilder/zhhKL/src/AutoBuild.jl:23
 [13] top-level scope at /workspace/F/FFMPEG/build_tarballs.jl:138
 [14] include at ./boot.jl:328 [inlined]
 [15] include_relative(::Module, ::String) at ./loading.jl:1105
 [16] include(::Module, ::String) at ./Base.jl:31
 [17] exec_options(::Base.JLOptions) at ./client.jl:295
 [18] _start() at ./client.jl:468
in expression starting at /workspace/F/FFMPEG/build_tarballs.jl:138
```
is rather cryptic and it doesn't mention which package is missing :confused:

**Comment by staticfloat** [comment]
https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/490

**Comment by giordano** [comment]
[This](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=134&view=logs&j=94886c89-1067-5128-4ba0-3fc53e2018fb&t=9a025564-307d-5786-f8fb-f384736d6306&l=51) is beautiful:

image

This nicely lets me know that I got three dependencies wrong :blush:

**Comment by staticfloat** [comment]
It should be able to find `Opus_jll` though?  🤔

**Comment by giordano** [comment]
Only if you merge https://github.com/JuliaRegistries/General/pull/5307 :stuck_out_tongue:

**Comment by staticfloat** [comment]
*cough cough*

**Comment by giordano** [comment]
Finally building for all platforms :slightly_smiling_face:

**Pull request merged**
