### PR TITLE
Build LLNL Elemental fork

### PR DESCRIPTION
**Pull request by christopher-dG**
So it turns out that Elemental is actually unmaintained and has been forked to this other repo where development has continued... It also seems to have been pseudo-renamed, not really sure whether this should have been called Elemental or Hydrogen. Don't merge this yet, I mostly just want to see which platforms build properly. 

e: looks like musl is not cooperating

### CODE REVIEW

**Comment by giordano** [comment]
Quoting from https://github.com/JuliaPackaging/Yggdrasil/issues/854#issuecomment-613046240

> I think it's a known issue in musl: https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/387.  See for example what we did in ZeroMQ to work around it: https://github.com/JuliaPackaging/Yggdrasil/blob/48ac662cd53e02aff0189c81008874a04f7172c7/Z/ZeroMQ/build_tarballs.jl#L20-L27

**Comment by christopher-dG** [comment]
Thanks for the tip :slightly_smiling_face:

**Comment by giordano** [comment]
Good to go?

**Comment by christopher-dG** [comment]
Just to confirm, JLL packages are no different from normal packages wrt compat, right? So if this is merged and Elemental_jll has both 0.87.7 and 1.3.3, I can just restrict Elemental_jll to `<1` or whatever to get the old version?

**Comment by giordano** [comment]
That's correct!

**Pull request merged**
