### PR TITLE
[tokei] use prebuilt executables

### PR DESCRIPTION
**Pull request by ericphanson**
I mimicked tectonic and made sure to add the feature flag to get JSON output

### CODE REVIEW

**Comment by ericphanson** [comment]
ref https://github.com/giordano/AnalyzeRegistry.jl/issues/8#issuecomment-777877687

Some googling indicates there's issues with compiling rust from musl.

I think I might just wrap the 64-bit prebuilt binaries for mac/windows/linux gnu / linux musl.

**Comment by giordano** [comment]
> Some googling indicates there's issues with compiling rust from musl.

I know.... This is the error I was expecting, I've seen also in tectonic a few days ago (#2515).

> I think I might just wrap the 64-bit prebuilt binaries for mac/windows/linux gnu / linux musl.

Yeah, at the moment it seems the best approach, until we can get a working Rust toolchain

**Comment by ericphanson** [comment]
Huh...
```julia
julia> tokei() do exe
           run(`$exe -h`)
       end
/Users/eh540/.julia/artifacts/27c9d1b9340ee8172c7bca38de97932b2940cceb/bin/tokei: /Users/eh540/.julia/artifacts/27c9d1b9340ee8172c7bca38de97932b2940cceb/bin/tokei: cannot execute binary file
ERROR: failed process: Process(`/Users/eh540/.julia/artifacts/27c9d1b9340ee8172c7bca38de97932b2940cceb/bin/tokei -h`, ProcessExited(126)) [126]
```

**Comment by giordano** [comment]
It's a tarball
```
shell> file $(Tokei_jll.tokei_path)
/home/mose/.julia/artifacts/eb1ea0844d13d34320da40c8b1658114d5f38dff/bin/tokei: gzip compressed data, last modified: Tue Jan 12 21:16:40 2021, from Unix, original size modulo 2^32 6225920
```
Don't ask me why Auditor was happy about it :see_no_evil:

**Comment by ericphanson** [comment]
ah, that explains why the URLs end with `.tar.gz` 😆

**Comment by giordano** [comment]
Yeah, sorry, I didn't notice that either... Those should be `ArchiveSource`

**Pull request merged**
