### PR TITLE
Wizard recipe: libinchi-v1.5.0

### PR DESCRIPTION
**Pull request by mojaie**
This pull request contains a new build recipe I built using the BinaryBuilder.jl wizard:

* Package name: libinchi
* Version: v1.5.0

@staticfloat please review and merge.

### CODE REVIEW

**Comment by mojaie** [comment]
mingw32 local build was successful in BinaryBuilder.run_wizard(). Is it something wrong...?

**Comment by giordano** [comment]
It may have been a bug in the wizard: https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/790

**Comment by giordano** [comment]
The library for Windows was simply not install.  I didn't have much interest in wrestling with CMake to convince it to install the library, so I just copied it manually.

Where is this code coming from?  It has a non-OSI license, it's not entirely clear to me whether we can redistribute it

**Comment by mojaie** [comment]
Thank you very much for your help.

Original source code is available at https://www.inchi-trust.org/downloads/
The InChI license is more permissive than LGPL, they said.
https://www.inchi-trust.org/technical-faq-2/#3.3

The library is used internally in widely known opensource projects in the field of cheminformatics
https://github.com/epam/Indigo/tree/master/third_party/inchi
https://github.com/openbabel/openbabel/tree/master/src/formats/libinchi

**Pull request merged**
