### PR TITLE
 [CoinUtils] Add  v2.11.3

### PR DESCRIPTION
**Pull request by ViralBShah**

### CODE REVIEW

**Comment by ViralBShah** [comment]
@giordano Any idea what is happening with ppc. I can't quite tell what the error is.

https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=2710&view=logs&j=16c254b1-7709-5de4-34ec-ce8f611959d7&t=e36e1d58-a663-58aa-366a-d863ede6b499&l=741

```
[ Info: Could not locate libCoinUtils inside ["/agent/_work/1/s/C/Coin-OR/CoinUtils/build/powerpc64le-linux-gnu-cxx11/P5oGBkT7/destdir/lib64", "/agent/_work/1/s/C/Coin-OR/CoinUtils/build/powerpc64le-linux-gnu-cxx11/P5oGBkT7/destdir/lib"]
┌ Error: Built CoinUtils but libCoinUtils still unsatisfied:
└ @ BinaryBuilder /depot/packages/BinaryBuilder/2Mudg/src/AutoBuild.jl:698
ERROR: LoadError: Cannot continue with unsatisfied build products!
```

**Comment by giordano** [comment]
Since also FreeBSD is failing, my guess is that it's always: https://github.com/JuliaPackaging/Yggdrasil/wiki/Build-Tricks#shared-library-not-built, i.e. out-of-date `configure` script that doesn't know how to build shared library for these two platforms :roll_eyes:

**Comment by giordano** [comment]
See https://github.com/coin-or/CoinUtils/issues/117

**Comment by ViralBShah** [comment]
Ok. thanks. For now, just disabling like before. I think a few months down the line, these will work.

**Pull request merged**
