### PR TITLE
[CImGuiPack] Fix version

### PR DESCRIPTION
**Pull request by Gnimuc**
The new src introduced breaking changes.

### CODE REVIEW

**Comment by giordano** [comment]
Are you going to yank the previous version? Otherwise I don't see how this duplicate helps

**Comment by Gnimuc** [comment]
https://github.com/JuliaImGui/LibCImGui.jl/blob/release-1.82.x/Project.toml 

CImGuiPack_jll is only used by LibCImGui so my plan is to drop 0.13 by forcing the version of CImGuiPack_jll to =0.1.2

There is no plan to maintain 0.1.x in the future.

**Comment by giordano** [comment]
I still think you may want to yank the broken version to ensure it's never ever used.

**Comment by Gnimuc** [comment]
@giordano Could you elaborate more about how to "yank" the broken version? Do you mean to open a PR to the registry?

**Comment by giordano** [comment]
> Do you mean to open a PR to the registry?

Yes, see for example https://github.com/JuliaRegistries/General/pulls?q=is%3Apr+sort%3Aupdated-desc+label%3Ayank+is%3Aclosed

**Comment by Gnimuc** [comment]
Thanks!

**Pull request merged**
