### PR TITLE
[tokei] unpack archives

### PR DESCRIPTION
**Pull request by ericphanson**
try to fix https://github.com/JuliaPackaging/Yggdrasil/pull/2540#issuecomment-778864910

### CODE REVIEW

**Comment by ericphanson** [comment]
I'm not sure this is right; I grabbed the link https://julia-bb-buildcache.s3.amazonaws.com/832f0d52e696354cdd22425aa70db1f209d62c9d84626a7e48cf4ca0190cfd50/825c02231f96ca71734b6b0d9b7ea1526c1c23d59b94a78655cb29b70797be6c/x86_64-apple-darwin.tar.gz from the CI process, and downloaded it locally. When I try `./tokei` in the `bin` folder, it pops up and says `“tokei” is damaged and can’t be opened. You should move it to the Bin.`

But it seems to not be an archive this time:
```
> file tokei
tokei: Mach-O 64-bit executable x86_64
```

**Comment by giordano** [comment]
@staticfloat any idea of what could be wrong with the macOS binary?

@ericphanson any way to test the Windows binary?  I hope it isn't an installer :sweat_smile:

**Comment by staticfloat** [comment]
I downloaded that archive, extracted it and run it just fine:

```
$ curl -L 'https://julia-bb-buildcache.s3.amazonaws.com/832f0d52e696354cdd22425aa70db1f209d62c9d84626a7e48cf4ca0190cfd50/825c02231f96ca71734b6b0d9b7ea1526c1c23d59b94a78655cb29b70797be6c/x86_64-apple-darwin.tar.gz' | tar zxv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1600k  100 1600k    0     0  2997k      0 --:--:-- --:--:-- --:--:-- 2997k
x bin/tokei
x logs/Tokei.log.gz
x logs/ldid_tokei.log.gz
x share/licenses/Tokei/LICENCE-APACHE
x share/licenses/Tokei/LICENCE-MIT
$ ./bin/tokei 
===============================================================================
 Language            Files        Lines         Code     Comments       Blanks
===============================================================================
===============================================================================
 Total                   0            0            0            0            0
===============================================================================
$ shasum -a 256 bin/tokei 
9fb87322caa2bb27191f03a3b10a146e914bf51cb1e56c741fab1a29bc69cbd2  bin/tokei
```

**Comment by ericphanson** [comment]
Thanks @staticfloat, I repeated your commands and got the same thing. Maybe I downloaded it wrong or it got corrupted or something when I tried earlier. I had used `wget` instead of `curl` and extracted by double-clicking instead of commandline but I don't think that stuff should matter. But anyway, seems like this is good to go 🎉 !

**Pull request merged**
