### PR TITLE
[JuliaNVTXCallbacks] initial attempt

### PR DESCRIPTION
**Pull request by simonbyrne**
I have no idea if this is the correct way to do this, but I'm trying to build this: https://github.com/simonbyrne/NVTX.jl/tree/main/deps

### CODE REVIEW

**Comment by simonbyrne** [comment]
Okay, not bad. Not sure why some of them failed...

**Comment by simonbyrne** [comment]
@giordano any idea why we're not picking up the CUDA headers on Windows?

**Comment by simonbyrne** [comment]
This also leaves open the question of how to handle `version = "local"`: I guess build it in a scratch space (via Scratch.jl)?

**Comment by giordano** [comment]
@maleadt

**Comment by maleadt** [comment]
CUDA_Runtime_jll is not meant as a build-time dependency, you need CUDA_full_jll for that. Seet e.g. the SuiteSparse recipe: https://github.com/JuliaPackaging/Yggdrasil/blob/master/S/SuiteSparse/SuiteSparse_GPU/build_tarballs.jl

**Comment by simonbyrne** [comment]
Okay, i've switched it, but am still not picking up the headers on Windows.

**Comment by simonbyrne** [comment]
What is the CUDA path? I tried this:
https://github.com/JuliaPackaging/Yggdrasil/blob/33f7cbd4ba0e4789fef6b20cb4ee15532b24331c/S/SuiteSparse/SuiteSparse_GPU/build_tarballs.jl#L37
but it didn't seem to work.

**Comment by simonbyrne** [comment]
I don't see any examples of building against CUDA on Windows in Yggdrasil

**Comment by simonbyrne** [comment]
Okay, so it turns out that NVTX has switched to being header-only, so I was picking up the old (wrong) header.

However now I'm getting issues with certain variables not being defined. On Linux:
```
[06:36:29] In file included from /opt/x86_64-linux-gnu/bin/../x86_64-linux-gnu/sys-root/usr/local/include/nvtx3/nvtxDetail/nvtxImpl.h:461:0,
[06:36:29]                  from /opt/x86_64-linux-gnu/bin/../x86_64-linux-gnu/sys-root/usr/local/include/nvtx3/nvToolsExt.h:1494,
[06:36:29]                  from callbacks.c:2:
[06:36:29] /opt/x86_64-linux-gnu/bin/../x86_64-linux-gnu/sys-root/usr/local/include/nvtx3/nvtxDetail/nvtxInit.h: In function ‘nvtxInitializeInjectionLibrary_v3’:
[06:36:29] /opt/x86_64-linux-gnu/bin/../x86_64-linux-gnu/sys-root/usr/local/include/nvtx3/nvtxDetail/nvtxInit.h:151:47: error: ‘PATH_MAX’ undeclared (first use in this function)
[06:36:29]          NVTX_PATHCHAR injectionLibraryPathBuf[NVTX_BUFSIZE];
[06:36:29]                                                ^
```

The headers are available here:
https://github.com/NVIDIA/NVTX/tree/release-v3/c/include/nvtx3

**Comment by simonbyrne** [comment]
Also on Windows:
```
[06:51:34]  ---> ls ${CUDA_PATH}/include/nvtx3/nvToolsExt.h
[06:51:34] ls: /workspace/destdir/cuda/include/nvtx3/nvToolsExt.h: No such file or directory
```
But it is in the CUDA_full artifact tarball. Am I getting the wrong CUDA directory?

**Comment by giordano** [comment]
`PATH_MAX` should be defined in linux/limits.h on Linux: https://stackoverflow.com/a/9449307/2442087. How they expect this to magically work without including the appropriate header is everybody's guess.

**Comment by simonbyrne** [comment]
okay, I've switched to using the git sources, which makes this much simpler. Thanks @maleadt and @giordano

**Comment by giordano** [comment]
Would it make sense to base this on `NVTX_jll`, to avoid duplication?

**Comment by simonbyrne** [comment]
We could move the patches there, but this is somewhat separate

**Pull request merged**
