### PR TITLE
Wizard recipe: P11Kit-v0.24.1

### PR DESCRIPTION
**Pull request by lucifer1004**
This pull request contains a new build recipe I built using the BinaryBuilder.jl wizard:

* Package name: P11Kit
* Version: v0.24.1

@staticfloat please review and merge.

### CODE REVIEW

**Comment by lucifer1004** [comment]
This will enable #5683

**Comment by lucifer1004** [comment]
@giordano Seems that on Windows, some built products are installed to different locations. How should I debug this locally?

**Comment by jeremiahpslewis** [comment]
@lucifer1004

1. From the `P11Kit` directory, run `julia —project=../../.ci build_tarballs.jl --debug —verbose x86_64-w64-mingw32` to debug the x86 windows platform, you'll be dropped into a debug shell upon error
2. You probably want to copy the build artifacts into the appropriate directory `${libdir}` or `${bindir}` as part of the build script, this way you don't have to specify the path in the `products` section of the code and can special case windows, like here: https://github.com/JuliaPackaging/Yggdrasil/blob/0d10b8e80ded9cbdab0e028054b26a0a2c9e1ed5/C/cilantro/build_tarballs.jl#L31

**Comment by lucifer1004** [comment]
I checked and found that a library was not built on Windows. How should we handle this situation?

**Comment by lucifer1004** [comment]
BTW, I cannot simply move the products to libdir and bindir because they depend on the relative path.

**Pull request merged**
