### PR TITLE
[LibUv] Bump version

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by giordano** [comment]
@staticfloat what version number should this use?

**Comment by musm** [comment]
I don't think we specifically version libuv

**Comment by musm** [comment]
Julia uses a fork and we just update to the latest commit on that fork for now

**Comment by staticfloat** [comment]
Yeah.... unfortunately, `v2` is "correct".  The version number of Julia's libuv fork is a hotly-contested topic.  ;)

**Comment by staticfloat** [comment]
Luckily, version numbers don't matter for this too much since its statically-linked into Julia, and we select it based on hash anyway.

**Comment by musm** [comment]
good to merge then?

**Comment by giordano** [comment]
>  since its statically-linked into Julia

Maybe not anymore in the future: https://github.com/JuliaLang/julia/pull/36697?

**Comment by giordano** [comment]
Uh, wrong library :sweat_smile:

**Pull request merged**
