### PR TITLE
[yosys] update to 34

### PR DESCRIPTION
**Pull request by sjkelly**
This is a simple version bump, but the dependencies list is quite old at this point. Is there a good way to update the dependency `compat`s automatically?

### CODE REVIEW

**Comment by giordano** [comment]
> Is there a good way to update the dependency compats automatically?

No, also because I don't that's a well defined process

**Comment by imciner2** [comment]
@sjkelly do you want to update the compats, or should we just merge this in and that be done later?

**Comment by sjkelly** [comment]
Since it builds, I suppose we can merge in the interim. I have been prototyping an update script to automate this.

**Comment by ViralBShah** [comment]
Merge?

**Pull request merged**
