### PR TITLE
[LLVM] Build LLVM 12

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Comment by jpsamaroo** [comment]
musl: Maybe the `__GLIBC__` macro is being set when it shouldn't be? In `linux/kernel.h` (where the compiler points to the duplicate include) I see:

```
#ifdef __GLIBC__
#include <linux/sysinfo.h>
#endif
```

This is odd, though, because there are `ifndef`s in place to prevent such double-includes.

**Comment by giordano** [comment]
So, the conflicting includes are at lines 72 and 81 of https://github.com/llvm/llvm-project/blob/d28af7c654d8db0b68c175db5ce212d74fb5e9bc/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp#L72-L81, which according to blame were introduced 8 years ago.  I haven't investigate further, but the last commit of the file is https://github.com/llvm/llvm-project/commit/7afdc89c2054d6fa3a6c2f2f24411becfc764676, which is supposed to refine musl support

**Comment by vchuravy** [comment]
Filled the mingw32 upstream https://github.com/intel/ittapi/issues/19

**Comment by giordano** [comment]
`x86_64-w64-mingw32-cxx03` is failing with
```
[02:18:05] [3595/3794] : && /usr/bin/cmake -E rm -f lib/libclangBasic.a && /opt/bin/x86_64-w64-mingw32-libgfortran4-cxx03/x86_64-w64-mingw32-ar qc lib/libclangBasic.a  tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Attributes.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Builtins.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/CharInfo.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/CodeGenOptions.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Cuda.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Diagnostic.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/DiagnosticIDs.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/DiagnosticOptions.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/ExpressionTraits.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/FileEntry.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/FileManager.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/FileSystemStatCache.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/IdentifierTable.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/LangOptions.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/LangStandards.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Module.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/ObjCRuntime.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/OpenCLOptions.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/OpenMPKinds.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/OperatorPrecedence.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/ProfileList.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/SanitizerBlacklist.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/SanitizerSpecialCaseList.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Sanitizers.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/SourceLocation.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/SourceManager.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Stack.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/TargetID.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/TargetInfo.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/AArch64.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/AMDGPU.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/ARC.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/ARM.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/AVR.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/BPF.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/Hexagon.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/Lanai.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/Le64.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/MSP430.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/Mips.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/NVPTX.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/OSTargets.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/PNaCl.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/PPC.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/RISCV.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/SPIR.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/Sparc.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/SystemZ.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/TCE.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/VE.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/WebAssembly.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/X86.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Targets/XCore.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/TokenKinds.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/TypeTraits.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Version.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/Warnings.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/XRayInstr.cpp.obj tools/clang/lib/Basic/CMakeFiles/obj.clangBasic.dir/XRayLists.cpp.obj && /opt/bin/x86_64-w64-mingw32-libgfortran4-cxx03/x86_64-w64-mingw32-ranlib lib/libclangBasic.a && :
[02:18:05] ninja: job failed: : && /opt/bin/x86_64-w64-mingw32-libgfortran4-cxx03/x86_64-w64-mingw32-g++ --sysroot=/opt/x86_64-w64-mingw32/x86_64-w64-mingw32/sys-root/ -remap -D__USING_SJLJ_EXCEPTIONS__ -D__CRT__NO_INLINE -fno-gnu-unique -Wa,-mbig-obj -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment  -O2 -DNDEBUG  -Wl,--stack,16777216 tools/llvm-rc/CMakeFiles/llvm-rc.dir/llvm-rc.cpp.obj tools/llvm-rc/CMakeFiles/llvm-rc.dir/ResourceFileWriter.cpp.obj tools/llvm-rc/CMakeFiles/llvm-rc.dir/ResourceScriptCppFilter.cpp.obj tools/llvm-rc/CMakeFiles/llvm-rc.dir/ResourceScriptParser.cpp.obj tools/llvm-rc/CMakeFiles/llvm-rc.dir/ResourceScriptStmt.cpp.obj tools/llvm-rc/CMakeFiles/llvm-rc.dir/ResourceScriptToken.cpp.obj  -o bin/llvm-rc.exe -Wl,--out-implib,lib/libllvm-rc.dll.a -Wl,--major-image-version,0,--minor-image-version,0  lib/libLLVM.dll.a  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && :
[02:18:05] tools/llvm-rc/CMakeFiles/llvm-rc.dir/ResourceScriptParser.cpp.obj:ResourceScriptParser.cpp:(.text$_ZNK4llvm2rc10RCResource5visitEPNS0_7VisitorE+0x0): multiple definition of `llvm::rc::RCResource::visit(llvm::rc::Visitor*) const'
[02:18:05] tools/llvm-rc/CMakeFiles/llvm-rc.dir/ResourceFileWriter.cpp.obj:ResourceFileWriter.cpp:(.text$_ZNK4llvm2rc10RCResource5visitEPNS0_7VisitorE+0x0): first defined here
[02:18:05] tools/llvm-rc/CMakeFiles/llvm-rc.dir/ResourceScriptStmt.cpp.obj:ResourceScriptStmt.cpp:(.text$_ZNK4llvm2rc10RCResource15getResourceTypeEv+0x0): multiple definition of `llvm::rc::RCResource::getResourceType() const'
[02:18:05] tools/llvm-rc/CMakeFiles/llvm-rc.dir/ResourceScriptParser.cpp.obj:ResourceScriptParser.cpp:(.text$_ZNK4llvm2rc10RCResource15getResourceTypeEv+0x0): first defined here
[02:18:05] tools/llvm-rc/CMakeFiles/llvm-rc.dir/ResourceScriptStmt.cpp.obj:ResourceScriptStmt.cpp:(.text$_ZNK4llvm2rc10RCResource19getResourceTypeNameEv+0x0): multiple definition of `llvm::rc::RCResource::getResourceTypeName() const'
[02:18:05] tools/llvm-rc/CMakeFiles/llvm-rc.dir/ResourceScriptParser.cpp.obj:ResourceScriptParser.cpp:(.text$_ZNK4llvm2rc10RCResource19getResourceTypeNameEv+0x0): first defined here
[02:18:05] tools/llvm-rc/CMakeFiles/llvm-rc.dir/ResourceScriptStmt.cpp.obj:ResourceScriptStmt.cpp:(.text$_ZNK4llvm2rc10RCResource5visitEPNS0_7VisitorE+0x0): multiple definition of `llvm::rc::RCResource::visit(llvm::rc::Visitor*) const'
[02:18:05] tools/llvm-rc/CMakeFiles/llvm-rc.dir/ResourceFileWriter.cpp.obj:ResourceFileWriter.cpp:(.text$_ZNK4llvm2rc10RCResource5visitEPNS0_7VisitorE+0x0): first defined here
[02:18:05] collect2: error: ld returned 1 exit status
```

**Pull request merged**
