### PR TITLE
[DynarePreprocessor] Update to v6.1.0

### PR DESCRIPTION
**Pull request by MichelJuillard**
New version of Dynare preprocessor source  and patches for clang

### CODE REVIEW

**Comment by MichelJuillard** [comment]
For some weird reason in aarch64-apple-darwin SDK 11.3 doesn't know map::contains but other apple-darwin architectures do as well as FreeBSD. I will deal with it tomorrow

**Comment by giordano** [comment]
Maybe because https://github.com/JuliaPackaging/Yggdrasil/blob/781206cac2788ebcdc43df01904fa4f6b256cb97/D/DynarePreprocessor/build_tarballs.jl#L31 says 11.1? That setting is important for declaring compatibility.

**Comment by MichelJuillard** [comment]
Thanks @giordano !

**Comment by ViralBShah** [comment]
As someone who studied macroecon at one point, I'm excited to see Dynare becoming first class in Julia! Thanks @MichelJuillard.

**Comment by MichelJuillard** [comment]
Thanks @ViralBShah ! We have still a way to go :)

**Pull request merged**
