### PR TITLE
Wizard recipe: COINBLAS-v1.4.8

### PR DESCRIPTION
**Pull request by giordano**
This pull request contains a new build recipe I built using the BinaryBuilder.jl wizard:

* Package name: COINBLAS
* Version: v1.4.8

@staticfloat please review and merge.

### CODE REVIEW

**Comment by giordano** [comment]
For PowerPC and FreeBSD, [regenerating the `configure` script would help](https://github.com/JuliaPackaging/Yggdrasil/wiki/Build-Tricks#shared-library-not-built), but the package doesn't ship the definitions of the M4 macros used in `configure.ac` :man_facepalming:

**Comment by ViralBShah** [comment]
Since this package doesn't depend on OpenBLAS_jll, is it fair to assume it is not using the system provided BLAS?

**Comment by giordano** [comment]
I know nothing about these COIN packages, I assume what you say is correct.

**Comment by giordano** [comment]
I mean, unless this does something magical at runtime (no idea, I dind't dare to look into the code), then no, it's not using Julia's BLAS

**Comment by ViralBShah** [comment]
Thanks. I looked a bit deeper. We don't want to use this package as it is just the reference BLAS.

**Comment by giordano** [comment]
Yeah, building this package has been a complete waste of a lot of time.  The maintainer said this is basically dead, too

**Comment by ViralBShah** [comment]
Sorry about that. I wish they archive these packages, or at least include a message in the README.

**Pull request merged**
