### PR TITLE
builder for PARMETIS

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
I restricted the list of platforms to MacOS to see if the build fails (it fails locally for me).

**Comment by dpo** [comment]
FWIW the build succeeds on my Mac (not using BinaryBuilder).

**Comment by ViralBShah** [comment]
Wow - this would be huge if it works. I was wondering if MPICH_jll is ready enough to be dependencies for other packages. I know that MPI.jl has some work to do on the Julia side before it uses MPICH_jll, but other packages can start using it.

**Comment by ViralBShah** [comment]
Wow - this would be huge if it works. I was wondering if MPICH_jll is ready enough to be dependencies for other packages. I know that MPI.jl has some work to do on the Julia side before it uses MPICH_jll, but other packages can start using it.

**Comment by dpo** [comment]
It looks like MPICH_jll is working fine here, but the issue comes from CMake or some setting in the cross-compilation environment.

**Comment by dpo** [comment]
You got it. Thank you!

**Comment by giordano** [comment]
Good to merge?

**Comment by giordano** [comment]
> I know that MPI.jl has some work to do on the Julia side before it uses MPICH_jll, but other packages can start using it.

One known problem is that it isn't easy to override libmpi at the moment: https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/625

**Comment by dpo** [comment]
> Good to merge?

Yeah! Thanks for the hand!

**Pull request merged**
