### PR TITLE
update NetCDF 4.8.0

### PR DESCRIPTION
**Pull request by Alexander-Barth**
This PR should upgrade NetCDF to the current version 4.8.0.

### CODE REVIEW

**Comment by giordano** [comment]
You also need to touch the `build_tarballs.jl` file corresponding to the version you want to build

**Comment by Alexander-Barth** [comment]
Thanks @giordano, I just added a new line to the files `NetCDF@julia-*/build_tarballs.jl`. Is this OK?

**Comment by giordano** [comment]
Yes, but NetCDF doesn't seem to like Conda's HDF5.... If only we could build it...

**Comment by Alexander-Barth** [comment]
I am testing this work-around: https://github.com/Unidata/netcdf-c/issues/1978

**Comment by Alexander-Barth** [comment]
The error on windows is now different:

```
2021-05-17T15:55:38.3906619Z [15:55:38] dpathmgr.c: In function ‘NCclosedir’:
2021-05-17T15:55:38.3907622Z [15:55:38] (first use in this function)
2021-05-17T15:55:38.3908452Z [15:55:38]      char* cvtname = NCpathcvt(path);
2021-05-17T15:55:38.3909108Z [15:55:38]                                ^
2021-05-17T15:55:38.3909968Z [15:55:38] dpathmgr.c:359:31: note: each undeclared identifier is reported only once for each function it appears in
```

I raised an issue here:
https://github.com/Unidata/netcdf-c/issues/1999

**Pull request closed without merging**
