### PR TITLE
PhyML: Enable MPItrampoline

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by eschnett** [comment]
This fails because it builds against MPItrampoline_jll v.5.0.0. Can you update this to v5.0.1?

@giordano

**Comment by eschnett** [comment]
According to the documentation, this line
```Julia
    ("MPItrampoline", PackageSpec(name="MPItrampoline_jll"), "5", !Sys.iswindows)
```
in `platforms/mpi.jl` should allow all MPItrampoline_jll version from 5 until 6. However, I find that this only selects version 5.0.0 and not version 5.0.1. Do you understand why?

The same applies a few lines further down:
```Julia
    push!(dependencies, Dependency(PackageSpec(name="MPIPreferences", uuid="3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"); compat="0.1"))
```
This will choose exactly `MPIPreferences` v0.1.0, and not the current v0.1.3.

**Comment by vchuravy** [comment]
Mose is on vacation for the next couple of weeks, but yes it was my understanding that this is equivalent to the `compat` section in Project.toml.

and indeed that's how they end up: https://github.com/JuliaBinaryWrappers/LAMMPS_jll.jl/blob/13406ef14359b77e89a050dfbabc86d6f99cbbe5/Project.toml#L22-L23

So the question is, what happens in the middle.

cc: @staticfloat

**Comment by eschnett** [comment]
@vchuravy What happens if I set the compat bound to `^5.0.1` in `mpi.jl`? There are many existing jll packages built with `5.0.0`. Will they continue to work if the bound has been increased?

In other words: Is "We intentionally use the lower compat bound" used only when building the artifacts by BinaryBuilder (which would be fine), or also when loading them in applications?

**Comment by vchuravy** [comment]
So we use the newest when we instantiate a Project.toml. so all those packages should already be using 5.0.1 at runtime.

I think raising it to `5.0.1` is perfectly fine :)

**Comment by staticfloat** [comment]
Yeah, we intentionally use the oldest version when building against it, since we figure that if we use a newer version, a package might configure itself to use features that are not necessarily available in all cases.  If you want to build against a particular version, you can use `build_version` without changing anything about how this gets actually installed on a user's machine.  Changing the `compat` string will effect what is in `Project.toml` for the JLL, and yes, if you set it to `^5.0.1` then you will exclude `5.0.0`, so the next time someone installs your JLL, it will force an upgrade to `5.0.1` of that depenedency.

**Pull request merged**
