### PR TITLE
Bump fzf to 0.43.0

### PR DESCRIPTION
**Pull request by Moelf**

### CODE REVIEW

**Comment by giordano** [comment]
```
[08:36:04] cgo: C compiler "cc" not found: exec: "cc": executable file not found in $PATH
```
Wut

**Comment by Moelf** [comment]
super confused

**Comment by Moelf** [comment]
oh `gcc` doens't giev you cc? oh well, will look into it after

**Comment by giordano** [comment]
We generate `cc` symlinks on all platforms.

**Comment by Moelf** [comment]
you're saying this is not my problem ;)?

**Comment by giordano** [comment]
The missing `:c` compiler was perhaps part of the problem, but now that's explicitly there I don't see why `cc` can't be found (especially since this works everywhere else).  I'll need to debug this when I get some time later this week.

**Comment by giordano** [comment]
Ah, it was the missing `:c`, and I didn't realise it was misspelled before :slightly_smiling_face:

**Pull request merged**
