### PR TITLE
new recipe:  duf

### PR DESCRIPTION
**Pull request by Moelf**

### CODE REVIEW

**Comment by giordano** [comment]
```
┌ Error: duf does not match the hard-float ABI
└ @ BinaryBuilder.Auditor /depot/packages/BinaryBuilder/vDNXJ/src/auditor/extra_checks.jl:24
```
The check works!!

**Comment by giordano** [comment]
Also our `hello_world_go` in `/usr/share/testsuite` has the same `e_flags`:
```
sandbox:${WORKSPACE} # readelf -h ${bindir}/hello_world_go 
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           ARM
  Version:                           0x1
  Entry point address:               0x63654
  Start of program headers:          52 (bytes into file)
  Start of section headers:          276 (bytes into file)
  Flags:                             0x5000002, has entry point, Version5 EABI
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         7
  Size of section headers:           40 (bytes)
  Number of section headers:         25
  Section header string table index: 3
```
At least we already have a good test case :smile:

**Comment by Moelf** [comment]
what do we want to do with this? if the `hello_world_go` has the same issue, should we just move on right now?

**Comment by giordano** [comment]
I'd like to fix the audit test first.  @staticfloat

**Comment by giordano** [comment]
There might be a bug in Go not settingly correctly `e_flags` (#2471), but there is little we can do about this and it doesn't prevent the executable from being run (https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1000), so we can probably go here anyway (luckily the audit failure isn't completely fatal)

**Pull request merged**
