### PR TITLE
[OpenBLAS] Add v0.3.17

### PR DESCRIPTION
**Pull request by ararslan**
This allows us to drop a number of patches.

### CODE REVIEW

**Comment by ararslan** [comment]
The FreeBSD Ports Collection has https://svnweb.freebsd.org/ports/head/math/openblas/files/patch-interface__ztrmv.c?view=markup but it doesn't explain what that's actually for, so I haven't bothered adding it for fear that it could cause issues elsewhere. Does anybody know whether that patch makes sense and is generally safe?

**Comment by staticfloat** [comment]
The patch should be safe, but it looks to me to be working around a compiler issue that it seems we don't have.  So no need to carry it unless we start segfaulting during build.

As an aside (doesn't need to happen in this PR) if we can de-duplicate these patches by using symlinks instead of copies, that would be useful.

**Review by staticfloat — APPROVED** [review]

**Comment by ararslan** [comment]
> As an aside (doesn't need to happen in this PR) if we can de-duplicate these patches by using symlinks instead of copies, that would be useful.

Good idea, will do next time I touch the OpenBLAS stuff, thanks!

**Comment by giordano** [comment]
I believe these should have required Julia v1.8 though

**Comment by ararslan** [comment]
Why's that?

**Comment by giordano** [comment]
Because I don't think this is going to make it to Julia v1.7, is it?

**Comment by ararslan** [comment]
Seems vanishingly unlikely without some compelling reason, but AFAIK it should be able to work on Julia 1.7.

**Comment by giordano** [comment]
Work, all OpenBLAS versions will likely work on any version of Julia :stuck_out_tongue: but since this package is effectively a stdlib, it'd be better to have the registry be aware of which version of OpenBLAS_jll is in which version of Julia

**Pull request merged**
