### PR TITLE
Add `-current_version` and `-compatibility_version` to build Bzip2

### PR DESCRIPTION
**Pull request by giordano**

### CODE REVIEW

**Comment by ianshmean** [comment]
@giordano The executableproduct line should be removed too (I added that in error):
https://github.com/JuliaPackaging/Yggdrasil/blob/bac99b83b8c2655bafbadc80d94384af6d770731/Bzip2/build_tarballs.jl#L69

**Comment by giordano** [comment]
Well, the executable is indeed there, together with a bunch of other binaries, I don't think it hurts.  Let's see what @staticfloat says

**Comment by staticfloat** [comment]
Sure, seems reasonable to me.

**Comment by giordano** [comment]
However, this is failing because of the missing executable: https://ci.appveyor.com/project/kmsquire/videoio-jl/builds/24958355/job/4a37yvn02uoxma4o  I'm confused, as the executable is there.  Is it because it doesn't have the extension (it's simply called `bzip2`)?

**Comment by staticfloat** [comment]
Yeah, we have an `$(exe)` environment variable that is empty on every sane platform, and `".exe"` on Windows, for precisely this reason.  :)

**Comment by giordano** [comment]
Let's just drop the executable then

**Pull request merged**
