### PR TITLE
update SQLCipher

### PR DESCRIPTION
**Pull request by aplavin**

### CODE REVIEW

**Comment by aplavin** [comment]
I don't understand the generator failure at all...

**Comment by giordano** [comment]
The line which is failing is
https://github.com/JuliaPackaging/Yggdrasil/blob/e9495fdd50f0ff025b961aa539ba4a67759b2da6/azure-pipelines.yml#L37
```
fatal: No such ref: 'remotes/origin/refs/heads/master'
```
I have no clue why this is happening, and why only this PR.

**Comment by giordano** [comment]
I converted the PR to draft in case anyone thinks about merging it as it is...

**Comment by giordano** [comment]
I'm more and more convinced that GitHub/Azure just doesn't like your fork and they go haywire for some reasons.  It's just all borked.

Have you considered the option of deleting the fork and starting over?

**Pull request closed without merging**
