### PR TITLE
[Singular] new version

### PR DESCRIPTION
**Pull request by tthsqe12**
with some bug fixes
@thofma

### CODE REVIEW

**Review by thofma — APPROVED** [review]

**Comment by thofma** [comment]
The errors are timeouts.

**Comment by giordano** [comment]
Where do you see the timeouts? :thinking:   I'd expect the error to be the same as https://github.com/JuliaPackaging/Yggdrasil/pull/1618#issuecomment-684077555, waiting for the new compiler shards to find their way to BinaryBuilder.

**Comment by thofma** [comment]
Probably wishful thinking. The same build worked 6 days ago: https://github.com/JuliaPackaging/Yggdrasil/pull/1528. I don't understand all the details, but did something change in the last few days?

**Comment by giordano** [comment]
> did something change in the last few days?

Yes: #1608

**Pull request merged**
