### PR TITLE
[SDL] WIP on SDL v1.2.15

### PR DESCRIPTION
**Pull request by d9w**

### CODE REVIEW

**Comment by d9w** [comment]
Marked as WIP because this doesn't compile on all supported platforms

**Comment by aviks** [comment]
Can you change the PR to use `supported_platforms()` so that we can see what issues there are in compiling. Atleast windows and mac should be working before this is merged.

**Comment by fingolfin** [comment]
SDL2 development is very active these days and https://github.com/libsdl-org/sdl12-compat has been greatly improved, so perhaps it would be better to focus on that?

**Comment by aviks** [comment]
Should close this, superseeded by #6003

**Pull request closed without merging**
