### PR TITLE
Use ROCmLLVM as compiler for hsa_rocr

### PR DESCRIPTION
**Pull request by pxl-th**
We need to use ROCmLLVM to successfully compile other packages ROCm packages.

### CODE REVIEW

**Comment by pxl-th** [comment]
Using glibc I can build successfully all the stack. But on musl it fails. Probably something is missing in rocm-clang wrapper. @jpsamaroo do you have an idea what is missing?

**Comment by pxl-th** [comment]
Or maybe @vchuravy has ideas what is missing...

**Comment by pxl-th** [comment]
These is the gist of the issue on `musl`:
```
ld.lld: error: cannot open crtbeginS.o: No such file or directory
ld.lld: error: unable to find library -lgcc
ld.lld: error: unable to find library -lgcc_s
ld.lld: error: cannot open crtendS.o: No such file or directory
```

All of these libraries and files do exist:

```
sandbox:/ # find . -name crtendS.o
./opt/x86_64-linux-musl/lib/gcc/x86_64-linux-musl/9.1.0/crtendS.o
sandbox:/ # find . -name libgcc.a
./opt/x86_64-linux-musl/lib/gcc/x86_64-linux-musl/9.1.0/libgcc.a
sandbox:/ # find . -name libgcc_s.so
./opt/x86_64-linux-musl/x86_64-linux-musl/lib64/libgcc_s.so
```

But the linker is not able to find them. Both the `gcc-toolchain` and `sysroot` are set:
- `--sysroot=/opt/${target}/${target}/sys-root`
- `--gcc-toolchain=/opt/${target}`

but my guess is that they are missing stuff for the musl...
`sysroot` directory for `musl` missing stuff that is present in `glibc` case:

- `musl`:
```
sandbox:/opt/x86_64-linux-musl/x86_64-linux-musl/sys-root # ls -l
total 8
drwxrwxr-x    2 root     root          4096 Jul  5 14:31 lib
drwxrwxr-x    1 root     root          4096 Jun 22 18:11 usr
```
- `glibc`:
```
sandbox:/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root # ls -l
total 24
drwxrwxr-x    2 root     root          4096 Jul  5 14:28 etc
drwxrwxr-x    2 root     root          4096 Jul  5 14:28 lib
drwxrwxr-x    2 root     root          4096 Jul  5 14:28 lib64
drwxrwxr-x    2 root     root          4096 Jul  5 14:28 sbin
drwxrwxr-x    1 root     root          4096 Jun 22 18:08 usr
drwxrwxr-x    3 root     root          4096 Jul  5 14:28 workspace
```

**Comment by pxl-th** [comment]
Maybe @giordano has some suggestions, that'd be really helpful...

**Review by jpsamaroo — APPROVED** [review]
LGTM!

**Comment by giordano** [comment]
License file is missing

**Comment by pxl-th** [comment]
> License file is missing

Done

**Pull request merged**
