### PR TITLE
Bumping to curl 7.78.0

### PR DESCRIPTION
**Pull request by bluesmoon**
Bump version due to security issues in older versions of curl

### CODE REVIEW

**Comment by Crghilardi** [comment]
Looking through the [release notes](https://github.com/curl/curl/pull/6372) there was the addition of using [libgsasl](https://www.gnu.org/software/gsasl/) which doesn't seem to be available in `Yggdrasil` currently. If I am reading the [configure script](https://github.com/curl/curl/blob/bfbde883af33397943df68a3ae01847a634d33bf/configure.ac#L1934-L1948) correctly it seems to be `yes` by default with a `--disable-libgsasl` flag added?

**Comment by bluesmoon** [comment]
Thanks for the feedback. This is my first time doing anything with BinaryBuilder

**Comment by Crghilardi** [comment]
Looks like there was another change that touched the `configure` file(https://github.com/curl/curl/pull/7176) in the release as well.

It looks like the flag for [metalink](https://github.com/curl/curl/blob/bfbde883af33397943df68a3ae01847a634d33bf/configure.ac#L1951-L1952) is set up to brute force error on anything containing the string `metalink`? We should be able to drop the entire `--without-libmetalink` from the flags now which is what they seem to do in all the updated CI scripts

**Comment by bluesmoon** [comment]
@Crghilardi thank you for the help.

**Comment by staticfloat** [comment]
Note that this is only one part of the process; after building this, Julia will still continue to ship with an older version, and Julia itself needs to be updated to use newer stdlibs.

https://github.com/JuliaLang/julia/blob/master/deps/Versions.make#L29
https://github.com/JuliaLang/julia/blob/master/stdlib/LibCURL_jll/Project.toml#L3

**Pull request merged**
