### PR TITLE
[XGBoost] update to v1.2

### PR DESCRIPTION
**Pull request by aviks**

### CODE REVIEW

**Comment by aviks** [comment]
Why can't musl find `<string>` ? 😞

**Comment by giordano** [comment]
That's a great question :confused:

**Comment by staticfloat** [comment]
This is confirmed a bug in the GCC 6+ x86_64-musl-linux shards.

**Comment by staticfloat** [comment]
Alright, I've confirmed that [this branch](https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/27) fixes the "musl can't find the C++ headers on GCC 6+" issue.  Unfortunately, it's going to take a little while for that PR to make its way into Yggdrasil, but we'll notify you when it does.

**Pull request merged**
