### PR TITLE
[Enzyme@9] Actually build new version

### PR DESCRIPTION
**Pull request by giordano**
CC: @vchuravy @wsmoses

### CODE REVIEW

**Comment by vchuravy** [comment]
urgh, right....

**Comment by wsmoses** [comment]
I am confused by this but presume new tarballs weren't actually being built without changing the file?

**Comment by vchuravy** [comment]
Yes, CI only triggers on touches to folders that contain a `build_tarball.jl`

**Comment by giordano** [comment]
I was going to touch the file in the other PR when I discovered that the PR wasn't there anymore :joy:

**Pull request merged**
