### PR TITLE
Build an ICU_jll

### PR DESCRIPTION
**Pull request by aviks**
Since apparently it's not been built yet.

### CODE REVIEW

**Comment by giordano** [comment]
There is #325

**Comment by giordano** [comment]
Ok, for Windows you'd need to take the rest of the changes in #325.  For macOS it's failing with
```
[14:09:43] /opt/x86_64-apple-darwin14/bin/x86_64-apple-darwin14-ranlib: archive member: uconvmsg/libuconvmsg.a(onvmsg_dat) size too large (archive member extends past the end of the file)
[14:09:43] /opt/x86_64-apple-darwin14/bin/x86_64-apple-darwin14-ar: internal ranlib command failed
```
For this error we used to use this trick https://github.com/JuliaPackaging/Yggdrasil/blob/60d4b2c811c774f50b814e322394f92491a629aa/I/ICU/build_tarballs.jl#L42-L45 but it doesn't work anymore after some changes to the compiler shards :disappointed:

**Comment by aviks** [comment]
For the `ranlib` error on the Mac, the internet seems to suggest that this is fixed in `XCode 4.4.1`. Is our version of mac tools older than that?

**Comment by aviks** [comment]
There is also a `x86_64-apple-darwin14-gcc-ar` ... is that what we want? However, running that seems to give me ` Cannot find plugin 'liblto_plugin.so'`

**Comment by giordano** [comment]
> However, running that seems to give me Cannot find plugin 'liblto_plugin.so'

https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/675

**Comment by aviks** [comment]
Ok. I'll wait for that to be fixed then, and come back to it after. Do you want to close this and keep #325? Or vice versa?

**Comment by giordano** [comment]
Maybe keep #325 and close this one?  The goal of the two pull requests is the same, I was just stuck with the macOS issues

**Comment by giordano** [comment]
I turned out https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/675 wasn't necessary after all and I could have fixed this ages ago :laughing:  I had to patch a file in the source code to remove a flag for `ar` which isn't supported by LLVM's `ar`: [`bb2252f` (#325)](https://github.com/JuliaPackaging/Yggdrasil/pull/325/commits/bb2252f04137c0160b1731237bf9f23fe6e8ecaa)

**Pull request closed without merging**
