### PR TITLE
[Reactant] Try build in aarch64-linux-gnu

### PR DESCRIPTION
**Pull request by mofeing**

### CODE REVIEW

**Comment by wsmoses** [comment]
whoops sorry thought was macos

**Comment by wsmoses** [comment]
```

[20:53:03]   external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/external/xla/xla/service/cpu/_objs/runtime_matmul_acl/runtime_matmul_acl.pic.d '-frandom-seed=bazel-out/k8-opt/bin/external/xla/xla/service/cpu/_objs/runtime_matmul_acl/runtime_matmul_acl.pic.o' '-DEIGEN_MAX_ALIGN_BYTES=64' -DEIGEN_ALLOW_UNALIGNED_SCALARS '-DEIGEN_USE_AVX512_GEMM_KERNELS=0' -DTENSORFLOW_USE_CUSTOM_CONTRACTION_KERNEL -DTENSORFLOW_USE_MKLDNN_CONTRACTION_KERNEL '-DBAZEL_CURRENT_REPOSITORY="xla"' -iquote external/xla -iquote bazel-out/k8-opt/bin/external/xla -iquote external/com_google_absl -iquote bazel-out/k8-opt/bin/external/com_google_absl -iquote external/eigen_archive -iquote bazel-out/k8-opt/bin/external/eigen_archive -iquote external/tsl -iquote bazel-out/k8-opt/bin/external/tsl -iquote external/onednn -iquote bazel-out/k8-opt/bin/external/onednn -iquote external/nsync -iquote bazel-out/k8-opt/bin/external/nsync -iquote external/ml_dtypes -iquote bazel-out/k8-opt/bin/external/ml_dtypes -Ibazel-out/k8-opt/bin/external/ml_dtypes/_virtual_includes/float8 -Ibazel-out/k8-opt/bin/external/ml_dtypes/_virtual_includes/intn -isystem external/eigen_archive -isystem bazel-out/k8-opt/bin/external/eigen_archive -isystem external/eigen_archive/mkl_include -isystem bazel-out/k8-opt/bin/external/eigen_archive/mkl_include -isystem external/onednn/include -isystem bazel-out/k8-opt/bin/external/onednn/include -isystem external/onednn/src -isystem bazel-out/k8-opt/bin/external/onednn/src -isystem external/onednn/src/common -isystem bazel-out/k8-opt/bin/external/onednn/src/common -isystem external/onednn/src/common/ittnotify -isystem bazel-out/k8-opt/bin/external/onednn/src/common/ittnotify -isystem external/onednn/src/cpu -isystem bazel-out/k8-opt/bin/external/onednn/src/cpu -isystem external/onednn/src/cpu/gemm -isystem bazel-out/k8-opt/bin/external/onednn/src/cpu/gemm -isystem external/onednn/src/cpu/x64/xbyak -isystem bazel-out/k8-opt/bin/external/onednn/src/cpu/x64/xbyak -isystem external/onednn/src/graph -isystem bazel-out/k8-opt/bin/external/onednn/src/graph -isystem external/nsync/public -isystem bazel-out/k8-opt/bin/external/nsync/public -isystem external/ml_dtypes -isystem bazel-out/k8-opt/bin/external/ml_dtypes -isystem external/ml_dtypes/ml_dtypes -isystem bazel-out/k8-opt/bin/external/ml_dtypes/ml_dtypes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIC -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections '-Wno-error=cpp' '-std=c++17' -w '-std=c++17' '-DTCP_USER_TIMEOUT=0' -DEIGEN_AVOID_STL_ARRAY -Iexternal/gemmlowp -Wno-sign-compare '-ftemplate-depth=900' -fno-exceptions '-DGOOGLE_CUDA=1' '-DTENSORFLOW_USE_NVCC=1' -DINTEL_MKL -DENABLE_ONEDNN_V3 -msse3 -pthread -c external/xla/xla/service/cpu/runtime_matmul_acl.cc -o bazel-out/k8-opt/bin/external/xla/xla/service/cpu/_objs/runtime_matmul_acl/runtime_matmul_acl.pic.o)
--
  | [20:53:03] # Configuration: 6fcb263b89c2a089e272fc7bc4589bb8e319060b7efea20371893a5897aac62c
  | [20:53:03] # Execution platform: @local_execution_config_platform//:platform
  | [20:53:03]
  | [20:53:03] Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
  | [20:53:03] aarch64-linux-gnu-gcc: error: unrecognized command-line option ‘-msse3’

```

so where ever msse3 comes from it should be disabled

**Comment by mofeing** [comment]
greping through xla repo suggests that this line is the responsible https://github.com/openxla/xla/blob/20d4636c743e53f070612d6b4c6ebd03b2b28bf5/xla/tsl/tsl.bzl#L334-L335 but don't know how to disable it. to me it seems like it's deciding based on host platform?

also, there's no platform configuration (no `platform` setting) in ReactantExtra's BUILD, so most probably we are making decision based on host platform for linux (unlike darwin)

**Comment by mofeing** [comment]
so the solutions passes through setting the flag `--cpu=aarch64` so that the correct configurable build attribute is set. but if I add it to `BAZEL_BUILD_FLAGS`, then I get the following error:

```
[13:32:20] ERROR: /workspace/bazel_root/097636303b1142f44508c1d8e3494e4b/external/local_config_cc/BUILD:47:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'aarch64'
[13:32:20] ERROR: /workspace/bazel_root/097636303b1142f44508c1d8e3494e4b/external/local_config_cc/BUILD:47:19: Analysis of target '@local_config_cc//:toolchain' failed
```

**Comment by mofeing** [comment]
I think we are missing the tool chain configuration for aarch64-linux from Yggdrasil in Reactant. I'm trying to fix it in the branch `reactant-aarch64-linux`.

**Comment by mofeing** [comment]
UPDATE: I think I managed to add Yggdrasil's aarch64-linux-gnu cross-compilation toolchain (first time I do sth in Bazel and kinda works)! Now I'm getting some usual cross-compile errors like headers not found and such.

**Comment by mofeing** [comment]
@wsmoses this error is weird because we add the paths where "features.h" to the toolchain

```
sandbox:${WORKSPACE}/srcdir/Reactant.jl/deps/ReactantExtra # find /opt/aarch64-linux-gnu/ -name features.h
/opt/aarch64-linux-gnu/aarch64-linux-gnu/include/c++/10.2.0/parallel/features.h
/opt/aarch64-linux-gnu/aarch64-linux-gnu/sys-root/usr/include/features.h
```

I added those paths in https://github.com/EnzymeAD/Reactant.jl/blob/bd89109872b59ed13f20be65da0b80e6a95056ab/deps/ReactantExtra/BUILD#L146-L155

the erroring call looks like Bazel is not adding the `-I` flags?

```
[23:57:52] ERROR: /workspace/bazel_root/097636303b1142f44508c1d8e3494e4b/external/llvm-project/llvm/BUILD.bazel:225:11: Compiling llvm/lib/Demangle/MicrosoftDemangleNodes.cpp failed: (Exit 1): gcc failed: error executing command (from target @llvm-project//llvm:Demangle) 
[23:57:52]   (cd /workspace/bazel_root/097636303b1142f44508c1d8e3494e4b/sandbox/linux-sandbox/11/execroot/__main__ && \
[23:57:52]   exec env - \
[23:57:52]     LD_LIBRARY_PATH=/usr/lib/csl-musl-x86_64:/usr/local/lib64:/usr/local/lib:/usr/lib64:/usr/lib:/lib64:/lib:/workspace/x86_64-linux-musl-cxx11/destdir/lib:/workspace/x86_64-linux-musl-cxx11/destdir/lib64:/opt/x86_64-linux-musl/x86_64-linux-musl/lib64:/opt/x86_64-linux-musl/x86_64-linux-musl/lib:/opt/aarch64-linux-gnu/aarch64-linux-gnu/lib64:/opt/aarch64-linux-gnu/aarch64-linux-gnu/lib:/workspace/destdir/lib64:/workspace/destdir/lib \
[23:57:52]     PATH=/workspace/srcdir/Reactant.jl/deps/ReactantExtra/.local/bin:/workspace/srcdir/Reactant.jl/deps/ReactantExtra/.local/bin:/opt/bin/aarch64-linux-gnu-libgfortran5-cxx11-gpu+none-mode+opt:/opt/aarch64-linux-gnu/bin:/opt/bin/x86_64-linux-musl-cxx11:/opt/x86_64-linux-musl/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/workspace/x86_64-linux-musl-cxx11/destdir/bin:/workspace/destdir/bin \
[23:57:52]     PWD=/proc/self/cwd \
[23:57:52]     TEMP=/workspace/srcdir/Reactant.jl/deps/ReactantExtra/.tmp \
[23:57:52]     TMP=/workspace/srcdir/Reactant.jl/deps/ReactantExtra/.tmp \
[23:57:52]     TMPDIR=/workspace/srcdir/Reactant.jl/deps/ReactantExtra/.tmp \
[23:57:52]   /opt/bin/aarch64-linux-gnu-libgfortran5-cxx11-gpu+none-mode+opt/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/aarch64-opt/bin/external/llvm-project/llvm/_objs/Demangle/MicrosoftDemangleNodes.pic.d '-frandom-seed=bazel-out/aarch64-opt/bin/external/llvm-project/llvm/_objs/Demangle/MicrosoftDemangleNodes.pic.o' -fPIC '-DLLVM_ON_UNIX=1' '-DNO_HAVE_BACKTRACE=0' '-DBACKTRACE_HEADER=<execinfo.h>' '-DLTDL_SHLIB_EXT=".so"' '-DLLVM_PLUGIN_EXT=".so"' '-DLLVM_ENABLE_THREADS=0' '-DHAVE_DEREGISTER_FRAME=1' '-DHAVE_LIBPTHREAD=1' '-DFAKE_HAVE_PTHREAD_GETNAME_NP=0' '-DHAVE_PTHREAD_H=1' '-DFAKE_HAVE_PTHREAD_SETNAME_NP=0' '-DHAVE_REGISTER_FRAME=1' '-DHAVE_SETENV_R=1' '-DHAVE_STRERROR_R=1' '-DHAVE_SYSEXITS_H=1' '-DHAVE_UNISTD_H=1' -D_GNU_SOURCE '-DDONT_HAVE_ANY_MALLINFO=0' '-DHAVE_SBRK=1' '-DHAVE_STRUCT_STAT_ST_MTIM_TV_NSEC=1' -DHAVE_BUILTIN_THREAD_POINTER '-DLLVM_NATIVE_ARCH="AArch64"' '-DLLVM_NATIVE_ASMPARSER=LLVMInitializeAArch64AsmParser' '-DLLVM_NATIVE_ASMPRINTER=LLVMInitializeAArch64AsmPrinter' '-DLLVM_NATIVE_DISASSEMBLER=LLVMInitializeAArch64Disassembler' '-DLLVM_NATIVE_TARGET=LLVMInitializeAArch64Target' '-DLLVM_NATIVE_TARGETINFO=LLVMInitializeAArch64TargetInfo' '-DLLVM_NATIVE_TARGETMC=LLVMInitializeAArch64TargetMC' '-DLLVM_NATIVE_TARGETMCA=LLVMInitializeAArch64TargetMCA' '-DLLVM_HOST_TRIPLE="aarch64-unknown-linux-gnu"' '-DLLVM_DEFAULT_TARGET_TRIPLE="aarch64-unknown-linux-gnu"' '-DLLVM_VERSION_MAJOR=20' '-DLLVM_VERSION_MINOR=0' '-DLLVM_VERSION_PATCH=0' '-DLLVM_VERSION_STRING="20.0.0git"' -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS '-DLLVM_HAS_AArch64_TARGET=1' '-DLLVM_HAS_AMDGPU_TARGET=1' '-DLLVM_HAS_ARM_TARGET=1' '-DLLVM_HAS_NVPTX_TARGET=1' '-DLLVM_HAS_PowerPC_TARGET=1' '-DLLVM_HAS_RISCV_TARGET=1' '-DLLVM_HAS_SystemZ_TARGET=1' '-DLLVM_HAS_X86_TARGET=1' '-DBAZEL_CURRENT_REPOSITORY="llvm-project"' -iquote external/llvm-project -iquote bazel-out/aarch64-opt/bin/external/llvm-project -isystem external/llvm-project/llvm/include -isystem bazel-out/aarch64-opt/bin/external/llvm-project/llvm/include '-Wno-error=cpp' '-D__ARM_FEATURE_AES=1' '-D__ARM_NEON=1' '-D__ARM_FEATURE_SHA2=1' '-DDNNL_ARCH_GENERIC=1' '-std=c++17' -w '-std=c++17' '-DTCP_USER_TIMEOUT=0' '--sysroot=/opt/aarch64-linux-gnu' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -Wno-unused-command-line-argument -Wno-gnu-offsetof-extensions -c external/llvm-project/llvm/lib/Demangle/MicrosoftDemangleNodes.cpp -o bazel-out/aarch64-opt/bin/external/llvm-project/llvm/_objs/Demangle/MicrosoftDemangleNodes.pic.o)
```

**Comment by mofeing** [comment]
the only thing not working right now is `aarch64-linux-gnu` with CUDA, most probably because it's using GCC and we should be using clang

let's merge it like it is now, and later fix that after we clean the toolchain definition

**Comment by wsmoses** [comment]
yeah that's almost certainly the thing

**Pull request merged**
