### PR TITLE
libclangex: Add runtime dependency

### PR DESCRIPTION
**Pull request by Gnimuc**

### CODE REVIEW

**Comment by Gnimuc** [comment]
```
[ Info: Building for x86_64-linux-gnu-cxx11-julia_version+1.7.0
    Updating registry at `/depot/registries/General`
[ Info: Cached repository found in /depot/downloads/libclangex.git
[ Info: Cloning libclangex.git to libclangex...
   Resolving package versions...
julia version requirement for package `LLVM_full_jll [a3ccf953]` not satisfied
julia version requirement for package `LLVM_full_jll [a3ccf953]` not satisfied
julia version requirement for package `LLVM_full_jll [a3ccf953]` not satisfied
julia version requirement for package `LLVM_full_jll [a3ccf953]` not satisfied
ERROR: LoadError: Unsatisfiable requirements detected for package libLLVM_jll [8f36deef]:
 libLLVM_jll [8f36deef] log:
 ├─possible versions are: 11.0.1 or uninstalled
 └─found to have no compatible versions left with Clang_jll [0ee61d77]
   └─Clang_jll [0ee61d77] log:
     ├─possible versions are: 9.0.1-12.0.0 or uninstalled
     └─restricted to versions 12.0.0 by an explicit requirement, leaving only versions 12.0.0
```

I don't know why `libLLVM_jll` limits the LLVM version to 11.

**Comment by vchuravy** [comment]
@staticfloat @giordano I think we need your help figuring out why we can't declare `Clang_jll` as a runtime dependency

**Comment by Gnimuc** [comment]
@vchuravy I found another problem on Windows. There is only a `libclang-cpp.dll.a` in the lib folder, so libclangex.dll cannot be dlopen-ed due to the missing dll in the bin folder.

**Comment by vchuravy** [comment]
I thought we included https://reviews.llvm.org/D73156, but I couldn't quickly find it.

**Comment by Gnimuc** [comment]
It's in LLVM12, but not LLVM11. 😵

**Comment by Gnimuc** [comment]
As Julia-1.7 with LLVM12 is about to release, maybe I should drop 1.6(LLVM11) and directly target 1.7(LLVM12).

**Comment by vchuravy** [comment]
We can backport that patch to fix the clang build

**Comment by Gnimuc** [comment]
For future reference, [this workaround](https://github.com/Gnimuc/ClangCompiler.jl/blob/6c0da078f9dd1fb13bfa0e3ffa78ec398ed68abd/src/ClangCompiler.jl#L6-L9) won't work as well:

```
ulia> using ClangCompiler
[ Info: Precompiling ClangCompiler [06fc9500-c033-43bc-8ca2-e20da63309d9]
ERROR: LoadError: InitError: could not load library "/Users/gnimuc/.julia/artifacts/fdaa481e8447a90688fc49a49f5b41de061d0fe8/lib/libclangex.dylib"
dlopen(/Users/gnimuc/.julia/artifacts/fdaa481e8447a90688fc49a49f5b41de061d0fe8/lib/libclangex.dylib, 1): Library not loaded: @rpath/libclang-cpp.dylib
  Referenced from: /Users/gnimuc/.julia/artifacts/fdaa481e8447a90688fc49a49f5b41de061d0fe8/lib/libclangex.dylib
  Reason: image not found
Stacktrace:
  [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
    @ Base.Libc.Libdl ./libdl.jl:117
  [2] dlopen(s::String, flags::UInt32)
    @ Base.Libc.Libdl ./libdl.jl:117
  [3] macro expansion
    @ ~/.julia/packages/JLLWrappers/bkwIo/src/products/library_generators.jl:54 [inlined]
  [4] __init__()
    @ libclangex_jll ~/.julia/packages/libclangex_jll/h0ISl/src/wrappers/x86_64-apple-darwin-julia_version+1.7.0.jl:8
  [5] _include_from_serialized(path::String, depmods::Vector{Any})
    @ Base ./loading.jl:768
  [6] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base ./loading.jl:854
  [7] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1097
  [8] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1013
  [9] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:997
 [10] include
    @ ./Base.jl:417 [inlined]
 [11] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base ./loading.jl:1318
 [12] top-level scope
    @ none:1
 [13] eval
    @ ./boot.jl:373 [inlined]
 [14] eval(x::Expr)
    @ Base.MainInclude ./client.jl:453
 [15] top-level scope
    @ none:1
during initialization of module libclangex_jll
in expression starting at /Users/gnimuc/.julia/dev/ClangCompiler/src/ClangCompiler.jl:1
ERROR: Failed to precompile ClangCompiler [06fc9500-c033-43bc-8ca2-e20da63309d9] to /Users/gnimuc/.julia/compiled/v1.7/ClangCompiler/jl_BoYJwB.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, ignore_loaded_modules::Bool)
   @ Base ./loading.jl:1466
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base ./loading.jl:1410
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1120
 [5] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:1013
 [6] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:997
```

**Comment by vchuravy** [comment]
@Gnimuc I assume this is still block on Clang.jl on 1.6 not having libclang-cpp?

**Pull request closed without merging**
