### PR TITLE
[FastTransforms] v0.3.3

### PR DESCRIPTION
**Pull request by MikaelSlevinsky**
Support all supported platforms.

Drops `expand_gfortran_versions`.

### CODE REVIEW

**Comment by MikaelSlevinsky** [comment]
Hey so earlier in v0.3.2 I was using -march=native on the buildbots to build as much Intel SIMD as they support. The library itself dispatches on CPUID at runtime. (For more context, the arch spec happened in the Make.inc to define `simd := $(shell $(CC) -march=native -E -v - </dev/null 2>&1 | grep cc1)`, then compiler flags were defined based on this result.) 

But on BinaryBuilder v0.2.5#master, it appears that using -march=native throws an error and exits the build. Is there a way for me to restore the previous functionality?

**Comment by MikaelSlevinsky** [comment]
Well I avoided the issue by requesting a preferred version of GCC (since 4.8.5 didn't recognize =mavx512f), but still think it's kinda harsh to throw an error on using -march.

**Comment by giordano** [comment]
> but still think it's kinda harsh to throw an error on using -march.

It's not harsh, it's to avoid using stuff like `-march=native` or `-march=skylake-avx512` which would make the libraries unusable on some platforms, that's what is harsh.  It looks like this library uses cpuid instructions, so it's not clear to me why it needs hints like `-march` or `-mavx` or `-mfma`.

Related to this, we're working to make it possible to build packages for a set of predefined microarchitectures (well, this feature is actually already there), and users will get automatically installed the package corresponding to the local microarchitecture.  This latter feature is still missing, so that using multi-microarchitecture packages can't really be used yet, hopefully it'll land for Julia v1.6

**Comment by MikaelSlevinsky** [comment]
It needs those flags to compile versions of functions with the so-labeled SIMD, that then get dispatched by cpuid.

The extended platform addition looks interesting.

**Comment by MikaelSlevinsky** [comment]
I understand the danger of using march=native on an advanced cross-compiler to actually compile a library (that would then be unusable on previous architectures), but I was using it in a diagnostic sense to extract all available flags.

**Pull request merged**
