### PR TITLE
Add builder for elfutils

### PR DESCRIPTION
**Pull request by giordano**
Not tested at all, requires a package for XZ (the builder is already here, though)

### CODE REVIEW

**Comment by staticfloat** [comment]
https://github.com/JuliaBinaryWrappers/XZ_jll.jl/releases

**Comment by staticfloat** [comment]
Hmmmm....

```
#error "<fts.h> cannot be used with -D_FILE_OFFSET_BITS==64"
```

**Comment by giordano** [comment]
> Not tested at all

:upside_down_face:

**Comment by staticfloat** [comment]
Okay, figured it out.  We shouldn't override `CFLAGS`.

**Comment by staticfloat** [comment]
I had to disable everything except glibc Linux.  I don't think any other platform will work without some other deps.

https://github.com/JuliaRegistries/General/pull/3927

**Pull request merged**
