### PR TITLE
[ROCmDeviceLibs] Add 4.0.0

### PR DESCRIPTION
**Pull request by jpsamaroo**

### CODE REVIEW

**Comment by jpsamaroo** [comment]
It looks like the x86_64-linux-gnu error is because of a too-old glibc?

**Comment by vchuravy** [comment]
No you are linking against the `musl` system LLVM, instead of providing it as a dependency.

**Comment by vchuravy** [comment]
Since you are generating a bitcode file you should use `LLVM_full` as a HostDependency and match that to the Julia version that will consume that bitcode file.
Also do we care about the host? Since these are device libs shouldn't generating one set of them be enough?

**Comment by jpsamaroo** [comment]
It seems like we didn't actually need any of the tools from `LLVM_full_jll`, CMake just wants the imported .cmake files to be consistent. So the latest push just temporarily symlinks the clang tools to make CMake happy.

**Comment by jpsamaroo** [comment]
> Also do we care about the host? Since these are device libs shouldn't generating one set of them be enough?

Correct, they should all generally be identical (and if there is any host-specific code, we don't use it in downstream packages).

**Comment by jpsamaroo** [comment]
@giordano is this good to merge?

**Comment by giordano** [comment]
I think so, if it works, but it's still draft :smile:

**Pull request merged**
