### PR TITLE
OSQP: update to 0.6.2

### PR DESCRIPTION
**Pull request by ViralBShah**

### CODE REVIEW

**Comment by ViralBShah** [comment]
The build looks for MKL Pardiso, which makes me wonder if we should have MKL_jll as a dependency.

**Comment by ViralBShah** [comment]
Doesn't seem like Pardiso is actually needed. Wasn't used before in the upstream binaries either (at least on mac).

**Comment by giordano** [comment]
My conclusion in https://github.com/JuliaPackaging/Yggdrasil/pull/846#issuecomment-614230042 was that MKL can be automatically dlopened at runtime.  No idea if anything changed since then

**Comment by ViralBShah** [comment]
I see. So it will automatically get downloaded if needed?

**Comment by giordano** [comment]
Not automatically downloaded, but if the user has MKL available somehow, it's automatically used.

**Comment by ViralBShah** [comment]
Ok we'll see what OSQP.jll authors say on the PR that is switching to BB.

**Comment by giordano** [comment]
It looks like Pardiso is still `dlopen`ed at runtime, instead of using dynamic linking: https://github.com/oxfordcontrol/osqp/blob/bf4a4ae7d25f511084a9b1e12c27442464be6739/lin_sys/direct/pardiso/pardiso_loader.c#L67-L72.  So adding `MKL_jll` at build-time shouldn't make any difference at all.

**Pull request merged**
