### PR TITLE
Create replace_includes.sh

### PR DESCRIPTION
**Pull request by bramtayl**

### CODE REVIEW

**Comment by staticfloat** [comment]
I updated the script to do things like not automatically put `.h` on the end (so that you can update headers like `#include <string>`) and to not throw errors if one of the patterns includes a `/` (since you were using that as the delimiter for the regex in the `sed` command).

Next, you need to add it to this list: https://github.com/JuliaPackaging/Yggdrasil/blob/master/0_RootFS/Rootfs/build_tarballs.jl#L155-L169

**Comment by bramtayl** [comment]
Ok! Thanks for the help!

**Comment by staticfloat** [comment]
LGTM!

**Comment by staticfloat** [comment]
This will be included in the next rootfs, whenever we build it!

**Comment by bramtayl** [comment]
Cool! How often does that happen?

**Comment by staticfloat** [comment]
Usually once every couple of months.  We let some changes build up, then we generate a new rootfs.

**Comment by bramtayl** [comment]
Thanks. Can you ping me when that happens?

**Pull request merged**
