### PR TITLE
New recipe: Clipper2

### PR DESCRIPTION
**Pull request by aviks**
Windows does not work, but keeping it enabled for now to see if anyone has any ideas. 

This is a C++ library, but presumably does not do any string manipulation. The Wizard did not seem to complain, so do I need `expand_cxx_abi` for this?

### CODE REVIEW

**Comment by giordano** [comment]
> This is a C++ library, but presumably does not do any string manipulation. The Wizard did not seem to complain, so do I need expand_cxx_abi for this?

No, if the auditor doesn't complain about the string ABI there is no need to do anything.

**Comment by giordano** [comment]
For Windows, https://stackoverflow.com/a/27586530/2442087 seems relevant for the error
```
[16:08:21] /opt/bin/x86_64-w64-mingw32-libgfortran5-cxx11/x86_64-w64-mingw32-g++ --sysroot=/opt/x86_64-w64-mingw32/x86_64-w64-mingw32/sys-root/ -DClipper2Zutils_EXPORTS -DUSINGZ @CMakeFiles/Clipper2Zutils.dir/includes_CXX.rsp -O3 -DNDEBUG -std=c++17 -MD -MT CMakeFiles/Clipper2Zutils.dir/Utils/ClipFileLoad.cpp.obj -MF CMakeFiles/Clipper2Zutils.dir/Utils/ClipFileLoad.cpp.obj.d -o CMakeFiles/Clipper2Zutils.dir/Utils/ClipFileLoad.cpp.obj -c /workspace/srcdir/Clipper2/CPP/Utils/ClipFileLoad.cpp
[16:08:22] In file included from /workspace/srcdir/Clipper2/CPP/Utils/ClipFileLoad.cpp:5:
[16:08:22] /workspace/srcdir/Clipper2/CPP/Utils/ClipFileLoad.h: In function ‘bool FileExists(const string&)’:
[16:08:22] /workspace/srcdir/Clipper2/CPP/Utils/ClipFileLoad.h:20:37: error: no matching function for call to ‘stat::stat(const char*, stat*)’
[16:08:22]    20 |   return (stat(name.c_str(), &buffer) == 0);
[16:08:22]       |                                     ^
```
?

**Comment by aviks** [comment]
OK, this is good to go from my side. @Cormullion might want to check if this looks reasonable.

**Comment by cormullion** [comment]
Well we'll have a go and see. I think making a new Julia package would be best, rather than update the older one:

https://github.com/JuliaGeometry/Clipper.jl

I'm hoping some JuliaGeometry folks will be able to assist... 😉

**Comment by giordano** [comment]
CC @sjkelly

**Comment by sjkelly** [comment]
Yes, we probably want to make a new Clipper2.jl package since the API is quite different. Thanks @aviks !

**Comment by sjkelly** [comment]
xref: https://github.com/JuliaGeometry/Clipper.jl/issues/49

**Comment by jebej** [comment]
There is an unofficial library offering C bindings here: https://github.com/geoffder/clipper2c

**Comment by ferrolho** [comment]
I have opened https://github.com/JuliaPackaging/Yggdrasil/pull/7093 to update Clipper2 from `v1.0.4` to the latest available version, `v1.2.2`. Is there anything else required besides opening the PR?

Also, what is the purpose for `sharedlib.patch`? Do we need it still?

**Pull request merged**
