### PR TITLE
patch official `gmsh.jl`

### PR DESCRIPTION
**Pull request by xue-cheng**

### CODE REVIEW

**Comment by giordano** [comment]
I guess this is related to #2502?

**Comment by xue-cheng** [comment]
@giordano  Yes, it is. I didn't see #2502 when I encountered that problem. The official SDK must use the version number to distinguish different dynamic link libraries in the system, but the JLL package load different Artifacts. Therefore, modifying the API file after build will not cause side effects and reduce the need for maintenance.

**Comment by giordano** [comment]
Thanks!

**Comment by giordano** [comment]
@xue-cheng I realised only after merging this PR that the backup file remains in the tarball (hence I also blocked registration: https://github.com/JuliaRegistries/General/pull/29689).  I think it'll be better to remove it (or simply edit the file with `sed -i`).  Any particular reason why you want to keep it around?

**Comment by xue-cheng** [comment]
@giordano I keep the original file habitually. This file should not cause any adverse effects except a little increase in the size of the tarball.

**Pull request merged**
