### PR TITLE
Add libjulia 1.3.1

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
There is no libLLVM_jll 6.0.1 which complicates this, I guess...

**Comment by fingolfin** [comment]
I might try using `LLVM_jll.jl` 6.0.1

**Comment by fingolfin** [comment]
Looking pretty good!

Anybody got an idea what this might be about ([from here](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=6537&view=logs&j=07d84a0c-7f1d-52db-2df1-daa71fdff229&t=1e7aeb38-840e-50bb-1bfb-7704b54c9b27&l=3339)):
```
 /opt/powerpc64le-linux-gnu/bin/../powerpc64le-linux-gnu/sys-root/usr/local/lib/libLLVM-6.0.so: undefined reference to `__tls_get_addr_opt@GLIBC_2.22'
```

**Comment by giordano** [comment]
Something like https://github.com/ldc-developers/druntime/commit/2f05aa1c0cfb1d521505e82114ecf67830c6681a
```diff
diff --git a/src/rt/sections_elf_shared.d b/src/rt/sections_elf_shared.d
index df003d80c8..4076953bc4 100644
--- a/src/rt/sections_elf_shared.d
+++ b/src/rt/sections_elf_shared.d
@@ -910,7 +910,12 @@ struct tls_index
 
 version(LDC)
 {
-    version(PPC64)
+    version(PPC)
+    {
+        extern(C) void* __tls_get_addr_opt(tls_index* ti);
+        alias __tls_get_addr = __tls_get_addr_opt;
+    }
+    else version(PPC64)
     {
         extern(C) void* __tls_get_addr_opt(tls_index* ti);
         alias __tls_get_addr = __tls_get_addr_opt;
```
might work.  @vchuravy better ideas?

**Comment by vchuravy** [comment]
We use Glibc 2.17 for PPC , this looks like LLVM at that point was build against 2.22. So likely we need to rebuild LLVM 6.

**Comment by giordano** [comment]
That's a much more sensible observation 😅

**Comment by fingolfin** [comment]
Ok. I guess one could also try to create a libLLVM 6.0.1 instead? Not sure how much extra work that'd take, though?

**Comment by vchuravy** [comment]
You can also skip PPC support for 1.3

**Comment by fingolfin** [comment]
I will skip the PowerPC builds then (although it's a bit of a pity, as it complicates the work on packages like libcxxwrap-julia if one wants to support as many platforms as possible: one has to very carefully match the platform selection in the various libjulia_jll variants.

**Comment by fingolfin** [comment]
Can this be merged now? While I hope that perhaps we can eventually add back the powerpc support, this is stalled for the moment (see PR #1914), so it'd be nice to not hold this up for the sake of a fringe (no offense intended) platform. Unless you think it'll be "easy" to resolve the LLVM 6.0.1 build issue on macOS?

**Pull request merged**
