### PR TITLE
[GDAL] Upgraded to 3.1.3

### PR DESCRIPTION
**Pull request by evetion**

### CODE REVIEW

**Comment by evetion** [comment]
Well, always interesting to see the pipelines, I'd say:
- roughly a quarter works
- roughly a quarter fails on downloading, hash mismatch
- roughly a quarter fails on patching libproj
- roughly a quarter fails on linking libpng (probably mismatching versions)

**Comment by giordano** [comment]
After kicking the jobs a few times, the hash mismatches issues are gone.  We're still investigating those issues, they're a bit annoying

**Comment by giordano** [comment]
See https://github.com/JuliaPackaging/Yggdrasil/pull/1674#issuecomment-714141133 and following messages

**Comment by fingolfin** [comment]
Since https://github.com/JuliaPackaging/Yggdrasil/pull/2311 was merged, can this be closed now?

**Pull request closed without merging**
