### PR TITLE
Update SuiteSparse GPU build.

### PR DESCRIPTION
**Pull request by maleadt**
@ViralBShah I removed several components that failed to build (e.g. Slip_LU), making it consistent with the main SuiteSparse build. I'm also not sure why this version included METIS? I couldn't find anything about SuiteSparse+CUDA and any METIS requirements.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Metis is nice to have but is not in default build as it is an extra library. I set this up as the "all bells and whistles" version.

@Wimmerer

**Comment by Wimmerer** [comment]
Let me know if you want to hand it off I can work on it this evening. I've got a few similar libs to build and I'll copy this structure.

**Comment by ViralBShah** [comment]
If suitesparse, should we just work on this build here and enable everything?

**Comment by ViralBShah** [comment]
Better option may be to have this package as building only libraries that are GPU compatible and a separate suitesparse that has everything else. Thoughts?

**Comment by ViralBShah** [comment]
What other libraries are you building? Does it make sense to unbundle the suitesparse libraries in Yggdrasil, so we have a separate set of packages for all the different libraries? I'll try to get this one merged.

**Comment by Wimmerer** [comment]
I'd like to unbundle at some point yes. We could do that now or later it doesn't necessarily matter immediately.

Although, aren't we duplicating builds here? Can this coexist with the existing JLL without clobbering?

Several sparse and dense libraries I recall were blocked: Gingko, GraphBLAST from Aydin, MAGMA and a few other ICL libs were also blocked on CUDA. SuiteSparseGraphBLAS_GPU is in pre-alpha also.

A bunch of one off libraries that I may just port to CUDA.jl (Adaptive CSR and such).

Kokkos CUDA executor library maybe?

**Comment by ViralBShah** [comment]
Hmm, let me see if I can just have these libraries depend on the ones that are in `SuiteSparse_jll`.

**Comment by ViralBShah** [comment]
One challenge here is that the libraries built here have the same names as the ones in SuiteSparse. So libsuitesparse_config, cholmod and spqr would be better off with some `_gpu` suffixes in their names.

**Comment by ViralBShah** [comment]
Don't see any such option to rename gpu libs on a quick scan. Does the current build look ok to you?

**Pull request merged**
