### PR TITLE
[Qt5] Add Qt5Wayland

### LINKED ISSUE #3551: Wayland support in `Qt5Base_jll`
Currently, on Wayland, the Qt windows use XWayland

Refer to https://github.com/sciapp/gr/issues/141 for more details

### PR DESCRIPTION
**Pull request by barche**
WIP attempt to fix #3551

### CODE REVIEW

**Comment by barche** [comment]
> It isn't clear to me how this solves #3551. Does the user need to install this package?

The package needs to be installed and its plugins/platforms dir added to the list of platform plugin directories (don't know how yet). But having just compared the contents of that directory against what I have on my Arch Linux system, I think we are missing at least `libqwayland-egl.so` for this to be useful (currently only the `libqwayland-generic.so` platform module is there).

**Comment by mkitti** [comment]
Could we revisit this?

**Comment by barche** [comment]
I'm not sure how to test this. I just tried Plasma on Wayland on my Arch installation, and on a fresh Plots installation the GKS Qt window shows up as normal after spitting the warning

```
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
```

I assume it's falling back to X11 emulation, and checking that the warning stays away is a good test?

**Comment by mkitti** [comment]
Here's the original issue:
https://github.com/sciapp/gr/issues/141

**Comment by mkitti** [comment]
Oh, hmm..

**Comment by barche** [comment]
Oh, this was accidental, I thought something went wrong with my Yggdrasil fork so I recreated it.

**Pull request closed without merging**
