### PR TITLE
[libcxxwrap_julia] rebuild for Julia 1.10 support

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
@giordano @benlorenz @staticfloat hurhm, getting this now:
```
ERROR: LoadError: KeyError: key UUID("a83860b7-747b-57cf-bf1f-3e79990d037f") not found
```
which of course comes from
```
# See https://github.com/JuliaLang/Pkg.jl/issues/2942
# Once this Pkg issue is resolved, this must be removed
uuid = Base.UUID("a83860b7-747b-57cf-bf1f-3e79990d037f")
delete!(Pkg.Types.get_last_stdlibs(v"1.6.3"), uuid)
```
This worked like a week ago. Any ideas what might be going on here?

**Comment by fingolfin** [comment]
Nevermind, it seems going back to julia_version `1.6.3` instead of `1.6` fixed it... maybe...

**Comment by barche** [comment]
I'm about to do a libcxxwrap bug fix release, not sure if it makes sense to postpone this one a little so that can get in

**Comment by fingolfin** [comment]
@barche I'd say depends on what "about to" means? If it is today, let's wait (and I assume you'll add the changes from this PR into your PR, perfectly fine). Also, if it is a ABI breaking change (meaning that afterwards other packages using cxxwrap will have to be rebuilt once again), let's wait.

Otherwise, my personal opinion: Let's not wait, because a ton of other JLL needs to be updated and are waiting for this PR to be merged.

**Comment by barche** [comment]
I agree, let's merge 😉

**Pull request merged**
