### PR TITLE
Add MPICH. Switch to https

### PR DESCRIPTION
**Pull request by ViralBShah**
Provide MPICH binaries based on discussion in https://github.com/JuliaParallel/MPI.jl/issues/328

### CODE REVIEW

**Comment by ViralBShah** [comment]
Same issue on macos as with openmpi with hashes and some case-sensitive stuff. :-(

**Comment by simonbyrne** [comment]
What was the issue with Windows?

**Comment by ViralBShah** [comment]
I can't quite remember. Probably didn't just work out of the box. Should we trigger a build and find out?

**Comment by ViralBShah** [comment]
Some POSIX issues: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=680&view=logs&jobId=d5d950e3-ce86-5057-1621-1b144c91855b&j=d5d950e3-ce86-5057-1621-1b144c91855b&t=87ac97cb-12a2-5bd9-c093-6e12d62cca68

IIRC, maybe you need Microsoft compilers. I didn't dig deeper at the time.

**Comment by ViralBShah** [comment]
Reading the install guide, cygwin is supported. So perhaps some issue with cross-compiling for windows.

**Comment by simonbyrne** [comment]
The issue was:
```
[02:42:07] configure: WARNING: POSIX timer requires definitions in time.h
[02:42:07] configure: error: Cannot find the definition of CLOCK_REALTIME for the POSIX timer
[02:42:07] configure: error: MPL configure failed
[02:42:07]  ---> ./configure --prefix=$prefix --host=$target --enable-shared=yes --enable-static=no
[02:42:07] Previous command exited with 1
[02:42:07] Saving srcdir due to previous error...
```

@staticfloat @giordano any idea how one might fix this?

**Comment by staticfloat** [comment]
You can [pass `--enable-timer-type=name` to `./configure`](https://github.com/pmodels/mpich/blob/a67f0216d76bb6c17fe93cc6f028c1c2de1603c2/src/mpl/configure.ac#L246); instead of using `clock_gettime` (which apparently doesn't work on mingw32) we can try `gettimeofday` instead.

**Comment by dpo** [comment]
Was there a specific reason why Fortran is explicitly disabled here? That prevents building other formulae such as SCALAPACK and MUMPS.

**Comment by ViralBShah** [comment]
No particular reason. I think I just wanted to get something reliably building without worrying about the Fortran dependencies.

**Pull request merged**
