### PR TITLE
[GR] Depend on Qt6 instead of Qt5

### PR DESCRIPTION
**Pull request by barche**
This is basically intended to replace https://github.com/jheinen/GR.jl/pull/518

@giordano Is a simple rebuild OK when the dependencies change, or do we need to bump the version?

CC @jheinen

### CODE REVIEW

**Comment by giordano** [comment]
I think you have to change version number, otherwise the removed dependency doesn't actually get removed, which is a mess

**Comment by barche** [comment]
@jheinen Do you know if a new gr release is far off? It would be preferable to keep the JLL and upstream version in sync, I think, so we could postpone this change until it is released.

**Comment by jheinen** [comment]
I'm currently out of office. But we will probably tag a new releasee next week.

**Comment by barche** [comment]
OK, there's no rush for this, I'll wait for the next release of gr.

**Comment by barche** [comment]
Unfortunately this will have to wait until GR 0.72.9 now, since .8 was just merged with still Qt5. Unless we accept a version number divergence, but there is no rush for me. We just need to remember to move to Qt6 on the next release.

**Comment by jheinen** [comment]
0.72.8 was a bugfix release. Will merge #7016 with 0.72.9 (next week) - or should we update to 0.73.0?

**Comment by barche** [comment]
I don't think 0.73 is needed, any version bump should be fine. Maybe to be sure we should both test on Qt6 though, I can add a JLL on my test registry.

**Comment by barche** [comment]
I have made some updates, but of course this should only be merged once 0.72.9 is out, converting to draft to be sure.

**Comment by ViralBShah** [comment]
Should this be closed in favour of #7059

**Comment by ViralBShah** [comment]
No big deal...

**Pull request closed without merging**
