### PR TITLE
MUMPS_seq@5: use libblastrampoline

### PR DESCRIPTION
**Pull request by dpo**

### CODE REVIEW

**Comment by dpo** [comment]
I would appreciate some guidance on how lbt is meant to be used here. If I understood well, it doesn't forward LAPACK symbols. How should we handle that?

**Comment by ViralBShah** [comment]
It does forward LAPACK symbols also. LBT currently only works with Julia 1.7, although I hope to be able to figure out how to initialize it for 1.6 as well.

@giordano Is just using Julia 1.7 sufficient for LBT on BB?

**Comment by giordano** [comment]
Julia v1.7 should be enough for ILP64 on 64-bit systems, because we always offer a default ILP64 BLAS.  With LP64, like here, I think we still need to make somewhat sure there is an appropriate BLAS available.  As I mentioned on Slack, these are uncharted territories, so someone will need to experiment a bit.

**Comment by ViralBShah** [comment]
Ah - this would be a mess. Since LBT will forward to either the built in openblas or to MKL - both ILP64, and the LP64 MKL cannot co-exist. The only option is OpenBLAS32. Alternately, MUMPS should be built as ILP64.

**Comment by ViralBShah** [comment]
The new MKL will have a way to mangle ILP64 symbols like we do in openblas, at which point we could also support LP64 in LBT.

**Comment by giordano** [comment]
Libblastrampoline already supports LP64, the only problem is that 64-bit Julia doesn't come with a default LP64 BLAS, so we need a mechanism to always ensure there is one

**Comment by ViralBShah** [comment]
Right. Also, MKL uses the same symbol names for ILP64 and LP64 for now - so there isn't much value to using LBT to switch LP64 at the moment - one can only directly link to OpenBLAS32.

**Comment by dpo** [comment]
Can't we use Apple Accelerate?

**Comment by dpo** [comment]
> Alternately, MUMPS should be built as ILP64.

That would screw up IPOPT.

**Comment by ViralBShah** [comment]
Apple Accelerate needs work because their lapack is 10 years out of date and won't pass out tests. We have to use our own LAPACK in BB with ILP64 name mangling.

**Comment by ViralBShah** [comment]
Can't we build IPOPT with 64 bit BLAS today?

**Comment by dpo** [comment]
Don't believe so.

**Comment by dpo** [comment]
> Apple Accelerate needs work because their lapack is 10 years out of date and won't pass out tests.

I opened an issue at Apple about that in 2017 and never heard back. Still, you can use Accelerate with Ipopt and other useful Julia packages.

**Comment by dpo** [comment]
On another note, @odow verified that this build works together with #4126 for Ipopt.jll. Any objection to merging?

**Comment by odow** [comment]
I think this should have a major version bump in case it breaks lots of things. What happens if MUMPS uses LBT and Ipopt uses OpenBLAS? Don't we need everything synced so that they all use LBT at the same time?

**Comment by giordano** [comment]
> What happens if MUMPS uses LBT and Ipopt uses OpenBLAS?

I wouldn't expect that to be a problem: BLAS is "pure" in the sense it's stateless, each call to BLAS functions is independent to all others. If libblastrampoline forwards calls to another library you'd get slightly different results than openblas depending on their relative discrepancies, but apart from that I don't envision problems. @staticfloat do you have anything to add (or correct what I said)?

**Comment by staticfloat** [comment]
Nope, Mosè nailed it.  Think of LBT as simply doing the following:

```
gemm(args...) = openblas_gemm(args...)
```

But at the C level, and making sure that `gemm_64_` always points to an ILP64 backing BLAS, while `gemm_` always points to an LP64 backing BLAS.

**Comment by dpo** [comment]
But if *both* MUMPS_seq and Ipopt use LBT, they will always be consistent in the sense that they will always call upon the same BLAS subroutines, won't they?

**Comment by staticfloat** [comment]
Yes, as long as they're both invoking LP64 or both invoking ILP64 (LBT separates these two with the `64_` suffix, in the same way as OpenBLAS when built as a part of Julia).

**Comment by ViralBShah** [comment]
Note that addressing https://github.com/JuliaLinearAlgebra/libblastrampoline/issues/52 will go a long way in fixing many issues and making it easy to use MKL LP64 as well.

**Comment by ViralBShah** [comment]
Done in https://github.com/JuliaPackaging/Yggdrasil/pull/5306

**Pull request closed without merging**
