### PR TITLE
bumping scip to 7.0.3 beta

### PR DESCRIPTION
**Pull request by matbesancon**
There shouldn't be much surprise, preparing the SCIP_jll for 7.0.3

### CODE REVIEW

**Comment by matbesancon** [comment]
not sure why Ipopt does not get detected on windows systems only :thinking:

**Comment by odow** [comment]
No ideas sorry. Is there a flag to manually pass the location of Ipopt to cmake?

**Comment by matbesancon** [comment]
yes, `-DIPOPT_DIR=/home/mbesancon/scip-dev/Ipopt/build/ -DIPOPT_LIBRARIES=/home/mbesancon/scip-dev/Ipopt/build/src/Interfaces/`, but I'm not sure we have a way to do that in a generic way on BinaryBuilder?

**Comment by odow** [comment]
Probably some variation of
```
-DIPOPT_DIR=${prefix} \
-DIPOPT_LIBRARIES=${libdir} \
```

**Comment by odow** [comment]
@matbesancon you need to copy the license file across. Here's the example from MibS:
```
# Because of multiple repos, automated license detection fails. Install them
# manually.
mkdir -p ${prefix}/share/licenses/MibS
for dir in SYMPHONY CHiPPS-ALPS CHiPPS-BiCePS CHiPPS-BLIS; do    
    cp $WORKSPACE/srcdir/${dir}/LICENSE ${prefix}/share/licenses/MibS/LICENSE_${dir}
done
cp $WORKSPACE/srcdir/MibS/LICENSE ${prefix}/share/licenses/MibS/LICENSE
```

**Comment by matbesancon** [comment]
curious, how can we fix this? Is it a license file that should be copied / detected from the SCIP repo?

**Pull request merged**
