### PR TITLE
Rebuild LLVM with forward slash off for windows

### PR DESCRIPTION
**Pull request by vchuravy**
Thanks to @vtjnash for spotting this

### CODE REVIEW

**Comment by giordano** [comment]
Should upgrade to 14.0.4 or it isn't worth following their new tight release cycle?

**Comment by vtjnash** [comment]
Ooooh, yeah https://reviews.llvm.org/D112787 seems awkward in the wrong ways

**Comment by vtjnash** [comment]
Thanks @vchuravy for finding this

**Comment by vchuravy** [comment]
> Should upgrade to 14.0.4 or it isn't worth following their new tight release cycle?

We will, once we are done with the major version update

**Pull request merged**
