### PR TITLE
Add LLVM patch

### PR DESCRIPTION
**Pull request by Keno**
Adds the patch from https://github.com/JuliaLang/julia/pull/34860.

### CODE REVIEW

**Comment by vchuravy** [comment]
Will this be backported to Julia 1.4? If so we need this for LLVM 8 as well.

**Comment by giordano** [comment]
Echoing here a comment from Slack: the directory `L/LLVM/v9` should be moved to ` L/LLVM/LLVM@9` (or also ` L/LLVM/LLVM@v9` if you prefer), like the structure of [`OpenBLAS`](https://github.com/JuliaPackaging/Yggdrasil/tree/4babc300138476d3b5696c37f14a2afacc2a43b0/O/OpenBLAS).  This is the reason of the failure to upload the artifacts.  No need to rename the other LLVM versions now, otherwise they'll trigger a rebuild.

**Comment by staticfloat** [comment]
> No need to rename the other LLVM versions now, otherwise they'll trigger a rebuild.

I'm going to push a commit to do the renames now, then cancel the resultant enormous CI job.  That way we won't forget to do this in the future.

**Comment by giordano** [comment]
or use `[skip ci]` :wink:

**Comment by Keno** [comment]
How do we move this forward now that the rename is done? Can I trigger CI again?

**Comment by giordano** [comment]
Yes, rename `L/LLVM/v9` to `L/LLVM/LLVM@9`

**Comment by staticfloat** [comment]
Only on win32:

```
[01:55:14] lib/liblldCOFF.a(Chunks.cpp.obj):Chunks.cpp:(.text$_ZNK3lld4coff15NonSectionChunk14getSectionNameEv+0x0): multiple definition of `lld::coff::NonSectionChunk::getSectionName() const'
[01:55:14] lib/liblldCOFF.a(Writer.cpp.obj):Writer.cpp:(.text$_ZNK3lld4coff15NonSectionChunk14getSectionNameEv+0x0): first defined here
[01:55:14] lib/liblldCOFF.a(DLL.cpp.obj):DLL.cpp:(.text$_ZNK3lld4coff15NonSectionChunk14getSectionNameEv+0x0): multiple definition of `lld::coff::NonSectionChunk::getSectionName() const'
[01:55:14] lib/liblldCOFF.a(Writer.cpp.obj):Writer.cpp:(.text$_ZNK3lld4coff15NonSectionChunk14getSectionNameEv+0x0): first defined here
[01:55:14] lib/liblldMachO.a(ArchHandler_arm64.cpp.obj):ArchHandler_arm64.cpp:(.text$_ZN3lld6mach_o11ArchHandler10createShimERNS0_9MachOFileEbRKNS_11DefinedAtomE+0x0): multiple definition of `lld::mach_o::ArchHandler::createShim(lld::mach_o::MachOFile&, bool, lld::DefinedAtom const&)'
[01:55:14] lib/liblldMachO.a(ArchHandler.cpp.obj):ArchHandler.cpp:(.text$_ZN3lld6mach_o11ArchHandler10createShimERNS0_9MachOFileEbRKNS_11DefinedAtomE+0x0): first defined here
[01:55:14] lib/liblldMachO.a(ArchHandler_x86.cpp.obj):ArchHandler_x86.cpp:(.text$_ZN3lld6mach_o11ArchHandler10createShimERNS0_9MachOFileEbRKNS_11DefinedAtomE+0x0): multiple definition of `lld::mach_o::ArchHandler::createShim(lld::mach_o::MachOFile&, bool, lld::DefinedAtom const&)'
[01:55:14] lib/liblldMachO.a(ArchHandler.cpp.obj):ArchHandler.cpp:(.text$_ZN3lld6mach_o11ArchHandler10createShimERNS0_9MachOFileEbRKNS_11DefinedAtomE+0x0): first defined here
[01:55:14] lib/liblldMachO.a(ArchHandler_x86_64.cpp.obj):ArchHandler_x86_64.cpp:(.text$_ZN3lld6mach_o11ArchHandler10createShimERNS0_9MachOFileEbRKNS_11DefinedAtomE+0x0): multiple definition of `lld::mach_o::ArchHandler::createShim(lld::mach_o::MachOFile&, bool, lld::DefinedAtom const&)'
[01:55:14] lib/liblldMachO.a(ArchHandler.cpp.obj):ArchHandler.cpp:(.text$_ZN3lld6mach_o11ArchHandler10createShimERNS0_9MachOFileEbRKNS_11DefinedAtomE+0x0): first defined here
```

**Comment by staticfloat** [comment]
And only on `-cxx11`?  That's gotta be a ccache error or something.  I'll try re-running.

**Comment by staticfloat** [comment]
Great.  I'm gonna merge.

**Pull request merged**
