### PR TITLE
Add builder for adwaita-icon-theme

### PR DESCRIPTION
**Pull request by giordano**
Dependency of GTK, see #62

### CODE REVIEW

**Comment by staticfloat** [comment]
So we're gonna have to point GTK at these icons somehow, right?  Add the artifact locations to an environment variable or something?

**Comment by giordano** [comment]
No idea, we'll find out 🙂

**Comment by giordano** [comment]
This should help: https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#directory_layout

**Comment by giordano** [comment]
Idea suggested by @staticfloat on Slack: we could patch GTK to look for these icons in the directory pointed by a custom environment variable like `GTK_DATA_DIRS` (or something more specific like `ADWAITA_ICONS_DIRS`), in order to avoid conflicts with other packages that could possibly be setting `XDG_DATA_DIRS`

**Pull request merged**
