### PR TITLE
libpng: New version 1.6.42

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by jheinen** [comment]
Could you please upgrade`libpng` to 1.6.43. It seems, that `PNG_FRAMEWORK=ON` causes trouble, e.g. when building the [GR framework](https://github.com/JuliaPackaging/Yggdrasil/pull/8263).

[This](https://github.com/pnggroup/libpng/commit/aa95dee697d0d688795839695099c383b0ac39f6) commit seems to fix that problem (for cross-compiler environments, like `BinaryBuilder`):
```
Update the PNG_FRAMEWORK option: force it back to OFF and print a
warning if the option was ON but the target is not an Apple system.
```

Cc: @giordano

**Comment by eschnett** [comment]
See https://github.com/JuliaBinaryWrappers/libpng_jll.jl, we upgraded last week.

**Comment by jheinen** [comment]
Thanks for the information. Unfortunately, in our build `CMake` tries to link `lib/png.framework` (without the `-framework` flag) instead of the dynamic link library. I have tried to prevent this using `CMake` flags (`CMAKE_FIND_FRAMEWORK=LAST`), but this didn't work either.

**Comment by giordano** [comment]
> [This](https://github.com/pnggroup/libpng/commit/aa95dee697d0d688795839695099c383b0ac39f6) commit seems to fix that problem (for cross-compiler environments, like BinaryBuilder):

I don't think that check is doing what you think, as [`APPLE`](https://cmake.org/cmake/help/v3.29/variable/APPLE.html) is true when we target macOS.  However we can disable the framework, which was disabled until https://github.com/pnggroup/libpng/commit/8fc13a8704370ed576aeed2a983ceb5704305c4f (first appeared in [v1.6.41](https://github.com/pnggroup/libpng/releases/tag/v1.6.41))

**Comment by jheinen** [comment]
Thanks for the fixes!!!

**Pull request merged**
