### PR TITLE
Update GR to version 0.57.0

### PR DESCRIPTION
**Pull request by jheinen**

### CODE REVIEW

**Comment by giordano** [comment]
@barche should we try to use the new Qt package?

**Comment by barche** [comment]
> @barche should we try to use the new Qt package?

Yes, it should be sufficient to replace the Qt dependency with:

```julia
Dependency("Qt5Base_jll"),
```

**Comment by barche** [comment]
Seems you can just edit this online, fingers crossed ;)

**Comment by giordano** [comment]
Awesome, thanks!

**Pull request merged**
