### PR TITLE
New Recipe: QuantRegBuilder v0.1.0

### PR DESCRIPTION
**Pull request by fogarty-ben**

### CODE REVIEW

**Comment by giordano** [comment]
Why did you clo the pull request?

**Comment by fogarty-ben** [comment]
My `build_tarballs.jl` was failing all test b/c it couldn't find the products due to a pretty simple mistake (wrong extension and path). I've worked out what was going on and will have a new PR shortly.

**Comment by giordano** [comment]
I think the problem is the target directory. You should put executables in the `${}bindir` directory

**Comment by fogarty-ben** [comment]
Yep, that was pretty much it. I wasn't thinking when ripping from the HelloWorldFORTRAN example. I have it working locally by changing to the following command:

`gfortran -fPIC -shared -std=legacy rqbr.f -o ${libdir}/rqbr.${dlext}`

and the analogous for the second command. Thanks for your help!

**Comment by giordano** [comment]
Just note that you don't need to open a new pull request to make changes, you can just keep pushing to the existing one :wink:

**Pull request closed without merging**
