### PR TITLE
New Recipe: libatomic_ops v1.33.7

### PR DESCRIPTION
**Pull request by staticfloat**
@bramtayl Here's a working recipe.

### CODE REVIEW

**Comment by bramtayl** [comment]
Thanks!!

**Comment by bramtayl** [comment]
Merge?

**Comment by bramtayl** [comment]
@staticfloat sorry to bother you but could you merge this?

**Comment by staticfloat** [comment]
Sure.  Since there are no products usable by Julia, I suggest seeing if you can list this as a `BuildDependency()` to whatever needs this to build, so that users don't have to download it.

**Pull request merged**
