### PR TITLE
[SDL2] Add a dependency on alsa_plugins

### PR DESCRIPTION
**Pull request by aviks**
In partial mitigation of https://github.com/JuliaPackaging/Yggdrasil/issues/1432#issuecomment-851065063

### CODE REVIEW

**Comment by giordano** [comment]
There is also [v2.24.0](https://github.com/libsdl-org/SDL/releases/tag/release-2.24.0), might want to upgrade?

**Comment by aviks** [comment]
cc @Gnimuc

**Comment by Gnimuc** [comment]
```
GitSource("https://github.com/libsdl-org/SDL.git",
              "8c9beb0c873f6ca5efbd88f1ad2648bfc793b2ac"),
```

**Comment by aviks** [comment]
Ah, well, I should known, and left the small change on it's own. 😞 

```
[13:12:47] Undefined symbols for architecture arm64:
[13:12:47]   "___isPlatformVersionAtLeast", referenced from:
[13:12:47]       _IOS_AddJoystickDevice in SDL_mfijoystick.o
[13:12:47] ld: symbol(s) not found for architecture arm64
```

**Comment by giordano** [comment]
Right :grimacing:

**Pull request merged**
