### PR TITLE
[Arrow] Build with ZSTD

### PR DESCRIPTION
**Pull request by evetion**
So we can work on https://github.com/JuliaGeo/GDAL.jl/issues/171.

### CODE REVIEW

**Comment by evetion** [comment]
Freebsd and macos [fail](https://buildkite.com/julialang/yggdrasil/builds/14722#01933aa4-8249-44bc-89bd-e5c29b3784b7/667-1017) with requiring boost v1.81, which we don't have yet (boost_jll is at v1.79). Not sure why these builds require this version whereas the other platforms seem happy with an older version.

Windows builds [fail](https://buildkite.com/julialang/yggdrasil/builds/14722#01933aa4-824f-43eb-9543-e7f58211045c/678-1940) with (I assume) a case-sensitivity error
```[15:22:30] /workspace/srcdir/arrow/cpp/src/arrow/util/io_util.cc:121:12: fatal error: Windows.h: No such file or directory
[15:22:30]  #  include <Windows.h>
```

**Comment by giordano** [comment]
> Windows builds fail with (I assume) a case-sensitivity error

Send a patch upstream to fix it please

**Comment by evetion** [comment]
The wrong boost version seems due to cmake finding a [system FindBoost.cmake](https://buildkite.com/julialang/yggdrasil/builds/14722#01933aa4-8245-4cbf-a3fd-05090793204f)?
```
[15:18:17] -- [ /usr/share/cmake/Modules/FindBoost.cmake:1673 ] _boost_TEST_VERSIONS = "1.84.0;1.84;1.83.0;1.83;1.82.0;1.82;1.81.0;1.81"
```

Versus my local build
```
[16:40:41] -- Found Boost: /opt/aarch64-apple-darwin20/aarch64-apple-darwin20/sys-root/usr/local/lib/cmake/Boost-1.76.0/BoostConfig.cmake (found suitable version "1.76.0", minimum required is "1.58")
```

**Comment by eschnett** [comment]
I have https://github.com/JuliaPackaging/Yggdrasil/pull/9926 that I'd like to go in in the mean time. It's a small update that supports more architectures.

**Comment by eschnett** [comment]
@evetion Can you have a look at https://github.com/JuliaPackaging/Yggdrasil/pull/9936?

**Comment by giordano** [comment]
Anything in here that isn't already on `master`?

**Comment by evetion** [comment]
Only the ZSTD compression option, which would be quite useful. I can make a new PR/rebase this for it?

**Comment by evetion** [comment]
Windows seem to be [failing](https://buildkite.com/julialang/yggdrasil/builds/15398#0193abad-cbf3-4338-a1f5-dece51d5cfd3/660-2084) with:
```
[14:00:22] src/arrow/CMakeFiles/arrow_shared.dir/build.make:978: *** target pattern contains no '%'.  Stop.
[14:00:22] make[1]: *** [CMakeFiles/Makefile2:714: src/arrow/CMakeFiles/arrow_shared.dir/all] Error 2
```

**Comment by eschnett** [comment]
@evetion This error is because Windows doesn't find zstd. The respective cmake variable then looks different than expected, and a resulting Makefile rule is not a pattern.

Are there explicit cmake variable that point it to where zstd is installed?

**Comment by evetion** [comment]
Hmm when I set an `IMPORTED_IMPLIB` for `cpp/cmake_modules/FindzstdAlt.cmake` I end up with:

```
[22:46:27] /opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld: /opt/x86_64-w64-mingw32/x86_64-w64-mingw32/sys-root/lib/../lib/libmsvcrt.a(lib64_libmsvcrt_common_a-wcrtomb.o): in function `wcsrtombs':
[22:46:27] /workspace/srcdir/mingw-w64-v11.0.1/mingw-w64-crt/misc/wcrtomb.c:58: multiple definition of `wcsrtombs'; /workspace/destdir/lib/libzstd.dll.a(d000557.o):(.text+0x0): first defined here
[22:46:27] collect2: error: ld returned 1 exit status
```

**Comment by eschnett** [comment]
`libzstd.dll.a` looks like a static library (not quite sure). I think you want to use a shared library instead. On Windows, shared libraries are installed into `bin`, not `lib`.

**Pull request closed without merging**
