### PR TITLE
Wizard recipe: finufft-v1.1.2

### PR DESCRIPTION
**Pull request by jonas-kr**
This pull request contains a new build recipe I built using the BinaryBuilder.jl wizard:

* Package name: finufft
* Version: v1.1.2

@staticfloat please review and merge.

### CODE REVIEW

**Comment by giordano** [comment]
@jonas-kr why do you keep closing and opening pull requests?

**Comment by jonas-kr** [comment]
> 
> 
> @jonas-kr why do you keep closing and opening pull requests?
I am truly sorry for this chaos! I am currently trying to figure out how to test my changes without opening a pull request...

**Comment by giordano** [comment]
You can run the build script, optionally only for some platforms, without using the wizard: https://juliapackaging.github.io/BinaryBuilder.jl/dev/FAQ/#I-love-the-wizard,-but-now-I-want-to-break-free:-can-I-build-the-tarballs-without-it?

**Comment by jonas-kr** [comment]
Thank you very much! Let's see whether I can reproduce the issues occurring on the Azure server

**Pull request closed without merging**
