### PR TITLE
[ImageMagick] Add `convert` and `identify` to products

### PR DESCRIPTION
**Pull request by ericphanson**
It would be helpful to be able to do stuff like `ImageMagick_jll.convert_path`; these two are the ones needed for pdfsandwich.

### CODE REVIEW

**Comment by giordano** [comment]
Could you please address the warnings in https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=3310&view=results?

Stuff like
```
┌ Warning: Using a pair as source is deprecated, use ArchiveSource instead
└ @ BinaryBuilder /depot/packages/BinaryBuilder/RgjsE/src/Sources.jl:212
[...]
┌ Warning: Using PackageSpec or string as dependency is deprecated, use Dependency instead
└ @ BinaryBuilder /depot/packages/BinaryBuilder/RgjsE/src/Dependencies.jl:138
[...]
┌ Warning: /agent/_work/1/s/I/ImageMagick/build/x86_64-linux-gnu/9XUDB2Sg/destdir/lib/libMagick++-6.Q16.so.8.0.0 contains std::string values!  This causes incompatibilities across the GCC 4/5 version boundary.  To remedy this, you must build a tarball for both GCC 4 and GCC 5.  To do this, immediately after your `platforms` definition in your `build_tarballs.jl` file, add the line:
│ 
│     platforms = expand_cxxstring_abis(platforms)
└ @ BinaryBuilder /depot/packages/BinaryBuilder/RgjsE/src/auditor/compiler_abi.jl:222
```

> It would be helpful to be able to do stuff like `ImageMagick_jll.convert_path`

Ideally, you should _never_ need to use the path of an executable, always use the wrapper instead.  There is a reason why the path is not exported but the wrapper is :wink:

**Comment by giordano** [comment]
The wrappers are there because they make sure the needed libraries are found at runtime.  If you don't use them, calling an executable can fail to load one of it dependencies.  It's not a matter of cleanness, but to make things work :slightly_smiling_face:

**Comment by ericphanson** [comment]
Ah ok, thanks for the clarification!

**Comment by ericphanson** [comment]
This broke ImageMagick.jl due to the new `convert` export conflicting with Base 😨. Luckily @asinghvi17 fixed it quickly in https://github.com/JuliaIO/ImageMagick.jl/commit/c347fb978f2f1353b170c90f70e9eeb11850c597.

I imagine this kind of conflict is rare, but still it’s a bit of an unexpected consequence here. It makes me wonder if maybe JLL packages shouldn’t have exports? Since they aren’t usually used directly by the end user anyway, and they can’t version via semver to communicate changes like this (since they version according to the underlying binary).

It seems to me the main benefit of exports is what you mentioned earlier in the thread: indicating that you should use the wrappers, not eg `convert_path`. But maybe that issue can be covered just by documentation? Eg the auto generated readme could just list what functions you are supposed to use and say the rest are internal.

Maybe it’s too late to make this kind of change though...

**Comment by giordano** [comment]
> Maybe it’s too late to make this kind of change though...

Well, yes.

Instead, I don't think it's too late to rename the `convert` symbol to something easier to use.  I don't expect anyone (apart from you maybe?) already took advantage of a new export that conflicts with a symbol in `Base`.  If you can come up with a good name, please open a PR to https://github.com/JuliaBinaryWrappers/ImageMagick_jll.jl without building again the tarballs, which would be useless and just annoying for the users.

**Comment by ericphanson** [comment]
Sure, I can do that, but won't it just get overridden if someone updates the build script?

**Comment by giordano** [comment]
Yes, so you'll do also a PR here with `[skip ci]` in the commit message that won't trigger a new build :wink:

**Comment by ericphanson** [comment]
Ok! Sounds good.

What about... `imagemagick_convert`?

**Comment by giordano** [comment]
A bit verbose since it'll be under `ImageMagick_jll`, but ok, we need to differentiate from `Base`'s `convert` somehow :sweat_smile:

**Comment by ericphanson** [comment]
Yeah... I thought since it is exported, at least you don't have to use as `ImageMagick_jll.imagemagick_convert`. Definitely a bit annoying but unambiguous at least.

**Pull request merged**
