### PR TITLE
[ZeroMQ] without debugging information

### PR DESCRIPTION
**Pull request by jaakkor2**
Potential space saving
`C:\Users\jr\.julia\artifacts\2fe5dc83269a247546ff56e9babd02af644a410e\bin\libzmq.dll`  19,003 KB
`C:\Users\jr\.julia\conda\3\Library\bin\libzmq.dll` 441 KB

### CODE REVIEW

**Comment by giordano** [comment]
You may also want to remove the static archives (but they're smaller) :sweat_smile:

**Comment by giordano** [comment]
And maybe address the [warnings](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=2772&view=results) about the type of the sources :wink:

**Comment by jaakkor2** [comment]
libzmq.dll inside https://julia-bb-buildcache.s3.amazonaws.com/951c6f4279c8b68ee32d9b87e09f4ac48b863e25/dd66ca4f46e434e779031f6c574c3af7b9f427a0e5b01a11c2ac814c8acbb24e/i686-w64-mingw32-cxx11.tar.gz is 867 KB.  Good enough for now.

**Comment by jaakkor2** [comment]
> 
> 
> You may also want to remove the static archives (but they're smaller) 😅

`lib\libzmq.dll.a` is 57 KB.  Import libraries generally not needed?  Not a major gain to be achieved :)

**Pull request merged**
