### PR TITLE
Wizard recipe: libdivsufsort-v2.0.2-1

### PR DESCRIPTION
**Pull request by cjdoris**
This pull request contains a new build recipe I built using the BinaryBuilder.jl wizard:

* Package name: libdivsufsort
* Version: v2.0.2-1

@staticfloat please review and merge.

### CODE REVIEW

**Comment by giordano** [comment]
Welcome and thank you so much for you contribution!  I took the liberty to build for all supported platforms, since it should just work :wink:

**Comment by cjdoris** [comment]
Thanks! Re the different platforms, I didn't do apple because I hadn't read the terms of the SDK yet, so thanks for that. But I tried to build for Windows and it failed. It looks like it works for you, so what's the difference?

**Comment by giordano** [comment]
> But I tried to build for Windows and it failed. It looks like it works for you, so what's the difference?

No idea :confused:  I didn't do anything special, just tried to run :slightly_smiling_face:

**Comment by cjdoris** [comment]
Ahh, my Windows woes were fixed by upgrading to master...

**Pull request merged**
