### PR TITLE
Don't lock microarchitecture for OpenBLAS

### PR DESCRIPTION
**Pull request by Keno**
@staticfloat says this is now required

### CODE REVIEW

**Comment by giordano** [comment]
That's correct, but we don't need to actually rebuild the package, do we? If not, in the commit message use `[skip build]` to only update the wrappers or `[skip ci]` to don't do anything at all when merging the pull request

**Comment by giordano** [comment]
Well, apparently we broke AZP :stuck_out_tongue:

**Comment by Keno** [comment]
No, we don't need to rebuild the package, other than maybe checking that it does still build with the updated toolchain.

**Comment by giordano** [comment]
In that case `[skip ci]` is probably the best option: it runs CI in the pull request but not when merging it on master. Anyway, here we generated too many jobs and AZP isn't happy about that

**Pull request merged**
