### PR TITLE
[MPICH] version 4.0.0

### PR DESCRIPTION
**Pull request by simonbyrne**

### CODE REVIEW

**Comment by giordano** [comment]
```
[07:27:23] ./src/include/mpichconf.h:782:28: error: unknown type name ‘unavailable’
[07:27:23]  #define MPIR_FC_REAL_CTYPE unavailable
[07:27:23]                             ^~~~~~~~~~~
[07:27:23] ./src/include/mpir_op_util.h:230:5: note: in expansion of macro ‘MPIR_FC_REAL_CTYPE’
[07:27:23]                             ^~~~~~~~~~~
[07:27:23] ./src/include/mpir_op_util.h:231:5: note: in expansion of macro ‘MPIR_FC_REAL_CTYPE’
[07:27:23]      MPIR_FC_REAL_CTYPE im;
[07:27:23]      ^~~~~~~~~~~~~~~~~~
[07:27:23] ./src/include/mpichconf.h:779:30: error: unknown type name ‘unavailable’
[07:27:23]  #define MPIR_FC_DOUBLE_CTYPE unavailable
[07:27:23]                               ^~~~~~~~~~~
[07:27:23] ./src/include/mpir_op_util.h:235:5: note: in expansion of macro ‘MPIR_FC_DOUBLE_CTYPE’
[07:27:23]      MPIR_FC_DOUBLE_CTYPE re;
[07:27:23]      ^~~~~~~~~~~~~~~~~~~~
[07:27:23] ./src/include/mpichconf.h:779:30: error: unknown type name ‘unavailable’
[07:27:23]  #define MPIR_FC_DOUBLE_CTYPE unavailable
[07:27:23]                               ^~~~~~~~~~~
[07:27:23] ./src/include/mpir_op_util.h:236:5: note: in expansion of macro ‘MPIR_FC_DOUBLE_CTYPE’
[07:27:23]      MPIR_FC_DOUBLE_CTYPE im;
[07:27:23]      ^~~~~~~~~~~~~~~~~~~~
```
Interesting...

**Comment by simonbyrne** [comment]
So the problem appears to be:
```
[07:26:10] checking for C type matching Fortran real... unavailable
[07:26:10] checking for C type matching Fortran double... unavailable
```
in the `configure.ac`. This was changed in https://github.com/pmodels/mpich/commit/615e9a512bc6f9a67f7155fe4215545438551eaf#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810L3393-R2972 (scroll to the bottom and click "show diff")

**Comment by simonbyrne** [comment]
So the problem appears to be:
```
[07:26:10] checking for C type matching Fortran real... unavailable
[07:26:10] checking for C type matching Fortran double... unavailable
```
The build logic was changed in https://github.com/pmodels/mpich/commit/615e9a512bc6f9a67f7155fe4215545438551eaf#diff-49473dca262eeab3b4a43002adb08b4db31020d190caaad1594b47f1d5daa810L3393-R2972

I suspect the problem lies in here:
https://github.com/pmodels/mpich/blob/v4.0/confdb/aclocal_datatype.m4#L47-L63

**Comment by giordano** [comment]
Frustratingly enough, the log of this test doesn't show the exact program that was compiled

**Comment by giordano** [comment]
We probably need to set also `CROSS_F77_SIZEOF_REAL` and `CROSS_F77_SIZEOF_DOUBLE_PRECISION`
https://github.com/pmodels/mpich/blob/v4.0/configure.ac#L2904-L2905?

**Comment by giordano** [comment]
Or more probably you're simply right:
```console
sandbox:${WORKSPACE}/srcdir/mpich-4.0 # get_c_float_type() {
>     len=$1
>     pac_retval=
>     for c_type in float double __float128 "long_double" ; do
>         eval ctypelen=\$"ac_cv_sizeof_$c_type"
>         if test "$len" = "$ctypelen" -a "$ctypelen" -gt 0 ; then
>             if test "$c_type" = "long_double" ; then
>                 pac_retval=`echo $c_type | sed -e 's/_/ /g'`
>             else
>                 pac_retval=$c_type
>             fi
>             return
>         fi
>     done
>     pac_retval="unavailable"
> }
sandbox:${WORKSPACE}/srcdir/mpich-4.0 # get_c_float_type 4
bash: test: : integer expression expected
bash: test: : integer expression expected
bash: test: : integer expression expected
bash: test: : integer expression expected
```

**Comment by giordano** [comment]
Ok, I was missing the value of the `ac_cv_sizeof_*` variables.  Copying them from the log file:
```sh
ac_cv_sizeof_Complex='8'
ac_cv_sizeof_DoubleComplex='16'
ac_cv_sizeof_LongDoubleComplex='32'
ac_cv_sizeof_MPII_Bsend_data_t='96'
ac_cv_sizeof__Bool='1'
ac_cv_sizeof__Float16='0'
ac_cv_sizeof___float128='16'
ac_cv_sizeof_bool='1'
ac_cv_sizeof_char='1'
ac_cv_sizeof_double='8'
ac_cv_sizeof_double__Complex='16'
ac_cv_sizeof_double_int='16'
ac_cv_sizeof_float='4'
ac_cv_sizeof_float__Complex='8'
ac_cv_sizeof_float_int='8'
ac_cv_sizeof_int='4'
ac_cv_sizeof_long='8'
ac_cv_sizeof_long_double='16'
ac_cv_sizeof_long_double__Complex='32'
ac_cv_sizeof_long_double_int='32'
ac_cv_sizeof_long_int='16'
ac_cv_sizeof_long_long='8'
ac_cv_sizeof_short='2'
ac_cv_sizeof_short_int='8'
ac_cv_sizeof_two_int='8'
ac_cv_sizeof_unsigned_char='1'
ac_cv_sizeof_unsigned_int='4'
ac_cv_sizeof_unsigned_long='8'
ac_cv_sizeof_unsigned_long_long='8'
ac_cv_sizeof_unsigned_short='2'
ac_cv_sizeof_void_p='8'
ac_cv_sizeof_wchar_t='4'

get_c_float_type() {
    len=$1
    pac_retval=
    for c_type in float double __float128 "long_double" ; do
        eval ctypelen=\$"ac_cv_sizeof_$c_type"
        if test "$len" = "$ctypelen" -a "$ctypelen" -gt 0 ; then
            if test "$c_type" = "long_double" ; then
                pac_retval=`echo $c_type | sed -e 's/_/ /g'`
            else
                pac_retval=$c_type
            fi
            return
        fi
    done
    pac_retval="unavailable"
}
```
I get
```console
sandbox:${WORKSPACE}/srcdir/mpich-4.0 # get_c_float_type 4
sandbox:${WORKSPACE}/srcdir/mpich-4.0 # echo ${pac_retval}
float
sandbox:${WORKSPACE}/srcdir/mpich-4.0 # get_c_float_type 8
sandbox:${WORKSPACE}/srcdir/mpich-4.0 # echo ${pac_retval}
double
```
which looks right.  So now I'm more confused than before.

**Comment by giordano** [comment]
It turns out we had indeed to set `CROSS_F77_SIZEOF_REAL` and `CROSS_F77_SIZEOF_DOUBLE_PRECISION`.  This makes it work on most platforms, but all Musl ones are failing at linking time

**Comment by simonbyrne** [comment]
Why did automake fail? It used to work before the refactor and the logic is mostly the same.

**Comment by giordano** [comment]
I'm not sure.  I thought (and maybe you too) that `get_c_float_type` could be doing something not busybox-friendly, but I showed above it seems to work correctly.

**Comment by giordano** [comment]
For aarch64-apple-darwin (which uses GCC 11) we need to set both `FFLAGS` _and_ `FCFLAGS` :roll_eyes: 

For Musl platforms the linking error is
```
[01:19:03] libtool: link: cc -fvisibility=hidden -DNDEBUG -DNVALGRIND -O3 -o src/env/.libs/mpichversion src/env/mpichversion.o  lib/.libs/libmpi.so -lpthread -lm -Wl,-rpath -Wl,/workspace/destdir/lib
[01:19:03] /opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/8.1.0/../../../../x86_64-linux-musl/bin/ld: lib/.libs/libmpi.so: undefined reference to `__CPU_ISSET_S'
[01:19:03] /opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/8.1.0/../../../../x86_64-linux-musl/bin/ld: lib/.libs/libmpi.so: undefined reference to `__CPU_SET_S'
[01:19:03] /opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/8.1.0/../../../../x86_64-linux-musl/bin/ld: lib/.libs/libmpi.so: undefined reference to `__CPU_ZERO_S'
[01:19:03] /opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/8.1.0/../../../../x86_64-linux-musl/bin/ld: lib/.libs/libmpi.so: undefined reference to collect2: error: ld returned 1 exit status
[01:19:03] `__CPU_ISSET_S'
[01:19:03] /opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/8.1.0/../../../../x86_64-linux-musl/bin/ld: lib/.libs/libmpi.so: undefined reference to `__CPU_SET_S'
[01:19:03] /opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/8.1.0/../../../../x86_64-linux-musl/bin/ld: lib/.libs/libmpi.so: undefined reference to `__CPU_ZERO_S'
[01:19:03] collect2: error: ld returned 1 exit status
[01:19:03] make[2]: *** [Makefile:14129: src/env/mpichversion] Error 1
[01:19:03] make[2]: *** Waiting for unfinished jobs....
[01:19:03] make[2]: *** [Makefile:14135: src/env/mpivars] Error 1
```
I'm not sure whether Musl is supposed to have this symbol, but it doesn't complain when compiling...

**Comment by giordano** [comment]
I feel like that's a genuine bug.  The documented functions in the manual are those without the leading `__`: https://linux.die.net/man/3/cpu_set.  In `sched.h` on arch linux I have stuff like
```c
# define CPU_SETSIZE __CPU_SETSIZE
# define CPU_SET(cpu, cpusetp)	 __CPU_SET_S (cpu, sizeof (cpu_set_t), cpusetp)
# define CPU_CLR(cpu, cpusetp)	 __CPU_CLR_S (cpu, sizeof (cpu_set_t), cpusetp)
# define CPU_ISSET(cpu, cpusetp) __CPU_ISSET_S (cpu, sizeof (cpu_set_t), \
						cpusetp)
# define CPU_ZERO(cpusetp)	 __CPU_ZERO_S (sizeof (cpu_set_t), cpusetp)
# define CPU_COUNT(cpusetp)	 __CPU_COUNT_S (sizeof (cpu_set_t), cpusetp)

# define CPU_SET_S(cpu, setsize, cpusetp)   __CPU_SET_S (cpu, setsize, cpusetp)
# define CPU_CLR_S(cpu, setsize, cpusetp)   __CPU_CLR_S (cpu, setsize, cpusetp)
# define CPU_ISSET_S(cpu, setsize, cpusetp) __CPU_ISSET_S (cpu, setsize, \
							   cpusetp)
# define CPU_ZERO_S(setsize, cpusetp)	    __CPU_ZERO_S (setsize, cpusetp)
# define CPU_COUNT_S(setsize, cpusetp)	    __CPU_COUNT_S (setsize, cpusetp)
```
and judging by their uses in https://github.com/pmodels/mpich/blob/v4.0/src/mpl/src/thread/mpl_thread_posix.c the standard versions could be used.

**Comment by giordano** [comment]
All green now!

**Comment by simonbyrne** [comment]
Thank you!

Is it worth trying to upstream any of this?

**Comment by giordano** [comment]
I submitted the Musl patch: https://github.com/pmodels/mpich/pull/5789. I don't know what to do for the other problem as I don't understand what's the the root.

**Pull request merged**
