### PR TITLE
[FastTransforms] v0.5.1

### PR DESCRIPTION
**Pull request by MikaelSlevinsky**
Fix spin-weighted spherical harmonics with |m| = 1

https://github.com/JuliaApproximation/FastTransforms.jl/issues/139

It's marked draft because I want to try fixing OpenMP on macOS

https://github.com/JuliaApproximation/FastTransforms.jl/issues/136

### CODE REVIEW

**Comment by MikaelSlevinsky** [comment]
Yes, you're right. But there is a workaround in this link that works locally for me https://stackoverflow.com/a/60564952. On BinaryBuilder, I'm missing the header. I've observed that Clang+OpenMP has a lower overhead than GCC. I also switched to the default compiler to get ready to support apple-aarch64

**Comment by MikaelSlevinsky** [comment]
So I guess the question is how can we make this work? Should we have a JLL package for libomp as it exists on homebrew?

**Comment by MikaelSlevinsky** [comment]
On top of Homebrew's bottle, here's how R make OpenMP available for Apple LLVM https://mac.r-project.org/openmp/

**Comment by giordano** [comment]
Using libomp is an open issue, so far unaddressed because libgomp works well.  You just need to use GCC instead of Clang.  `omp.h` is in GCC header files:
```console
sandbox:${WORKSPACE} # qfind  /opt/${target} -name "omp.h"
/opt/x86_64-apple-darwin14/lib/gcc/x86_64-apple-darwin14/4.8.5/include/omp.h
```

**Comment by giordano** [comment]
To be clear, getting libomp properly in is something I wish, but it isn't very high priority as we have an alternative

> I also switched to the default compiler to get ready to support apple-aarch64

Note that when you'll want to introduce aarch64 darwin in the list of platforms, that'd make the JLL package compatible only with julia v1.6+.  You can do it, but just be aware you'll lose compatibility with older versions.

**Comment by MikaelSlevinsky** [comment]
I don't I can do this until FFTW_jll.jl has aarch64 on darwin, so there's no rush.

**Pull request merged**
