### PR TITLE
[MKL] Add IntelOpenMP as dependency

### PR DESCRIPTION
**Pull request by giordano**
This reorganises the builder like #259 in order to properly work with Azure Pipelines and adds IntelOpenMP as dependency.  Requires https://github.com/JuliaRegistries/General/pull/6255 to be merged.

### CODE REVIEW

**Comment by giordano** [comment]
Here audit takes quite a lot of time, should we disable it, like it was before?

**Comment by giordano** [comment]
Interesting: after adding IntelOpenMP as dependency audit is failing :confused:

**Comment by staticfloat** [comment]
I don't know why, but it's putting the libraries into `lib/lib/libmkl_core.so` instead of `lib/libmkl_core.so`, so it can't find them at the end.

**Comment by giordano** [comment]
Maybe I should check the `mv` commands

**Comment by giordano** [comment]
Now `${libdir}` already exists and
```sh
mv lib ${libdir}
```
put `lib` _into_ `${libdir}`.

After we finish the LLVM builds I'll update the script to:
```sh
cd $WORKSPACE/srcdir
if [[ ${target} == *mingw* ]]; then
    cp -r Library/bin/* ${libdir}
else
    cp -r lib/* ${libdir}
fi
install_license info/*.txt
```

**Comment by giordano** [comment]
Good to go?

**Pull request merged**
