### PR TITLE
rebuild packages for PPC -- 2

### PR DESCRIPTION
**Pull request by vchuravy**
with this we should be able to load all jll's on PPC

### CODE REVIEW

**Comment by giordano** [comment]
Why is it building Glib? :confused:

**Comment by vchuravy** [comment]
Ooh because you merged Glib in the meantime. And so the diff it includes that:

```
git diff-tree --no-commit-id --name-only -r HEAD "remotes/origin/master" | grep -E ".+/.+"
B/bmon/build_tarballs.jl
G/Geant4/build_tarballs.jl
T/tree_sitter_c/build_tarballs.jl
➜  Yggdrasil git:(vc/ppc_rebuild2) ✗ git fetch
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), 2.54 KiB | 1.27 MiB/s, done.
From git://github.com/JuliaPackaging/Yggdrasil
   4384e08..86fc693  master     -> origin/master
➜  Yggdrasil git:(vc/ppc_rebuild2) ✗ 
git diff-tree --no-commit-id --name-only -r HEAD "remotes/origin/master" | grep -E ".+/.+"
B/bmon/build_tarballs.jl
G/Geant4/build_tarballs.jl
G/Glib/build_tarballs.jl
T/tree_sitter_c/build_tarballs.jl
```

**Comment by vchuravy** [comment]
So I think we want:

```
git diff-tree --no-commit-id --name-only -r HEAD $(git merge-base --fork-point remotes/origin/master HEAD) | grep -E ".+/.+"
B/bmon/build_tarballs.jl
G/Geant4/build_tarballs.jl
T/tree_sitter_c/build_tarballs.jl
```

**Comment by giordano** [comment]
Good catch!  This explains why sometimes we get some strange builds, it happens when there has been a commit to `master` in the meantime

**Comment by giordano** [comment]
> So I think we want:

Yes, that looks like a good idea!

**Pull request merged**
