### PR TITLE
[OpenBLAS/lapack] Apply the patch from xianyi/OpenBLAS#3392

### PR DESCRIPTION
**Pull request by DilumAluthge**
This pull request applies the patch from xianyi/OpenBLAS#3392 to the following JLLs:

1. OpenBLAS_jll
2. OpenBLAS32_jll
3. OpenBLASHighCoreCount_jll

---

Refs JuliaLang/LinearAlgebra.jl#873
Refs Reference-LAPACK/lapack#625

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@Keno Which version of OpenBLAS should I be applying this patch to? It seems to be "failing to apply the patch" when I try to apply it to OpenBLAS 0.3.10.

**Comment by DilumAluthge** [comment]
Let's try using the patch from the relevant PR on OpenBLAS: https://github.com/xianyi/OpenBLAS/pull/3392

**Comment by DilumAluthge** [comment]
> OpenBLAS vendors lapack in one of it's source directories. You'll have to adjust the patch file or patch invocation accordingly.

Alright, I'm now using the patch file from the relevant PR to OpenBLAS (https://github.com/xianyi/OpenBLAS/pull/3392).

**Comment by DilumAluthge** [comment]
It looks like the patch is applying correctly now. I put it in the folders for OpenBLAS@0.3.10, OpenBLAS32@0.3.10, and OpenBLASHighCoreCount@0.3.10. Is that sufficient, or should I also put it into the folders for other versions of OpenBLAS?

**Comment by DilumAluthge** [comment]
I guess I don't understand how the patch folders work here. If I add the patch file to OpenBLAS 0.3.10, does it automatically get applied to later OpenBLAS versions as well? Or do I manually need to symlink my patch file into the `bundled/patches` folder of each OpenBLAS version to which I want to apply the patch?

**Comment by staticfloat** [comment]
Yes, it needs to be symlinked into every `patches` folder that needs it.

**Comment by DilumAluthge** [comment]
- https://github.com/JuliaLang/julia/pull/42546
- https://github.com/JuliaLang/julia/pull/42563
- https://github.com/JuliaLang/julia/pull/42564

**Pull request merged**
