### PR TITLE
[Sundials 5] Build Sundials v5.2 with SuiteSparse 7.2

### PR DESCRIPTION
**Pull request by ViralBShah**
Attempt to build Sundials 5 with SuiteSparse 7.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Not sure where commit b16d3d3995668c9a13c9f4bee8b0113ff6a9cf6d on the sundials repo disappeared. I'm pulling in the v5.2 tag.

**Comment by Wimmerer** [comment]
Weird that KLU is the issue perhaps?

**Comment by giordano** [comment]
> Not sure where commit b16d3d3995668c9a13c9f4bee8b0113ff6a9cf6d on the sundials repo disappeared.

Sounds like they overwrote the history: https://github.com/LLNL/sundials/commit/b16d3d3995668c9a13c9f4bee8b0113ff6a9cf6d.  The commit is still there in the GitHub backend of the repo, but not in the actual Git repo.

**Comment by ViralBShah** [comment]
What is libklu_cholmod? Is it something that SuiteSparse builds? Odd that the issue is only on linux.

**Comment by Wimmerer** [comment]
What if we build 5.8? If they follow semver it should be fine?

**Comment by ViralBShah** [comment]
I don't know enough about Sundials to know whether they follow SEMVER.

**Comment by ViralBShah** [comment]
The issue is:
```
bk;t=1689105137413^G[19:52:17] CMake Warning at config/SundialsCMakeMacros.cmake:83 (message):
bk;t=1689105137413^G[19:52:17]   ------------------------------------------------------------------------
bk;t=1689105137413^G[19:52:17] 
bk;t=1689105137413^G[19:52:17]   WARNING: KLU not functional - support will not be provided
bk;t=1689105137413^G[19:52:17] 
bk;t=1689105137413^G[19:52:17]   Double check spelling of include path and specified libraries (search is
bk;t=1689105137414^G[19:52:17]   case sensitive)
bk;t=1689105137414^G[19:52:17] 
bk;t=1689105137414^G[19:52:17]   ------------------------------------------------------------------------
bk;t=1689105137414^G[19:52:17] Call Stack (most recent call first):
bk;t=1689105137414^G[19:52:17]   CMakeLists.txt:991 (print_warning)
```

So it is some silly PATH issue with finding the include files or the binaries.

**Comment by Wimmerer** [comment]
We should probably make a note to pkgeval everything that this upgrade touches. Even once builds all pass

**Pull request merged**
