### PR TITLE
[LLVM] add patches for JuliaLang/julia#36062

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Comment by vchuravy** [comment]
@yuyichao should these be backported to LLVM 8?

**Comment by yuyichao** [comment]
I believe these two should be although I didn't test on LLVM 8 or 9 to see if they needs to.
Both changes, especially the "backport" of https://reviews.llvm.org/D80101 for stack coloring, should pass another pair of eyes... The change to `CodeGenPrepare` should be pretty safe and will hopefully have reviews from https://reviews.llvm.org/D84031.................

Also note that these two changes aren't related to https://github.com/JuliaLang/julia/issues/36062, they are the two other bugs that I hit when debugging it (actually I hit them only after working around https://github.com/JuliaLang/julia/issues/36062 via https://github.com/JuliaLang/julia/pull/36705 ....).

https://github.com/JuliaLang/julia/issues/36062, which is also the only bug that is easily reprodicible without assertion on and without additional verification passes, is caused by lsr. The instruction is introduced in the pass at https://github.com/llvm/llvm-project/blob/076e08aa4501f682c43e71a8fed1e12da485abc7/llvm/lib/Transforms/Scalar/LoopStrengthReduce.cpp#L5277. AFAICT it may require some "non-local" changes to either change the decision about doing the transformation or change the code pattern it wants to emit...

FWIW, since this is in codegen preparation, it's probably fixable if we simply strip out the address space or remove the NI from the datalayout.

**Comment by vchuravy** [comment]
> FWIW, since this is in codegen preparation, it's probably fixable if we simply strip out the address space or remove the NI from the datalayout.

So we could run the RemoveAddrspacesPass (https://github.com/JuliaLang/julia/blob/master/src/llvm-remove-addrspaces.cpp) instead of disabling LSR?

**Comment by yuyichao** [comment]
> So we could run the RemoveAddrspacesPass (https://github.com/JuliaLang/julia/blob/master/src/llvm-remove-addrspaces.cpp) instead of disabling LSR?

Yes, that might be the case. I'm also testing if we can just change the datalayout since it'll be cheaper. Is that legal?

**Comment by yuyichao** [comment]
It passes initial testing... so I'll do a more complete test to see if it passes full compilation...

**Pull request merged**
