### PR TITLE
Bump CUDNN to 8.0.4

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
Looks like this still redownloads, even though all files are there:

```
tbesard@amdci7 ~sabae/yggstorage/depot/downloads
 % ls eb4b888e61715168f57a0a0a21c281ada6856b728e5112618ed15f8637487715* 690811bbf04adef635f4a6f480575fc2a558c4a2c98c85c7090a3a8c60dacea9* f9a7e6632ac1e2058676eed141d05ce34d8b479df388cdc80334356dce63bac2* c12c69eb16698eacac40aa46b9ce399d4cd86efb6ff0c105142f8a28fcfb980e* 32a5b92f9e1ef2be90e10f220c4ab144ca59d215eb6a386e93597f447aa6507e* 45dc48f6c19d62e4e4f56da216b72cf69454db374ffb6589aca0cf7c309762fa* 38a81a28952e314e21577432b0bab68357ef9de7f6c8858f721f78df9ee60c35* 8da8ed689b1a348182ddd3f59b6758a502e11dc6708c33f96e3b4a40e033d2e1* 1b1438b828ce61888b7f1ed3ac506b32137425dd48aed8bc71abd5d4a7006143*
1b1438b828ce61888b7f1ed3ac506b32137425dd48aed8bc71abd5d4a7006143-cudnn-11.0-windows-x64-v8.0.4.30.zip    8da8ed689b1a348182ddd3f59b6758a502e11dc6708c33f96e3b4a40e033d2e1-cudnn-11.0-linux-ppc64le-v8.0.4.30.tgz
32a5b92f9e1ef2be90e10f220c4ab144ca59d215eb6a386e93597f447aa6507e-cudnn-10.2-linux-ppc64le-v8.0.4.30.tgz  c12c69eb16698eacac40aa46b9ce399d4cd86efb6ff0c105142f8a28fcfb980e-cudnn-10.2-linux-x64-v8.0.4.30.tgz
38a81a28952e314e21577432b0bab68357ef9de7f6c8858f721f78df9ee60c35-cudnn-11.0-linux-x64-v8.0.4.30.tgz      eb4b888e61715168f57a0a0a21c281ada6856b728e5112618ed15f8637487715-cudnn-10.1-linux-x64-v8.0.4.30.tgz
45dc48f6c19d62e4e4f56da216b72cf69454db374ffb6589aca0cf7c309762fa-cudnn-10.2-windows10-x64-v8.0.4.30.zip  f9a7e6632ac1e2058676eed141d05ce34d8b479df388cdc80334356dce63bac2-cudnn-10.1-windows10-x64-v8.0.4.30.zip
690811bbf04adef635f4a6f480575fc2a558c4a2c98c85c7090a3a8c60dacea9-cudnn-10.1-linux-ppc64le-v8.0.4.30.tgz
```

```
Considering C/CUDNN/CUDNN_CUDA101
 --> Accepted!
Considering C/CUDNN/CUDNN_CUDA102
 --> Accepted!
Considering C/CUDNN/CUDNN_CUDA110
 --> Accepted!
Considering C/CUDNN/CUDNN_CUDA111
 --> Accepted!
Generating meta.json...
Downloading sources...
ERROR: LoadError: HTTP/2 403
```

And after the failed run:

```
 % ls eb4b888e61715168f57a0a0a21c281ada6856b728e5112618ed15f8637487715* 690811bbf04adef635f4a6f480575fc2a558c4a2c98c85c7090a3a8c60dacea9* f9a7e6632ac1e2058676eed141d05ce34d8b479df388cdc80334356dce63bac2* c12c69eb16698eacac40aa46b9ce399d4cd86efb6ff0c105142f8a28fcfb980e* 32a5b92f9e1ef2be90e10f220c4ab144ca59d215eb6a386e93597f447aa6507e* 45dc48f6c19d62e4e4f56da216b72cf69454db374ffb6589aca0cf7c309762fa* 38a81a28952e314e21577432b0bab68357ef9de7f6c8858f721f78df9ee60c35* 8da8ed689b1a348182ddd3f59b6758a502e11dc6708c33f96e3b4a40e033d2e1* 1b1438b828ce61888b7f1ed3ac506b32137425dd48aed8bc71abd5d4a7006143*
zsh: no matches found: eb4b888e61715168f57a0a0a21c281ada6856b728e5112618ed15f8637487715*
```

So it immediately deletes one of the downloads...

cc @giordano

**Comment by giordano** [comment]
@staticfloat

**Comment by giordano** [comment]
Do you need to place the files there?

**Comment by maleadt** [comment]
Yeah, Downloads.jl had removed them. Let's try again.

**Pull request merged**
