### PR TITLE
Add Julia_jll 1.5, but keep version for 1.4

### PR DESCRIPTION
**Pull request by fingolfin**
This is an alternative to PR #1439 by @barche which adds Julia 1.5.0 but also keep Julia 1.4 around. I hope that in the future we can then add Julia 1.6, etc. (and perhaps also Julia 1.3).

### CODE REVIEW

**Comment by fingolfin** [comment]
Note: one could in principle reduce the "code duplication" here, but I wasn't sure whether it'd be worth the effort: e.g. the list of supported architectures may change, also perhaps the scheme of download URLs, so it wasn't clear to me what exactly would be a good approach, if any

**Comment by barche** [comment]
I don't understand why this is needed, since we can just specify the version of the package, especially with https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/875 almost merged?

**Comment by fingolfin** [comment]
https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/875 is completely orthogonal to this PR here: 875 restricts the runtime version of Julia, which is completely independent from the Julia used during buildtime. The main motivation for this PR is to leave the sources for older versions of Julia_jll around, so that I can build separate versions of a JLL which needs to link against Julia.

Now, you may argue "but Julia_jll 1.4.1 and 1.4.2 already exist and won't go away", which is true. However, I am still hoping there'll be one last update for the 1.4 Julia_jll which includes both Windows binaries (missing in the current Julia_jll 1.4.2) and a correct macOS binary (partially broken in 1.4.1, see #1372).

Of course one can argue that "1.4 is end of life anyway", but for example Ubuntu 20.04 "Focal", the current Ubuntu LTS, is shipping Julia 1.4.1, so I'd really like to support it for a time to come.

And ideally I'd even like to see a Julia_jll 1.3 but that's indeed getting less and less relevant.

**Comment by giordano** [comment]
Can we merge #1439 and then you rebase this PR on master adding `[skip ci]`  to the commit message?  I don't want to rebuild the tarballs, unless really necessary (and I don't think this is the case for Julua v1.4.1)

**Comment by fingolfin** [comment]
Sure

**Comment by fingolfin** [comment]
I've now rebased this and added the `[skip ci]` as instructed.

**Pull request merged**
