### PR TITLE
[SSGraphBLAS] v5.0 - Don't Merge

### PR DESCRIPTION
**Pull request by Wimmerer**
New version, force compat to 1.6?

### CODE REVIEW

**Comment by giordano** [comment]
> force compat to 1.6?

I guess you should ask to the maintainer of [`SuiteSparseGraphBLAS.jl`](https://github.com/abhinavmehndiratta/SuiteSparseGraphBLAS.jl) whether they're happy about it.

Also, latest version is [v5.6.0](https://github.com/JuliaBinaryWrappers/SuiteSparseGraphBLAS_jll.jl/releases/tag/SuiteSparseGraphBLAS-v5.6.0%2B3)?

**Comment by Wimmerer** [comment]
That's the old builder, we replaced it since it was using the downstream SuiteSparse metapackage. Moving to upstream GraphBLAS we had to move *down* a version.

**Comment by giordano** [comment]
BTW, if you require Julia v1.6 you can also build for the experimental platforms

**Comment by Wimmerer** [comment]
```
Undefined symbols for architecture arm64:
"___divdc3", referenced from:
_complex_div in usercomplex.c.o
_complex_rdiv in usercomplex.c.o
 _complex_minv in usercomplex.c.o
ld: symbol(s) not found for architecture arm64
```

**Comment by ViralBShah** [comment]
Yes, let's go to 1.6 and enable the experimental platforms.

**Comment by Wimmerer** [comment]
5.0.3 fixes some missing exports, please do not merge until I go to 5.0.3﻿

**Pull request merged**
