### PR TITLE
[Tk] Refresh build to include new architectures like mac aarch64

### PR DESCRIPTION
**Pull request by ViralBShah**

### CODE REVIEW

**Comment by ViralBShah** [comment]
The Cocoa framework path in the applied patches is hardcoded and is x86_64 specific. Is this required because our sandbox has stuff in different places compared to a standard macOS?

**Comment by ViralBShah** [comment]
Is this something where we need to build artifacts for more arch triplets for some of these packages?

```
┌ Warning: Dependency Xorg_xtrans_jll does not have a mapping for artifact Xorg_xtrans for platform aarch64-apple-darwin20-libgfortran5-cxx11
└ @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/VItjk/src/Prefix.jl:753
┌ Warning: Dependency Xorg_libXft_jll does not have a mapping for artifact Xorg_libXft for platform aarch64-apple-darwin20-libgfortran5-cxx11
└ @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/VItjk/src/Prefix.jl:753
┌ Warning: Dependency Xorg_libXrender_jll does not have a mapping for artifact Xorg_libXrender for platform aarch64-apple-darwin20-libgfortran5-cxx11
└ @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/VItjk/src/Prefix.jl:753
┌ Warning: Dependency Xorg_libpthread_stubs_jll does not have a mapping for artifact Xorg_libpthread_stubs for platform aarch64-apple-darwin20-libgfortran5-cxx11
└ @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/VItjk/src/Prefix.jl:753
┌ Warning: Dependency Xorg_libX11_jll does not have a mapping for artifact Xorg_libX11 for platform aarch64-apple-darwin20-libgfortran5-cxx11
└ @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/VItjk/src/Prefix.jl:753
┌ Warning: Dependency Xorg_libXdmcp_jll does not have a mapping for artifact Xorg_libXdmcp for platform aarch64-apple-darwin20-libgfortran5-cxx11
└ @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/VItjk/src/Prefix.jl:753
┌ Warning: Dependency Xorg_libXau_jll does not have a mapping for artifact Xorg_libXau for platform aarch64-apple-darwin20-libgfortran5-cxx11
└ @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/VItjk/src/Prefix.jl:753
┌ Warning: Dependency Libuuid_jll does not have a mapping for artifact Libuuid for platform aarch64-apple-darwin20-libgfortran5-cxx11
└ @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/VItjk/src/Prefix.jl:753
┌ Warning: Dependency Xorg_libxcb_jll does not have a mapping for artifact Xorg_libxcb for platform aarch64-apple-darwin20-libgfortran5-cxx11

```

**Comment by giordano** [comment]
No, that's normal, we don't want to use the x11 stack on windows and macos

**Comment by giordano** [comment]
Actually, Xorg_libXft_jll should be made a conditional dependency (only Linux and freebsd)

**Comment by ViralBShah** [comment]
I get this linking error whether using clang ld or not:

```
[17:37:11] Undefined symbols for architecture arm64:
[17:37:11]   "_OBJC_CLASS_$_UTType", referenced from:
[17:37:11]       objc-class-ref in tkMacOSXDialog.o
[17:37:11]       objc-class-ref in tkMacOSXFileTypes.o
[17:37:11] ld: symbol(s) not found for architecture arm64
[17:37:11] clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
[17:37:11] make: *** [Makefile:592: libtk8.6.dylib] Error 1
[17:37:11]  ---> make -j${nproc}
[17:37:11]  ---> make -j${nproc}
[17:37:11] Previous command exited with 2
```

**Comment by ViralBShah** [comment]
I tried various `-mmacosx-min-version` values from 10.0 to 14.0, but doesn't seem to help.

**Comment by giordano** [comment]
Setting `-mmacosx-version-min` doesn't do much without actually using a newer SDK: the symbols are searched by the linker in the stub libraries shipped by the SDK, `-mmacosx-version-min` has (nearly) no effect for the linker.

**Comment by giordano** [comment]
For what is worth, I cloned https://github.com/realjf/MacOSX-SDKs and I couldn't find the symbol `_OBJC_CLASS_$_UTType` in any of the macOS 12.* directories.  I have no clue what library or macOS SDK is supposed to provide it, and searching for it on the Internet is very complicated, because of the dollar sign.

**Comment by giordano** [comment]
`UTType` is mentioned in https://developer.apple.com/documentation/uniformtypeidentifiers/uttype-swift.struct/, with reference to macOS 11.0 as minimum supported version (which is what we use for aarch64 anyway).  But that's Swift documentation, I don't know how that's supposed to work here.

**Comment by ViralBShah** [comment]
Homebrew seems to be able to build this just fine, but they do not do cross compilation like us. Their script:

https://github.com/Homebrew/homebrew-core/blob/a74fd6bb88a76815fc7d88c11a92962c56106cb7/Formula/t/tcl-tk.rb

**Comment by ViralBShah** [comment]
It builds fine on my local machine, which has the current Xcode / SDK.

**Comment by ViralBShah** [comment]
Could this be an issue because `gcc` is being used on aarch64 mac to cross compile? Can `clang` be used and might it help?

**Comment by giordano** [comment]
> Could this be an issue because `gcc` is being used on aarch64 mac to cross compile? Can `clang` be used and might it help?

Sorry, I had missed this. Where are we using gcc on macos? I had a quick look at the recipe but I didn't see it.

**Comment by ViralBShah** [comment]
> Sorry, I had missed this. Where are we using gcc on macos? I had a quick look at the recipe but I didn't see it.

I thought that the configure script looks for `gcc` but picks `cc` and wasn't sure what to make of it: https://buildkite.com/julialang/yggdrasil/builds/12426#019143bd-2aff-4366-9f53-ebfa2ce45104/667-1798

**Comment by giordano** [comment]
I think that printing is confusing: in the entire build log `cc` is mentioned in the compiler invocations, and that's a symlink to clang, not gcc

**Comment by ViralBShah** [comment]
The solution is to just use 8.6.12 for now, which seems to build fine.

**Pull request merged**
