### PR TITLE
Update SDL2_image, and build for arm mac

### LINKED ISSUE #5484: SDL2_image_jll for aarch64-apple-darwin
It would be great if an Apple Silicon build of SDL2_image_jll could be provided.

#5481

### PR DESCRIPTION
**Pull request by aviks**
Will fix #5484

### CODE REVIEW

**Comment by aviks** [comment]
OK, I don't understand why mac (x64 and arm) builds are failing. It seems to be erroring in compiling something from the system framework. The previous version of this package seems to have compiled fine in #428 though that was a while ago.

**Comment by aviks** [comment]
So this seems to be failing to compile the OSX system framework.  Which seems strange. Is it using the wrong compiler somehow? 

```
/opt/aarch64-apple-darwin20/bin/../aarch64-apple-darwin20/sys-root/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:19:21: error: unknown type name ‘nullable’
[18:20:18]    19 | - (id)copyWithZone:(nullable NSZone *)zone;
[18:20:18]       |                     ^~~~~~~~
[18:20:18] /opt/aarch64-apple-darwin20/bin/../aarch64-apple-darwin20/sys-root/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:19:29: error: expected ‘)’ before ‘NSZone’
[18:20:18]    19 | - (id)copyWithZone:(nullable NSZone *)zone;
[18:20:18]       |                             ^~~~~~~
[18:20:18]       |                             )

```

**Comment by aviks** [comment]
So using Cmake rather than autoconf makes the build work for macs. There are a few warning from the auditor on apple, but I'm not sure if I should be worried about those? 

Also, I'm wondering if all the SDL2_* builds should now be moved to cmake?

**Comment by giordano** [comment]
> There are a few warning from the auditor on apple, but I'm not sure if I should be worried about those?

I don't see any warnings (`@warn` log messages) from the auditor?  All other messages are fine

> Also, I'm wondering if all the SDL2_* builds should now be moved to cmake?

Maybe next time we update them, but I wouldn't touch existing builds.

**Pull request merged**
