### PR TITLE
add telnet

### PR DESCRIPTION
**Pull request by Moelf**

### CODE REVIEW

**Comment by giordano** [comment]
We can't compile this with our old glibc, sigh.

**Comment by Moelf** [comment]
also the tests were passing yesterday what happened

**Comment by giordano** [comment]
[`6a59a8e` (#4978)](https://github.com/JuliaPackaging/Yggdrasil/pull/4978/commits/6a59a8ee79bf2afd0b0d9b7768e08d9b16ae1b56)

**Comment by giordano** [comment]
#4879

**Comment by giordano** [comment]
Maybe using OpenSSL?  I don't know if telnet would like it, but maybe you can try that

**Comment by Moelf** [comment]
https://github.com/JuliaParallel/ClusterManagers.jl/blob/ff73e36e108cfd6810d6689c51696930a7503f63/src/condor.jl#L29

I don't think this usage can be replaced telnet -> ssh

**Comment by giordano** [comment]
I'm not sure what you mean

**Comment by Moelf** [comment]
what do you mean by using OpenSSH?

**Comment by giordano** [comment]
I [said](https://github.com/JuliaPackaging/Yggdrasil/pull/4978#issuecomment-1144991655)

> Maybe using OpenSSL?

not OpenSSH.  And I was answering [your question](https://github.com/JuliaPackaging/Yggdrasil/pull/4978#issuecomment-1144981880)

> how does OpenSSH manage to compile?

since OpenSSH has OpenSSL as dependency https://github.com/JuliaPackaging/Yggdrasil/blob/7289473d58445a58f358c48e77aab0f7540c0223/O/OpenSSH/build_tarballs.jl#L71

**Comment by Moelf** [comment]
nvm, giving up until we have a new glibc I guess

**Comment by giordano** [comment]
For reference, #5501 should help with bringing this forward

**Comment by giordano** [comment]
This is now working right, but the tarball contains more than just telnet
```console
% wget -qO - 'https://julia-bb-buildcache.s3.amazonaws.com/b3e17edd0a76ae284c75f005918cd5a057f51d90b4025ed8dcc50be94582a6f5/689dad91b3ed55dda9f7626cd782bb86a2c22caec1f24fc879710327f24878ce/x86_64-linux-gnu.tar.gz' | tar tzv | grep 'bin/'
-rwxr-xr-x 0/0          229400 1970-01-01 01:00 bin/dnsdomainname
-rwxr-xr-x 0/0          589530 1970-01-01 01:00 bin/ftp
-rwxr-xr-x 0/0          342920 1970-01-01 01:00 bin/ping
-rwxr-xr-x 0/0          288017 1970-01-01 01:00 bin/ping6
-rwxr-xr-x 0/0          288397 1970-01-01 01:00 bin/talk
-rwxr-xr-x 0/0          475518 1970-01-01 01:00 bin/telnet
-rwxr-xr-x 0/0          305131 1970-01-01 01:00 bin/whois
```
Also, the log shows
```
[23:17:14] Summary of build decisions:
[23:17:14] 
[23:17:14]   Clients:
[23:17:14] 
[23:17:14]     telnet         yes  -lncurses
[23:17:14]     tftp           no
[23:17:14]     traceroute     no
[23:17:14]     whois          yes
[23:17:14] 
[23:17:14]   Servers:
[23:17:14] 
[23:17:14]     ftpd           yes  
[23:17:14]     inetd          no
[23:17:14]     rexecd         no
[23:17:14]     rlogind        yes  
[23:17:14]     rshd           yes  
[23:17:14]     syslogd        no
[23:17:14]     talkd          yes
[23:17:14]     telnetd        yes  -lncurses
[23:17:14]     tftpd          no
[23:17:14]     uucpd          yes
[23:17:14] 
[23:17:14]   Support:
[23:17:14] 
[23:17:14]     libls          yes
```
I presume you wanted _only_ telnet, right?

**Comment by Moelf** [comment]
That's right

**Comment by giordano** [comment]
Now I get
```
Summary of build decisions:

  Clients:

    dnsdomainname  no
    ftp            no
    hostname       no
    ifconfig       no
    logger         no
    ping           no
    ping6          no
    rcp            no
    rexec          no
    rlogin         no
    rsh            no
    talk           no
    telnet         yes  -lncurses
    tftp           no
    traceroute     no
    whois          no

  Servers:

    ftpd           no
    inetd          no
    rexecd         no
    rlogind        no
    rshd           no
    syslogd        no
    talkd          no
    telnetd        no
    tftpd          no
    uucpd          no

  Support:

    libls          yes
```
It this what you want?  Only telnet client, not the server.

**Comment by Moelf** [comment]
Yeah that looks right to me

**Pull request merged**
