### PR TITLE
[CoinUtils] build on experimental platforms

### PR DESCRIPTION
**Pull request by odow**

### CODE REVIEW

**Comment by giordano** [comment]
Need to build with OpenBLAS32 v0.3.10 at least

**Comment by odow** [comment]
I'm a bit nervous doing this, because the coin-or dependency tree is quite entangled, and we've had compatibility issues with various patch releases along the way :(

**Comment by giordano** [comment]
OpenBLAS32 should be pretty safe, all versions have same API/ABI (_last famous words_ 😉). It's the ILP64 version which is more complex, as you've seen

**Comment by odow** [comment]
I more meant rebuilding chain of
```
CoinUtils -> Osi -> Clp -> Cgl -> Cbc -> Symphony -> Alps -> Biceps -> Chipps_BLIS -> MibS                                     
ASL -> Ipopt                          -> Bonmin -> Couenne
                                      -> SHOT
```
Along the way I want to bump some patch releases :(

**Pull request merged**
