### PR TITLE
[SuiteSparse] Delete extra SuiteSparse libraries on Windows

### LINKED ISSUE #7: Win32 SuiteSparse build is subtly borked
It's installing 3 copies of every dll, and loading 2 of each at runtime.

### PR DESCRIPTION
**Pull request by ViralBShah**
Fix #7

### CODE REVIEW

**Comment by ViralBShah** [comment]
Is there a way to inspect the contents of the CI produced windows tarball?

**Comment by giordano** [comment]
Looks ok:
```
products/SuiteSparse.v5.4.0.i686-w64-mingw32% ls bin 
libamd.dll  libcamd.dll     libcholmod.dll  libklu.dll  librbio.dll  libsuitesparseconfig.dll    libumfpack.dll
libbtf.dll  libccolamd.dll  libcolamd.dll   libldl.dll  libspqr.dll  libsuitesparse_wrapper.dll
```

However note that we're not installing the license:
```
┌ Warning: Unable to find valid license file in "${prefix}/share/licenses/SuiteSparse"
└ @ BinaryBuilder /depot/packages/BinaryBuilder/xbKKQ/src/Auditor.jl:416
```

Please, don't merge this, registration won't work until #485 is fixed

**Comment by ViralBShah** [comment]
Btw, there is no reason for this to be called `SuiteSparse@5`. Can I rename it to `SuiteSparse`, since the old one has been removed?

**Comment by ViralBShah** [comment]
There's a LICENSE.txt in the root directory. I thought it used to get automatically picked up in the past.

https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/master/LICENSE.txt

**Comment by giordano** [comment]
> Btw, there is no reason for this to be called SuiteSparse@5. Can I rename it to SuiteSparse, since the old one has been removed?

If we aren't going to support other versions at the same time probably yes

> I thought it used to get automatically picked up in the past.

The logic to automatically install the license file is the following: if under `/workspace` there is only one directory, or at most two one of which is called `patches`, then install all files with a sensible name.

Here under `/workspace` there are three directories because there is also the wrapper, so the license is not automatically installed

**Comment by ViralBShah** [comment]
Ok, I'm going to remove the `@5` and also fix the license file.

**Comment by ViralBShah** [comment]
@giordano ok to merge?

**Pull request merged**
