### PR TITLE
ADIOS2: New version 2.10.1

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by eschnett** [comment]
I disabled Windows builds. They seem thoroughly broken. I hope they work again in later versions of ADIOS2.

**Comment by eschnett** [comment]
*ping*

**Comment by giordano** [comment]
In general I'm not a fan of dropping widely used platforms like Windows, but you also maintain the Julia wrapper so I guess you're happy to deal with potentially unhappy users. Were the build issues reported upstream?

**Comment by eschnett** [comment]
Windows builds are enabled again, with the help of the ADIOS2 developers.

**Comment by giordano** [comment]
Awesome, thanks!

**Pull request merged**
