### PR TITLE
[PCL] increment version number and SHA, remove upstream merged patches

### PR DESCRIPTION
**Pull request by Crghilardi**
This updates the version and SHA to the latest release as well as removing patches that were merged upstream. :crossed_fingers:

### CODE REVIEW

**Comment by giordano** [comment]
Uhm, I guess I'll need to refresh the hacky patch. I just hope they didn't break it too much 😣

**Comment by giordano** [comment]
Ok, this is bizarre, locally it works for me :confused: :confused:

**Comment by Crghilardi** [comment]
Was there something going on with FLANN? I looked and the version seemed recent enough?

**Comment by giordano** [comment]
There was an issue with the `FLANN_jll` package in the build machine.  I removed it and then it was fine

**Pull request merged**
