### PR TITLE
rebuild libjulia 1.5 with more platforms

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by giordano** [comment]
Oh wow, only Windows passing

**Comment by fingolfin** [comment]
Apparently the last minute pattern matching change which was meant to remove `julia_version+1.5` didn't work *sigh*. I'll fix it

BTW, any point in upgrading this to Julia 1.5.2? It shouldn't matter for creating binaries, should it?

**Comment by giordano** [comment]
> BTW, any point in upgrading this to Julia 1.5.2?

No problem with me

> It shouldn't matter for creating binaries, should it?

Of course it doesn't matter (_famous last words_)

**Comment by fingolfin** [comment]
Only thing I can think of is that perhaps `extglob` is off in the bash used by the builder -- or that the builder is not using bash at all?

Errr, I feel stupid for asking, but what was again the BB command I can use to just get into a BB drive shell from inside a Julia session?

**Comment by fingolfin** [comment]
anyway, my guess about extglob seems to have been right. I'll clean this up and push again

**Comment by giordano** [comment]
> Errr, I feel stupid for asking, but what was again the BB command I can use to just get into a BB drive shell from inside a Julia session?

https://juliapackaging.github.io/BinaryBuilder.jl/dev/FAQ/#Can-I-open-a-shell-in-a-particular-build-environment-for-doing-some-quick-tests?

**Comment by fingolfin** [comment]
Thanks. I swear I looked at the FAQ but somehow I've been blind. And I actually *thought* it was something like `runshell`, but what got me is that typing `BinaryBuilder.r` and then using tab completion showed nothing :-(.

Anyway, this PR seems to be ready now.

**Comment by giordano** [comment]
This is extremely weird: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=6892&view=results tarballs have been rebuilt, registration failed with
```
ERROR: LoadError: GitError(Code:ENOTFOUND, Class:Repository, could not find repository from '/depot/dev/libjulia_jll')
```
:neutral_face:

**Comment by giordano** [comment]
The hash of the cache is the same between the build in the PR
```
 ---> libjulia@1.5: 89ab26b9984c1901081496b5fb38d281932e1821/9f8fcdbad21ef86d350a699dafbd74773935f8a864d3e90b5a97216c056d745f (feba77188d6e0094f450023145045aac19c1e7c8 + 7473776126221ac7a4d35ea45bc110f44e4c13262b61d1069428346d1918a384)
```
and the build in master
```
 ---> libjulia@1.5: 89ab26b9984c1901081496b5fb38d281932e1821/9f8fcdbad21ef86d350a699dafbd74773935f8a864d3e90b5a97216c056d745f (feba77188d6e0094f450023145045aac19c1e7c8 + 7473776126221ac7a4d35ea45bc110f44e4c13262b61d1069428346d1918a384)
```
I'm extremely confused why they were rebuilt

**Comment by giordano** [comment]
It worked after I kicked the failed job, I still don't understand

1. why the tarballs have been rebuilt on master
2. how `/depot/dev/libjulia_jll` disappeared

**Pull request merged**
