### PR TITLE
[qr_mumps] Rebuild for SuiteSparse 7

### PR DESCRIPTION
**Pull request by ViralBShah**
Fake version bump to be able to set compat for Julia 1.10.

### CODE REVIEW

**Comment by amontoison** [comment]
@ViralBShah Why do you need to change the compat entry?
I planned to recompile `qr_mumps` with LBT.
Let's do that in the same time.

**Comment by ViralBShah** [comment]
Julia 1.10 will include SuiteSparse 7. I believe if we just compile the same existing version with the latest SuiteSparse and update the binaries, there will be a clash for older releases of Julia. Perhaps there is a better way of doing this?

I thought about doing the transition to libblastrampoline, but then the upstream package probably needs to make sure that an LP64 BLAS is always present - which is not available by default.

**Comment by amontoison** [comment]
We should test `QRMumps.jl` on Julia 1.10 before.
Julia will automatically use the libamd.$dlext of SuiteSparse 7 instead of SuiteSparse 5.
I don't think that it will break something because AMD is just an ordering package (like METIS) and it's not updated very often.

If something is not working anymore, we need to add a compat entry of `suitesparse_jll` with the version (7.x.x?) that is provided by Julia 1.10.

**Comment by ViralBShah** [comment]
Just FYI - I created https://github.com/JuliaLinearAlgebra/OpenBLAS32.jl to make it easy for packages that use LP64 BLAS to link to libblastrampoline.

**Pull request closed without merging**
