### PR TITLE
Add libjulia 1.5.4

### PR DESCRIPTION
**Pull request by devmotion**
This PR tries to solve https://github.com/JuliaPackaging/Yggdrasil/pull/2792#issuecomment-816174683. I just updated the version number and the checksum - maybe this should be done differently or something is missing?

### CODE REVIEW

**Comment by giordano** [comment]
For the failure on macOS see [`e5f6b33` (#1987)](https://github.com/JuliaPackaging/Yggdrasil/pull/1987/commits/e5f6b33647f8f32a8eb4fe26b75518ee5ab287ea).

However I have no clue how this is going to work in terms of compatibility, @staticfloat do you have more insights?

**Comment by staticfloat** [comment]
What are the compatibility concerns you're thinking of?

**Comment by giordano** [comment]
libjulia 1.5.4 is incompatible with previous 1.5.x versions, because of changes to an internal data structure: https://github.com/TuringLang/Turing.jl/pull/1568#issuecomment-815368746

**Comment by staticfloat** [comment]
Seems that users can just bound their compat entries accordingly, if they are sensitive to the layout.  That is really unfortunate, but I can see how it slipped through.

**Comment by barche** [comment]
Closing this in favor of the rebased version at #3418

**Pull request closed without merging**
