### PR TITLE
[ParU] Update to v1.0.0

### PR DESCRIPTION
**Pull request by mzy2240**

### CODE REVIEW

**Comment by mzy2240** [comment]
@ViralBShah is it possible to approve and merge?

**Comment by ericphanson** [comment]
fyi, the package is not loadable: https://github.com/JuliaRegistries/General/pull/118860

**Comment by ViralBShah** [comment]
It's always challenging to pull in other SuiteSparse libraries and get the dependency ordering right.

**Comment by imciner2** [comment]
> fyi, the package is not loadable: https://github.com/JuliaRegistries/General/pull/118860

I believe this is to be expected for Julia 1.11. This version of ParU requires 7.8.3, but that currently only has 7.7.0 in it. Since SuiteSparse is a stdlib, we are limited to compatibility with the version that is included in the Julia release - so this version of ParU won't install there. I actually don't think this will even install on Julia master, since that only has SuiteSparse 7.8.3, and this will have a dependency that is strict equality with SuiteSparse 7.8.3.

**Comment by ViralBShah** [comment]
We can go bump master to 7.8.3.

**Comment by rayegun** [comment]
I specifically wanted to avoid updating ParU yet for this reason, since the PR that works on 1.11 previously failed... I wish we could have a codeowners on this haha

I'll have to do some fiddling here, although Tim said we can probably attempt to build ParU v1 against older versions of SuiteSparse_config and the other packages

**Comment by ViralBShah** [comment]
I didn't realize - will ping you on future ones!

**Pull request merged**
