### PR TITLE
Bison: update to 3.8.2, enable more platforms

### PR DESCRIPTION
**Pull request by fingolfin**
As an experiment, I've also turned Windows back on, just to say if / how that fails.

### CODE REVIEW

**Comment by fingolfin** [comment]
Nice, Windows build seems to work! On macOS it warns about libiconv, so let's try to deal with that...

**Comment by fingolfin** [comment]
It's a bit annoying that the executable is referenced via `:bison_exe` and not `:bison`. and that the package name is `Bison_jll` not `bison_jll` (compared to sed_jll, grep_jll, flex_jll, ...). But I guess it can't be helped now...?!

**Comment by giordano** [comment]
> On macOS it warns about libiconv, so let's try to deal with that...

I'm the responsible for those pesky audit warnings. For more information about them see https://github.com/JuliaGtk/GtkSourceWidget.jl/pull/9 and https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/591. However I haven't seen many issues recently (although that warning is still often printed), so I wonder whether the warning is a bit too aggressive..

**Comment by fingolfin** [comment]
No worries :-) Given that sed_jll and grep_jll also use libiconv_jll, I don't mind *shrug*

**Comment by fingolfin** [comment]
All in all this was quite easy and straightforward... ;-)

**Comment by giordano** [comment]
It looks like the package isn't used anywhere, at least according to https://juliahub.com/ui/Packages/Bison_jll/AcV4i/3.5.2+0?page=2. Maybe we can rename the product at least? 😬

**Comment by fingolfin** [comment]
Sure, why not. I mean, if someone *really* uses it, they can complain and we can change it back or they adjust or... *shrug*

**Pull request merged**
