### PR TITLE
Wizard recipe: libsharp2-v1.0.0

### PR DESCRIPTION
**Pull request by ziotom78**
This pull request contains a new build recipe I built using the BinaryBuilder.jl wizard:

* Package name: libsharp2
* Version: v1.0.0

@staticfloat please review and merge.

### CODE REVIEW

**Comment by giordano** [comment]
Uhm:
```
[ Info: Checking shared library lib/libmudflap.so
ERROR: could not load library "/agent/_work/1/s/L/libsharp2/build/x86_64-linux-gnu/2z6HVvrR/destdir/lib/libmudflap.so"
/agent/_work/1/s/L/libsharp2/build/x86_64-linux-gnu/2z6HVvrR/destdir/lib/libmudflap.so: undefined symbol: _start
[ Info: ../artifacts/73fc9d78961d0609aa1ccc8ffd8594bef9dd9d3c/lib/libmudflap.so.0.0.0 already has SONAME "libmudflap.so.0"
/agent/_work/1/s/L/libsharp2/build/x86_64-linux-gnu/2z6HVvrR/destdir/lib/libmudflapth.so.0.0.0: undefined symbol: _start
[ Info: ../artifacts/73fc9d78961d0609aa1ccc8ffd8594bef9dd9d3c/lib/libmudflapth.so.0.0.0 already has SONAME "libmudflapth.so.0"
[ Info: Checking shared library lib/libobjc.so
[ Info: ../artifacts/73fc9d78961d0609aa1ccc8ffd8594bef9dd9d3c/lib/libobjc.so.4.0.0 already has SONAME "libobjc.so.4"
[ Info: Checking shared library lib/libobjc.so.4
[ Info: ../artifacts/73fc9d78961d0609aa1ccc8ffd8594bef9dd9d3c/lib/libobjc.so.4.0.0 already has SONAME "libobjc.so.4"
[ Info: Checking shared library lib/libobjc.so.4.0.0
[ Info: ../artifacts/73fc9d78961d0609aa1ccc8ffd8594bef9dd9d3c/lib/libobjc.so.4.0.0 already has SONAME "libobjc.so.4"
[ Info: Checking shared library lib/libquadmath.so
[ Info: ../artifacts/73fc9d78961d0609aa1ccc8ffd8594bef9dd9d3c/lib/libquadmath.so.0.0.0 already has SONAME "libquadmath.so.0"
[ Info: Checking shared library lib/libquadmath.so.0
[ Info: ../artifacts/73fc9d78961d0609aa1ccc8ffd8594bef9dd9d3c/lib/libquadmath.so.0.0.0 already has SONAME "libquadmath.so.0"
[ Info: Checking shared library lib/libquadmath.so.0.0.0
[ Info: ../artifacts/73fc9d78961d0609aa1ccc8ffd8594bef9dd9d3c/lib/libquadmath.so.0.0.0 already has SONAME "libquadmath.so.0"
[ Info: Checking shared library lib/libsharp2.so
ERROR: could not load library "/agent/_work/1/s/L/libsharp2/build/x86_64-linux-gnu/2z6HVvrR/destdir/lib/libsharp2.so"
libgomp.so.1: cannot open shared object file: No such file or directory
[ Info: lib/libsharp2.so.0.0.0 already has SONAME "libsharp2.so.0"
[ Info: Checking shared library lib/libsharp2.so.0
ERROR: could not load library "/agent/_work/1/s/L/libsharp2/build/x86_64-linux-gnu/2z6HVvrR/destdir/lib/libsharp2.so.0"
libgomp.so.1: cannot open shared object file: No such file or directory
[ Info: lib/libsharp2.so.0.0.0 already has SONAME "libsharp2.so.0"
[ Info: Checking shared library lib/libsharp2.so.0.0.0
ERROR: could not load library "/agent/_work/1/s/L/libsharp2/build/x86_64-linux-gnu/2z6HVvrR/destdir/lib/libsharp2.so.0.0.0"
libgomp.so.1: cannot open shared object file: No such file or directory
```

This is failing just like #336, even though the error messages are different

**Comment by ziotom78** [comment]
I'm puzzled as well. Locally, BinaryBuilder was able to complete all the jobs…

**Comment by giordano** [comment]
Yes, it works for me as well.  Also in #336 it works locally for me.  Let's hope @staticfloat can shed some light on this mystery

**Comment by staticfloat** [comment]
I believe the issue is that the Julia sitting outside of the sandbox, in the main agent environment, is lacking `libgomp` itself.  So although we "assume" that all the CSLs are available, they actually aren't.  This will be fixed when we ship CSL_jll with Julia, but until then I think I can work around it by ensuring that the agent rootfs has a `libgomp` within it.  I've [added `libgomp1`]() as a package to be installed globally in the agent install script for now; that looks like it's solved the problem. :D

**Comment by giordano** [comment]
Why can't it use the libgomp that is in CSL though?

**Comment by staticfloat** [comment]
I think it's because `libgomp` is listed in the lists of `should_ignore_lib()` in `auditor/dynamic_linkage.jl`.  That prevents us from rewriting the dependency path to use a relative path.  I'm not sure if we should change that; I'll have to think on it.  Or you'll have to convince me.  :P

The intention with the `should_ignore_lib()` stuff was to not bother changing things taht will always be available on the target system (like `libc.so`).  Our philosophy has changed a bit since then, and we are providing _many_ more things than we used to, including `libgomp`.  It may be that we should remove it from that list.

**Pull request merged**
