### PR TITLE
first version of Pythia8

### PR DESCRIPTION
**Pull request by jstrube**

### CODE REVIEW

**Comment by giordano** [comment]
I think you wanted to rebase?

Also, since this seems a common pattern, note that working on `master` is generally speaking a bad idea when using the GitHub workflow.  See also https://github.com/JuliaPackaging/Yggdrasil/pull/405#issuecomment-576012097

**Comment by giordano** [comment]
Note also that our CI system looks to all files modified in the PR in order to decide what to build: this has 536 files changed, I had to cancel the job, it would have built _all_ projects in Yggdrasil.

**Comment by giordano** [comment]
@jstrube Feel free to reopen a new PR of course, but I had to close this one because I think it was not going to work unless you properly rebase on `origin/master`, after a hard reset on your original commit.

**Comment by jstrube** [comment]
aargh! Sorry about this.

**Pull request closed without merging**
