### PR TITLE
[SuiteSparse_GPU] add new build to experiment with GPU support

### PR DESCRIPTION
**Pull request by ViralBShah**
Bump to 5.8.1
Enable METIS
Enable SLIP_LU
Use MKL
Build with GPU support

### CODE REVIEW

**Comment by staticfloat** [comment]
Yes, this is the right way to do it.

I'm not 100% certain, but I believe that SuiteSparse is loaded eagerly by Julia, so you won't be able to load, e.g. a new `libcholmod` from a separate JLL.  You can still build this, but you'll probably need to forcibly replace the ones that ship with Julia with this one, for instance.

**Comment by ViralBShah** [comment]
For purposes of experimentation, using these binaries to overwrite the ones in Julia would be ok. I'm hoping that after 1.6 branches, we can start figuring out how to loosen the coupling of all the sparse matrix stuff in stdlib.

**Comment by staticfloat** [comment]
Yes, I hope that by the time v1.7 comes around, we'll have much more flexible JLL selection as well.

**Comment by ViralBShah** [comment]
@staticfloat @giordano I guess this would be ok to merge and won't interfere with stdlib stuff, right?

**Comment by ViralBShah** [comment]
cc @andreasnoack @ranjanan @dkarrasch as an fyi.

**Comment by ViralBShah** [comment]
Did not get merged: https://github.com/JuliaRegistries/General/pull/24943/checks?check_run_id=1423766662

There's some more CUDA readiness needed that @maleadt is going to be looking into.

**Pull request merged**
