### PR TITLE
[Git] Version v2.29.1

### PR DESCRIPTION
**Pull request by staticfloat**

### CODE REVIEW

**Comment by staticfloat** [comment]
@giordano uh oh; it appears that `collect_jlls()` is not selecting `nghttp2_jll` here, when I think it should be?

**Comment by giordano** [comment]
😞

I was wondering at what point we'll need to test that function, at least we now have a good test case

**Comment by giordano** [comment]
Actually, the problem is that `LibCURL_jll` doesn't list `nghttp2_jll` in the dependencies, so you need to do something like https://github.com/JuliaPackaging/Yggdrasil/blob/6866b1c1986edfe7587e7624421999c24ab18f3e/G/GDAL/build_tarballs.jl#L105-L109 (or properly add all the missing JLL stdlibs :wink:)

**Comment by staticfloat** [comment]
Ah, fantastic catch Mosè!  I'll fix that in Julia immediately.

**Comment by staticfloat** [comment]
I thought I checked that, but I checked the actual MbedTLS package, not the dummy JLL.  😂

**Pull request closed without merging**
