### PR TITLE
[FFMPEG] Build `ffplay`

### PR DESCRIPTION
**Pull request by yakir12**
Added ffplay to the party.
Solves https://github.com/JuliaIO/FFMPEG.jl/issues/31

### CODE REVIEW

**Comment by giordano** [comment]
It doesn't seem we're building it at all

**Comment by yakir12** [comment]
Yea, I'm way over my head here. What's missing?

**Comment by giordano** [comment]
No idea :slightly_smiling_face:

**Comment by yakir12** [comment]
LOL... I'll take this up with at slack#video, see if anyone knows...

**Pull request closed without merging**
