### PR TITLE
[platforms/cuda.jl] Provide full CUDA version numbers

### PR DESCRIPTION
**Pull request by jkrimmer**
Locally building tarballs with CUDA support currently leads to an error message similar to `ERROR: LoadError: KeyError: key v"11.4.4" not found` (here, for CUDA 11.4, see also the issue described on [Julia Discourse](https://discourse.julialang.org/t/compiling-cuda-code-with-binarybuilder/109638). This PR provides the full version numbers such that the corresponding `CUDA_SDK_jll` and `CUDA_SDK_Static_jll` are found by Pkg.

Best
Jonas

### CODE REVIEW

**Comment by giordano** [comment]
Full version number, including build number, looks unsustainable and error-prone.

**Comment by jkrimmer** [comment]
I absolutely agree with that. However, in the current state, Pkg does not seem find the desired jll as long as the build number is missing.

**Comment by jkrimmer** [comment]
If I try to build NCCL locally on julia 1.10.4 with the current Yggdrasil master, I receive exactly the same error
```
ERROR: LoadError: KeyError: key v"11.4.4" not found
Stacktrace:
  [1] getindex
    @ ./dict.jl:498 [inlined]
  [2] resolve_versions!(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, julia_version::Nothing, installed_only::Bool)
    @ Pkg.Operations ~/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:446
  [3] targeted_resolve(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, preserve::Pkg.Types.PreserveLevel, julia_version::Nothing)
    @ Pkg.Operations ~/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1361
  [4] tiered_resolve(env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, julia_version::Nothing, try_all_installed::Bool)
    @ Pkg.Operations ~/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1333
  [5] _resolve(io::Base.TTY, env::Pkg.Types.EnvCache, registries::Vector{Pkg.Registry.RegistryInstance}, pkgs::Vector{Pkg.Types.PackageSpec}, preserve::Pkg.Types.PreserveLevel, julia_version::Nothing)
    @ Pkg.Operations ~/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1371
  [6] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}, new_git::Set{Base.UUID}; preserve::Pkg.Types.PreserveLevel, platform::Platform)
    @ Pkg.Operations ~/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1388
  [7] add
    @ ~/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/share/julia/stdlib/v1.10/Pkg/src/Operations.jl:1377 [inlined]
  [8] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Platform, kwargs::@Kwargs{io::Base.TTY})
    @ Pkg.API ~/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/share/julia/stdlib/v1.10/Pkg/src/API.jl:278
  [9] Pkg_add(::Pkg.Types.Context, ::Vararg{Any}; kwargs::@Kwargs{platform::Platform, io::Base.TTY})
    @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/VItjk/src/Prefix.jl:611
 [10] (::BinaryBuilderBase.var"#95#101"{Bool, Prefix, Vector{Pkg.Types.PackageSpec}, Platform, Vector{String}, Vector{String}})()
    @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/VItjk/src/Prefix.jl:679
 [11] activate(f::BinaryBuilderBase.var"#95#101"{Bool, Prefix, Vector{Pkg.Types.PackageSpec}, Platform, Vector{String}, Vector{String}}, new_project::String)
    @ Pkg.API ~/.julia/juliaup/julia-1.10.4+0.x64.linux.gnu/share/julia/stdlib/v1.10/Pkg/src/API.jl:1980
 [12] setup_dependencies(prefix::Prefix, dependencies::Vector{Pkg.Types.PackageSpec}, platform::Platform; verbose::Bool)
    @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/VItjk/src/Prefix.jl:670
 [13] setup_dependencies
    @ ~/.julia/packages/BinaryBuilderBase/VItjk/src/Prefix.jl:640 [inlined]
 [14] (::BinaryBuilder.var"#setup_deps#27")(f::typeof(BinaryBuilderBase.is_target_dependency), prefix::Prefix, dependencies::Vector{BinaryBuilderBase.AbstractDependency}, platform::Platform, verbose::Bool)
    @ BinaryBuilder ~/.julia/packages/BinaryBuilder/L8tBh/src/AutoBuild.jl:825
 [15] autobuild(dir::AbstractString, src_name::AbstractString, src_version::VersionNumber, sources::Vector{<:BinaryBuilderBase.AbstractSource}, script::AbstractString, platforms::Vector, products::Vector{<:Product}, dependencies::Vector{<:BinaryBuilderBase.AbstractDependency}; verbose::Bool, debug::Bool, skip_audit::Bool, ignore_audit_errors::Bool, autofix::Bool, code_dir::Union{Nothing, String}, require_license::Bool, dont_dlopen::Bool, kwargs...)
    @ BinaryBuilder ~/.julia/packages/BinaryBuilder/L8tBh/src/AutoBuild.jl:828
 [16] build_tarballs(ARGS::Any, src_name::Any, src_version::Any, sources::Any, script::Any, platforms::Any, products::Any, dependencies::Any; julia_compat::String, kwargs...)
    @ BinaryBuilder ~/.julia/packages/BinaryBuilder/L8tBh/src/AutoBuild.jl:363
 [17] top-level scope
    @ ~/work/tmp/Yggdrasil/N/NCCL/build_tarballs.jl:63
in expression starting at /home/ws/mv6955/work/tmp/Yggdrasil/N/NCCL/build_tarballs.jl:58
```
Maybe I have to clean up my `.julia` directory?

**Comment by maleadt** [comment]
Yeah, it took me a while to realize as well. Although right now it looks like BinaryBuilder prints a warning?

```
❯ rm -rf build products; julia +1.8 --project build_tarballs.jl --verbose --debug x86_64-linux-gnu
ERROR: LoadError: InitError: BinaryBuilder supports only Julia v1.7.
Contribute to JuliaPackaging/JLLPrefixes.jl#6 (<https://github.com/JuliaPackaging/JLLPrefixes.jl/issues/6>)
if you care about supporting newer versions of Julia.
```

If you want to fully mimic the CI env, it's recommended to use the `.ci/Manifest.toml` (e.g., by simlinking it into the `Yggdrasil` root check-out folder).

**Comment by jkrimmer** [comment]
Because I have never referred to the `.ci` directory, I have never encoutered this error message so far. Thank you!

**Pull request closed without merging**
