### PR TITLE
Patch categorical support for mlpack

### PR DESCRIPTION
**Pull request by rcurtin**
It was recently discovered in mlpack/mlpack#2973 that mlpack's Julia bindings segfault when a user is trying to learn a model on categorical data.  This was traced to a fairly simple patch, but, a new mlpack release is not coming soon since the library is currently in a heavy state of refactoring to reduce its dependencies.

Therefore, I took the relevant patch from that PR and backported it into the `mlpack_jll` package here.

One thing I am not sure of is whether I need to bump the package version from 3.4.2 so that Julia will automatically update the package.  If so, I'd bump it to something like 3.4.2-1, but I think that is not a valid Julia version number... someone please correct me with whatever the right thing is here. :)

### CODE REVIEW

**Comment by rcurtin** [comment]
Did the names of symbols in OpenBLAS change recently or something?  That is what the build failure looks like, but maybe someone who has spent more time in the OpenBLAS code can comment... (presumably it will be an easy fix to the `armadillo_jll` package).

**Comment by giordano** [comment]
> One thing I am not sure of is whether I need to bump the package version from 3.4.2 so that Julia will automatically update the package. If so, I'd bump it to something like 3.4.2-1, but I think that is not a valid Julia version number... someone please correct me with whatever the right thing is here. :)

3.4.2-1 is a valid `VersionNumber`:
```julia
julia> v"3.4.2-1"
v"3.4.2-1"
```
However, the problem is that the package manager doesn't really like anything outside of the basic <major>.<minor>.<patch> versioning scheme, so we recommend to not add anything to that.

Just to contradict what I've just said and make the package manager angry, JLL packages use the build number.  For example, current version of `mlpack_jll` is `3.4.2+0`.  If you don't change the version number here, the next build will have the build number increased to 1, so next version will be `3.4.2+1`.

I think adding a hot-fix patch without changing the version number is totally reasonable.

**Comment by giordano** [comment]
> Did the names of symbols in OpenBLAS change recently or something?

Ugh, yes.  Since version 0.3.13 aarch64 has ILP64, like all other 64-bit platforms: #2465.  This is reasonable, but also means that this conflicts with previous versions :persevere:  You can change the dependency
```julia
    Dependency("OpenBLAS_jll")
```
to
```
    Dependency("OpenBLAS_jll", v"0.3.10")
```
which means to use v0.3.10 for the build.

**Comment by rcurtin** [comment]
Perfect, I won't worry about the version number then.

For OpenBLAS, honestly I'd rather update `armadillo_jll` to correctly use ILP64 on aarch64.  I suppose I will need to open a different PR for that... hang on...

**Comment by rcurtin** [comment]
I see... so perhaps #3145 is not the right solution here.  I pushed 6f80fa85 to this branch, which forces OpenBLAS 0.3.10 for `mlpack_jll`, but I suppose we should update the dependency version for `armadillo_jll` too?

**Comment by giordano** [comment]
> I see... so perhaps #3145 is not the right solution here.

Agreed.

> I pushed 6f80fa8 to this branch, which forces OpenBLAS 0.3.10 for mlpack_jll

I'm a bit confused by this.  Why did you touch mlpack in that pull request?  Now we have two pull requests rebuilding mlpack :slightly_smiling_face:

> but I suppose we should update the dependency version for armadillo_jll too?

What do you mean exactly?

**Comment by rcurtin** [comment]
> I'm a bit confused by this. Why did you touch mlpack in that pull request? Now we have two pull requests rebuilding mlpack slightly_smiling_face

Incompetence... I pushed that commit to the wrong branch.  Fixed now... :)

>> but I suppose we should update the dependency version for armadillo_jll too?
>
> What do you mean exactly?

`armadillo_jll` also depends on `openblas_jll`---but it does not force a version of that dependency.  Should we also change that in `A/armadillo/build_tarballs.jl` from `Dependency("OpenBLAS_jll")` to `Dependency("OpenBLAS_jll", "v0.3.10")`?  Sorry about the lack of clarity in what I wrote.

**Comment by giordano** [comment]
> armadillo_jll also depends on openblas_jll---but it does not force a version of that dependency.

I think that was reasonable: OpenBLAS has in principle a rather stable API/ABI, it's just that we managed to break it in our builds :upside_down_face:  At least it isn't one of the most popular platforms, but still...

> Should we also change that in A/armadillo/build_tarballs.jl from Dependency("OpenBLAS_jll") to Dependency("OpenBLAS_jll", "v0.3.10")? Sorry about the lack of clarity in what I wrote.

I'd suggest to do nothing for the time being.  This is a general problem with all [dependents of `OpenBLAS_jll`](https://juliahub.com/ui/Packages/OpenBLAS_jll/vLkFP?t=2) (surprisingly not _that_ many).  We'll need to do something when Julia v1.7 gets closer.  Maybe we'll cap all of these existing packages to support only up to Julia v1.6, and we'll need to to new builds against OpenBLAS 0.3.13 to be able to support Julia v1.7

**Comment by rcurtin** [comment]
Okay, that sounds reasonable.  Thanks @giordano!  You are awesome help as always. :rocket:

**Pull request merged**
