### PR TITLE
Wizard recipe: xpa-v2.1.19

### PR DESCRIPTION
**Pull request by mileslucas**
This pull request contains a new build recipe I built using the BinaryBuilder.jl wizard:

* Package name: xpa
* Version: v2.1.19

@staticfloat please review and merge.

### CODE REVIEW

**Comment by mileslucas** [comment]
for windows:

There is a bug in the `Makefile.in` where the install step expects `<executable>.exe` but the build steps always make extensionless binaries

**Comment by giordano** [comment]
Note that we do want executables to have the `.exe` extension on Windows

**Comment by mileslucas** [comment]
fixed this version with a filthy hack that `sed`-edits the generated `Makefile` only for the windows build.

**Comment by giordano** [comment]
@emmt maybe we should ship and compile also [`gencode.c`](https://github.com/emmt/XPA.jl/blob/1fc72006098dba9f31daa138d8eacc48583a97a7/deps/gencode.c)?  Or is there a way to avoid running this program?

**Comment by emmt** [comment]
[`gencode.c`](https://github.com/JuliaAstro/XPA.jl/blob/master/deps/gencode.c) is to facilitate having up-to-date definitions, it *automatically* defines constants and types according to XPA C header definitions and to the compiler which produced the libraries. It should be shipped with the binary build. Avoiding it is possible but is, I think, not a good idea as it would mean that we have to check/update definitions by hand whenever the XPA C library is updated in the future.

**Comment by mileslucas** [comment]
I mean, how often is xpa critically updated? Could XPA.jl just pin this at precisely this version? Unless there’s a way we can get those into the jll (@giordano)

**Comment by emmt** [comment]
Not really often, the `gencode.c` solution was meant to forget about such a possibility. In fact you just have to provide the file `deps.jl` generated by `gencode.c`. May be it is possible to provide such a thing with/inside the jll?

**Comment by giordano** [comment]
Yes, that's possible.  We do something like that already for other packages.

**Pull request merged**
