### PR TITLE
[Foldseek] update to v6, take 2

### PR DESCRIPTION
**Pull request by marcom**
@diegozea 
Messed up the previous PR branch, starting anew here

Had to disable armv6l, armv7l, powerpc64le: 'No SIMD support for this architecture' (maybe due to missing rust simd support on these architectures?)

### CODE REVIEW

**Comment by diegozea** [comment]
Hi!

Thanks for trying it again :) I was looking, and Rust has SIMD support for `powerpc64le-unknown-linux-gnu`. Does the problem arise from the extra `-unknown` in the platform name used by Rust? In any case, for platforms without SIMD support, maybe we can patch `CMakeLists.txt`:

```cmake
if(RUST_FEATURE STREQUAL "")
    message(FATAL_ERROR "No SIMD support for this architecture")
endif()
```

So that it avoids throwing the fatal error, giving a warning instead and setting the `RUST_FEATURE` to `no_simd` to allow the compilation in those platforms. So, using something like the following:

```cmake
if(RUST_FEATURE STREQUAL "")
    message(WARNING "No SIMD support for this architecture. Setting RUST_FEATURE to no_simd.")
    set(RUST_FEATURE "no_simd")
endif()
```

Cheers,

**Comment by diegozea** [comment]
For example, it looks like `powerpc64le-linux-gnu` supports AVX2 and SSE4.1 instructions. So, maybe the `HAVE_AVX2` and `HAVE_SSE4_1` are incorrectly set.

```
sandbox:${WORKSPACE}/srcdir/foldseek/build # cat /proc/cpuinfo | grep avx2 | head -1
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp pku ospke md_clear flush_l1d arch_capabilities
sandbox:${WORKSPACE}/srcdir/foldseek/build # cat /proc/cpuinfo | grep sse4_1 | head -1
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp pku ospke md_clear flush_l1d arch_capabilities
```

**Comment by giordano** [comment]
> it looks like `powerpc64le-linux-gnu` supports AVX2 and SSE4.1 instructions.

That sounds impossible.

> ```
> sandbox:${WORKSPACE}/srcdir/foldseek/build # cat /proc/cpuinfo | grep avx2 | head -1
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp pku ospke md_clear flush_l1d arch_capabilities
> sandbox:${WORKSPACE}/srcdir/foldseek/build # cat /proc/cpuinfo | grep sse4_1 | head -1
> flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp pku ospke md_clear flush_l1d arch_capabilities
> ```

If you tried that in the the BinaryBuilder sandbox as it looks like, then you're seeing your own host machine, not the target.

**Comment by marcom** [comment]
I can't see any support for powerpc64 at https://crates.io/crates/block-aligner and a grep under lib/block-aligner/ for ppc, powerpc, altivec, or vmx also came up empty. So my guess is that this rust library which is now being used by foldseek doesn't yet support powerpc64 simd.

@diegozea It seems to me this is a new upstream limitation due to the new dependency on block-aligner and it's best to open an issue at the foldseek or block-aligner repos if you want to run foldseek on powerpc64.

**Comment by diegozea** [comment]
> If you tried that in the the BinaryBuilder sandbox as it looks like, then you're seeing your own host machine, not the target.

Ah! Yes, it was in the BinaryBuilder sandbox.

> It seems to me this is a new upstream limitation due to the new dependency on block-aligner and it's best to open an issue at the foldseek or block-aligner repos if you want to run foldseek on powerpc64.

There is no special need for `powerpc64` or `32-bits` from my side; I am running on `x86_64-linux-gnu`. So, this JLL update fits me perfectly. Thank you a lot to both of you for making it possible :)

**Pull request merged**
