### PR TITLE
[FastJet] Fixing capitalization

### PR DESCRIPTION
**Pull request by jstrube**
to be consistent with upstream project.
Should this result in a new minor version?
Does the directory name have to be changed?
Upstream project is here: http://fastjet.fr/

### CODE REVIEW

**Comment by giordano** [comment]
> Should this result in a new minor version?

We keep the same version as the upstream project.

> Does the directory name have to be changed?

Yes, please.

However, keep in mind this will result in the creation of a new JLL package, I'm not sure this is worth at this point....

**Comment by giordano** [comment]
It looks also like FastJet wants to be too fast:
```
[03:55:08] You used one or more of the unsafe flags: -Ofast, -ffast-math, -funsafe-math-optimizations
[03:55:08] Please repent.
```

**Comment by jstrube** [comment]
I don't think there are any users, yet.
I can look into whether those flags can be turned off.

**Comment by giordano** [comment]
I'd recommend removing `Fastjet_jll` from the registry, to avoid cluttering it beyond necessary.

**Comment by jstrube** [comment]
Agreed. I'll write a pull request.

**Pull request merged**
