### PR TITLE
Generate SuiteSparse constants

### PR DESCRIPTION
**Pull request by simonbyrne**
Fixed https://github.com/JuliaLang/julia/issues/34725

### CODE REVIEW

**Comment by simonbyrne** [comment]
Hmmm:
```
[20:47:08]  ---> "${CC}" -O2 -I${prefix}/include SuiteSparse_genconsts.c -o SuiteSparse_genconsts -L${libdir} -lcholmod
[20:47:08] /opt/i686-linux-musl/bin/../lib/gcc/i686-linux-musl/4.8.5/../../../../i686-linux-musl/bin/ld: warning: libgfortran.so.3, needed by /opt/i686-linux-musl/bin/../i686-linux-musl/sys-root/usr/local/lib/libopenblas.so.0, not found (try using -rpath or -rpath-link)
[20:47:08] /opt/i686-linux-musl/bin/../i686-linux-musl/sys-root/usr/local/lib/libopenblas.so.0: undefined reference to `_gfortran_concat_string'
[20:47:08] /opt/i686-linux-musl/bin/../i686-linux-musl/sys-root/usr/local/lib/libopenblas.so.0: undefined reference to `_gfortran_etime'
[20:47:08] collect2: error: ld returned 1 exit status
```
Any ideas?

**Comment by giordano** [comment]
Needs `-lgfortran` probably

**Comment by simonbyrne** [comment]
Maybe Clang.jl would be a better solution here (or maybe it is overkill). Is there a way I could try it?

**Comment by giordano** [comment]
> Is there a way I could try it?

A `Clang.jl`-based solution might be more maintainable, but yes, I'm not sure how it fits here

**Comment by giordano** [comment]
I have a patch to fix the compilation, but the problem is that we can't run the program in this environment

**Comment by giordano** [comment]
Compiling the generator on PowerPC currently requires GCC v5 because it needs libgomp, which is very annoying and probably not desirable, as this is a dependency of Julia

**Comment by simonbyrne** [comment]
Hmm, in that case maybe this effort is doomed. It does seem silly that we need to go through all these hoops to print out a couple of constants.

**Comment by Gnimuc** [comment]
> Maybe Clang.jl would be a better solution here (or maybe it is overkill). Is there a way I could try it?

We need to upgrade Clang.jl's build system to BB2-v0.2 firstly. I guess we can implement a light version of Clang.jl for generating constants only.

**Comment by ViralBShah** [comment]
I thought this executable would not run on non-x86 architectures because of the cross compilation. So how does it get built there? It could be that we do this on the Julia side, where this can be run at Julia build time and the buildbots can do it right on all the supported platforms.

**Comment by ViralBShah** [comment]
@Gnimuc It would seem that targeting Julia 1.3 would be fine. If Clang.jl can do this, nothing like it!

**Comment by Gnimuc** [comment]
I wrote some pseudo-code in the following gist to illustrate the idea of running Clang.jl as a post-processing step:

https://gist.github.com/Gnimuc/c67d51d0f33f18280d28aa05420c411f#file-build_tarballs-jl-L105-L150

If using Clang.jl is an overkill for this job, I can edit the code by directly using `LLVM_jll`'s libclang C API.

BTW, may I ask why we'd like to get rid of `SuiteSparse_wrapper.c`? looks like the old method works just fine.

**Comment by ViralBShah** [comment]
Reason for me mainly was to move to more Julia tooling. Hopefully also makes it easy to support both 32-bit and 64-bit suitesparse eventually.

**Comment by Gnimuc** [comment]
The ultimate solution would be to have a full-featured Libc like what rust guys did [here](https://github.com/rust-lang/libc).

**Comment by simonbyrne** [comment]
> BTW, may I ask why we'd like to get rid of `SuiteSparse_wrapper.c`? looks like the old method works just fine.

There has been a request to expose more of the struct interface (https://github.com/JuliaLang/julia/issues/20985), and this infrastructure would be useful for many other libraries where extracting structs and whatnot is a bit of a pain.

**Comment by simonbyrne** [comment]
@Gnimuc do you know if that snipped will compute the correct offset when the platforms differ (e.g. if the fields are `long`, which will be different on Windows/Linux and 32/64 bit)

**Comment by Gnimuc** [comment]
According to [Julia doc](https://docs.julialang.org/en/latest/manual/calling-c-and-fortran-code/#man-bits-types-1), `long` should be mapped to `Clong` in Julia. And Julia has already taken care of that platform difference for us(here I assume Julia did it right, if not, we need to patch Julia). If we could map the whole `cholmod_common_struct` to Julia, then it would be no need to query the field offsets.

C name | Standard Julia Alias | Julia Base Type
-- | -- | --
char | Cchar | Int8 (x86, x86_64), UInt8 (powerpc, arm)
long | Clong | Int (UNIX), Int32 (Windows)
unsigned long | Culong | UInt (UNIX), UInt32 (Windows)
wchar_t | Cwchar_t | Int32 (UNIX), UInt16 (Windows)

Instead of `long`, I guess your real question is about the `SuiteSparse_long` defined in [`SuiteSparse_config.h`](https://github.com/DrTimothyAldenDavis/SuiteSparse/blob/v5.7.1/SuiteSparse_config/SuiteSparse_config.h#L52-L68):
```c
#ifndef SuiteSparse_long

#ifdef _WIN64

#define SuiteSparse_long __int64
#define SuiteSparse_long_max _I64_MAX
#define SuiteSparse_long_idd "I64d"

#else

#define SuiteSparse_long long
#define SuiteSparse_long_max LONG_MAX
#define SuiteSparse_long_idd "ld"

#endif
#define SuiteSparse_long_id "%" SuiteSparse_long_idd
#endif
```

Since libclang-c is just a stable C API of Clang, `clang_Cursor_getOffsetOfField` will compute the correct offset as long as we give it those correct system headers. For example, [`_WIN64` is defined depending on whether Windows headers are included](https://github.com/mirror/mingw-w64/blob/16151c441e89081fd398270bb888511ebef6fb35/mingw-w64-headers/crt/_cygwin.h#L28-L34). This is usually a "no-op" when you're using gcc to compile something in the mingw environment because gcc will automatically find those system headers in the default path. Clang.jl has the same behavior:

#### test.h
```c
#ifdef _WIN64
#define SuiteSparse_long char
#else
#define SuiteSparse_long long
#endif

struct foo {
    int x;
    char y;
    SuiteSparse_long z;
    char w;
};
```
#### macOS
```julia
julia> using Clang

julia> using Clang.LibClang

julia> ctx = DefaultContext();

julia> parse_headers!(ctx, ["test.h"]);  # note we don't need to feed system headers, clang will find itself. 

julia> tu = ctx.trans_units[]
TranslationUnit(Ptr{Nothing} @0x00007fc3e32c31c0, Index(Ptr{Nothing} @0x00007fc3e318d5a0, 0, 1))

julia> root_cursor = getcursor(tu)
CLCursor (CLTranslationUnit) test.h

julia> foo_cursor = search(root_cursor, x->name(x)=="foo")
1-element Array{CLCursor,1}:
 CLCursor (CLStructDecl) foo

julia> foo_fields = children(foo_cursor[])
4-element Array{CLCursor,1}:
 CLCursor (CLFieldDecl) x
 CLCursor (CLFieldDecl) y
 CLCursor (CLFieldDecl) z
 CLCursor (CLFieldDecl) w

julia> for (field_idx, field_cursor) in enumerate(foo_fields)
           field_name = name(field_cursor)
           field_offset = clang_Cursor_getOffsetOfField(field_cursor)
           @show field_name field_offset
       end
field_name = "x"
field_offset = 0
field_name = "y"
field_offset = 32
field_name = "z"
field_offset = 64
field_name = "w"
field_offset = 128

```

#### Windows x64
```julia
julia> for (field_idx, field_cursor) in enumerate(foo_fields)
               field_name = name(field_cursor)
               field_offset = clang_Cursor_getOffsetOfField(field_cursor)
               @show field_name field_offset
       end
field_name = "x"
field_offset = 0
field_name = "y"
field_offset = 32
field_name = "z"
field_offset = 40
field_name = "w"
field_offset = 48
```

However, if we run Clang.jl in the BB2 environment(Linux), we do need to provide those system headers. This is equivalent to do a ~~cross-compile~~ "cross-parse" using Clang.jl and that's why the snippet needs BB2 to provide the `get_include_dirs` API.  

For this specific case, maybe we can do the following trick:
```julia
julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
...

julia> parse_headers!(ctx, ["test.h"], args=["-D_WIN64"]); 

julia> tu = ctx.trans_units[]
TranslationUnit(Ptr{Nothing} @0x00007fc3e320f1f0, Index(Ptr{Nothing} @0x00007fc3e326d050, 0, 1))

julia> root_cursor = getcursor(tu)
CLCursor (CLTranslationUnit) test.h

julia> foo_cursor = search(root_cursor, x->name(x)=="foo")
1-element Array{CLCursor,1}:
 CLCursor (CLStructDecl) foo

julia> foo_fields = children(foo_cursor[])
4-element Array{CLCursor,1}:
 CLCursor (CLFieldDecl) x
 CLCursor (CLFieldDecl) y
 CLCursor (CLFieldDecl) z
 CLCursor (CLFieldDecl) w

julia> for (field_idx, field_cursor) in enumerate(foo_fields)
           field_name = name(field_cursor)
           field_offset = clang_Cursor_getOffsetOfField(field_cursor)
           @show field_name field_offset
       end
field_name = "x"
field_offset = 0
field_name = "y"
field_offset = 32
field_name = "z"
field_offset = 40
field_name = "w"
field_offset = 48

```

**Comment by ViralBShah** [comment]
Can be reopened if there's someone who wants to push this through.

**Comment by vtjnash** [comment]
We could have some fun, and not actually need to execute it, since it is all constexprs
```c
#include <cholmod.h>

const long long SuiteSparse_long = 8*sizeof(SuiteSparse_long);
const long long cholmod_version_main = CHOLMOD_MAIN_VERSION;
const long long cholmod_version_sub  = CHOLMOD_SUB_VERSION;
const long long cholmod_version_sub  = CHOLMOD_SUBSUB_VERSION;
const long long cholmod_common_sizeof = sizeof(cholmod_common);
const long long cholmod_common_offset_dbound = offsetof(cholmod_common, dbound);
const long long cholmod_common_offset_maxrank = offsetof(cholmod_common, maxrank);
const long long cholmod_common_offset_supernodal_switch = offsetof(cholmod_common, supernodal_switch);
const long long cholmod_common_offset_supernodal = offsetof(cholmod_common, supernodal);
const long long cholmod_common_offset_final_asis = offsetof(cholmod_common, final_asis);
const long long cholmod_common_offset_final_super = offsetof(cholmod_common, final_super);
const long long cholmod_common_offset_final_ll = offsetof(cholmod_common, final_ll);
const long long cholmod_common_offset_final_pack = offsetof(cholmod_common, final_pack);
const long long cholmod_common_offset_final_monotonic = offsetof(cholmod_common, final_monotonic);
const long long cholmod_common_offset_final_resymbol = offsetof(cholmod_common, final_resymbol);
const long long cholmod_common_offset_prefer_zomplex = offsetof(cholmod_common, prefer_zomplex);
const long long cholmod_common_offset_prefer_upper = offsetof(cholmod_common, prefer_upper);
const long long cholmod_common_offset_print = offsetof(cholmod_common, print);
const long long cholmod_common_offset_precise = offsetof(cholmod_common, precise);
const long long cholmod_common_offset_nmethods = offsetof(cholmod_common, nmethods);
const long long cholmod_common_offset_selected = offsetof(cholmod_common, selected);
const long long cholmod_common_offset_postorder = offsetof(cholmod_common, postorder);
const long long cholmod_common_offset_itype = offsetof(cholmod_common, itype);
const long long cholmod_common_offset_dtype = offsetof(cholmod_common, dtype);
```

### compile
```
cc -c foo.o foo.c
```
### check endian (LSB / MSB) and pointer size
```
file fib.o 
fib.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
```
### lookup symbol index
```
$ llvm-objdump --syms foo.o
0000000000000000 g     O .rodata	00000008 SuiteSparse_long
0000000000000008 g     O .rodata	00000008 cholmod_version_main
...
```
### print data in a convenient format
```
$ llvm-objcopy -O binary --only-section=.rodata foo.o - | od --endian=little -t x8 -A n -w8
 000000000000007b
 0123456789abcdef
...
```
then columnate and mix, stir well, and bake until ready

**Pull request closed without merging**
