### PR TITLE
[Clp] Add v1.17.6

### PR DESCRIPTION
**Pull request by odow**
Contains a bug-fix for https://github.com/coin-or/Clp/issues/142

cc @ViralBShah is this all I need to do for a release?

### CODE REVIEW

**Comment by amontoison** [comment]
No, you also need to update the build_tarballs.jl of Clp to trigger the compilation.
You can remove the comma at the end of this line : https://github.com/JuliaPackaging/Yggdrasil/blob/master/C/Coin-OR/Clp/build_tarballs.jl#L9

**Comment by ViralBShah** [comment]
I don't understand why BB can't find that commit.

**Comment by giordano** [comment]
Use an `ArchiveSource` instead? :slightly_smiling_face:  I know I'm an outlier in this, but I'm not a fan of using `GitSource`.

**Comment by ViralBShah** [comment]
The main benefit of `GitSource` is that it is fewer steps because you don't need to compute the sha256.  But `ArchiveSource` is certainly less error-prone.

**Comment by ViralBShah** [comment]
The way the coin-or builds are set up, I'll have to switch them all - so perhaps that will have to be a separate PR. In the meanwhile, I will leave this open if someone can point out what might be going on with GitSource.

**Comment by giordano** [comment]
The interesting thing is that locally it works for me and compilation (at least for `x86_64-linux-gnu`) is successfull

**Comment by ViralBShah** [comment]
@staticfloat Any thoughts?

**Comment by giordano** [comment]
My guess is that since this a recent commit, the `LibGit2.fetch` call in https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/15fb9ba3c42c2528226cd09732ac454cd5a460d8/src/Sources.jl#L149-L154 may not be getting the new revision.  Removing the git repo in the cache could probably help (or at least test my hypothesis(

**Comment by ViralBShah** [comment]
> My guess is that since this a recent commit, the `LibGit2.fetch` call in https://github.com/JuliaPackaging/BinaryBuilder.jl/blob/15fb9ba3c42c2528226cd09732ac454cd5a460d8/src/Sources.jl#L149-L154 may not be getting the new revision. Removing the git repo in the cache could probably help (or at least test my hypothesis)

Can I remove the git repo in the cache? How would I do that? That certainly seems like a plausible explanation.

**Comment by giordano** [comment]
> Can I remove the git repo in the cache? How would I do that?

I think that requires access to the machine.

**Comment by staticfloat** [comment]
I nuked `Clp.git`; is it possible you changed upstream git repo?

**Comment by ViralBShah** [comment]
> I nuked `Clp.git`; is it possible you changed upstream git repo?

I don't think so.

**Pull request merged**
