### PR TITLE
Update RadeonProRender

### PR DESCRIPTION
**Pull request by SimonDanisch**

### CODE REVIEW

**Comment by giordano** [comment]
This may be a good occasion to require Julia v1.6?

**Comment by SimonDanisch** [comment]
Ah... Why and where?

**Comment by giordano** [comment]
> Why

It's in particular useful in case you want to add support for the M1 in the future (no idea whether this is relevant for this package in particular)

> and where?

Add `julia_compat="1.6"` to the `build_tarballs()` call at the end

**Comment by SimonDanisch** [comment]
>It's in particular useful in case you want to add support for the M1 in the future

Ah yeah that's impossible I guess...

**Pull request merged**
