### PR TITLE
Upgrade to OpenSSL 3.0.8, due 11th September 2023

### PR DESCRIPTION
**Pull request by mkitti**
From https://www.openssl.org/source/

> Note: The latest stable version is the 3.0 series supported until 7th September 2026. This is also a Long Term Support (LTS) version. The previous LTS version (the 1.1.1 series) is also available and is supported until 11th September 2023.

### CODE REVIEW

**Comment by mkitti** [comment]
cc: @eschnett

**Comment by mkitti** [comment]
I converted to draft since I think this needs more discussion before we merge it.

**Comment by giordano** [comment]
One thing to do is to make sure that all packages depending on openssl_jll set the compat bounds already

**Comment by giordano** [comment]
Skimming through the direct dependencies at https://juliahub.com/ui/Packages/OpenSSL_jll/M3X35/1.1.20+0?page=2, _**very**_ few JLL packages specify the compat with OpenSSL.  We must fix that in all the recipes and in the registry before going on here.

**Comment by mkitti** [comment]
It is not clear to me how breaking OpenSSL 3 is versus 1.1.1:

> Upgrading to OpenSSL 3.0 from OpenSSL 1.1.1 should be relatively straight forward in most cases. The most likely area where you will encounter problems is if you have used low level APIs in your code (as discussed above). In that case you are likely to start seeing deprecation warnings when compiling your application. 

https://www.openssl.org/docs/man3.0/man7/migration_guide.html

It sounds like we may just get some deprecation warnings.

**Comment by mkitti** [comment]
Well it also says,

> OPENSSL 3.0

> Main Changes from OpenSSL 1.1.1

> Major Release

> OpenSSL 3.0 is a major release and consequently any application that currently uses an older version of OpenSSL will at the very least need to be recompiled in order to work with the new version. It is the intention that the large majority of applications will work unchanged with OpenSSL 3.0 if those applications previously worked with OpenSSL 1.1.1. However this is not guaranteed and some changes may be required in some cases. Changes may also be required if applications need to take advantage of some of the new features available in OpenSSL 3.0 such as the availability of the FIPS module.

**Comment by giordano** [comment]
The soversion of the libraries changed from 1.1 to 3, that's already enough to wreak havoc 🙂

**Comment by eschnett** [comment]
How would a compat entry look like? Would it be something like
```Julia
Dependency("OpenSSL_jll"; compat="1.1.20")
```
?

**Comment by giordano** [comment]
In most cases `compat="1.1.20"` should be enough.  I think @mkitti was already looking into this.

**Comment by eschnett** [comment]
@mkitti If you are looking into this: I recommend creating many small pull requests, essentially one per package. Rebuilding a package, even with a trivial change, is often not a trivial task, and many small unrelated things might break and need fixing.

**Comment by giordano** [comment]
I don't think we want to rebuild the packages, they've already been built against openssl 1.1 anyway.  I recommend adding `[skip ci] [skip build]` to the commit message: https://github.com/JuliaPackaging/Yggdrasil/blob/8d12ba7c6823660dfd90117bdbe124fdb3b5bb8d/CONTRIBUTING.md#recommendations-and-tips-about-commit-messages

**Comment by mkitti** [comment]
Couldn't we increment the build number and have that build use OpenSSL v3 though?

Then folks could obtain the entire ecosystem with either v1.1.1 or v3?

**Comment by giordano** [comment]
> Couldn't we increment the build number and have that build use OpenSSL v3 though?

No.

**Comment by mkitti** [comment]
Here are all the references I can find in Yggdrasil to OpenSSL_jll.

```
Yggdrasil$ grep OpenSSL_jll $(find . -name build_tarballs.jl) | sort
./0_RootFS/Rust/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./A/Aria2/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll")),
./B/BerkeleyDB/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
./C/CMake/build_tarballs.jl:    Dependency("OpenSSL_jll")
./C/CyrusSASL/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
./D/dmg2img/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./E/Entwine/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
./F/FFMPEG/FFMPEG/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./G/Git/build_tarballs.jl:    Dependency("OpenSSL_jll"; compat="1.1.10"),
./G/git_crypt/build_tarballs.jl:    "OpenSSL_jll",
./H/HDF5/build_tarballs.jl:    Dependency("OpenSSL_jll"; compat="1.1.10"),
./H/hiredis/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"); compat="1.1.13"),
./H/htslib/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./L/ldid/build_tarballs.jl:    Dependency("OpenSSL_jll"; compat="1.1.13"),
./L/LibArchive/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./L/libevent/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./L/LibPQ/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./L/librdkafka/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
./L/libsnark/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./M/marble/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
./M/MariaDB_Connector_C/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./M/MariaDB_Connector_ODBC/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./M/mold/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
./M/MongoC/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
./O/OpenLDAPClient/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
./O/OpenSSH/build_tarballs.jl:    Dependency("OpenSSL_jll")
./O/opusfile/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95")),
./O/oxigraph_server/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./P/PulseAudio/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
./P/Python/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./Q/Qt5Base/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./Q/Qt6Base/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./Q/Qt/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./Q/qwtw/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
./R/rsync/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95")),
./R/ruby/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./S/S2Geometry/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95")),
./S/SCALE_MAMBA/build_tarballs.jl:    "OpenSSL_jll",
./S/sccache/build_tarballs.jl:    Dependency("OpenSSL_jll"; compat="1.1.17"),
./S/SLEEF/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./S/SQLCipher/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95")),
./S/stork/build_tarballs.jl:    Dependency("OpenSSL_jll")
./S/systemd/build_tarballs.jl:    #Dependency("OpenSSL_jll"),
./T/TDLib/build_tarballs.jl:	Dependency("OpenSSL_jll")
./T/tectonic/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./V/VerizonEctoken/build_tarballs.jl:  "OpenSSL_jll"
./W/wget2/build_tarballs.jl:    Dependency("OpenSSL_jll")
./X/XRootD/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
(openjdk11) mkitti@stonyisland:~/src/Yggdrasil$ 
(openjdk11) mkitti@stonyisland:~/src/Yggdrasil$ grep OpenSSL_jll $(find . -name build_tarballs.jl) | sort
./0_RootFS/Rust/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./A/Aria2/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll")),
./B/BerkeleyDB/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
./C/CMake/build_tarballs.jl:    Dependency("OpenSSL_jll")
./C/CyrusSASL/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
./D/dmg2img/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./E/Entwine/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
./F/FFMPEG/FFMPEG/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./G/Git/build_tarballs.jl:    Dependency("OpenSSL_jll"; compat="1.1.10"),
./G/git_crypt/build_tarballs.jl:    "OpenSSL_jll",
./H/HDF5/build_tarballs.jl:    Dependency("OpenSSL_jll"; compat="1.1.10"),
./H/hiredis/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"); compat="1.1.13"),
./H/htslib/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./L/ldid/build_tarballs.jl:    Dependency("OpenSSL_jll"; compat="1.1.13"),
./L/LibArchive/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./L/libevent/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./L/LibPQ/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./L/librdkafka/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
./L/libsnark/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./M/marble/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
./M/MariaDB_Connector_C/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./M/MariaDB_Connector_ODBC/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./M/mold/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
./M/MongoC/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
./O/OpenLDAPClient/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
./O/OpenSSH/build_tarballs.jl:    Dependency("OpenSSL_jll")
./O/opusfile/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95")),
./O/oxigraph_server/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./P/PulseAudio/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
./P/Python/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./Q/Qt5Base/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./Q/Qt6Base/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./Q/Qt/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./Q/qwtw/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
./R/rsync/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95")),
./R/ruby/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./S/S2Geometry/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95")),
./S/SCALE_MAMBA/build_tarballs.jl:    "OpenSSL_jll",
./S/sccache/build_tarballs.jl:    Dependency("OpenSSL_jll"; compat="1.1.17"),
./S/SLEEF/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./S/SQLCipher/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95")),
./S/stork/build_tarballs.jl:    Dependency("OpenSSL_jll")
./S/systemd/build_tarballs.jl:    #Dependency("OpenSSL_jll"),
./T/TDLib/build_tarballs.jl:	Dependency("OpenSSL_jll")
./T/tectonic/build_tarballs.jl:    Dependency("OpenSSL_jll"),
./V/VerizonEctoken/build_tarballs.jl:  "OpenSSL_jll"
./W/wget2/build_tarballs.jl:    Dependency("OpenSSL_jll")
./X/XRootD/build_tarballs.jl:    Dependency(PackageSpec(name="OpenSSL_jll", uuid="458c3c95-2e84-50aa-8efc-19380b2a3a95"))
```

**Comment by mkitti** [comment]
Should they all have UUIDs or no?

**Comment by giordano** [comment]
>     Yggdrasil$ grep OpenSSL_jll $(find . -name build_tarballs.jl) | sort

Side note, you may find `grep OpenSSL_jll --include="build_tarballs.jl"` more useful than doing command substitution on `find -name` 🙂

**Comment by mkitti** [comment]
What needs to be done in this pull request?

Here's what I'm thinking.
* Create `OpenSSL@3.0` folder for this build_tarballs.jl
* Create `OpenSSL@1.1` folder for the build_tarballs.jl currently on master. Do I need to do this in another pull request to avoid building?
* Identify common elements and put it in a common.jl

**Comment by giordano** [comment]
All correct, including not building of 1.1 here.  In the first instance, just moving to `O/OpenSSL/OpenSSL@3` (probably not necessary yet to be overly specific with minor version) should be sufficient

**Comment by mkitti** [comment]
I think we do want to say `OpenSSL@3.0` because 3.0 is the long term support version. 3.1 is stable but not LTS.

**Pull request merged**
