### PR TITLE
Wizard recipe: libconfuse-v3.2.2

### PR DESCRIPTION
**Pull request by innerlee**
This pull request contains a new build recipe I built using the BinaryBuilder.jl wizard:

* Package name: libconfuse
* Version: v3.2.2

@staticfloat please review and merge.

### CODE REVIEW

**Comment by giordano** [comment]
Is there any warning during the audit stage of the builds? If so, could you please share the direct link to the log in azure pipelines? From the phone I can't get there 😕

**Comment by innerlee** [comment]
0 error/warn for libconfuse-i686-linux-gnu, libconfuse-x86_64-linux-gnu, etc. 

2 warns for apple
```bash
[12:36:13] cli.c:259:25: warning: expression which evaluates to zero treated as a null pointer constant of type 'char *' [-Wnon-literal-null-conversion]
[12:36:13]                 CFG_BOOL_LIST("bool", cfg_false, CFGF_NONE),
[12:36:13]                                       ^~~~~~~~~
[12:36:13] ../src/confuse.h:479:25: note: expanded from macro 'CFG_BOOL_LIST'
[12:36:13]   __CFG_BOOL_LIST(name, def, flags, 0, 0)
[12:36:13]                         ^~~
[12:36:13] ../src/confuse.h:469:62: note: expanded from macro '__CFG_BOOL_LIST'
[12:36:13]   {name,0,CFGT_BOOL,0,0,flags | CFGF_LIST,0,{0,0,cfg_false,0,def},0,{.boolean=svalue},cb,0,0,0,0}
[12:36:13]                                                              ^~~
[12:36:13] 1 warning generated.
```
```bash
[12:36:13] clang-8: warning: argument unused during compilation: '-nostdinc++' [-Wunused-command-line-argument]
```

1 warn for bsd
```bash
[12:35:53] cli.c:259:25: warning: expression which evaluates to zero treated as a null pointer constant of type 'char *' [-Wnon-literal-null-conversion]
[12:35:53]                 CFG_BOOL_LIST("bool", cfg_false, CFGF_NONE),
[12:35:53]                                       ^~~~~~~~~
[12:35:53] ../src/confuse.h:479:25: note: expanded from macro 'CFG_BOOL_LIST'
[12:35:53]   __CFG_BOOL_LIST(name, def, flags, 0, 0)
[12:35:53]                         ^~~
[12:35:53] ../src/confuse.h:469:62: note: expanded from macro '__CFG_BOOL_LIST'
[12:35:53]   {name,0,CFGT_BOOL,0,0,flags | CFGF_LIST,0,{0,0,cfg_false,0,def},0,{.boolean=svalue},cb,0,0,0,0}
[12:35:53]                                                              ^~~
[12:35:53] 1 warning generated.
```

some libtool error for win
```bash

[12:35:51] libtool:   error: Could not determine the host path corresponding to
[12:35:51] libtool:   error:   '/workspace/srcdir/confuse-3.2.2/src:/workspace/srcdir/confuse-3.2.2/src/.libs:/workspace/destdir/lib:/workspace/destdir/bin'
[12:35:51] libtool:   error: Continuing, but uninstalled executables may not work.
[12:35:51] libtool:   error: Could not determine the host path corresponding to
[12:35:51] libtool:   error:   '/workspace/srcdir/confuse-3.2.2/src:/workspace/srcdir/confuse-3.2.2/src/.libs:/workspace/destdir/lib:/workspace/destdir/bin'
[12:35:51] libtool:   error: Continuing, but uninstalled executables may not work.
[12:35:51] libtool:   error: Could not determine the host path corresponding to
[12:35:51] libtool:   error:   '/workspace/srcdir/confuse-3.2.2/src/.libs'
[12:35:51] libtool:   error: Continuing, but uninstalled executables may not work.
[12:35:51] libtool:   error: Could not determine the host path corresponding to
[12:35:51] libtool:   error:   '/workspace/srcdir/confuse-3.2.2/src:/workspace/srcdir/confuse-3.2.2/src/.libs:/workspace/destdir/lib:/workspace/destdir/bin'
[12:35:51] libtool:   error: Continuing, but uninstalled executables may not work.
[12:35:53] mv -f .deps/wincfgtest.Tpo .deps/wincfgtest.Po
[12:35:53] /bin/sh ../libtool  --tag=CC   --mode=link cc  -g -O2 -L../src/  -o wincfgtest.exe wincfgtest.o ../src/libconfuse.la 
[12:35:53] libtool: link: cc -g -O2 -o .libs/wincfgtest.exe wincfgtest.o  -L../src/ ../src/.libs/libconfuse.dll.a -L/workspace/destdir/lib
[12:35:53] libtool:   error: Could not determine the host path corresponding to
[12:35:53] libtool:   error:   '/workspace/srcdir/confuse-3.2.2/src/.libs'
[12:35:53] libtool:   error: Continuing, but uninstalled executables may not work.
[12:35:54] libtool:   error: Could not determine the host path corresponding to
[12:35:54] libtool:   error:   '/workspace/srcdir/confuse-3.2.2/src:/workspace/srcdir/confuse-3.2.2/src/.libs:/workspace/destdir/lib:/workspace/destdir/bin'
[12:35:54] libtool:   error: Continuing, but uninstalled executables may not work.
```

**Comment by innerlee** [comment]
links 
https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=736&view=logs&jobId=ec5b25a2-bdab-55b2-9d96-5de0ba5ab370&j=5ac49f89-703e-506b-3f64-858f38ea7aa8
https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=736&view=logs&j=ec5b25a2-bdab-55b2-9d96-5de0ba5ab370&t=932bc2d3-cafe-593a-0972-2797b24784d4
https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=736&view=logs&j=003fcb58-0865-5321-5db6-7cce2eccc166&t=51ccf385-282c-59a9-2813-42f979b63c5b
https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=736&view=logs&j=b3916287-fa89-5833-06b2-7ce088a2f183&t=8933b576-04cc-518b-23b6-7d84fda177e0

**Comment by giordano** [comment]
Ok, they look good, thanks!

**Pull request merged**
