### PR TITLE
[libcxxwrap] update for libjulia 1.11

### PR DESCRIPTION
**Pull request by fingolfin**
CC @barche @benlorenz 

(Note: I am slightly wary about adding a new Julia variant but not updating the JLL version... but in the end this doesn't seem worse than the "rebuilding" we are doing otherwise? Or is it???)

### CODE REVIEW

**Comment by giordano** [comment]
If this build is reproducible we should get same binaries as before, so the artifact wouldn't change

**Comment by fingolfin** [comment]
Except we are adding artifacts for Julia 1.11 that weren't there before.

**Comment by giordano** [comment]
Yes, I mean, otherwise this PR wouldn't exist, I was saying that if this package is reproducible then adding a new Julia version has _almost_ no cost

**Review by barche — APPROVED** [review]

**Comment by fingolfin** [comment]
@giordano excellent, thank you for explaining and clarifying

**Pull request merged**
