### PR TITLE
[SPRAL] Upgrade to v2023.11.15

### PR DESCRIPTION
**Pull request by amontoison**
@jfowkes

### CODE REVIEW

**Comment by amontoison** [comment]
Meson is unable to determine a dependency order when we cross-compile modern Fortran files...
I will open an issue.

**Comment by jfowkes** [comment]
@amontoison `meson.build` version bumped and `v2023.11.15` re-released as requested.

**Comment by jfowkes** [comment]
> Meson is unable to determine a dependency order when we cross-compile modern Fortran files... I will open an issue.

But it builds fine with meson locally in our tests?

**Comment by amontoison** [comment]
> > Meson is unable to determine a dependency order when we cross-compile modern Fortran files... I will open an issue.
> 
> But it builds fine with meson locally in our tests?

Yes, you are right.
It's probably related to the cross-compilation.
It's not a good news for GALAHAD...

**Pull request merged**
