### PR TITLE
Wizard recipe: CoinUtils-v2.11.4

### PR DESCRIPTION
**Pull request by giordano**
This pull request contains a new build recipe I built using the BinaryBuilder.jl wizard:

* Package name: CoinUtils
* Version: v2.11.4

@staticfloat please review and merge.

### CODE REVIEW

**Comment by giordano** [comment]
@dpo I'm pinging you because it looks like you know these packages: do you think it make sense to build this without any dependency?  Making it work with OpenBLAS is just too much work for me.

Note that our `ASL` is quite incomplete, it misses a lot of header files.  I think we should properly build it from source from https://github.com/ampl/mp, if only it was easy...

**Comment by dpo** [comment]
The COIN-OR build system is more or less engineered so all those packages work together, and it may be the way to go if the alternative is just too much work. However, I would then recommend to not build a separate shared lib for COINBLAS because it will conflict with OpenBLAS (it supplies the same libraries, except it uses the so-called "standard BLAS and LAPACK", which are not optimized).

It may be helpful to look at the Homebrew formulae we started writing a few years back: https://github.com/coin-or-tools/homebrew-coinor. The intention was to make them work with OpenBLAS. A potential difficulty here is that you have much more variety in your platforms and a lot of that software may never have been tested on such combinations. It's worth opening issues upstream though.

I'm currently working on formulae for MUMPS and IPOPT (without using CoinMUMPS or CoinIpopt). That's why I submitted METIS@4 and PARMETIS.

Regarding ASL, the library I'm building is the real one (the one updated by the actual author of the ASL). The one you point to is an (official) offshoot with bells and whistles that isn't updated consistently. It doesn't build shared libs on Windows (https://github.com/ampl/mp/issues/107), and support is very limited. Anyways, I can't think of a library that would work with AMPL-MP and not with ASL. My formula doesn't export header files, but that would be easy to fix, right?

**Comment by giordano** [comment]
> However, I would then recommend to not build a separate shared lib for COINBLAS because it will conflict with OpenBLAS (it supplies the same libraries, except it uses the so-called "standard BLAS and LAPACK", which are not optimized).

I had already built COINBLAS, but I'm not planning to actually use it anywhere because you already suggested so somewhere :wink:

Today I tried to build CoinUtils with OpenBLAS.  I opened an issue in their repo because their build system is quite... "incomplete": `configure` allows passing CFLAGS and LDFLAGS for the lapack libraries -- this is great, we need to use both of them for our OpenBLAS -- but then it ignores them, which of course completely defeats the purpose of having them at all...

> My formula doesn't export header files, but that would be easy to fix, right?

Yes, if someone takes the time to update the builder script :slightly_smiling_face:

**Comment by dpo** [comment]
> Yes, if someone takes the time to update the builder script 

Happy to do it. Where should headers go?

**Comment by giordano** [comment]
> Happy to do it. Where should headers go?

`${prefix}/include` I guess

**Comment by ViralBShah** [comment]
The big thing that needs to happen here is to depend on OpenBLAS_jll and patches for 64-bit OpenBLAS. It looks like it should be reasonably doable.

**Comment by ViralBShah** [comment]
Having dived into this a little bit, @dpo, I think doing this in the right way without making a monolithic build should be possible. In fact many linux distributions are doing it. I suspect that there is an upfront effort involved, but I feel like it is worth a shot - if some of us can collaborate and pull it off.

**Pull request closed without merging**
