### PR TITLE
CUDA_full: Fix missing thrust library

### PR DESCRIPTION
**Pull request by stemann**
Fix for issue discovered in #4554 : CUDA_full@11.3 is missing thrust library

### CODE REVIEW

**Comment by stemann** [comment]
... there is a sibling PR in #4696 which tests the cuda_products for all the CUDA-recipes.

**Comment by maleadt** [comment]
I'm not convinced we want to maintain a list of products here... The original goal for CUDA_full was for it to be a simple repackage of the toolkit without much processing, sticking as close as possible to how the installer would deploy things. Since we'll never actually use this package as a JLL, defining products seemed unnecessary. Also, where does it end, do we want a FileProduct for every entry-point header like you do for Thrust?

In addition, recently library version numbers have been decoupled from the toolkit's release number, https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-major-component-versions, so it's going to be tricky to match those anyway. Unless we pass additional arguments, like you already do for CUPTI and NVVM, at which point it may be easier to just hard-code the list?

**Comment by stemann** [comment]
> > I'm not convinced we want to maintain a list of products here... The original goal for CUDA_full was for it to be a simple repackage of the toolkit without much processing, sticking as close as possible to how the installer would deploy things. Since we'll never actually use this package as a JLL, defining products seemed unnecessary. Also, where does it end, do we want a FileProduct for every entry-point header like you do for Thrust?
> > In addition, recently library version numbers have been decoupled from the toolkit's release number, https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-major-component-versions, so it's going to be tricky to match those anyway. Unless we pass additional arguments, like you already do for CUPTI and NVVM, at which point it may be easier to just hard-code the list?
> 
> In the light of the above, I agree that it might be easier, and more easily interpretable and maintable, to just hard-code the list(s).
> 
> However, defining a couple of products helped to get some audit for some files that turned out to be missing, notably in CUDA_full 11.3-11.6, so I think that a bit of audit does help to ensure that a CUDA_full with its many billions of bytes is first released when it should be more or less complete - regardless of how much NVIDIA decides to re-invent their packaging from minor-release to minor-release. Checking the log for the output from `find .` across the CUDA_full platforms is a bit overwhelming.
> 
> My intent was to actually define one `FileProduct` for every "central" (in some sense) header file in each sub-component of CUDA_full. I don't have the complete overview of which components and which headers to cover.

... but if it makes zero sense, I can also cut this PR down to "just the fixes".

**Comment by maleadt** [comment]
> ... but if it makes zero sense, I can also cut this PR down to "just the fixes".

No it does make sense, I'm just trying to think if it's worth the maintenance burden :-) Since it caught some actual issues, it's probably worth trying it out and defining some products at least, like you propose. If it turns out too much of a hassle to maintain in the various places we need, it's always possible to reduce or remove the list in the future.

**Comment by stemann** [comment]
> > ... but if it makes zero sense, I can also cut this PR down to "just the fixes".
> 
> No it does make sense, I'm just trying to think if it's worth the maintenance burden :-) Since it caught some actual issues, it's probably worth trying it out and defining some products at least, like you propose. If it turns out too much of a hassle to maintain in the various places we need, it's always possible to reduce or remove the list in the future.

As I stalled a bit on doing on the lists, I have parked the "products check" on https://github.com/IHPSystems/Yggdrasil/tree/feature/cuda_products_check, and this branch/PR now only includes the fixes.

**Review by maleadt — APPROVED** [review]
LGTM

**Pull request merged**
