### PR TITLE
Touch libsndfile to force rebuild

### PR DESCRIPTION
**Pull request by abhayap**

### CODE REVIEW

**Comment by giordano** [comment]
```
[16:29:08] grep: /workspace/destdir/lib/libogg.la: No such file or directory
[16:29:08] sed: /workspace/destdir/lib/libogg.la: No such file or directory
[16:29:08] libtool:   error: '/workspace/destdir/lib/libogg.la' is not a valid libtool archive
[16:29:08] make[2]: *** [Makefile:1917: src/libsndfile.la] Error 1
```
@fingolfin sigh

**Comment by fingolfin** [comment]
Gotta rebuild libogg first I guess ...

We could also add code to BB to remove all *.la files at the start of every build script (basically with the same logic/code as we use to remove them when creating new JLLs)

**Comment by fingolfin** [comment]
Oh I see you updated Ogg_jll yesterday. Huh?1

**Comment by giordano** [comment]
Ogg was rebuilt just yesterday: #4181

**Comment by fingolfin** [comment]
This is weird. I'll need to look at the libsndfile build system to see if it does something weird. I can have a look -- but first need to prepare dinner for the family :-)

**Comment by abhayap** [comment]
@giordano @fingolfin Thanks for taking a look.

**Comment by giordano** [comment]
Ok, worked around by using CMake instead of AutoConf.

@abhayap side note, for your own sanity it's better to _never_ create pull requests from a branch with the same name as the target branch.  GitHub should even show a big red warning banner if you try to do that.

**Comment by abhayap** [comment]
Thanks for fixing it @giordano! Ok I'll make sure to always use a different branch name in the future. Thanks for the tip.

**Pull request merged**
