### PR TITLE
Add OpenCL ICD v2.3.2

### PR DESCRIPTION
**Pull request by Mellich**

### CODE REVIEW

**Comment by vchuravy** [comment]
How does this differ from https://github.com/JuliaPackaging/Yggdrasil/blob/2297685fadbe660f8c23cac4e69271da3e8087de/O/OpenCL/build_tarballs.jl#L10 ?

**Comment by Mellich** [comment]
> How does this differ from
> 
> https://github.com/JuliaPackaging/Yggdrasil/blob/2297685fadbe660f8c23cac4e69271da3e8087de/O/OpenCL/build_tarballs.jl#L10
> ?

The headers differ and some software relies on this implementation.

**Review by maleadt — APPROVED** [review]
LGTM. Just know that for OpenCL.jl I went with Khronos' ICD loader because of specific features -- lazy initialization (not sure if this one has it) and `OCL_ICD_FILENAMES` (definitely not implemented in ocl-icd) -- so you won't be able to use this as-is with that package.

**Comment by maleadt** [comment]
That said, have you tried getting this to work on musl? Googling for `rpl_malloc` reveals a couple of potential workarounds, e.g., https://stackoverflow.com/questions/67116092/ld-problem-rpl-malloc-cross-compiling-arm. Windows support would be useful too, so you can look at e.g. cygwin or msys for potential patches you could use here (https://cygwin.com/cgit/cygwin-packages/ocl-icd/tree/ or https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-opencl-icd).

**Comment by Mellich** [comment]
Thanks for the review! Good points. I will take a look at it.

**Comment by Mellich** [comment]
The musl fixed worked well. Now the only remaining issue is the Windows support.
I applied the patches and used dlfcn_win32 to get around the first build errors but now I am getting the following error:

```
[13:43:27] libtool: compile:  cc -std=gnu11 -DHAVE_CONFIG_H -I. -Wall -I/workspace/srcdir/ocl-icd/khronos-headers -Wno-deprecated-declarations -DCL_NO_NON_ICD_DISPATCH_EXTENSION_PROTOTYPES "-DETC_OPENCL_VENDORS=\"/etc/OpenCL/vendors\"" "-DETC_OPENCL_LAYERS=\"/etc/OpenCL/layers\"" -g -O2 -MT libOpenCL_la-ocl_icd_loader_gen.lo -MD -MP -MF .deps/libOpenCL_la-ocl_icd_loader_gen.Tpo -c ocl_icd_loader_gen.c  -DDLL_EXPORT -DPIC -o .libs/libOpenCL_la-ocl_icd_loader_gen.o
[13:43:28] run_dummy_icd_gen.c:398:1: error: conflicting types for ‘clEnqueueNativeKernel’
[13:43:28]  clEnqueueNativeKernel(cl_command_queue  /* command_queue */,
[13:43:28]  ^
[13:43:28] In file included from /workspace/srcdir/ocl-icd/khronos-headers/CL/opencl.h:24:0,
[13:43:28]                  from run_dummy_icd_gen.c:40:
[13:43:28] /workspace/srcdir/ocl-icd/khronos-headers/CL/cl.h:1749:1: note: previous declaration of ‘clEnqueueNativeKernel’ was here
[13:43:28]  clEnqueueNativeKernel(cl_command_queue  command_queue,
[13:43:28]  ^
[13:43:28] make[2]: *** [Makefile:1021: run_dummy_icd_through_our_ICDL-run_dummy_icd_gen.o] Error 1
```
You can find my attempt here: https://github.com/Mellich/Yggdrasil/blob/ocl-icd-windows/O/ocl_icd/build_tarballs.jl

Does anyone have an idea what's going on? 
For me, Windows support is not that urgent, so I would be fine with the current state for now.

**Comment by maleadt** [comment]
Another fatal error:

```
cc -std=gnu11 -DHAVE_CONFIG_H -I.  -Wall   -DCLLAYERINFO -Wno-deprecated-declarations   -DCL_NO_NON_ICD_DISPATCH_EXTENSION_PROTOTYPES -DETC_OPENCL_VENDORS=\"/etc/OpenCL/vendors\" -DETC_OPENCL_LAYERS=\"/etc/OpenCL/layers\" -g -O2 -MT cllayerinfo-ocl_icd_loader.o -MD -MP -MF .deps/cllayerinfo-ocl_icd_loader.Tpo -c -o cllayerinfo-ocl_icd_loader.o `test -f 'ocl_icd_loader.c' || echo './'`ocl_icd_loader.c
ocl_icd_loader.c:1098:14: error: ‘clGetExtensionFunctionAddress_hid’ aliased to undefined symbol ‘clGetExtensionFunctionAddress’
 hidden_alias(clGetExtensionFunctionAddress);
              ^
ocl_icd_loader.c:1008:16: note: in definition of macro ‘hidden_alias’
   typeof(name) name##_hid __attribute__ ((alias (#name), visibility("hidden")))
                ^
```

Not sure what's up here. However, these issues only occur on mingw-i686, so maybe it's worth keeping the x86_64 build enabled at least.

**Comment by Mellich** [comment]
I haven't noticed that this is only an i686 issue. Now we have x86_64 Windows support

**Comment by Mellich** [comment]
Is there anything else I can help with to get this merged? Any suggestions or objections?

**Comment by maleadt** [comment]
I'll make a couple of minor NFC changes and merge this once CI is green.

**Pull request merged**
