### PR TITLE
Add LLVM18 Bootstrap

### PR DESCRIPTION
**Pull request by jkrimmer**

### CODE REVIEW

**Review by ararslan — APPROVED** [review]
I assume the other LLVM 17 patches are no longer needed? LGTM if so, and thanks!

In case you're unfamiliar with the full process here...
1. Run `build_tarballs.jl --deploy` with Julia 1.7 and BinaryBuilderBase `dev`'d. This creates a new release on this repository with the artifacts attached as release assets, and updates the BinaryBuilderBase Artifacts.toml. Notably, this requires write access to this repository.
2. Open a pull request to BinaryBuilderBase to incorporate the change to Artifacts.toml and a bump to the package version in Project.toml.
3. Once the new BinaryBuilderBase version is registered, update Yggdrasil's Manifest.toml by running the GitHub Actions workflow. This also requires write access.

A good example if you haven't seen previously is how @maleadt added support for 14, 15, and 17. See also @giordano's comments in Tim's PRs.
- https://github.com/JuliaPackaging/Yggdrasil/pull/9162
- https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/386

**Comment by giordano** [comment]
> This creates a new release on this repository with the artifacts attached as release assets

Only committers can do that.

**Comment by ararslan** [comment]
Right, that's why I said
> Notably, this requires write access to this repository.

😁

**Comment by maleadt** [comment]
I've built and uploaded the artifacts from this PR: https://github.com/JuliaPackaging/Yggdrasil/releases/tag/LLVMBootstrap-v18.1.7

@jkrimmer You should be able to continue the steps explained by @ararslan now.

**Comment by ararslan** [comment]
@maleadt, don't you now need to be the one to open the BinaryBuilderBase PR since building the binaries would have updated your local Artifacts.toml?

**Comment by maleadt** [comment]
I figured it would be possible to create that with ArtifactUtils.jl. Anyway, I'll create a PR.

Tangentially, why is it these changes are done to my `.julia/packages/BinaryBuilderBase/rWG8o/Artifacts.toml` and not to my `.julia/dev/BinaryBuilderBase`?

**Comment by giordano** [comment]
> Tangentially, why is it these changes are done to my .julia/packages/BinaryBuilderBase/rWG8o/Artifacts.toml and not to my .julia/dev/BinaryBuilderBase?

We use the path of whatever BBB is active in the environment.

**Comment by ararslan** [comment]
> I figured it would be possible to create that with ArtifactUtils.jl.

TIL https://github.com/JuliaPackaging/ArtifactUtils.jl exists, cool.

**Comment by ararslan** [comment]
I updated the Manifest.toml, so the process here is now complete. Thanks @jkrimmer!

**Comment by jkrimmer** [comment]
I am sorry for not getting back to my pull request any sooner. For the past week, I have been attending a conference and have not managed to work on anything else. Thanks a lot for taking care of this issue!

**Comment by ararslan** [comment]
No worries, the majority of the work here aside from what you implemented in your PR requires commit access anyway

**Pull request merged**
