### PR TITLE
[CUDA] make cuDriverGetVersion not fail if stub libcuda.so

### PR DESCRIPTION
**Pull request by vchuravy**
Fixes https://github.com/JuliaGPU/CUDA.jl/issues/1753

### CODE REVIEW

**Comment by maleadt** [comment]
Hmm, I'm not sure we should just ignore a broken `libcuda`... We should already handle the stub case below (all CUDA APIs are available in the stub libraries, as they need to be there for dynamic linking purposes, they just return a specific error status).

**Comment by vchuravy** [comment]
Yeah, I was questioning that as well. But on the other hand there might be other reasons for failing and since this is so early... As an example what would happen if an initializer failed.

**Comment by maleadt** [comment]
Yeah I guess we need it. Added some debug statements though to make this less opaque.

**Comment by maleadt** [comment]
Added some more debugging, and verified locally that the generated JLLs still work as expected.

**Comment by vchuravy** [comment]
LGTM!

**Comment by giordano** [comment]
Note that last commit didn't trigger build because of `[skip build]`.  Might be worth doing a run without `[skip build]` and remember to remove it from squash merge commit message.

**Comment by maleadt** [comment]
But I added that explicitly to avoid re-generating the artifacts. Or is that not how it works? In any case, we just need the JLLs regenerated.

**Comment by giordano** [comment]
Sorry, yes, if it's only for wrappers it's ok

**Pull request merged**
