### PR TITLE
[GR] Update GR to 0.56

### PR DESCRIPTION
**Pull request by jheinen**

### CODE REVIEW

**Comment by ViralBShah** [comment]
@giordano Is this failing because of the way the Platforms are specified?

**Comment by giordano** [comment]
Yes

**Comment by jheinen** [comment]
With the build script in [this](https://github.com/jheinen/GR.jl/commit/94af874ff5604e1cc3f094e1d50ceee23440b940) commit, I could build the Linux and macOS distributions on macOS.] What is the further procedure? Should I change the script here?

**Comment by ViralBShah** [comment]
@jheinen I have made a few commits here that give us pretty much everything except windows. Let's see if @giordano or others can help us with Windows.

**Comment by giordano** [comment]
Oh, cool, we just removed the static libraries: #2704

**Comment by jheinen** [comment]
Once it works, how should things be managed in the future? Should **I** update version information etc. in the build script to provide new binaries? Right now, it seems that I'm not allowed to make PRs.

**Comment by giordano** [comment]
> Ok. Just wondering, why the Platform() methods don't work for me!?

I assume you're using Julia v1.5.  That has been introduced in Julia v1.6.  Yggdrasil uses Julia v1.6

**Comment by ViralBShah** [comment]
> Once it works, how should things be managed in the future? Should **I** update version information etc. in the build script to provide new binaries? Right now, it seems that I'm not allowed to make PRs.

You should be able to make PRs to this repo. The easiest thing is to just update the version numbers here in a PR in the future.

**Comment by jheinen** [comment]
> > Ok. Just wondering, why the Platform() methods don't work for me!?
> 
> I assume you're using Julia v1.5. The new `Platform` type has been introduced in Julia v1.6. Yggdrasil uses Julia v1.6

```julia
% /opt/julia-1.6/bin/julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0-rc3 (2021-03-16)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.6) pkg> add BinaryBuilder
  Installing known registries into `~/.julia`
       Added registry `General` to `~/.julia/registries/General`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package BinaryBuilder [12aac903]:
 BinaryBuilder [12aac903] log:
 ├─possible versions are: 0.1.0-0.2.6 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.1.0-0.2.6
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
 ```

**Comment by giordano** [comment]
Yes, because there are no _released_ versions of BinaryBuilder compatible with Julia v1.6, yet (coming soon).

The easiest thing to do is to instantiate the environment in the [`.ci/`](https://github.com/JuliaPackaging/Yggdrasil/tree/f748fdc97c4bc356605738bcb2e4228e0eebc3a1/.ci) directory, so you simply use the same environment as Yggdrasil.

**Comment by ViralBShah** [comment]
@giordano Now I am confused. Is it not picking up the latest Qt release, or is the problem something else?

**Comment by giordano** [comment]
PkgServer being lazy :slightly_smiling_face:

**Comment by ViralBShah** [comment]
It's pulling the new Qt_jll for me, but not on Yggdrasil. Maybe try tomorrow?

**Pull request merged**
