### PR TITLE
Wizard recipe: helloworld-v0.2.1

### PR DESCRIPTION
**Pull request by mankai-chow**
This pull request contains a new build recipe I built using the BinaryBuilder.jl wizard:

* Package name: helloworld
* Version: v0.2.1

@staticfloat please review and merge.

### CODE REVIEW

**Comment by giordano** [comment]
This looks like a test?

**Comment by staticfloat** [comment]
@mankai-chow can you give some more information about what this is?  In particular:

1. The name `helloworld` is not very descriptive, it looks like you have some numerical code being put together here, is this a library of your creation?  If so, you will need a better name for it than "helloworld".
2. The library you're creating is just called `lib.so`, which will be difficult for downstream C/C++/Fortran users to actually use.  You usually want to name it something like `libblasfuncs.so` or something like that so that they can link to it via `-lblasfuncs` on the command line.
3. The software itself should come with a README, a license, etc....

**Comment by mankai-chow** [comment]
Dear Saba :

    Sorry. This generation by the wizard was meant just for I test. Could
you remove it for me ? Sorry for the trouble. Thank you.

Best regards,
Zheng Zhou 周正.

**Comment by staticfloat** [comment]
Yep, no worries.  Thanks for the quite response!

**Pull request closed without merging**
