### PR TITLE
New Recipe: OCaml v4.10.0

### PR DESCRIPTION
**Pull request by LaurentMazare**
Add a recipe to install the ocaml compiler (my main motivation is that I'm working on some interoperability layer between julia and ocaml and this would make the package setup easier).

### CODE REVIEW

**Comment by giordano** [comment]
Do you raelly need to list all those products?  The build is successful but some products are missing or maybe are found in different directories.

Generally speaking, you only need to list products that you'll reference in the Julia package, like a shared library or an executable.  No need to list every single file in the tarball.

**Comment by LaurentMazare** [comment]
Right, I've restricted the products list to the bare minimum (that is the compiler itself and the basic libraries), it's enough to build native ocaml executables which is a good start.

**Comment by giordano** [comment]
@LaurentMazare as far as I can see, the only shared libraries are
```
sandbox:${WORKSPACE}/srcdir/ocaml-4.10.0 # ls -lhrt ${libdir}/ocaml/*.so
-rwxrwxr-x    1 root     root      906.3K Jun 19 00:19 /workspace/destdir/lib/ocaml/libcamlrun_shared.so
-rwxrwxr-x    1 root     root      843.0K Jun 19 00:19 /workspace/destdir/lib/ocaml/libasmrun_shared.so
```
`bigarray`, `unix` and `str` are all static archives, that can't be called by julia (and can't be used as `LibraryProduct`s).

**Comment by LaurentMazare** [comment]
@giordano Is there a way to have these still available? Maybe LibraryProduct is not the right choice there, these are some form of pre-compiled ocaml libraries that are used by the ocaml compiler in its linking step (they are only used when the ocaml code use some specific libraries but still would be good to get).

**Comment by giordano** [comment]
They can be listed as [`FileProduct`](https://juliapackaging.github.io/BinaryBuilder.jl/dev/reference/#BinaryBuilder.FileProduct), something like
```
FileProduct("bigarray.a", :bigarray, "lib/ocaml")
```
should do the job, but I'm not sure how you're going to use them in Julia.

To be clear: everything in the `${prefix}` directory will be put inside the tarball, listings the products will only make it easy to reference them in the julia package as it creates a named variable.  No need to explicit list files that aren't going to be directly referenced from Julia.

**Comment by LaurentMazare** [comment]
Ah that makes sense, I was worried about missing runtime dependencies for the executable but looks like everything will be there and only the compiler binary needs to be easily reachable from julia. I've removed the unnecessary products, thanks a lot for your help!

**Comment by giordano** [comment]
I'm playing with the tarball generated by this script.  The executable products you listed seems to be able to run (I just tried to invoke them without arguments).

One question: why did you list only these 4 platforms?  Did it fail for the others or you don't care about the others?

**Comment by LaurentMazare** [comment]
The other platforms failed when I tried them on my local computer, and I don't care that much about them.

**Pull request merged**
