### PR TITLE
Support windows for mdbtools

### PR DESCRIPTION
**Pull request by kdheepak**
- Add patch for Windows
- Remove LibraryProducts 
    - Windows only has static .a files
    - Most users are probably interested in the binaries

Reference: https://github.com/cyberemissary/mdbtools/issues/18

### CODE REVIEW

**Comment by giordano** [comment]
> Windows only has static .a files

Did you try to configure with `--enable-shared`?

**Comment by kdheepak** [comment]
I did try `-enable-shared` and it generates libtool libraries (`lib/libmdbsql.la` and `lib/libmdb.la`) instead of DLL files. 

I know you are busy, and this is not important for me at the moment. I've been able to get Linux and Mac binaries working, and the official binaries to work for windows.

**Comment by giordano** [comment]
Did you read the documentation?  The issues you were having here is described in https://juliapackaging.github.io/BinaryBuilder.jl/dev/troubleshooting/#Libtool-refuses-to-build-shared-library-because-of-undefined-symbols :slightly_smiling_face:

**Comment by kdheepak** [comment]
Called out 😅, I didn't read the documentation. Nice page! I'll go through the docs more carefully next time.

**Pull request merged**
