### PR TITLE
Wizard recipe: OpenJpeg-v2.3.1

### PR DESCRIPTION
**Pull request by ericphanson**
This pull request contains a new build recipe I built using the BinaryBuilder.jl wizard:

* Package name: OpenJpeg
* Version: v2.3.1

@staticfloat please review and merge.

### CODE REVIEW

**Comment by ericphanson** [comment]
By the way, BB crashes if you say "make a PR" but your local git "user.name" isn't set (though you can just set it and resume, if you realize what's missing).

**Comment by giordano** [comment]
I remember I got the same issue a few days ago, but if I remember correctly the error message was clear.  Did you find the error message informative?

**Comment by ericphanson** [comment]
Here's the message:
```julia
Would you like to actually open the pull request or just prepare it?
 > Go ahead, open it
   No, just prepare it and let me look at it first
[ Info: Checking temporary Yggdrasil out to /tmp/jl_NSEi22
[ Info: Generating O/OpenJpeg/build_tarballs.jl
[ Info: Committing and pushing to ericphanson/Yggdrasil#wizard/OpenJpeg-v2.3.1_5f303f96...
GitError(Code:ENOTFOUND, Class:Config, config value 'user.name' was not found)
Stacktrace:
 [1] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/LibGit2/src/error.jl:101 [inlined]
 [2] default_signature(::LibGit2.GitRepo) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/LibGit2/src/signature.jl:69
 [3] LibGit2.Signature(::LibGit2.GitRepo) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/LibGit2/src/signature.jl:25
 [4] commit at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/LibGit2/src/commit.jl:113 [inlined]
 [5] (::BinaryBuilder.var"#518#521"{Bool,String,VersionNumber,Array{BinaryBuilder.PatchSource,1},String,GitHub.OAuth2,GitHub.Repo})(::String) at /home/eric/.julia/packages/BinaryBuilder/o9Hrl/src/wizard/deploy.jl:170
 [6] mktempdir(::BinaryBuilder.var"#518#521"{Bool,String,VersionNumber,Array{BinaryBuilder.PatchSource,1},String,GitHub.OAuth2,GitHub.Repo}, ::String; prefix::String) at ./file.jl:682
 [7] mktempdir(::Function, ::String) at ./file.jl:680 (repeats 2 times)
 [8] yggdrasil_deploy(::String, ::VersionNumber, ::Array{BinaryBuilder.PatchSource,1}, ::String; open_pr::Bool, branch_name::Nothing) at /home/eric/.julia/packages/BinaryBuilder/o9Hrl/src/wizard/deploy.jl:135
 [9] yggdrasil_deploy(::BinaryBuilder.WizardState, ::Bool) at /home/eric/.julia/packages/BinaryBuilder/o9Hrl/src/wizard/deploy.jl:121
 [10] step7(::BinaryBuilder.WizardState) at /home/eric/.julia/packages/BinaryBuilder/o9Hrl/src/wizard/deploy.jl:240
 [11] run_wizard(::Nothing) at /home/eric/.julia/packages/BinaryBuilder/o9Hrl/src/Wizard.jl:105
 [12] run_wizard() at /home/eric/.julia/packages/BinaryBuilder/o9Hrl/src/Wizard.jl:75
 [13] top-level scope at REPL[3]:1
 [14] eval(::Module, ::Any) at ./boot.jl:331
 [15] eval_user_input(::Any, ::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
 [16] run_backend(::REPL.REPLBackend) at /home/eric/.julia/packages/Revise/Pcs5V/src/Revise.jl:1073
 [17] top-level scope at none:0
 [18] eval(::Module, ::Any) at ./boot.jl:331
 [19] eval_user_input(::Any, ::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:86
 [20] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/REPL/src/REPL.jl:118 [inlined]
 [21] (::REPL.var"#26#27"{REPL.REPLBackend})() at ./task.jl:358

WizardState [step7]
```

I didn't find it super clear; at first I thought it was a bug in BB and maybe I should try master instead (but I didn't). So that's why I made the PR manually for LittleCMS. But this one had a patch so I figured it was worth seeing if I could fix it and that's when I remember git uses global config options and maybe that's what it's talking about.

**Comment by ericphanson** [comment]
I think it surprised me that it needed that because I already had to sign into my github account and setup a token, so I thought it already had everything it would need.

**Comment by giordano** [comment]
Ok, feel free to open an issue to BinaryBuilder to discuss this.  Maybe we should catch missing `user.name` and `user.email` and prompt the user to insert these settings as well.

**Pull request merged**
