### PR TITLE
MGARD: New library

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by eschnett** [comment]
@giordano I have a problem here: The cmake check for protobuf (our `protoc_jll` package) didn't finish in 4 hours. This check takes an inordinate time anyway, probably 10 minutes on my local system. I think the reason is that protobuf installs a large number of shared libraries (all the abseil stuff) with a lot of pkgconfig files. I think all the time is spent running `pkgconfig`. Do you have any suggestions?

**Comment by giordano** [comment]
Uhm, no, sorry, I don't have concrete suggestions about this, never came across something similar before. Only hint I could give is: make sure you're using the right protoc, because my assumption is that it'd be looking at the target one, is that what you want?

**Comment by eschnett** [comment]
Thanks. Yes, there are both a `HostBuildDependency` and a regular `Dependency` for protc. (Both are needed, it seems.)

**Comment by eschnett** [comment]
I now think it's a problem with `pkg-config` on BSD platforms. It runs for a very long time.

**Pull request merged**
