### PR TITLE
[aws_c_cal] Update to version 0.7.1

### PR DESCRIPTION
**Pull request by quinnj2**
This PR updates aws_c_cal to version 0.7.1. cc: @quinnj @Octogonapus

### CODE REVIEW

**Comment by giordano** [comment]
@quinnj can you please remove the continuous force-push if nothing changes?  Thanks!

**Comment by quinnj** [comment]
Yeah, sorry about that. I think I put it in initially while testing things out to make sure I force-pushed the updated-correct thing, but I think we're in a good state here now.

**Comment by quinnj** [comment]
(I've taken out the force-push, so we shouldn't see that behavior any more)

**Comment by giordano** [comment]
Thanks!

**Pull request merged**
