### PR TITLE
[Libbpf] Update to 0.4

### PR DESCRIPTION
**Pull request by jpsamaroo**

### CODE REVIEW

**Comment by giordano** [comment]
Can we require Julia v1.6 and build for experimental platforms (basically armv6l)?

**Comment by jpsamaroo** [comment]
Sure! How do I do that?

**Comment by jpsamaroo** [comment]
Sorry, I force-pushed to fix the build error, and overwrote your changes :cry: I won't push anymore.

**Comment by giordano** [comment]
No worries.  I _think_ `--force-with-lease` should prevent this kind of issues :wink:

**Comment by giordano** [comment]
Right, we can't build for armv6l because the dependency doesn't have it, but we can at least require julia v1.6, which will let us to do that later

**Comment by jpsamaroo** [comment]
SGTM!

**Pull request merged**
