### PR TITLE
Bump SQLite to latest version

### PR DESCRIPTION
**Pull request by quinnj**

### CODE REVIEW

**Comment by giordano** [comment]
Uhm, the license file is missing

**Comment by quinnj** [comment]
I'm not sure what you mean?

**Comment by giordano** [comment]
Audit issues this warning:
```
┌ Warning: Unable to find valid license file in "${prefix}/share/licenses/SQLite"
└ @ BinaryBuilder /depot/packages/BinaryBuilder/SlQ9E/src/Auditor.jl:416
```
You can install the license file inside the build environment with our custom `install_license` utility: https://juliapackaging.github.io/BinaryBuilder.jl/dev/build_tips/#Installing-the-license-file-1

**Comment by quinnj** [comment]
Hmmmm, there's no license file that comes w/ the sqlite source. there's https://sqlite.org/copyright.html, which says that all the code is "in the public domain". should we link to that page somehow?

**Pull request merged**
