### PR TITLE
[qr_mumps] Version 3.0.4

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by amontoison** [comment]
@abuttari
I have compilation issues with Windows for qr_mumps 3.0.4. Do you know where the problem comes from ?

**Comment by abuttari** [comment]
@amontoison I cannot really understand what the problem is. Compilation works smoothly on my computer although scotch and suitesparse are not found by cmake but I don't think this is the issue. Do you have any further insight?

**Comment by giordano** [comment]
`libqrm_common`, `libcqrm`, `libsqrm`, `libdqrm`, and `libzqrm` can't be found in the prefix.  Looks like they aren't installed at all?

**Comment by amontoison** [comment]
It seems that `libqrm_common`, `libcqrm`, `libsqrm`, `libdqrm`, and `libzqrm` are installed but the extension is `dll.a` (https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=12359&view=logs&j=5b2774f6-2659-5c13-ca2c-8612585b2529&t=b04e44fd-f0be-57b4-3252-efc982726767&l=4614).

For SuiteSparse, the library is a `.dll` and for SCOTCH I never succeeded to compile it on Windows.

**Comment by giordano** [comment]
> but the extension is dll.a

Those are *not* shared libraries but import libraries

**Comment by amontoison** [comment]
@abuttari 
I tried to recompile `qr_mumps` with `libblastrampoline` to easily switch the BLAS backend but I still have issue with the version `3.0.4` for windows platforms.
I don't understand why the shared libraries are not generated.
A folder `cmake` is also copied at the end instead of the `.dll`.
With the version `v3.0.3`, `.dll` and `.dll.a` files were available in the `${prefix}/lib` folder.

Do you have an idea how to solve it?

Capture d’écran du 2022-08-31 18-43-54
ted.

**Comment by abuttari** [comment]
the problem should be fixed in the master branch of the qr_mumps git repository which has not become public:

https://gitlab.com/qr_mumps/qr_mumps

**Comment by amontoison** [comment]
Thanks @abuttari!
Windows platforms are still unable to detect AMD/COLAMD librairies (see [here](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=22683&view=logs&j=5b2774f6-2659-5c13-ca2c-8612585b2529&t=b04e44fd-f0be-57b4-3252-efc982726767&l=246)) but they generate `.dll`.

**Comment by abuttari** [comment]
> Thanks @abuttari! Windows platforms are still unable to detect AMD/COLAMD librairies (see [here](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=22683&view=logs&j=5b2774f6-2659-5c13-ca2c-8612585b2529&t=b04e44fd-f0be-57b4-3252-efc982726767&l=246)) but they can use METIS ordering. For windows platforms, the library folder is `${prefix}/bin` and not `${prefix}/lib`. I added `-DAMD_LIBRARIES="${libdir}/amd.${dlext};${libdir}/colamd.${dlext}"` but `qr_mumps` is still unable to find them.
> 
> The issue with dynamic libraries is solved, they generate `.dll`!!!
> 
> I will wait LBT v"5.2.0" to recompile `qr_mumps` and it should be good.

I guess the problem with AMD/COLAMD is that no import libraries (.dll.a) are generated by the SuiteSparse package. If I understand correctly CMake (at least the one in qr_mumps) will look for .dll.a files and not for .dll ones. This is why METIS is correctly detected and AMD/COLAMD are not.

**Comment by amontoison** [comment]
> I guess the problem with AMD/COLAMD is that no import libraries (.dll.a) are generated by the SuiteSparse package. If I understand correctly CMake (at least the one in qr_mumps) will look for .dll.a files and not for .dll ones. This is why METIS is correctly detected and AMD/COLAMD are not.

I will compile `qr_mumps` without AMD/COLAMD for windows platforms.
I suppose that we will have the same issue if one day we want to use SCOTCH ordering too.

**Comment by amontoison** [comment]
@giordano 
If it's fine for you, you can merge the PR.

**Comment by giordano** [comment]
Sorry, it wasn't clear to me it was good to go, thanks for the bump

**Pull request merged**
