### PR TITLE
Upgrade z3 to v4.8.14 and build for all supported platforms.

### PR DESCRIPTION
**Pull request by kllrak**
`]add Z3` fails for me using Julia 1.7, so I thought I would try to update the recipe. This is the first time I have worked on Yggdrasil recipes, comments and scrutiny welcomed. 

There are two patches in here that should be removed at a later date: one to get builds working with Julia 1.6, and another to get builds working for macOS. I'm not quite sure I'm doing the `julia_versions` part right, but I intended to follow the example in the [libcxxwrap_julia](https://github.com/JuliaPackaging/Yggdrasil/blob/82eb18cb6222195b9995b98b136f6f5f995fc721/L/libcxxwrap_julia/build_tarballs.jl#L13) recipe.

### CODE REVIEW

**Comment by giordano** [comment]
Brilliant, thanks a lot!

**Comment by kllrak** [comment]
You're welcome. Out of curiosity, do any of the warnings in the build matter, for example: "Minimum instruction set detected for bin/z3 is avx2, not x86_64 as desired" ?

**Comment by giordano** [comment]
Those checks aren't 100% bullet-proof, but if we have to trust them it means that someone using a CPU without AVX2 will not be able to use the library.  We go a long way to target the base architecture, but if the package really wants to sneak those features... well, we probably can do little about that.  It's still good to know that there may be problems for some users.

**Comment by kllrak** [comment]
Sorry, I have one more question. Is the update to the corresponding JLL package expected to happen automatically, or do I need to trigger it somehow?

**Comment by giordano** [comment]
Ugh, the registration process failed: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=18521&view=logs&j=023ed65f-e065-55fe-4452-05a5186a5335&t=b718c291-7755-5e2a-f9ae-f6d624c03d80.  I'll need to have a look

**Comment by giordano** [comment]
I opened #4664, I believe the issue was the duplication of the non-libcxxwrap platforms, probably a relic from the past where we used to do things in a different way.  Let's see how that goes

**Comment by kllrak** [comment]
Many thanks, I appreciate the help!

**Comment by giordano** [comment]
https://github.com/JuliaRegistries/General/pull/57049

**Pull request merged**
