### PR TITLE
[Sundials] Trigger build

### PR DESCRIPTION
**Pull request by giordano**
Let's see if it works.  Ref #268.  CC: @ViralBShah

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
CC @jd-lara

**Comment by ViralBShah** [comment]
How do I actually find the failing log for freebsd?

**Comment by giordano** [comment]
Here it is: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=475&view=logs&jobId=11cc9737-c3b2-5b2e-49c1-3ecd4dd3473d&j=11cc9737-c3b2-5b2e-49c1-3ecd4dd3473d&t=6864626c-b206-5daa-5d51-831805962223

**Comment by jd-lara** [comment]
We have a working version of the BinaryBuilder here https://github.com/Energy-MAC/SundialsBuilder there is a hiccup with the integration of LAPACK through OpenBlas in 64 bits that the LLNL sundials team is tackling in a minor release.

Also, the new clang wrapper is here https://github.com/Energy-MAC/Sundials.jl/blob/jd/Sundialsv5/src/wrap_sundials.jl and works well.

I have not made new updates waiting for 1. the Sundials LAPACK fix for 64 bits and 2. reimplement the BinaryBuilder pipeline using the new Pkg traits.

**Comment by ViralBShah** [comment]
Thanks @jd-lara. I think a good strategy would be to get 3.1.1 working with the new artifacts infrastructure, and remove the suitesparse dependency (#270). 

From there, sundials 5 binaries should be an easy step when things are ready on that front.

**Comment by ViralBShah** [comment]
The freebsd build is having trouble with `libsundials_sunlinsolklu` but I can't quite tell why.

**Comment by jd-lara** [comment]
@ViralBShah yeah, I realized the new artifacts infrastructure was coming too late and already included the KLU in the same script.

**Comment by jd-lara** [comment]
> Thanks @jd-lara. I think a good strategy would be to get 3.1.1 working with the new artifacts infrastructure, and remove the suitesparse dependency (#270).
> 
> From there, sundials 5 binaries should be an easy step when things are ready on that front.

I would also wait to see if the patches I added will also be needed when LLNL makes the updates to Sundials.

**Comment by giordano** [comment]
I'm closing this pull request in favour of #270.  This want mainly meant to test the build, #270 is more interesting

**Pull request closed without merging**
