### PR TITLE
[UCX] enable logging, multi-threading, and rdma-core

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Comment by vchuravy** [comment]
```
[02:02:31] checking for ib_cm_send_req in -libcm... no
[02:02:31] configure: WARNING: CM support not found, skipping
[02:02:31] checking /usr/include/rdma/rdma_cma.h usability... no
[02:02:31] checking /usr/include/rdma/rdma_cma.h presence... no
[02:02:31] checking for /usr/include/rdma/rdma_cma.h... no
```

**Comment by vchuravy** [comment]
ah @giordano you were slightly to quick on the trigger

**Comment by giordano** [comment]
Ugh :persevere: 

I blocked registration in General: https://github.com/JuliaRegistries/General/pull/29026#issuecomment-770313225

**Comment by vchuravy** [comment]
Nah it's fine let me first check if this now has what I wanted, it's an improvement nontheless

**Pull request merged**
