### PR TITLE
Upgrade GAP to a developer snapshot of the 4.12 branch

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
@giordano merge please?

**Comment by giordano** [comment]
The license is missing

**Comment by fingolfin** [comment]
Huh, weird, it used to be there. Where did you see it missing? In any case, I added an explicit call to `install_license` (it used to be picked up automatically)

**Comment by giordano** [comment]
> Huh, weird, it used to be there.

The license is installed automatically only if there is only one directory in `${WORKSPACE}/srcdir` (`patches` being ignored), but now you have `${WORKSPACE}/srcdir/generated` there.

> Where did you see it missing?

https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=11885&view=results

**Pull request merged**
