### PR TITLE
[GMT] Update build_tarballs.jl

### PR DESCRIPTION
**Pull request by joa-quim**
Use a more recent GMT dev version

### CODE REVIEW

**Comment by fingolfin** [comment]
Shouldn't the version also be adjusted?

**Comment by joa-quim** [comment]
You’re probably right (must wait till Monday) but would that explain a “port access error”?

**Comment by fingolfin** [comment]
No, it's unrelated :-).

I think there was a network error, unrelated to your changes. But if you just apply any update to this, it'll run the tests again, hopefully it'll work this time.

E.g. bump the version as I suggested

**Comment by giordano** [comment]
I don't think buildkite reruns CI when closing/reopening a PR.

**Comment by giordano** [comment]
As a general remark working with Git and GitHub, opening a PR from a branch with the same name as the target branch is an [anti-pattern](https://blog.jasonmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/). You should always create a ***new*** branch.

**Pull request closed without merging**
