### PR TITLE
[OpenBLAS@0.3.27] Restore patch to fix compilation on aarch64-darwin

### PR DESCRIPTION
**Pull request by giordano**
Ref https://github.com/JuliaPackaging/Yggdrasil/pull/8446#issuecomment-2041183503.

### CODE REVIEW

**Comment by giordano** [comment]
Actually, I'm not sure the patch changes anything in practice? https://buildkite.com/julialang/yggdrasil/builds/9571#018ec4f1-42c1-49b3-a6c8-bf2843961451/6-6643
```
[ Info: Tree hash of contents of OpenBLAS.v0.3.27.aarch64-apple-darwin-libgfortran5.tar.gz: 06231e3b1f5b24391c982ece485fd71c163e7cab
[ Info: SHA256 of OpenBLAS.v0.3.27.aarch64-apple-darwin-libgfortran5.tar.gz: ac933f2494ab73e73e848a1e5439c9312bbb4f7517f527f13d86197e0a51176e
```
but this is _exactly_ what [we have now](https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/blob/ad46be4a79b7e8830bf6c608ae4476537b84d6d0/Artifacts.toml#L3-L8).

 Also, [the `peakflops` difference](https://github.com/JuliaPackaging/Yggdrasil/pull/8446#issuecomment-2046110240) may be an artifact of benchmarking, if I replace `libopenblas64_.dylib` in place I get the same performance as with OpenBLAS 0.3.26 on `master`.

**Comment by imciner2** [comment]
Interesting that it's going with the Neoverse N1 path. That one uses the same flags on all the builds, actually.

There is definitely a change in the flags used to build the Neoverse N2 files though.

0.3.26:
```
cc -c -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=512 -DMAX_PARALLEL_NUMBER=1 -DBUILD_BFLOAT16 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.26\" -march=armv8.5-a+sve+sve2+bf16 -mtune=neoverse-n2 -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=_isamax_k_NEOVERSEN2 -DASMFNAME=_isamax_k_NEOVERSEN2_ -DNAME=isamax_k_NEOVERSEN2_ -DCNAME=isamax_k_NEOVERSEN2 -DCHAR_NAME=\"isamax_k_NEOVERSEN2_\" -DCHAR_CNAME=\"isamax_k_NEOVERSEN2\" -DNO_AFFINITY -DTS=_NEOVERSEN2 -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_NEOVERSEN2 -UDOUBLE  -UCOMPLEX -UCOMPLEX -UDOUBLE -DUSE_ABS  -UUSE_MIN ../kernel/arm64/iamax_thunderx2t99.c -o isamax_k_NEOVERSEN2.o
```

General registry 0.3.27:
```
cc -c -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=512 -DMAX_PARALLEL_NUMBER=1 -DBUILD_BFLOAT16 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.27\" -march=armv8.2-a+sve+bf16 -mtune=cortex-a72 -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=_isamax_k_NEOVERSEN2 -DASMFNAME=_isamax_k_NEOVERSEN2_ -DNAME=isamax_k_NEOVERSEN2_ -DCNAME=isamax_k_NEOVERSEN2 -DCHAR_NAME=\"isamax_k_NEOVERSEN2_\" -DCHAR_CNAME=\"isamax_k_NEOVERSEN2\" -DNO_AFFINITY -DTS=_NEOVERSEN2 -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_NEOVERSEN2 -UDOUBLE  -UCOMPLEX -UCOMPLEX -UDOUBLE -DUSE_ABS  -UUSE_MIN ../kernel/arm64/iamax_thunderx2t99.c -o isamax_k_NEOVERSEN2.o
```

This PR:
```
cc -c -O2 -DMAX_STACK_ALLOC=2048 -Wall -DF_INTERFACE_GFORT -fPIC -DDYNAMIC_ARCH -DSMP_SERVER -DNO_WARMUP -DMAX_CPU_NUMBER=512 -DMAX_PARALLEL_NUMBER=1 -DBUILD_BFLOAT16 -DBUILD_SINGLE=1 -DBUILD_DOUBLE=1 -DBUILD_COMPLEX=1 -DBUILD_COMPLEX16=1 -DVERSION=\"0.3.27\" -march=armv8.5-a+sve+sve2+bf16 -mtune=neoverse-n2 -UASMNAME -UASMFNAME -UNAME -UCNAME -UCHAR_NAME -UCHAR_CNAME -DASMNAME=_isamax_k_NEOVERSEN2 -DASMFNAME=_isamax_k_NEOVERSEN2_ -DNAME=isamax_k_NEOVERSEN2_ -DCNAME=isamax_k_NEOVERSEN2 -DCHAR_NAME=\"isamax_k_NEOVERSEN2_\" -DCHAR_CNAME=\"isamax_k_NEOVERSEN2\" -DNO_AFFINITY -DTS=_NEOVERSEN2 -I.. -DBUILD_KERNEL -DTABLE_NAME=gotoblas_NEOVERSEN2 -UDOUBLE  -UCOMPLEX -UCOMPLEX -UDOUBLE -DUSE_ABS  -UUSE_MIN ../kernel/arm64/iamax_thunderx2t99.c -o isamax_k_NEOVERSEN2.o
```

So we have recovered the armv8.5 and neoverse-n2 specialization flags in this PR.

**Comment by giordano** [comment]
> Interesting that it's going with the Neoverse N1 path. That one uses the same flags on all the builds, actually.

That's because https://github.com/OpenMathLib/OpenBLAS/pull/4394 chooses neoverse-n1 for apple silicon.

> There is definitely a change in the flags used to build the Neoverse N2 files though.

But the resulting binary is *identical* to previous build of 0.3.27.

**Comment by giordano** [comment]
Side note, the 4x slowdown reported in https://github.com/JuliaPackaging/Yggdrasil/pull/8446#issuecomment-2046110240 may be due to number of threads being reset to 1 when changing the backing library with `BLAS.lbt_forward`.  Right now I don't have my laptop at hand, but I should try again with setting `OPENBLAS_NUM_THREADS=4` before starting julia.

**Comment by imciner2** [comment]
> But the resulting binary is identical to previous build of 0.3.27.

This I can't explain then, unless maybe our Clang compiler is ignoring the armv8.5 level silently and dropping it down?

**Comment by giordano** [comment]
Or maybe none of the features in `armv8.5-a+sve+sve2+bf16` makes a difference compared to `armv8.2-a+sve+bf16` and the instructions needed are already present in the latter?  According to https://gcc.gnu.org/onlinedocs/gcc/AArch64-Options.html (this is GCC, but Clang should be similar) the extensions that `armv8.5-a` has in addition to `armv8.2-a` are `+pauth`, `+flagm`, `+fp16fml`, `+dotprod`, `+sb`, `+ssbs`, `+predres`

**Comment by giordano** [comment]
@imciner2 are we good to go with this one, or do you have other concerns?

**Comment by imciner2** [comment]
I'm fine with it. I still can't explain the oddity of the binaries being seemingly identical even though the compiler flags changed... but I think its better to merge this and at least have it.

**Pull request merged**
