### PR TITLE
Snappy

### PR DESCRIPTION
**Pull request by aviks**
https://github.com/google/snappy

### CODE REVIEW

**Comment by aviks** [comment]
So this library audited fine, but when I use it as a dependency on another build, I get 

```
cd /workspace/srcdir/mongo-c-driver-1.16.2/cmake-build/src/libmongoc && /usr/bin/cmake -E cmake_link_script CMakeFiles/mongoc-stat.dir/link.txt --verbose=true
/opt/bin/x86_64-linux-gnu-gcc --sysroot=/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/ -O3 -DNDEBUG  -rdynamic CMakeFiles/mongoc-stat.dir/__/tools/mongoc-stat.c.o  -o mongoc-stat -Wl,-rpath,/workspace/srcdir/mongo-c-driver-1.16.2/cmake-build/src/libmongoc:/usr/local/lib:/workspace/destdir/lib:/workspace/srcdir/mongo-c-driver-1.16.2/cmake-build/src/libbson libmongoc-1.0.so.0.0.0 /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib/libssl.so /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib/libcrypto.so -lrt -lresolv /workspace/destdir/lib/libsnappy.so /opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root/usr/local/lib/libz.so /workspace/destdir/lib/libzstd.so ../libbson/libbson-1.0.so.0.0.0 -pthread
/opt/x86_64-linux-gnu/bin/../lib/gcc/x86_64-linux-gnu/4.8.5/../../../../x86_64-linux-gnu/bin/ld: warning: libstdc++.so.6, needed by /workspace/destdir/lib/libsnappy.so, not found (try using -rpath or -rpath-link)
/workspace/destdir/lib/libsnappy.so: undefined reference to `operator delete(void*)@GLIBCXX_3.4'
/workspace/destdir/lib/libsnappy.so: undefined reference to `std::string::_M_leak_hard()@GLIBCXX_3.4'
/workspace/destdir/lib/libsnappy.so: undefined reference to `vtable for __cxxabiv1::__si_class_type_info@CXXABI_1.3'
/workspace/destdir/lib/libsnappy.so: undefined reference to `std::string::append(char const*, unsigned long)@GLIBCXX_3.4'
/workspace/destdir/lib/libsnappy.so: undefined reference to `__gxx_personality_v0@CXXABI_1.3'
/workspace/destdir/lib/libsnappy.so: undefined reference to `operator delete[](void*)@GLIBCXX_3.4'
/workspace/destdir/lib/libsnappy.so: undefined reference to `operator new(unsigned long)@GLIBCXX_3.4'
/workspace/destdir/lib/libsnappy.so: undefined reference to `__cxa_pure_virtual@CXXABI_1.3'
/workspace/destdir/lib/libsnappy.so: undefined reference to `vtable for __cxxabiv1::__class_type_info@CXXABI_1.3'
/workspace/destdir/lib/libsnappy.so: undefined reference to `operator new[](unsigned long)@GLIBCXX_3.4'
/workspace/destdir/lib/libsnappy.so: undefined reference to `std::string::resize(unsigned long, char)@GLIBCXX_3.4'
collect2: error: ld returned 1 exit status
```

On my local machine, a `ccall` to a simple function using the jll seems to go through. However, I'm not sure if the `ldd` output is as expected:

```
:~/.julia/artifacts/dd01dfe7179e8dde544502792b644837630a3662/lib$ ldd libsnappy.so.
1.1.8
        linux-vdso.so.1 (0x00007fffda73e000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0d76260000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0d75ec0000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0d75ca0000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0d758a0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0d76a00000)
```

**Comment by giordano** [comment]
That's normal when linking a C++ library with a C compiler and the solution is written along the lines of the error message.

Something like this should do the trick:
```sh
if [[ "${nbits}" == 64 ]]; then
    export CFLAGS="-Wl,-rpath-link,/opt/${target}/${target}/lib64"
else
    export CFLAGS="-Wl,-rpath-link,/opt/${target}/${target}/lib"
fi
```
This is probably a good addition to https://juliapackaging.github.io/BinaryBuilder.jl/dev/troubleshooting/

**Comment by aviks** [comment]
Thanks, this works for linux, but fails for mac/clang where is goes not understand `-rpath-link`

```
 CMake Error at CMakeLists.txt:10 (_message):
[06:56:16]   The C compiler
[06:56:16]
[06:56:16]     "/opt/bin/clang"
[06:56:16]
[06:56:16]   ;is not able to compile a simple test program.
[06:56:16]
[06:56:16]   It fails ;with the following output:
[06:56:16]
[06:56:16]     Change Dir: /workspace/srcdir/mongo-c-driver-1.16.2/cmake-build/CMakeFiles/CMakeTmp
[06:56:16]
[06:56:16]     Run Build Command:"/usr/bin/make" "cmTC_3c7fe/fast"
[06:56:16]     /usr/bin/make -f CMakeFiles/cmTC_3c7fe.dir/build.make CMakeFiles/cmTC_3c7fe.dir/build
[06:56:16]     make[1]: Entering directory '/workspace/srcdir/mongo-c-driver-1.16.2/cmake-build/CMakeFiles/CMakeTmp'
[06:56:16]     Building C object CMakeFiles/cmTC_3c7fe.dir/testCCompiler.c.o
[06:56:16]     /opt/bin/clang --sysroot=/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root   -Wl,-rpath-link,/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/lib64    -o CMakeFiles/cmTC_3c7fe.dir/testCCompiler.c.o   -c /workspace/srcdir/mongo-c-driver-1.16.2/cmake-build/CMakeFiles/CMakeTmp/testCCompiler.c
[06:56:16]     Linking C executable cmTC_3c7fe
[06:56:16]     /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_3c7fe.dir/link.txt --verbose=1
[06:56:16]     /opt/bin/clang --sysroot=/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/sys-root -Wl,-rpath-link,/opt/x86_64-apple-darwin14/x86_64-apple-darwin14/lib64  -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_3c7fe.dir/testCCompiler.c.o  -o cmTC_3c7fe
[06:56:16]     ld: unknown option: -rpath-link
[06:56:16]     clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by giordano** [comment]
Ok, maybe we don't need it for macOS, try this:
```sh
if [[ "${nbits}" == 32 ]]; then
    export CFLAGS="-Wl,-rpath-link,/opt/${target}/${target}/lib"
elif [[ "${target}" != *-apple-* ]]; then
    export CFLAGS="-Wl,-rpath-link,/opt/${target}/${target}/lib64"
fi
```
It's just a matter of finding the right setup, but it should work.  We definitely need to put this in the troubleshooting page

**Pull request merged**
