### PR TITLE
[HiGHS] Update to v0.2.1 and don't expand libgfortran

### PR DESCRIPTION
**Pull request by galabovaa**

### CODE REVIEW

**Comment by galabovaa** [comment]
@odow 
@matbesancon 

I can not edit the file in https://github.com/JuliaPackaging/Yggdrasil/pull/2508/files

So I opened this PR, is this what we need?

**Comment by odow** [comment]
> I can not edit the file

That's because it is in @matbesancon's fork. Opening this PR is fine.

You just need to change the version to: `version = v"0.2.1"`.

I guess `gfortran` is okay to remove because it was only used for the fortran interface?

Please close the other PRs so we don't get confused:
https://github.com/JuliaPackaging/Yggdrasil/pull/2553
https://github.com/JuliaPackaging/Yggdrasil/pull/2551

You can edit this file online by going "Files Change > ... > Edit this file".

**Comment by giordano** [comment]
> I guess gfortran is okay to remove because it was only used for the fortran interface?

Oh yeah, audit confirms the library doesn't link to libgfortran.  Why we ever did that? :sweat_smile:

**Comment by galabovaa** [comment]
Yes, gfortran is not used anywhere in HiGHS, it is needed just for the fortran interface. Before the update to the HiGHS CMake build system it was required to build HiGHS too and there was no way of switching it off.

**Review by odow — APPROVED** [review]

**Pull request merged**
