### PR TITLE
[OpenBLAS@0.3.23] Add patch to fix CGEMM/CTRMM/DNRM2 on Apple M1/M2

### PR DESCRIPTION
**Pull request by pablosanjose**
Ref https://github.com/JuliaLang/julia/issues/53054

This should bring the fix from https://github.com/OpenMathLib/OpenBLAS/pull/4003 to Julia 1.10

### CODE REVIEW

**Comment by ViralBShah** [comment]
The patch is not applying cleanly: https://buildkite.com/julialang/yggdrasil/builds/8000#018d4684-0eea-427e-a169-f7f3059fa192/622-12767

**Comment by pablosanjose** [comment]
yes, let me try to reconstruct the patch

**Comment by giordano** [comment]
The [diff](https://github.com/OpenMathLib/OpenBLAS/commit/efcf71255aaf0c636fc76e5235dde8bb9cf76469.diff) may be simpler than than the [patch](https://github.com/OpenMathLib/OpenBLAS/commit/efcf71255aaf0c636fc76e5235dde8bb9cf76469.patch), maybe it's easier to start from there.

**Comment by pablosanjose** [comment]
I'm just learning the ropes here, but I think the issue might be that we also need the M2 patch from commit caa29451, since otherwise the patch does not apply properly to the 0.3.23 release

**Comment by giordano** [comment]
Yes, but at this point it's easier to have a single cumulative patch.  Something like (untested!) should work
```diff
diff --git a/cpuid_arm64.c b/cpuid_arm64.c
index 809f48e95a..e586f9a3c2 100644
--- a/cpuid_arm64.c
+++ b/cpuid_arm64.c
@@ -267,8 +267,9 @@ int detect(void)
 	}
 #else
 #ifdef __APPLE__
-	sysctlbyname("hw.cpufamily",&value,&length,NULL,0);
-	if (value ==131287967|| value == 458787763 ) return CPU_VORTEX; //A12/M1
-	if (value == 3660830781) return CPU_VORTEX; //A15/M2
+	sysctlbyname("hw.cpufamily",&value64,&length64,NULL,0);
+	if (value ==131287967|| value == 458787763 ) return CPU_VORTEX;
 #endif
 	return CPU_ARMV8;	
 #endif
diff --git a/kernel/arm64/cgemm_kernel_8x4.S b/kernel/arm64/cgemm_kernel_8x4.S
index 24e08a646a..f100adc7af 100644
--- a/kernel/arm64/cgemm_kernel_8x4.S
+++ b/kernel/arm64/cgemm_kernel_8x4.S
@@ -49,7 +49,7 @@ USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #define pCRow3		x15
 #define pA		x16
 #define alphaR		w17
-#define alphaI		w18
+#define alphaI		w19
 
 #define alpha0_R	s10
 #define alphaV0_R	v10.s[0]
diff --git a/kernel/arm64/cgemm_kernel_8x4_thunderx2t99.S b/kernel/arm64/cgemm_kernel_8x4_thunderx2t99.S
index 29a68ff227..2c63925be2 100644
--- a/kernel/arm64/cgemm_kernel_8x4_thunderx2t99.S
+++ b/kernel/arm64/cgemm_kernel_8x4_thunderx2t99.S
@@ -49,7 +49,7 @@ USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #define pCRow3		x15
 #define pA		x16
 #define alphaR		w17
-#define alphaI		w18
+#define alphaI		w19
 
 #define alpha0_R	s10
 #define alphaV0_R	v10.s[0]
diff --git a/kernel/arm64/ctrmm_kernel_8x4.S b/kernel/arm64/ctrmm_kernel_8x4.S
index 5c08273975..e8f1d8cf30 100644
--- a/kernel/arm64/ctrmm_kernel_8x4.S
+++ b/kernel/arm64/ctrmm_kernel_8x4.S
@@ -49,10 +49,10 @@ USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 #define pCRow3		x15
 #define pA		x16
 #define alphaR		w17
-#define alphaI		w18
-#define temp		x19
-#define tempOffset	x20
-#define tempK		x21
+#define alphaI		w19
+#define temp		x20
+#define tempOffset	x21
+#define tempK		x22
 
 #define alpha0_R	s10
 #define alphaV0_R	v10.s[0]
diff --git a/kernel/arm64/dznrm2_thunderx2t99.c b/kernel/arm64/dznrm2_thunderx2t99.c
index e342b0b63f..6077c85dd1 100644
--- a/kernel/arm64/dznrm2_thunderx2t99.c
+++ b/kernel/arm64/dznrm2_thunderx2t99.c
@@ -27,7 +27,7 @@ USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
 
 #include "common.h"
-
+#include <float.h>
 #include <arm_neon.h>
 
 #if defined(SMP)
@@ -404,7 +404,8 @@ FLOAT CNAME(BLASLONG n, FLOAT *x, BLASLONG inc_x)
 #else
 	nrm2_compute(n, x, inc_x, &ssq, &scale);
 #endif
-	if (fabs(scale) <1.e-300) return 0.;
+	volatile FLOAT sca = fabs(scale);
+	if (sca < DBL_MIN) return 0.;
 	ssq = sqrt(ssq) * scale;
 
 	return ssq;
```

**Comment by ViralBShah** [comment]
Seems reasonable to pull that in as well. It is not surprising that we need more than one patch.

**Comment by pablosanjose** [comment]
I've added the M2 patch together with the actual fix, including the history information, and it seems to be passing. Thanks to both for your guidance.
So if this eventually goes green and is merged, what else is needed to get the fix bundled into 1.10? Will it be automatic upon releasing 1.10.1?

**Comment by giordano** [comment]
> So if this eventually goes green and is merged, what else is needed to get the fix bundled into 1.10? Will it be automatic upon releasing 1.10.1?

Not quite.  You'll need to make a PR for Julia against branch https://github.com/JuliaLang/julia/tree/backports-release-1.10 to update the build of OpenBLAS, see for example instructions at https://github.com/JuliaLang/julia/pull/52762#issue-2067648457. In your case you can skip second point because you aren't changing the upstream version.

**Comment by ViralBShah** [comment]
Should we be using `value64` and `length64` as in the OpenBLAS 4003 PR?

```
sysctlbyname("hw.cpufamily",&value64,&length64,NULL,0);
	if (value64 ==131287967|| value64 == 458787763 ) return CPU_VORTEX; //A12/M1
	if (value64 == 3660830781) return CPU_VORTEX; //A15/M2
```

**Comment by pablosanjose** [comment]
We are, see PATCH 6/8 (line 187)

**Comment by ViralBShah** [comment]
Ah thanks. I didn't realize that the patches are stacked on top of each other.

**Comment by pablosanjose** [comment]
> Not quite. You'll need to make a PR for Julia against branch https://github.com/JuliaLang/julia/tree/backports-release-1.10 to update the build of OpenBLAS, see for example instructions at https://github.com/JuliaLang/julia/pull/52762#issue-2067648457. In your case you can skip second point because you aren't changing the upstream version.

https://github.com/JuliaLang/julia/pull/53074

Alright, I hope I did that correctly. (Perhaps the PR title should be changed).

**Pull request merged**
