### PR TITLE
[LLVM_full@18] Rebuild for FreeBSD AArch64 support

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Comment by giordano** [comment]
You also need to build the corresponding assert version

**Comment by ararslan** [comment]
I had planned to do that in a subsequent PR, do you mean it should be part of this one?

**Comment by giordano** [comment]
Yes, we usually do them both in a single PR.

**Comment by giordano** [comment]
@ararslan can you please follow up with all the other related packages? It's quite important to have consistent version numbers among all of them

**Comment by ararslan** [comment]
By related packages do you mean like Clang, LLD, etc.? Basically just all of the other things that are in `L/LLVM/`?

**Comment by giordano** [comment]
Yes, also libllvm and such.  See the history of the directory to see what's the chain (I don't know it myself)

**Comment by ararslan** [comment]
It looks like it's LLVM_full then libLLVM (just opened a PR) then Clang, LLD, MLIR, and LLVM in any order.

**Pull request merged**
