### PR TITLE
Attempt to build suitesparse with PARTITION module (with metis)

### PR DESCRIPTION
**Pull request by ViralBShah**
Now that metis-5.1.0 is included in SuiteSparse, let's try build CHOLMOD with the PARTITION module. This should give us the capability to do nested dissection orderings. For cholesky factorizations on certain graphs, this may give better fill.

Cc @ranjanan

### CODE REVIEW

**Comment by ViralBShah** [comment]
@staticfloat @giordano How do I fix `sys/resource.h` not found issue on Windows? Seems like mingw doesn't provide it but you need msys (for posix).  
https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=566&view=logs&jobId=2ea53ff3-6db4-5249-2f87-da31e5d82122&j=2ea53ff3-6db4-5249-2f87-da31e5d82122&t=67e8a9f6-14e3-5f6a-4b95-09ca0e7ad8bd

**Comment by ViralBShah** [comment]
Not sure how to get metis to build on windows with mingw. If anyone has ideas, much appreciated.

This is the failure: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=570&view=logs&j=2ea53ff3-6db4-5249-2f87-da31e5d82122&t=67e8a9f6-14e3-5f6a-4b95-09ca0e7ad8bd&l=8296

**Comment by ViralBShah** [comment]
Trying all these patches: https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-metis

**Comment by ViralBShah** [comment]
Binaries including Metis are here: https://github.com/JuliaBinaryWrappers/SuiteSparse_jll.jl/releases/tag/SuiteSparse-v5.4.0%2B2

**Comment by fredrikekre** [comment]
Shouldn't this be done by depending on Metis_jll?

**Comment by giordano** [comment]
I think you're right. But I'm confused, it looks like suitesparse vendors metis?

**Comment by ViralBShah** [comment]
Yes, metis is included in suitesparse. This just enables that build.

**Comment by ViralBShah** [comment]
Argh, I didn't realize we already have Metis_jll. So this is a bit of trouble. Since suitesparse ships in stdlib, we do want metis in the build so suitesparse can use it. 

Any thoughts?

**Comment by giordano** [comment]
> Yes, metis is included in suitesparse

This is a bit unfortunate.  In general we want as granular artifacts as possible, to increase reusability.  If someone needs metis only doesn't need to grab the rest of suitesparse.  This is for example what [we did for Xorg libraries](https://github.com/JuliaPackaging/Yggdrasil/pull/92), which were initially inside a single huge artifact, making it hard to pick up a single library.

> The trigger for this work is that we do want Circuitscape.jl to be able to use nested dissection.

If metis is not needed in Julia itself, then I'd suggest reverting this PR and adding `METIS_jll` as dependencies of whatever `Circuitscape.jl` needs.  Does building SuiteSparse with metis enable extra feature apart from providing an extra library?

**Comment by ViralBShah** [comment]
I agree on the granularity. The issue is mainly that SuitesSparse ships as part of stdlib. So may be just make SuiteSparse depend on Metis_jll, and then install Metis_jll along with SuiteSparse_jll whenever we move the Julia stdlib to use these new packages?

**Comment by giordano** [comment]
> The issue is mainly that SuitesSparse ships as part of stdlib.

That's why I asked if Julia itself needs metis or only third-party applications like `Circuitscape.jl` and if building metis enables extra feature in SuiteSparse or it's a runtime only dependency: if Julia doesn't need metis and metis is only a runtime dependency for applications using SuiteSparse, then SuiteSparse doesn't neeed metis at all.  But the fact that SuiteSparse vendors metis makes me think that it uses metis at build-time if available.

**Comment by ViralBShah** [comment]
When we build SuiteSparse with Metis, we want to be able to use it in sparse cholesky solves. So, in that sense, Julia will need it. It is not a common use case, but packages like Circuitscape will end up using it through the sparse linear algebra that ships in the stdlib.

I think the right thing to do is to always install Metis along with SuiteSparse, but keep it a separate dependency. We can implement this when we update the stdlib to install the artifact binaries.

**Comment by giordano** [comment]
Agreed, thank you so much for going ahead and opening the new pull requests!

**Pull request merged**
