### PR TITLE
[Tesseract] Upgrade to Tesseract v5.

### PR DESCRIPTION
**Pull request by sunoru**
The libtool files for `libtiff` have been manually included for ease of compilation. I hope this is fine?

### CODE REVIEW

**Comment by giordano** [comment]
> The libtool files for libtiff have been manually included for ease of compilation. I hope this is fine?

Not really, we prefer to [_delete_ them](https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1105), adding them goes exactly in the opposite direction

**Comment by sunoru** [comment]
> > The libtool files for libtiff have been manually included for ease of compilation. I hope this is fine?
> 
> Not really, we prefer to [_delete_ them](https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1105), adding them goes exactly in the opposite direction

I have read that discussion. The use here is only for Tesseract's building process since it is required there. They won't be included in the products. Actually, the building scripts for previous versions will also fail now, because the .la files have been removed in the dependencies.

BTW, do you have any idea why there are two failures in the CI checks? It says:

```ERROR: LoadError: Error when installing package XSLT_jll:
IOError: unlink("/depot/packages/XSLT_jll/4AZBo/src/wrappers/powerpc64le-linux-gnu.jl"): no such file or directory (ENOENT)```

**Comment by giordano** [comment]
How are these files generated?  What I don't like is that this isn't very sustainable, it's very easy for someone to update the version of the package without updating the libtool files correctly, so you get into an inconsistent state.

@fingolfin do you have ideas about how to deal with this situation?

**Comment by giordano** [comment]
Maybe you can use CMake instead of autoconf and completely sidestep the libtool issue?

**Comment by giordano** [comment]
Oh, I think it's again an issue with another package referencing a libtool file.  I think it's leptonica.

**Comment by giordano** [comment]
Should have been fixed by #4737 (in which I found a small bug in our removal of libtool files: https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/1199).  Of course you'll have to wait for the new version to make it to the registry before trying again.

**Comment by fingolfin** [comment]
@giordano seems you've figure it out. Annoying that it keeps making trouble :-(. Anyway, I hope that'll be it. But we'll see..

**Comment by sunoru** [comment]
Thanks so much. I will try again later. (BTW, the `.la` files were copied from a previous version of `Libtiff_jll.jl` where `BinaryBuilder.jl` didn't remove them.)

**Comment by sunoru** [comment]
Looks problems solved :smile:

**Comment by giordano** [comment]
Lovely, thanks!

**Pull request merged**
