### PR TITLE
[GR] Build using BinaryBuilder

### PR DESCRIPTION
**Pull request by barche**
WIP for issue #11 

This builds on the three platforms that I can test myself, but the GR tests don't pass yet because Qhull only exposes the reentrant variant of the library.

### CODE REVIEW

**Comment by ViralBShah** [comment]
What specifically do we need to do with qhull?

**Comment by ViralBShah** [comment]
https://github.com/jheinen/GR.jl/issues/314

**Comment by barche** [comment]
> What specifically do we need to do with qhull?

Only #1508

**Comment by barche** [comment]
The remaining problem is that the default plotting window (GKSterm) won't build because it requires ZeroMQ to be exactly at version 4. Since we have Qt I think it should be possible to use gksqt instead, but on Mac it fails with:

```
dyld: Library not loaded: @rpath/QtWidgets
  Referenced from: /Users/user/tmp/clean_julia_depot/artifacts/a3cef704ad530f86921b2fd1b0d084cb1425a0a2/Applications/gksqt.app/Contents/MacOS/gksqt
  Reason: image not found
```

However, QtWidgets is loaded, from `dllist`:

```
/Users/user/tmp/clean_julia_depot/artifacts/2cb154cd91aa24f8120a30441414a4507ad0311f/lib/QtWidgets.framework/Versions/5/QtWidgets
```



During building there are these messages:

```
[ Info: Skipping binary analysis of Applications/gksqt.app/Contents/Info.plist
[ Info: Checking Applications/gksqt.app/Contents/MacOS/gksqt with RPath list String[]
[ Info: Linked library QtGui has been auto-mapped to @rpath/QtGui
[ Info: Linked library libfreetype.6.dylib has been auto-mapped to @rpath/libfreetype.6.dylib
[ Info: Linked library QtWidgets has been auto-mapped to @rpath/QtWidgets
[ Info: Linked library libz.1.dylib has been auto-mapped to @rpath/libz.1.dylib
```

**Comment by barche** [comment]
Adding `gksqt` as an `ExecutableProduct` and then starting it like this got me a plot in a window, but if the user closes the window there is no apparent way to recover...

```julia
julia> ENV["GKSwstype"]="socket"
"socket"

julia> using GR_jll

julia> p = gksqt() do gkscmd
         run(`$gkscmd`; wait=false)
       end
Process(`/Users/bjanssens/tmp/clean_julia_depot/artifacts/8e20f74413b6345ed51cc9f41db7f41fee9cef53/bin/gksqt`, ProcessRunning)

julia> using GR

julia> plot(rand(4,4))
```

**Comment by giordano** [comment]
> but if the user closes the window there is no apparent way to recover...

I've seen this issue with GR before

**Comment by giordano** [comment]
https://github.com/jheinen/GR.jl/issues/290

**Comment by jheinen** [comment]
> > but if the user closes the window there is no apparent way to recover...
> 
> I've seen this issue with GR before

... which should be fixed in the meantime.

**Comment by barche** [comment]
Yes, I see that in GR itself there is code to restart gksqt, but that can't work in the BinaryBuilder system because we have to use the `gksqt` function from GR_jll to start it, or it won't find the Qt libraries. So I see three options:

1. Start gksqt from within GR.jl, using a more streamlined version of the code I outlined above, plus code to restart it from the Julia side if needed
2. Hack around the path issues to allow GR itself (the C lib)  to start gksqt
3. Add ZeroMQ version 4.0 to allow building GKSterm, but that will probably result in the same kind of library issues

To me, 1 seems the most elegant way, though I don't know if `gksqt` is actually the preferred window type?

**Comment by barche** [comment]
It seems that recovery is possible using:

```julia
julia> p = gksqt() do gkscmd
         run(`$gkscmd`; wait=false)
       end
Process(`/Users/bjanssens/tmp/clean_julia_depot/artifacts/8e20f74413b6345ed51cc9f41db7f41fee9cef53/bin/gksqt`, ProcessRunning)

julia> GR.init(true)
true

julia> plot(rand(4,4))
```

**Comment by barche** [comment]
Added all the platforms for which Qt is built, for me this is working together with PR https://github.com/jheinen/GR.jl/pull/339

For reference, the GR config summary:

```
GKS plugins:
- cairoplugin:
        PNG output: Yes
        BMP output: Yes
        JPEG output: Yes
        Tiff output: Yes
        Sixel output: Yes
        Memory output: Yes
        X11 output: No (not available in CMake build)
- videoplugin:
        MP4 output: Yes
        MOV output: Yes
        WEBM output: Yes
        OGG output: Yes
        GIF output: Yes
- pgfplugin:
        TeX output: Yes
- wmfplugin:
        WMF output: Yes
- gsplugin: No (X11 / Xt not found)
- svgplugin:
        SVG output: Yes
- glplugin: Yes
- zmqplugin: No (ZeroMQ not found)
- x11plugin: No (X11 / Xft / Xt not found)
- qt5plugin: Yes
- qtplugin: No (Qt4 not found)
- gtkplugin: No (not implemented yet)

GKS applications:
- gksqt: Yes
```

**Comment by jheinen** [comment]
> Added all the platforms for which Qt is built, for me this is working together with PR [jheinen/GR.jl#339](https://github.com/jheinen/GR.jl/pull/339)
> 
> For reference, the GR config summary:
> 
> ```
> GKS plugins:
> - cairoplugin:
>         PNG output: Yes
>         BMP output: Yes
>         JPEG output: Yes
>         Tiff output: Yes
>         Sixel output: Yes
>         Memory output: Yes
>         X11 output: No (not available in CMake build)
> - videoplugin:
>         MP4 output: Yes
>         MOV output: Yes
>         WEBM output: Yes
>         OGG output: Yes
>         GIF output: Yes
> - pgfplugin:
>         TeX output: Yes
> - wmfplugin:
>         WMF output: Yes
> - gsplugin: No (X11 / Xt not found)
> - svgplugin:
>         SVG output: Yes
> - glplugin: Yes
> - zmqplugin: No (ZeroMQ not found)
> - x11plugin: No (X11 / Xft / Xt not found)
> - qt5plugin: Yes
> - qtplugin: No (Qt4 not found)
> - gtkplugin: No (not implemented yet)
> 
> GKS applications:
> - gksqt: Yes
> ```
> 
> Edit: @jheinen is this OK?

Looks fine. Thanks a lot !!

**Comment by ViralBShah** [comment]
This is immense progress! Is the next step to remove the draft status and make it a proper PR?

**Comment by giordano** [comment]
Does GR currently work on aarch64?

**Comment by jheinen** [comment]
We are currently working both on a self-contained Debian 9 based aarch64 cross compile build (on our own CI/CD system) and a BinaryBuilder variant. Both will be made available soon ...

**Comment by barche** [comment]
> Does GR currently work on aarch64?

The script in this PR doesn't work because the gksqt executable is not built, since we don't build Qt on aarch64. I tried fixing that, but it errors on not finding the math.h header.

What is the concrete use case for aarch64? It appears that Qt only has a device type for nVidia Jetson, not sure if that is use case here too?

**Comment by ViralBShah** [comment]
I guess the real use case is raspberry pi but that is armv7.

**Comment by giordano** [comment]
I was just checking that this build works on all platforms currently supported by GR, just in case that'd be a regression compared to current situation

**Comment by barche** [comment]
> I guess the real use case is raspberry pi but that is armv7. But if this PR already works on x86 on the 3 OSes we support, it would be great to get that merged.

armv7 is covered, I just can't test it because I don't have a Raspberry Pi :)

**Comment by ViralBShah** [comment]
Bump. Since this is all green, can we get it merged? I feel like this is the first step in getting Plots.jl to be able to use all the fancy new infrastructure.

**Comment by jheinen** [comment]
Does `GR_jll` need a special setup (for the dynamic loader search paths)? Manually starting `gksqt` leads to the following problem (on my MacBook):
```
.julia/artifacts/35fbd0565157bb11e835f17fd1775134df7fc0f8/Applications/gksqt.app/Contents/MacOS/gksqt
dyld: Library not loaded: @rpath/QtWidgets
  Referenced from: /Users/jheinen/.julia/artifacts/35fbd0565157bb11e835f17fd1775134df7fc0f8/Applications/gksqt.app/Contents/MacOS/gksqt
  Reason: image not found
zsh: abort      
```

**Comment by giordano** [comment]
https://juliapackaging.github.io/BinaryBuilder.jl/dev/jll/#ExecutableProduct

**Comment by barche** [comment]
> Does `GR_jll` need a special setup (for the dynamic loader search paths)? Manually starting `gksqt` leads to the following problem (on my MacBook):

Yes, this is what most of the changes in my PR https://github.com/jheinen/GR.jl/pull/339 are about.

**Comment by jheinen** [comment]
So the ExecutableProduct (`gksqt`) has to be started by Julia (in the GR.jl wrapper)?

**Comment by barche** [comment]
Yes, theoretically it is possible to export the environment variables, but that will pollute the environment, and also I tried it and it seems that the GR library ignores the environment variables when starting gksqt, so I think it would require adaptation of the GR library.

**Pull request merged**
