### PR TITLE
Add MPIPreferences to dependencies of P4est_jll

### PR DESCRIPTION
**Pull request by JoshuaLampert**
Following the advice from @simonbyrne and @vchuravy in https://github.com/JuliaParallel/MPI.jl/issues/721.

### CODE REVIEW

**Comment by JoshuaLampert** [comment]
Any idea why one test is failing @vchuravy (or anyone)?

**Comment by simonbyrne** [comment]
```
┌ Error: Built P4est but libsc still unsatisfied:
```

**Comment by JoshuaLampert** [comment]
Yes, and
`ERROR: could not load library "/cache/build/yggy-amdci7-8/julialang/yggdrasil/P/P4est/build/x86_64-linux-gnu-mpi+mpitrampoline/geNnEL6L/x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline/destdir/lib/libp4est.so.0.0.0"`, but I don't know why and how to fix it. Any ideas on that?

**Comment by JoshuaLampert** [comment]
Yes, and
`ERROR: could not load library "/cache/build/yggy-amdci7-8/julialang/yggdrasil/P/P4est/build/x86_64-linux-gnu-mpi+mpitrampoline/geNnEL6L/x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline/destdir/lib/libp4est.so.0.0.0"`, but I don't know why and how to fix it. Any ideas on that?

**Comment by vchuravy** [comment]
```
julia +1.7 --project=../../.ci/ build_tarballs.jl --verbose --debug x86_64-linux-gnu-mpi+mpitrampoline
```

Passed locally...

```
[ Info: Found a valid dl path libsc.so while looking for libsc
[ Info: /home/vchuravy/builds/Yggdrasil/P/P4est/build/x86_64-linux-gnu-mpi+mpitrampoline/pQDfrNuQ/x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline/destdir/lib/libsc.so matches our search criteria of libsc
[ Info: Compressing files in /home/vchuravy/builds/Yggdrasil/P/P4est/build/x86_64-linux-gnu-mpi+mpitrampoline/pQDfrNuQ/x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline/destdir/logs/P4est
[ Info: Tree hash of contents of P4est.v2.8.1.x86_64-linux-gnu-mpi+mpitrampoline.tar.gz: e1689e17edced863c2a6ac5fcf83f8d56bf1f7a3
[ Info: SHA256 of P4est.v2.8.1.x86_64-linux-gnu-mpi+mpitrampoline.tar.gz: 521d021b5550a64838a7045d7b0d2a63de31a7c65c2e46d27a22fbb23a0bc884
[ Info: Tree hash of contents of P4est-logs.v2.8.1.x86_64-linux-gnu-mpi+mpitrampoline.tar.gz: 56f619217526a89137762931e16d9038360eb972
[ Info: SHA256 of P4est-logs.v2.8.1.x86_64-linux-gnu-mpi+mpitrampoline.tar.gz: 226aa2f60c54e1407c86c47c296a8929f3dde5577500b5c1f50bdc3fc3b5f3ef
[ Info: Timings: setup: 3m 20.28s, build: 15.65s, audit: 19.78s, packaging: 0.85s
```

**Comment by JoshuaLampert** [comment]
I did that previously after #6396 was merged. But I think I needed [f39e5a4](https://github.com/JuliaPackaging/Yggdrasil/pull/6360/commits/f39e5a4c6650d8d08d0aba8877b61720f516b9cc). Let's hope CI passes now.

**Pull request merged**
