### PR TITLE
Update to latest BB and BBB

### PR DESCRIPTION
**Pull request by fingolfin**
... and all their deps, while at it.

I need this for https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/93

@giordano so I just did a `Pkg.update()` in there -- but perhaps that's too much? Not sure what else would be the recommended way, though?

### CODE REVIEW

**Comment by giordano** [comment]
> Not sure what else would be the recommended way, though?

I usually do
```
]up BinaryBuilder BinaryBuilderBase
```
but I think you used something like Julia nightly or v1.6, which pulled in many JLLs as stdlibs, which wouldn't work here

**Comment by giordano** [comment]
Wait, merging this without https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/986 is a bad idea

**Comment by fingolfin** [comment]
Yeah my bad, I was not using my `julia-for-bb` binary. Sorry for causing extra work now :-(

**Comment by giordano** [comment]
Hopefully we won't need it anymore :crossed_fingers:  I'm still stuck at
```
Julia Version 1.6.0-DEV.1581
Commit 377aa809eb (2020-11-26 01:44 UTC)
```

**Pull request merged**
