### PR TITLE
[Sundials@5] Resubmit Sundials build

### PR DESCRIPTION
**Pull request by ViralBShah**
Trying the suggestion from https://github.com/LLNL/sundials/issues/29 for fixing windows build.
Remove gcc preferred version.

### CODE REVIEW

**Comment by ViralBShah** [comment]
Upstream suggested fix for windows does not work, so we are retaining the same fix from earlier.

https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=1498&view=logs&j=0c8f16f8-c0df-5cf3-8178-b591b90f12cf&t=fdd4b889-5821-506e-6c2a-64b809c5b85c&l=3913

**Comment by ViralBShah** [comment]
cc @jd-lara 

Hoping this one goes through now that #485 is fixed.

**Comment by giordano** [comment]
We really need GCC v6: https://github.com/JuliaPackaging/Yggdrasil/pull/421#discussion_r370961388

**Comment by ViralBShah** [comment]
Since ppc is using -lgomp, do we not need CompilerSupportLibraries?

**Comment by ViralBShah** [comment]
@giordano This didn't seem to get uploaded here: https://github.com/JuliaBinaryWrappers/Sundials-5_jll.jl

**Comment by giordano** [comment]
That's the wrong repository anyway, but we still have problems: https://github.com/JuliaPackaging/Yggdrasil/pull/488#issuecomment-584638894

**Comment by ViralBShah** [comment]
Ok, where should I look when the bugs are all squashed?

**Comment by giordano** [comment]
I've opened #497 to track this last issue

**Comment by ViralBShah** [comment]
It seems like #499 should fix the above issue, but even after wiping my .julia and installing everything again, I still get:  

```
julia> using Sundials_jll
[ Info: Precompiling Sundials_jll [fb77eaff-e24c-56d4-86b1-d163f2edb164]
ERROR: LoadError: LoadError: InitError: could not load library "C:\Users\viral\.julia\artifacts\bc235f981126068329fbf3f9f58f57ae63827269\bin\libspqr.dll"
The specified procedure could not be found.
```

**Comment by giordano** [comment]
https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/669#issuecomment-586546677

**Comment by ViralBShah** [comment]
Is it possible that the libcholmod that is being picked up by libspqr is the one from Julia system install and not the one from SuiteSparse_jll? I wish we could stop doing two separate SuiteSparse builds.

**Comment by ViralBShah** [comment]
@giordano Hah just saw your comment.

**Comment by giordano** [comment]
> Is it possible that the libcholmod that is being picked up by libspqr is the one from Julia system install and not the one from SuiteSparse_jll?

Yes, that was my conclusion in the comment linked above :wink:

**Comment by ViralBShah** [comment]
In #548 I have disabled METIS linking in SuiteSparse for now due to the very special kinds of issues that will only be possible to resolve once SuiteSparse is not shipped in stdlib. 

I think this should fix the Sundials issue on Windows.

**Pull request merged**
