### PR TITLE
Recompile IPOPT with MUMPS 5.4.1 and LBT

### PR DESCRIPTION
**Pull request by amontoison**
@odow @ViralBShah

### CODE REVIEW

**Comment by ViralBShah** [comment]
@giordano Is this the right way to pick LBT?

**Comment by amontoison** [comment]
Maybe we should also add a compat entry for LBT to be sure to install the version `v5.1.1`.

**Comment by ViralBShah** [comment]
But isn't LBT provided by Julia - and hence you don't get to pick which version it is?

**Comment by giordano** [comment]
they can have different ABIs (like `libblastrampoline.so.5` vs `libblastrampoline.so.6` in the future) so you have to pick one and link against that one.  In julia v1.7+ we always use v5, but apparently the windows library is subtly broken.

**Comment by ViralBShah** [comment]
Should we merge?

**Comment by ViralBShah** [comment]
@giordano Do we need something like https://github.com/JuliaPackaging/Yggdrasil/pull/4770/files#diff-4bc380ae1048b4b2419d0800b074f33fa94b5101e3c56d2bf85f4bc3c6894416R63 for LBT?

**Comment by giordano** [comment]
This package requires Julia v1.8 anyway, so at the moment we don't need to do much

**Comment by odow** [comment]
I understood from https://github.com/jump-dev/Ipopt.jl/pull/327#issuecomment-1233540747 that this PR won't fix the issue?

**Pull request merged**
