### PR TITLE
Update GAP_lib

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by giordano** [comment]
No version change?

**Comment by fingolfin** [comment]
No version change as this is so far still only used in a PR (i.e. by nobody other than me and 1-2 testers), so I hope a new version is not necessary...

**Comment by giordano** [comment]
Sure, up to you, I was just double-checking :slightly_smiling_face:

**Comment by fingolfin** [comment]
And I very much appreciate that you double check, you caught enough of my stupid mistakes that way 😬

**Pull request merged**
