### PR TITLE
[ROCmDeviceLibs] Use any platform

### PR DESCRIPTION
**Pull request by pxl-th**

### CODE REVIEW

**Comment by gbaraldi** [comment]
Oh, that's annyoing that it finds the lld from the host but LGTM

**Comment by pxl-th** [comment]
Not sure what's changed, but if I don't tell it to use project from `.ci` dir, then this does not happen (those files are not there at all).

**Comment by pxl-th** [comment]
Thanks for merging!

**Comment by gbaraldi** [comment]
So what's changed is that I made lld work like the normal linker, but maybe we will hit corner cases like this one.

**Comment by giordano** [comment]
Also, these changes are on master of BinaryBuilderBase.jl, but probably not in a stable release yet

**Pull request merged**
