### PR TITLE
Add builder for CGAL julia wrapper

### PR DESCRIPTION
**Pull request by rgcv**
Submitting a recipe for building the wrapper code for a (very rough WIP) package that exposes some of [CGAL](https://www.cgal.org)'s types and functionality: [CGAL.jl](https://github.com/rgcv/CGAL.jl).

A few notes:

- Akin to the libcxxwrap-julia builder recipe (see #357), I too am downloading julia during the build process as a temporary workaround.
- Unlike the aforementioned library, I was met with linking errors when linking against its `cxx03` string abi binaries. I suspected I might encounter this error (https://github.com/JuliaPackaging/Yggdrasil/pull/393#discussion_r367458743). Filtering them out appeared to work.
- Since, apparently, my build system isn't a simple build system anymore, `dll`s in mingw builds are being manually copied to `bin` as well. Any pointers on removing this from the build script would be much appreciated.

Any and all feedback will be more than welcome!

### CODE REVIEW

**Comment by giordano** [comment]
> Unlike the aforementioned library, I was met with linking errors when linking against its cxx03 string abi binaries. I suspected I might encounter this error (#393 (comment)). Filtering them out appeared to work.

What error did you get exactly? Are you sure you need to expand here?

Note that there is no license in the generated tarball

**Comment by rgcv** [comment]
> What error did you get exactly? Are you sure you need to expand here?
I was getting a linking error with a name-mangled reference to what I can only assume is a c++11 basic_string.. I think I can still find the exact logs, I'll get back to you on that.

> Note that there is no license in the generated tarball
Misfire on my behalf, I'll address it ASAP

**Comment by giordano** [comment]
> I was getting a linking error with a name-mangled reference to what I can only assume is a c++11 basic_string.. I think I can still find the exact logs, I'll get back to you on that.

If so, this issue has been likely fixed by https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/604, but if cgal has symbols involving basic_string it's also very much probable that you need to expand cxxstring ABIs for that package first. Can you please run again locally the builder for cgal with the latest master of BinaryBuilder.jl and see if you get a warning about the C++ string ABI?

**Comment by rgcv** [comment]
> If so, this issue has been likely fixed by [JuliaPackaging/BinaryBuilder.jl#604](https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/604), but if cgal has symbols involving basic_string it's also very much probable that you need to expand cxxstring ABIs for that package first.

I'm scratching my head now, remembering a relatively important detail: since 5.0, CGAL's minimum supported version of the C++ standard is C++ 11, so I'm guessing I'll have to expand the ABI versions and only include `cxx11`? I'm not too sure, but it makes sense in my head, at least.

> Can you please run again locally the builder for cgal with the latest master of BinaryBuilder.jl and see if you get a warning about the C++ string ABI? You can do it for any platform, don't need to run again for all of them

Will get on that as well!

**Comment by giordano** [comment]
> I'm scratching my head now, remembering a relatively important detail: since 5.0, CGAL's minimum supported version of the C++ standard is C++ 11, so I'm guessing I'll have to expand the ABI versions and only include cxx11? I'm not too sure, but it makes sense in my head, at least.

The C++ string ABI of GCC doesn't have to do with the C++ standard used, this is exactly the source of the incompatibility mentioned in [`RootFS.md`](https://github.com/JuliaPackaging/Yggdrasil/blob/5556c40c31653bd1ef6994a406a4bec7371a6c3e/RootFS.md#sources-of-incompatibility): when using GCC, you can compile a C++11 program with both C++03- and C++11-style ABIs.  For more information, see also the the [Dual ABI](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html) page in the GNU C++ Library manual.

**Comment by rgcv** [comment]
> The C++ string ABI of GCC doesn't have to do with the C++ standard used, this is exactly the source of the incompatibility mentioned in [`RootFS.md`](https://github.com/JuliaPackaging/Yggdrasil/blob/5556c40c31653bd1ef6994a406a4bec7371a6c3e/RootFS.md#sources-of-incompatibility): when using GCC, you can compile a C++11 program with both C++03- and C++11-style ABIs. For more information, see also the the [Dual ABI](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html) page in the GNU C++ Library manual.

Thanks you for that! I'm still relatively new to some of these intricacies, still can't quite wrap my mind around it. But it makes sense, yes, of course.

On another note, I indeed *do* get some warnings about using `std::string` values. I'll submit a PR to expand the C++ string ABI version in the CGAL builder.

**Comment by rgcv** [comment]
..I did not mean to close the PR, probably shouldn't just have force-pushed, deleting the commit.. My sincerest apologies for the mess.

**Comment by giordano** [comment]
No worries, but keep in mind that working in a branch that has the same name as the upstream branch is a very bad idea, also because this workflow doesn't let you submit multiple pull requests at the same time, which I think is what happened here.  I'm pretty sure that GitHub gives you also prominent warning if you try to do so.  You should always create a new branch for each PR

**Comment by rgcv** [comment]
> No worries, but keep in mind that working in a branch that has the same name as the upstream branch is a very bad idea, also because this workflow doesn't let you submit multiple pull requests at the same time, which I think is what happened here. I'm pretty sure that GitHub gives you also prominent warning if you try to do so. You should always create a new branch for each PR

Roger that. Been too accustomed work on a single branch recently. Lesson learned, that's for sure! Will be submitting a new PR properly now :wink:

**Pull request closed without merging**
