### PR TITLE
[Qt] Build tools

### PR DESCRIPTION
**Pull request by barche**
As requested in PR #2340 and https://github.com/barche/QML.jl/issues/104 and a few other places ;)

I have verified that this builds a host lrelease, so it seems the build system makes an automatic distinction between build-time and runtime executables, e.g for macOS:

```
% file bin/lrelease
bin/lrelease: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, stripped
% file bin/qmlscene 
bin/qmlscene: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|BINDS_TO_WEAK|PIE>
```

### CODE REVIEW

**Comment by giordano** [comment]
> I have verified that this builds a host lrelease, so it seems the build system makes an automatic distinction between build-time and runtime executables

This is great!

**Comment by barche** [comment]
I'm stuck on these errors, both seem to be related to not finding libc when building qdoc:

## Linux

```
g++ -Wl,-O1 -Wl,--enable-new-dtags -Wl,-rpath,/opt/x86_64-linux-musl/lib -Wl,-z,origin -Wl,-rpath,\$ORIGIN/../lib -o ../../bin/qdoc .obj/atom.o .obj/clangcodeparser.o .obj/codechunk.o .obj/codemarker.o .obj/codeparser.o .obj/config.o .obj/cppcodemarker.o .obj/cppcodeparser.o .obj/doc.o .obj/docbookgenerator.o .obj/editdistance.o .obj/generator.o .obj/helpprojectwriter.o .obj/htmlgenerator.o .obj/location.o .obj/main.o .obj/node.o .obj/openedlist.o .obj/parameters.o .obj/puredocparser.o .obj/qdocdatabase.o .obj/qdoctagfiles.o .obj/qdocindexfiles.o .obj/quoter.o .obj/sections.o .obj/separator.o .obj/text.o .obj/tokenizer.o .obj/tree.o .obj/xmlgenerator.o .obj/yyindent.o .obj/webxmlgenerator.o .obj/qdoccommandlineparser.o .obj/utilities.o .obj/jscodemarker.o .obj/qmlcodemarker.o .obj/qmlcodeparser.o .obj/qmlmarkupvisitor.o .obj/qmlvisitor.o   -L/workspace/destdir/lib -L/opt/x86_64-linux-musl/lib -lclang /workspace/srcdir/build/qtdeclarative/lib/libQt5QmlDevTools.a /workspace/srcdir/build/qtbase/lib/libQt5Core.so -lpthread
/opt/x86_64-linux-gnu/bin/../lib/gcc/x86_64-linux-gnu/7.1.0/../../../../x86_64-linux-gnu/bin/ld: warning: libc.musl-x86_64.so.1, needed by /opt/x86_64-linux-musl/lib/libclang.so, not found (try using -rpath or -rpath-link)
/opt/x86_64-linux-gnu/bin/../lib/gcc/x86_64-linux-gnu/7.1.0/../../../../x86_64-linux-gnu/bin/ld: ../../bin/qdoc: hidden symbol `stat' in /opt/x86_64-linux-gnu/bin/../x86_64-linux-gnu/sys-root/usr/lib64/libc_nonshared.a(stat.oS) is referenced by DSO
/opt/x86_64-linux-gnu/bin/../lib/gcc/x86_64-linux-gnu/7.1.0/../../../../x86_64-linux-gnu/bin/ld: final link failed: Bad value
```

## FreeBSD

```
x86_64-unknown-freebsd11.1-g++ -c -include .pch/Qt5XmlPatterns -pipe --sysroot=/opt/x86_64-unknown-freebsd11.1/bin/../x86_64-unknown-freebsd11.1/sys-root -O2 -std=c++1z -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -Wvla -Wdate-time -Wshift-overflow=2 -Wduplicated-cond -Wno-stringop-overflow -pthread -fPIC -DQT_NO_LINKED_LIST -DQT_NO_FOREACH -DQT_NO_USING_NAMESPACE -DQT_ENABLE_QEXPLICITLYSHAREDDATAPOINTER_STATICCAST -DYYLTYPE_IS_DECLARED=1 -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_BUILD_XMLPATTERNS_LIB -DQT_BUILDING_QT -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050000 -DQT_DEPRECATED_WARNINGS_SINCE=0x060000 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtxmlpatterns/src/xmlpatterns -I. -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtxmlpatterns/src/xmlpatterns/acceltree -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtxmlpatterns/src/xmlpatterns/data -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtxmlpatterns/src/xmlpatterns/api -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtxmlpatterns/src/xmlpatterns/environment -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtxmlpatterns/src/xmlpatterns/expr -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtxmlpatterns/src/xmlpatterns/functions -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtxmlpatterns/src/xmlpatterns/iterators -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtxmlpatterns/src/xmlpatterns/janitors -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtxmlpatterns/src/xmlpatterns/parser -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtxmlpatterns/src/xmlpatterns/schema -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtxmlpatterns/src/xmlpatterns/type -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtxmlpatterns/src/xmlpatterns/utils -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtxmlpatterns/include -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtxmlpatterns/include/QtXmlPatterns -I../../include -I../../include/QtXmlPatterns -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtxmlpatterns/include/QtXmlPatterns/5.15.2 -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtxmlpatterns/include/QtXmlPatterns/5.15.2/QtXmlPatterns -I../../include/QtXmlPatterns/5.15.2 -I../../include/QtXmlPatterns/5.15.2/QtXmlPatterns -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtbase/include/QtCore/5.15.2 -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtbase/include/QtCore/5.15.2/QtCore -I/workspace/srcdir/build/qtbase/include/QtCore/5.15.2 -I/workspace/srcdir/build/qtbase/include/QtCore/5.15.2/QtCore -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtbase/include -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtbase/include/QtNetwork -I/workspace/srcdir/build/qtbase/include -I/workspace/srcdir/build/qtbase/include/QtNetwork -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtbase/include/QtCore -I/workspace/srcdir/build/qtbase/include/QtCore -I.moc -I/usr/local/include -I/workspace/srcdir/qt-everywhere-src-5.15.2/qtbase/mkspecs/freebsd-g++ -o .obj/qcomparisonfactory.o /workspace/srcdir/qt-everywhere-src-5.15.2/qtxmlpatterns/src/xmlpatterns/data/qcomparisonfactory.cpp
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: warning: libc.so.7, needed by /workspace/destdir/lib/libz.so.1, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: warning: libthr.so.3, needed by /workspace/destdir/lib/libxml2.so.2, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: warning: libm.so.5, needed by /workspace/destdir/lib/libxml2.so.2, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /workspace/destdir/lib/libxml2.so.2: undefined reference to `__mb_sb_limit@FBSD_1.0'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /workspace/destdir/lib/libxml2.so.2: undefined reference to `ferror@FBSD_1.0'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /workspace/destdir/lib/libxml2.so.2: undefined reference to `fmod@FBSD_1.0'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: /workspace/destdir/lib/libxml2.so.2: undefined reference to `pthread_mutex_unlock@FBSD_1.0'
```

**Comment by ViralBShah** [comment]
@giordano This seems to be failing on the most reliable platforms. Any ideas? This could unblock gnuplot if we can figure it out.

**Comment by giordano** [comment]
There is some weird mess: on Linux with Glibc it's trying to load Musl's libc for clang while compiling with GCC (?!?!), on FreeBSD it's trying to build with the host GCC (?!?!??!?!)

**Comment by giordano** [comment]
Ok, the good news is that now trying to rebuild all platforms fail.  Consistency is always important

**Comment by giordano** [comment]
On a second thought, I don't think adding dev tools to a package which is mainly used at runtime is a good idea.  Maybe we can build only these tools in a separate package (and maybe that'd also be easier to debug)

**Comment by barche** [comment]
I think the problem comes from the fact that qdoc needs the host llvm. It uses `llvm-config` to find it, and on Linux this finds the installation under /opt/x86_64-linux-musl. This seems correct, but linking fails with:

`/opt/x86_64-linux-gnu/bin/../lib/gcc/x86_64-linux-gnu/7.1.0/../../../../x86_64-linux-gnu/bin/ld: warning: libc.musl-x86_64.so.1, needed by /opt/x86_64-linux-musl/lib/libclang.so, not found (try using -rpath or -rpath-link)`

So possibly this means that the link flags returned by `llvm-config` are incomplete?

Regarding splitting off of the tools: this would be good for more than just tools. Most Linux distributions split up the Qt package, so I could look at how they do it. I propose to postpone this to Qt 6, however. (QML.jl almost works with this locally).

**Comment by giordano** [comment]
I think `llvm-config` gives you the wrong information.  @vchuravy has a gripe about that.  I should get back to https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/43 at some point and try to do something more backward-compatible

**Comment by vchuravy** [comment]
Yeah `llvm-config` is actively lying to you.

**Comment by barche** [comment]
The green check is a fake:
https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=8535&view=logs&j=f64450a0-9594-5c72-e92a-c283b9cc7912&t=b82015f4-0b05-52a9-52bf-db7c0feb2148&l=376387

On the other hand, does anyone need QDoc?

**Comment by giordano** [comment]
Not that I'm aware of.  But again, I'm a bit hesitant to add this stuff to `Qt_jll`: I'd like to avoid further polluting users' home directories

**Comment by barche** [comment]
The tools are actually just a small addition compared to what's already there. I think it's cleanest to do the splitting together with the upgrade to Qt 6.

**Comment by barche** [comment]
OK, proposal on how to proceed with this: build tools without qdoc and merge this for now, and split up the Qt package for Qt6. That way PR #2339  might be able to go through?

**Comment by giordano** [comment]
Let's try that, this adds ~10 MB to a tarball of already ~50 MB, that's almost a 20% increase

**Comment by barche** [comment]
> Let's try that, this adds ~10 MB to a tarball of already ~50 MB, that's almost a 20% increase

I have to admit that is about 10 times what I had estimated. I took a look at the [arch linux approach](https://github.com/archlinux/svntogit-packages/blob/packages/qt5-tools/trunk/PKGBUILD) to make a separate package, I'll try that, seems easy enough.

Once [the Qt download site is up again](https://forum.qt.io/topic/122837/download-qt-io-is-down), that is ;)

**Comment by barche** [comment]
Locally this almost works for mingw, but fails at the finish line with:

```
[ Info: ["lrelease"] does not exist, reporting unsatisfied
┌ Error: Built QtTools but lrelease still unsatisfied:
└ @ BinaryBuilder ~/.julia/packages/BinaryBuilder/7H3La/src/AutoBuild.jl:763
ERROR: LoadError: Cannot continue with unsatisfied build products!
```

However, the executable is there:
```
% file build/x86_64-w64-mingw32-cxx11/BurBKqtW/destdir/bin/lrelease
build/x86_64-w64-mingw32-cxx11/BurBKqtW/destdir/bin/lrelease: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, with debug_info, not stripped
```

**Comment by giordano** [comment]
If it's an executable for the host, it can't be an ExecutableProduct, which is only for the target. You can however list it as a FileProduct

**Comment by barche** [comment]
In case anyone is holding their breath for this: I'm quite stuck, building tools separately uses a tool `uic` from the main Qt package, but this is linked against the GNU libc, so it won't run. I think this is because the linux Qt is not cross compiled as far as qmake is concerned. Possibly the solution would be to build Qt with something like `-platform linux-g++-musl -xplatform linux-g++-glibc`. This requires that we create the makespecs for ` linux-g++-musl` and  `linux-g++-glibc` ourselves (probably a thin wrapper around the existing `linux-g++`. Questions:

* Is it still worth doing this for Qt5
* Are we going to handle co-existing Qt5 and Qt6 in the same environment, and how would that work?

**Comment by giordano** [comment]
Since we now have real BuildDependency for the host (https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/995), honestly I think these tools should only be built for the host in a separate package.

> Are we going to handle co-existing Qt5 and Qt6 in the same environment, and how would that work?

Can they coexist at runtime?  The easiest case is if they cannot coexist, so we can simply move to Qt 6 in this recipe

**Comment by barche** [comment]
> Since we now have real BuildDependency for the host ([JuliaPackaging/BinaryBuilder.jl#995](https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/995)), honestly I think these tools should only be built for the host in a separate package.

Yes, I agree, what I mean is: is it worth building the tools for Qt5 still, or shall we do this for Qt6 only?

> > Are we going to handle co-existing Qt5 and Qt6 in the same environment, and how would that work?
> 
> Can they coexist at runtime? The easiest case is if they cannot coexist, so we can simply move to Qt 6 in this recipe

Not "in the same executable or library": https://doc-snapshots.qt.io/qt6-dev/cmake-qt5-and-qt6-compatibility.html#mixing-qt-5-and-qt-6

I have the following possible problem in mind: QML.jl requiring Qt6 and GR.jl requiring Qt5, then users couldn't have both (the newest) QML.jl and GR.jl at the same time, even when using only the non-Qt parts of GR (e.g. plot to png).

**Comment by giordano** [comment]
>  is it worth building the tools for Qt5 still, or shall we do this for Qt6 only?

I don't have particular rush, but these tools may be useful for Gnuplot.  No idea if/when Gnuplot will be able to work with Qt6.

> I have the following possible problem in mind: QML.jl requiring Qt6 and GR.jl requiring Qt5, then users couldn't have both (the newest) QML.jl and GR.jl at the same time, even when using only the non-Qt parts of GR (e.g. plot to png).

That's an interesting point, but also hard to deal with at the moment: currently we automatically load all libraries anyway, so there isn't really such a thing like GR without Qt.

**Comment by VarLad** [comment]
Weird Suggestion - Rename Qt_jll to Qt5_jll
I'm a Fedora user, and here Qt means qt 4.8.x
qt5 refers to qt 5.15.x
and qt6 refers to qt 6.x

I don't think someone will have to maintain Qt5_jll anyway, as its the last version of qt5 and its support will end in 2 years. 

That way devs can choose their respective versions

**Pull request closed without merging**
