### PR TITLE
update TDLib

### PR DESCRIPTION
**Pull request by aplavin**

### CODE REVIEW

**Comment by giordano** [comment]
@aplavin can we require Julia v1.6?  This isn't super-important here since at the moment we don't build for formerly-experimental platforms, but it'd still be good to update the compat

**Comment by aplavin** [comment]
@giordano I don't see any compat specification in the build file, where to put the julia version constraint?

**Comment by giordano** [comment]
Add the `julia_compat="1.6"` keyword argument to the `build_tarballs()` function on the last line

**Comment by aplavin** [comment]
I see, that must be a new feature since I last wrote a build_tarballs script :)

**Pull request merged**
