### PR TITLE
libjulia: add 1.10, update 1.9, add debug shared libs

### PR DESCRIPTION
**Pull request by fingolfin**
Also update Julia 1.9-DEV to latest git version, just in case.

First step towards #5787. It does *not* add `debug` to the platform as Julia happily allows `libjulia` and `libjulia-debug` to co-exist...

... though perhaps we *should* augment the platform like that, and only build either `libjulia` or `libjulia-debug`? One argument for doing that is that it should make it impossible to accidentally link against `libjulia` when one should be linking against `libjulia-debug`, and vice-versa.

As an additional data point, I looked into adding a `platforms/julia-debug.jl`, and realized that all packages that would include it already including `L/libjulia/common.jl`. So now I am wondering if either the `augment_platform` helpers should just go in there -- or dually, that it should all go into a `platforms/julia.jl` file (which then would also be included by `L/libjulia/common.jl`).

Thoughts, opinions, preferences?

### CODE REVIEW

**Comment by giordano** [comment]
As a datapoint, doubling the number of platforms would likely go over the hard limit of [256 jobs for a stage](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml) Azure Pipelines, so avoiding that would have some benefits in terms of infrastructure.

**Comment by fingolfin** [comment]
@giordano that's good.

I see that the `release-1.9` branch was opened, so we *also* need to add 1.10-DEV to libjulia... and then rebuild all JLLs using libjulia for that. perhaps I can combine the work.

**Comment by fingolfin** [comment]
I've now added 1.10-DEV and updated 1.9-DEV to match the current `release-1.9` branch. And of course it adds `libjulia-debug` -- I figure this won't hurt even if perhaps we don't need it.

So assuming the tests pass, it should be OK to merge (of course resolving those ARM 32bit issues would be great, but that can't be helped for now :-/)

**Comment by fingolfin** [comment]
Hmm, `LoadError: Unsupported Julia version`

**Comment by giordano** [comment]
https://github.com/JuliaPackaging/Yggdrasil/blob/a0b7b6b816aa029cac6d074d832963a684057676/L/libjulia/common.jl#L360

**Comment by fingolfin** [comment]
Argh :facepalm: Yeah, it helps if one adds all changes before committing&pushing *sigh*

**Comment by fingolfin** [comment]
Huh, I don't get why `mingw` fails for 1.10 but not for 1.9... the two given commits only differ in three files: `VERSION`, `VERSION`, `NEWS.md`.

**Comment by fingolfin** [comment]
Thanks @benlorenz . I didn't realize we had a patch there.

**Comment by fingolfin** [comment]
OK, now it passes, phew :-)

**Comment by fingolfin** [comment]
This already has 118 platforms; once/if ARM32 is fixed for Julia 1.9 and 1.10, that'll be another 8, for a total of 126... So yeah, that is already quite tight! If a JLL needs libjulia and e.g. has to expand fortran platforms, there's already a  problem now, I guess?

I wonder if we could not do away with the `expand_cxxstring_abis` after all. Well, we wisely documented why it is used for libjulia_jll:
```
    # While the "official" Julia kernel ABI itself does not involve any C++
    # symbols on the linker level, `libjulia` still exports "unofficial" symbols
    # dependent on the C++ strings ABI (coming from LLVM related code). This
    # doesn't matter if the client code is pure C, but as soon as there are
    # other (actual) C++ dependencies, we must make sure to use the matching C++
    # strings ABI. Hence we must use `expand_cxxstring_abis` below.
    platforms = expand_cxxstring_abis(platforms)

```
But I had a look at `nm libjulia.so` and `nm libjulia.dylib` for various Linux and macOS versions of `libjulia`, and in none was there a single C++ symbol visible. Did I look in the wrong place? (of course on macOS, we don't expand on the C++ ABI anyway, but that's orthogonal to the point)

**Comment by fingolfin** [comment]
@benlorenz thanks, that makes sense. I've now pushed a commit which disables the C++ ABI expansion for Julia >= 1.6. Let's see if @giordano (or @staticfloat ?) have concerns.

**Comment by staticfloat** [comment]
That's actually a great find, thank you @benlorenz!  Yes, since we've separated out `libjulia` from `libjulia-internal`, and `libjulia-internal` is the only one that does C++ stuff, that actually does give us greater freedom to link against the C-only `libjulia` without needing to worry about cxxstring ABI expansion.

**Comment by giordano** [comment]
I usually look at the auditor output: if it says "locks us to..." for one of the libraries we care about then we need to expand the ABIs, otherwise we can't. This would be possible to automate if auditor was more structured and we could collect the status of each pass individually (at the moment we only have a global true/false). If auditor is happy with not splitting, then I'm happy as well.

**Comment by fingolfin** [comment]
There are 490 warnings on https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=23639&view=results , including:
- complaints about the C++ API/ABI for `libjulia-internal` -- but we know that, and are OK with it, I think?
  - would it make sense / be helpful to remove `libjulia-internal` from the JLL, thus removing the warning and also making it impossible to "accidentally" link to it?
  - this would also silence further warnings about use of cpuid in there
- `Warning: Dependency LibGit2_jll does not have an (Stdlib)Artifacts.toml` (for older version used in Julia 1.6)
- `Warning: Dependency LibGit2_jll does not have an (Stdlib)Artifacts.toml` (for older version used in Julia 1.6)
- many variants of `Skipping abspath scanning of /agent/_work/1/s/L/libjulia/build/powerpc64le-linux-gnu-julia_version+1.7.0/bynylOc5/powerpc64le-linux-gnu-libgfortran4-cxx11-julia_version+1.7.0/destdir/tools/wasm-ld, as we can't open it` -- huh?

(Boy, it is super annoying that I have to click dozens of times to expand the list of warning, and then I can't even right-click on entries to open them in a new tab, because those aren't real hyperlinks; and opening a link and then going back resets the list of warnings to the initial state with just 10 shown. Grrr)

**Comment by fingolfin** [comment]
I've now added another commit to remove `libjulia-internal`.

**Comment by fingolfin** [comment]
Drawback of removing `libjulia-internal` is that the auditor then complains that it can't find `libjulia-internal`... so for now I added it back.

From my POV this is ready for merging.

**Pull request merged**
