### PR TITLE
[TempestRemap] Build more platforms

### PR DESCRIPTION
**Pull request by simonbyrne**
NetCDF now works on more platforms, so we can try all of them

### CODE REVIEW

**Comment by fingolfin** [comment]
Fails on Windows. Seems some code assumes that `sizeof(pointer) == sizeof(long)` which is true on Linux and macOS and Win32 but not Win64 (where Microsoft decided to use LLP64 instead of LP64 used by "everyone else", at least on the desktop).

This can be fixed but is non-trivial.

**Comment by fingolfin** [comment]
This also seems to be a duplicate of #5411 ?

**Comment by simonbyrne** [comment]
from https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=24425&view=logs&j=d88e6f07-f042-546b-a82c-9a2b987ecca6&t=32748299-5526-5468-0f25-28de28db4185&l=786 Windows failures are now:
```
libtool:   error: can't build x86_64-w64-mingw32 shared library unless -no-undefined is specified
```

**Comment by simonbyrne** [comment]
Okay, so current [failures on Windows](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=24426&view=logs&j=d88e6f07-f042-546b-a82c-9a2b987ecca6&t=32748299-5526-5468-0f25-28de28db4185):
```
[19:35:48] src/.libs/FiniteVolumeTools.o: In function `TriangleLineIntersection(Node&, std::vector<Node, std::allocator<Node> >&, DataArray1D<double>&, double&)':
[19:35:48] /workspace/srcdir/tempestremap-2.1.6/build/../src/FiniteVolumeTools.cpp:817: undefined reference to `dgetrf_'
[19:35:48] /workspace/srcdir/tempestremap-2.1.6/build/../src/FiniteVolumeTools.cpp:821: undefined reference to `dgetri_'
...
```

and on [Mac Aarch64](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=24426&view=logs&j=c1c90f1d-4335-55cc-47e9-7f0b47e2ad94&t=49c9434a-5aae-5284-a721-8d9cc541f775&l=846)
```
[19:35:44] Undefined symbols for architecture arm64:
[19:35:44]   "_dgemv_", referenced from:
[19:35:44]       __Z29ForceConsistencyConservation3RK11DataArray1DIdES2_R11DataArray2DIdEbb in LinearRemapSE0.o
[19:35:44]       __Z36ForceIntArrayConsistencyConservationRK11DataArray1DIdES2_R11DataArray2DIdEb in LinearRemapFV.o
[19:35:44]   "_dgeqrf_", referenced from:
[19:35:44]       __Z27InvertFitArray_LeastSquaresRK11DataArray1DIdER11DataArray2DIdERS0_S5_ in FiniteVolumeTools.o
...
```

These are both BLAS library functions, but may have something to do with how the signatures are defined, e.g.
https://github.com/ClimateGlobalChange/tempestremap/blob/bcdc4f1d865b43b7b96c77dde2f9adff5f6fda13/src/LinearRemapSE0.cpp#L50-L62

**Comment by simonbyrne** [comment]
Comparing the Darwin x86_64 vs Aarch64 commands:
```diff
-[19:35:49] libtool: link: c++ -dynamiclib -Wl,-undefined -Wl,dynamic_lookup -o .libs/libTempestRemap.0.dylib  src/.libs/Announce.o src/.libs/PolynomialInterp.o src/.libs/GridElements.o src/.libs/MeshUtilities.o src/.libs/MeshUtilitiesFuzzy.o src/.libs/MeshUtilitiesExact.o src/.libs/GenerateCSMesh.o src/.libs/GenerateTransectMesh.o src/.libs/GenerateStereographicMesh.o src/.libs/GenerateICOMesh.o src/.libs/GenerateRLLMesh.o src/.libs/GenerateRectilinearMeshFromFile.o src/.libs/GenerateUTMMesh.o src/.libs/GenerateGLLMetaData.o src/.libs/GenerateLambertConfConicMesh.o src/.libs/GenerateOverlapMesh.o src/.libs/GenerateOverlapMesh_v1.o src/.libs/GaussQuadrature.o src/.libs/GaussLobattoQuadrature.o src/.libs/LegendrePolynomial.o src/.libs/FiniteElementTools.o src/.libs/FiniteVolumeTools.o src/.libs/NetCDFUtilities.o src/.libs/RestructureData.o src/.libs/ncvalues.o src/.libs/netcdf.o src/.libs/OverlapMesh.o src/.libs/OfflineMap.o src/.libs/LinearRemapSE0.o src/.libs/LinearRemapFV.o src/.libs/TriangularQuadrature.o src/.libs/ApplyOfflineMap.o src/.libs/GenerateOfflineMap.o src/.libs/GenerateConnectivityData.o src/.libs/kdtree.o src/.libs/triangle.o   -L/workspace/destdir/lib -ldl -lm  -g -O2   -install_name  /workspace/destdir/lib/libTempestRemap.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module
+[19:35:44] libtool: link: c++ -dynamiclib  -o .libs/libTempestRemap.0.dylib  src/.libs/Announce.o src/.libs/PolynomialInterp.o src/.libs/GridElements.o src/.libs/MeshUtilities.o src/.libs/MeshUtilitiesFuzzy.o src/.libs/MeshUtilitiesExact.o src/.libs/GenerateCSMesh.o src/.libs/GenerateTransectMesh.o src/.libs/GenerateStereographicMesh.o src/.libs/GenerateICOMesh.o src/.libs/GenerateRLLMesh.o src/.libs/GenerateRectilinearMeshFromFile.o src/.libs/GenerateUTMMesh.o src/.libs/GenerateGLLMetaData.o src/.libs/GenerateLambertConfConicMesh.o src/.libs/GenerateOverlapMesh.o src/.libs/GenerateOverlapMesh_v1.o src/.libs/GaussQuadrature.o src/.libs/GaussLobattoQuadrature.o src/.libs/LegendrePolynomial.o src/.libs/FiniteElementTools.o src/.libs/FiniteVolumeTools.o src/.libs/NetCDFUtilities.o src/.libs/RestructureData.o src/.libs/ncvalues.o src/.libs/netcdf.o src/.libs/OverlapMesh.o src/.libs/OfflineMap.o src/.libs/LinearRemapSE0.o src/.libs/LinearRemapFV.o src/.libs/TriangularQuadrature.o src/.libs/ApplyOfflineMap.o src/.libs/GenerateOfflineMap.o src/.libs/GenerateConnectivityData.o src/.libs/kdtree.o src/.libs/triangle.o   -L/workspace/destdir/lib -ldl -lm  -g -O2   -install_name  /workspace/destdir/lib/libTempestRemap.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module
```

**Comment by simonbyrne** [comment]
@giordano any ideas or suggestions?

**Comment by giordano** [comment]
I had a dejavu: https://github.com/JuliaPackaging/Yggdrasil/pull/5019#issuecomment-1152967156.  Might be something similar, you have to check how those flags are set.

**Comment by simonbyrne** [comment]
Woohoo, that fixes the Mac Aarch64.

Any ideas/suggestions on the Windows ones?

**Comment by giordano** [comment]
```
[19:35:48] libtool: link: c++ -shared -nostdlib /opt/x86_64-w64-mingw32/bin/../x86_64-w64-mingw32/sys-root/lib/../lib/dllcrt2.o /opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/crtbegin.o  src/.libs/Announce.o src/.libs/PolynomialInterp.o src/.libs/GridElements.o src/.libs/MeshUtilities.o src/.libs/MeshUtilitiesFuzzy.o src/.libs/MeshUtilitiesExact.o src/.libs/GenerateCSMesh.o src/.libs/GenerateTransectMesh.o src/.libs/GenerateStereographicMesh.o src/.libs/GenerateICOMesh.o src/.libs/GenerateRLLMesh.o src/.libs/GenerateRectilinearMeshFromFile.o src/.libs/GenerateUTMMesh.o src/.libs/GenerateGLLMetaData.o src/.libs/GenerateLambertConfConicMesh.o src/.libs/GenerateOverlapMesh.o src/.libs/GenerateOverlapMesh_v1.o src/.libs/GaussQuadrature.o src/.libs/GaussLobattoQuadrature.o src/.libs/LegendrePolynomial.o src/.libs/FiniteElementTools.o src/.libs/FiniteVolumeTools.o src/.libs/NetCDFUtilities.o src/.libs/RestructureData.o src/.libs/ncvalues.o src/.libs/netcdf.o src/.libs/OverlapMesh.o src/.libs/OfflineMap.o src/.libs/LinearRemapSE0.o src/.libs/LinearRemapFV.o src/.libs/TriangularQuadrature.o src/.libs/ApplyOfflineMap.o src/.libs/GenerateOfflineMap.o src/.libs/GenerateConnectivityData.o src/.libs/kdtree.o src/.libs/triangle.o   -L/workspace/destdir/bin -L/workspace/destdir/lib -L/opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0 -L/opt/x86_64-w64-mingw32/bin/../lib/gcc -L/opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib/../lib -L/opt/x86_64-w64-mingw32/bin/../x86_64-w64-mingw32/sys-root/lib/../lib -L/opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/../../../../x86_64-w64-mingw32/lib -L/opt/x86_64-w64-mingw32/bin/../x86_64-w64-mingw32/sys-root/lib -lstdc++ -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt /opt/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/5.2.0/crtend.o  -g -O2   -o .libs/libTempestRemap-0.dll -Wl,--enable-auto-image-base -Xlinker --out-implib -Xlinker .libs/libTempestRemap.dll.a
[19:35:50] src/.libs/FiniteVolumeTools.o: In function `TriangleLineIntersection(Node&, std::vector<Node, std::allocator<Node> >&, DataArray1D<double>&, double&)':
[19:35:50] /workspace/srcdir/tempestremap-2.1.6/build/../src/FiniteVolumeTools.cpp:817: undefined reference to `dgetrf_'
[19:35:50] /workspace/srcdir/tempestremap-2.1.6/build/../src/FiniteVolumeTools.cpp:821: undefined reference to `dgetri_'
```
It's not linking to netcdf nor openblas, which explains the linking error, but I don't know why the linker invocation is wrong on Windows.

**Comment by simonbyrne** [comment]
What's odd is that it is failing at the first linker invocation (https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=24426&view=logs&j=d610057a-c804-5b96-6674-07f8a2b105bd&t=110d7483-3ec8-55a6-1b58-2ad695d2b22e&l=805)
```
[19:35:36] /bin/sh ./libtool  --tag=CXX   --mode=link c++ -std=gnu++11  -g -O2 -L/workspace/destdir/bin -no-undefined -L/workspace/destdir/lib -L/workspace/destdir/bin -no-undefined -o libTempestRemap.la -rpath /workspace/destdir/lib src/Announce.lo src/PolynomialInterp.lo src/GridElements.lo src/MeshUtilities.lo src/MeshUtilitiesFuzzy.lo src/MeshUtilitiesExact.lo src/GenerateCSMesh.lo src/GenerateTransectMesh.lo src/GenerateStereographicMesh.lo src/GenerateICOMesh.lo src/GenerateRLLMesh.lo src/GenerateRectilinearMeshFromFile.lo src/GenerateUTMMesh.lo src/GenerateGLLMetaData.lo src/GenerateLambertConfConicMesh.lo src/GenerateOverlapMesh.lo src/GenerateOverlapMesh_v1.lo src/GaussQuadrature.lo src/GaussLobattoQuadrature.lo src/LegendrePolynomial.lo src/FiniteElementTools.lo src/FiniteVolumeTools.lo src/NetCDFUtilities.lo src/RestructureData.lo src/ncvalues.lo src/netcdf.lo src/OverlapMesh.lo src/OfflineMap.lo src/LinearRemapSE0.lo src/LinearRemapFV.lo src/TriangularQuadrature.lo src/ApplyOfflineMap.lo src/GenerateOfflineMap.lo src/GenerateConnectivityData.lo src/kdtree.lo src/triangle.lo  -lm
[19:35:38] libtool: link: c++ -shared -nostdlib /opt/i686-w64-mingw32/bin/../i686-w64-mingw32/sys-root/lib/../lib/dllcrt2.o /opt/i686-w64-mingw32/bin/../lib/gcc/i686-w64-mingw32/4.8.5/crtbegin.o  src/.libs/Announce.o src/.libs/PolynomialInterp.o src/.libs/GridElements.o src/.libs/MeshUtilities.o src/.libs/MeshUtilitiesFuzzy.o src/.libs/MeshUtilitiesExact.o src/.libs/GenerateCSMesh.o src/.libs/GenerateTransectMesh.o src/.libs/GenerateStereographicMesh.o src/.libs/GenerateICOMesh.o src/.libs/GenerateRLLMesh.o src/.libs/GenerateRectilinearMeshFromFile.o src/.libs/GenerateUTMMesh.o src/.libs/GenerateGLLMetaData.o src/.libs/GenerateLambertConfConicMesh.o src/.libs/GenerateOverlapMesh.o src/.libs/GenerateOverlapMesh_v1.o src/.libs/GaussQuadrature.o src/.libs/GaussLobattoQuadrature.o src/.libs/LegendrePolynomial.o src/.libs/FiniteElementTools.o src/.libs/FiniteVolumeTools.o src/.libs/NetCDFUtilities.o src/.libs/RestructureData.o src/.libs/ncvalues.o src/.libs/netcdf.o src/.libs/OverlapMesh.o src/.libs/OfflineMap.o src/.libs/LinearRemapSE0.o src/.libs/LinearRemapFV.o src/.libs/TriangularQuadrature.o src/.libs/ApplyOfflineMap.o src/.libs/GenerateOfflineMap.o src/.libs/GenerateConnectivityData.o src/.libs/kdtree.o src/.libs/triangle.o   -L/workspace/destdir/bin -L/workspace/destdir/lib -L/opt/i686-w64-mingw32/bin/../lib/gcc/i686-w64-mingw32/4.8.5 -L/opt/i686-w64-mingw32/bin/../lib/gcc -L/opt/i686-w64-mingw32/bin/../lib/gcc/i686-w64-mingw32/4.8.5/../../../../i686-w64-mingw32/lib/../lib -L/opt/i686-w64-mingw32/bin/../i686-w64-mingw32/sys-root/lib/../lib -L/opt/i686-w64-mingw32/bin/../lib/gcc/i686-w64-mingw32/4.8.5/../../../../i686-w64-mingw32/lib -L/opt/i686-w64-mingw32/bin/../i686-w64-mingw32/sys-root/lib -lstdc++ -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc_s -lgcc -lmoldname -lmingwex -lmsvcrt /opt/i686-w64-mingw32/bin/../lib/gcc/i686-w64-mingw32/4.8.5/crtend.o  -g -O2   -o .libs/libTempestRemap-0.dll -Wl,--enable-auto-image-base -Xlinker --out-implib -Xlinker .libs/libTempestRemap.dll.a
[19:35:39] src/.libs/FiniteVolumeTools.o: In function `Z24TriangleLineIntersectionR4NodeRSt6vectorIS_SaIS_EER11DataArray1DIdERd':
[19:35:39] /workspace/srcdir/tempestremap-2.1.6/build/../src/FiniteVolumeTools.cpp:817: undefined reference to `dgetrf_'
[19:35:39] /workspace/srcdir/tempestremap-2.1.6/build/../src/FiniteVolumeTools.cpp:821: undefined reference to `dgetri_'
```

In Linux, it doesn't link in those libraries until later:
https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=24426&view=logs&j=f5643889-fc91-5126-16ad-2c9014e7d8fd&t=100da867-b2dc-5796-a371-2c18ec6f0431&l=977

**Comment by simonbyrne** [comment]
Ok, I think this is ready.

**Comment by giordano** [comment]
Awesome, thanks!

**Pull request merged**
