### PR TITLE
Add LLVM libunwind v12.0.1

### PR DESCRIPTION
**Pull request by ararslan**

### CODE REVIEW

**Comment by ararslan** [comment]
```
[03:26:00] CMake Error at CMakeLists.txt:2 (message):
[03:26:00]   libunwind requires being built in a monorepo layout with libcxx available
```
UGH. This apparently wasn't the case for libunwind 11 based on #2360, #2557, and #2570. I'm guessing what will need to happen is to use `LLVM_full` as a `BuildDependency`, build libcxx first in the script, then build libunwind. But if libunwind 12 actually needs to link to libc++, I would imagine we'd need a separate libcxx build recipe that would then be a `Dependency` for libunwind.

**Comment by ararslan** [comment]
Wait what, https://github.com/llvm/llvm-project/commit/8c03fdf34a659925a3f09c8f54016e47ea1c7519 I think it only needs libcxx and the monorepo so it can reuse one CMake file?!

**Comment by ararslan** [comment]
Things seem to be working now. I worked around the build system change by straight up reverting the commit that touched it. A better long-term solution would of course be to properly adjust how we build it here, buuuuuuuuuut...

**Review by giordano — APPROVED** [review]
Not super happy about reverting a commit, but might be good as a temporary solution

**Comment by ararslan** [comment]
yolo

**Pull request merged**
