### PR TITLE
fts: build for experimental platforms.

### PR DESCRIPTION
**Pull request by maleadt**
Needed for https://github.com/JuliaPackaging/Yggdrasil/pull/5841

### CODE REVIEW

**Comment by giordano** [comment]
This should have change the version number, I'm going to block it

**Comment by maleadt** [comment]
When only adding a platform? That's new to me. I'll fix it up in a new PR.

**Comment by maleadt** [comment]
What do I bump it to, given that we're following upstream's version here?

**Comment by giordano** [comment]
> EDIT: ah, it's because of the change in julia compat, I presume.

You, without changing the version number you'd break the package in older versions of Julia, without Pkg dealing with it nicely

> What do I bump it to, given that we're following upstream's version here?

Eh, if there are no new upstream versions I usually bump the patch number

**Pull request merged**
