### PR TITLE
Build a LLVM9 bootstrapping shard

### PR DESCRIPTION
**Pull request by vchuravy**
TODO:
Do we need
- [ ] https://git.alpinelinux.org/aports/plain/main/clang/10-add-musl-triples.patch
- 0003-llvm8_clang_musl_gcc_detector.patch
- [x] Turned of Sanitizer support for musl

### CODE REVIEW

**Comment by giordano** [comment]
> When I run it locally it immediately asked after my GITHUB_TOKEN (while insulting me :P)

It recognised you're an imposter!

**Comment by vchuravy** [comment]
@staticfloat I was trying to test this locally but I have no clue how to do so even after reading https://github.com/JuliaPackaging/Yggdrasil/blob/master/RootFS.md :)

**Comment by staticfloat** [comment]
Just set a bogus `GITHUB_TOKEN`, comment out [these two lines](https://github.com/JuliaPackaging/Yggdrasil/blob/master/0_RootFS/common.jl#L79-L80) and run it again.

**Comment by vchuravy** [comment]
@staticfloat this now passes locally, albeit we probably still need the clang patch?

Any good way of testing whether the build is solid?

**Comment by staticfloat** [comment]
I needed to rebase, but then I built, then locally did the following (After adding the version number to the list of version numbers in `choose_shards()`:

```
julia> using BinaryBuilder
       BinaryBuilder.runshell(Linux(:x86_64); preferred_llvm_version=v"9", verbose=true)
...
sandbox:/usr/share/testsuite # make LANGUAGES="c cxx" runall
x86_64-linux-gnu-cc -o /tmp/testsuite/x86_64-linux-gnu/c/hello_world/hello_world -g -O2 hello_world.c
x86_64-linux-gnu-c++ -o /tmp/testsuite/x86_64-linux-gnu/cxx/hello_world/hello_world -g -O2 hello_world.cc
x86_64-linux-gnu-cc -shared -o /tmp/testsuite/x86_64-linux-gnu/c/dyn_link/libfoo/libfoo.so -fPIC -g -O2 -lm libfoo/libfoo.c
x86_64-linux-gnu-cc -o /tmp/testsuite/x86_64-linux-gnu/c/dyn_link/dyn_link -I/usr/share/testsuite/c/dyn_link/libfoo -fPIC -g -O2 -Wl,-z,origin -Wl,-rpath,$ORIGIN/libfoo -L/tmp/testsuite/x86_64-linux-gnu/c/dyn_link/libfoo -lfoo dyn_link.c
x86_64-linux-gnu-c++ -shared -o /tmp/testsuite/x86_64-linux-gnu/cxx/dyn_link/librepeater/librepeater.so -fPIC -g -O2 -lm librepeater/librepeater.cc
x86_64-linux-gnu-c++ -o /tmp/testsuite/x86_64-linux-gnu/cxx/dyn_link/dyn_link -I/usr/share/testsuite/cxx/dyn_link/librepeater -fPIC -g -O2 -Wl,-z,origin -Wl,-rpath,$ORIGIN/librepeater -L/tmp/testsuite/x86_64-linux-gnu/cxx/dyn_link/librepeater -lrepeater dyn_link.cc
/tmp/testsuite/x86_64-linux-gnu/c/hello_world/hello_world 
Hello, World!
/tmp/testsuite/x86_64-linux-gnu/cxx/hello_world/hello_world 
Hello, World!
/tmp/testsuite/x86_64-linux-gnu/c/dyn_link/dyn_link 
foo(2.0) == 2.0
/tmp/testsuite/x86_64-linux-gnu/cxx/dyn_link/dyn_link
wakawakawakawaka
```
Looks good to me!

**Comment by staticfloat** [comment]
https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/580

**Comment by vchuravy** [comment]
Thanks Elliot! Did you take a look if we need the clang patches that Alpine Linux is carying?

**Comment by staticfloat** [comment]
As far as I can tell, no, we don't; those sanity tests look pretty good.

**Comment by staticfloat** [comment]
wait, no, I'm a dummy.  Those tests were with `gcc`.

**Comment by staticfloat** [comment]
Yes, we do need that patch.  Will fix.

**Pull request merged**
