### PR TITLE
[Julia] Update Julia_jll to 1.4.2

### PR DESCRIPTION
**Pull request by ViralBShah**
@staticfloat Put this PR together to see which ArchiveSources are missing.

### CODE REVIEW

**Comment by ViralBShah** [comment]
I guess I need the new hashes.

**Comment by giordano** [comment]
The one for `aarch64` is `f124d1b9fa68c3049d4ffe2349454f8ba1753d17d6578bc6e7cb916aed7cff4a`

**Comment by ViralBShah** [comment]
The armv7 and windows (both) download links are failing.

**Comment by giordano** [comment]
armv7l wasn't build at all.  @ararslan any plan to build it later?

**Comment by ViralBShah** [comment]
It usually shows up a few days later.

**Comment by ViralBShah** [comment]
@staticfloat Any reason why freebsd is downloading from `julialang.s3` instead of `julialang2.s3`?

**Comment by ViralBShah** [comment]
Note: Still need the win32, win64 before merging. Eventually, need armv7 binaries as well.

**Comment by ViralBShah** [comment]
Should we do anything about this?

```
 Warning: To ensure that the correct version of libgfortran is found at runtime, add the following entry to the list of dependencies of this builder
│ 
│     Dependency(PackageSpec(name="CompilerSupportLibraries_jll", uuid="e66e0078-7015-5450-92f7-15fbd957f2ae"))
└ @ BinaryBuilder /depot/packages/BinaryBuilder/SPVAM/src/auditor/compiler_abi.jl:4
##[warning]To ensure that the correct version of libgfortran is found at runtime, add the following entry to the list of dependencies of this builder

    Dependency(PackageSpec(name="CompilerSupportLibraries_jll", uuid="e66e0078-7015-5450-92f7-15fbd957f2ae"))
```

**Comment by ararslan** [comment]
> any plan to build it later?

Not on my end. I've tried for the past several releases to build official ARMv7 binaries but to no avail. Lately, any time we've had them is because @staticfloat worked some kind of dark magic.

**Comment by fingolfin** [comment]
@ViralBShah wrote:
> Note: Still need the win32, win64 before merging. Eventually, need armv7 binaries as well.

... and yet this was merged with win32 and win64 disabled -- was that done intentionally?

**Comment by ViralBShah** [comment]
Ouch I forgot about it. Got carried away with all the greens.

**Comment by ViralBShah** [comment]
@staticfloat Can you re-upload the windows binaries? They are broken...

**Pull request merged**
