### PR TITLE
Bump JLL wrapper: PCRE2_jll

### PR DESCRIPTION
**Pull request by musm**

### CODE REVIEW

**Comment by giordano** [comment]
Current PCRE2:
```
sandbox:${WORKSPACE} # otool -L libpcre2-*.dylib
libpcre2-16.0.dylib:
        @rpath/libpcre2-16.0.dylib (compatibility version 10.0.0, current version 10.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
libpcre2-16.dylib:
        @rpath/libpcre2-16.0.dylib (compatibility version 10.0.0, current version 10.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
libpcre2-32.0.dylib:
        @rpath/libpcre2-32.0.dylib (compatibility version 10.0.0, current version 10.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
libpcre2-32.dylib:
        @rpath/libpcre2-32.0.dylib (compatibility version 10.0.0, current version 10.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
libpcre2-8.0.dylib:
        @rpath/libpcre2-8.0.dylib (compatibility version 10.0.0, current version 10.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
libpcre2-8.dylib:
        @rpath/libpcre2-8.0.dylib (compatibility version 10.0.0, current version 10.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
libpcre2-posix.2.dylib:
        @rpath/libpcre2-posix.2.dylib (compatibility version 3.0.0, current version 3.3.0)
        @rpath/libpcre2-8.0.dylib (compatibility version 10.0.0, current version 10.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
libpcre2-posix.dylib:
        @rpath/libpcre2-posix.2.dylib (compatibility version 3.0.0, current version 3.3.0)
        @rpath/libpcre2-8.0.dylib (compatibility version 10.0.0, current version 10.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```
This one:
```
sandbox:${WORKSPACE} # otool -L libpcre2-*.dylib 
libpcre2-16.0.dylib:
        @rpath/libpcre2-16.0.dylib (compatibility version 11.0.0, current version 11.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
libpcre2-16.dylib:
        @rpath/libpcre2-16.0.dylib (compatibility version 11.0.0, current version 11.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
libpcre2-32.0.dylib:
        @rpath/libpcre2-32.0.dylib (compatibility version 11.0.0, current version 11.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
libpcre2-32.dylib:
        @rpath/libpcre2-32.0.dylib (compatibility version 11.0.0, current version 11.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
libpcre2-8.0.dylib:
        @rpath/libpcre2-8.0.dylib (compatibility version 11.0.0, current version 11.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
libpcre2-8.dylib:
        @rpath/libpcre2-8.0.dylib (compatibility version 11.0.0, current version 11.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
libpcre2-posix.2.dylib:
        @rpath/libpcre2-posix.2.dylib (compatibility version 3.0.0, current version 3.3.0)
        @rpath/libpcre2-8.0.dylib (compatibility version 11.0.0, current version 11.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
libpcre2-posix.dylib:
        @rpath/libpcre2-posix.2.dylib (compatibility version 3.0.0, current version 3.3.0)
        @rpath/libpcre2-8.0.dylib (compatibility version 11.0.0, current version 11.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```
This is going to create the same headaches as GMP, maybe even worse as the soversion changed also on Linux (from `libpcre2-32.so.0.9.0` to `libpcre2-32.so.0.10.0`)

**Comment by musm** [comment]
yikes that sounds annoyingly complicated

**Comment by staticfloat** [comment]
So I think the way forward here is to change all dependencies of PCRE2_jll to express a version compatibility that requires v10.31 for all old JLLs, and all new JLLs will require PCRE2_jll v10.35+.

**Comment by staticfloat** [comment]
Okay so the `SONAME` issue is not a problem on Linux; the SONAME used by `PCRE2` is just `libpcre2-8.so.0` (verified by looking at the `Git_jll` output on Linux).  So if we want `Git_jll` (which is the only other user of `PCRE2_jll`.....so far) we just need to tell `Git_jll` to build against the oldest version of `PCRE2_jll` that we can stomach, which will allow `Git_jll` to be compatible with the corresponding version of Julia onward.

**Comment by giordano** [comment]
However we need a way to better control this, it's very easy to forget about it (see #2050...)

**Comment by staticfloat** [comment]
Agreed.

I think it's reasonable for us to do a quick test across multiple Julia versions that a JLL is loadable.  We can do the test on `x86_64-linux-gnu` right here on Yggdrasil.

**Pull request merged**
