### PR TITLE
rebuild Glib

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Comment by vchuravy** [comment]
Currently fails with:

```

2020-04-03T00:11:19.7008970Z [0m[1m[00:11:19] [22m../glib/gconvert.c:59:2: error: #error GNU libiconv not in use but included iconv.h is from libiconv
2020-04-03T00:11:19.7009936Z [0m[1m[00:11:19] [22m #error GNU libiconv not in use but included iconv.h is from libiconv
```

**Comment by giordano** [comment]
You'll also likely need to rename the products, see https://github.com/JuliaPackaging/Yggdrasil/pull/91/files

**Comment by giordano** [comment]
We're hitting this check: https://gitlab.gnome.org/GNOME/glib/-/blob/37f41eb44a7d423069ff93f44dd0baec92adad62/glib/gconvert.c#L57.  I'm going to figure out why `USE_LIBICONV_GNU` is not defined

**Comment by vchuravy** [comment]
Yay!

**Comment by giordano** [comment]
Hold on, I wanted to see if we can slim the Windows tarballs

**Comment by giordano** [comment]
Well, we don't really save much space in the compressed archive by removing the static archives, less than 0.1 MiB

**Pull request merged**
