### PR TITLE
[Qt] Try to fix libatomic issue on armv7

### PR DESCRIPTION
**Pull request by ViralBShah**
Attempt to fix #2204

### CODE REVIEW

**Comment by ViralBShah** [comment]
@barche Any clue here why this is failing?

**Comment by barche** [comment]
Looks to me like it's picking up the wrong header files for compilation now, qmake needs to be built for the host, not the target.

**Comment by ViralBShah** [comment]
Perhaps it is picking up something from `CompilerSupportLibraries_jll` that it shouldn't? Seems like @giordano may have a clue.

**Comment by ViralBShah** [comment]
The wrong ELF header suggests that it is perhaps picking up the wrong cross-compiler.

**Comment by giordano** [comment]
All hard-coded `/opt/bin` paths must be replaced with `/opt/bin/${bb_full_target}` (or even better, don't hard-code these paths which aren't guaranteed to stay the same forever)

**Comment by giordano** [comment]
But I'm a bit lost about why adding CSL would help with #2204

**Comment by ViralBShah** [comment]
Because the armv7 failure was due to it not finding libatomic, and the Qt build was issuing a warning that CSL was necessary.

**Comment by giordano** [comment]
> Because the armv7 failure was due to it not finding libatomic

No, the error is an undefined reference to a symbol defined in `libatomic.so`.  It's more likely that the solution is a `-latomic` somewhere.  I stopped the registration because I believe this is wrong

**Comment by ViralBShah** [comment]
Should we ignore the warning in the earlier Qt build?

**Comment by giordano** [comment]
It might still be the case that CSL is helpful at runtime, but not to fix the build error for GR.  I'm trying to have a look

**Comment by ViralBShah** [comment]
Ok thanks. I see what you are saying. I still think that CSL is useful to have to address the warning. But it may still not fix the GR issue - because it was a missing symbol issue and not a missing library issue. 

Maybe the libatomic we build against and the one we end up using at install time are different?

**Comment by giordano** [comment]
```
sandbox:${WORKSPACE} # ${target}-objdump -p libQt5Core.so | grep -i needed
  NEEDED               libiconv.so.2
  NEEDED               libpthread.so.0
  NEEDED               libatomic.so.1
  NEEDED               libz.so.1
  NEEDED               libdl.so.2
  NEEDED               libstdc++.so.6
  NEEDED               libm.so.6
  NEEDED               libgcc_s.so.1
  NEEDED               libc.so.6
  NEEDED               ld-linux-armhf.so.3
```
`libQt5Core.so` correctly links to `libatomic.so`, so I don't think there is any issue in the Qt build.  `CompilerSupporLibraries_jll` might still be a good idea, but that can be added without rebuilding the tarballs (i.e., using `[skip build]`), reason why I stopped the registration: I don't want to rebuild new tarballs without any real change for the users.  Especially Qt which is quite large (~50 MiB), it'd cause a new large download for the users, with no benefits.

**Comment by giordano** [comment]
I'm now convinced this is an issue in GR:
```
[ 30%] Linking CXX executable gksqt
/usr/bin/cmake -E cmake_link_script CMakeFiles/gksqt.dir/link.txt --verbose=1
/opt/bin/armv7l-linux-gnueabihf-libgfortran5-cxx11/g++ --sysroot=/opt/arm-linux-gnueabihf/arm-linux-gnueabihf/sys-root/  -O3 -DNDEBUG  -rdynamic CMakeFiles/gksqt.dir/gksqt_autogen/mocs_compilation.cpp.o CMakeFiles/gksqt.dir/lib/gks/qt/gksqt.cxx.o CMakeFiles/gksqt.dir/lib/gks/qt/gksserver.cxx.o CMakeFiles/gksqt.dir/lib/gks/qt/gkswidget.cxx.o CMakeFiles/gksqt.dir/gksqt_autogen/BBJKBE7WMO/qrc_gksqt.cpp.o  -o gksqt  -Wl,-rpath,/workspace/destdir/lib: libGKS.a /workspace/destdir/lib/libQt5Widgets.so.5.15.1 /workspace/destdir/lib/libQt5Network.so.5.15.1 -lpthread -lm /workspace/destdir/lib/libfreetype.so /workspace/destdir/lib/libpng.so /workspace/destdir/lib/libz.so -ldl /workspace/destdir/lib/libQt5Gui.so.5.15.1 /workspace/destdir/lib/libQt5Core.so.5.15.1 -Wl,-rpath-link,/workspace/destdir/lib 
/opt/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/8.1.0/../../../../arm-linux-gnueabihf/bin/ld: warning: libatomic.so.1, needed by /workspace/destdir/lib/libQt5Widgets.so.5.15.1, not found (try using -rpath or -rpath-link)
/opt/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/8.1.0/../../../../arm-linux-gnueabihf/bin/ld: /workspace/destdir/lib/libQt5Core.so.5.15.1: undefined reference to `__atomic_store_8@LIBATOMIC_1.0'
/opt/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/8.1.0/../../../../arm-linux-gnueabihf/bin/ld: /workspace/destdir/lib/libQt5Gui.so.5.15.1: undefined reference to `__atomic_fetch_add_8@LIBATOMIC_1.0'
/opt/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/8.1.0/../../../../arm-linux-gnueabihf/bin/ld: /workspace/destdir/lib/libQt5Core.so.5.15.1: undefined reference to `__atomic_load_8@LIBATOMIC_1.0'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/gksqt.dir/build.make:179: gksqt] Error 1
make[2]: Leaving directory '/workspace/srcdir/build'
make[1]: *** [CMakeFiles/Makefile2:253: CMakeFiles/gksqt.dir/all] Error 2
make[1]: Leaving directory '/workspace/srcdir/build'
make: *** [Makefile:150: all] Error 2
sandbox:${WORKSPACE}/srcdir/build # /opt/bin/armv7l-linux-gnueabihf-libgfortran5-cxx11/g++ --sysroot=/opt/arm-linux-gnueabihf/arm-linux-gnueabihf/sys-root/  -O3 -DNDEBUG  -rdynamic CMakeFiles/gksqt.dir/gksqt_autogen/mocs_compilation.cpp.o CMakeFiles/gksqt.dir/lib/gks/qt/gksqt.cxx.o CMakeFiles/gksqt.dir/lib/gks/qt/gksserver.cxx.o CMakeFiles/gksqt.dir/lib/gks/qt/gkswidget.cxx.o CMakeFiles/gksqt.dir/gksqt_autogen/BBJKBE7WMO/qrc_gksqt.cpp.o  -o gksqt  -Wl,-rpath,/workspace/destdir/lib: libGKS.a /workspace/destdir/lib/libQt5Widgets.so.5.15.1 /workspace/destdir/lib/libQt5Network.so.5.15.1 -lpthread -lm /workspace/destdir/lib/libfreetype.so /workspace/destdir/lib/libpng.so /workspace/destdir/lib/libz.so -ldl /workspace/destdir/lib/libQt5Gui.so.5.15.1 /workspace/destdir/lib/libQt5Core.so.5.15.1 -Wl,-rpath-link,/workspace/destdir/lib 
/opt/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/8.1.0/../../../../arm-linux-gnueabihf/bin/ld: warning: libatomic.so.1, needed by /workspace/destdir/lib/libQt5Widgets.so.5.15.1, not found (try using -rpath or -rpath-link)
/opt/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/8.1.0/../../../../arm-linux-gnueabihf/bin/ld: /workspace/destdir/lib/libQt5Core.so.5.15.1: undefined reference to `__atomic_store_8@LIBATOMIC_1.0'
/opt/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/8.1.0/../../../../arm-linux-gnueabihf/bin/ld: /workspace/destdir/lib/libQt5Gui.so.5.15.1: undefined reference to `__atomic_fetch_add_8@LIBATOMIC_1.0'
/opt/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/8.1.0/../../../../arm-linux-gnueabihf/bin/ld: /workspace/destdir/lib/libQt5Core.so.5.15.1: undefined reference to `__atomic_load_8@LIBATOMIC_1.0'
collect2: error: ld returned 1 exit status
sandbox:${WORKSPACE}/srcdir/build # /opt/bin/armv7l-linux-gnueabihf-libgfortran5-cxx11/g++ --sysroot=/opt/arm-linux-gnueabihf/arm-linux-gnueabihf/sys-root/  -O3 -DNDEBUG  -rdynamic CMakeFiles/gksqt.dir/gksqt_autogen/mocs_compilation.cpp.o CMakeFiles/gksqt.dir/lib/gks/qt/gksqt.cxx.o CMakeFiles/gksqt.dir/lib/gks/qt/gksserver.cxx.o CMakeFiles/gksqt.dir/lib/gks/qt/gkswidget.cxx.o CMakeFiles/gksqt.dir/gksqt_autogen/BBJKBE7WMO/qrc_gksqt.cpp.o  -o gksqt  -Wl,-rpath,/workspace/destdir/lib: libGKS.a /workspace/destdir/lib/libQt5Widgets.so.5.15.1 /workspace/destdir/lib/libQt5Network.so.5.15.1 -lpthread -lm /workspace/destdir/lib/libfreetype.so /workspace/destdir/lib/libpng.so /workspace/destdir/lib/libz.so -ldl /workspace/destdir/lib/libQt5Gui.so.5.15.1 /workspace/destdir/lib/libQt5Core.so.5.15.1 -Wl,-rpath-link,/workspace/destdir/lib -latomic
sandbox:${WORKSPACE}/srcdir/build #
```
In the last command I simply added `-latomic` at the end and that fixed the build

**Comment by giordano** [comment]
I pushed [a better fix](https://github.com/JuliaPackaging/Yggdrasil/commit/1149da1309814594e9eb9278b82916a2d09c5c2c) in #2204

**Comment by ViralBShah** [comment]
@barche While looking into Qt I realized there is a new release 5.15.2. Is it worthwhile to update the build?

**Comment by ViralBShah** [comment]
The other thing I wanted to do was fix was the file permissions in the Qt install. Is there something we can do on the package side to fix this? Or is it something that will be fixed somewhere else in the system?

**Comment by giordano** [comment]
> Is there something we can do on the package side to fix this? Or is it something that will be fixed somewhere else in the system?

Hard to tell anything, I don't even know what the problem is :slightly_smiling_face:

**Comment by barche** [comment]
The permissions issue is tracked here: https://github.com/JuliaLang/Pkg.jl/issues/2185

There is nothing to be done at the level of the Qt package for that.

**Comment by barche** [comment]
> While looking into Qt I realized there is a new release 5.15.2. Is it worthwhile to update the build?

It's a bugfix release, I don't think there is any rush in upgrading.

**Comment by giordano** [comment]
> The permissions issue is tracked here: JuliaLang/Pkg.jl#2185

I mean, _I_ opened that issue, but I looked into the ICU tarball, I don't know whether the problem we're seeing in Qt has the same root or not, I never looked into it.

**Comment by giordano** [comment]
> > The permissions issue is tracked here: JuliaLang/Pkg.jl#2185
> 
> I mean, _I_ opened that issue
> 

BTW, just one hour ago I opened https://github.com/JuliaLang/Pkg.jl/pull/2274 to make sure we don't run into the same issue again in the future.

**Comment by barche** [comment]
> I don't know whether the problem we're seeing in Qt has the same root or not

Well, the latest Qt tarballs still have the problem, for sure. I don't know if these are from after the switch to Tar.jl?

**Comment by giordano** [comment]
I now looked into the Qt tarball
```
% wget -q -O - 'https://github.com/JuliaBinaryWrappers/Qt_jll.jl/releases/download/Qt-v5.15.1%2B0/Qt.v5.15.1.x86_64-apple-darwin.tar.gz' | tar tzvf - | grep QtMultimediaQuick.framework
drwxr-xr-x root/root         0 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/
lrwxrwxrwx root/root         0 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Resources -> Versions/Current/Resources
drwxr-xr-x root/root         0 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/
dr-xr-xr-x root/root         0 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/
dr-xr-xr-x root/root         0 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/Resources/
-r--r--r-- root/root       660 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/Resources/Info.plist
-r--r--r-- root/root      1959 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/Resources/QtMultimediaQuick.prl
dr-xr-xr-x root/root         0 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/Headers/
-r--r--r-- root/root       268 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/Headers/QtMultimediaQuickDepends
-r--r--r-- root/root        38 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/Headers/QtMultimediaQuickVersion
-r--r--r-- root/root       175 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/Headers/QtMultimediaQuick
drwxr-xr-x root/root         0 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/
drwxr-xr-x root/root         0 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/QtMultimediaQuick/
drwxr-xr-x root/root         0 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/QtMultimediaQuick/private/
-r--r--r-- root/root      4483 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/QtMultimediaQuick/private/qdeclarativevideooutput_backend_p.h
-r--r--r-- root/root      3208 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/QtMultimediaQuick/private/qsgvideonode_rgb_p.h
-r--r--r-- root/root      5267 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/QtMultimediaQuick/private/qdeclarativevideooutput_render_p.h
-r--r--r-- root/root      3225 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/QtMultimediaQuick/private/qsgvideonode_texture_p.h
-r--r--r-- root/root      3256 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/QtMultimediaQuick/private/qsgvideonode_yuv_p.h
-r--r--r-- root/root      3990 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/QtMultimediaQuick/private/qsgvideonode_p.h
-r--r--r-- root/root      7271 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/QtMultimediaQuick/private/qdeclarativevideooutput_p.h
-r--r--r-- root/root      2532 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/QtMultimediaQuick/private/qtmultimediaquickdefs_p.h
-r--r--r-- root/root      3142 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/QtMultimediaQuick/private/qdeclarativevideooutput_window_p.h
-r--r--r-- root/root       253 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/Headers/qtmultimediaquickversion.h
-r-xr-xr-x root/root    183000 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/5/QtMultimediaQuick
lrwxrwxrwx root/root         0 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Versions/Current -> 5
lrwxrwxrwx root/root         0 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/Headers -> Versions/Current/Headers
lrwxrwxrwx root/root         0 2020-11-20 14:06 ./lib/QtMultimediaQuick.framework/QtMultimediaQuick -> Versions/Current/QtMultimediaQuick
```
So the situation is similar to `ICU`: there are symlinks to some directories and the files inside those directories, for some reasons we don't know, got read-only permissions.

In the build of this PR (which uses a newer version of Julia and Pkg than the latest released version of `Qt_jll`) the files have the right permissions (`644`)
```
% wget -q -O - 'https://julia-bb-buildcache.s3.amazonaws.com/6b69c2cba76191dcf5d71d651c5437126f00266ff45e24e28d31af48cccbef87/4811a88f72531a77871eaa3bd40a9f9327faeac72095f06c9a7c8d8243dd92d7/x86_64-apple-darwin.tar.gz' | tar tzvf - | grep QtMultimediaQuick.framework
lrwxr-xr-x 0/0               0 1970-01-01 01:00 lib/QtMultimediaQuick.framework/Headers -> Versions/Current/Headers
lrwxr-xr-x 0/0               0 1970-01-01 01:00 lib/QtMultimediaQuick.framework/QtMultimediaQuick -> Versions/Current/QtMultimediaQuick
lrwxr-xr-x 0/0               0 1970-01-01 01:00 lib/QtMultimediaQuick.framework/Resources -> Versions/Current/Resources
-rw-r--r-- 0/0            4483 1970-01-01 01:00 lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/QtMultimediaQuick/private/qdeclarativevideooutput_backend_p.h
-rw-r--r-- 0/0            7271 1970-01-01 01:00 lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/QtMultimediaQuick/private/qdeclarativevideooutput_p.h
-rw-r--r-- 0/0            5267 1970-01-01 01:00 lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/QtMultimediaQuick/private/qdeclarativevideooutput_render_p.h
-rw-r--r-- 0/0            3142 1970-01-01 01:00 lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/QtMultimediaQuick/private/qdeclarativevideooutput_window_p.h
-rw-r--r-- 0/0            3990 1970-01-01 01:00 lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/QtMultimediaQuick/private/qsgvideonode_p.h
-rw-r--r-- 0/0            3208 1970-01-01 01:00 lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/QtMultimediaQuick/private/qsgvideonode_rgb_p.h
-rw-r--r-- 0/0            3225 1970-01-01 01:00 lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/QtMultimediaQuick/private/qsgvideonode_texture_p.h
-rw-r--r-- 0/0            3256 1970-01-01 01:00 lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/QtMultimediaQuick/private/qsgvideonode_yuv_p.h
-rw-r--r-- 0/0            2532 1970-01-01 01:00 lib/QtMultimediaQuick.framework/Versions/5/Headers/5.15.1/QtMultimediaQuick/private/qtmultimediaquickdefs_p.h
-rw-r--r-- 0/0             175 1970-01-01 01:00 lib/QtMultimediaQuick.framework/Versions/5/Headers/QtMultimediaQuick
-rw-r--r-- 0/0             268 1970-01-01 01:00 lib/QtMultimediaQuick.framework/Versions/5/Headers/QtMultimediaQuickDepends
-rw-r--r-- 0/0              38 1970-01-01 01:00 lib/QtMultimediaQuick.framework/Versions/5/Headers/QtMultimediaQuickVersion
-rw-r--r-- 0/0             253 1970-01-01 01:00 lib/QtMultimediaQuick.framework/Versions/5/Headers/qtmultimediaquickversion.h
-rwxr-xr-x 0/0          183000 1970-01-01 01:00 lib/QtMultimediaQuick.framework/Versions/5/QtMultimediaQuick
-rw-r--r-- 0/0             660 1970-01-01 01:00 lib/QtMultimediaQuick.framework/Versions/5/Resources/Info.plist
-rw-r--r-- 0/0            1959 1970-01-01 01:00 lib/QtMultimediaQuick.framework/Versions/5/Resources/QtMultimediaQuick.prl
lrwxr-xr-x 0/0               0 1970-01-01 01:00 lib/QtMultimediaQuick.framework/Versions/Current -> 5
```

**Comment by ViralBShah** [comment]
Should we bump Qt to 5.15.2, which will get us the new version and also the fixes?

**Comment by barche** [comment]
> Should we bump Qt to 5.15.2, which will get us the new version and also these permissions fixes?

Seems worth it to me!

**Pull request merged**
