### PR TITLE
Update Arb for Apple M1 support

### PR DESCRIPTION
**Pull request by fingolfin**
CC @tthsqe12 @wbhart @thofma

### CODE REVIEW

**Comment by fingolfin** [comment]
I've had PRs change multiple recipes, sometimes that's useful and a huge timesaver.

Moreover, I think it is crystal clear for this PR which recipe it modifies -- it really feels what you are doing is "convention for its own sake". It's still unclear to me what problem you are trying to address?

And if this is indeed a convention, then where is it documented? And why isn't it followed for >50% of all commits, and why has nobody ever mentioned it to me in the past 1.5 years?

Also, who are you and who put you in charge of setting policy for Yggdrasil? Is it really worth it to annoy people with it?

**Comment by giordano** [comment]
Ok, chill down.  Although I do personally like the commit style `[PackageName] Description`, that's not required, the important thing is to have a reference to the touched package, and this PR already has it, so that's good with me.  I'm sure @jeremiahpslewis had good intentions, but no need to insist on asking something unnecessarily.

@fingolfin I'm not sure whether this is good to go or you're still waiting for :+1: from the people pinged above :slightly_smiling_face:

**Comment by fingolfin** [comment]
This is good to go, thanks

**Comment by jeremiahpslewis** [comment]
@fingolfin

Appreciate your candid response, you bring up valid points.

1. I’m just a contributor to the Yggdrasil project and like everyone else involved volunteer my time to try to make it run smoothly and contain lots of great, up-to-date binaries.
2. Like any PR comment / feedback, you’re free to disregard it entirely…the ultimate determination of what does / doesn’t work is whether the PR gets merged by a maintainer (which I am not).
3. I hope that you feel treated with respect in our conversation in this PR; Yggdrasil is a true ‘crossroads’ project where many different parts of the Julia community intersect and collaborate. I also expect to be treated with respect in this project and feel that some of your comments escalate a discussion to a personal attack; this makes me feel less welcome here.
4. The reason why I posted on your PR, specifically, although many PRs do not follow this convention (as I mentioned above), is that you are quite active, so if you could be convinced that the convention helps, then it would have a significant impact on the overall convention.
5. The best example of where the convention is a lifesaver is if you are watching the project on github…then you get many notifications every day and can easily scan them if they are ‘project prepended’. See below. :)
6. As projects get bigger, it’s worth it to discuss and then formalize some things. I’ve opened up an issue where this convention can be debated.

image

**Comment by fingolfin** [comment]
@jeremiahpslewis actually I do not find your action respectful, but rather toxic. If you had started out with the issue and/or initiated an open discussion on Slack that would have been one thing, and I would have happily participated . But singling me out and phrasing things as if you were a maintainer asking a dumb newb to follow the rules (that you actually made up yourself) felt  hostile and demotivating. And I am still not convinced this is a useful rule; the reason you give is about how you personally would benefit.  To me, it is simply yet another arbitrary barrier for potential contributors to this repository.

Anyway, I am not interested in engaging with you on this anymore. Blocked.

**Comment by giordano** [comment]
Alright, stand down everybody.  We'll continue the discussion about the title elsewhere, there is no need to insist further here.

**Pull request merged**
