### PR TITLE
[OpenLDAPClient] Rebuild

### PR DESCRIPTION
**Pull request by giordano**
CC: @felipenoris @aviks

### CODE REVIEW

**Comment by aviks** [comment]
Any particular reason for rebuilding this? Could figure out from the diff.

**Comment by giordano** [comment]
https://github.com/JuliaPackaging/Yggdrasil/issues/1438#issuecomment-674099868

**Comment by aviks** [comment]
Ah, ok, thanks!

**Comment by felipenoris** [comment]
@giordano many thanks!!

I'll wait until Pkg Server updates this and I'll give you feedback if the macOS issue got solved.

**Pull request merged**
