### PR TITLE
Add LLVM AArch64 unwind patches

### PR DESCRIPTION
**Pull request by topolarity**
This includes patches to resolve https://github.com/JuliaLang/julia/issues/39986

### CODE REVIEW

**Comment by vchuravy** [comment]
We need to fix the `common.jl` https://github.com/JuliaPackaging/Yggdrasil/pull/2906/files#diff-aec5ce90e52ef031701fcc63b146c71cae494f32831653a0f582902a3d626977R161 

Also @Keno do we want to backport this to Julia 1.6?

@topolarity can you also add the patches to LLVM_full@12

**Comment by Keno** [comment]
Are we doing a 1.6 release for Apple Silicon? I think we could, but somebody would have to take charge. Probably a good idea if the 1.6 series will be LTS. If so, we'd need the backport. Also, seems like there may be an additional change required to force the eh frame emission? In that case, we should maybe wait until that's figured out, so we can avoid having to do two LLVM bumps.

**Comment by topolarity** [comment]
Sure thing :+1: I've added the patches for LLVM 12

The second patch included already [forces EH Frame emission on AArch64](https://github.com/JuliaPackaging/Yggdrasil/pull/3063/files#diff-97f1d5e894c2a8c4e31ab54505f258bd2476d2d17c677cac12ca6d329a14ef6eR22-R25). The related open on https://reviews.llvm.org/D103052 is how to enable that specifically for JIT workflows at run-time, to avoid hard-coding it like this

**Comment by Keno** [comment]
@vchuravy would you mind pushing this through? I'd like to have this in 1.7 if possible.

**Comment by vchuravy** [comment]
@topolarity thanks! I have it from here

**Pull request closed without merging**
