### PR TITLE
Remove SuiteSparse 4 which we haven't used in a very long time.

### PR DESCRIPTION
**Pull request by ViralBShah**
@giordano @staticfloat Any reason to keep this? I can't think of a good reason.

### CODE REVIEW

**Comment by vchuravy** [comment]
LTS is currently 1.0.5 and that uses SuiteSparse 4 (https://github.com/JuliaLang/julia/blob/3af96bcefcb0aec559d4652fd75e1bc3fcfe99da/deps/Versions.make#L6)

**Comment by ViralBShah** [comment]
Good point. But LTS does not use anything from Yggdrasil, right?

**Comment by ararslan** [comment]
I thought it did with `make USE_BINARYBUILDER=1`.

**Comment by ViralBShah** [comment]
No, we didn't have all this stuff back then.

https://github.com/JuliaLang/julia/blob/release-1.0/deps/suitesparse.mk

**Comment by staticfloat** [comment]
I think I added this a while back as a test for libgfortran stuff.  Yeah, let's just get rid of it.

**Pull request merged**
