### PR TITLE
[FastJet_Julia_Wrapper] version bump

### PR DESCRIPTION
**Pull request by jstrube**

### CODE REVIEW

**Comment by jstrube** [comment]
I don't understand what this error message is about. This looks unrelated to the changes in this PR.

**Comment by giordano** [comment]
@fingolfin this is the error I was referring to in https://github.com/JuliaPackaging/Yggdrasil/pull/2543#discussion_r575727249

**Comment by jstrube** [comment]
Ah, ok, looks like at least I'm not the only one seeing this.

**Comment by jstrube** [comment]
What's the workaround, though? I don't understand how to fix from the comment you linked. Is this something I'll have to do for other build scripts, too, in the future?

**Comment by giordano** [comment]
I just put an `ARGS` before the `include`

**Comment by giordano** [comment]
> Is this something I'll have to do for other build scripts, too, in the future?

If I knew what's going on I wouldn't need to leave random `ARGS` in the script :slightly_smiling_face:   Something must have changed in Julia v1.6, I think

**Comment by jstrube** [comment]
The workaround seems to work! Thanks. The build failure is unrelated to my code, though. 
Is this known? Should I just exclude the platform for the time being?

**Comment by jstrube** [comment]
Thanks!

**Pull request merged**
