### PR TITLE
[Zlib] Trigger a new build

### PR DESCRIPTION
**Pull request by ararslan**
To get FreeBSD AArch64 support

### CODE REVIEW

**Comment by giordano** [comment]
https://buildkite.com/julialang/yggdrasil/builds/13148#0191d976-0012-41b3-b57e-608bdf6baeac/666-963
```
┌ Warning: libz.so.1.3.1 has an ELF header OS/ABI value that is not set to FreeBSD (9), this may be an issue at link time
```
Sigh.

**Comment by ararslan** [comment]
> Warning: libz.so.1.3.1 has an ELF header OS/ABI value that is not set to FreeBSD (9), this may be an issue at link time

😕

**Comment by ararslan** [comment]
https://buildkite.com/julialang/yggdrasil/builds/13148#0191d976-0012-41b3-b57e-608bdf6baeac/666-674

This is weird, the other platforms don't have this in their logs 🤔

**Comment by giordano** [comment]
You mean
```
Downloading artifact: PlatformSupport-aarch64-unknown-freebsd13.2.v2024.8.10.x86_64-linux-musl.unpacked
```
? Their platform support artifacts are probably cached: they're always needed and they're always the same (unlike for example gcc: it's also always needed, but we often use different versions, so caching isn't very effective for that)

**Comment by ararslan** [comment]
> unlike for example gcc: it's also always needed, but we often use different versions, so caching isn't very effective for that

The other platforms aren't downloading GCC either, but this is:

```
Downloading artifact: GCCBootstrap-aarch64-unknown-freebsd13.2.v7.1.0.x86_64-linux-musl.unpacked
```
https://buildkite.com/julialang/yggdrasil/builds/13148#0191d976-0012-41b3-b57e-608bdf6baeac/666-676

Why would this need GCC? FreeBSD uses Clang as its compiler.

**Comment by giordano** [comment]
Ah, when we ask for the "C" compilers we always have both gcc and clang, it's only the default (what `cc` points to) which is platform-specific (clang on bsd systems, gcc elsewhere)

**Pull request merged**
