### PR TITLE
Remove PALISADE builder

### PR DESCRIPTION
**Pull request by fingolfin**
Nothing uses this, and its LibraryProduct was set wrong, so I have
some doubts this ever worked in a meaningful way?

### CODE REVIEW

**Comment by fingolfin** [comment]
@staticfloat added PALISADE and IIRC he also confirmed at some point that it ought to be safe to remove this (but I might misremember this)

**Comment by ViralBShah** [comment]
People may have private packages that use BB libraries that don't have any dependents. But of course, if it doesn't work, that's a different matter altogether.

**Comment by fingolfin** [comment]
But as far as I can tell, we don't provide binaries for this recipe (definitely not in a JLL); if somebody relies on this privately they must have uploaded their own binaries somewhere? Even of not: the recipe is not necessary to use the binaries? And finally, I'd rather have those provate users of an outdated and semibroken PALISADE complain about the removal and the reinstantiate it, than to leave them under the believe this is sage tonuse inits current form?

**Comment by ViralBShah** [comment]
Agree.

**Pull request merged**
