### PR TITLE
Rebuild mlpack

### PR DESCRIPTION
**Pull request by rcurtin**
This is a follow-up to #580.

### CODE REVIEW

**Comment by giordano** [comment]
I was rereading [this discussion](https://github.com/JuliaPackaging/Yggdrasil/pull/368#discussion_r364432643): in the end you're linking to `libarmadillo`, right?

**Comment by rcurtin** [comment]
Yes, so I'm guessing the question is "why does mlpack need a rebuild if it links against Armadillo anyway?"

The answer is a little bit weird.  Armadillo can be used as a header-only library, or it can generate `libarmadillo.so`.  What `libarmadillo.so` is is really just a *wrapper* around whatever LAPACK or BLAS is available on the system.  So basically it re-exports all of the LAPACK/BLAS symbols like `dgeev` as `wrapper_dgeev`.  The reason for this is so that users of Armadillo can easily link with `-larmadillo` as opposed to needing to link against all of the things that Armadillo is built on (various MKL libraries, or OpenBLAS or another LAPACK/BLAS replacement, etc., etc.).  In our work here for mlpack_jll and armadillo_jll we chose to use this wrapper library (although realistically it doesn't make much difference for us either way).

Where the `ARMA_BLAS_LONG` change really makes a difference is in Armadillo's internal type definition of the type `blas_int`.  In general that will choose a 32-bit integer type, but in our 64-bit Julia situation it needs a 64-bit integer (hence #580).  Now, we wouldn't need to do any relinking if that `blas_int` type was entirely contained in `libarmadillo.so`---but it's not.  `blas_int` is used throughout the Armadillo codebase, so its existing 32-bit definition will be compiled into the various parts of mlpack.  Thus rebuilding only `libarmadillo.so` won't actually get us all of the way to what we need, as now we have the situation that the Armadillo headers are trying to interface with `libarmadillo.so`, but in the mlpack shared objects `blas_int` is 32 bits but in `libarmadillo.so` it's 64, so it still explodes.

Um, anyway, I wrote a lot, I hope I correctly anticipated your question.  And if not it's always fun to write overdetailed explanations anyway.  I think. :smile:

**Comment by rcurtin** [comment]
Hmm, now that I think about it there actually is another potential concern here, which is that mlpack_jll will need to be rebuilt every time armadillo_jll is updated.  I don't know how this system handles things like that though, maybe there's already a solution in place or something.

**Comment by giordano** [comment]
> Hmm, now that I think about it there actually is another potential concern here, which is that mlpack_jll will need to be rebuilt every time armadillo_jll is updated.

Why? :thinking:   I mean, any kind of change or only particular changes like the one in #580?

**Comment by giordano** [comment]
To elaborate on my question, sometimes we need to retrigger a build of packages (just like what you did here), I don't think in cases like that if we rebuild armadillo we need to rebuild mlpack as well?  I assume that only real changes like #580 would warrant a rebuild.

**Comment by rcurtin** [comment]
So, the worry about rebuilding would be that symbols in libarmadillo.so had changed.  But, now that I think about it more closely, I guess this only happens on a major soversion bump. :+1:

**Comment by giordano** [comment]
```
julia> using mlpack

julia> x = rand(5, 5);

julia> mlpack.pca(x, verbose=true)
[INFO ] Performing PCA on dataset...
[INFO ] 100% of variance retained (5 dimensions).
5×5 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
  0.381181   0.177964   0.262588    0.024171   -1.29729e-16
 -0.361113  -0.415117   0.0620887  -0.108543   -1.37916e-16
  0.327677   0.390823  -0.170119   -0.0813053  -8.52652e-17
  0.345843  -0.435227  -0.12423     0.0896105  -1.36147e-16
 -0.693589   0.281556  -0.0303283   0.0760669  -1.50133e-17
```
:tada:

**Pull request merged**
