### PR TITLE
Set OpenSSL_jll compat to 1.1.10 [skip build]

### PR DESCRIPTION
**Pull request by mkitti**
I used the following to do this.

```julia
julia> function find_openssl_jll(; query="OpenSSL_jll")
           lines_dict = Dict{String, String}()
           for(root, dirs, files) in walkdir(".")
               for file in files
                   if file == "build_tarballs.jl"
                       fullfile = joinpath(root,file)
                       lines = filter(contains(query), readlines(fullfile))
                       if !isempty(lines)
                           printstyled(fullfile, ": "; color=:green)
                           println.(lines)
                           lines_dict[fullfile] = only(lines)
                       end
                   end
               end
           end
           return lines_dict
       end
find_openssl_jll (generic function with 1 method)

julia> function process_line(input)
           if !contains(input, "Dependency")
               return replace(input, "\"OpenSSL_jll\"" => "Dependency(\"OpenSSL_jll\"; compat=\"1.1.20\")")
           end
           m = match(r"(compat=\".*\")", input)
           if !isnothing(m)
               return replace(input, m.captures[1] => "compat=\"1.1.20\"")
           end
           m = match(r"\)(\,?)$", input)
           if !isnothing(m)
               return replace(input, r"\)\,?$" => "; compat=\"1.1.20\")$(m.captures[1])")
           end
       end
process_line (generic function with 1 method)

julia> function edit_files(lines_dict)
           for (file, line) in lines_dict
               new_line = process_line(line)
               contents = read(file, String)
               new_contents = replace(contents, line => new_line)
               write(file, new_contents)
           end
       end
edit_files (generic function with 1 method)

julia> find_openssl_jll() |> edit_files
```

[skip ci] [skip build]

### CODE REVIEW

**Comment by giordano** [comment]
Need to do the same also in the General registry :slightly_smiling_face:

**Comment by giordano** [comment]
Well, `[skip ci]` in Buildkite clearly works differently than AZP.  But now that I removed all references to `[skip ci]` I have no idea why CI isn't starting at all.

**Comment by mkitti** [comment]
> 2023-02-25 23:23:01 ERROR  Unrecoverable error, skipping retries
  | 2023-02-25 23:23:01 FATAL  Failed to upload and process pipeline: POST https://agent.buildkite.com/v3/jobs/01868ae2-9e51-4052-a487-1c5b6bc6e0a9/pipelines: 422 There must be at least 1 step in a group
  | pipeline upload failed:
  | steps:
  | - group: "Qt6Base"
  | steps: []
  |  
  | ERROR: LoadError: failed process: Process(`buildkite-agent pipeline upload --no-interpolation`, ProcessExited(1)) [1]

**Comment by giordano** [comment]
@vchuravy do you have a clue of what's going on here?

**Comment by vchuravy** [comment]
This is likely the first use of skip build.

probably we should add to https://github.com/JuliaPackaging/Yggdrasil/blob/f9fefe1606688bf0c56a8081a558f1caec35f2fe/.buildkite/generator.jl#L123

```
if !isempty(STEPS)
   definition = Dict(
    :steps => Any[group_step(NAME, STEPS)]
)
upload_pipeline(definition)
```

**Comment by giordano** [comment]
I don't think this is the first time we use `skip build`: https://github.com/search?q=repo%3AJuliaPackaging%2FYggdrasil+skip+build&type=commits&s=committer-date&o=desc (the BK pipeline [started on January 17](https://github.com/JuliaPackaging/Yggdrasil/commit/a1b9ad54254b7709878a12f9afe46dd8eb0137bf))

**Comment by mkitti** [comment]
Is there anything you would like me to do?

**Comment by giordano** [comment]
I think it'll be good to move on with this PR, but I have no idea of what's going on with CI, someone will have to figure that out.

**Comment by mkitti** [comment]
Hmm... see https://github.com/JuliaPackaging/Yggdrasil/pull/6486

**Comment by giordano** [comment]
This has been in separate PRs, thanks!

**Pull request closed without merging**
