### PR TITLE
Rename CUDNN and CUTENSOR packages.

### PR DESCRIPTION
**Pull request by maleadt**
```
(wrap) pkg> add CUDNN_CUDA10.2_jll
  Updating registry at `~/Julia/depot/registries/General`
  Updating git-repo `git@github.com:JuliaRegistries/General.git`
   Cloning git-repo `CUDNN_CUDA10.2_jll`
ERROR: failed to clone from CUDNN_CUDA10.2_jll, error: GitError(Code:ERROR, Class:Net, unsupported URL protocol)

julia> Pkg.add("CUDNN_CUDA10.2_jll")
ERROR: CUDNN_CUDA10.2_jll is not a valid packagename.
Stacktrace:
 [1] pkgerror(::String) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Pkg/src/Types.jl:113
 [2] check_package_name(::String, ::Symbol) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Pkg/src/API.jl:30
```

### CODE REVIEW

**Comment by giordano** [comment]
https://github.com/JuliaPackaging/Yggdrasil/pull/1144#discussion_r439583136 :slightly_smiling_face:

**Comment by maleadt** [comment]
Ah, completely missed that!

**Comment by maleadt** [comment]
Good to go? Or do you suggest a different naming scheme? It's a bit ugly...

**Comment by giordano** [comment]
It must be good for you, I don't care too much :wink:   But yeah, I was wondering whether `CUTENSOR_CUDA10_0` is easier to parse by eye?  (Maybe with another underscore before the major version?).  But really, the decision is up to you.  Just remember that the name of the directory must match the name of the package!

**Comment by maleadt** [comment]
I'd rather keep the single underscore to separate the package name from it's CUDA dependency, so let's go with this for now.

**Pull request merged**
