### PR TITLE
Draft to bump [HarfBuzz] version

### PR DESCRIPTION
**Pull request by bramtayl**

### CODE REVIEW

**Comment by bramtayl** [comment]
Sorry for the multiple commits

**Comment by giordano** [comment]
I believe the library for macOS of this new version is incompatible with the previous version

**Comment by bramtayl** [comment]
I don't really understand what that means to be honest...and I'm not finding anything too helpful on google either...maybe "library macOS incompatible" are just too general search terms?

**Comment by bramtayl** [comment]
But on their website they say

```
The API included in the hb.h file will not change in a compatibility-breaking way in any release. However, other, peripheral headers are more likely to go through minor modifications. We will do our best to never change APIs in an incompatible way. We will _never_ break the ABI. 
```

which is encouraging?

**Comment by giordano** [comment]
No, I checked the minimum compatibility version of the library for macOS and it's different, hence it's breaking

**Comment by bramtayl** [comment]
Ah. Well, turns out I don't actually need this I think, so sorry for the hastle

**Pull request closed without merging**
