### PR TITLE
Update LibTeXPrintf to upstream v1.17

### PR DESCRIPTION
**Pull request by stevengj**

### CODE REVIEW

**Comment by stevengj** [comment]
Build error:
```
[20:11:02] mv -f .deps/drawbox.Tpo .deps/drawbox.Po
[20:11:02] mv -f .deps/drawbox.Tpo .deps/drawbox.Plo
[20:11:02] mv: can't rename '.deps/drawbox.Tpo': No such file or directory
```
Looks suspicious that it's trying to  `mv -f deps/drawbox.Tpo` twice to two different destinations?  Could be an upstream bug?

**Comment by giordano** [comment]
Yes, and given the randomness of the failures and the fact that restarting failed jobs makes them succeed, my hunch is that this is due to the build being racy. I guess the developers don't frequently build with `-j16` (and maybe should learn about the new option `--shuffle` in gnu make 4.4)

**Comment by Suavesito-Olimpiada** [comment]
Yes, previous builds were also random for me. I'll report the bug upstream.

P.S. Thanks for the tip about `--shufle`! That seems like a nice addition.

**Comment by stevengj** [comment]
I found a fix for the problem — I'll submit a PR upstream.

**Pull request merged**
