### PR TITLE
[HDF5] Upgrade to 1.14.2

### PR DESCRIPTION
**Pull request by mkitti**
This sets up the source builds for HDF5 1.14.2.

Msys2 packages have been updated.

### CODE REVIEW

**Comment by mkitti** [comment]
@eschnett We may need to redo the H5init.c

**Comment by eschnett** [comment]
@mkitti I can do that for all architectures except Windows. Which architectures do we need?

**Comment by mkitti** [comment]
We need all architectures except Windows.

Note that upstream has a patch on the develop branch that moves this logic to runtime. We could alternatively try that.

Also, I ran into Axel at HUG23. You got a shout out at at least two talks there.

**Comment by eschnett** [comment]
I tried to open a pull request against your pull request branch https://github.com/mkitti/Yggdrasil/pull/1.

**Comment by mkitti** [comment]
I think we are good to go here.

**Pull request merged**
