### PR TITLE
[GnuPG] Add builder

### LINKED ISSUE #2728: Build GnuPG
If you need inspiration:
* [Alpine Linux](https://pkgs.alpinelinux.org/package/edge/main/x86_64/gnupg)
* [Arch Linux](https://archlinux.org/packages/core/x86_64/gnupg/)

CC: @christopher-dG

### PR DESCRIPTION
**Pull request by giordano**
Fix #2728, close #2728

### CODE REVIEW

**Comment by giordano** [comment]
CC @christopher-dG :slightly_smiling_face:  Thanks @Wimmerer for all the work along the way!

**Comment by christopher-dG** [comment]
Cool, thanks!

**Comment by giordano** [comment]
We may need to tweak the Windows build, I think it doesn't have gnutls support at the moment, but it should hopefully mostly working at the moment

**Comment by fredrikekre** [comment]
I get
```
gpg: failed to start agent '/workspace/destdir/bin/gpg-agent': No such file or directory
```
when trying to use this. `gpg-agent` exist in the tarball, but obviously not on that path.

**Comment by giordano** [comment]
Awesome.  Can you please open an issue?  We need to track down where the path is hard-coded and how to work around that

**Comment by giordano** [comment]
For the record, I believe the path is coming from https://github.com/gpg/gnupg/blob/86f446fd446fcc7295ecf6b37a3f4cca45a165f1/common/homedir.c#L1139, which should call the `gnupg_bindir` function defined in the same file

**Comment by fredrikekre** [comment]
https://github.com/JuliaPackaging/Yggdrasil/issues/2861

**Pull request merged**
