### PR TITLE
Sundials 5.1 build (and co-exist with Sundials 3 build)

### PR DESCRIPTION
**Pull request by ViralBShah**
This is basically the work of @jd-lara in #421, but creates a separate directory for Sundials 5.

@jd-lara Hope you don't mind me creating a new PR that is essentially what you had in #421. I would prefer to have your contributions in the commit log - so perhaps if this PR gets all green eventually, we can resuscitate your original PR in #421 with the work here. For now, I have closed it to avoid accidental merging and overwriting sundials 3.1.

Alternately if there is a way to add you to the commit log here, I would love to do so. I have seen it been done in other places, but not sure how to.

### CODE REVIEW

**Comment by jd-lara** [comment]
@ViralBShah no problem at all, I should also get back to this to wrap it up. A lot of that git log are also mistakes since all of this toolchain compilation is new to me. Thanks for letting me know, I will open a new PR when I have more progress and targe this folder.

**Comment by ViralBShah** [comment]
On windows, it is having trouble building the lapack banded solver: 
https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=1444&view=logs&j=b3a31097-4f47-5d0a-f6f4-af130d752a3f&t=8033e1c5-641c-5b4b-f4fe-4ec052bd18f0&l=4498

**Comment by giordano** [comment]
Yes, this is the same error we were seeing in #421:
```
[02:40:11] cd /workspace/srcdir/sundials-5.1.0/build/src/cvode && /opt/bin/i686-w64-mingw32-gcc --sysroot=/opt/i686-w64-mingw32/i686-w64-mingw32/sys-root/ -DBUILD_SUNDIALS_LIBRARY -D_CRT_SECURE_NO_WARNINGS @CMakeFiles/sundials_cvode_static.dir/includes_C.rsp -lgfortran -lquadmath -O3 -DNDEBUG   -o CMakeFiles/sundials_cvode_static.dir/__/sunmatrix/sparse/sunmatrix_sparse.c.obj   -c /workspace/srcdir/sundials-5.1.0/src/sunmatrix/sparse/sunmatrix_sparse.c
[02:40:11] cd /workspace/srcdir/sundials-5.1.0/build/src/cvodes && /opt/bin/i686-w64-mingw32-gcc --sysroot=/opt/i686-w64-mingw32/i686-w64-mingw32/sys-root/ -DBUILD_SUNDIALS_LIBRARY -D_CRT_SECURE_NO_WARNINGS -Dsundials_cvodes_shared_EXPORTS @CMakeFiles/sundials_cvodes_shared.dir/includes_C.rsp -lgfortran -lquadmath -O3 -DNDEBUG   -o CMakeFiles/sundials_cvodes_shared.dir/__/sundials/sundials_iterative.c.obj   -c /workspace/srcdir/sundials-5.1.0/src/sundials/sundials_iterative.c
[02:40:11] CMakeFiles/sundials_sunlinsollapackband_shared.dir/objects.a(sunlinsol_lapackband.c.obj):sunlinsol_lapackband.c:(.text+0x42c): undefined reference to `_imp__SUNLinSolNewEmpty'
[02:40:11] CMakeFiles/sundials_sunlinsollapackband_shared.dir/objects.a(sunlinsol_lapackband.c.obj):sunlinsol_lapackband.c:(.text+0x4ae): undefined reference to `_imp__SUNLinSolFree'
[02:40:11] CMakeFiles/sundials_sunlinsollapackband_shared.dir/objects.a(sunlinsol_lapackband.c.obj):sunlinsol_lapackband.c:(.text+0x55c): undefined reference to `_imp__SUNLinSolNewEmpty'
[02:40:11] CMakeFiles/sundials_sunlinsollapackband_shared.dir/objects.a(sunlinsol_lapackband.c.obj):sunlinsol_lapackband.c:(.text+0x5de): undefined reference to `_imp__SUNLinSolFree'
[02:40:11] collect2: error: ld returned 1 exit status
```
I'm fairly sure this is an upstream bug.

**Comment by jd-lara** [comment]
Should we open an issue in Sundials?

**Comment by ViralBShah** [comment]
Yes, I think so. It seems like it has to do with the link step not doing the right thing on windows.

**Comment by giordano** [comment]
> Should we open an issue in Sundials?

Yes, please.  I think they're missing some `__declspec` somewhere, or maybe it's not used when building with mingw

**Comment by ViralBShah** [comment]
These are the patches mingw folks apply to sundials (I think sundials 4): https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-cvode/001-install-location.patch

**Comment by giordano** [comment]
> These are the patches mingw folks apply to sundials (I think sundials 4): https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-cvode/001-install-location.patch

To me it looks like they're modifying some paths.  I might be wrong, but I don't expect that to resolve our issue.

**Comment by giordano** [comment]
There are tons of warnings like
```
[02:40:11] /workspace/srcdir/sundials-5.1.0/src/sundials/sundials_linearsolver.c:28:17: warning: ‘SUNLinSolNewEmpty’ redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
[02:40:11]  SUNLinearSolver SUNLinSolNewEmpty()
[02:40:11]                  ^~~~~~~~~~~~~~~~~
```
which is probably related

**Comment by ViralBShah** [comment]
@giordano Should we go ahead with the fix you suggested in the upstream issue? If `make test` passes, we should be ok.

**Comment by giordano** [comment]
Yes, I'm double checking locally that it works.  I was able to build in a debug shell, I need to convert into a working script.

**Comment by ViralBShah** [comment]
Will we still need the gfortran expansion?

**Comment by giordano** [comment]
Ok, this should be working, but now I'd like to remove explicit `-lgfortran -lquadmath` when not necessary, if possible.

**Comment by ViralBShah** [comment]
Not sure I got the `Co-authored-by:` stuff right.

**Comment by jd-lara** [comment]
Thanks a lot for the effort, I will write to the Sundials guys to add the fix.

**Comment by giordano** [comment]
> Not sure I got the Co-authored-by: stuff right.

I've fixed that.

Now I'm polishing the script to use libgfortran only for lapack

**Comment by giordano** [comment]
Ok, if tests pass it should be good to go

**Comment by giordano** [comment]
Looks like it worked?

**Comment by giordano** [comment]
> Will we still need the gfortran expansion?

Yes, if I build for `x86_64-linux-gnu` I get the following warnings:
```
[ Info: /home/mose/repo/builders/Yggdrasil/S/Sundials@5/build/x86_64-linux-gnu/chUoJwVx/destdir/lib/libsundials_sunlinsollapackband.so.3.1.0 locks us to libgfortran v3.0.0
┌ Warning: /home/mose/repo/builders/Yggdrasil/S/Sundials@5/build/x86_64-linux-gnu/chUoJwVx/destdir/lib/libsundials_sunlinsollapackband.so.3.1.0 links to libgfortran!  This causes incompatibilities across major versions of GCC.  To remedy this, you must build a tarball for each major version of GCC.  To do this, immediately after your `platforms` definition in your `build_tarballs.jl` file, add the line:
│ 
│     platforms = expand_gfortran_versions(platforms)
└ @ BinaryBuilder ~/.julia/dev/BinaryBuilder/src/auditor/compiler_abi.jl:47
[...]
[ Info: /home/mose/repo/builders/Yggdrasil/S/Sundials@5/build/x86_64-linux-gnu/chUoJwVx/destdir/lib/libsundials_sunlinsollapackdense.so.3.1.0 locks us to libgfortran v3.0.0
┌ Warning: /home/mose/repo/builders/Yggdrasil/S/Sundials@5/build/x86_64-linux-gnu/chUoJwVx/destdir/lib/libsundials_sunlinsollapackdense.so.3.1.0 links to libgfortran!  This causes incompatibilities across major versions of GCC.  To remedy this, you must build a tarball for each major version of GCC.  To do this, immediately after your `platforms` definition in your `build_tarballs.jl` file, add the line:
│ 
│     platforms = expand_gfortran_versions(platforms)
└ @ BinaryBuilder ~/.julia/dev/BinaryBuilder/src/auditor/compiler_abi.jl:47
```
and further down the following fatal error:
```
[ Info: Could not locate libsundials_sunlinsollapackdense inside ["/home/mose/repo/builders/Yggdrasil/S/Sundials@5/build/x86_64-linux-gnu/chUoJwVx/destdir/lib64", "/home/mose/repo/builders/Yggdrasil/S/Sundials@5/build/x86_64-linux-gnu/chUoJwVx/destdir/lib"]
┌ Error: Built Sundials but libsundials_sunlinsollapackdense still unsatisfied:
└ @ BinaryBuilder ~/.julia/dev/BinaryBuilder/src/AutoBuild.jl:677
```

**Comment by ViralBShah** [comment]
Is there a way to run `make test` on windows?

**Comment by giordano** [comment]
> Is there a way to run make test on windows?

No, we can't run tests in this environment :disappointed:

**Comment by ViralBShah** [comment]
Do we need `CompilerSupportLibraries`?

**Comment by giordano** [comment]
> Do we need `CompilerSupportLibraries`?

It doesn't look like so, audit would have complained otherwise, or the build would have failed.

**Comment by giordano** [comment]
Uhm, the build that should have published the JLL package failed after creating a [repo with a wrong name](https://github.com/JuliaBinaryWrappers/Sundials-5_jll.jl).  Something probably went wrong with the latest changes we had in CI here in Yggdrasil.

**Comment by ViralBShah** [comment]
Seems like #486 fixed it. How does one retrigger a build after merging? Submit a dummy PR?

**Comment by giordano** [comment]
> Submit a dummy PR?

Yes, exactly, however I see there are some problems with Azure Pipelines: the agents are up but the jobs aren't starting.  @staticfloat yesterday was playing a bit to try and fix the problem with colours

**Comment by ViralBShah** [comment]
@jd-lara follow the discussion here for the new sundials 5 binaries. Hopefully we get there today or tomorrow.

**Comment by giordano** [comment]
https://github.com/JuliaRegistries/General/pull/9310

**Pull request merged**
