### PR TITLE
fixes #12. openspecfun

### LINKED ISSUE #12: openspecfun
Would be nice to move it in here from:

https://github.com/JuliaMath/OpenspecfunBuilder

Maybe that will help address the issues such as https://github.com/JuliaMath/SpecialFunctions.jl/issues/155

### PR DESCRIPTION
**Pull request by ViralBShah**

### CODE REVIEW

**Comment by ViralBShah** [comment]
How do I find out if the builders were able to put everything together? Is there a README with instructions somewhere on how to contribute to this repo, and ensure that everything worked out ok?

**Comment by ViralBShah** [comment]
How do I find out where the binaries produced are, so that we can switch it over in the openspecfun.jl package?

**Comment by staticfloat** [comment]
https://github.com/JuliaPackaging/Yggdrasil/releases/tag/OpenSpecFun-v0.5.3%2B0

**Comment by staticfloat** [comment]
> How do I find out if the builders were able to put everything together

You can't, yet, short of running the BinaryBuilder locally.  At the moment, I just build everything everyone submits here and upload it.

**Pull request merged**
