### PR TITLE
SQLite: New version 3.45.3

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by imciner2** [comment]
So, I realize it has already been this way, but I think we are misconfiguring the Apple builds. Looking at the auditor log, it throws warnings on apple:

> ┌ Warning: Linked library /usr/lib/libedit.3.dylib could not be resolved and could not be auto-mapped
└ @ BinaryBuilder.Auditor /cache/julia-buildkite-plugin/depots/e2fd9734-29d8-45cd-b0eb-59f7104f3131/packages/BinaryBuilder/L8tBh/src/Auditor.jl:397
┌ Warning: Linked library /usr/lib/libncurses.5.4.dylib could not be resolved and could not be auto-mapped
└ @ BinaryBuilder.Auditor /cache/julia-buildkite-plugin/depots/e2fd9734-29d8-45cd-b0eb-59f7104f3131/packages/BinaryBuilder/L8tBh/src/Auditor.jl:397

It looks like it is able to find the `readline` library on apple, just using the command `-lreadline`

> [20:22:57] checking for editline/readline.h... yes
[20:22:57] checking for library containing readline... no
[20:22:57] checking for readline/readline.h... yes

It isn't able to find the `readline` library on Linux, so it isn't building this component and linking it, so we don't get the warnings there. 

Maybe we should add a dependency on `Readline_jll` to get a uniform build config across the platforms? (That will enable it on Linux, and I think make these auditor warnings go away on Apple).

**Comment by eschnett** [comment]
@imciner2 Adding `Readline_jll` did not make the warnings on Apple go away. I notice that the libraries' paths in the warning messages start with`/usr/lib` – this sounds wrong?

**Comment by giordano** [comment]
> this sounds wrong?

The stub libraries in the SDK probably indicate where the real libraries are on the system, including under /usr.

If adding readline doesn't solve the warning anyway maybe you can remove the dep, for the sake of minimising dependencies?

**Comment by eschnett** [comment]
@giordano Done.

**Pull request merged**
