### PR TITLE
[CImGui] Bump version to 1.82

### PR DESCRIPTION
**Pull request by Gnimuc**

### CODE REVIEW

**Comment by Gnimuc** [comment]
ready to merge

**Comment by IanButterworth** [comment]
@Gnimuc this appears to have broken CImGUI for me:

```
UndefVarError: libcimgui_helper not defined
Stacktrace:
 [1] ImGuiIO_Get_BackendFlags
   @ ~/.julia/packages/CImGui/sRsPZ/gen/libhelper_api.jl:10 [inlined]
 [2] getproperty
   @ ~/.julia/packages/CImGui/sRsPZ/src/helper.jl:57 [inlined]
 [3] ImGui_ImplGlfw_Init(window::GLFW.Window, install_callbacks::Bool, client_api::CImGui.GLFWBackend.GlfwClientApi)
   @ CImGui.GLFWBackend ~/.julia/packages/CImGui/sRsPZ/src/backend/GLFW/impl.jl:11
 [4] ImGui_ImplGlfw_InitForOpenGL
   @ ~/.julia/packages/CImGui/sRsPZ/src/backend/GLFW/impl.jl:63 [inlined]
```

**Comment by giordano** [comment]
Fixed by https://github.com/Gnimuc/CImGui.jl/pull/47?

**Comment by IanButterworth** [comment]
Yeah, but I think the reason this broke is I'm on an older CImGui version that didn't have an upper bound for the JLL
https://github.com/Gnimuc/CImGui.jl/blob/db923231c5effcdaa963a120b69eb4d8dc30ddd3/Project.toml#L14

**Comment by IanButterworth** [comment]
As discussed on slack, the Pkg resolver was preferring the new JLL, and downgrading my CImGui.jl version to 1.77 as it was more permissive.

The General registry needs to have retroactive caps added to the old CImGui_jll compat entries

**Comment by Gnimuc** [comment]
https://github.com/JuliaRegistries/General/pull/33621

**Pull request merged**
