### PR TITLE
add GLFW for linux x86_64

### PR DESCRIPTION
**Pull request by colinxs**
Related to JuliaPackaging/Yggdrasil#86. Adds Linux support, but I couldn't get Windows/Mac to build. It's a start at least!

### CODE REVIEW

**Comment by staticfloat** [comment]
Any reason you restrict it to `:x86_64`?

**Comment by colinxs** [comment]
laziness? Running for all Linux arches now :)

**Comment by colinxs** [comment]
Errors so far:
```julia
┌ Error: Hash Mismatch!
│   Expected sha256:   c194e6cca765de557b53b230dfb1c6174982ca093150e63e5d6afc4901af5ede
│   Calculated sha256: 9011df002161b596d6d568a484469bdc76e3095b296595d5af084878f0d174c3
└ @ Pkg.PlatformEngines /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Pkg/src/PlatformEngines.jl:981
ERROR: LoadError: Unable to automatically install 'GCCBootstrap-i686-linux-gnu.v4.8.5.x86_64-linux-musl.unpacked' from '/home/colinxs/workspace/BinaryBuilder.jl/Artifacts.toml' 
```

**Comment by giordano** [comment]
If #86 actually works for Windows and macOS, why not contributing to that builder instead of opening a new conflicting pull request?

**Comment by giordano** [comment]
Closing in favour of #86, I've integrated your changes there.

**Comment by colinxs** [comment]
@giordano I wasn't sure the how to best contribute to #86. Would it have been better to fork SimonDanisch:patch-1 and make a PR to his fork?

**Comment by giordano** [comment]
That's usually what I do :wink:

**Comment by colinxs** [comment]
Sounds good! I'll remember that for the future :)

**Pull request closed without merging**
