### PR TITLE
[Ipopt] Move to C/Coin-OR

### PR DESCRIPTION
**Pull request by odow**
x-ref https://github.com/JuliaPackaging/Yggdrasil/pull/2831.
cc @tkralphs

This moves Ipopt into `C/Coin-OR` to get some consistency between the different COIN solvers.

Not sure about what to do re-versioning. We might need to introduce `300.300.1400` so we can distinguish JLL changes and upstream changes.

The big changes is that it uses MUMPS 4.10 as a BuildDependency, instead of MUMPS 5.2.1 as a Dependency.

This seemed to work locally.
```Julia
julia> model = Model(() -> AmplNLWriter.Optimizer(Ipopt_jll.amplexe))
A JuMP Model
Feasibility problem with:
Variables: 0
Model mode: AUTOMATIC
CachingOptimizer state: EMPTY_OPTIMIZER
Solver name: AmplNLWriter

julia> @variable(model, x, start = 2)
x

julia> @objective(model, Min, 2x^2)
2 x²

julia> optimize!(model)
Ipopt 3.13.4: 

******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit https://github.com/coin-or/Ipopt
******************************************************************************

This is Ipopt version 3.13.4, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:        0
Number of nonzeros in inequality constraint Jacobian.:        0
Number of nonzeros in Lagrangian Hessian.............:        1

Total number of variables............................:        1
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:        0
Total number of inequality constraints...............:        0
        inequality constraints with only lower bounds:        0
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  8.0000000e+00 0.00e+00 8.00e+00  -1.0 0.00e+00    -  0.00e+00 0.00e+00   0
   1  0.0000000e+00 0.00e+00 0.00e+00  -1.0 2.00e+00    -  1.00e+00 1.00e+00f  1

Number of Iterations....: 1

                                   (scaled)                 (unscaled)
Objective...............:   0.0000000000000000e+00    0.0000000000000000e+00
Dual infeasibility......:   0.0000000000000000e+00    0.0000000000000000e+00
Constraint violation....:   0.0000000000000000e+00    0.0000000000000000e+00
Complementarity.........:   0.0000000000000000e+00    0.0000000000000000e+00
Overall NLP error.......:   0.0000000000000000e+00    0.0000000000000000e+00


Number of objective function evaluations             = 2
Number of objective gradient evaluations             = 2
Number of equality constraint evaluations            = 0
Number of inequality constraint evaluations          = 0
Number of equality constraint Jacobian evaluations   = 0
Number of inequality constraint Jacobian evaluations = 0
Number of Lagrangian Hessian evaluations             = 1
Total CPU secs in IPOPT (w/o function evaluations)   =      0.003
Total CPU secs in NLP function evaluations           =      0.000

EXIT: Optimal Solution Found.
```

### CODE REVIEW

**Comment by amontoison** [comment]
@odow I can rebuild MUMPS 5.2.1 as a BuildDependency with static libraries. I should keep a recent release of MUMPS linear solver.

**Comment by amontoison** [comment]
Except v4.0.3, `METIS_jll` has dynamic libraries...
Is it an issue to keep MUMPS 5.2.1 as a dependency ?

**Comment by odow** [comment]
I want to build Bonmin and Couenne, which use both Ipopt and Clp. Currently Clp and Ipopt build with different versions of MUMPS. So we either need to rebuild Clp with MUMPS@5.2.1, or Ipopt with MUMPS@4.10.0. I'll make another PR bumping Clp, and we can decide which one to keep.

**Comment by giordano** [comment]
This needs a rebase now

**Comment by odow** [comment]
This should be fine as a `+N` release. It's mainly just moving the file and unifying some of the `configure` arguments with the rest of the COIN-OR solvers.

**Comment by amontoison** [comment]
Thanks @odow !
MUMPS 5.2.1 has numerous improvements compared to MUMPS 4.1.0.

**Pull request merged**
