### PR TITLE
Bump MParT to 2.1.0

### PR DESCRIPTION
**Pull request by dannys4**

### CODE REVIEW

**Comment by dannys4** [comment]
I think there's a cmake version problem in freeBSD, but I have no idea how to debug this and, tbh, FreeBSD support is much lower for this package vs. fixing bugs for everyone else. If someone has advice, I'd appreciate; otherwise, I'm just going to end FreeBSD support.

**Comment by giordano** [comment]
For the record, the error message is
```
[01:53:40] -- Configuring done
[01:53:40] CMake Error in CMakeLists.txt:
[01:53:40]   Imported target "Kokkos::kokkos" includes non-existent path
[01:53:40] 
[01:53:40]     "/opt/x86_64-unknown-freebsd12.2/x86_64-unknown-freebsd12.2/sys-root/usr/include"
[01:53:40] 
[01:53:40]   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
[01:53:40] 
[01:53:40]   * The path was deleted, renamed, or moved to another location.
[01:53:40] 
[01:53:40]   * An install or uninstall procedure did not complete successfully.
[01:53:40] 
[01:53:40]   * The installation package was faulty and references files it does not
[01:53:40]   provide.
[01:53:40] 
[01:53:40] 
[01:53:40] 
[01:53:40] CMake Error in CMakeLists.txt:
[01:53:40]   Imported target "Kokkos::kokkos" includes non-existent path
[01:53:40] 
[01:53:40]     "/opt/x86_64-unknown-freebsd12.2/x86_64-unknown-freebsd12.2/sys-root/usr/include"
[01:53:40] 
[01:53:40]   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
[01:53:40] 
[01:53:40]   * The path was deleted, renamed, or moved to another location.
[01:53:40] 
[01:53:40]   * An install or uninstall procedure did not complete successfully.
[01:53:40] 
[01:53:40]   * The installation package was faulty and references files it does not
[01:53:40]   provide.
[01:53:40] 
[01:53:40] 
[01:53:40] 
[01:53:40] CMake Error in bindings/julia/CMakeLists.txt:
[01:53:40]   Imported target "Kokkos::kokkos" includes non-existent path
[01:53:40] 
[01:53:40]     "/opt/x86_64-unknown-freebsd12.2/x86_64-unknown-freebsd12.2/sys-root/usr/include"
[01:53:40] 
[01:53:40]   in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
[01:53:40] 
[01:53:40]   * The path was deleted, renamed, or moved to another location.
[01:53:40] 
[01:53:40]   * An install or uninstall procedure did not complete successfully.
[01:53:40] 
[01:53:40]   * The installation package was faulty and references files it does not
[01:53:40]   provide.
```
I believe the problem is related to the recent upgrade of FreeBSD to v13, so the path mentioned above doesn't exist anymore.  I believe this should be fixed by rebuilding Kokkos.

Sorry, I noticed this only now, but https://github.com/dannys4/Yggdrasil/blob/0e41f3390d8d77c4c536f2533b17db44424d5d7f/M/MParT/build_tarballs.jl#L60 should be a [`BuildDependency`](https://docs.binarybuilder.org/stable/reference/#BinaryBuilderBase.BuildDependency) because Eigen it's header-only, it isn't needed at runtime.

**Comment by giordano** [comment]
You should still remove kokkos from here. You have to keep each package in a separate PR

**Comment by dannys4** [comment]
That's fine, but I still need #7126 merged before this will pass anyway

**Comment by dannys4** [comment]
Everything seems to work @giordano, thanks for your help in this.

**Pull request merged**
