### PR TITLE
[Perple_X ] update to version 7.1.9

### PR DESCRIPTION
**Pull request by brenhinkeller**
CC @boriskaus @jadconnolly does this look correct?

### CODE REVIEW

**Comment by boriskaus** [comment]
looks like you forgot to compile `MC_fit`
```
[14:19:35]  ---> for file in ${FilesArray[*]}
[14:19:35]  ---> install -Dvm 755 $file${exeext} "${bindir}/$file${exeext}"
[14:19:35] install: can't stat 'MC_fit': No such file or directory
```

**Comment by brenhinkeller** [comment]
Oh hmm, I was just trying to copy the previous PRs that seem to just bump the version and sha.. did things move internally within the perplex repo or something?

**Comment by boriskaus** [comment]
>  1) am i right that you're gonna leave me to push releases to the julia package manager? that's ok by me and given your previous help i can probably manage, but of course it's fine by me if you intend to continue to do it. 

I would actually prefer if you maintain this, as I'm involved in many other open-source projects and can't always keep up with this. Ofcourse, if @brenhinkeller is happy to help that is fine as well. 

> 2) i made a new release (7.1.9) mainly because i had screwed up the LINUX_makefile so that the precompiled "release asset" was no longer statically linked. because the other corrections were minor, and because i thought the push to the package manager was not automatic, i didn't bother with trying to make the push myself. 

I guess the issue is that as soon as you make a new release of Perple_X, some users would like to incorporate this immediately and compile new binaries. As long make sure that `make all` works, it should be fine. 

> 3) MC_fit is in development and not documented, though it does do some useful things (fitting data, thermobarometry). Given the lack of documentation I don't think it's all that useful to push it to the package manager, but if its presence somewhere (the makefile?) makes that automatic or is causing other problems then tell me and i'll modify whatever needs to be modified. Since I use MC_fit it's an easier for me if i keep it as part of Perple_X, so that's my preference.

In the current `build_tarballs.jl` file, `MC_fit` is [listed](https://github.com/JuliaPackaging/Yggdrasil/blob/f114f44d4b53223c74d250bf4e0aea2e06658d2d/P/Perple_X/build_tarballs.jl#L17) as a file to be compiled. If you just take this out for now, and also comment the library, it won't be included in the BinaryBuilder version.

**Comment by jadconnolly** [comment]
________________________________________

**Comment by brenhinkeller** [comment]
Ah I just have a grad student who's been having issues with gridding on 7.1.8 and was hoping that 7.1.9 would fix that, so I thought I'd try to get the JLL build started -- I've never submitted a yggdrasil PR before though so have even less idea what I'm doing probably!

**Comment by jadconnolly** [comment]
the correction for gridding is only relevant for analyzing 1d gridded minimization done by vertex. if that's the ....ah, i bet it was your student who told me of the problem, so yes it is relevant. 
________________________________________

**Comment by jadconnolly** [comment]
? i just looked at the 7.1.9 "makefile" and it does have the MC_fit target and dependencies. it's not easy for me to do a make on WINDOWS, but i see no reason why "make all" should fail (and that's consistent with the push working for 7.1.8).
________________________________________

**Comment by jadconnolly** [comment]
sorry! i see it now, MC_fit in not in "MYOBJ", i'll push it now.
________________________________________

**Comment by brenhinkeller** [comment]
Looks like we're in business! Thanks so much Jamie!

**Comment by jadconnolly** [comment]
you're very welcome, that bug was a bad one albeit for a special case. 
________________________________________

**Pull request merged**
