### PR TITLE
make libtask compatible with Julia 1.6

### PR DESCRIPTION
**Pull request by KDr2**

### CODE REVIEW

**Comment by KDr2** [comment]
Oh, 1.6/nightly-build is not available now?

**Comment by fingolfin** [comment]
See https://github.com/JuliaPackaging/Yggdrasil/pull/1987

**Comment by fingolfin** [comment]
Problem with that one is that apparently Julia packages and in particular JLLs are not supposed to use the "prerelease" part of a semver version... Which is kind of a pity, as they would be the absolutely natural thing to deal with JLLs bundling prerelease snapshot of software (as done in #1987, and also in a bunch of other JLLs I myself work on). Not to mention the possibility to use it to deal with Julia versions etc. :-(

**Comment by devmotion** [comment]
@giordano @KDr2 It seems libjulia is now available for Julia 1.6, so maybe we can build Libtask_jll for Julia 1.6?

**Comment by giordano** [comment]
Some internal julia structures may have changed?

**Comment by devmotion** [comment]
Probably some additional changes in task.c after the PR was created: [`v1.5.3...v1.6.0`#diff-1ac89047bd](https://github.com/JuliaLang/julia/compare/v1.5.3...v1.6.0#diff-1ac89047bd5ddf49f271321da0d86793efdc534d0edd56548b3ea0dcd2f37c04)

**Comment by giordano** [comment]
Thanks!

**Pull request merged**
