### PR TITLE
[EarCut] Update build_tarballs.jl

### PR DESCRIPTION
**Pull request by anandijain**
m1

### CODE REVIEW

**Comment by vchuravy** [comment]
@staticfloat do I recall correctly that we need a version bump for changes like this?

**Comment by staticfloat** [comment]
Yes, that's correct.  Otherwise, it will get rejected at the registry.

Also, to be a "good Yggdrasil neighbor", please try and follow the commit message style that we typically go for, which is `[$buildername] $commit_message`.  So for something like this, you would write `[EarCut] Enable experimental platforms` or something like that.

**Comment by anandijain** [comment]
sure thing, thanks. what exactly needs a new version and how do I go about getting it tagged?
 
is it https://github.com/SimonDanisch/EarCutBuilder or https://github.com/JuliaGeometry/EarCut.jl?

**Comment by SimonDanisch** [comment]
Haven't gotten around to clean this up in ages, but here it is: https://github.com/JuliaPackaging/Yggdrasil/pull/3580
@anandijain thanks for kickstarting this!

**Pull request closed without merging**
