### PR TITLE
[Singular] update to v4.3.0

### PR DESCRIPTION
**Pull request by tthsqe12**
@thofma

### CODE REVIEW

**Review by thofma — APPROVED** [review]

**Comment by tthsqe12** [comment]
@hannes14 all of the builds are failing like this
```
[13:18:44] feread.cc: In function ‘char* fe_fgets(const char*, char*, int)’:
[13:18:44] feread.cc:313:10: error: ‘mflush’ was not declared in this scope
[13:18:44]    mflush();
```
Do we need to update the configuration step for Singular 4.3.0?

Also, probably unrelated, building the latest spielwiese errors on
```
*** No rule to make target 'weight0.c', needed by 'weight0.lo'. Stop.
```

**Comment by tthsqe12** [comment]
This is definitely a configure issue as I get the exact same error locally inside the kernel directory.
```
feread.cc: In function ‘char* fe_fgets(const char*, char*, int)’:
feread.cc:313:3: error: ‘mflush’ was not declared in this scope; did you mean ‘fflush’?
  313 |   mflush();
```

**Comment by hannes14** [comment]
Am Wed, Jan 19, 2022 at 05:56:54AM -0800 schrieb dan:
>  feread.cc:313:3: error: ‘mflush’ was not declared in this scope; did you mean ‘fflush’?
seems to be missing includes if configured without readline,
git commit bbc293564bf76fcdfdc37354d406b7ca77bc780f of singular shlould
fix it.

**Comment by hannes14** [comment]
Am Wed, Jan 19, 2022 at 05:39:10AM -0800 schrieb dan:
>  *** No rule to make target 'weight0.c', needed by 'weight0.lo'. Stop.
There are leftovers from older builds: "make distclean" should fix it.
weight0.c is now weight0.cc, but somethere are still the old dependencies.

**Comment by tthsqe12** [comment]
@hannes14 thanks, seems to work now.

**Comment by thofma** [comment]
@giordano this is ready to go, thanks!

**Pull request merged**
