### PR TITLE
Add YAJL recipe

### PR DESCRIPTION
**Pull request by christopher-dG**
for use in YAJL.jl

### CODE REVIEW

**Comment by giordano** [comment]
Is this supposed to work on Windows at all?

**Comment by christopher-dG** [comment]
ah yes it should, i need to look at [this](https://github.com/lloyd/yajl/blob/5e3a7856e643b4d6410ddc3f84bc2f38174f2872/BUILDING.win32) evidently.

**Comment by giordano** [comment]
Yes, I'm reading the same file, but I don't think that helps, it's about using Visual Studio

**Comment by giordano** [comment]
I think it's creating broken Makefiles, `/D NDEBUG /O2` makes me think they're hardcoding these flags with `/` instead of `-`

**Comment by giordano** [comment]
https://github.com/lloyd/yajl/blob/5e3a7856e643b4d6410ddc3f84bc2f38174f2872/CMakeLists.txt#L31-L49 :sob:

**Comment by christopher-dG** [comment]
Oh well... I'm just gonna remove Windows then.

**Comment by giordano** [comment]
I have the feeling that we can patch the CMake file to just remove entire W32 branch, it's just wrong

**Comment by giordano** [comment]
And we also already have the patch: https://github.com/msys2/MINGW-packages/blob/2cfdf054df2c826d7c61237ee5ac2453b0f3964d/mingw-w64-yajl/01-fix-compiler.patch

**Comment by christopher-dG** [comment]
oh cool!

**Comment by christopher-dG** [comment]
It works locally now, so all the builds should succeed.

**Comment by giordano** [comment]
I opened a PR upstream to fix the CMake file: https://github.com/lloyd/yajl/pull/228

**Comment by christopher-dG** [comment]
It's very unlikely to be merged i think, development has long since stopped on that repo 😬

**Comment by giordano** [comment]
Oh, I didn't even check the activity :facepalm:

**Pull request merged**
