### PR TITLE
[libsingular-julia]: version v0.2.2

### PR DESCRIPTION
**Pull request by thofma**
@fingolfin: @fieker wants to use the new version now. I think we should not wait for https://github.com/JuliaPackaging/Yggdrasil/pull/1798.

### CODE REVIEW

**Comment by fieker** [comment]
On Tue, Dec 01, 2020 at 02:21:32AM -0800, thofma wrote:
> @fingolfin: @fieker wants to use the new version now. I think we should not wait for https://github.com/JuliaPackaging/Yggdrasil/pull/1798.
> You can view, comment on, or merge this pull request online at:
I'm happy witha local build - if I an figure out how.

**Comment by thofma** [comment]
This PR is good to go.

**Comment by fingolfin** [comment]
@thofma You first commented "this is good to go", then marked this as a draft, so I guess it is not good to go after all?

**Comment by thofma** [comment]
No, there are some issues that need to be resolved (libsingular-julia is fine, but we don't know yet if we need to put in more changes).

**Comment by fingolfin** [comment]
There is of course also PR #1798 which also updates libsingular_julia_jll -- I'd rather continue with that. We could also hold back both that and this PR to wait until we created new FLINT_jll (#2234) and Singular_jll versions and then migrated to them?

**Comment by thofma** [comment]
I am fine with continuing this at #1798. But I don't know how long this will take and how long @fieker wants to wait.

**Pull request closed without merging**
