### PR TITLE
Add swiftshader

### PR DESCRIPTION
**Pull request by serenity4**
Bindings for swiftshader (Vulkan on the CPU). Locally it seemed to work fine, though I got a bunch of warnings for MacOS with linked libraries that could not be resolved and could not be auto-mapped. I don't know the implications of that but I can't test it since I don't have a MacOS. The product is dlopened fine though.

### CODE REVIEW

**Comment by serenity4** [comment]
[ERROR: LoadError: ArgumentError: Platform `x86_64-linux-glibc` is not an officially supported platform](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=8461&view=logs&j=96c13d9d-dfd2-51e5-2f76-4a0b3ce09abc&t=09532434-8b0a-5f0e-118d-a3181cde5ec8&l=29)

What is happening? It is something from `build_tarballs.jl`?

**Comment by serenity4** [comment]
Thanks for the edits!

**Comment by giordano** [comment]
Why you gave up building from source?

**Comment by serenity4** [comment]
I managed to remove the -march=<proc> options, but it was complaining about other missing dependencies that weren't listed in the README, such as X11 and others. Maybe those were from tests that could be disabled, but I didn't have the courage to go through it all, not being very familiar with build systems. I can give it another try though, I'll let you know how it goes.
Is there a significant downside in taking distributed binaries (apart from having less control over the build options)?

**Comment by giordano** [comment]
Ok, let's go this way for the time being.  You can always look into building from source later

>  Is there a significant downside in taking distributed binaries (apart from having less control over the build options)?

You can build for more platforms, if you build from source (provided that it builds cleanly....)

**Pull request merged**
