### PR TITLE
Pixman: New version 0.42.2

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by giordano** [comment]
It fails on aarch64 darwin on compiling some assembly :disappointed:

**Comment by eschnett** [comment]
I disabled the assembly and added a patch with a fallback implementation.

I also enabled OpenMP.

**Comment by bilderbuchi** [comment]
@eschnett I'm not sure if the OS-conditional dependency [here](https://github.com/JuliaPackaging/Yggdrasil/pull/6870/files#diff-c9e93591f4903476772c4bc653da787b32d38e0c6b6cd888f753043b5fc16d02R48-R53) made it into the package successfully.

I'm on Windows, and investigated why I got `LLVMOpenMP_jll` pulled in as a new dependency in a project (turns out: by `Pixman_jll`). And indeed, https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/blob/main/Project.toml lists _both_  `LLVMOpenMP_jll` and `CompilerSupportLibraries_jll` as unconditional dependencies. From your diff linked above, it looks like this could be unintentional?

**Comment by giordano** [comment]
Julia doesn't have conditional dependencies (this makes package resolution easier), they're always installed, but ll openmp is not used on windows, as expected: https://github.com/JuliaBinaryWrappers/Pixman_jll.jl/blob/56299c7b1a77fca2bd5bf979fdefbfe3f74cf3fc/src/wrappers/x86_64-w64-mingw32.jl

**Comment by bilderbuchi** [comment]
Ah, I see, thanks. Coming from [Python](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#platform-specific-dependencies), I did not expect that. 
So some dependencies get _installed_, but _never used_ under some circumstances (e.g. OS), so are essentially ballast/waste (e.g. when using PackageCompiler). Do I understand that correctly?

**Pull request merged**
