### PR TITLE
Wizard recipe: CRLibm-v1.0.0

### PR DESCRIPTION
**Pull request by giordano**
This pull request contains a new build recipe I built using the BinaryBuilder.jl wizard:

* Package name: CRLibm
* Version: v1.0.0

@staticfloat please review and merge.

CC: @dpsanders

### CODE REVIEW

**Comment by dpsanders** [comment]
Wow, fantastic @giordano, thank you for this!

**Comment by dpsanders** [comment]
I take it Windows is still excluded...?

**Comment by giordano** [comment]
Yeah, it fails, but I don't understand why

**Comment by giordano** [comment]
It fails on the following platforms:
 - Windows i686
 - Windows x86_64
 - Linux i686 {libc=musl}
 - Linux x86_64 {libc=musl}
 - Linux i686 {libc=glibc}

**Comment by giordano** [comment]
@dpsanders you only care about the library, right?

**Comment by giordano** [comment]
We'll find out whether this works or not

**Pull request merged**
