### PR TITLE
Wizard recipe: SDL2_mixer-v2.0.4

### PR DESCRIPTION
**Pull request by aviks**
This pull request contains a new build recipe I built using the BinaryBuilder.jl wizard:

* Package name: SDL2_mixer
* Version: v2.0.4

@staticfloat please review and merge.

### CODE REVIEW

**Comment by aviks** [comment]
For the record, this build support FLAC, mpg123 and libvorbis. 

Not supported yet are opus, fluidsynth (MIDI) and libmodplug. IMO, their utility is minor, so should not be a blocker for now. Support can be added after the dependencies are available on here.

**Comment by giordano** [comment]
> Not supported yet are opus, fluidsynth (MIDI) and libmodplug.

We already have opus and libmodplug

**Comment by giordano** [comment]
It needs opusfile, not simply opus, we have only the latter

**Comment by aviks** [comment]
> It needs opusfile, not simply opus, we have only the latter

Yeah, hence #432 (WiP)

**Pull request merged**
