### PR TITLE
SuiteSparse - Use 7.2.1 release from upstream

### PR DESCRIPTION
**Pull request by ViralBShah**
cc @Wimmerer

### CODE REVIEW

**Comment by ViralBShah** [comment]
@Wimmerer @giordano Any suggestions on if we can set these for all platforms?

```
2023-10-03 21:06:13 UTC | [21:06:14] CMake Error: try_run() invoked in cross-compiling mode, please set the following cache variables appropriately:
-- | --
  | 2023-10-03 21:06:14 UTC | [21:06:14]    HAVE_KEYWORD__THREAD_EXITCODE (advanced)
  | 2023-10-03 21:06:14 UTC | [21:06:14]    HAVE_KEYWORD__THREAD_EXITCODE__TRYRUN_OUTPUT (advanced)
  | 2023-10-03 21:06:14 UTC | [21:06:14] For details see /workspace/srcdir/SuiteSparse/CHOLMOD/build/TryRunResults.cmake
```

**Comment by giordano** [comment]
Try run is fundamentally against cross-compilation, since it's trying to run a foreign executable.

**Comment by ViralBShah** [comment]
Yeah. What I wonder is if the cached answers can be used correctly on all platforms. I don't know enough to safely set it to yes.

**Comment by giordano** [comment]
It's _doable_ by using the CMake options mentioned in the error message, but you need to be sure we don't have any weird corner cases.  Hard to tell whether we can have such cases.

**Comment by ViralBShah** [comment]
Not sure what to set it to:
```
2023-10-05 12:43:06 UTC | [12:43:06] CMake Error: Parse error in command line argument: HAVE_KEYWORD__THREAD_EXITCODE
-- | --
  | 2023-10-05 12:43:06 UTC | [12:43:06]  Should be: VAR:type=value
  | 2023-10-05 12:43:06 UTC | [12:43:06]
  | 2023-10-05 12:43:06 UTC | [12:43:06] CMake Error: Run 'cmake --help' for all supported options.
```

**Comment by Wimmerer** [comment]
@DrTimothyAldenDavis, do you know why you're using `try run` here? Try run is pretty much impossible to deal with when cross compiling.

Is this from Markus' changes to the build system?

**Comment by imciner2** [comment]
@Wimmerer see the discussion in the upstream issue (https://github.com/DrTimothyAldenDavis/SuiteSparse/issues/428).

**Comment by Wimmerer** [comment]
Ah okay. Weird that this didn't affect my branch. I didn't think many changes were made between mine and release.

**Comment by ViralBShah** [comment]
@Wimmerer As per the Changelog, SuiteSparse 7.2 had substantial updates to the build system, which is exactly what is problematic here.

**Comment by ViralBShah** [comment]
@giordano  The sanitize build is failing, presumably because these directories may be read only. I suspect all the builds that do the msan+sanitize will probably fail in the same way.

```
2023-10-06 08:31:19 UTC | [08:31:19]  ---> cp -rL ${libdir}/linux/* /opt/x86_64-linux-musl/lib/clang/*/lib/linux/
-- | --
  | 2023-10-06 08:31:19 UTC | [08:31:19] cp: can't create '/opt/x86_64-linux-musl/lib/clang/*/lib/linux/clang_rt.crtbegin-x86_64.o': No such file or directory
  | 2023-10-06 08:31:19 UTC | [08:31:19] cp: can't create '/opt/x86_64-linux-musl/lib/clang/*/lib/linux/clang_rt.crtend-x86_64.o': No such file or directory
  | 2023-10-06 08:31:19 UTC | [08:31:19] cp: can't create '/opt/x86_64-linux-musl/lib/clang/*/lib/linux/libclang_rt.asan-preinit-x86_64.a': No such file or directory
  | 2023-10-06 08:31:19 UTC | [08:31:19] cp: can't create '/opt/x86_64-linux-musl/lib/clang/*/lib/linux/libclang_rt.asan-x86_64.a': No such file or directory
```

**Comment by giordano** [comment]
The msan build is still a work in progress also in  #7358

**Comment by DrTimothyAldenDavis** [comment]
I will post a stable SuiteSparse v7.2.1 today, once the CI finishes. It will be identical to the v7.2.1.beta2 pre-release, except for a one-line change in GraphBLAS/Source/GB_add.c (https://github.com/DrTimothyAldenDavis/SuiteSparse/commit/a5132c0912c0f2e529dfccc6c82d6feddf93422d)

See https://github.com/DrTimothyAldenDavis/SuiteSparse/pull/437

**Pull request merged**
