### PR TITLE
[GR 0.53] Experiment with GR build

### PR DESCRIPTION
**Pull request by ViralBShah**
Carrying out some experiments on the PR in https://github.com/JuliaPackaging/Yggdrasil/pull/2070

@barche Just drawing your attention to this PR.

### CODE REVIEW

**Comment by ViralBShah** [comment]
On armv7, there's a complaint about [libatomic.so not being found](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=7733&view=logs&j=24f8cd14-f3f5-505d-d378-584a8609d754&t=f1acd7c3-a20b-5558-d191-6f54d3b17bda&l=1638). Is this an issue with how Qt is built?

```
[02:46:57] /opt/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/8.1.0/../../../../arm-linux-gnueabihf/bin/ld: warning: libatomic.so.1, needed by /workspace/destdir/lib/libQt5Widgets.so.5.15.1, not found (try using -rpath or -rpath-link)
[02:46:57] /opt/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/8.1.0/../../../../arm-linux-gnueabihf/bin/ld: /workspace/destdir/lib/libQt5Core.so.5.15.1: undefined reference to `__atomic_store_8@LIBATOMIC_1.0'
[02:46:57] /opt/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/8.1.0/../../../../arm-linux-gnueabihf/bin/ld: /workspace/destdir/lib/libQt5Gui.so.5.15.1: undefined reference to `__atomic_fetch_add_8@LIBATOMIC_1.0'
[02:46:57] /opt/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/8.1.0/../../../../arm-linux-gnueabihf/bin/ld: /workspace/destdir/lib/libQt5Core.so.5.15.1: undefined reference to `__atomic_load_8@LIBATOMIC_1.0'
[02:46:57] collect2: error: ld returned 1 exit status
[02:46:57] make[2]: *** [CMakeFiles/gksqt.dir/build.make:179: gksqt] Error 1
```

**Comment by ViralBShah** [comment]
On windows, I bypassed the ZeroMQ build for now, but it is having trouble with libtiff, irrespective of if `tiffflags` is defined or not.

**Comment by ViralBShah** [comment]
@barche I think the libatomic stuff may be a Qt issue. In any case armv7 can be disabled - we don't even ship Julia binaries for it. When we fix the Qt issue, we can re-enable it here. This should get GR 0.53 into BB.

**Comment by ViralBShah** [comment]
@giordano Any idea about how to fix the libatomic issue on armv7?

**Comment by ViralBShah** [comment]
Perhaps `CompilerSupportLibraries_jll` will do the trick 

https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=7435&view=logs&j=7773f650-d868-55ad-7f31-23f9687ad3dd&t=665e94cf-f3ce-522e-ac96-82b99aea4402&l=348520

**Comment by ViralBShah** [comment]
Should we merge?

**Comment by ViralBShah** [comment]
I tried with 1.6 master today, and I am getting this:

```
  Downloaded artifact: GR
 Downloading artifact: GR
┌ Error: Tree Hash Mismatch!
│   Expected git-tree-sha1:   675a7b3f5c39670ec0abaafee3df17a0e854b909
│   Calculated git-tree-sha1: 09bf0efdd598e1fc131b38e28d8e78b82e96a01b
  Downloaded artifact: GR

```

**Comment by giordano** [comment]
See https://github.com/jheinen/GR.jl/issues/360 and https://github.com/JuliaLang/Pkg.jl/pull/2273

**Pull request merged**
