### PR TITLE
coin-or: version bumps and rebuild.

### PR DESCRIPTION
**Pull request by ViralBShah**

### CODE REVIEW

**Comment by ViralBShah** [comment]
Fantastic. It can't now build things that used to build before!

**Comment by giordano** [comment]
I think there are some problems with FreeBSD, see also #2062.  @staticfloat

**Comment by fingolfin** [comment]
This is different from the issue in #2062: The old coin-or binaries did not actually contain FreeBSD binaries, see e.g. https://github.com/JuliaBinaryWrappers/CoinUtils_jll.jl/releases. 

So the simplest fix would to exclude FreeBSD from the platforms list for now.

If you want to get it working, though, I believe there is hope: Most of the failed builds here complain because a JLL *dependency* is missing a FreeBSD artifact. However, to get this working, I think you'll need to submit the JLL updates in sequence, so that each can pick the FreeBSD artifacts from the ones it depends on, as I think (but might be wrong?) that building multiple JLLs in a single PR like that will work (but I might be wrong -- but hopefully @giordano will correct me if I am :-))

Anyway, in the end, I think there is only one genuine build failure, namely for CoinUtils; [log here](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=7175&view=logs&j=c102bc87-f431-5f9b-3a0d-ebbdd024bd8d&t=810e4681-1668-55be-dccb-a7efb154e166). Apparently it boils down to a lack of support for building shared libraries:
```
...
[02:34:30] checking if libtool supports shared libraries... no
[02:34:30] checking whether to build shared libraries... no
...
```
I've not yet bothered to check further, but I note that in `C/Coin-OR/CoinUtils/build_tarballs.jl` we see this:
```
# Without fixing this configure reports that we can't build shared
# libraries. We use `elf64lppc` for LE support. This seems to be
# fixed on master, but using `update_configure_scripts -reconf` breaks.
sed -i s/elf64ppc/elf64lppc/ configure
```
I have no idea what that's about (other than based on the name it's for PowerPC support only?). But in any case: Perhaps a similar workaround is needed for FreeBSD?

**Comment by giordano** [comment]
> The old coin-or binaries did not actually contain FreeBSD binaries, see e.g. JuliaBinaryWrappers/CoinUtils_jll.jl/releases.

I'm confused though: this PR didn't change the platforms, so how come FreeBSD is being built at all?

Ok, now I remember: all these packages have the _old_ `configure` scripts which don't support compiling shared libraries for FreeBSD and PowerPC: https://juliapackaging.github.io/BinaryBuilder.jl/latest/troubleshooting/#Shared-library-not-built.  I think I've complained about these packages shipping _ancient_ `configure` script (+ not providing all the M4 macros needed to update them) uncountable times here.

> I have no idea what that's about (other than based on the name it's for PowerPC support only?). But in any case: Perhaps a similar workaround is needed for FreeBSD?

No, the fix for FreeBSD is much more complicated.  The fix would simply be to regenerate the `configure` script, if only they provided all what is needed to do so.......

**Comment by fingolfin** [comment]
Actually, FreeBSD *was* disabled but this patch is needed to disable it again:
```patch
diff --git a/C/Coin-OR/coin-or-common.jl b/C/Coin-OR/coin-or-common.jl
index 8b304895..6403247d 100644
--- a/C/Coin-OR/coin-or-common.jl
+++ b/C/Coin-OR/coin-or-common.jl
@@ -44,4 +44,4 @@ METIS_packagespec = PackageSpec(; name = "METIS_jll",
 # These are the platforms we will build for by default, unless further
 # platforms are passed in on the command line
 platforms = expand_cxxstring_abis(supported_platforms())
-platforms = [p for p in platforms if !(typeof(p) <: FreeBSD)]
+filter!(!Sys.isfreebsd, platforms)
```

Going beyond that, I ust found your issue https://github.com/coin-or/CoinUtils/issues/117. Ugh, that's nasty :-(.

And yeah, they regenerated the configure script etc. on their `master` branch (ugh again: `configure` script committed to the repo... not so nice, but of course necessary if you mess with the innards of autotools). Even there, one can not just run `autoreconf` because there are still missing macros. AFAICT those are in https://github.com/coin-or-tools/BuildTools (wow, it's even a different GitHub org).

**Comment by fingolfin** [comment]
Fixed that and several related instances in https://github.com/JuliaPackaging/Yggdrasil/pull/2072

**Comment by fingolfin** [comment]
Actually doing #2072 right requires some more work. So I'd suggest to just add the patch I proposed above to this PR.

**Comment by ViralBShah** [comment]
@odow @mlubin A quick note that JuMP dependencies are now updated to use JLLWrappers, which should lead to quicker package loading times - in line with the rest of the ecosystem.

**Comment by odow** [comment]
Thanks team.

**Pull request merged**
