### PR TITLE
Vendor GraphViz config file

### PR DESCRIPTION
**Pull request by Keno**
GraphViz uses a file called `config6` to specify which plugins
are available for loading. Generally, package managers are expected
to run `dot -c` upon installation which will enumerate the plugins
and detect whether they are functional. Without running `dot -c`,
GraphViz will refuse to load any plugins and be essentially
non-functional. In our case, we can't really run `dot -c` for two
reasons:

1. It would write into the artifacts directory, which is a big no-no.
2. It would potentially make errors non-consistent even with the same
   version of the GraphViz_jll, because the availability of features
   would depend on GraphViz's dynamic scan (which shouldn't change,
   but definitely could if external packages are updated).

So to workaround that, ship a generated config6. Unfortunately,
we do probably have to split these out by platform (or at least
by linux/mac/windows), since plugin availability varies between
platforms. I've included the linux one here, since that's the platform
I have easily available. If this direction seems good, I'll add the
other ones (or other people can push whatever they have access to).

### CODE REVIEW

**Comment by giordano** [comment]
Should this work, would it fix #1428?

**Comment by Keno** [comment]
> Should this work, would it fix #1428?

That just looks like `dot` is being run without the env vars to make it find libpango

**Comment by Keno** [comment]
I guess I also missed #1419 so cc @christopher-dG

**Comment by Keno** [comment]
In particular, catlab runs `dot -c` at __init__ time (thus writing into the artifact space that is supposed to be read-only): https://github.com/AlgebraicJulia/Catlab.jl/blob/master/src/graphics/Graphviz.jl#L23, so it's probably a separate issue.

**Comment by giordano** [comment]
Yeah, in the issue you linked above Eliot [suggested](https://github.com/JuliaPackaging/Yggdrasil/pull/1419#discussion_r467319746) to use a scratch space instead

**Comment by Keno** [comment]
Yes, I considered that, but then in order to make the command line programs work, something has to tell them where to find the scratch space, so julia always has to run (so e.g. things like ygg don't work). Plus, I don't think anything is actually gained from running the config on the end user machine. It makes sense when you don't control the dependencies, because who knows that the end users have installed, but in our case, I think we can just vendor it.

**Comment by giordano** [comment]
Alternatively, can we build a `dot-host` binary that can run only on the host and we can use to genereate the config file at the end? I don't know whether that's feasible at all, for example if we basically need to build an entire host graphviz, which would likely be incompatible with the target one.

**Comment by Keno** [comment]
I'm not sure because I don't know enough about what exactly is in this configuration, but I'd expect it to be highly platform dependent, e.g. on OS X there are Quartz renderers that won't be available anywhere else.

**Comment by Keno** [comment]
I added the darwin config file and added the workaround for #3905 and as mention in the issue this should fix #1428 as well, which just needs a rebuild to make the SONAME for bzip2 match up.

**Comment by Keno** [comment]
powerpc, eh?

**Comment by Keno** [comment]
Added windows also while I'm at it. Upstream changes are here: https://gitlab.com/graphviz/graphviz/-/merge_requests/2289

**Comment by Keno** [comment]
Oh hey, windows built. So this depends on #3906 for the moment and I need to go generate the config6 file for windows, but otherwise this should be good to go.

**Comment by Keno** [comment]
Windows binaries have the wrong import name for the dlls (missing the lib prefix), but the build seems good otherwise. Added the config6. Will look at the import name issue in the morning.

**Comment by Keno** [comment]
Ok, added a patch for that issue. Modulo this picking up the libffi fix, this should be good to go.

**Comment by Keno** [comment]
This looks green to me. Let's try it!

**Pull request merged**
