### PR TITLE
Add header files to ranger

### PR DESCRIPTION
**Pull request by tecosaur**
I'm trying to wrap ranger with CxxWrap, and I realised that the header files could be useful.

### CODE REVIEW

**Comment by giordano** [comment]
If you wanted to include header files in the tarball, I don't see them

**Comment by tecosaur** [comment]
Ah, that's a pity to hear (and thanks for having a look). How does one inspect the tarball?

**Comment by giordano** [comment]
The link is at the bottom of all logs: https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=18119&view=logs&j=c477e828-6dc1-5ede-03d3-b8e2be184c34&t=a035ee40-cee9-5999-2d06-38ca99e364f2

**Comment by imciner2** [comment]
@tecosaur are you still wanting to work on this?

**Comment by tecosaur** [comment]
In the end I've found this too difficult to work out for the time I have availible.

**Comment by imciner2** [comment]
Sorry to hear. I'll go ahead and close this PR then.

**Pull request closed without merging**
