### PR TITLE
[GR] Update to v0.58.1

### PR DESCRIPTION
**Pull request by jheinen**
Bump GR run-time version

### CODE REVIEW

**Comment by giordano** [comment]
If you're OK with requiring Julia v1.6 for the JLL package, can we do #2760 instead?

**Comment by jheinen** [comment]
So Julia v1.6 would be the minimum version? Would be OK for us/me, but I don't know what the community thinks about it ...

**Comment by jheinen** [comment]
@giordano : How do you think we should proceed?

**Comment by jheinen** [comment]
It turned out, that there are still some problems with 3d plots. We will first have to fix those problems and then tag a new release ...

**Comment by giordano** [comment]
> How do you think we should proceed?

Unless `GR.jl` depends on some specific features provided by the binary library (and judging by the fact `GR.jl` doesn't specify a compat on `GR_jll` that might not be the case), I think that requiring Julia v1.6 for this JLL wouldn't a big deal: users on Julia v1.5- who want the latest version of the GR library can always use the GR provider, and since `GR.jl` doesn't specify a compat on `GR_jll` the latest version of `GR.jl` can always be installed also by users on Julia v1.5-.

I don't think there are too many users on v1.5-.  Hopefully Julia v1.6 will become the new LTS version, so that requiring v1.6 will be much easier to accept.

**Comment by jheinen** [comment]
@giordano : Please merge this MR. I will add the Julia 1.6 requirement in the next major `GR.jl` release. Thanks!

**Comment by giordano** [comment]
> I will add the Julia 1.6 requirement in the next major GR.jl release.

Note that that will not be enough, you should also incorporate _all_ changes in #2760

**Pull request merged**
