### PR TITLE
[libsingular_julia] for option handling

### PR DESCRIPTION
**Pull request by hannes14**
@fingolfin

### CODE REVIEW

**Comment by giordano** [comment]
This is failing on master: https://buildkite.com/julialang/yggdrasil/builds/11623

**Comment by fingolfin** [comment]
```
┌ Error: Unable to find dependency!
--
  | │   name = "MPFR_jll"
  | │   version = v"4.2.1+0"
  | │   registries =

```
but why?!

**Comment by fingolfin** [comment]
Aha, so MPFR 4.2.1 indeed is not in the General registry. So I guess we need to re-land PR #7376 ?

**Comment by giordano** [comment]
Now I'm extremely confused: how's it possible a version of a jll is in Julia but not registered?

**Comment by giordano** [comment]
This is now working after https://github.com/JuliaRegistries/General/pull/110107: https://buildkite.com/julialang/yggdrasil/builds/11623

**Pull request merged**
