### PR TITLE
fix CoinUtils for PPC

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Comment by vchuravy** [comment]
Do I really need to rebuild the Coin-OR builds 1 by 1? Grrml dependency chains are clunky.

**Comment by vchuravy** [comment]
FreeBSD not working is due to the configure script having a hilarious:

```
freebsd1*)
  dynamic_linker=no
  ;;
```

**Comment by giordano** [comment]
Yes, this happens in `configure` scripts generated by _old_ Autoconf versions: https://github.com/JuliaPackaging/Yggdrasil/wiki/Build-Tricks#shared-library-not-built.  You can find lots my comments around complaining about COIN packages, like in #510 :sweat_smile:

**Comment by vchuravy** [comment]
:P `update_configure_scripts` the docs don't mention `--reconf`.

**Comment by giordano** [comment]
To be honest I didn't know that flag :sweat_smile:   But now we have it: https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/796 :slightly_smiling_face:

**Pull request merged**
