### PR TITLE
NEO: bump to v24.05.28454.6

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
Execution of `ocloc` fails in the cxx03 build, with gdb revealing:

```
free(): invalid pointer

Program received signal SIGABRT, Aborted.
__pthread_kill_internal (threadid=<optimized out>, signo=signo@entry=6) at pthread_kill.c:45
45	pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_internal (threadid=<optimized out>, signo=signo@entry=6) at pthread_kill.c:45
#1  0x00007ffff7a2ed0d in __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at pthread_kill.c:62
#2  0x00007ffff79e4ef2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff79d043c in __GI_abort () at abort.c:79
#4  0x00007ffff7a237b8 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff7b55b22 "%s\n")
    at ../sysdeps/posix/libc_fatal.c:155
#5  0x00007ffff7a37fca in malloc_printerr (str=str@entry=0x7ffff7b53767 "free(): invalid pointer") at malloc.c:5543
#6  0x00007ffff7a3975c in _int_free (av=<optimized out>, p=<optimized out>, have_lock=have_lock@entry=0)
    at malloc.c:4326
#7  0x00007ffff7a3c231 in __GI___libc_free (mem=<optimized out>) at malloc.c:3278
#8  0x00007ffff7d33495 in operator delete (ptr=<optimized out>)
    at /workspace/srcdir/gcc-8.1.0/libstdc++-v3/libsupc++/del_op.cc:49
#9  0x00007ffff7d72fe5 in __gnu_cxx::new_allocator<char>::deallocate (this=<optimized out>, __p=<optimized out>)
    at /workspace/srcdir/gcc_build/x86_64-linux-gnu/libstdc++-v3/include/ext/new_allocator.h:116
#10 0x00007ffff7d73dcd in std::string::_Rep::_M_dispose (__a=..., this=<optimized out>)
    at /workspace/srcdir/gcc_build/x86_64-linux-gnu/libstdc++-v3/include/bits/basic_string.h:3251
#11 std::string::reserve (this=this@entry=0x7fffffffc288, __res=<optimized out>, __res@entry=29)
    at /workspace/srcdir/gcc_build/x86_64-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:961
#12 0x00007ffff7d73ffe in std::string::append (this=this@entry=0x7fffffffc288,
    __s=0x41d878 "cl_khr_byte_addressable_store cl_khr_device_uuid cl_khr_fp16 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_icd cl_khr_local_int32_base_atomics cl_khr_local_int32_extende"...,
    __n=__n@entry=29) at /workspace/srcdir/gcc_build/x86_64-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc:758
#13 0x00007ffff7d4e142 in std::operator>><char, std::char_traits<char>, std::allocator<char> > (__in=..., __str=...)
    at /workspace/srcdir/gcc-8.1.0/libstdc++-v3/src/c++98/istream-string.cc:83
#14 0x00007ffff7e6d838 in NEO::convertEnabledExtensionsToCompilerInternalOptions(char const*, StackVec<_cl_name_version, 27ul, unsigned char>&) () from /workspace/srcdir/compute-runtime/build/bin/libocloc.so
#15 0x00007ffff7eb5c29 in NEO::appendExtensionsToInternalOptions(NEO::HardwareInfo const&, std::string const&, std::string&) () from /workspace/srcdir/compute-runtime/build/bin/libocloc.so
#16 0x00007ffff7f0cb5e in NEO::OfflineCompiler::initialize(unsigned long, std::vector<std::string, std::allocator<std::string> > const&, bool) () from /workspace/srcdir/compute-runtime/build/bin/libocloc.so
#17 0x00007ffff7f0d7bc in NEO::OfflineCompiler::create(unsigned long, std::vector<std::string, std::allocator<std::string> > const&, bool, int&, OclocArgHelper*) () from /workspace/srcdir/compute-runtime/build/bin/libocloc.so
#18 0x00007ffff7efe9a1 in Ocloc::Commands::compile(OclocArgHelper*, std::vector<std::string, std::allocator<std::string> > const&) () from /workspace/srcdir/compute-runtime/build/bin/libocloc.so
#19 0x00007ffff7eeaec8 in oclocInvoke () from /workspace/srcdir/compute-runtime/build/bin/libocloc.so
#20 0x0000000000401093 in main ()
```

... also point to string-related operations.

**Comment by giordano** [comment]
> Execution of ocloc fails in the cxx03 build

Is it basically trying to run a foreign executable?  I don't know what libstdc++ we have in the build environment, if it has supports for both ABIs.

**Comment by maleadt** [comment]
> Is it basically trying to run a foreign executable? I don't know what libstdc++ we have in the build environment, if it has supports for both ABIs.

Ah interesting. Yes, it's executing a foreign binary, and building for musl first doesn't work (and I also don't want to have to deal with supporting musl).

**Comment by maleadt** [comment]
> I don't know what libstdc++ we have in the build environment, if it has supports for both ABIs.

I think it does:

```
sandbox:${WORKSPACE}/srcdir/compute-runtime/build # nm -C /usr/lib/csl-glibc-x86_64/libstdc++.so | grep -w basic_string | grep 'reserve()'
0000000000145400 W std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve()
000000000015b660 W std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::reserve()
00000000000f7880 W          std::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::reserve()
```

i.e. there's both regular and cxx11 symbols in there. Also, wouldn't that otherwise result in a link error?

**Comment by giordano** [comment]
Right, or also if it was only for missing symbols at runtime it have failed to start the process rather than dying during the run? So it's probably not that.

**Pull request merged**
