### PR TITLE
[Qt] Version 5.15, license and dependency fixes

### PR DESCRIPTION
**Pull request by barche**
This supersedes PR  #1162 

Changes:
* Upgrade to 5.15
* Add LGPLv3 license
* Turn all dependencies into `BuildDependency`s

The last point might seem bad, but I compared with the official Qt Linux binaries, and they use a similar mechanism, where all the OpenGL and Xorg stuff comes from the system. This makes sense, since otherwise subtle errors appear. For example, using our own fontconfig at runtime will try to look for a config file in the buildbot root. I also experienced crashes that didn't happen anymore after this change.

### CODE REVIEW

**Comment by giordano** [comment]
> For example, using our own fontconfig at runtime will try to look for a config file in the buildbot root.

https://github.com/JuliaGraphics/Cairo.jl/blob/a591b52ccc809d3179c6cd1dca2eadb947e5986e/src/Cairo.jl#L20-L24 or more simply
```julia
ENV["FONTCONFIG_FILE"] = Fontconfig_jll.fonts_conf
```

**Comment by giordano** [comment]
If we drop all explicit dependencies, this package is not going to work as it is, because you require the user to install them, so.... what's the point of this package? :grimacing:

**Comment by barche** [comment]
> If we drop all explicit dependencies, this package is not going to work as it is, because you require the user to install them, so.... what's the point of this package? 😬

All of these are only for Linux, and if you're running X on Linux, all of these are installed. I have built a local version from the script in this PR and it worked out of the box, without crashes. The fact that the official Qt binaries don't vendor any of these libraries is also a strong indicator that this is the way to go, I think.

**Comment by barche** [comment]
Windows error is due to a bug in GCC 7.1, so I bumped the preferred GCC version to 8.

**Comment by barche** [comment]
But GCC 8 crashes on Linux 😭
```
[ Info: lib/libQt53DQuickExtras.so.5.15.0 already has SONAME "libQt53DQuickExtras.so.5"
[ Info: Checking shared library lib/libQt53DQuickExtras.so.5.15.0
signal (11): Segmentation fault
in expression starting at none:2
unknown function (ip: 0x7f6d2c494462)
_ZN18QThreadStorageDataC1EPFvPvE at /agent/_work/1/s/Q/Qt/build/x86_64-linux-gnu-cxx11/SFfOfyka/destdir/lib/libQt5Core.so.5 (unknown line)
```

See https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=4194&view=logs&j=f64450a0-9594-5c72-e92a-c283b9cc7912

I will try with GCC 9.

**Comment by giordano** [comment]
> But GCC 8 crashes on Linux

You see the error only on the platform because only when building for `x86_64-linux-gnu-cxx11` the auditor tries to dlopen it (because that's the platform of the host, so the only case where the system can actually open it).  If the library can't be dlopened for that platform, there are high chances that there will be problems elsewhere, too.

**Comment by barche** [comment]
Yep, confirmed in the mean time that the segfault happens outside of the build environment when dlopening that library, on both GCC 8 and 9. To make it more interesting, it doesn't segfault with `-debug`, because what fun would debugging be with an actual stacktrace, right?

**Comment by barche** [comment]
OK, so I used GCC8 for Windows and GCC7 for linux, and verified that the resulting Windows library loads. So I think this is good to go, assuming https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/754 is now active on Azure.

**Pull request merged**
