### PR TITLE
[Graphviz][DONOTMERGE] Use upstream mingw changes rather than my patches

### PR DESCRIPTION
**Pull request by Keno**
Upstream requested that we test their version of the mingw support patches,
so I'm putting this up here to run this through our CI and see if everything
builds ok.

### CODE REVIEW

**Comment by giordano** [comment]
Yup, it's all green here.

**Comment by Keno** [comment]
Hah, whoops, our build here finished before upstream's CI of the same changes. Maybe we should seriously think about #3307 again.

**Comment by giordano** [comment]
That's... weird, unless they build serially for all platform, run also tests and have a total one hour wall time?

**Comment by Keno** [comment]
Ok, anyway, since this isn't merged upstream, I'm gonna go ahead and close this and we'll keep using my patch in the meantime. Once upstream merges this and tags a new release, we can just do the version bump as usual, delete the patch and everyone should be happy.

**Pull request closed without merging**
