### PR TITLE
[Openresty] Rebuild to trigger registration

### LINKED ISSUE #2006: Openresty JLL not created
A build_tarballs.jl for OpenResty was submitted and merged at https://github.com/JuliaPackaging/Yggdrasil/pull/1016 but the JLL package doesn't seem to have been generated correctly: https://github.com/JuliaBinaryWrappers/Openresty_jll.jl

### PR DESCRIPTION
**Pull request by giordano**
Fix #2006. CC: @aviks

### CODE REVIEW

**Comment by aviks** [comment]
32 bit builds failing with 

```
[21:25:26] In file included from host/buildvm.c:22:0:
[21:25:26] ./lj_ircall.h:311:2: error: #error "Missing soft-float definitions for target architecture"
[21:25:26]  #error "Missing soft-float definitions for target architecture"
```

This presumably worked in #1016 ? 

cc: @tanmaykm

**Comment by giordano** [comment]
I know what's the problem, but I got caught in other stuff now :joy:

**Comment by aviks** [comment]
Danke! At some point I'll have to learn what this  `lock_microarchitecture` thingy is, but that's for later.

**Comment by giordano** [comment]
With the new microarchitecture stuff we support, by default we don't allow the compiler to set `-march=...`.  Here I checked that it was simply setting `-march=i686` which is ok (we mainly don't want to do stuff like `-march=native` or advanced microarchitectures)

**Pull request merged**
