### PR TITLE
Update FreeBSD support from 11 to 12

### PR DESCRIPTION
**Pull request by ararslan**
FreeBSD 11 will be EOL next month.

### CODE REVIEW

**Comment by ararslan** [comment]
```
ERROR: LoadError: SystemError: opening file "/agent/_work/1/s/B/common.jl": No such file or directory
```
🤔

**Comment by giordano** [comment]
I'm moderately sure the `BaseCompilerShard` package can simply be removed, I have never seen it and I suspect it was replaced by `0_RootFS/Rootfs` and stuff in `BinaryBuilderBase`

**Comment by ararslan** [comment]
Makes sense. I reverted the commit that touched it.

**Comment by ararslan** [comment]
CI is green but tbh I'm not even sure how to interpret that in this case, since CI seems to skip changes to things in `0_RootFS`.

**Comment by DilumAluthge** [comment]
@giordano @staticfloat Is it okay to remove the `DirectorySource("./bundled")`, or will that break something else?

**Comment by giordano** [comment]
No, that should be removed

**Review by giordano — APPROVED** [review]

**Pull request merged**
