### PR TITLE
Sundials: New version 6.6.0

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by ViralBShah** [comment]
In general I find the git method to be convenient because it is easier to update to a new commit for a new release (without downloading and computing the SHA).

**Comment by eschnett** [comment]
I wish there was a way to confirm that a given git commit hash corresponds to a particular version of the package (without downloading and inspecting it).

**Comment by ViralBShah** [comment]
I usually just pick it up from the tagged release of that package on github.

**Comment by eschnett** [comment]
Yes, that's what I do as well. But I'm afraid I might update the version number without updating the commit id, and there's no easy way to check that for consistency...

**Pull request merged**
