### PR TITLE
[aws_c_io] Update to version 0.14.10

### PR DESCRIPTION
**Pull request by quinnj2**
This PR updates aws_c_io to version 0.14.10. cc: @quinnj @Octogonapus

### CODE REVIEW

**Review by giordano — CHANGES_REQUESTED** [review]
@quinnj the version number wasn't changed, my guess is that the regexp isn't matching a two-digit patch number?

**Comment by quinnj** [comment]
yeah, weird. let me look into it

**Comment by quinnj** [comment]
Looks like the aws-c-io version number got messed up somehow to be `v"v0.14.9"` (with the extra v inside the quotes)

**Comment by quinnj** [comment]
PR to fix: https://github.com/JuliaPackaging/Yggdrasil/pull/9059

**Pull request closed without merging**
