### PR TITLE
Wizard recipe: harminvMKL-v1.4.1

### PR DESCRIPTION
**Pull request by platawiec**
This pull request contains a new build recipe I built using the BinaryBuilder.jl wizard:

* Package name: harminvMKL
* Version: v1.4.1

@staticfloat please review and merge.

### CODE REVIEW

**Comment by platawiec** [comment]
I followed the excellent presentation and tried to generate binaries off this script, so consider this an attempt. I actually had some trouble using OpenBLAS, for some reason the compiler wasn't finding it when built with `OpenBLAS_jll`, so I generated this MKL version instead, using only the platforms `MKL_jll` supports. I think it works but the wizard recommended adding `platforms = expand_gfortran_versions(platforms)` though it never gave me an opportunity to do so. Let me know if any changes are needed, and thanks again!

**Comment by giordano** [comment]
> I actually had some trouble using OpenBLAS, for some reason the compiler wasn't finding it when built with OpenBLAS_jll

Yes, sorry, `OpenBLAS_jll` requires some special management because of some name mangling.  It needs to be documented, it's a common problem, but I never got to write it down properly.  If you want to go back to using `OpenBLAS_jll`, I'm happy to guide you.

> though it never gave me an opportunity to do so

And yes, this is one of the few things you simply can't do with the wizard.  You need to manually modify the file to add the line
```julia
platforms = expand_gfortran_versions(platforms)
```
after the definition of `platforms`, as suggested by the warning

**Comment by ViralBShah** [comment]
What needs to be done here?

**Comment by ViralBShah** [comment]
Closing this since we'll soon have LBT as the way to use MKL.

**Pull request closed without merging**
