### PR TITLE
P4est: Support MPItrampoline

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by eschnett** [comment]
I assume that all artefacts are rebuilt when this PR are merged. If so, this PR will automatically require MPItrampoline 5.

**Comment by sloede** [comment]
I don't (yet) understand what was changed, but if it is working towards supporting MPItrampoline I am looking forward to it 👍

However, I think it is a bit unfortunate that the non-existent version `2.8.1` was used to tag this update of the JLL package. Right now it's just confusing, but once the p4est folks tag the actual version 2.8.1 we have a real issue 😞

**Comment by eschnett** [comment]
Mostly I added the bits that make it possible to call `MPI.augment_platforms(platforms)`, which makes it explicit which MPI implementation is used (MPICH, MPItrampoline, OpenMPI).

Since this changes dependencies, it is necessary to increase the version number. That can be necessary for several other reasons as well, and there are many packages which thus don't quite track their upstream version numbers. The latter isn't a requirement – it's more of a convention, with using comments to indicate when the convention doesn't hold. Usually, version numbers sync when the next minor release is made.

**Comment by eschnett** [comment]
And yes, you can now use `P4est` with MPItrampoline from Julia.

**Pull request merged**
