### PR TITLE
Rebuild libcxxwrap_julia against latest libjulia_jll

### PR DESCRIPTION
**Pull request by fingolfin**
Do not merge this just yet, I want to test the macOS binary to see if it actually solves the issues there.

I've incremented the version as otherwise I am not sure we can rely on everybody receiving the fix? But perhaps this is not actually necessary?

CC @barche

### CODE REVIEW

**Comment by fingolfin** [comment]
I've now tested the macOS binaries on my computer, with help of `~/.julia/artifacts/Overrides.toml`, and everything seems to work fine now!

The only thing I am unsure about is whether to change the version (as this PR does not right now) or else leave it... @barche @giordano advice?

**Comment by giordano** [comment]
> The only thing I am unsure about is whether to change the version (as this PR does not right now) or else leave it... @barche @giordano advice?

We're going to decouple the JLL version from the upstream one, so versioning it's mostly up to you.  In particular we want to not use build versions going forward, so the safest option is to bump the patch version.

Other the version number (which looks ok to me), I take this can be merged?

**Comment by fingolfin** [comment]
From my POV it is ready for merging

**Comment by barche** [comment]
OK, since the versions are decoupled now anyway I guess it's most logical to just go ahead and base the JLLs for julia 1.4 and 1.5 also on libcxxwrap-julia 0.8.2?

**Comment by fingolfin** [comment]
@barche they all will be based on the same git commit of libcxxwrap-julia, if you mean that? But that was always the plan, wasn't it?

**Comment by barche** [comment]
Well, I was going to bump the upstream versions in sync, but actually it's better not to. This way, if bugs are fixed we can just update all JLLs. So basically nothing is holding back the creation of the other JLLs now, I think.

**Comment by fingolfin** [comment]
@barche exactly -- see also PR #2106 :-)

**Pull request merged**
