### PR TITLE
[jemalloc] Drop Apple Silicon special case (fixed in 5.3)

### PR DESCRIPTION
**Pull request by jeremiahpslewis**

### CODE REVIEW

**Comment by giordano** [comment]
This shouldn't affect the resulting binary, right?

**Comment by jeremiahpslewis** [comment]
No, fix hard codes 14 on the jemalloc side: https://github.com/jemalloc/jemalloc/commit/7ae0f15c598258610dd3cfd9633301ffa8661c45

**Comment by giordano** [comment]
Ok, and I can confirm the libraries are identical (same sha256 as before).  So I'm going to add `[skip ci]` to avoid rebuilding tarballs needlessly.

**Comment by jeremiahpslewis** [comment]
Thanks!

**Pull request merged**
