### PR TITLE
[LLVM@11] Build for v1.6+ and experimental platforms like aarch64-darwin

### PR DESCRIPTION
**Pull request by staticfloat**

### CODE REVIEW

**Comment by staticfloat** [comment]
It appears our host toolchain for GCC 11 is borked; it can't find its own C++ headers.  A problem for tomorrow.  :)

**Comment by giordano** [comment]
@staticfloat need to update BinaryBuilderBase?

**Comment by staticfloat** [comment]
😮 it didn't rebuild everything!   Are we not tracking BBB hash in our hash calculations?!

**Comment by giordano** [comment]
> Are we not tracking BBB hash in our hash calculations?!

Nope :grimacing:

**Pull request merged**
