### PR TITLE
Download sundials from official github page

### PR DESCRIPTION
**Pull request by ViralBShah**

### CODE REVIEW

**Comment by ViralBShah** [comment]
@giordano Any idea why this is failing only on freebsd?

**Comment by giordano** [comment]
There is no `libsundials_sunlinsolklu` in the products.

**Comment by ViralBShah** [comment]
I couldn't see a build failure, but isn't it in the products: https://github.com/JuliaPackaging/Yggdrasil/blob/78fb3a7b4d00f3bc7fd2b1bcd24e96d6f31d6c4b/S/Sundials/build_tarballs.jl#L58

**Comment by giordano** [comment]
Sorry for the confusion: `libsundials_sunlinsolklu` is an expected product, but the FreeBSD build doesn't seem to be building it.

**Comment by ViralBShah** [comment]
I see, it got disabled in the build
```
CMake Warning at config/SundialsCMakeMacros.cmake:83 (MESSAGE):
[23:56:53]   ------------------------------------------------------------
[23:56:53] 
[23:56:53]   WARNING: KLU not functional - support will not be provided
[23:56:53] 
```

**Comment by ViralBShah** [comment]
Did something change under the hood? Perhaps FreeBSD has new compilers now? I literally changed nothing here but the download URL.

**Comment by giordano** [comment]
The log of the [FreeBSD tarballs](https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/download/Sundials-v3.1.1%2B0/Sundials.v3.1.1.x86_64-unknown-freebsd11.1.tar.gz) of the latest release has:
```
-- Looking for KLU libraries...
-- Checking if KLU works... OK
```
while the log of this build has
```
[23:56:53] -- Looking for KLU libraries...
[23:56:53] -- Checking if KLU works... FAILED
```
I can't build locally also the current builder (without your changes).

**Comment by ViralBShah** [comment]
It is failing even on BLAS in this PR.

**Comment by giordano** [comment]
More than the environment, probably what changed are the dependencies.  _I have a bad feeling about this_

**Comment by giordano** [comment]
These are the test that are failing:
```
sandbox:${WORKSPACE}/srcdir/sundials-3.1.1/build/KLUTest # make V=1
/usr/bin/cmake -S/workspace/srcdir/sundials-3.1.1/build/KLUTest -B/workspace/srcdir/sundials-3.1.1/build/KLUTest --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /workspace/srcdir/sundials-3.1.1/build/KLUTest/CMakeFiles /workspace/srcdir/sundials-3.1.1/build/KLUTest/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/workspace/srcdir/sundials-3.1.1/build/KLUTest'
make -f CMakeFiles/ltest.dir/build.make CMakeFiles/ltest.dir/depend
make[2]: Entering directory '/workspace/srcdir/sundials-3.1.1/build/KLUTest'
cd /workspace/srcdir/sundials-3.1.1/build/KLUTest && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /workspace/srcdir/sundials-3.1.1/build/KLUTest /workspace/srcdir/sundials-3.1.1/build/KLUTest /workspace/srcdir/sundials-3.1.1/build/KLUTest /workspace/srcdir/sundials-3.1.1/build/KLUTest /workspace/srcdir/sundials-3.1.1/build/KLUTest/CMakeFiles/ltest.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/workspace/srcdir/sundials-3.1.1/build/KLUTest'
make -f CMakeFiles/ltest.dir/build.make CMakeFiles/ltest.dir/build
make[2]: Entering directory '/workspace/srcdir/sundials-3.1.1/build/KLUTest'
[ 50%] Linking C executable ltest
/usr/bin/cmake -E cmake_link_script CMakeFiles/ltest.dir/link.txt --verbose=1
/opt/bin/cc -O3 -DNDEBUG  -rdynamic CMakeFiles/ltest.dir/ltest.o  -o ltest -Wl,-rpath,/workspace/destdir/lib /workspace/destdir/lib/libklu.so /workspace/destdir/lib/libamd.so /workspace/destdir/lib/libcolamd.so /workspace/destdir/lib/libbtf.so /workspace/destdir/lib/libsuitesparseconfig.so 
/workspace/destdir/lib/libklu.so: error adding symbols: File in wrong format
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/ltest.dir/build.make:92: ltest] Error 1
make[2]: Leaving directory '/workspace/srcdir/sundials-3.1.1/build/KLUTest'
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/ltest.dir/all] Error 2
make[1]: Leaving directory '/workspace/srcdir/sundials-3.1.1/build/KLUTest'
make: *** [Makefile:87: all] Error 2

sandbox:${WORKSPACE}/srcdir/sundials-3.1.1/build/BlasTest # make V=1
/usr/bin/cmake -S/workspace/srcdir/sundials-3.1.1/build/BlasTest -B/workspace/srcdir/sundials-3.1.1/build/BlasTest --check-build-system CMakeFiles/Makefile.cmake 0
Re-run cmake missing file: CMakeFiles/Makefile.cmake
-- The C compiler identification is Clang 9.0.1
-- Check for working C compiler: /opt/bin/cc
-- Check for working C compiler: /opt/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /workspace/srcdir/sundials-3.1.1/build/BlasTest
/usr/bin/cmake -E cmake_progress_start /workspace/srcdir/sundials-3.1.1/build/BlasTest/CMakeFiles /workspace/srcdir/sundials-3.1.1/build/BlasTest/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/workspace/srcdir/sundials-3.1.1/build/BlasTest'
make -f CMakeFiles/ltest.dir/build.make CMakeFiles/ltest.dir/depend
make[2]: Entering directory '/workspace/srcdir/sundials-3.1.1/build/BlasTest'
cd /workspace/srcdir/sundials-3.1.1/build/BlasTest && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /workspace/srcdir/sundials-3.1.1/build/BlasTest /workspace/srcdir/sundials-3.1.1/build/BlasTest /workspace/srcdir/sundials-3.1.1/build/BlasTest /workspace/srcdir/sundials-3.1.1/build/BlasTest /workspace/srcdir/sundials-3.1.1/build/BlasTest/CMakeFiles/ltest.dir/DependInfo.cmake --color=
Dependee "/workspace/srcdir/sundials-3.1.1/build/BlasTest/CMakeFiles/ltest.dir/DependInfo.cmake" is newer than depender "/workspace/srcdir/sundials-3.1.1/build/BlasTest/CMakeFiles/ltest.dir/depend.internal".
Dependee "/workspace/srcdir/sundials-3.1.1/build/BlasTest/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/workspace/srcdir/sundials-3.1.1/build/BlasTest/CMakeFiles/ltest.dir/depend.internal".
Scanning dependencies of target ltest
make[2]: Leaving directory '/workspace/srcdir/sundials-3.1.1/build/BlasTest'
make -f CMakeFiles/ltest.dir/build.make CMakeFiles/ltest.dir/build
make[2]: Entering directory '/workspace/srcdir/sundials-3.1.1/build/BlasTest'
[ 50%] Building C object CMakeFiles/ltest.dir/ltest.o
/opt/bin/cc   -O3 -DNDEBUG   -o CMakeFiles/ltest.dir/ltest.o   -c /workspace/srcdir/sundials-3.1.1/build/BlasTest/ltest.c
[100%] Linking C executable ltest
/usr/bin/cmake -E cmake_link_script CMakeFiles/ltest.dir/link.txt --verbose=1
/opt/bin/cc -O3 -DNDEBUG  -rdynamic CMakeFiles/ltest.dir/ltest.o  -o ltest -L/workspace/destdir/lib -lopenblas64_ 
/opt/x86_64-unknown-freebsd11.1/bin/x86_64-unknown-freebsd11.1-ld: warning: libgfortran.so.5, needed by /workspace/destdir/lib/libopenblas64_.so, not found (try using -rpath or -rpath-link)
/opt/x86_64-unknown-freebsd11.1/bin/x86_64-unknown-freebsd11.1-ld: warning: libquadmath.so.0, needed by /workspace/destdir/lib/libopenblas64_.so, not found (try using -rpath or -rpath-link)
/workspace/destdir/lib/libopenblas64_.so: undefined reference to `_gfortran_etime@GFORTRAN_8'
/workspace/destdir/lib/libopenblas64_.so: undefined reference to `_gfortran_pow_r4_i8@GFORTRAN_8'
/workspace/destdir/lib/libopenblas64_.so: undefined reference to `_gfortran_pow_r8_i8@GFORTRAN_8'
/workspace/destdir/lib/libopenblas64_.so: undefined reference to `_gfortran_concat_string@GFORTRAN_8'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/ltest.dir/build.make:87: ltest] Error 1
make[2]: Leaving directory '/workspace/srcdir/sundials-3.1.1/build/BlasTest'
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/ltest.dir/all] Error 2
make[1]: Leaving directory '/workspace/srcdir/sundials-3.1.1/build/BlasTest'
make: *** [Makefile:87: all] Error 2
```
It looks like that `libklu.so` from SuiteSparse is a Linux library:
```
sandbox:${WORKSPACE}/srcdir/sundials-3.1.1/build/BlasTest # file $(readlink -f ${libdir}/libklu.so)
/workspace/artifacts/fdba4a644d55ce87a020047d38fd91fa3f92703b/lib/libklu.so.1.3.8: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, not stripped
sandbox:${WORKSPACE}/srcdir/sundials-3.1.1/build/BlasTest # ldd $(readlink -f ${libdir}/libklu.so)
        linux-vdso.so.1 (0x00007ffc6cf2c000)
        libm.so.5 => not found
        libamd.so.2 => /workspace/destdir/lib/libamd.so.2 (0x00007f8161e27000)
        libcolamd.so.2 => /workspace/destdir/lib/libcolamd.so.2 (0x00007f8161c1f000)
        libbtf.so.1 => /workspace/destdir/lib/libbtf.so.1 (0x00007f8161a1b000)
        libsuitesparseconfig.so.5 => /workspace/destdir/lib/libsuitesparseconfig.so.5 (0x00007f8161819000)
        libc.so.7 => not found
        libm.so.5 => not found
        libc.so.7 => not found
        libm.so.5 => not found
        libc.so.7 => not found
        libm.so.5 => not found
        libc.so.7 => not found
        libm.so.5 => not found
        libc.so.7 => not found
```

**Comment by ViralBShah** [comment]
What about the BLAS failure? Is that also a linux library?

**Comment by ViralBShah** [comment]
Should we just re-trigger SuiteSparse build?

**Comment by giordano** [comment]
> What about the BLAS failure? Is that also a linux library?

No, it's a FreeBSD one:

```
sandbox:${WORKSPACE}/srcdir/sundials-3.1.1/build/BlasTest # file $(readlink -f ${libdir}/libopenblas64_.so)
/workspace/artifacts/59a2637ff411b95919a39db5dcc1c94337c73933/lib/libopenblas64_.0.3.7.so: ELF 64-bit LSB shared object, x86-64, version 1 (FreeBSD), dynamically linked, not stripped
```

but there is a mismatch between the expected libgfortran version (v5) and the one available in the environment (v3):

```
sandbox:${WORKSPACE}/srcdir/sundials-3.1.1/build/BlasTest # ${target}-objdump -x $(readlink -f ${libdir}/libopenblas64_.so) | grep NEEDED
  NEEDED               libgfortran.so.5
  NEEDED               libm.so.5
  NEEDED               libquadmath.so.0
  NEEDED               libc.so.7
  NEEDED               libthr.so.3
sandbox:${WORKSPACE}/srcdir/sundials-3.1.1/build/BlasTest # qfind / -name "libgfortran.so*"
/workspace/mounts/GCCBootstrap-x86_64-unknown-freebsd11.1.v4.8.5.x86_64-linux-musl.squashfs/x86_64-unknown-freebsd11.1/lib/libgfortran.so
/workspace/mounts/GCCBootstrap-x86_64-unknown-freebsd11.1.v4.8.5.x86_64-linux-musl.squashfs/x86_64-unknown-freebsd11.1/lib/libgfortran.so.3
/workspace/mounts/GCCBootstrap-x86_64-linux-musl.v4.8.5.x86_64-linux-musl.squashfs/x86_64-linux-musl/lib64/libgfortran.so
/workspace/mounts/GCCBootstrap-x86_64-linux-musl.v4.8.5.x86_64-linux-musl.squashfs/x86_64-linux-musl/lib64/libgfortran.so.3
/workspace/mounts/GCCBootstrap-x86_64-linux-musl.v4.8.5.x86_64-linux-musl.squashfs/x86_64-linux-musl/lib64/libgfortran.so.3.0.0
/opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/lib/libgfortran.so
/opt/x86_64-unknown-freebsd11.1/x86_64-unknown-freebsd11.1/lib/libgfortran.so.3
/opt/x86_64-linux-musl/x86_64-linux-musl/lib64/libgfortran.so
/opt/x86_64-linux-musl/x86_64-linux-musl/lib64/libgfortran.so.3
/opt/x86_64-linux-musl/x86_64-linux-musl/lib64/libgfortran.so.3.0.0
```

I assume we need to use `expand_gfortran_version` here.

> Should we just re-trigger SuiteSparse build?

I'm trying to figure out what went wrong there.

**Comment by ViralBShah** [comment]
Do we then need `expand_libgfortran` in SuiteSparse as well (anything that links to BLAS and LAPACK)?

**Comment by giordano** [comment]
Honestly I'm not sure.  I think @staticfloat will have a look to all the issues here.

**Comment by ViralBShah** [comment]
safe to merge?

**Comment by staticfloat** [comment]
wait, it worked?

**Comment by giordano** [comment]
Ok, rebuilding METIS (#370) and SuiteSparse (#371) solved the issues with weird FreeBSD libraries.

A working BLAS can't be found on FreeBSD, but also on most of other platforms.  Not sure this is a problem in practice: also many in the [current release](https://github.com/JuliaBinaryWrappers/Sundials_jll.jl/releases/tag/Sundials-v3.1.1%2B0) many platforms weren't built against BLAS.

**Comment by ViralBShah** [comment]
The LAPACK won't work (too many 32-bit assumptions for 64-bit BLAS and will need the move to sundials 5). The BLAS I will try to see if it does, but perhaps without LAPACK it is not valuable.

**Comment by giordano** [comment]
BTW, OpenBLAS troubles here looks related with https://github.com/JuliaPackaging/Yggdrasil/pull/368#issuecomment-572252321.

**Pull request merged**
