### PR TITLE
Split X11 builder in separate builders

### PR DESCRIPTION
**Pull request by giordano**
I created the new builders with [this script](https://gist.github.com/giordano/649a0e4db081f0e0931e98c1e8753b4d).  I need to fix all the libs, in particular the products and their dependencies, which is quite tricky as I need the registered packages to properly test.

### CODE REVIEW

**Comment by staticfloat** [comment]
My goodness.  What do you mean you need to fix all the libs?  Also, do you think we should name these `x11_<name>` or something to make it more clear that they belong to X11?

**Comment by giordano** [comment]
> What do you mean you need to fix all the libs?

Mostly that I need to set the dependencies and the list of products

> Also, do you think we should name these x11_<name> or something to make it more clear that they belong to X11?

I don't have a strong opinion about this, but this might be a good idea. Actually, I've already done this in one case: xorg_util_macros instead of util_macros (many Linux distros do the same for this package)

**Comment by staticfloat** [comment]
Okay, let's go ahead and rename them all to have an `x11` in front.

**Comment by giordano** [comment]
What about `xorg_*` instead?  Xorg is the specific implementation of X11 that we're providing: https://unix.stackexchange.com/a/14087/40264

**Comment by staticfloat** [comment]
Even better.

**Comment by giordano** [comment]
Renamed.  The protos should be ready to publish right away

**Comment by giordano** [comment]
Have fun :slightly_smiling_face:

**Comment by staticfloat** [comment]
Ohhhh boy.  I think I'm gonna have to leave this for later this week, when I need something mindless to do for a few hours.  :P

**Pull request merged**
