### PR TITLE
Build a separate SuiteSparse32 with 32-bit OpenBLAS

### PR DESCRIPTION
**Pull request by christopher-dG**
Prerequisite for #995 

I followed a similar pattern as OpenBLAS's multiple builds. Only tested builds on x86_64-linux-gnu, so we'll see how the other platforms work.

unrelated: it's very nice that the CI you guys have set up here is smart enough to recognize that there are now multiple packages to build

### CODE REVIEW

**Comment by giordano** [comment]
I think here we have a problem of name clash of the shared library.  For OpenBLAS, the 32-bit version is always called `libopenblas` and the the 64-bit is always called `libopenblas64_`.  Here the shared libraries will always have the same names, so that only the 64-bit versions built into Julia will be ever used

**Comment by christopher-dG** [comment]
Ah, so in SuiteSparse32, the shared objects should be suffixed with `32` or something?

**Comment by giordano** [comment]
I think so, yes

**Comment by staticfloat** [comment]
Note that it's not just the filename, you actually need the SONAME to be different; so just a `mv` won't be enough; you'll need to either alter the build invocation/patch the build scripts to use a different SONAME, or you'll have to use `patchelf`/`install_name_tool` to fix it up on Linux, FreeBSD and MacOS.

**Comment by giordano** [comment]
Doesn't audit do this automatically?

**Comment by staticfloat** [comment]
Well, it will, but that audit pass assumes that everything is linked together properly.  So if you have `libsuitesparse.so` and `libklu.so`, and `libsuitesparse` depends on `libklu`, but you've moved `libklu` to `libklu64_`, it won't properly rename the dependency within `libsuitesparse` to point to `@rpath/libklu64_.so`; it will just say that it couldn't find `libklu.so`.

Also, I think you should call it `libklu64_.so` instead of `libklu32.so`, for the same reasons that we do so for OpenBLAS.  If some outside library gets linked in, we want them to find the 32-bit symbols by default.

Also, I just realized that just like the OpenBLAS case, you're going to need to re-name all the symbols within this library to not conflict as well.  :scream:

**Comment by christopher-dG** [comment]
oh boy... 😅 

Alright so renaming the files seems to be the easy part, just moving files and fixing symlinks afterwards.

But before that I need to suffix the symbols... I don't think that SuiteSparse has a nice `SYMBOLSUFFIX` option like OpenBLAS does, so do I need to write out all the symbols by hand and do `-Dsym=sym64_` before building, or is there a better way? Can I do it after the build somehow with `objcopy` or something?

Setting the SONAME seems pretty straightforward with `patchelf`/`install_name_tool`. 

The rpath stuff isn't super clear to me (I'll admit, I had never heard of this term last week).
If I do something like `readelf -d libsuitesparse_wrapper.so`, I get, among other things:

```
0x000000000000000e (SONAME)             Library soname: [libsuitesparse_wrapper.so]
0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN]
0x0000000000000001 (NEEDED)             Shared library: [libcholmod.so.3]
0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```

So it would appear that to load this library, I need to have a `libcholmod.so.3`, but if I've moved that to `libcholmod64_.so.3`, then it won't be found. So would I need to do something like `patchelf --replace-needed` to rename all the libraries that are part of SuiteSparse (aka not replacing the libc entry)?

**Comment by staticfloat** [comment]
> but if I've moved that to libcholmod64_.so.3, then it won't be found.

Yes, precisely.  I suggest not doing this after the fact, and instead patching the buildsystem to change the library names.  It will be a lot simpler than figuring out how to patch the binaries for all the different platforms.

While you're at it, patching the buildsystem to have different symbol names is probably the right way to go as well.  Let's try the `-Dsym=sym64_` approach and see if it works.

**Comment by christopher-dG** [comment]
> It will be a lot simpler than figuring out how to patch the binaries for all the different platforms.

Yeah I'm finding this out myself... 🙃

**Comment by giordano** [comment]
Hold on, you aren't renaming the symbols in the 32-bit libraries, are you?

**Comment by christopher-dG** [comment]
This isn't quite done yet but I've almost got the symbol renaming figured out. Renaming only happens on 64-bit, the suffix for files and symbols is `64_`.

**Comment by giordano** [comment]
> Renaming only happens on 64-bit, the suffix for files and symbols is 64_.

Maybe it's better to suffix the 32-bit version, since the one used by Julia is the 64-bit and doesn't currently have any suffix?

**Comment by christopher-dG** [comment]
I'm doing what Elliot said to do 🙃

**Comment by christopher-dG** [comment]
Alright so I feel like I did this in a pretty awkward way, but... it compiles and seems to do what we want.

I collected the symbols from all the libraries by first building it with no renaming, then running `nm -D` on all the libraries, and taking just the names of the `T` entries. At that point, CHOLMOD was complaining about some undefined symbols which were internal, prefixed versions of exported functions (for some reason they didn't show up anywhere in `nm -a`). They're created by some preprocessor magic which is basically the C equivalent of:

```jl
for prefix in (:c, :r, :p, :z)
    @eval $(prefix)_cholmod_XXX(...) = ...
end
```

...where `cholmod_XXX` was something already in our rename list. I think the the prefixed functions were then being defined with our suffix because the symbol passed to the macro was being suffixed. So to solve that, I just put all those prefixed functions in the rename file too.

**Comment by christopher-dG** [comment]
Bump, I think this needs the @staticfloat seal of approval 🙂

**Comment by staticfloat** [comment]
Great!  This is more or less what I was looking for.  One more thing though; we need to change Julia's from-source build to do roughly the same thing.  :)

**Comment by staticfloat** [comment]
To be slightly more verbose, what I mean is that these renaming steps/patches need to be integrated into [`deps/suitesparse.mk`](https://github.com/JuliaLang/julia/blob/master/deps/suitesparse.mk), then julia needs to be built with `USE_BINARYBUILDER_SUITESPARSE=0` to ensure that this actually works with Julia.

**Comment by giordano** [comment]
Raising also here a concern I have: if we're going to change the name of the 64-bit library, we'll quickly need to rebuild all packages depending on `SuiteSparse_jll`.  Also, the change of the name is not really backportable, so we'll have a situation where in Julia v1.4- (or 1.5- if this doesn't make it for v1.5) `libFOO` is the 64-bit version, so `SuiteSparse32_jll` will have all of its products shadowed by the 64-bit libraries built in Julia and loading `SuiteSparse_jll` will load a second 64-bit SuiteSparse with a different name than the default one.

**Comment by christopher-dG** [comment]
I think we're going for a less intrusive approach: https://github.com/JuliaPackaging/Yggdrasil/pull/995#issuecomment-630915300

**Comment by jd-lara** [comment]
@giordano and @christopher-dG what's the plan here? Still make a SuiteSparse32 or build SuiteSparse inside of the Sundials build like it was before?

**Comment by christopher-dG** [comment]
I think this is what we want: https://github.com/JuliaPackaging/Yggdrasil/pull/995#issuecomment-630968990

So either a minimal SuiteSparse32 JLL or just built in the Sundials builder.

**Comment by christopher-dG** [comment]
Closing this in favour of something else

**Pull request closed without merging**
