### PR TITLE
Build LLVM libs 16.0.6+3

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Comment by giordano** [comment]
@vchuravy @gbaraldi this is failing (but the `2> /dev/null` doesn't help much with knowing what's the problem).

**Comment by gbaraldi** [comment]
I struggled just a bit to come up with something not awful for this, and it's pretty awful, but it seems to work correctly

**Comment by vchuravy** [comment]
I think we could also do extraction scripts that are per version

**Comment by gbaraldi** [comment]
We have those for MLIR, but I think this seems to pretty ok, it at least works for llvm 15 and 16 for me

**Pull request merged**
