### PR TITLE
Wizard recipe: libsharp-v1.0.0

### PR DESCRIPTION
**Pull request by eschnett**
This pull request contains a new build recipe I built using the BinaryBuilder.jl wizard:

* Package name: libsharp
* Version: v1.0.0

@staticfloat please review and merge.

### CODE REVIEW

**Comment by eschnett** [comment]
This is a recipe for the libsharp https://github.com/Libsharp/libsharp library that calculates spin-weighted spherical harmonics. This provides a subset of the (unfortunately outdated) https://github.com/mweastwood/LibHealpix.jl .

The respective build worked on my laptop. Can you assist me in debugging these failures? I don't understand the error messages.

Another questions: I disabled `-march=native` in the build because I saw a warning in the output. Is this necessary, or should I re-enable it?

**Comment by giordano** [comment]
Is it the same as https://github.com/JuliaPackaging/Yggdrasil/blob/master/L/libsharp2/build_tarballs.jl?

**Comment by ziotom78** [comment]
@giordano , it's the same library, but @eschnett is providing bindings for the older version of the library (https://github.com/Libsharp/libsharp), while my implementation is based on a more recent branch (https://gitlab.mpcdf.mpg.de/mtr/libsharp).

@eschnett, if you're interested, @xzackli and I are working to provide high-level implementations of `map2alm` and `alm2map` in [Healpix.jl](https://github.com/ziotom78/Healpix.jl): see [this PR](https://github.com/ziotom78/Healpix.jl/pull/21) (in progress).

**Comment by eschnett** [comment]
@giordano It isn't, but that library seems sufficiently close that I'll be using it instead. I will close my pull request.

`Healpix.jl` is quite interesting, and definitively the way to go for the future. I am very much looking forward to being able to use more advanced types (`BigFloat`, or dual numbers, etc.). But at the moment I'm looking for a stop-gap solution only. Thanks for the pointer to the PR!

**Pull request closed without merging**
