### PR TITLE
Add qttools builder

### PR DESCRIPTION
**Pull request by clad26**
Again, incomplete!
@giordano Do you happen to have any experience with qmake?👀

### CODE REVIEW

**Comment by clad26** [comment]
@giordano I don't seem to get the error
Can you take a look?

**Comment by giordano** [comment]
https://github.com/JuliaPackaging/Yggdrasil/blob/e342947ac056aca9dff222c42d99b8d703462711/G/Gnuplot/build_tarballs.jl#L16-L17

**Comment by clad26** [comment]
> https://github.com/JuliaPackaging/Yggdrasil/blob/e342947ac056aca9dff222c42d99b8d703462711/G/Gnuplot/build_tarballs.jl#L16-L17

Should I add this?😅😅

**Comment by clad26** [comment]
@giordano 
```
[20:38:22]  ---> qmake PREFIX=${prefix}
[20:38:22] /bin/bash: line 38: qmake: command not found
[20:38:22]  ---> qmake PREFIX=${prefix}
[20:38:22] Previous command exited with 127
[20:38:22] Child Process exited, exit code 127
ERROR: LoadError: Build for Qttools on aarch64-linux-musl did not complete successfully

```

Huhh....
Is it anyhow related to 
```
##[warning]Dependency Qt_jll does not have a mapping for artifact Qt for platform Linux aarch64 {cxxstring_abi=cxx11, libc=musl, libgfortran_version=5.0.0}
```
???

**Comment by clad26** [comment]
I'm lost 
@giordano Any ideas?

**Comment by clad26** [comment]
Any chance it might be "making" into the wrong directory？

**Comment by ViralBShah** [comment]
@barche Do we install `qmake` as part of `Qt_jll`?

**Comment by ViralBShah** [comment]
IIRC, musl is not supported for Qt_jll. So you should use the same platforms as Qt_jll - but that is not the reason for this failure.

**Comment by clad26** [comment]
> @barche Do we install `qmake` as part of `Qt_jll`?

I think so... qmake actually runs when I include Qt_jll as a dependency

**Comment by ViralBShah** [comment]
Maybe disable qdoc and see if you can go further for now?

**Comment by clad26** [comment]
Yeah as long we've linguist, gnuplot is good to go
The problem is, how do I disable/skip qdocs in src？

**Comment by ViralBShah** [comment]
I think qdoc may not be sufficient to bypass. The others are failing with ELF relocation errors and such. Perhaps some link flags from the BB environment that need passing.

**Comment by clad26** [comment]
@giordano @staticfloat might help！

**Comment by ViralBShah** [comment]
I think we may need to use the [QMAKE_LDFLAGS](https://github.com/JuliaPackaging/Yggdrasil/blob/3dbfd6db265cc2eeae52a2f82c6f373e13093917/Q/Qt/build_tarballs.jl#L106) that are used in the Qt build recipe.

**Comment by clad26** [comment]
> I think qdoc may not be sufficient to bypass. The others are failing with ELF relocation errors and such. Perhaps some link flags from the BB environment that need passing.

@giordano @staticfloat any ideas？

**Comment by clad26** [comment]
I was looking at https://github.com/JuliaPackaging/Yggdrasil/blob/cb91198f697d1d6266535ebbb8a62d6c8e0c8fe0/Q/Qt/build_tarballs.jl

```
commonoptions=" \
-opensource -confirm-license \
-skip qtactiveqt -skip qtandroidextras -skip qtcanvas3d -skip qtconnectivity -skip qtdatavis3d -skip qtdoc -skip qtgamepad \
-skip qtnetworkauth -skip qtpurchasing -skip qtremoteobjects -skip qtscript -skip qtscxml -skip qtsensors -skip qtserialbus \
-skip qtserialport -skip qtspeech -skip qtvirtualkeyboard -skip qtlocation -skip qtwayland -skip qtwebchannel -skip qtwebengine \
-skip qtwebglplugin -skip qtwebsockets -skip qtwebview  -skip qttools  -openssl-linked  -nomake examples -release \
"
```

Can someone try the same script, just removing ``` -skip qttools  ``` ?

**Comment by clad26** [comment]
> I was looking at https://github.com/JuliaPackaging/Yggdrasil/blob/cb91198f697d1d6266535ebbb8a62d6c8e0c8fe0/Q/Qt/build_tarballs.jl
> 
> ```
> commonoptions=" \
> -opensource -confirm-license \
> -skip qtactiveqt -skip qtandroidextras -skip qtcanvas3d -skip qtconnectivity -skip qtdatavis3d -skip qtdoc -skip qtgamepad \
> -skip qtnetworkauth -skip qtpurchasing -skip qtremoteobjects -skip qtscript -skip qtscxml -skip qtsensors -skip qtserialbus \
> -skip qtserialport -skip qtspeech -skip qtvirtualkeyboard -skip qtlocation -skip qtwayland -skip qtwebchannel -skip qtwebengine \
> -skip qtwebglplugin -skip qtwebsockets -skip qtwebview  -skip qttools  -openssl-linked  -nomake examples -release \
> "
> ```
> 
> Can someone try the same script, just removing `-skip qttools ` ?

If that works, we might not even need this PR... 
To be honest, on the developer's side, I think the above is more efficient to maintain
On the user's side, he/she can just skip qttools if he doesn't need it, if we make a separate JLL for qttools like this

**Comment by giordano** [comment]
I keep saying that I don't think cross-compiling gnuplot is going to be straightforward.  We need the `lrelease` binary for the host, not the target.  This recipe is mostly useless for your goal

**Comment by clad26** [comment]
@giordano can you suggest some changes？😅
Even I used BB for the first time yesterday so....

**Comment by clad26** [comment]
Don't we just need the lrelease binary in the bin folder, which building qttools will give us？

**Comment by clad26** [comment]
> I keep saying that I don't think cross-compiling gnuplot is going to be straightforward.  We need the `lrelease` binary for the host, not the target.  This recipe is mostly useless for your goal

Does that mean we need the equivalent of --host and --target for qmake？

**Comment by barche** [comment]
I skipped `qttools` on the Qt build because I think it wasn't needed. Seems to me that the most logical way to get it would be to simply enable it in the Qt package. In the long run, splitting up the Qt package into components as the linux distributions do may be the way forward, though.

**Comment by giordano** [comment]
Closing this to reduce the noise, my understanding is that we aren't going to follow this path at the moment: https://github.com/JuliaPackaging/Yggdrasil/issues/2252#issuecomment-753684360

**Pull request closed without merging**
