### PR TITLE
Bump `Git` version

### LINKED ISSUE #1063: Git_jll fails with PCRE2 error
```
julia> git() do git
       readchomp(`$(git) --help`)
       end
dyld: Library not loaded: @rpath/libpcre2-8.0.dylib
  Referenced from: /Users/sabae/.julia/artifacts/592d01a4f901d3676d38410fd6520d335612c691/bin/git
  Reason: Incompatible library version: git requires version 10.0.0 or later, but libpcre2-8.0.dylib provides version 8.0.0
```

It looks like the libpcre that is bundled with Julia 1.4 is incompatible with the libpcre that git is trying to load.

### PR DESCRIPTION
**Pull request by staticfloat**
Fixes #1063, fixes https://github.com/JuliaBinaryWrappers/Git_jll.jl/issues/2

### CODE REVIEW

**Comment by omus** [comment]
Are we sure this is fixed? I'm still seeing the exact same error I reported in https://github.com/JuliaBinaryWrappers/Git_jll.jl/issues/2 with `Git_jll@2.27.0`

**Comment by giordano** [comment]
I can't test because I can't reproduce this issue on GNU/Linux, but https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/824 was meant to address this issue, and that change had been propagated to all packages involved.  This was the last package that needed to be updated to get the effect of https://github.com/JuliaPackaging/BinaryBuilder.jl/pull/824

**Comment by staticfloat** [comment]
It turns out we actually need JuliaPackaging/BinaryBuilder.jl#825 as well.  I'll do another rebuild.

**Comment by staticfloat** [comment]
Alright, confirmed fixed now. :)

**Pull request merged**
