### PR TITLE
[unixODBC] 2.3.12

### PR DESCRIPTION
**Pull request by ViralBShah**
Windows build recipe: https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-unixodbc/PKGBUILD

### CODE REVIEW

**Comment by ViralBShah** [comment]
```

2024-11-06 23:58:11 EST | [04:58:11] __handles.c: In function ‘pool_timedwait’:
-- | --
  | 2024-11-06 23:58:11 EST | [04:58:11] __handles.c:1911:5: warning: implicit declaration of function ‘clock_gettime’ [-Wimplicit-function-declaration]
  | 2024-11-06 23:58:11 EST | [04:58:11]      clock_gettime( CLOCK_REALTIME, &waituntil );
  | 2024-11-06 23:58:11 EST | [04:58:11]      ^~~~~~~~~~~~~
  | 2024-11-06 23:58:11 EST | [04:58:11] __handles.c:1911:20: error: ‘CLOCK_REALTIME’ undeclared (first use in this function)
  | 2024-11-06 23:58:11 EST | [04:58:11]      clock_gettime( CLOCK_REALTIME, &waituntil );
  | 2024-11-06 23:58:11 EST | [04:58:11]                     ^~~~~~~~~~~~~~
  | 2024-11-06 23:58:11 EST | [04:58:11] __handles.c:1911:20: note: each undeclared identifier is reported only once for each function it appears in
  | 2024-11-06 23:58:11 EST | [04:58:11] make[2]: *** [Makefile:871: __handles.lo] Error 1

```

**Comment by ViralBShah** [comment]
@DilumAluthge Is there a problem in a CI script?

**Comment by eschnett** [comment]
For `CLOCK_REALTIME` on Windows: Try `grep` on the Yggdrasil packages. I few packages are applying various kinds of patches. `Notcurses` brings its own header `pthread_time.h` that might help.

**Comment by DilumAluthge** [comment]
Ref https://github.com/JuliaCI/julia-buildkite-plugin/pull/52#issuecomment-2464161910

**Pull request merged**
