### PR TITLE
[SDPA] add methods to sdpawrap.cpp

### PR DESCRIPTION
**Pull request by odow**
I don't really understand what I'm doing, but this looks correct to me.

x-ref https://github.com/jump-dev/SDPA.jl/issues/49

cc @blegat

### CODE REVIEW

**Comment by odow** [comment]
I don't understand the compilation failures with the `(g|s)etDisplay` methods: https://buildkite.com/julialang/yggdrasil/builds/2415#01879757-da46-48be-95fa-15f9f98e69ec

> error: invalid use of incomplete type ‘struct _IO_FILE’

Do we need to handle `FILE*` arguments differently somewhere? The headers for the methods are:
```cpp
void setDisplay(FILE* Display  = stdout);
FILE* getDisplay();
```

**Comment by giordano** [comment]
I don't have much time to look into this, but https://www.openwall.com/lists/musl/2021/10/06/4 is likely relevant.

**Comment by odow** [comment]
@blegat do you want to take a look at this?

**Comment by blegat** [comment]
Maybe we can merge with `getDisplay`/`setDisplay` for now ?

**Comment by ViralBShah** [comment]
Should we merge?

**Comment by blegat** [comment]
No objection from me

**Pull request merged**
