### PR TITLE
[PETSc] Update the compat entry for MUMPS_jll

### PR DESCRIPTION
**Pull request by amontoison**
#7560

### CODE REVIEW

**Comment by amontoison** [comment]
I just changed the compat entry of `MUMPS_jll` and many builds are failing...
I don't think that it's related to my modification.

**Comment by ViralBShah** [comment]
Seems to be unable to find BLAS.

**Comment by ViralBShah** [comment]
Seems like my commits make it worse.

**Comment by amontoison** [comment]
@giordano I wanted to regenerate `PETSc_jll.jl` to add a compat entry for `MUMPS_jll.jl` directly in the `Project.toml` of `PETSc_jll.jl` but it seems that PETSc downloads additional files during the compilation and we can't easily rebuild it with the same setup.
Is it enough if we just add the compat entry in the `General` repository (done with this [PR](https://github.com/JuliaRegistries/General/pull/93917))?

@ViralBShah The idea of this PR was to rebuild `PETSc_jll` without updating the dependencies.
LBT is great but here we need to rebuild a few packages with it before (`SCALAPACK`, `MUMPS`, ...).
It will break a lot of Julia packages because LP64 BLAS / LAPACK must manually loaded and it's what is required here.

**Comment by giordano** [comment]
My understanding of
```
ERROR: LoadError: Unsatisfiable requirements detected for package LazyArtifacts [4af54fe1]:
 LazyArtifacts [4af54fe1] log:
 ├─possible versions are: 1.3.0 or uninstalled
 └─found to have no compatible versions left with MUMPS_jll [ca64183c]
   └─MUMPS_jll [ca64183c] log:
     ├─possible versions are: 5.2.1-5.6.1 or uninstalled
     └─restricted to versions 5.5.1 by an explicit requirement, leaving only versions 5.5.1
```
is that there's something wrong in the registry which has to be fixed.

**Comment by ViralBShah** [comment]
@amontoison Agree. Aplogoes for polluting the PR. Would it be possible for you to revert or force push to get rid of my commits?

**Comment by ViralBShah** [comment]
cc @KristofferC

**Comment by giordano** [comment]
https://github.com/JuliaRegistries/General/pull/92622#issuecomment-1813255248. Same problem as in #7687

**Comment by ViralBShah** [comment]
aarch64 mac libgfortran5 seems to be complaining about unable to link to `divdc3`.

**Comment by giordano** [comment]
https://github.com/JuliaPackaging/Yggdrasil/blob/80da7de30c6632f05b7e15dc9f779ba16111fb32/L/LLVMOpenMP/build_tarballs.jl#L38-L42

**Comment by amontoison** [comment]
#7865 will fix the issue.

**Pull request closed without merging**
