### PR TITLE
[DuckDB] Bump to v0.9.1

### PR DESCRIPTION
**Pull request by jeremiahpslewis**

### CODE REVIEW

**Comment by Mytherin** [comment]
@giordano could you have another look at this one? It should be fixed now.

**Comment by jeremiahpslewis** [comment]
@Mytherin It's probably cleaner to wait a week until v0.9.1 has been tagged, otherwise we have to include a patch you have already upstreamed...

**Comment by Mytherin** [comment]
Alright, fine by me

**Comment by mzy2240** [comment]
is it possible to move forward, as v0.9.1 was released?

**Pull request merged**
