### PR TITLE
Try building Enzyme_jll for Windows and LLVM 16

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Comment by vchuravy** [comment]
@gbarald could you add this to your todo list? Otherwise the users of SciML won't be able to test against v1.11 on Windows

**Comment by vchuravy** [comment]
cc: @gbaraldi 

Apparently I spelled it wrong originally

**Comment by gbaraldi** [comment]
The issue here is supposedly that enzyme is using a internal LLVM symbol, except that there isn't a clear definition of that and it just gets hidden in windows now.

**Comment by vchuravy** [comment]
replaced by #8902

**Pull request closed without merging**
