### PR TITLE
Update to Typst v0.11

### PR DESCRIPTION
**Pull request by jkrumbiegel**

### CODE REVIEW

**Comment by imciner2** [comment]
This looks to be blocked on needing rust 1.74, but we only have 1.73 in the BB environment.

**Comment by giordano** [comment]
I'll try to get to this this week, that's also needed for #8210.

**Comment by giordano** [comment]
```
[13:49:05] error: failed to run custom build command for `openssl-sys v0.9.101`
[13:49:05] 
[13:49:05] Caused by:
[13:49:05]   process didn't exit successfully: `/workspace/srcdir/typst/target/release/build/openssl-sys-fd985cca103da17f/build-script-main` (exit status: 101)
[13:49:05]   --- stdout
[13:49:05]   cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
[13:49:05]   X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
[13:49:05]   cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
[13:49:05]   OPENSSL_LIB_DIR unset
[13:49:05]   cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
[13:49:05]   X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
[13:49:05]   cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
[13:49:05]   OPENSSL_INCLUDE_DIR unset
[13:49:05]   cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
[13:49:05]   X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
[13:49:05]   cargo:rerun-if-env-changed=OPENSSL_DIR
[13:49:05]   OPENSSL_DIR unset
[13:49:05]   cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_x86_64-unknown-linux-gnu
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_x86_64_unknown_linux_gnu
[13:49:05]   cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
[13:49:05]   cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
[13:49:05]   cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
[13:49:05]   cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG
[13:49:05]   cargo:rerun-if-env-changed=OPENSSL_STATIC
[13:49:05]   cargo:rerun-if-env-changed=OPENSSL_DYNAMIC
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
[13:49:05]   cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_PATH
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_PATH
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
[13:49:05]   cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_LIBDIR
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
[13:49:05]   cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
[13:49:05]   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
[13:49:05]   run pkg_config fail: 
[13:49:05]   pkg-config exited with status code 1
[13:49:05]   > PKG_CONFIG_PATH=/workspace/destdir/lib/pkgconfig:/workspace/destdir/lib64/pkgconfig:/workspace/destdir/share/pkgconfig PKG_CONFIG_SYSROOT_DIR=/workspace/destdir PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags openssl
[13:49:05] 
[13:49:05]   The system library `openssl` required by crate `openssl-sys` was not found.
[13:49:05]   The file `openssl.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
[13:49:05]   PKG_CONFIG_PATH contains the following:
[13:49:05]       - /workspace/destdir/lib/pkgconfig
[13:49:05]       - /workspace/destdir/lib64/pkgconfig
[13:49:05]       - /workspace/destdir/share/pkgconfig
[13:49:05] 
[13:49:05]   HINT: you may need to install a package such as openssl, openssl-dev or openssl-devel.
[13:49:05] 
[13:49:05] 
[13:49:05]   --- stderr
[13:49:05]   thread 'main' panicked at /opt/x86_64-linux-musl/registry/src/index.crates.io-6f17d22bba15001f/openssl-sys-0.9.101/build/find_normal.rs:190:5:
[13:49:05] 
[13:49:05] 
[13:49:05]   Could not find directory of OpenSSL installation, and this `-sys` crate cannot
[13:49:05]   proceed without this knowledge. If OpenSSL is installed and this crate had
[13:49:05]   trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
[13:49:05]   compilation process.
[13:49:05] 
[13:49:05]   Make sure you also have the development packages of openssl installed.
[13:49:05]   For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.
[13:49:05] 
[13:49:05]   If you're in a situation where you think the directory *should* be found
[13:49:05]   automatically, please open a bug at https://github.com/sfackler/rust-openssl
[13:49:05]   and include information about your system as well as t
is message.
[13:49:05] 
[13:49:05]   $HOST = x86_64-unknown-linux-musl
[13:49:05]   $TARGET = x86_64-unknown-linux-gnu
[13:49:05]   openssl-sys = 0.9.101
[13:49:05] 
```
Sounds like you now need to add OpenSSL as dep

**Comment by jkrumbiegel** [comment]
haha I tried to add this dependency line 30 seconds after you did...

**Comment by jkrumbiegel** [comment]
@giordano thanks! Can the libiconv warning in the audit log be ignored?

**Comment by giordano** [comment]
Yes and no: I've seen it causing real problems only in limited cases, I'm kinda curious to see if we have more problems in the future.

**Pull request merged**
