### PR TITLE
PROJ build new minor version 6.3.0

### PR DESCRIPTION
**Pull request by visr**
https://github.com/OSGeo/PROJ/releases/tag/6.3.0

### CODE REVIEW

**Comment by visr** [comment]
Hmm 1 is failing, only `powerpc64le-linux-gnu-cxx11`.

[The log](https://dev.azure.com/JuliaPackaging/Yggdrasil/_build/results?buildId=996&view=logs&j=96e13899-1113-51e7-f2eb-5baf97ab30bd&t=f6b3f466-7ca3-5d77-4b23-c4e6f691a575&l=1325) blames `libsqlite`:
```
[14:55:20] /opt/powerpc64le-linux-gnu/bin/../lib/gcc/powerpc64le-linux-gnu/5.2.0/../../../../powerpc64le-linux-gnu/bin/ld: warning: libdl.so.2, needed by /workspace/destdir/lib/libsqlite3.so, not found (try using -rpath or -rpath-link)
[14:55:20] /workspace/destdir/lib/libsqlite3.so: undefined reference to `dlerror@GLIBC_2.17'
[14:55:20] /workspace/destdir/lib/libsqlite3.so: undefined reference to `dlclose@GLIBC_2.17'
[14:55:20] /workspace/destdir/lib/libsqlite3.so: undefined reference to `dlopen@GLIBC_2.17'
[14:55:20] /workspace/destdir/lib/libsqlite3.so: undefined reference to `dlsym@GLIBC_2.17'
[14:55:20] collect2: error: ld returned 1 exit status
```

Not sure what's wrong. The SQLite build is [from Oct 18, 2019](https://github.com/JuliaPackaging/Yggdrasil/pull/144). Maybe it's just time for a new SQLite build with a newer BinaryBuilder? The SQLite version is still the latest.

https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases/tag/SQLite-v3.30.1%2B0

**Comment by giordano** [comment]
New interesting error:
```
[14:55:20] [ 79%] Linking CXX executable ../bin/projinfo
[14:55:20] cd /workspace/srcdir/proj-6.3.0/build/src && /usr/bin/cmake -E cmake_link_script CMakeFiles/binprojinfo.dir/link.txt --verbose=true
[14:55:20] /opt/bin/powerpc64le-linux-gnu-g++ --sysroot=/opt/powerpc64le-linux-gnu/powerpc64le-linux-gnu/sys-root/  -O3 -DNDEBUG   CMakeFiles/binprojinfo.dir/apps/projinfo.cpp.o  -o ../bin/projinfo  -L/workspace/srcdir/proj-6.3.0/build/lib -Wl,-rpath,/workspace/srcdir/proj-6.3.0/build/lib:/workspace/destdir/lib: ../lib/libproj.so.18.0.3 -lm -lpthread /workspace/destdir/lib/libsqlite3.so 
[14:55:20] /opt/powerpc64le-linux-gnu/bin/../lib/gcc/powerpc64le-linux-gnu/5.2.0/../../../../powerpc64le-linux-gnu/bin/ld: warning: libdl.so.2, needed by /workspace/destdir/lib/libsqlite3.so, not found (try using -rpath or -rpath-link)
[14:55:20] /workspace/destdir/lib/libsqlite3.so: undefined reference to `dlerror@GLIBC_2.17'
[14:55:20] /workspace/destdir/lib/libsqlite3.so: undefined reference to `dlclose@GLIBC_2.17'
[14:55:20] /workspace/destdir/lib/libsqlite3.so: undefined reference to `dlopen@GLIBC_2.17'
[14:55:20] /workspace/destdir/lib/libsqlite3.so: undefined reference to `dlsym@GLIBC_2.17'
[14:55:20] collect2: error: ld returned 1 exit status
[14:55:20] make[2]: *** [src/CMakeFiles/binprojinfo.dir/build.make:86: bin/projinfo] Error 1
```

**Comment by giordano** [comment]
[`RootFS.md`](https://github.com/JuliaPackaging/Yggdrasil/blob/e4bb29c1faab43db92fcbae72f23bd5680476b88/RootFS.md#glibc-versions), which however is not very up-to-date, says that PowerPC uses glibc 2.25, indeed I can see these symbols in libsqlite:
```
shell> nm $(SQLite_jll.libsqlite_path)
[...]
                 U write@@GLIBC_2.2.5
[...]
                 U __xstat64@@GLIBC_2.2.5
[...]
```
There have been changes to PowerPC recently, maybe the glibc version associated with it changed, so yes, this package may require a new build, but Elliot can tell us more.

**Comment by giordano** [comment]
While we are at it, maybe you can replace
```
cmake --build .
```
with
```
make -j${nproc}
```
?  This slightly speeds up compilation.

**Comment by visr** [comment]
Unfortunately using a freshly baked [SQLite_jll v3.30.1+1](https://github.com/JuliaBinaryWrappers/SQLite_jll.jl/releases/tag/SQLite-v3.30.1%2B1) did not resolve the issue. Perhaps @staticfloat has a clue what's wrong with the `powerpc64le-linux-gnu-cxx11` build.

**Comment by giordano** [comment]
Now that I reread my message, it doesn't make any sense: I used for testing SQLite for my architecture, which isn't PowerPC.

Looking better also to the error message I think you may need to link against libdl, so that you need to add `-ldl` to the command line invocation, for example by adding `dl` to the `CMAKE_REQUIRED_LIBRARIES` at line 148 of the CMake file:
```cmake
set(CMAKE_REQUIRED_LIBRARIES dl m)
```

**Comment by visr** [comment]
Ah ok, thanks. This is the first time I'm creating such a patch, so I just tried copying from the other examples. Is a workflow for how to create and apply these patches documented somewhere?

Locally this fixed `powerpc64le-linux-gnu-cxx11` for me :)

**Comment by giordano** [comment]
> Is a workflow for how to create and apply these patches documented somewhere?

https://juliapackaging.github.io/BinaryBuilder.jl/dev/build_tips/#Editing-files-in-the-wizard-1 but that's just one way of doing it. I have a completely different workflow, which I don't know if I want to document because it's extremely convoluted and inefficient, I don't think anyone would benefit from knowing it

**Comment by giordano** [comment]
Sorry, I was expecting that CMake could do something reasonable, what a blunder.  I went ahead and worked around with a more direct setting.

**Pull request merged**
