### PR TITLE
[GDAL] Make sure we link to GEOS and SQLite3

### PR DESCRIPTION
**Pull request by giordano**
In #418 it was reported that GDAL in some cases doesn't actually link against GEOS.  For the time being, this PR just checks for which platforms this happens, then we'll figure out what to do.

CC: @visr

### CODE REVIEW

**Comment by giordano** [comment]
It's rather interesting that `x86_64-linux-musl` is the only Linux platform that can doesn't have problems

**Comment by giordano** [comment]
We're getting there

**Comment by giordano** [comment]
@visr good to go?

**Comment by visr** [comment]
Yeah looks great, thanks! Do you think these patches can be upstreamed as-is, including `EXTRA_GEOS_LIBS` and `EXTRA_SQLITE3_LIBS`?

**Comment by giordano** [comment]
We definitely need a mechanism to pass extra libraries when configuring the library and while dropping the patches would be great (less maintenance work, I'm not proud of them, they're quick hacks to make things work. Maybe this is still worth opening an issue for the upstream project?

**Pull request merged**
