### PR TITLE
[BlueZ] Actually build the library

### PR DESCRIPTION
**Pull request by bramtayl**

### CODE REVIEW

**Comment by bramtayl** [comment]
Hmm, that version doesn't seem to be compatible with the other dependencies?

**Comment by giordano** [comment]
Should be fixed by #3075

**Comment by bramtayl** [comment]
Well, I see the Ncurses BinaryWrappers was updated 20 hours ago...so maybe #3075 didn't do the trick?

**Comment by giordano** [comment]
> so maybe #3075 didn't do the trick?

..._cough cough_...

**Comment by bramtayl** [comment]
Thanks! What's the coughing for?

**Comment by giordano** [comment]
Well, #3075 _did_ the trick despite what you thought

**Pull request merged**
