### PR TITLE
Add compilation support for FastTransforms on MacOS AArch64

### PR DESCRIPTION
**Pull request by abhayap**

### CODE REVIEW

**Comment by giordano** [comment]
As explained in #2763, if you change the compatibility of Julia you _*MUST*_ also change the version number

**Comment by abhayap** [comment]
@giordano I'll update the version number. I'm still new to all this so I'm  just getting used to the requirements. What is the recommended version to use if the base library is still on the same version?

**Comment by giordano** [comment]
And when changing the compatibility bound of Julia, it'd be better to ask the maintainer of the package, to make sure this doesn't break anything, although with v1.6 now the LTS, that should hopefully not be a big deal. CC @MikaelSlevinsky

**Comment by MikaelSlevinsky** [comment]
Hi, it looks like maybe the Aarch64 builds can be fixed by removing the case exception in the redefinition of the BLAS symbols.

https://github.com/JuliaPackaging/Yggdrasil/blob/254d465c532ee33905405af000b6dfc6691c4a70/F/FastTransforms/build_tarballs.jl#L28

could look like `if [[ ${nbits} == 64 ]]; then`.

**Comment by giordano** [comment]
OpenBLAS on aarch64 is complicated: we do ILP64 for Julia v1.7, but not v1.6, this means we can't possibly have a single library for both versions of Julia linking to 64-bit OpenBLAS.  I'm looking into available options.

**Comment by abhayap** [comment]
Thanks @MikaelSlevinsky. That worked. I made the minimum required version of Julia v1.7 because I see that OpenBLAS 0.3.17 had that requirement. I wanted to compile this for Apple's M1 processor which needs Julia v1.7 anyway.

**Comment by abhayap** [comment]
@MikaelSlevinsky I ran the tests in FastTransforms.jl on my M1 MacBook Pro with Julia v1.7 using the library here https://github.com/abhayap/FastTransforms_jll and they all passed.

```
Test Summary:     | Pass  Total
Special functions |   19     19
Test Summary:       | Pass  Total
Chebyshev transform |  369    369
Test Summary:                        | Pass  Total
Fejér and Clenshaw–Curtis quadrature |    9      9
Test Summary:     | Pass  Total
libfasttransforms |  311    311
Test Summary:                      | Pass  Broken  Total
Nonuniform fast Fourier transforms |  248       4    252
Test Summary:        | Pass  Total
BigFloat FFT and DCT |  140    140
Test Summary:                   | Pass  Total
Padua transform and its inverse |   10     10
Test Summary:      | Pass  Total
Gaunt coefficients |   36     36
Test Summary: | Pass  Total
Hermite       |   17     17
Test Summary:     | Pass  Total
BigFloat Toeplitz |    6      6
Test Summary: | Pass  Total
clenshaw      |   63     63
Test.DefaultTestSet("clenshaw", Any[Test.DefaultTestSet("Chebyshev T", Any[Test.DefaultTestSet("Strided", Any[], 3, false, false), Test.DefaultTestSet("matrix coefficients", Any[], 2, false, false), Test.DefaultTestSet("Strided", Any[], 3, false, false), Test.DefaultTestSet("matrix coefficients", Any[], 2, false, false)], 14, false, false), Test.DefaultTestSet("Chebyshev U", Any[Test.DefaultTestSet("forwardrecurrence!", Any[], 3, false, false), Test.DefaultTestSet("matrix coefficients", Any[], 2, false, false)], 1, false, false), Test.DefaultTestSet("Chebyshev-as-general", Any[Test.DefaultTestSet("forwardrecurrence!", Any[], 3, false, false)], 6, false, false), Test.DefaultTestSet("Legendre", Any[Test.DefaultTestSet("Float64", Any[], 18, false, false), Test.DefaultTestSet("BigFloat", Any[], 1, false, false)], 0, false, false), Test.DefaultTestSet("Int", Any[], 3, false, false), Test.DefaultTestSet("Zeros diagonal", Any[], 2, false, false)], 0, false, false)
```

**Comment by MikaelSlevinsky** [comment]
Cool!

**Comment by giordano** [comment]
@MikaelSlevinsky there are [some changes](https://github.com/MikaelSlevinsky/FastTransforms/compare/v0.5.1...master), since last release, would you be able to tag a new release perhaps? That'd make it easier to change the version number of this recipe.

Also, would you be OK with requiring Julia v1.7 for this jll package? I'm OK with that, but you're the maintainer of the package which uses it, so I want to make sure _you_ are OK with this change.

**Comment by MikaelSlevinsky** [comment]
Sure, @giordano, I just tagged v0.5.2. I guess that means, @abhayap, that the top version variable here can be redefined and the bottom one (and text) can be deleted.

I'm fine with Julia v1.7 since this _jll version will increase portability (it doesn't sound like there's really a realistic second option). Does that mean that Julia v1.6 (and lesser versions) can still use old _jll's?

**Comment by abhayap** [comment]
Thanks for the reviews @MikaelSlevinsky and @giordano! I think this is ready to go.

**Comment by giordano** [comment]
> I'm fine with Julia v1.7 since this _jll version will increase portability (it doesn't sound like there's really a realistic second option). 

There is a second option, but not very realistic right now.

> Does that mean that Julia v1.6 (and lesser versions) can still use old _jll's?

Yes, previous versions will still continue to work regularly.  The only problem is that going forward new versions of this JLL will all require Julia v1.7, and this is what I want to make sure you're OK with.

**Comment by MikaelSlevinsky** [comment]
Execute [Order No. 227](https://en.m.wikipedia.org/wiki/Order_No._227)

**Pull request merged**
