### PR TITLE
Scip bump

### PR DESCRIPTION
**Pull request by matbesancon**

### CODE REVIEW

**Comment by matbesancon** [comment]
fixing last comment

**Comment by giordano** [comment]
No changes?

**Comment by matbesancon** [comment]
That's weird, https://github.com/JuliaPackaging/Yggdrasil/pull/2290/commits/63d31e8e78b8ee8f470b0ce0ebe0daab81470d4a should fix the version syntax?

**Comment by matbesancon** [comment]
oh wait, you did that in another PR, got it thanks

**Pull request closed without merging**
