### PR TITLE
Wizard recipe: SDL2_gfx-v1.0.3

### PR DESCRIPTION
**Pull request by aviks**
This pull request contains a new build recipe I built using the BinaryBuilder.jl wizard:

* Package name: SDL2_gfx
* Version: v1.0.3

@staticfloat please review and merge.

### CODE REVIEW

**Comment by giordano** [comment]
Looks like they're expecting only x86 architectures

**Comment by giordano** [comment]
Should now work for ARM architectures, still need to fix some problems on PowerPC and FreeBSD

**Comment by aviks** [comment]
Thanks! There seem to be some linker errors on windows that I also do not understand.

**Comment by giordano** [comment]
I have the feeling that the remaining issues are all related to the very old build system of the package.  If only we were able to rebuild the `configure` script...

**Comment by giordano** [comment]
I didn't want to spend further time on investigating the problem and since this is very simple I just went with manually building the shared library out of the static archive.

**Comment by giordano** [comment]
For the record, most of the issues we found here are similar to what we had in #123.  Also for Windows, the link problem is the same as the one reported in https://github.com/JuliaPackaging/Yggdrasil/pull/123#issuecomment-546605808, and also the solution was the same: [manually build the shared library](https://github.com/JuliaPackaging/Yggdrasil/pull/123#issuecomment-569425127).

**Pull request merged**
