### PR TITLE
Wizard recipe: util_linux-v2.35.0

### PR DESCRIPTION
**Pull request by bramtayl**
This pull request contains a new build recipe I built using the BinaryBuilder.jl wizard:

* Package name: util_linux
* Version: v2.35.0

@staticfloat please review and merge.

### CODE REVIEW

**Comment by bramtayl** [comment]
Only built on Linux. I used 2.35 instead of 2.36 to get around O_PATH not being defined in musl

**Comment by bramtayl** [comment]
@staticfloat sorry to bother you again. Would it be possible to merge the 2.35 version (it can't be that different from 2.36?) for now so I can get on with building udev, and worry about the version compatibility later?

**Comment by staticfloat** [comment]
This PR seems to still be building 2.36, and it also doesn't work.  Do you have a different version somewhere?

**Comment by bramtayl** [comment]
I think the first commit was 2.35 and the second was 2.36, but I can't figure out how to revert a commit on github so I just copied and pasted it back

**Comment by staticfloat** [comment]
That's a crazy number of products, nice!

**Review by staticfloat — APPROVED** [review]

**Comment by giordano** [comment]
I assume this won't build for FreeBSD, right?

**Comment by bramtayl** [comment]
Thanks everyone! Thank the folks over at Linux for all the products.

**Comment by bramtayl** [comment]
Good to go?

**Pull request merged**
