### PR TITLE
[Geant4_julia]: Added new package with CxxWrap wrappers for Geant4 

### PR DESCRIPTION
**Pull request by peremato**
Added new package with CxxWrap wrappers for Geant4

### CODE REVIEW

**Comment by giordano** [comment]
* The name is fine, I don't know why that check is enabled for jlls, I honestly thought that would have been skipped
* the error I see in https://github.com/JuliaRegistries/General/actions/runs/4603423325/jobs/8133415698?pr=80960#step:16:353 is
  ```
  libG4ToolsSG.so: cannot open shared object file: No such file or directory
  ```
  but `libG4ToolsSG` isn't a product in [Geant4 recipe](https://github.com/JuliaPackaging/Yggdrasil/blob/e3bd44f46a3959dd3e55a88dc930718cbdec0667/G/Geant4/build_tarballs.jl).  If you need that, it has to be listed as a `LibraryProduct` explicitly, so that we can dlopen it automatically when loading Geant4

**Comment by peremato** [comment]
Thanks very much. Question, once I add the missing `LibraryProduct` in the recipe do I need to change the version for new PR?

**Comment by giordano** [comment]
No, it isn't necessary for just listing more products.  You may want to make sure that all geant4 libraries required by your wrapper are listed as products:
```console
shell> readelf -d ~/.julia/artifacts/94e2be9aeb96002d2b0c84100d9346dceafb5382/lib/libGeant4Wrap.so

Dynamic section at offset 0xf1eeb8 contains 72 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libcxxwrap_julia_stl.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4Tree.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4FR.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4GMocren.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4visHepRep.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4RayTracer.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4VRML.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4ToolsSG.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4vis_management.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4modeling.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4interfaces.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4persistency.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4error_propagation.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4readout.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4physicslists.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4run.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4event.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4tracking.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4parmodels.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4processes.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4digits_hits.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4track.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4particles.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4geometry.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4materials.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4graphics_reps.so]
 0x0000000000000001 (NEEDED)             Shared library: [libcxxwrap_julia.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libjulia.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libGL.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libXmu.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXext.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXt.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libICE.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libSM.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libxerces-c-3.2.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4analysis.so]
 0x0000000000000001 (NEEDED)             Shared library: [libexpat.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libG4zlib.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4intercoms.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4global.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4clhep.so]
 0x0000000000000001 (NEEDED)             Shared library: [libG4ptl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [libGeant4Wrap.so]
```

**Comment by peremato** [comment]
The change in the recipe is done and the PR https://github.com/JuliaPackaging/Yggdrasil/pull/6521 is ready to be merged.

**Pull request merged**
