### PR TITLE
[New package] Add ROCmCompilerSupport 4.0.0

### PR DESCRIPTION
**Pull request by jpsamaroo**
In theory I don't need LLVM_full, but the other LLVM packages don't have LLD, which is needed for this package.

### CODE REVIEW

**Comment by jpsamaroo** [comment]
I'm not sure I understand the cxx03 errors, and the glibc cxx11 segfault seems to be related to loading two different LLVM libraries at once (since libamd_comgr.so loads the LLVM from LLVM_full_jll).

**Comment by jpsamaroo** [comment]
I guess the cxx03 issue is here: https://github.com/RadeonOpenCompute/ROCm-CompilerSupport/blob/5932ed5770b26c23367423a7bf8797856cd0c34a/lib/comgr/CMakeLists.txt#L185. They expect cxx14, and I suppose cxx11 is the only standard recent enough to support what they actually use?

**Comment by giordano** [comment]
C++ string ABI doesn't have to do with the C++ standard used by the source code: https://docs.binarybuilder.org/stable/building/#Expanding-C-string-ABIs-or-libgfortran-versions

**Comment by jpsamaroo** [comment]
Thanks for the info! I figured it was the `cxxstring_abi` option since all the errors in cxx03 CI were from things related to `std::string`.

**Comment by jpsamaroo** [comment]
We'll be skipping cxx03 for right now, but we can investigate fixing it when users run into it

**Comment by jpsamaroo** [comment]
I find it odd that the auditor hits an assertion on Yggdrasil, but it doesn't happen for me locally. Is the auditor run in the build environment or outside of it?

**Comment by giordano** [comment]
Do you run on `x86_64-linux-musl`?  If so, that's relevant, because loading the library is done only for the host platform, which would be different between you and Yggdrasil

**Comment by jpsamaroo** [comment]
Ok I see, I'll re-add `dont_dlopen=true`

**Comment by jpsamaroo** [comment]
IMO this is good to go.

**Pull request merged**
