### PR TITLE
Gettext: Update to 0.22.0

### PR DESCRIPTION
**Pull request by eschnett**

### CODE REVIEW

**Comment by giordano** [comment]
The patch we're applying when building for Windows is probably unneeded now.

**Comment by eschnett** [comment]
On Windows we see the build error
```
     undefined reference to `close_used_without_requesting_gnulib_module_close'
```
The respective discussion at <https://lists.gnu.org/r/bug-gettext/2023-06/msg00059.html> shows that cross-compiling for Windows with our setup isn't supported, and that there isn't any real effort by the maintainers to remedy this problem. We thus disable Windows.

**Comment by eschnett** [comment]
Yes, the patch is not necessary any more, and I have removed it.

**Comment by giordano** [comment]
I just realised this is a duplicate of #6950.  Unfortunately removing Windows will break [all binaries currently linking to gettext](https://juliahub.com/ui/Packages/General/Gettext_jll), like `Git_jll` and `Glib_jll`, besides `Gettext.jl` :confused:  CC: @stevengj

**Comment by stevengj** [comment]
I don't have any particular insight here.  Someone with mingw installed locally and some patience would have to dig around for a workaround.   But I don't think it's good to simply omit Windows.

**Comment by stevengj** [comment]
But I think this PR should be closed in favor of https://github.com/JuliaPackaging/Yggdrasil/pull/6950, which has some additional fixes to the exports.

**Comment by eschnett** [comment]
Closing in favour of #6950.

**Pull request closed without merging**
