### PR TITLE
[oneTBB] Version bump

### PR DESCRIPTION
**Pull request by jeremiahpslewis**
- Expand build to all platforms

### CODE REVIEW

**Comment by giordano** [comment]
For future reference [the error](https://buildkite.com/julialang/yggdrasil/builds/261#0185cc24-54ab-4e65-ae39-a7dcefec377e/625-821) is
```
[22:57:00] In file included from /workspace/srcdir/oneTBB/src/tbb/../../include/oneapi/tbb/detail/_utils.h:26:0,
[22:57:00]                  from /workspace/srcdir/oneTBB/src/tbb/../../include/oneapi/tbb/detail/_template_helpers.h:20,
[22:57:00]                  from /workspace/srcdir/oneTBB/src/tbb/exception.cpp:19:
[22:57:00] /workspace/srcdir/oneTBB/src/tbb/../../include/oneapi/tbb/detail/_machine.h:247:56: error: ‘_MCW_DN’ was not declared in this scope
[22:57:00]      static constexpr unsigned int X87CW_CONTROL_MASK = _MCW_DN | _MCW_EM | _MCW_RC;
[22:57:00]                                                         ^
```
The problem is that `__STRICT_ANSI__` is defined, which prevents `_MCW_DN` from being defined (the latter is conditionally defined in `<float.h>` only if the former is undefined).

**Comment by giordano** [comment]
That was the point of [the lines](https://github.com/oneapi-src/oneTBB/blob/ba0cc2e0f92c56c529c25e9e23a00361bdb8b59b/cmake/compilers/GNU.cmake#L62-L64)
```cmake
if (MINGW)
    list(APPEND TBB_COMMON_COMPILE_FLAGS -U__STRICT_ANSI__)
endif()
```
which for some reasons have been removed in https://github.com/oneapi-src/oneTBB/blob/7673da272f7e1592876b42cfe98b9f4cadf6ae41/cmake/compilers/GNU.cmake

**Comment by giordano** [comment]
After that you'd run into the error
```
In file included from /workspace/srcdir/oneTBB/src/tbb/concurrent_monitor_mutex.h:22:0,
                 from /workspace/srcdir/oneTBB/src/tbb/concurrent_monitor.h:23,
                 from /workspace/srcdir/oneTBB/src/tbb/address_waiter.cpp:19:
/workspace/srcdir/oneTBB/src/tbb/semaphore.h: In member function ‘void tbb::detail::r1::semaphore::init_semaphore(size_t)’:
/workspace/srcdir/oneTBB/src/tbb/semaphore.h:145:113: error: ‘CreateSemaphoreEx’ was not declared in this scope
         sem = CreateSemaphoreEx( nullptr, LONG(start_cnt_), max_semaphore_cnt, nullptr, 0, SEMAPHORE_ALL_ACCESS );
                                                                                                                 ^
compilation terminated due to -Wfatal-errors.
```
which is due to the fact that this function [requires](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsemaphoreexa#requirements) Windows Server 2008, so you have to set `_WIN32_WINNT` accordingly.

**Comment by jeremiahpslewis** [comment]
@giordano Thanks for the pointers! Got x86 windows back up and running.

**Comment by giordano** [comment]
Closing and reopening will not do anything good.

**Pull request merged**
